import {Scene} from './scene.mjs';
import {CyberRoom} from './network.mjs';
import {makeSession,questionFor,answer,useSkill,tick,next,summary,validSnapshot,KINDS,LEVELS} from './core.mjs';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const STORE='aitech-neon-learning-v1',scene=new Scene($('scene'));let bank,byId,state=null,mode='local',room=null,peerReady=false,pending=null,lastTick=Date.now(),renderKey='',sound=false,audioCtx=null,codexPage=0,codexText='',codexStatus='all',codexCategory='all';const recorded=new Set();let progress=loadProgress();
function loadProgress(){try{const v=JSON.parse(localStorage.getItem(STORE)||'{}');return v&&typeof v==='object'&&!Array.isArray(v)?v:{};}catch{return{};}}
function saveLearning(){if(!state)return;const latest=loadProgress();for(const h of state.history){const key=state.id+':'+h.round;if(recorded.has(key))continue;recorded.add(key);for(const r of h.results){if(mode==='online'&&r.side!==room?.side)continue;const p=latest[r.id]||{seen:0,correct:0,wrong:0,streak:0};p.seen++;if(r.correct){p.correct++;p.streak++;}else{p.wrong++;p.streak=0;}p.updated=Date.now();latest[r.id]=p;}}progress=latest;try{localStorage.setItem(STORE,JSON.stringify(latest));}catch{$('play-status').textContent='このブラウザーでは学習記録を保存できません。ゲームは続けられます。';}}
function beep(kind){if(!sound)return;try{audioCtx??=new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume();const notes=kind==='overdrive'?[440,660,880,1320]:kind==='link'?[392,587,784]:kind==='hurt'?[160,110]:[440,660];notes.forEach((f,i)=>{const o=audioCtx.createOscillator(),g=audioCtx.createGain(),t=audioCtx.currentTime+i*.08;o.type='triangle';o.frequency.setValueAtTime(f,t);g.gain.setValueAtTime(.035,t);g.gain.exponentialRampToValueAtTime(.001,t+.16);o.connect(g);g.connect(audioCtx.destination);o.start(t);o.stop(t+.18);});}catch{sound=false;$('sound').textContent='音 OFF';}}
function setMode(value){if(room)return;mode=value;document.querySelectorAll('[data-mode]').forEach(b=>{const yes=b.dataset.mode===mode;b.classList.toggle('selected',yes);b.setAttribute('aria-pressed',String(yes));});$('online-box').hidden=mode!=='online';updateLobby();}
function updateLobby(){const online=mode==='online';$('start').textContent=online?(room?.side===1?'ホストの出撃を待機':peerReady?'2人で出撃する →':'相棒の合流を待機'):mode==='solo'?'1人で出撃する →':'2人で出撃する →';$('start').disabled=!bank||(online&&(!room||!peerReady||room.side!==0));for(const id of ['category','difficulty','question-mode'])$(id).disabled=Boolean(room&&room.side===1);for(const b of document.querySelectorAll('[data-mode]'))b.disabled=Boolean(room);$('create-room').disabled=Boolean(room);$('join-form').querySelector('button').disabled=Boolean(room);$('room-input').disabled=Boolean(room);$('room-info').hidden=!room?.joined;$('leave-room').hidden=!room?.joined;if(room?.code)$('room-code').textContent=room.code;$('setup-status').textContent=bank?'1作戦内の重複出題なし。2回続けて正解すると「習得」になります。':'問題を読み込み中…';}
function options(){return{mode,category:$('category').value,difficulty:$('difficulty').value,questionMode:$('question-mode').value};}
function launch(){if(!bank)return;if(mode==='online'&&(!peerReady||room?.side!==0))return;const s=makeSession(bank,options(),progress);if(!s){$('setup-status').textContent='この範囲には復習対象がありません。出題モードかエリアを変更してください。';return;}state=s;pending=null;renderKey='';lastTick=Date.now();render();sendState();if(innerWidth<721)$('play').scrollIntoView({behavior:'smooth',block:'start'});}
function sendState(){if(room?.side===0&&state&&room.ready)room.broadcast('state',{state,bankVersion:bank.version});}
function action(type,side,value){if(!state)return;if(mode==='online'){if(!room?.ready||!peerReady)return;if(room.side===1){if(side!==1&&type!=='pause')return;const body={session:state.id,round:state.round,type,side:1,value};if(type==='answer')pending=body;room.broadcast('action',body);renderKey='';render();return;}}
 applyAction({session:state.id,round:state.round,type,side,value});}
function applyAction(a){if(!state||a.session!==state.id||a.round!==state.round)return;let changed=false;const old=state.phase;if(a.type==='answer')changed=answer(state,a.side,a.value,byId);if(a.type==='skill')changed=useSkill(state,a.side);if(a.type==='pause'&&state.phase==='question'&&typeof a.value==='boolean'){state.paused=a.value;state.pauseReason=a.value?'manual':'';state.revision++;changed=true;}if(changed){if(old==='question'&&state.phase==='result')onOutcome();render();sendState();}}
function onOutcome(){saveLearning();const o=state.outcome;const effect=o.overdrive?'overdrive':o.link?'link':o.correct?'hit':'hurt';scene.hit(effect);beep(effect);}
function renderStats(){const single=state?.players===1||!state&&mode==='solo';$('combo-label').textContent=single?'STREAK':'LINK COMBO';$('combo-description').textContent=single?'連続正解で記録を伸ばそう':'2人とも正解で連携攻撃';const learned=Object.values(progress).filter(x=>x.streak>=2).length;$('mastery').textContent=`習得 ${learned} / 1,000問`;if(!state){$('hp-text').textContent='100 / 100';$('hp-bar').style.width='100%';$('boss-text').textContent='待機中';$('boss-bar').style.width='100%';$('combo').textContent='× 0';$('score').textContent='000000';scene.set(null);return;}const cat=bank.categories.find(c=>c.id===state.category);$('sector-label').textContent=cat?`SECTOR ${String(bank.categories.indexOf(cat)+1).padStart(2,'0')} / ${cat.en}`:'ALL SECTORS / CYBER DEFENSE';$('hp-text').textContent=state.hp+' / 100';$('hp-bar').style.width=state.hp+'%';$('boss-text').textContent=state.boss===0?'コア無力化':state.boss+' / '+state.bossMax;$('boss-bar').style.width=state.boss/state.bossMax*100+'%';$('combo').textContent='× '+state.combo;$('score').textContent=String(state.score).padStart(6,'0');$('wave-label').textContent=state.phase==='finished'?'作戦終了':state.round+1===state.rounds?'FINAL / BOSS':'WAVE '+String(state.round+1).padStart(2,'0');$('battle-call').textContent=state.paused?'作戦を一時停止しています':state.phase==='result'?(state.outcome.overdrive?'OVERDRIVE! 連携必殺技':state.outcome.link?'LINK ATTACK! 2人の知識がつながった':state.outcome.correct?'THREAT DAMAGED / 解説を確認しよう':'DEFENSE ALERT / 次の判断につなげよう'):state.round+1===state.rounds?'BOSS INCOMING / 最後の防衛線':'TRACE × PATCH / 相棒と都市を守れ';scene.set(state);updateClock();}
function updateClock(){$('time').textContent=state?.limit===null?'∞':String(Math.ceil((state?.remaining??45000)/1000));}
function render(){renderStats();$('lobby').hidden=Boolean(state);$('play').hidden=!state||state.phase==='finished';$('summary').hidden=!state||state.phase!=='finished';if(!state){updateLobby();return;}saveLearning();if(state.phase==='finished'){renderSummary();return;}const key=[state.id,state.revision,mode,room?.side,pending?.value,peerReady].join(':');if(key===renderKey)return;renderKey=key;$('round-title').textContent=`${state.round+1===state.rounds?'BOSS ROUND':'ROUND '+String(state.round+1).padStart(2,'0')} / ${String(state.rounds).padStart(2,'0')}`;$('pause').textContent=state.paused?'再開する':'一時停止';$('pause').disabled=state.phase!=='question'||(mode==='online'&&!peerReady);$('questions').classList.toggle('solo',state.players===1);$('questions').innerHTML=Array.from({length:state.players},(_,p)=>renderQuestion(p)).join('');const resolved=state.phase==='result';$('result').hidden=!resolved;if(resolved){const o=state.outcome;const label=o.overdrive?'OVERDRIVE / 連携必殺技！':o.link?'LINK ATTACK / 2人とも正解！':o.wrong===0?'正解！':`${o.correct}問正解 / 解説で取り戻そう`;$('result').innerHTML=`<div><strong>${label}</strong><p>脅威へ ${o.damage} ダメージ · ${o.shield?'シールドで被害を防いだ':'都市への被害 '+o.hurt} · 解説を読んでから進めます。</p></div>${mode==='online'&&room?.side===1?'<p>ホストが進めるのを待っています。</p>':`<button class="primary" data-next>${state.hp<=0||state.round+1>=state.rounds?'作戦結果へ':'次のラウンド →'}</button>`}`;}$('play-status').textContent=state.paused?(state.pauseReason==='network'?'相棒との通信を確認中。再接続すると再開します。':'一時停止中です。「再開する」で続けられます。'):mode==='online'?(peerReady?'接続中 · 自分の担当欄から回答してください。':'相棒との接続を確認しています。'):state.players===2?'PC：TRACEは1–4、PATCHは7–0。スマホ：それぞれの欄をタップ。':'PCは1–4、スマホは選択肢をタップ。';}
function renderQuestion(p){const q=questionFor(state,p,byId),trace=p===0,own=mode!=='online'||room?.side===p,resolved=state.phase==='result';if(!q)return`<article class="question-card ${trace?'':'patch'}"><div class="player-head"><b>${trace?'TRACE':'PATCH'}</b></div><p>このラウンドは相棒をサポートしよう。</p></article>`;const picked=state.answers[p],waiting=mode==='online'&&p===1&&pending?.round===state.round&&pending?.session===state.id;const locked=!own||state.paused||picked!==null||resolved||waiting||(mode==='online'&&!peerReady);const keys=trace?['1','2','3','4']:['7','8','9','0'];const hidden=state.hint&&trace?q.options.map((_,i)=>i).filter(i=>i!==q.correct).slice(0,Math.max(1,q.options.length-2)):[];const cat=bank.categories.find(c=>c.id===q.category);const choice=waiting?pending.value:picked;
 return`<article class="question-card ${trace?'trace':'patch'}" data-player="${p}"><div class="player-head"><b>${trace?'01 / TRACE':'02 / PATCH'} <span>${trace?'解析担当':'防御担当'}</span></b><span>${own?'あなたの操作':'相棒の操作'}</span></div><p class="q-tags">${esc(cat?.name)} · ${KINDS[q.kind]} · ${LEVELS[q.level]} <span> #${esc(q.id)}</span></p><h3 class="prompt">${esc(q.prompt)}</h3>${state.hint&&trace?'<p class="hint">TRACE SCAN：誤った選択肢を除外しました。</p>':''}<div class="answers">${q.options.map((label,i)=>`<button class="answer${!resolved&&choice===i?' selected':''}${resolved&&i===q.correct?' correct':''}${resolved&&choice===i&&choice!==q.correct?' wrong':''}${hidden.includes(i)?' dim':''}" data-answer="${i}" data-side="${p}" ${locked||hidden.includes(i)?'disabled':''}><span class="key">${keys[i]}</span><span>${esc(label)}</span>${resolved&&i===q.correct?' <span aria-label="正解">✓</span>':''}</button>`).join('')}</div><div class="locked"><span>${resolved?(picked===q.correct?'✓ 正解':picked===-1?'時間切れ':'不正解'):waiting?'送信中…':picked!==null?'✓ 回答を確定しました':state.paused?'一時停止中':own?'相談してから答えてもOK':'相棒が回答します'}</span><button class="skill" data-skill="${p}" ${locked||state.skills[p]?'disabled':''}>${trace?'解析ヒント':'防御シールド'} ${state.skills[p]?'使用済み':'×1'}</button></div>${!trace&&state.shield?'<p class="hint">このラウンドの都市への被害を防ぎます。</p>':''}${resolved?`<div class="explanation"><b>正解：${esc(q.options[q.correct])}</b><p>${esc(q.explanation)}</p><a href="${esc(q.source)}" target="_blank" rel="noopener noreferrer">参考：${esc(q.sourceTitle)} ↗</a></div>`:''}</article>`;
}
function renderSummary(){const d=summary(state);$('summary').innerHTML=`<p class="eyebrow">OPERATION ${state.won?'COMPLETE':'REPORT'}</p><div class="rank">${d.rank}</div><h2>${state.won?'作戦成功。ネオンシティを守り切った。':state.hp<=0?'防衛線が突破された。もう一度挑もう。':'脅威が残っている。学んだ知識で再挑戦。'}</h2><p>${state.won?'相棒とつないだ正解が、都市の盾になった。':'間違えた問題は復習モードで練習できます。'}</p><div class="summary-grid"><div><strong>${d.correct} / ${d.total}</strong><span>正解数 · ${d.accuracy}%</span></div><div><strong>${state.bestCombo}</strong><span>最大連続正解ラウンド</span></div><div><strong>${state.score.toLocaleString()}</strong><span>チームスコア</span></div></div><div class="summary-actions">${mode!=='online'||room?.side===0?'<button class="primary" data-retry>新しい問題で再出撃 →</button>':'<p>ホストの再出撃を待っています。</p>'}<button data-lobby>作戦選択に戻る</button></div>${d.misses.length?`<details><summary>今回間違えた ${d.misses.length} 問を確認する</summary><ul class="review-list">${d.misses.map(r=>{const q=byId.get(r.id);return`<li><strong>${esc(q.term)} / ${KINDS[q.kind]}</strong>${esc(q.explanation)}</li>`;}).join('')}</ul></details>`:''}`;}
function showModal(title,html){$('modal-title').textContent=title;$('modal-body').innerHTML=html;if(!$('modal').open)$('modal').showModal();}
function openCodex(){if(!bank)return;showModal('問題図鑑 / この端末の学習記録',`<p>全1,000問を確認できます。同じ問題に2回連続で正解すると習得。オンラインでは自分の回答をこの端末に記録します。</p><div class="codex-filter"><label>キーワード<input id="codex-search" type="search" placeholder="XSS、暗号、バックアップ…" value="${esc(codexText)}"></label><label>分野<select id="codex-cat"><option value="all">全20分野</option>${bank.categories.map(c=>`<option value="${c.id}" ${codexCategory===c.id?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label><label>状態<select id="codex-status"><option value="all">すべて</option><option value="wrong" ${codexStatus==='wrong'?'selected':''}>復習対象</option><option value="mastered" ${codexStatus==='mastered'?'selected':''}>習得済み</option><option value="unseen" ${codexStatus==='unseen'?'selected':''}>未回答</option></select></label></div><div id="codex-list"></div>`);renderCodex();$('codex-search').oninput=e=>{codexText=e.target.value;codexPage=0;renderCodex();};$('codex-cat').onchange=e=>{codexCategory=e.target.value;codexPage=0;renderCodex();};$('codex-status').onchange=e=>{codexStatus=e.target.value;codexPage=0;renderCodex();};}
function renderCodex(){const needle=codexText.toLocaleLowerCase(),list=bank.questions.filter(q=>(codexCategory==='all'||q.category===codexCategory)&&(!needle||(q.term+' '+q.prompt).toLocaleLowerCase().includes(needle))).filter(q=>codexStatus==='all'||codexStatus==='wrong'&&progress[q.id]?.wrong&&progress[q.id]?.streak<2||codexStatus==='mastered'&&progress[q.id]?.streak>=2||codexStatus==='unseen'&&!progress[q.id]);const pages=Math.max(1,Math.ceil(list.length/15));codexPage=Math.min(codexPage,pages-1);$('codex-list').innerHTML=`<p>${list.length}問 · ${codexPage+1} / ${pages}ページ</p>${list.slice(codexPage*15,(codexPage+1)*15).map(q=>`<details class="codex-item"><summary>${progress[q.id]?.streak>=2?'✓ ':''}${esc(q.term)} · ${KINDS[q.kind]} <small>${esc(q.id)}</small></summary><p>${esc(q.prompt)}</p><b>正解：${esc(q.choices[q.answer])}</b><p>${esc(q.explanation)}</p><a href="${esc(q.source)}" target="_blank" rel="noopener noreferrer">${esc(q.sourceTitle)} ↗</a></details>`).join('')||'<p>該当する問題はありません。</p>'}<div class="pager"><button data-page="-1" ${codexPage===0?'disabled':''}>← 前</button><button data-page="1" ${codexPage+1>=pages?'disabled':''}>次 →</button></div>`;}
async function setupRoom(create){if(room||!bank)return;$('net-error').textContent='接続しています…';const r=new CyberRoom();room=r;peerReady=false;updateLobby();r.addEventListener('connection',e=>{if(room!==r)return;const d=e.detail;peerReady=d.online&&d.peer;$('connection').textContent=peerReady?'相棒と接続中':d.online?'相棒を待機中':'再接続中';$('room-message').textContent=peerReady?(r.side===0?'相棒が合流しました。ホストが出撃してください。':'合流しました。ホストの出撃を待っています。'):'相棒の参加・再接続を待っています。';if(state&&r.side===0&&state.phase==='question'){if(!peerReady&&!state.paused){state.paused=true;state.pauseReason='network';state.revision++;}else if(peerReady&&state.pauseReason==='network'){state.paused=false;state.pauseReason='';state.revision++;}lastTick=Date.now();}updateLobby();renderKey='';render();if(peerReady)sendState();});r.addEventListener('error',e=>{$('net-error').textContent=e.detail;$('connection').textContent='接続を確認してください';});r.addEventListener('message',e=>{if(room!==r)return;const {type,body}=e.detail;if(type==='state'&&r.side===1){if(body.bankVersion!==bank.version){$('net-error').textContent='問題データの版が違います。2人ともページを再読み込みしてください。';return;}const s=body.state;if(!validSnapshot(s,byId)||s.mode!=='online')return;if(state&&s.id===state.id&&s.revision<state.revision)return;const was=state?.phase,oldRound=state?.round,oldId=state?.id;state=s;if(pending&&(pending.round!==s.round||pending.session!==s.id||s.answers[1]!==null))pending=null;if(s.phase==='result'&&(was!=='result'||oldRound!==s.round||oldId!==s.id))onOutcome();render();}if(type==='action'&&r.side===0&&body.side===1&&['answer','skill','pause'].includes(body.type))applyAction(body);});try{await(create?r.create():r.join($('room-input').value));$('net-error').textContent='';updateLobby();$('room-input').value=r.code;}catch(e){await r.leave();if(room===r)room=null;peerReady=false;$('net-error').textContent=e.name==='TimeoutError'?'接続が時間切れになりました。再試行してください。':e.message;updateLobby();}}
async function leaveToLobby(){const old=room;room=null;peerReady=false;state=null;pending=null;renderKey='';$('connection').textContent='ローカル待機中';$('room-info').hidden=true;$('net-error').textContent='';$('wave-label').textContent='作戦準備';$('battle-call').textContent='NEON CITY · 次の作戦を待機しています';$('modal').close();render();if(old)await old.leave();}
$('leave-room').onclick=leaveToLobby;$('start').onclick=launch;$('create-room').onclick=()=>setupRoom(true);$('join-form').onsubmit=e=>{e.preventDefault();setupRoom(false);};$('copy-room').onclick=async()=>{try{await navigator.clipboard.writeText(room.code);$('copy-room').textContent='コピーしました';}catch{$('room-message').textContent='部屋番号を長押ししてコピーしてください。';}};
$('pause').onclick=()=>action('pause',room?.side??0,!state?.paused);$('exit').onclick=()=>showModal('作戦を中断しますか？','<p>回答済みの学習記録は残ります。進行中の作戦は終了します。</p><button class="primary" data-lobby>中断して作戦選択へ</button>');$('close-modal').onclick=()=>$('modal').close();$('open-codex').onclick=openCodex;
$('help').onclick=()=>showModal('操作方法','<p><b>同じ画面の2人プレイ</b><br>PC：TRACEは1・2・3・4、PATCHは7・8・9・0で回答。スマホ：上下それぞれの問題をタップ。相棒と相談してから確定できます。</p><p><b>オンライン</b><br>1人が部屋を作り、もう1人が6文字の番号で参加します。ホストはTRACE、参加者はPATCH。ホストが出撃と次ラウンドを操作します。両端末で一時停止できます。</p><p><b>スキルと勝利条件</b><br>解析ヒントは誤答を除外、防御シールドはそのラウンドの被害を防ぎます。各1回。2人の正解で連携、3連携ごとに必殺技。最終ラウンドまで生存し、脅威の耐久をゼロにすると作戦成功です。</p><p>回答は確定後に変更できません。解説画面に制限時間はありません。訓練の難易度では回答時間も無制限です。</p>');
$('sources').onclick=()=>{if(!bank)return;showModal('出題範囲・参考資料',`<p>本ゲームはサイバー防衛を学ぶためのオリジナル問題です。200テーマを5つの異なる観点から問い、合計1,000問を収録しています。四択・対策判断・正誤に加え、ログやコードを読む実践ケースも収録。順序の変更を問題数に加えていません。</p><p>参考資料は各分野の学習用です。公的試験の過去問や公式認定問題ではありません。製品ごとの設定や仕様は各社の現行資料を確認してください。</p><ul>${bank.categories.map(c=>`<li><b>${esc(c.name)}：50問</b><br><a href="${esc(c.source)}" target="_blank" rel="noopener noreferrer">${esc(c.title)} ↗</a></li>`).join('')}</ul><p>データ版：${esc(bank.version)} · 学習記録はこのブラウザー内に保存されます。オンライン通信にはAItechの既存の通信基盤を使用します。</p>`);};
$('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'音 ON':'音 OFF';$('sound').setAttribute('aria-pressed',String(sound));if(sound)beep('hit');};$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();else $('setup-status').textContent='このブラウザーは全画面切替に対応していません。';}catch{$('setup-status').textContent='全画面に切り替えられませんでした。';}};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.mode)setMode(b.dataset.mode);if(b.dataset.answer!==undefined)action('answer',+b.dataset.side,+b.dataset.answer);if(b.dataset.skill!==undefined)action('skill',+b.dataset.skill);if(b.hasAttribute('data-next')&&state&&(mode!=='online'||room?.side===0)){next(state);renderKey='';render();sendState();if(innerWidth<721)$('play').scrollIntoView({behavior:'smooth',block:'start'});}if(b.hasAttribute('data-retry'))launch();if(b.hasAttribute('data-lobby'))leaveToLobby();if(b.dataset.page){codexPage+=+b.dataset.page;renderCodex();}});
document.addEventListener('keydown',e=>{if(e.repeat||$('modal').open||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||e.ctrlKey||e.metaKey||e.altKey||!state||state.phase!=='question')return;const p=['1','2','3','4'].includes(e.key)?0:['7','8','9','0'].includes(e.key)?1:-1;if(p>=0){if(mode==='online'&&room?.side!==p)return;const c=(p===0?['1','2','3','4']:['7','8','9','0']).indexOf(e.key);const btn=$('questions').querySelector(`[data-side="${p}"][data-answer="${c}"]`);if(btn&&!btn.disabled){e.preventDefault();action('answer',p,c);}}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&mode!=='online'&&state?.phase==='question'&&!state.paused){state.paused=true;state.pauseReason='manual';state.revision++;render();}lastTick=Date.now();});
setInterval(()=>{const now=Date.now(),elapsed=now-lastTick;lastTick=now;if(!state||mode==='online'&&room?.side!==0)return;if(tick(state,elapsed,byId)){onOutcome();render();sendState();}else updateClock();},200);
setInterval(()=>{if(mode==='online'){sendState();if(pending&&room?.ready&&peerReady)room.broadcast('action',pending);}},1000);
window.addEventListener('pagehide',()=>{scene.stop();if(room)room.leave();});
async function init(){try{const r=await fetch('./bank.json?v=1');if(!r.ok)throw new Error('問題データの読み込みに失敗しました。');bank=await r.json();if(bank.questions?.length!==1000||bank.categories?.length!==20)throw new Error('問題データを確認できませんでした。');byId=new Map(bank.questions.map(q=>[q.id,q]));$('category').innerHTML='<option value="all">全20エリアから出題</option>'+bank.categories.map((c,i)=>`<option value="${c.id}">${String(i+1).padStart(2,'0')} ${esc(c.name)} · 50問</option>`).join('');render();}catch(e){$('start').disabled=true;$('setup-status').textContent=e.message+' ページを再読み込みしてください。';}}
updateLobby();init();
