export const KINDS={identify:'用語解析',defend:'対策選択',mechanism:'仕組みの判定',myth:'誤解を見抜く',judgment:'現場判断'};
export const LEVELS={1:'基礎',2:'実践',3:'応用'};
export function rng(seed){let a=seed>>>0;return()=>{a+=0x6d2b79f5;let t=a;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296;};}
export function shuffle(items,random=Math.random){const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
export function makeSession(bank,options={},progress={}){
 const seed=options.seed??crypto.getRandomValues(new Uint32Array(1))[0],random=rng(seed),players=options.mode==='solo'?1:2;
 let pool=bank.questions.filter(q=>options.category==='all'||!options.category||q.category===options.category);
 if(options.questionMode==='review')pool=pool.filter(q=>progress[q.id]?.wrong&&progress[q.id]?.streak<2);
 pool=shuffle(pool,random);
 if(options.questionMode==='fresh')pool.sort((a,b)=>(progress[a.id]?.streak>=2?2:progress[a.id]?1:0)-(progress[b.id]?.streak>=2?2:progress[b.id]?1:0));
 if(!pool.length)return null;
 const rounds=Math.min(10,Math.ceil(pool.length/players)),deck=[],chosen=new Set();
 for(let r=0;r<rounds;r++){const pair=[];for(let p=0;p<players;p++){const role=p===0?'trace':'patch';let candidates=pool.filter(q=>!chosen.has(q.id));if(options.questionMode==='fresh'&&candidates.length){const priority=q=>progress[q.id]?.streak>=2?2:progress[q.id]?1:0;const first=priority(candidates[0]);candidates=candidates.filter(q=>priority(q)===first);}let q=players===1?candidates[0]:candidates.find(q=>q.role===role||q.role==='either');if(!q)q=candidates[0];if(!q){pair.push(null);continue;}chosen.add(q.id);const order=shuffle(q.choices.map((_,i)=>i),random);pair.push({id:q.id,order});}deck.push(pair);}
 const bossMax=Math.round(chosen.size*8.5),limit=options.difficulty==='relaxed'?null:options.difficulty==='expert'?25000:45000;
 const s={v:1,id:seed.toString(36)+'-'+Date.now().toString(36),revision:1,mode:options.mode||'local',category:options.category||'all',difficulty:options.difficulty||'normal',questionMode:options.questionMode||'fresh',seed,players,deck,rounds,round:0,phase:'question',hp:100,boss:bossMax,bossMax,score:0,combo:0,bestCombo:0,limit,remaining:limit,answers:[],skills:[false,false],hint:false,shield:false,paused:false,pauseReason:'',history:[],outcome:null};
 prepareRound(s);return s;
}
export function prepareRound(s){s.answers=s.deck[s.round].map(q=>q?null:-2);s.remaining=s.limit;s.hint=false;s.shield=false;s.phase='question';s.paused=false;s.pauseReason='';s.revision++;}
export function questionFor(s,side,byId){const item=s.deck[s.round]?.[side];if(!item)return null;const q=byId.get(item.id);if(!q)return null;return{...q,options:item.order.map(i=>q.choices[i]),correct:item.order.indexOf(q.answer)};}
export function answer(s,side,choice,byId){if(s.phase!=='question'||s.paused||side<0||side>=s.players||s.answers[side]!==null)return false;const q=questionFor(s,side,byId);if(!q||!Number.isInteger(choice)||choice<0||choice>=q.options.length)return false;s.answers[side]=choice;s.revision++;if(s.answers.every(x=>x!==null))resolve(s,byId);return true;}
export function useSkill(s,side){if(!Number.isInteger(side)||side<0||side>=s.players)return false;if(s.phase!=='question'||s.paused||s.skills[side]||s.answers[side]!==null)return false;s.skills[side]=true;if(side===0)s.hint=true;else s.shield=true;s.revision++;return true;}
export function tick(s,elapsed,byId){if(s.phase!=='question'||s.paused||s.limit===null)return false;s.remaining=Math.max(0,s.remaining-Math.max(0,elapsed));if(s.remaining===0){s.answers=s.answers.map(a=>a===null?-1:a);resolve(s,byId);return true;}return false;}
export function resolve(s,byId){if(s.phase!=='question')return;const results=s.deck[s.round].map((item,p)=>{const q=questionFor(s,p,byId);return q?{id:q.id,side:p,choice:s.answers[p],correct:s.answers[p]===q.correct,answer:q.correct}:null;}).filter(Boolean);const correct=results.filter(r=>r.correct).length,wrong=results.length-correct,all=correct===results.length;
 s.combo=all?s.combo+1:0;s.bestCombo=Math.max(s.bestCombo,s.combo);const link=all&&results.length===2,overdrive=link&&s.combo%3===0;const damage=correct*12+(link?6:0)+(overdrive?16:0);const hurt=s.shield?0:wrong*(s.difficulty==='expert'?12:s.difficulty==='relaxed'?4:8);s.hp=Math.max(0,s.hp-hurt);s.boss=Math.max(0,s.boss-damage);s.score+=correct*100+(link?80:0)+(overdrive?200:0)+Math.round(correct*(s.remaining??0)/1000);s.phase='result';s.outcome={results,correct,wrong,link,overdrive,damage,hurt,shield:s.shield};s.history.push({...s.outcome,round:s.round});s.revision++;
}
export function next(s){if(s.phase!=='result')return false;if(s.hp<=0||s.round+1>=s.rounds){s.phase='finished';s.won=s.hp>0&&s.boss===0;s.revision++;return true;}s.round++;prepareRound(s);return true;}
export function validSnapshot(s,byId){try{return Boolean(s&&s.v===1&&typeof s.id==='string'&&s.id.length<80&&Number.isSafeInteger(s.revision)&&s.revision>0&&[1,2].includes(s.players)&&Array.isArray(s.deck)&&s.deck.length>0&&s.deck.length<=10&&s.rounds===s.deck.length&&Number.isInteger(s.round)&&s.round>=0&&s.round<s.rounds&&['question','result','finished'].includes(s.phase)&&['normal','expert','relaxed'].includes(s.difficulty)&&['local','online','solo'].includes(s.mode)&&[s.hp,s.boss,s.bossMax,s.score,s.combo,s.bestCombo].every(Number.isFinite)&&s.hp>=0&&s.hp<=100&&s.boss>=0&&s.boss<=s.bossMax&&s.bossMax<=200&&s.score>=0&&s.score<=20000&&[null,25000,45000].includes(s.limit)&&(s.remaining===null||Number.isFinite(s.remaining)&&s.remaining>=0&&s.remaining<=45000)&&Array.isArray(s.answers)&&s.answers.length===s.players&&s.answers.every(a=>a===null||Number.isInteger(a)&&a>=-2&&a<=3)&&Array.isArray(s.skills)&&s.skills.length===2&&s.skills.every(a=>typeof a==='boolean')&&Array.isArray(s.history)&&s.history.length<=10&&s.history.every(h=>Array.isArray(h.results)&&h.results.length<=2&&h.results.every(r=>byId.has(r.id)&&[0,1].includes(r.side)&&typeof r.correct==='boolean'))&&s.deck.every(pair=>Array.isArray(pair)&&pair.length===s.players&&pair.every(q=>q===null||byId.has(q.id)&&Array.isArray(q.order)&&q.order.length===byId.get(q.id).choices.length&&new Set(q.order).size===q.order.length&&q.order.every(n=>Number.isInteger(n)&&n>=0&&n<q.order.length))));}catch{return false;}}
export function summary(s){const results=s.history.flatMap(x=>x.results),correct=results.filter(x=>x.correct).length,accuracy=results.length?Math.round(correct/results.length*100):0;return{total:results.length,correct,accuracy,rank:s.won?(accuracy>=95?'S':accuracy>=80?'A':'B'):'C',misses:results.filter(x=>!x.correct)};}
