// Uses the existing two-seat room RPC and Supabase's documented JSON v1 protocol.
// A random server-issued channel key separates rooms; no accounts or chat are needed.
export class CyberRoom extends EventTarget{
 constructor(config=globalThis.SUPABASE_CONFIG){super();this.config=config;this.token=crypto.randomUUID();this.ref=0;this.ready=false;this.joined=false;this.closed=false;this.remote=null;this.seen=0;this.seq=0;this.attempts=0;this.lastPeer=0;this.lastServer=0;}
 emit(type,detail){this.dispatchEvent(new CustomEvent(type,{detail}));}
 async rpc(name){if(!this.config?.url||!this.config?.publishableKey)throw new Error('通信設定を読み込めませんでした。ページを再読み込みしてください。');const r=await fetch(this.config.url+'/rest/v1/rpc/'+name,{method:'POST',headers:{apikey:this.config.publishableKey,'Content-Type':'application/json'},body:JSON.stringify({p_code:this.code,p_player_token:this.token}),signal:AbortSignal.timeout(15000)});if(!r.ok){let text=await r.text();if(text.includes('ROOM_FULL'))throw new Error('この部屋は2人で満員です。');if(text.includes('ROOM_NOT_FOUND'))throw new Error('部屋が見つかりません。番号と相棒の待機状態を確認してください。');if(text.includes('ROOM_CODE_TAKEN'))throw new Error('番号が重複しました。もう一度部屋を作ってください。');throw new Error('通信できませんでした。少し待って再試行してください。');}const text=await r.text();return text?JSON.parse(text):null;}
 async create(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';this.code=Array.from(crypto.getRandomValues(new Uint8Array(6)),n=>chars[n%chars.length]).join('');this.side=0;const r=await this.rpc('create_game_room');await this.connect(Array.isArray(r)?r[0]:r);return this.code;}
 async join(code){this.code=code.trim().toUpperCase();if(!/^[A-Z0-9]{6}$/.test(this.code))throw new Error('部屋番号は英数字6文字です。');this.side=1;const r=await this.rpc('join_game_room');await this.connect(Array.isArray(r)?r[0]:r);return this.code;}
 async connect(row){if(!row?.channel_key)throw new Error('部屋を開始できませんでした。');this.topic='realtime:neon-sentinels:'+row.channel_key;this.joined=true;return this.openSocket();}
 openSocket(){return new Promise((resolve,reject)=>{if(this.closed)return reject(new Error('部屋を退出しました。'));const url=new URL(this.config.url.replace(/^http/,'ws')+'/realtime/v1/websocket');url.searchParams.set('apikey',this.config.publishableKey);url.searchParams.set('vsn','1.0.0');const ws=new WebSocket(url);this.ws=ws;const joinRef=String(++this.ref);this.joinRef=joinRef;let settled=false;const fail=()=>{if(!settled){settled=true;reject(new Error('オンライン接続を開始できませんでした。再試行してください。'));}};const timeout=setTimeout(()=>{fail();ws.close();},12000);
 ws.onopen=()=>{this.lastServer=Date.now();ws.send(JSON.stringify({topic:this.topic,event:'phx_join',payload:{config:{broadcast:{ack:false,self:false},presence:{enabled:false},private:false}},ref:joinRef,join_ref:joinRef}));};
 ws.onmessage=e=>{this.lastServer=Date.now();if(typeof e.data!=='string'||e.data.length>100000)return;let p;try{p=JSON.parse(e.data);}catch{return;}if(p.event==='phx_reply'&&p.ref===joinRef){if(p.payload?.status!=='ok'){clearTimeout(timeout);fail();ws.close();return;}clearTimeout(timeout);this.ready=true;this.attempts=0;if(!settled){settled=true;resolve();}this.startHeartbeat();this.emit('connection',{online:true,peer:false});this.broadcast('hello');return;}if(p.event==='broadcast'&&p.topic===this.topic&&p.payload?.event==='packet')this.receive(p.payload.payload);};
 ws.onerror=()=>{fail();};ws.onclose=()=>{clearTimeout(timeout);clearInterval(this.heartbeat);this.ready=false;this.lastPeer=0;this.emit('connection',{online:false,peer:false});fail();if(!this.closed){if(this.attempts++<4)this.reconnectTimer=setTimeout(()=>this.openSocket().catch(()=>{}),Math.min(8000,1000*2**this.attempts));else this.emit('error','再接続できませんでした。作戦を中断し、部屋を作り直してください。');}};
 });}
 startHeartbeat(){clearInterval(this.heartbeat);this.heartbeat=setInterval(()=>{if(!this.ready)return;this.ws.send(JSON.stringify({topic:'phoenix',event:'heartbeat',payload:{},ref:String(++this.ref)}));this.broadcast('hello');if(Date.now()-this.lastServer>18000){this.ws.close();return;}if(this.lastPeer&&Date.now()-this.lastPeer>11000)this.emit('connection',{online:true,peer:false});},2500);}
 broadcast(type,body={}){if(!this.ready||this.ws?.readyState!==1)return false;this.ws.send(JSON.stringify({topic:this.topic,event:'broadcast',payload:{type:'broadcast',event:'packet',payload:{protocol:'neon-sentinels-1',sender:this.token,side:this.side,seq:++this.seq,type,body}},ref:String(++this.ref),join_ref:this.joinRef}));return true;}
 receive(p){if(!p||p.protocol!=='neon-sentinels-1'||typeof p.sender!=='string'||p.sender.length!==36||p.sender===this.token||p.side===this.side||![0,1].includes(p.side)||!Number.isSafeInteger(p.seq)||p.seq<=0)return;if(this.remote&&p.sender!==this.remote)return;if(p.seq<=this.seen)return;this.remote=p.sender;this.seen=p.seq;const wasMissing=!this.lastPeer||Date.now()-this.lastPeer>11000;this.lastPeer=Date.now();if(wasMissing)this.emit('connection',{online:true,peer:true});if(p.type==='hello'){this.broadcast('ack');return;}if(p.type==='ack')return;if(p.type==='leave'){this.lastPeer=0;this.emit('connection',{online:true,peer:false});this.emit('error','相棒が退出しました。作戦を中断して部屋を作り直してください。');return;}if(p.body&&typeof p.body==='object')this.emit('message',{type:p.type,body:p.body});}
 async leave(){if(this.closed)return;this.broadcast('leave');this.closed=true;clearInterval(this.heartbeat);clearTimeout(this.reconnectTimer);if(this.ws){this.ws.onclose=null;this.ws.close();}this.ready=false;if(this.joined){try{await this.rpc('leave_game_room');}catch{}}}
}
