export const origins={onepiece:'https://www.onepiece-cardgame.com',pokemon:'https://www.pokemon-card.com',zx:'https://www.zxtcg.com'};
export const pageSizes={onepiece:12,pokemon:13,zx:10};
export function decode(s=''){return String(s).replace(/&#(x[\da-f]+|\d+);/gi,(_,n)=>{const v=n[0].toLowerCase()==='x'?parseInt(n.slice(1),16):Number(n);return v>=0&&v<=0x10ffff?String.fromCodePoint(v):'';}).replace(/&(?:amp|lt|gt|quot|apos|nbsp);/g,m=>({'&amp;':'&','&lt;':'<','&gt;':'>','&quot;':'"','&apos;':"'",'&nbsp;':' '}[m]));}
export function plain(s=''){return decode(String(s).replace(/<!--[\s\S]*?-->/g,'').replace(/<(script|style)\b[^>]*>[\s\S]*?<\/\1>/gi,'').replace(/<img\b[^>]*\balt=["']([^"']*)["'][^>]*>/gi,' $1 ').replace(/<br\b[^>]*>/gi,'\n').replace(/<\/(?:h[1-6]|p|div|li|tr)>/gi,'\n').replace(/<[^>]+>/g,'')).replace(/[ \t\r]+/g,' ').replace(/ *\n */g,'\n').replace(/\n{3,}/g,'\n\n').trim();}
const attr=(s,n)=>decode(s.match(new RegExp('(?:^|\\s)'+n+'=["\']([^"\']*)["\']','i'))?.[1]||'');
export function block(s,tag,cls){const re=new RegExp('<'+tag+'\\b[^>]*class=["\'][^"\']*\\b'+cls+'\\b[^"\']*["\'][^>]*>','i'),m=re.exec(s);if(!m)return '';let level=1;const scan=new RegExp('<(/?)'+tag+'\\b[^>]*>','gi');scan.lastIndex=m.index+m[0].length;let x;while((x=scan.exec(s))){level+=x[1]?-1:1;if(!level)return s.slice(m.index+m[0].length,x.index);}return '';}
function url(path,game){try{const u=new URL(decode(path),origins[game]+'/card/');return u.origin===origins[game]&&u.protocol==='https:'?u.href:'';}catch{return '';}}
export function parseSets(html,game){let entries=[];if(game==='pokemon'){entries=[...html.matchAll(/\{\s*name:\s*"pg",\s*value:\s*"([^"]+)",\s*group:\s*"[^"]+",\s*label:\s*"([^"]+)"\s*\}/g)].map(m=>({id:m[1],name:plain(m[2])}));}else{for(const m of html.matchAll(/<select\b([^>]*)>([\s\S]*?)<\/select>/gi)){const field=attr(m[1],'name');if(game==='onepiece'?field!=='series':!/^pn[1-8]$/.test(field))continue;for(const o of m[2].matchAll(/<option\b([^>]*)>([\s\S]*?)<\/option>/gi)){const v=attr(o[1],'value');if(v)entries.push({id:game==='zx'?field+'|'+v:v,name:plain(decode(o[2]))});}}}if(!entries.length)throw Error('収録商品の情報を読み取れませんでした。');return entries;}
export function parseOP(html){const count=Number(plain(block(html,'div','countCol')).replace(/[^\d]/g,''));const cards=[];for(const m of html.matchAll(/<dl\b([^>]*class="modalCol"[^>]*)>([\s\S]*?)<\/dl>/g)){const id=attr(m[1],'id'),h=m[2],info=[...block(h,'div','infoCol').matchAll(/<span[^>]*>([\s\S]*?)<\/span>/g)].map(m=>plain(m[1]));const field=cls=>plain(block(h,'div',cls).replace(/<h3[^>]*>[\s\S]*?<\/h3>/,''));const image=attr(block(h,'div','frontCol').match(/<img\b[^>]*>/)?.[0]||'','data-src');cards.push({id,number:info[0],rarity:info[1],type:info[2],name:plain(block(h,'div','cardName')),image:url(image,'onepiece'),set:field('getInfo'),stats:[field('color'),field('feature'),plain(block(h,'div','cost')),plain(block(h,'div','power'))].filter(Boolean).join(' · '),effect:[field('text'),field('trigger')?'トリガー\n'+field('trigger'):''].filter(Boolean).join('\n\n'),flavor:'',detailLoaded:true,sourceUrl:origins.onepiece+'/cardlist/?freewords='+encodeURIComponent(info[0])});}if(html.includes('検索結果が多すぎます'))throw Error('検索結果が多すぎるため、カード名を詳しくするか収録商品で絞り込んでください。');if(!html.includes('countCol')||count!==cards.length)throw Error('公式検索の件数とカード一覧が一致しませんでした。');return {cards,total:count};}
export function parsePokemonList(data){if(Number(data.result)!==1||!Array.isArray(data.cardList)||!Number.isFinite(Number(data.hitCnt)))throw Error('公式カード検索の応答を読み取れませんでした。');return {total:Number(data.hitCnt),cards:data.cardList.map(c=>({id:String(c.cardID),name:plain(c.cardNameAltText||c.cardNameViewText),image:url(c.cardThumbFile,'pokemon'),sourceUrl:origins.pokemon+'/card-search/details.php/card/'+encodeURIComponent(c.cardID)+'/regu/all',detailLoaded:false}))};}
function pokemonText(html){return plain(html.replace(/<span\b[^>]*class="icon-([^ "-]+)[^>]*><\/span>/g,(_,type)=>'['+({grass:'草',fire:'炎',water:'水',lightning:'雷',electric:'雷',psychic:'超',fighting:'闘',darkness:'悪',dark:'悪',metal:'鋼',steel:'鋼',fairy:'妖',dragon:'竜',none:'無'}[type]||type)+']'));}
export function parsePokemonDetail(html,id){const name=plain(block(html,'h1','Heading1')),card=block(html,'div','card Text-fjalla'),right=block(html,'div','RightBox-inner'),author=block(html,'div','author');const image=html.match(/<img[^>]*class="fit"[^>]*>/)?.[0]||'';const effect=right.replace(/^[\s\S]*?<\/div>\s*<\/div>\s*<\/div>/,'').split(/<table\b|<h2[^>]*>進化/)[0];if(!name||!image)throw Error('カード詳細を読み取れませんでした。');return {id,name,image:url(attr(image,'src'),'pokemon'),flavor:plain(card.split(/<hr\b[^>]*>/)[1]||''),effect:pokemonText(effect),stats:pokemonText(block(right,'div','TopInfo')),number:plain(block(html,'div','subtext')),set:plain(block(html,'div','PopupSub')),artist:plain(author).replace(/^イラストレーター\s*/,''),detailLoaded:true,sourceUrl:origins.pokemon+'/card-search/details.php/card/'+id+'/regu/all'};}
export function parseZXList(html){const count=plain(block(html,'div','countRule')).match(/全([\d,]+)件/);const cards=[];for(const m of html.matchAll(/<section\b([^>]*data-modal-card=[^>]*)>([\s\S]*?)<\/section>/g)){const id=attr(m[1],'data-modal-card'),h=m[2],img=h.match(/<img[^>]*src="[^"]*\/card_img\/[^>]*>/)?.[0]||'';cards.push({id,number:plain(block(h,'span','cardno')),name:plain(block(h,'span','name')),image:url(attr(img,'src'),'zx'),rarity:attr(block(h,'div','rarity').match(/<img[^>]*>/)?.[0]||'','alt'),type:plain(block(h,'p','summary')),artist:plain(block(h,'p','illustrator')).replace(/^Illustrator\./,''),sourceUrl:origins.zx+'/card/card_detail.php?n='+encodeURIComponent(id),detailLoaded:false});}if(!count&&!/0件|見つかりません|該当するカード/.test(plain(html)))throw Error('公式カード一覧を読み取れませんでした。');return {cards,total:count?Number(count[1].replaceAll(',','')):0};}
export function parseZXDetail(html,id){const name=plain(block(html,'span','main'));const fields={};for(const m of html.matchAll(/<tr>\s*<th[^>]*>([\s\S]*?)<\/th>\s*<td[^>]*>([\s\S]*?)<\/td>/g))fields[plain(m[1])]=plain(m[2]);const image=attr(html.match(/<img[^>]*src="[^"]*\/card_img\/[^>]*>/)?.[0]||'','src');if(!name||!image)throw Error('カードの本文を取得できませんでした。');return {id,name,number:plain(block(html,'p','cardno')),image:url(image,'zx'),rarity:attr(block(html,'div','rarity').match(/<img[^>]*>/)?.[0]||'','alt'),type:fields['カード種類'],stats:[fields['コスト／パワー']?'コスト／パワー '+fields['コスト／パワー']:'',fields['種族']].filter(Boolean).join(' · '),set:fields['収録作品'],artist:fields['イラストレーター'],effect:plain(block(html,'div','cardtext')),flavor:plain(block(html,'div','flavor_text')||block(html,'div','flavor')||block(html,'div','flavortext')||block(html,'p','flavor')),detailLoaded:true,sourceUrl:origins.zx+'/card/card_detail.php?n='+encodeURIComponent(id)};}
