import {origins,pageSizes,parseSets,parseOP,parsePokemonList,parsePokemonDetail,parseZXList,parseZXDetail} from './core.mjs';
const KEY='sb_publishable_IcEN-3GgzcLCHiyNLyRiCQ_RpkAhCGI';
const allowed=new Set(['https://aitechd.com','https://www.aitechd.com']);
const cache=new Map(),pending=new Map(),budgets=new Map();let cacheSize=0,active=0;
function keep(key,data){const bytes=JSON.stringify(data).length*2;if(bytes>24000000)return;while(cache.size&&cacheSize+bytes>24000000){const k=cache.keys().next().value;cacheSize-=cache.get(k).bytes;cache.delete(k);}const old=cache.get(key);if(old)cacheSize-=old.bytes;cache.set(key,{data,bytes,at:Date.now()});cacheSize+=bytes;}
async function cached(key,ttl,work){const saved=cache.get(key);if(saved&&Date.now()-saved.at<ttl)return saved.data;if(pending.has(key))return pending.get(key);if(active>=6)throw Error('読み込みが混み合っています。少し待って再試行してください。');const promise=(async()=>{active++;try{const value=await work();keep(key,value);return value;}finally{active--;pending.delete(key);}})();pending.set(key,promise);return promise;}
async function upstream(game,path,body){const url=new URL(path,origins[game]);if(url.origin!==origins[game])throw Error('出典が不正です。');const r=await fetch(url,{method:body?'POST':'GET',body:body||undefined,redirect:'follow',signal:AbortSignal.timeout(22000),headers:{Accept:'text/html, application/json','User-Agent':'AItech-Card-Library/1.0 (+https://aitechd.com/commons/)'}});if(!r.ok){await r.body?.cancel();throw Error(r.status===429?'公式検索が混み合っています。時間をおいて再試行してください。':'公式カード検索に接続できませんでした。');}if(new URL(r.url).origin!==origins[game]){await r.body?.cancel();throw Error('公式サイトの転送先を確認できませんでした。');}const reader=r.body?.getReader();if(!reader)throw Error('応答が空です。');let size=0;const chunks=[];while(true){const part=await reader.read();if(part.done)break;size+=part.value.length;if(size>30000000){await reader.cancel();throw Error('取得対象が大きいため、収録商品で絞り込んでください。');}chunks.push(part.value);}const bytes=new Uint8Array(size);let i=0;for(const chunk of chunks){bytes.set(chunk,i);i+=chunk.length;}return new TextDecoder().decode(bytes);}
const sourcePaths={onepiece:'/cardlist/',pokemon:'/card-search/',zx:'/card/'};
export async function handler(request){const origin=request.headers.get('origin');const headers={'Access-Control-Allow-Origin':origin&&allowed.has(origin)?origin:'https://aitechd.com','Access-Control-Allow-Headers':'apikey, content-type, x-region','Access-Control-Allow-Methods':'GET, OPTIONS','Access-Control-Max-Age':'600','Vary':'Origin','Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'};const send=(data,status=200)=>Response.json(data,{status,headers});if(origin&&!allowed.has(origin))return send({error:'このサイトからは利用できません。'},403);if(request.method==='OPTIONS')return new Response(null,{status:204,headers});if(request.method!=='GET')return send({error:'GETのみ利用できます。'},405);if(request.headers.get('apikey')!==KEY)return send({error:'接続設定を確認してください。'},401);
 const ip=request.headers.get('x-forwarded-for')?.split(',')[0]?.trim()||'anonymous',now=Date.now(),b=budgets.get(ip);if(!b||now-b.at>60000)budgets.set(ip,{at:now,count:1});else if(++b.count>100)return send({error:'読み込み回数が多いため、1分ほど待ってください。'},429);if(budgets.size>2000)budgets.clear();
 const params=new URL(request.url).searchParams,game=params.get('game'),kind=params.get('kind');if(!Object.hasOwn(origins,game))return send({error:'カードゲームが不正です。'},400);
 try{if(kind==='sets'){const data=await cached(game+':sets',3600000,async()=>({sets:parseSets(await upstream(game,sourcePaths[game]),game),fetchedAt:new Date().toISOString()}));return send(data);}
 if(kind==='detail'){const id=params.get('id')||'';if(game==='pokemon'?!/^\d{1,6}$/.test(id):game==='zx'?!/^[A-Z0-9]+-[A-Za-z0-9]+-\d{2}$/.test(id):true)return send({error:'カード番号が不正です。'},400);return send(await cached(game+':detail:'+id,86400000,async()=>game==='pokemon'?parsePokemonDetail(await upstream(game,'/card-search/details.php/card/'+id+'/regu/all'),id):parseZXDetail(await upstream(game,'/card/card_detail.php?n='+id),id)));}
 if(kind!=='search')return send({error:'検索種別が不正です。'},400);const term=(params.get('q')||'').trim(),set=params.get('set')||'',page=Number(params.get('page')||1),size=pageSizes[game];if(term.length>100||set.length>200||!Number.isInteger(page)||page<1||page>10000)return send({error:'検索条件を確認してください。'},400);
 let result,sourceUrl,effectiveSet,setName,note,offset=0;
 if(game==='zx'&&/^[a-z]{1,4}\d{1,3}-\d{1,4}[a-z]?(?:-\d{2})?$/i.test(term)){
 const id=term.toUpperCase()+(term.split('-').length===2?'-00':'');
 const card=await cached('zx:number:'+id,86400000,async()=>{const html=await upstream(game,'/card/card_detail.php?n='+id);return html.trim()?parseZXDetail(html,id):null;});
 let matches=Boolean(card);if(set){const index=set.indexOf('|'),field=set.slice(0,index),value=set.slice(index+1);if(index<0||!/^pn[1-8]$/.test(field))return send({error:'収録商品が不正です。'},400);matches=matches&&(card.set||'').normalize('NFKC').replace(/\s+/g,' ').includes(value.normalize('NFKC').replace(/\s+/g,' '));}
 result={cards:matches?[card]:[],total:matches?1:0,fetchedAt:new Date().toISOString()};sourceUrl=origins.zx+'/card/card_detail.php?n='+id;note='カード番号に一致する収録版を表示しています。末尾の版番号を省略した場合は、基本の掲載版が対象です。';
 }
 else if(game==='onepiece'){if(set&&!/^\d{6}$/.test(set))return send({error:'収録商品が不正です。'},400);effectiveSet=set;if(!term&&!set){const html=await cached('onepiece:landing',3600000,()=>upstream(game,'/cardlist/'));effectiveSet=html.match(/<option value="(\d{6})"[^>]*selected/)?.[1];if(!effectiveSet)throw Error('収録商品を選んで検索してください。');setName=parseSets(html,game).find(s=>s.id===effectiveSet)?.name;}const p=new URLSearchParams({freewords:term,series:effectiveSet||''});result=await cached('onepiece:'+p,900000,async()=>({...parseOP(await upstream(game,'/cardlist/',p)),fetchedAt:new Date().toISOString()}));sourceUrl=origins[game]+'/cardlist/?'+p;offset=(page-1)*size;}
 else if(game==='pokemon'){if(set&&!/^[A-Za-z0-9-]{1,15}$/.test(set))return send({error:'収録商品が不正です。'},400);const sourcePage=Math.floor((page-1)/3)+1,p=new URLSearchParams({keyword:term,sm_and_keyword:'true',regulation_sidebar_form:'all',pg:set,page:String(sourcePage)});result=await cached('pokemon:'+p,900000,async()=>({...parsePokemonList(JSON.parse(await upstream(game,'/card-search/resultAPI.php?'+p))),fetchedAt:new Date().toISOString()}));sourceUrl=origins[game]+'/card-search/index.php?'+p;offset=((page-1)%3)*size;}
 else{const p=new URLSearchParams({page:String(Math.floor((page-1)/3)+1)});if(term){p.set('fw',term);p.set('fwmode','and');for(const key of ['fwcn','fwct','fwft','fwrm'])p.set(key,'1');}if(set){const index=set.indexOf('|'),field=set.slice(0,index),value=set.slice(index+1);if(index<0||!/^pn[1-8]$/.test(field))return send({error:'収録商品が不正です。'},400);p.set(field,value);}if(!term&&!set){p.set('cl','赤,青,白,黒,緑,無,多色');p.set('clmode','or');}result=await cached('zx:'+p,900000,async()=>({...parseZXList(await upstream(game,'/card/?'+p)),fetchedAt:new Date().toISOString()}));sourceUrl=origins[game]+'/card/?'+p;offset=((page-1)%3)*size;}
 if(page>Math.max(1,Math.ceil(result.total/size)))return send({error:'そのページはありません。ページ番号を小さくして検索してください。'},400);
 return send({cards:result.cards.slice(offset,offset+size),total:result.total,page,pageSize:size,sourceUrl,effectiveSet,fetchedAt:result.fetchedAt,note:note||(game==='onepiece'?(effectiveSet?'表示対象：'+(result.cards[0]?.set||setName||'指定した収録商品')+'。全商品を探す場合は収録商品を全商品にしてキーワードを入力してください。':'全商品を横断した検索結果です。再録・パラレルを含みます。'):'公式掲載の全収録商品が検索対象です。公開済みの発売予定カードを含む場合があります。')});
 }catch(e){console.error('commons-tcg',game,kind,e?.message);return send({error:e instanceof Error?e.message:'カード情報を取得できませんでした。'},502);}}
