import {Game, LEVELS, WORLDS, W, H} from './engine.mjs';

const $=id=>document.getElementById(id);
const canvas=$('gameCanvas'),ctx=canvas.getContext('2d',{alpha:false});
const SAVE_KEY='lantern-duo-v1';
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const formatTime=n=>`${Math.floor(Math.max(0,n)/60)}:${String(Math.floor(Math.max(0,n)%60)).padStart(2,'0')}`;
let storageAvailable=true;
function readSave(){try{const s=JSON.parse(localStorage.getItem(SAVE_KEY)||'{}');return {unlocked:clamp(Math.floor(Number(s.unlocked)||1),1,LEVELS.length),level:clamp(Math.floor(Number(s.level)||0),0,LEVELS.length-1),elapsed:Math.max(0,Number(s.elapsed)||0),coins:Math.max(0,Number(s.coins)||0),stars:Array.isArray(s.stars)?s.stars.slice(0,LEVELS.length).map(n=>clamp(Number(n)||0,0,3)):[],started:!!s.started,completed:!!s.completed,mode:s.mode==='solo'?'solo':'coop',sound:s.sound!==false};}catch{storageAvailable=false;return {unlocked:1,level:0,elapsed:0,coins:0,stars:[],started:false,completed:false,mode:'coop',sound:true};}}
let save=readSave(),mode=save.mode,game=null,playing=false,paused=false,assetsReady=false,modalKind='',camera=0,viewWidth=1100,viewHeight=560,renderTime=0,accumulator=0,lastFrame=0,hudClock=0,saveClock=0;
const keys=new Set(),pointers=new Map(),sprites={},particles=[];
window.__lantern={get game(){return game},get paused(){return paused},get mode(){return mode}};

function persist(){try{localStorage.setItem(SAVE_KEY,JSON.stringify(save));}catch{storageAvailable=false;}}
function snapshot(){if(!game)return;save.level=game.state==='clear'?Math.min(LEVELS.length-1,game.levelIndex+1):game.levelIndex;save.elapsed=game.time;save.coins=game.score;save.started=true;save.mode=mode;persist();}
function syncHome(){document.querySelectorAll('.mode-btn').forEach(b=>{const active=b.dataset.mode===mode;b.classList.toggle('selected',active);b.setAttribute('aria-pressed',String(active));});$('continueButton').hidden=!save.started;$('saveNote').textContent=storageAvailable?(save.started?`ステージ ${String(save.level+1).padStart(2,'0')} から再開できます。`:'全12ステージ · 約30分の冒険（目安）'):'このブラウザーでは進み具合を保存できません。';$('p2Controls').classList.toggle('cpu',mode==='solo');$('p2ControlLabel').textContent=mode==='solo'?'CPU PARTNER':'PLAYER 2';$('player2Name').textContent=mode==='solo'?'AMBER · CPU':'AMBER';document.querySelectorAll('[data-player="1"]').forEach(b=>b.disabled=mode==='solo');$('soundState').textContent=save.sound?'ON':'OFF';$('soundButton').setAttribute('aria-pressed',String(save.sound));$('soundButton').setAttribute('aria-label',save.sound?'サウンドをオフにする':'サウンドをオンにする');}

const audio={context:null,master:null,nextNote:0,note:0,
  init(){try{if(!this.context){this.context=new (window.AudioContext||window.webkitAudioContext)();this.master=this.context.createGain();this.master.gain.value=save.sound?.16:0;this.master.connect(this.context.destination);}if(this.context.state==='suspended')this.context.resume().catch(()=>{});}catch{}},
  tone(freq,duration=.12,type='triangle',volume=.4,delay=0,end=0){const ac=this.context;if(!ac||!save.sound||ac.state!=='running')return;const t=ac.currentTime+delay,o=ac.createOscillator(),g=ac.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);if(end)o.frequency.exponentialRampToValueAtTime(end,t+duration);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(volume,t+.01);g.gain.exponentialRampToValueAtTime(.001,t+duration);o.connect(g);g.connect(this.master);o.start(t);o.stop(t+duration+.02);o.onended=()=>{o.disconnect();g.disconnect();};},
  event(name){if(name==='jump')this.tone(290,.14,'triangle',.18,0,600);if(name==='coin'){this.tone(880,.1,'sine',.36);this.tone(1320,.14,'sine',.22,.06);}if(name==='star'||name==='checkpoint'||name==='gate'||name==='rescue')[523,659,784].forEach((n,i)=>this.tone(n,.25,'triangle',.27,i*.075));if(name==='stomp')this.tone(150,.16,'square',.15,0,370);if(name==='hurt')this.tone(210,.18,'sawtooth',.16,0,75);if(name==='win')[523,659,784,1046].forEach((n,i)=>this.tone(n,.5,'triangle',.3,i*.14));},
  update(){const ac=this.context;if(!ac||!save.sound||!playing||paused||ac.state!=='running')return;if(ac.currentTime<this.nextNote)return;this.nextNote=ac.currentTime+.38;const melody=[523,0,659,784,0,659,587,0,440,0,523,659,0,587,523,0];const n=melody[this.note%melody.length];if(n)this.tone(n,.32,'sine',.12);if(this.note%4===0)this.tone([130.81,110,174.61,146.83][Math.floor(this.note/4)%4],1.3,'triangle',.16);this.note++;},
  toggle(){this.init();save.sound=!save.sound;if(this.master)this.master.gain.setTargetAtTime(save.sound?.16:0,this.context.currentTime,.04);persist();syncHome();if(save.sound)this.tone(659,.15);}
};

async function loadAssets(){assetsReady=false;$('loadError').hidden=true;$('startButton').disabled=true;$('startText').textContent='冒険の準備中…';let lastError;for(let attempt=0;attempt<3;attempt++){try{const response=await fetch('../startrail/assets.json',{cache:attempt?'reload':'default'});if(!response.ok)throw new Error('Asset HTTP '+response.status);const data=await response.json();await Promise.all(['hero0','hero1','hero2','hero3','bug0','bug1','tree','hill','cloud','coin','gate','lantern','star','spike'].map(name=>new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>{sprites[name]=img;resolve();};img.onerror=reject;img.src=data[name]||'';})));for(let i=0;i<4;i++){const src=sprites['hero'+i],c=document.createElement('canvas');c.width=src.width;c.height=src.height;const cctx=c.getContext('2d');cctx.drawImage(src,0,0);cctx.globalCompositeOperation='source-atop';cctx.fillStyle='#e6a74b';cctx.globalAlpha=.47;cctx.fillRect(0,0,c.width,c.height);sprites['amber'+i]=c;}assetsReady=true;$('startButton').disabled=false;$('startText').textContent='冒険をはじめる';return;}catch(error){lastError=error;}}console.warn('Lantern Duo assets failed',lastError);$('loadError').hidden=false;$('startText').textContent='もう一度読み込む';}

function clearInputs(){keys.clear();pointers.clear();document.querySelectorAll('.held').forEach(b=>b.classList.remove('held'));}
function isDown(player,action){for(const value of pointers.values())if(value.player===player&&value.action===action)return true;return false;}
function inputs(){return [{move:Number(keys.has('KeyD')||isDown(0,'right'))-Number(keys.has('KeyA')||isDown(0,'left')),jump:keys.has('KeyW')||keys.has('Space')||isDown(0,'jump')},{move:Number(keys.has('ArrowRight')||isDown(1,'right'))-Number(keys.has('ArrowLeft')||isDown(1,'left')),jump:keys.has('ArrowUp')||isDown(1,'jump')}];}
const playKeys=new Set(['KeyA','KeyD','KeyW','Space','ArrowLeft','ArrowRight','ArrowUp','ArrowDown','KeyR']);
window.addEventListener('keydown',e=>{if(e.code==='Escape'){if(e.repeat)return;if($('modal').open){if(modalKind!=='clear')closeModal();}else if(playing)showPause();return;}if(e.code==='KeyM'&&!e.repeat){audio.toggle();return;}if(!playing||paused||!playKeys.has(e.code))return;if(e.ctrlKey||e.metaKey||e.altKey)return;e.preventDefault();if(e.code==='KeyR'&&!e.repeat){game.recall();return;}keys.add(e.code);});
window.addEventListener('keyup',e=>{keys.delete(e.code);if(playing&&!paused&&playKeys.has(e.code))e.preventDefault();});
document.querySelectorAll('[data-player]').forEach(button=>{button.addEventListener('pointerdown',e=>{if(!playing||paused||button.disabled)return;e.preventDefault();audio.init();pointers.set(e.pointerId,{player:Number(button.dataset.player),action:button.dataset.action,button});button.classList.add('held');try{button.setPointerCapture(e.pointerId);}catch{}});const release=e=>{const item=pointers.get(e.pointerId);pointers.delete(e.pointerId);if(item&&!Array.from(pointers.values()).some(v=>v.button===item.button))item.button.classList.remove('held');};button.addEventListener('pointerup',release);button.addEventListener('pointercancel',release);button.addEventListener('lostpointercapture',release);button.addEventListener('contextmenu',e=>e.preventDefault());});
window.addEventListener('blur',()=>{clearInputs();if(playing&&!paused&&game?.state==='playing')showPause();});
document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInputs();snapshot();if(playing&&!paused&&game?.state==='playing')showPause();}});
window.addEventListener('pagehide',snapshot);
document.querySelectorAll('.mode-btn').forEach(b=>b.addEventListener('click',()=>{mode=b.dataset.mode;save.mode=mode;persist();syncHome();audio.init();audio.tone(440,.1);}));
$('startButton').addEventListener('click',()=>startLevel(0,false));
$('continueButton').addEventListener('click',()=>startLevel(Math.min(save.level,save.unlocked-1),true));
$('mapButton').addEventListener('click',showMap);
$('soundButton').addEventListener('click',()=>audio.toggle());
$('helpButton').addEventListener('click',showHelp);
$('pauseButton').addEventListener('click',showPause);
$('recallButton').addEventListener('click',()=>{if(playing&&!paused){audio.init();game.recall();}});
$('reloadAssetsButton').addEventListener('click',loadAssets);
$('fullscreenButton').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('app').requestFullscreen();}catch{$('fullscreenButton').title='このブラウザーは全画面表示に対応していません';}});
if(!document.fullscreenEnabled)$('fullscreenButton').hidden=true;
$('modalClose').addEventListener('click',()=>{if(modalKind==='clear')goHome();else closeModal();});
$('modal').addEventListener('cancel',e=>{e.preventDefault();if(modalKind!=='clear')closeModal();});
$('modal').addEventListener('click',e=>{if(e.target===$('modal')){const r=$('modal').getBoundingClientRect();if((e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)&&modalKind!=='clear')closeModal();}});

function startLevel(index,continuing=false){if(!assetsReady)return;audio.init();clearInputs();if($('modal').open)$('modal').close();modalKind='';game=new Game({level:index,mode,elapsed:continuing?save.elapsed:0,coins:continuing?save.coins:0});playing=true;paused=false;camera=0;particles.length=0;accumulator=0;save.level=index;save.mode=mode;save.started=true;save.elapsed=game.time;save.coins=game.score;persist();$('app').classList.add('playing');$('homeScreen').hidden=true;$('sceneShade').hidden=true;$('liveStats').hidden=false;$('homeStats').hidden=true;syncHome();updateHUD();resize();canvas.focus({preventScroll:true});}
function openModal(kind,title,content,eyebrow='LANTERN DUO'){clearInputs();paused=playing;modalKind=kind;$('modalTitle').textContent=title;$('modalEyebrow').textContent=eyebrow;$('modalContent').replaceChildren();if(typeof content==='string')$('modalContent').innerHTML=content;else $('modalContent').append(content);if(!$('modal').open)$('modal').showModal();}
function closeModal(){if($('modal').open)$('modal').close();modalKind='';paused=false;clearInputs();accumulator=0;if(playing&&game?.state==='clear'){onClear();return;}if(playing)canvas.focus({preventScroll:true});}
function button(label,action,primary=false){const b=document.createElement('button');b.className=primary?'primary-btn':'secondary-btn';b.textContent=label;b.addEventListener('click',action);return b;}
function actions(...buttons){const div=document.createElement('div');div.className='modal-actions';div.append(...buttons);$('modalContent').append(div);}
function showPause(){if(!playing||game?.state==='clear')return;snapshot();openModal('pause','ちょっと、ひとやすみ。',`<p>ステージ ${String(game.levelIndex+1).padStart(2,'0')} · ${game.level.name}</p><p class="help-note">進み具合はステージ単位で保存されます。この画面を閉じると、その場からつづけられます。</p>`,'PAUSED · ふたりを待っています');actions(button('冒険にもどる',closeModal,true),button('中間地点から',()=>{game.retry();closeModal();}));actions(button('あそびかた',showHelp),button('ステージ選択',showMap));const home=button('タイトルへ',goHome);home.className='text-btn';$('modalContent').append(home);}
function goHome(){snapshot();playing=false;paused=false;clearInputs();if($('modal').open)$('modal').close();modalKind='';$('app').classList.remove('playing');$('homeScreen').hidden=false;$('sceneShade').hidden=false;$('liveStats').hidden=true;$('homeStats').hidden=false;$('gameBanner').hidden=true;$('worldLabel').textContent='A SMALL ADVENTURE, TOGETHER.';$('stageLabel').textContent='ふたりで、あの光の向こうへ。';$('objective').textContent='光のかけらを集めて、ふたりで灯台へ。';$('health1').textContent=$('health2').textContent='♥ ♥ ♥';syncHome();resize();}
function showMap(){const content=document.createElement('div');const note=document.createElement('p');note.className='help-note';note.textContent=`${mode==='coop'?'ローカル 2人':'1人 + CPU'} · 4つの世界、12のステージ。クリアすると次の道が開きます。`;content.append(note);WORLDS.forEach((world,wi)=>{const title=document.createElement('div');title.className='map-world';title.textContent=`0${wi+1} / ${world.name}`;content.append(title);const grid=document.createElement('div');grid.className='level-grid';LEVELS.filter(l=>l.world===wi).forEach(l=>{const b=document.createElement('button');b.className='level-button'+(l.id===save.level?' current':'');b.disabled=l.id>=save.unlocked;b.innerHTML=`<strong>${b.disabled?'◇':String(l.id+1).padStart(2,'0')}</strong><span>${b.disabled?'まだとじた道':l.name}</span><small>${'★'.repeat(save.stars[l.id]||0)}${'☆'.repeat(3-(save.stars[l.id]||0))}</small>`;b.setAttribute('aria-label',`ステージ${l.id+1} ${l.name}${b.disabled?' 未開放':''}`);b.addEventListener('click',()=>startLevel(l.id,false));grid.append(b);});content.append(grid);});openModal('map','どこへ、冒険しよう？',content,'WORLD MAP');actions(button(playing?'冒険にもどる':'タイトルにもどる',closeModal));}
function showHelp(){openModal('help','ふたりの、あそびかた。',`<div class="help-row"><strong>PLAYER 1</strong><span><b>A / D</b> で移動、<b>W / Space</b> でジャンプ。</span></div><div class="help-row"><strong>PLAYER 2</strong><span><b>← / →</b> で移動、<b>↑</b> でジャンプ。<br>ひとりモードでは CPU が相棒に。</span></div><div class="help-row"><strong>TOUCH</strong><span>画面下の緑が1P、金色が2P。ふたり同時に、移動とジャンプを押せます。</span></div><div class="help-row"><strong>TOGETHER</strong><span>ふたつの床スイッチを同時に踏むと扉が開きます。光の泡になった仲間は、触れると復活。</span></div><div class="help-row"><strong>EXPLORE</strong><span>ジャンプは長押しで高く、短押しで低く。敵は上から踏もう。ふたりそろって灯台へ。星は3つの寄り道チャレンジ。集めなくてもクリアできます。</span></div><p class="help-note">Esc：一時停止 / R：パートナーを呼ぶ / M：音の切り替え。中間地点の灯りをともせば、失敗してもそこから再挑戦できます。ひとつの端末・ひとつの画面で遊ぶゲームです。</p>`,'HOW TO PLAY');actions(button(playing?'冒険にもどる':'わかった！',closeModal,true));}
function onClear(){paused=true;snapshot();save.unlocked=Math.max(save.unlocked,Math.min(LEVELS.length,game.levelIndex+2));save.stars[game.levelIndex]=Math.max(save.stars[game.levelIndex]||0,game.starCount);save.completed=save.completed||game.levelIndex===LEVELS.length-1;save.level=Math.min(LEVELS.length-1,game.levelIndex+1);persist();const final=game.levelIndex===LEVELS.length-1;openModal('clear',final?'世界に、灯りがともった。':'ふたりで、たどりついた！',`<p>${game.level.name} · STAGE CLEAR</p><div class="result-stars" aria-label="星 ${game.starCount} 個">${'★'.repeat(game.starCount)}${'☆'.repeat(3-game.starCount)}</div><div class="result-stats"><div><span>ステージタイム</span><strong>${formatTime(game.stageTime)}</strong></div><div><span>集めたコイン</span><strong>${game.score}</strong></div><div><span>ここまでの冒険</span><strong>${formatTime(game.time)}</strong></div></div><p>${final?'12の道を越えて、ふたりの灯台が輝きました。星を探しに、もう一度冒険へ。':'次のステージへの道が開きました。息を合わせて、もうひとつ先へ。'}</p>`,final?'THE LIGHT WE SHARE':'A LITTLE CLOSER, TOGETHER');if(!final)actions(button('次のステージへ',()=>startLevel(game.levelIndex+1,true),true),button('ステージ選択',showMap));else actions(button('ステージ選択',showMap,true),button('タイトルへ',goHome));}

function resize(){const r=canvas.getBoundingClientRect();const dpr=Math.min(window.devicePixelRatio||1,2);canvas.width=Math.max(1,Math.round(r.width*dpr));canvas.height=Math.max(1,Math.round(r.height*dpr));viewWidth=playing?1100:1200;viewHeight=viewWidth*r.height/Math.max(1,r.width);ctx.imageSmoothingEnabled=false;}
new ResizeObserver(resize).observe($('scene'));
function sprite(name,x,y,w,h,flip=false,alpha=1){const img=sprites[name];if(!img)return;ctx.save();ctx.globalAlpha=alpha;ctx.translate(Math.round(x+(flip?w:0)),Math.round(y));if(flip)ctx.scale(-1,1);ctx.drawImage(img,0,0,w,h);ctx.restore();}
function rect(x,y,w,h,color){ctx.fillStyle=color;ctx.fillRect(Math.round(x),Math.round(y),Math.ceil(w),Math.ceil(h));}
function glow(x,y,r,color){const g=ctx.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,color);g.addColorStop(1,'transparent');ctx.fillStyle=g;ctx.fillRect(x-r,y-r,r*2,r*2);}
function textAt(str,x,y,color='#f0f7e4',size=14,align='center'){ctx.fillStyle=color;ctx.font=`600 ${size}px system-ui, sans-serif`;ctx.textAlign=align;ctx.fillText(str,x,y);}
function background(world,cam,base,home=false){const vh=viewHeight,vw=viewWidth,night=home||game?.level.world===3;const grad=ctx.createLinearGradient(0,0,0,vh);grad.addColorStop(0,home?'#183743':world.sky);grad.addColorStop(.68,home?'#315c61':world.far);grad.addColorStop(1,home?'#2b5656':world.near);ctx.fillStyle=grad;ctx.fillRect(0,0,vw,vh);if(night){for(let i=0;i<45;i++){const x=((i*193+Math.sin(i*6)*60-cam*.035)%(vw+70)+vw+70)%(vw+70),y=25+(i*71)%(Math.max(150,base-140));rect(x,y,i%7===0?3:2,i%7===0?3:2,`rgba(220,241,209,${.2+.35*(1+Math.sin(renderTime*.7+i))*.5})`);}}
  const sunX=home?vw*.83:vw*.8, sunY=home?Math.min(base*.31,180):Math.min(145,base*.24);glow(sunX,sunY,110,night?'#b4efc514':'#fff3d722');ctx.fillStyle=home?'#dbe8bc':world.accent;ctx.beginPath();ctx.arc(sunX,sunY,home?36:32,0,Math.PI*2);ctx.fill();if(home){ctx.fillStyle='#264953';ctx.beginPath();ctx.arc(sunX-12,sunY-10,31,0,Math.PI*2);ctx.fill();}
  for(let layer=0;layer<3;layer++){const speed=[.08,.16,.3][layer],spacing=layer===0?390:310,color=home?['#365e66','#2c535b','#244951'][layer]:[world.far,world.near,world.soil][layer];ctx.save();ctx.globalAlpha=[.35,.48,.33][layer];for(let i=-1;i<Math.ceil(vw/spacing)+2;i++){const worldI=Math.floor(cam*speed/spacing)+i,x=i*spacing-(cam*speed%spacing),h=90+((worldI*93+layer*29)%140+140)%140;ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(x-90,base+25);ctx.lineTo(x+spacing*.15,base-h*.6);ctx.lineTo(x+spacing*.42,base-h);ctx.lineTo(x+spacing*.57,base-h*.68);ctx.lineTo(x+spacing*.8,base-h*.85);ctx.lineTo(x+spacing+60,base+25);ctx.closePath();ctx.fill();}ctx.restore();}
  for(let i=-1;i<6;i++){const x=i*330-((cam*.23)%330);sprite('cloud',x,70+(i%3)*47,176,64,false,night?.11:.36);}for(let i=-1;i<9;i++){const x=i*200-((cam*.4)%200),variation=((i+Math.floor(cam*.4/200))*71)%3;sprite('tree',x,base-160-variation*13,150+variation*10,180+variation*13,false,home?.42:.38);}for(let i=0;i<14;i++){const x=(i*179-cam*.7+Math.sin(renderTime*.25+i)*40)%(vw+200),y=base-45-((i*57)%170)+Math.sin(renderTime+i)*10;rect(x,y,3,3,night?'#e9d87d88':'#f5eeb866');}}

function drawPlatform(p,base,cam,world){if(p.hidden)return;let x=p.x-cam,y=base-p.z,w=p.w,h=p.h;if(x>viewWidth+60||x+w<-60)return;const left=Math.max(-60,x),right=Math.min(viewWidth+60,x+w),top=p.kind==='crumble'?'#d5b897':p.kind==='moving'?'#d6daf3':world.grass;rect(left,y,right-left,h,world.soil);rect(left,y,right-left,7,top);rect(left,y+7,right-left,5,p.kind==='ground'?world.near:'#58716c');if(p.kind==='ground'){rect(left,y+12,right-left,13,world.near+'88');for(let xx=Math.floor((left+cam)/55)*55-cam;xx<right;xx+=55){rect(xx+7,y+18+(Math.floor((xx+cam)/55)%3)*8,10,5,'#10253235');rect(xx+29,y+46,15,6,'#10253240');if(xx>=x+8&&xx+30<x+w){rect(xx+15,y-5,3,5,top);rect(xx+23,y-3,3,3,top);}}rect(x,y+7,6,h-7,'#1027353a');}else{rect(x+4,y+h-4,w-8,4,'#10253566');if(p.kind==='crumble'){ctx.strokeStyle='#79666c';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x+w*.3,y+7);ctx.lineTo(x+w*.4,y+14);ctx.lineTo(x+w*.33,y+h);ctx.moveTo(x+w*.72,y+7);ctx.lineTo(x+w*.66,y+17);ctx.stroke();if(p.timer>0)glow(x+w/2,y,65,'#ffb4863c');}if(p.kind==='moving'){rect(x+12,y+14,w-24,3,'#a8d8e29a');textAt('‹   ›',x+w/2,y+20,'#ecf3fe',11);}}}

function drawPlayer(p,base,cam,scale=1,home=false){const x=p.x-cam,y=base-p.z;const mint=p.id===0,color=mint?'#a1e7ba':'#f2ce7e';if(p.bubble){glow(x,y-30,53,mint?'#a8e7dc33':'#ffe3b133');ctx.strokeStyle=mint?'#b2f0db':'#f6daa2';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y-26,29,0,Math.PI*2);ctx.stroke();sprite(mint?'hero0':'amber0',x-13,y-44,26,34,false,.7);rect(x-15,y-44,4,4,'#fff9');textAt(`${p.id+1}P`,x,y-67,color,12);return;}
  if(!home){ctx.save();ctx.globalAlpha=.17;ctx.fillStyle='#061723';ctx.beginPath();ctx.ellipse(x,base-Math.max(0,p.z)+3,16,4,0,0,Math.PI*2);ctx.fill();ctx.restore();}
  const frame=home?(Math.floor(renderTime*2)%2):(!p.grounded?2:Math.abs(p.vx)>15?Math.floor(renderTime*10)%4:0);const bob=home?Math.sin(renderTime*1.8+p.id)*2:0;const alpha=p.invulnerable>0&&!home&&Math.floor(renderTime*12)%2===0?.45:1;const width=40*scale,height=H*scale+8*scale;glow(x,y-height*.3,width*1.4,mint?'#a1e7ba0e':'#f2ce7e0e');sprite((mint?'hero':'amber')+frame,x-width/2,y-height+bob,width,height,p.facing<0,alpha);if(home){sprite('lantern',x+width*.19,y-height*.51,22*scale,30*scale);glow(x+width*.43,y-height*.2,45*scale,'#ffe6a42c');}else {rect(x-11,y-height-17,22,12,mint?'#214d42':'#675531');textAt(`${p.id+1}P`,x,y-height-7,color,10);}}

function drawHome(){const world=WORLDS[3],base=viewHeight-54;background(world,renderTime*4,base,true);const compact=viewHeight>850;const islandY=compact?viewHeight*.58:base-80;const islandX=compact?780:685;drawPlatform({x:islandX-80,z:base-islandY,w:420,h:Math.max(100,viewHeight-islandY+40),kind:'ground'},base,0,{...world,grass:'#91c7a4',near:'#4c8470',soil:'#203d48'});sprite('tree',1100,islandY-270,260,300,false,.65);sprite('tree',520,base-180,180,230,false,.3);sprite('gate',1080,islandY-183,120,190,false,.52);glow(1140,islandY-95,125,'#f8d99027');for(let i=0;i<5;i++)sprite('coin',islandX+65+i*55,islandY-190-Math.sin(i*.65)*32,20,20,false,.7);const p1={id:0,x:islandX+45,z:base-islandY,vx:0,facing:1,grounded:true},p2={...p1,id:1,x:islandX+175,z:p1.z+21,facing:-1};drawPlayer(p1,base,0,2.55,true);drawPlayer(p2,base,0,2.55,true);for(let i=0;i<3;i++)sprite('star',islandX+230+i*45,islandY-275+Math.sin(renderTime+i)*7,16,16,false,.8);rect(0,base+35,viewWidth,50,'#0d263566');}

function drawGame(){const world=WORLDS[game.level.world]||WORLDS[0],alive=game.players.filter(p=>!p.bubble),visible=alive.length?alive:game.players,mid=visible.reduce((sum,p)=>sum+p.x,0)/visible.length;const target=clamp(mid-viewWidth*.42,0,Math.max(0,game.level.width-viewWidth));camera+=(target-camera)*Math.min(1,.13);const high=Math.max(0,...visible.map(p=>p.z));const base=viewHeight-85+Math.max(0,high-(viewHeight-240))*.6;background(world,camera,base);for(const p of game.platforms)drawPlatform(p,base,camera,world);
  for(const s of game.springs){const x=s.x-camera,y=base-s.z;if(x<-70||x>viewWidth+70)continue;rect(x,y-10,s.w,10,'#7797a3');ctx.strokeStyle=world.accent;ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(x+5,y-10);for(let i=0;i<5;i++)ctx.lineTo(x+8+i*10,y-15-(i%2)*9);ctx.stroke();rect(x-2,y-30,s.w+4,7,world.accent);}
  for(const s of game.spikes){const x=s.x-camera,y=base-s.z;if(x<-80||x>viewWidth+80)continue;sprite('spike',x,y-(s.active?s.h:5),s.w,s.active?s.h:5,false,s.active?1:.45);if(s.timed){rect(x+4,y+3,s.w-8,3,s.active?'#e99896':'#9dcdad');}}
  for(const gate of game.gates){const x=gate.x-camera,y=base-gate.z;if(x<-400||x>viewWidth+400)continue;for(let pi=0;pi<gate.plates.length;pi++){const plate=gate.plates[pi],px=plate.x-camera,py=base-plate.z,color=pi===0?'#a1e7ba':'#f2ce7e';rect(px,py-6,plate.w,6,plate.pressed?color:'#506a70');rect(px+3,py-10,plate.w-6,4,plate.pressed?'#efffe0':color);if(plate.pressed)glow(px+plate.w/2,py,45,color+'55');textAt('◆',px+plate.w/2,py-21,color,14);ctx.save();ctx.setLineDash([3,7]);ctx.strokeStyle=plate.pressed?color+'aa':'#b8daca44';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(px+plate.w/2,py-2);ctx.lineTo(x+gate.w/2,py-2);ctx.stroke();ctx.restore();}rect(x-6,y-gate.h-12,gate.w+12,12,'#466271');rect(x-6,y-gate.h,7,gate.h,'#527782');rect(x+gate.w-1,y-gate.h,7,gate.h,'#527782');if(!gate.open){glow(x+gate.w/2,y-gate.h*.5,80,'#a7ebdd17');for(let yy=0;yy<gate.h;yy+=18)rect(x+4,y-yy-10,gate.w-8,4,Math.floor(renderTime*3)%2?'#a3e6c2cc':'#d4ecb699');textAt('ふたりでスイッチ',x-115,y-gate.h-32,'#edf5dc',13);rect(x-65,y-gate.h-22,165,4,'#132c3b66');rect(x-65,y-gate.h-22,165*clamp(gate.charge,0,1),4,'#b9eab1');}else{sprite('star',x+8,y-gate.h-28,20,20);}}
  for(const cp of game.checkpoints){const x=cp.x-camera,y=base-cp.z;if(x<-100||x>viewWidth+100)continue;rect(x-3,y-93,6,93,'#557780');rect(x-9,y-4,18,4,'#b4b8aa');sprite('lantern',x-12,y-109,24,33,false,cp.active?1:.5);if(cp.active){glow(x,y-88,65,'#ffe8aa33');textAt('CHECKPOINT',x,y-120,'#e6eed8',9);}else{rect(x+3,y-85,24,15,'#85b7aa');}}
  for(const c of game.coins){if(c.taken)continue;const x=c.x-camera,y=base-c.z+Math.sin(renderTime*3+c.x*.01)*3;if(x<-30||x>viewWidth+30)continue;sprite('coin',x-11,y-11,22,22);}
  for(const s of game.stars){if(s.taken)continue;const x=s.x-camera,y=base-s.z+Math.sin(renderTime*2+s.x)*6;if(x<-60||x>viewWidth+60)continue;glow(x,y,40,'#ffe19a33');sprite('star',x-15,y-15,30,30);}
  for(const e of game.enemies){if(!e.alive)continue;const x=e.x-camera,y=base-e.z;if(x<-120||x>viewWidth+120)continue;const alpha=e.invulnerable>0&&Math.floor(renderTime*14)%2?.45:1;if(e.kind==='boss'){glow(x,y-e.h*.5,85,'#ffa98814');sprite('bug'+Math.floor(renderTime*5)%2,x-e.w/2-7,y-e.h,e.w+14,e.h,(e.dir||1)<0,alpha);rect(x-e.w/2,y-e.h-22,e.w,5,'#173341');rect(x-e.w/2,y-e.h-22,e.w*e.hp/e.maxHp,5,'#f2ce7e');for(let i=0;i<3;i++)rect(x-18+i*15,y-e.h-8-(i===1?7:0),9,11,'#e8c17e');}else{sprite('bug'+Math.floor(renderTime*7)%2,x-e.w/2,y-e.h,e.w,e.h,(e.dir||1)<0,alpha);if(e.kind==='hopper'){rect(x-7,y-e.h-5,4,6,'#f1c48c');rect(x+4,y-e.h-5,4,6,'#f1c48c');}}}
  const fx=game.finish-camera;if(fx>-180&&fx<viewWidth+180){glow(fx,base-100,160,'#ffda9929');rect(fx-46,base-160,92,160,'#567681');rect(fx-55,base-170,110,12,'#bdd5b1');rect(fx-34,base-148,68,20,'#dce8bd');for(let i=0;i<3;i++)rect(fx-34,base-112+i*30,68,6,'#789794');sprite('gate',fx-48,base-126,96,128);sprite('lantern',fx-18,base-220,36,50);glow(fx,base-188,80,'#ffe9a777');textAt('ふたりで、ここへ。',fx,base-239,world.accent,13);}
  const p0=game.players[0],p1=game.players[1];if(!p0.bubble&&!p1.bubble&&Math.abs(p0.x-p1.x)>570){ctx.save();ctx.setLineDash([4,9]);ctx.strokeStyle='#deefd888';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(p0.x-camera,base-p0.z-H*.5);ctx.lineTo(p1.x-camera,base-p1.z-H*.5);ctx.stroke();ctx.restore();}
  for(const p of game.players)drawPlayer(p,base,camera);for(const p of particles){rect(p.x-camera,base-p.z,p.size,p.size,p.color);}const progress=clamp(mid/game.finish,0,1);rect(0,viewHeight-3,viewWidth,3,'#10293788');rect(0,viewHeight-3,viewWidth*progress,3,world.grass);}

function effect(name){audio.event(name);if(['coin','star','rescue','stomp','checkpoint'].includes(name)){const p=game.players.find(p=>!p.bubble)||game.players[0];for(let i=0;i<(name==='star'?18:7);i++){const a=Math.random()*Math.PI*2;particles.push({x:p.x,z:p.z+30,vx:Math.cos(a)*70,vz:Math.sin(a)*70+30,life:.55+Math.random()*.3,size:name==='star'?4:3,color:i%2?'#f8db93':'#b9edca'});}}}
function updateHUD(){if(!game)return;const world=WORLDS[game.level.world];$('worldLabel').textContent=`WORLD 0${game.level.world+1} / ${world.name}`;$('stageLabel').textContent=`${String(game.levelIndex+1).padStart(2,'0')} — ${game.level.name}`;$('coinCount').textContent=game.score;$('starCount').textContent='★'.repeat(game.starCount)+'☆'.repeat(3-game.starCount);$('starCount').setAttribute('aria-label',`星 ${game.starCount} / 3`);$('timeCount').textContent=formatTime(game.stageTime);game.players.forEach((p,i)=>{$('health'+(i+1)).textContent=p.bubble?'◇ 復活待ち':'♥'.repeat(p.health)+'♡'.repeat(Math.max(0,3-p.health));});$('objective').textContent=game.players.some(p=>p.bubble)?'光の泡に触れて、仲間を助けよう。':game.level.brief;$('gameBanner').hidden=game.bannerTime<=0||paused;if(game.bannerTime>0)$('gameBanner').textContent=game.banner;}
function frame(now){const dt=Math.min(.05,Math.max(0,(now-lastFrame)/1000));lastFrame=now;renderTime+=dt;if(playing&&!paused&&game?.state==='playing'){accumulator+=dt;while(accumulator>=1/60){game.step(1/60,inputs());for(const event of game.events)effect(event);accumulator-=1/60;if(game.state==='clear'){onClear();break;}}for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.life-=dt;p.x+=p.vx*dt;p.z+=p.vz*dt;p.vz-=120*dt;if(p.life<=0)particles.splice(i,1);}hudClock+=dt;saveClock+=dt;if(hudClock>.1){updateHUD();hudClock=0;}if(saveClock>8){snapshot();saveClock=0;}audio.update();}ctx.setTransform(canvas.width/viewWidth,0,0,canvas.height/viewHeight,0,0);ctx.imageSmoothingEnabled=false;if(playing&&game)drawGame();else drawHome();requestAnimationFrame(frame);}

syncHome();resize();loadAssets();requestAnimationFrame(frame);
