(() => {
'use strict';
const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const id=Math.max(1,Math.min(100,Number(new URLSearchParams(location.search).get('id'))||1));
const root=$('#tool-main'); const KEY=`mg20-app100-tool-${id}`; let cleanup=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const load=(fallback={})=>{try{return JSON.parse(localStorage.getItem(KEY)||JSON.stringify(fallback))}catch(_){return fallback}};
const save=v=>localStorage.setItem(KEY,JSON.stringify(v));
const today=()=>new Date().toISOString().slice(0,10); const nowLocal=()=>new Date().toISOString().slice(0,16);
const days=(a,b)=>Math.ceil((new Date(a)-new Date(b))/(864e5)); const money=n=>`¥${Math.round(Number(n)||0).toLocaleString('ja-JP')}`;
const fmtSec=n=>{n=Math.max(0,Math.floor(n));return `${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`};
const field=(name,label,type='text',opts='')=>`<label class="field"><span>${esc(label)}</span>${type==='textarea'?`<textarea name="${name}" ${opts}></textarea>`:`<input name="${name}" type="${type}" ${opts}>`}</label>`;
const select=(name,label,arr)=>`<label class="field"><span>${esc(label)}</span><select name="${name}">${arr.map(x=>`<option value="${esc(Array.isArray(x)?x[0]:x)}">${esc(Array.isArray(x)?x[1]:x)}</option>`).join('')}</select></label>`;
const panel=(title,body,cls='')=>`<section class="tool-panel ${cls}"><h2>${esc(title)}</h2>${body}</section>`;
const btn=(text,cls='tool-btn',attrs='')=>`<button class="${cls}" type="button" ${attrs}>${esc(text)}</button>`;
function clearCleanup(){cleanup.forEach(fn=>{try{fn()}catch(_){}});cleanup=[]}
async function metadata(){
  try{
    const text=await fetch('apps.js',{cache:'no-store'}).then(r=>r.text());
    const re=/\['([^']*)','([^']*)','([^']*)','([^']*)','([^']*)'\]/g; const out=[]; let m;
    while((m=re.exec(text)))out.push({name:m[1],category:m[2],desc:m[3],difficulty:m[4],money:m[5]});
    return out[id-1]||{name:`APP ${id}`,category:'アプリ',desc:'実装版Webアプリ'};
  }catch(_){return{name:`APP ${id}`,category:'アプリ',desc:'実装版Webアプリ'}}
}
function formValues(form){return Object.fromEntries(new FormData(form).entries())}
function itemList(items,summary){return `<div class="item-list">${items.length?items.map((x,i)=>`<div class="item"><div class="item-main">${summary(x,i)}</div><div class="item-actions"><button class="mini" data-del="${i}" type="button">削除</button></div></div>`).join(''):'<p class="subtle">まだデータがありません。</p>'}</div>`}
function bindDeletes(state,render){$$('[data-del]',root).forEach(b=>b.onclick=()=>{state.items.splice(Number(b.dataset.del),1);save(state);render()})}
function crud(cfg){
 let state=load({items:[]}); if(!Array.isArray(state.items))state={items:[]};
 const render=()=>{
   const fields=cfg.fields.map(f=>f.type==='select'?select(f.key,f.label,f.options):field(f.key,f.label,f.type||'text',f.attrs||'')).join('');
   let items=[...state.items]; if(cfg.sort)items.sort(cfg.sort);
   root.innerHTML=panel(cfg.formTitle||'追加',`<form id="crud-form"><div class="tool-grid">${fields}</div><div class="tool-actions"><button class="tool-btn primary" type="submit">保存</button></div></form>`)+
    (cfg.stats?panel('集計',cfg.stats(state.items)):'')+panel(cfg.listTitle||'一覧',itemList(items,(x,i)=>cfg.summary(x,i)));
   $('#crud-form').onsubmit=e=>{e.preventDefault();const v=formValues(e.currentTarget);v.createdAt=Date.now();state.items.unshift(v);save(state);render()};
   $$('[data-del]',root).forEach(b=>b.onclick=()=>{const shown=items[Number(b.dataset.del)];state.items.splice(state.items.indexOf(shown),1);save(state);render()});
   cfg.after?.(state,render,items);
 }; render();
}
function checklist(cfg){
 let state=load({items:(cfg.defaults||[]).map(t=>({text:t,done:false}))}); if(!Array.isArray(state.items))state.items=[];
 const render=()=>{const done=state.items.filter(x=>x.done).length;root.innerHTML=panel(cfg.title||'チェックリスト',`<div class="progress"><i style="width:${state.items.length?done/state.items.length*100:0}%"></i></div><p class="subtle">${done} / ${state.items.length} 完了</p><form id="add-check"><div class="tool-grid"><label class="field"><span>項目</span><input name="text" required></label>${cfg.extraField||''}</div><div class="tool-actions"><button class="tool-btn primary" type="submit">追加</button><button id="reset-check" class="tool-btn" type="button">全部未完了に戻す</button></div></form>`)+panel('項目',`<div class="check-grid">${state.items.map((x,i)=>`<button class="check-tile ${x.done?'done':''}" data-check="${i}" type="button">${esc(x.text)}</button>`).join('')}</div>`);
 $('#add-check').onsubmit=e=>{e.preventDefault();const v=formValues(e.currentTarget);if(v.text.trim())state.items.push({text:v.text.trim(),done:false,...v});save(state);render()};
 $$('[data-check]',root).forEach(b=>b.onclick=()=>{state.items[Number(b.dataset.check)].done=!state.items[Number(b.dataset.check)].done;save(state);render()});
 $('#reset-check').onclick=()=>{state.items.forEach(x=>x.done=false);save(state);render()}; cfg.after?.(state,render);
 };render();
}
function countdown(cfg){
 let state=load({seconds:(cfg.defaultMinutes||5)*60,running:false,endAt:0,label:cfg.label||''}); let tick=0;
 const getRemain=()=>state.running?Math.max(0,Math.ceil((state.endAt-Date.now())/1000)):state.seconds;
 const render=()=>{const r=getRemain();root.innerHTML=panel(cfg.title||'タイマー',`<div id="timer-face" class="timer-face ${state.running&&r===0?'over':''}"><strong id="timer-value">${fmtSec(r)}</strong><small>${esc(state.label||cfg.subtitle||'')}</small></div><div class="tool-grid"><label class="field"><span>分</span><input id="timer-min" type="number" min="1" max="720" value="${Math.max(1,Math.round(r/60)||cfg.defaultMinutes||5)}"></label>${cfg.labelInput?`<label class="field"><span>名前</span><input id="timer-label" value="${esc(state.label||'')}"></label>`:''}</div><div class="tool-actions"><button id="timer-start" class="tool-btn primary" type="button">${state.running?'一時停止':'開始'}</button><button id="timer-reset" class="tool-btn" type="button">リセット</button></div><p id="timer-alert" class="notice ${r===0?'danger':''}">${r===0?'時間です。':'終了するとこの画面で通知します。'}</p>`);
 $('#timer-start').onclick=()=>{if(state.running){state.seconds=getRemain();state.running=false}else{state.seconds=Math.max(60,Number($('#timer-min').value)*60||60);state.label=$('#timer-label')?.value||state.label;state.endAt=Date.now()+state.seconds*1000;state.running=true}save(state);render()};
 $('#timer-reset').onclick=()=>{state={seconds:(cfg.defaultMinutes||5)*60,running:false,endAt:0,label:''};save(state);render()};
 };
 const update=()=>{if(!state.running)return;const r=getRemain();const v=$('#timer-value');if(v)v.textContent=fmtSec(r);if(r<=0){state.running=false;state.seconds=0;save(state);render();try{navigator.vibrate?.([150,80,150])}catch(_){}}};
 render();tick=setInterval(update,500);cleanup.push(()=>clearInterval(tick));
}
async function readImage(file){return new Promise((resolve,reject)=>{const fr=new FileReader();fr.onerror=reject;fr.onload=()=>{const img=new Image();img.onload=()=>{const scale=Math.min(1,800/img.width,800/img.height),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.68))};img.src=fr.result};fr.readAsDataURL(file)})}
function photoLog(cfg){
 let state=load({items:[]});const render=()=>{root.innerHTML=panel('記録を追加',`<form id="photo-form"><div class="tool-grid">${field('title',cfg.titleLabel||'名前')}${field('note','メモ','textarea')}<label class="field"><span>写真</span><input name="photo" type="file" accept="image/*" capture="environment"></label></div><div class="tool-actions"><button class="tool-btn primary" type="submit">保存</button>${cfg.geo?'<button id="geo-now" class="tool-btn" type="button">現在地を入力</button>':''}</div><input id="geo-hidden" type="hidden"></form>`)+panel('記録',itemList(state.items,x=>`<strong>${esc(x.title)}</strong><small>${esc(x.note||'')}${x.geo?` / ${esc(x.geo)}`:''}</small>${x.image?`<img class="photo-preview" src="${x.image}" alt="記録写真">`:''}`));
 $('#photo-form').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),f=fd.get('photo');const item={title:fd.get('title'),note:fd.get('note'),geo:$('#geo-hidden').value,createdAt:Date.now()};if(f&&f.size)try{item.image=await readImage(f)}catch(_){}state.items.unshift(item);try{save(state)}catch(_){item.image='';save(state)}render()};
 if($('#geo-now'))$('#geo-now').onclick=()=>navigator.geolocation?.getCurrentPosition(p=>{$('#geo-hidden').value=`${p.coords.latitude.toFixed(6)}, ${p.coords.longitude.toFixed(6)}`;$('#geo-now').textContent='現在地を取得済み'},()=>{$('#geo-now').textContent='位置情報を取得できません'});bindDeletes(state,render)};render();
}
function realtimeBoard(cfg){
 let state=load({items:[]}),channel=null,client=null,room='';
 const render=()=>{root.innerHTML=panel('共有ルーム',`<div class="room-box"><input id="room-code" maxlength="12" placeholder="ROOM CODE" value="${esc(room)}"><button id="room-connect" class="tool-btn primary" type="button">接続</button><button id="room-new" class="tool-btn" type="button">コード生成</button></div><p id="share-status" class="share-status">未接続。ローカルだけでも使えます。</p>`)+panel(cfg.formTitle||'投稿',`<form id="share-form"><div class="tool-grid">${cfg.fields.map(f=>f.type==='select'?select(f.key,f.label,f.options):field(f.key,f.label,f.type||'text')).join('')}</div><div class="tool-actions"><button class="tool-btn primary" type="submit">追加・共有</button></div></form>`)+panel(cfg.listTitle||'共有一覧',itemList(state.items,x=>cfg.summary(x)));
 $('#room-new').onclick=()=>{$('#room-code').value=Math.random().toString(36).slice(2,8).toUpperCase()};
 $('#room-connect').onclick=async()=>{room=$('#room-code').value.trim().toUpperCase().replace(/[^A-Z0-9_-]/g,'').slice(0,12);if(!room)return;try{const c=window.SUPABASE_CONFIG;if(!c?.url||!window.supabase)throw new Error('config');client=window.supabase.createClient(c.url,c.publishableKey||c.anonKey);channel=client.channel(`app100:${id}:${room.toLowerCase()}`,{config:{broadcast:{self:false}}});channel.on('broadcast',{event:'state'},p=>{if(Array.isArray(p.payload?.items)){state.items=p.payload.items;save(state);render();setTimeout(connectAgain,0)}}).on('broadcast',{event:'sync'},()=>channel.send({type:'broadcast',event:'state',payload:{items:state.items}}));await channel.subscribe(s=>{const st=$('#share-status');if(st){st.textContent=s==='SUBSCRIBED'?`ROOM ${room} 接続中`:`接続: ${s}`;st.classList.toggle('connected',s==='SUBSCRIBED')}if(s==='SUBSCRIBED')channel.send({type:'broadcast',event:'sync',payload:{}})});cleanup.push(()=>client?.removeChannel(channel))}catch(_){const st=$('#share-status');if(st)st.textContent='オンライン接続に失敗しました。ローカルモードで継続できます。'}};
 function connectAgain(){if(!room)return;setTimeout(()=>$('#room-connect')?.click(),0)}
 $('#share-form').onsubmit=e=>{e.preventDefault();const item={...formValues(e.currentTarget),createdAt:Date.now()};state.items.unshift(item);save(state);channel?.send({type:'broadcast',event:'state',payload:{items:state.items}});render();if(room)setTimeout(connectAgain,0)};
 $$('[data-del]',root).forEach(b=>b.onclick=()=>{state.items.splice(Number(b.dataset.del),1);save(state);channel?.send({type:'broadcast',event:'state',payload:{items:state.items}});render();if(room)setTimeout(connectAgain,0)});
 };
 render();
}
function splitExpenses(){let state=load({people:['A','B'],items:[]});const render=()=>{const balances={};state.people.forEach(p=>balances[p]=0);const total=state.items.reduce((s,x)=>s+(Number(x.amount)||0),0),share=state.people.length?total/state.people.length:0;state.people.forEach(p=>balances[p]=-share);state.items.forEach(x=>balances[x.payer]=(balances[x.payer]||0)+(Number(x.amount)||0));const creditors=Object.entries(balances).filter(x=>x[1]>0).sort((a,b)=>b[1]-a[1]),debtors=Object.entries(balances).filter(x=>x[1]<0).sort((a,b)=>a[1]-b[1]),trans=[];let ci=0,di=0;while(ci<creditors.length&&di<debtors.length){const pay=Math.min(creditors[ci][1],-debtors[di][1]);if(pay>0)trans.push(`${debtors[di][0]} → ${creditors[ci][0]} ${money(pay)}`);creditors[ci][1]-=pay;debtors[di][1]+=pay;if(creditors[ci][1]<1)ci++;if(debtors[di][1]>-1)di++}
 root.innerHTML=panel('メンバー',`<form id="people-form"><div class="tool-grid"><label class="field"><span>名前（カンマ区切り）</span><input name="people" value="${esc(state.people.join(','))}"></label></div><div class="tool-actions"><button class="tool-btn" type="submit">更新</button></div></form>`)+panel('支払いを追加',`<form id="expense-form"><div class="tool-grid">${select('payer','支払った人',state.people)}${field('amount','金額','number','min="0" step="1" required')}${field('memo','内容')}</div><div class="tool-actions"><button class="tool-btn primary" type="submit">追加</button></div></form>`)+panel('精算結果',`<p class="big-number">${money(total)}</p><div class="item-list">${trans.length?trans.map(t=>`<div class="item"><div class="item-main"><strong>${esc(t)}</strong></div></div>`).join(''):'<p class="subtle">精算はありません。</p>'}</div>`)+panel('支払い履歴',itemList(state.items,x=>`<strong>${esc(x.payer)} / ${money(x.amount)}</strong><small>${esc(x.memo||'')}</small>`));
 $('#people-form').onsubmit=e=>{e.preventDefault();state.people=formValues(e.currentTarget).people.split(',').map(x=>x.trim()).filter(Boolean);save(state);render()};$('#expense-form').onsubmit=e=>{e.preventDefault();state.items.unshift(formValues(e.currentTarget));save(state);render()};bindDeletes(state,render)};render()}
function miniCalculator(kind){
 if(kind==='budget'){let s=load({budget:200000,spent:0});const render=()=>{const d=new Date(),remaining=new Date(d.getFullYear(),d.getMonth()+1,0).getDate()-d.getDate()+1,left=Math.max(0,Number(s.budget)-Number(s.spent)),daily=left/remaining;root.innerHTML=panel('今月の予算',`<div class="tool-grid">${field('budget','月予算','number')}${field('spent','今月使った額','number')}</div><div class="tool-actions"><button id="calc-save" class="tool-btn primary">計算・保存</button></div>`)+panel('今日使える目安',`<div class="big-number">${money(daily)}</div><p class="subtle">残り ${remaining}日 / 残額 ${money(left)}</p>`);$$('input',root).forEach(i=>i.value=s[i.name]);$('#calc-save').onclick=()=>{s={budget:Number($('[name=budget]').value),spent:Number($('[name=spent]').value)};save(s);render()}};render();return}
 if(kind==='tax'){let s=load({salary:6000000,side:0,deductions:1200000});const render=()=>{const taxable=Math.max(0,Number(s.salary)+Number(s.side)-Number(s.deductions));let incomeTax=0;if(taxable<=1950000)incomeTax=taxable*.05;else if(taxable<=3300000)incomeTax=taxable*.1-97500;else if(taxable<=6950000)incomeTax=taxable*.2-427500;else if(taxable<=9000000)incomeTax=taxable*.23-636000;else if(taxable<=18000000)incomeTax=taxable*.33-1536000;else incomeTax=taxable*.4-2796000;incomeTax=Math.max(0,incomeTax);const resident=taxable*.1;root.innerHTML=panel('概算入力',`<div class="tool-grid">${field('salary','給与・本業収入','number')}${field('side','副収入','number')}${field('deductions','控除の概算','number')}</div><div class="tool-actions"><button id="tax-save" class="tool-btn primary">概算</button></div><p class="notice warn">資金計画用の非常に粗い概算です。実際の税額・申告には使わないでください。</p>`)+panel('概算',`<div class="big-number">${money(incomeTax+resident)}</div><p class="subtle">所得税概算 ${money(incomeTax)} / 住民税概算 ${money(resident)}</p>`);$$('input',root).forEach(i=>i.value=s[i.name]);$('#tax-save').onclick=()=>{s={salary:+$('[name=salary]').value,side:+$('[name=side]').value,deductions:+$('[name=deductions]').value};save(s);render()}};render();return}
}
function savingsChallenge(){let s=load({days:30,amount:500,done:[]});const render=()=>{const total=s.done.length*s.amount;root.innerHTML=panel('チャレンジ設定',`<div class="tool-grid">${field('days','日数','number','min="1" max="365"')}${field('amount','1回の金額','number','min="1"')}</div><div class="tool-actions"><button id="challenge-set" class="tool-btn">設定</button></div>`)+panel('進捗',`<div class="big-number">${money(total)}</div><p class="subtle">${s.done.length} / ${s.days} 達成</p><div class="check-grid">${Array.from({length:s.days},(_,i)=>`<button class="check-tile ${s.done.includes(i)?'done':''}" data-day="${i}">${i+1}</button>`).join('')}</div>`);$('[name=days]').value=s.days;$('[name=amount]').value=s.amount;$('#challenge-set').onclick=()=>{s.days=Math.min(365,Math.max(1,+$('[name=days]').value||30));s.amount=Math.max(1,+$('[name=amount]').value||500);s.done=s.done.filter(x=>x<s.days);save(s);render()};$$('[data-day]').forEach(b=>b.onclick=()=>{const n=+b.dataset.day;s.done.includes(n)?s.done=s.done.filter(x=>x!==n):s.done.push(n);save(s);render()})};render()}
function waterTracker(){let s=load({date:today(),ml:0,target:2000});if(s.date!==today())s={date:today(),ml:0,target:s.target||2000};const render=()=>{const pct=Math.min(100,s.ml/s.target*100);root.innerHTML=panel('今日の水分',`<div class="big-number">${s.ml}<span style="font-size:.28em"> ml</span></div><div class="progress"><i style="width:${pct}%"></i></div><p class="subtle">目標 ${s.target} ml / ${Math.round(pct)}%</p><div class="tool-actions"><button class="tool-btn primary" data-water="250">+250ml</button><button class="tool-btn primary" data-water="500">+500ml</button><button id="water-minus" class="tool-btn">-250ml</button></div><div class="tool-grid" style="margin-top:12px">${field('target','1日の目標','number')}</div>`);$('[name=target]').value=s.target;$$('[data-water]').forEach(b=>b.onclick=()=>{s.ml+=+b.dataset.water;s.target=+$('[name=target]').value||s.target;save(s);render()});$('#water-minus').onclick=()=>{s.ml=Math.max(0,s.ml-250);save(s);render()};$('[name=target]').onchange=e=>{s.target=Math.max(250,+e.target.value||2000);save(s);render()}};render()}
function dailyStock(){let s=load({items:[]});const levels=['少','普通','十分'];const render=()=>{root.innerHTML=panel('日用品を追加',`<form id="stock-form"><div class="tool-grid">${field('text','日用品名')}</div><div class="tool-actions"><button class="tool-btn primary" type="submit">追加</button></div></form>`)+panel('ストック',`<div class="item-list">${s.items.map((x,i)=>`<div class="item"><div class="item-main"><strong>${esc(x.text)}</strong><small>残量: ${levels[x.level||0]}</small></div><div class="item-actions"><button class="mini" data-level="${i}">残量変更</button><button class="mini" data-del="${i}">削除</button></div></div>`).join('')||'<p class="subtle">まだありません。</p>'}</div>`);$('#stock-form').onsubmit=e=>{e.preventDefault();const t=formValues(e.currentTarget).text.trim();if(t)s.items.push({text:t,level:1});save(s);render()};$$('[data-level]').forEach(b=>b.onclick=()=>{s.items[+b.dataset.level].level=(s.items[+b.dataset.level].level+1)%3;save(s);render()});bindDeletes(s,render)};render()}
function leftovers(){let s=load({saved:[]});const suggest=txt=>{const a=txt.toLowerCase();const out=[];if(/[卵たまご]/.test(a))out.push('卵とじ / オムレツ');if(/米|ごはん/.test(a))out.push('チャーハン / 雑炊');if(/麺|うどん|パスタ/.test(a))out.push('焼き麺 / スープ麺');if(/鶏|豚|牛|肉/.test(a))out.push('野菜炒め / 丼');if(/野菜|キャベツ|白菜|玉ねぎ/.test(a))out.push('スープ / 炒め物');if(!out.length)out.push('具だくさんスープ','炒め物','お好み焼き風');return out};const render=()=>{root.innerHTML=panel('余り食材',`${field('ingredients','食材（カンマ区切り）','textarea')}<div class="tool-actions"><button id="menu-make" class="tool-btn primary">献立候補を出す</button></div><div id="menu-result"></div>`)+panel('保存した候補',itemList(s.saved,x=>`<strong>${esc(x.text)}</strong><small>${esc(x.ingredients)}</small>`));$('#menu-make').onclick=()=>{const t=$('[name=ingredients]').value,arr=suggest(t);$('#menu-result').innerHTML=`<div class="item-list" style="margin-top:12px">${arr.map(x=>`<div class="item"><div class="item-main"><strong>${esc(x)}</strong></div><button class="mini" data-save-menu="${esc(x)}">保存</button></div>`).join('')}</div>`;$$('[data-save-menu]').forEach(b=>b.onclick=()=>{s.saved.unshift({text:b.dataset.saveMenu,ingredients:t});save(s);render()})};bindDeletes({items:s.saved},()=>{save(s);render()})};render()}
function cooldown(){let s=load({items:[]});const render=()=>{const n=Date.now();root.innerHTML=panel('欲しいものを寝かせる',`<form id="cool-form"><div class="tool-grid">${field('item','欲しいもの')}${field('hours','待つ時間','number','min="1" value="24"')}</div><div class="tool-actions"><button class="tool-btn primary" type="submit">クールダウン開始</button></div></form>`)+panel('判定待ち',itemList(s.items,x=>{const left=Math.ceil((x.until-n)/36e5);return `<strong>${esc(x.item)}</strong><small>${left>0?`あと約${left}時間`:'再検討できます。「まだ欲しい？」を確認してください。'}</small>`}));$('#cool-form').onsubmit=e=>{e.preventDefault();const v=formValues(e.currentTarget);s.items.unshift({item:v.item,until:Date.now()+(+v.hours||24)*36e5});save(s);render()};bindDeletes(s,render)};render()}
function healthDiary(){crud({formTitle:'今日の記録',fields:[{key:'date',label:'日付',type:'date'},{key:'sleep',label:'睡眠時間',type:'number'},{key:'mood',label:'気分 1〜5',type:'number',attrs:'min="1" max="5"'},{key:'food',label:'食事・体調',type:'textarea'},{key:'symptoms',label:'症状メモ',type:'textarea'}],sort:(a,b)=>String(b.date).localeCompare(String(a.date)),summary:x=>`<strong>${esc(x.date||'日付なし')} / 気分 ${esc(x.mood||'-')}</strong><small>睡眠 ${esc(x.sleep||'-')}h / ${esc(x.symptoms||x.food||'')}</small>`})}
function steps(){let s=load({goal:8000,items:[]});const render=()=>{const map=new Map(s.items.map(x=>[x.date,+x.steps])),dates=[...map.keys()].sort().reverse();let streak=0,d=new Date();for(;;){const k=d.toISOString().slice(0,10);if((map.get(k)||0)>=s.goal){streak++;d.setDate(d.getDate()-1)}else break}root.innerHTML=panel('歩数を記録',`<form id="step-form"><div class="tool-grid">${field('date','日付','date')}${field('steps','歩数','number')}${field('goal','目標','number')}</div><div class="tool-actions"><button class="tool-btn primary" type="submit">保存</button></div></form>`)+panel('ストリーク',`<div class="big-number">${streak}<span style="font-size:.28em"> 日</span></div>`)+panel('履歴',itemList(s.items,x=>`<strong>${esc(x.date)} / ${Number(x.steps).toLocaleString()}歩</strong><small>${+x.steps>=s.goal?'達成':'未達'}</small>`));$('[name=date]').value=today();$('[name=goal]').value=s.goal;$('#step-form').onsubmit=e=>{e.preventDefault();const v=formValues(e.currentTarget);s.goal=+v.goal||8000;s.items=s.items.filter(x=>x.date!==v.date);s.items.push({date:v.date,steps:+v.steps});save(s);render()};bindDeletes(s,render)};render()}
function doctorNote(emergency=false){let s=load({});const labels=emergency?['氏名','緊急連絡先','服薬','アレルギー','持病・注意事項']:['症状','聞きたいこと','服薬','経過'];const keys=labels.map((_,i)=>`f${i}`);const render=()=>{root.innerHTML=panel(emergency?'緊急情報を登録':'受診前メモ',`<div class="tool-grid">${labels.map((l,i)=>field(keys[i],l,i>1?'textarea':'text')).join('')}</div><div class="tool-actions"><button id="note-save" class="tool-btn primary">保存</button><button id="note-print" class="tool-btn">印刷 / PDF保存</button></div>${emergency?'<p class="notice warn">本人が入力した情報を表示するだけのカードです。医療判断は行いません。</p>':''}`)+panel(emergency?'緊急表示':'1枚表示',`<div class="big-card">${labels.map((l,i)=>`<h3>${esc(l)}</h3><p>${esc(s[keys[i]]||'-')}</p>`).join('')}</div>`,'print-target');labels.forEach((l,i)=>{const e=$(`[name=${keys[i]}]`);if(e)e.value=s[keys[i]]||''});$('#note-save').onclick=()=>{keys.forEach(k=>s[k]=$(`[name=${k}]`).value);save(s);render()};$('#note-print').onclick=()=>window.print()};render()}
function spacedCards(){let s=load({items:[]});const render=()=>{const due=s.items.filter(x=>!x.next||x.next<=today()),card=due[0];root.innerHTML=panel('カード追加',`<form id="card-form"><div class="tool-grid">${field('q','質問')}${field('a','答え')}</div><div class="tool-actions"><button class="tool-btn primary" type="submit">追加</button></div></form>`)+panel('今日の復習',card?`<div class="big-card"><h2>${esc(card.q)}</h2><p id="card-answer" class="hidden">${esc(card.a)}</p></div><div class="tool-actions"><button id="show-answer" class="tool-btn">答えを見る</button><button class="tool-btn bad" data-rate="1">忘れた</button><button class="tool-btn" data-rate="3">微妙</button><button class="tool-btn good" data-rate="7">覚えた</button></div>`:'<p class="subtle">今日の復習はありません。</p>')+panel('全カード',itemList(s.items,x=>`<strong>${esc(x.q)}</strong><small>次回 ${esc(x.next||'今日')}</small>`));$('#card-form').onsubmit=e=>{e.preventDefault();s.items.push({...formValues(e.currentTarget),next:today()});save(s);render()};if($('#show-answer'))$('#show-answer').onclick=()=>$('#card-answer').classList.remove('hidden');$$('[data-rate]').forEach(b=>b.onclick=()=>{const d=new Date();d.setDate(d.getDate()+Number(b.dataset.rate));card.next=d.toISOString().slice(0,10);save(s);render()});bindDeletes(s,render)};render()}
function progressCalc(kind){let s=load({});const render=()=>{const exam=kind==='exam',book=kind==='book';root.innerHTML=panel(exam?'試験情報':'読書情報',`<div class="tool-grid">${field('date',exam?'試験日':'期限','date')}${field('total',exam?'残り範囲（単位）':'総ページ数','number')}${book?field('current','現在ページ','number'):''}</div><div class="tool-actions"><button id="prog-save" class="tool-btn primary">計算</button></div>`)+panel('必要ペース',`<div class="big-number" id="prog-big">-</div><p class="subtle" id="prog-sub"></p>`);Object.keys(s).forEach(k=>{const e=$(`[name=${k}]`);if(e)e.value=s[k]});const calc=()=>{const v={date:$('[name=date]').value,total:+$('[name=total]').value,current:+($('[name=current]')?.value||0)},d=Math.max(1,days(v.date,today())),rem=Math.max(0,v.total-v.current),per=rem/d;$('#prog-big').textContent=book?`${Math.ceil(per)} p/日`:`${per.toFixed(1)} /日`;$('#prog-sub').textContent=`残り ${d}日 / 残量 ${rem}`;s=v;save(s)};$('#prog-save').onclick=calc;if(s.date)calc()};render()}
function wordBattle(){let s=load({raw:'apple=りんご\ndog=犬\nwater=水',score:[0,0],idx:0});const pairs=()=>s.raw.split(/\n/).map(x=>x.split(/[=\t]/)).filter(x=>x[0]&&x[1]);const render=()=>{const p=pairs(),q=p.length?p[s.idx%p.length]:['-','-'];root.innerHTML=panel('単語セット',`${field('raw','1行1語：単語=意味','textarea')}<div class="tool-actions"><button id="words-save" class="tool-btn">更新</button></div>`)+panel('対戦',`<div class="big-card"><h2>${esc(q[0])}</h2><p id="word-answer" class="hidden">${esc(q[1])}</p></div><div class="tool-actions"><button id="word-show" class="tool-btn">答え</button><button class="tool-btn primary" data-win="0">PLAYER 1 正解</button><button class="tool-btn primary" data-win="1">PLAYER 2 正解</button><button id="word-next" class="tool-btn">次へ</button></div><p class="big-number">${s.score[0]} - ${s.score[1]}</p>`);$('[name=raw]').value=s.raw;$('#words-save').onclick=()=>{s.raw=$('[name=raw]').value;s.idx=0;save(s);render()};$('#word-show').onclick=()=>$('#word-answer').classList.remove('hidden');$$('[data-win]').forEach(b=>b.onclick=()=>{s.score[+b.dataset.win]++;s.idx++;save(s);render()});$('#word-next').onclick=()=>{s.idx++;save(s);render()}};render()}
function quizMaker(){let s=load({text:''});const render=()=>{root.innerHTML=panel('文章を貼り付け',`${field('source','本文','textarea')}<div class="tool-actions"><button id="quiz-make" class="tool-btn primary">問題を作る</button></div>`)+panel('確認問題',`<div id="quiz-out" class="item-list"></div>`);$('[name=source]').value=s.text;$('#quiz-make').onclick=()=>{s.text=$('[name=source]').value;save(s);const sentences=s.text.split(/[。！？\n]+/).map(x=>x.trim()).filter(x=>x.length>8).slice(0,20);$('#quiz-out').innerHTML=sentences.map((x,i)=>{const words=x.match(/[A-Za-z0-9一-龥ぁ-んァ-ン]{3,}/g)||[];const w=words.sort((a,b)=>b.length-a.length)[0]||x.slice(0,4);return `<div class="item"><div class="item-main"><strong>Q${i+1}. ${esc(x.replace(w,'＿＿＿'))}</strong><small>答え: ${esc(w)}</small></div></div>`}).join('')||'<p class="subtle">文章をもう少し長くしてください。</p>'}};render()}
function noteOrganizer(){let s=load({text:''});const render=()=>{const lines=s.text.split(/\n/).map(x=>x.trim()).filter(Boolean),todos=lines.filter(x=>/todo|やる|課題|宿題|期限/i.test(x)),heads=lines.filter(x=>/^#|^[0-9]+[\.、]|：|:/.test(x)).slice(0,12),rest=lines.filter(x=>!todos.includes(x)&&!heads.includes(x)).slice(0,12);root.innerHTML=panel('講義メモ',`${field('note','メモ','textarea')}<div class="tool-actions"><button id="organize" class="tool-btn primary">整理</button></div>`)+panel('整理結果',`<div class="split"><div><h3>見出し・要点</h3><div class="item-list">${[...heads,...rest].map(x=>`<div class="item"><div class="item-main"><strong>${esc(x)}</strong></div></div>`).join('')}</div></div><div><h3>TODO</h3><div class="item-list">${todos.map(x=>`<div class="item"><div class="item-main"><strong>${esc(x)}</strong></div></div>`).join('')||'<p class="subtle">TODOなし</p>'}</div></div></div>`);$('[name=note]').value=s.text;$('#organize').onclick=()=>{s.text=$('[name=note]').value;save(s);render()}};render()}
function heatmap(){let s=load({items:[]});const render=()=>{const map=new Map(s.items.map(x=>[x.date,+x.minutes]));const cells=[];const d=new Date();d.setDate(d.getDate()-97);for(let i=0;i<98;i++){const k=d.toISOString().slice(0,10),m=map.get(k)||0,l=m>=120?4:m>=60?3:m>=30?2:m>0?1:0;cells.push(`<div class="heat-cell l${l}" title="${k}: ${m}分"></div>`);d.setDate(d.getDate()+1)}root.innerHTML=panel('勉強時間を追加',`<form id="heat-form"><div class="tool-grid">${field('date','日付','date')}${field('minutes','分','number')}</div><div class="tool-actions"><button class="tool-btn primary" type="submit">保存</button></div></form>`)+panel('14週間ヒートマップ',`<div class="heatmap">${cells.join('')}</div>`);$('[name=date]').value=today();$('#heat-form').onsubmit=e=>{e.preventDefault();const v=formValues(e.currentTarget);s.items=s.items.filter(x=>x.date!==v.date);s.items.push({date:v.date,minutes:+v.minutes});save(s);render()}};render()}
function recorder(){let rec=null,chunks=[],url='';root.innerHTML=panel('ティーチバック録音',`<p id="rec-status" class="notice">マイク許可後に録音できます。</p><div class="tool-actions"><button id="rec-start" class="tool-btn primary">録音開始</button><button id="rec-stop" class="tool-btn" disabled>停止</button><a id="rec-download" class="tool-link hidden" download="teachback.webm">録音を保存</a></div><audio id="rec-audio" controls class="hidden" style="width:100%;margin-top:12px"></audio><p class="subtle">録音データはプライバシー優先でサーバーへ送信しません。必要なら端末へ保存してください。</p>`);$('#rec-start').onclick=async()=>{try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});rec=new MediaRecorder(stream);chunks=[];rec.ondataavailable=e=>chunks.push(e.data);rec.onstop=()=>{url=URL.createObjectURL(new Blob(chunks,{type:rec.mimeType}));$('#rec-audio').src=url;$('#rec-audio').classList.remove('hidden');$('#rec-download').href=url;$('#rec-download').classList.remove('hidden');stream.getTracks().forEach(t=>t.stop())};rec.start();$('#rec-status').innerHTML='<span class="recording-dot"></span>録音中';$('#rec-start').disabled=true;$('#rec-stop').disabled=false}catch(_){$('#rec-status').textContent='マイクを利用できません。'}};$('#rec-stop').onclick=()=>{rec?.stop();$('#rec-start').disabled=false;$('#rec-stop').disabled=true;$('#rec-status').textContent='録音終了'};cleanup.push(()=>{try{rec?.state==='recording'&&rec.stop();url&&URL.revokeObjectURL(url)}catch(_){}})}
function travelWallet(){let s=load({budget:50000,items:[]});const render=()=>{const total=s.items.reduce((a,x)=>a+(+x.amount||0),0);root.innerHTML=panel('旅行予算',`<div class="tool-grid">${field('budget','予算','number')}</div><div class="tool-actions"><button id="trip-budget" class="tool-btn">保存</button></div>`)+panel('支出追加',`<form id="trip-exp"><div class="tool-grid">${field('person','支払った人')}${field('amount','金額','number')}${field('category','カテゴリ')}</div><div class="tool-actions"><button class="tool-btn primary" type="submit">追加</button></div></form>`)+panel('残高',`<div class="big-number">${money(s.budget-total)}</div><p class="subtle">支出 ${money(total)} / 予算 ${money(s.budget)}</p>`)+panel('履歴',itemList(s.items,x=>`<strong>${esc(x.person)} ${money(x.amount)}</strong><small>${esc(x.category)}</small>`));$('[name=budget]').value=s.budget;$('#trip-budget').onclick=()=>{s.budget=+$('[name=budget]').value;save(s);render()};$('#trip-exp').onsubmit=e=>{e.preventDefault();s.items.unshift(formValues(e.currentTarget));save(s);render()};bindDeletes(s,render)};render()}
function voteApp(realtime=false){if(realtime)return realtimeBoard({formTitle:'候補を追加',fields:[{key:'name',label:'候補'}],summary:x=>`<strong>${esc(x.name)}</strong><small>投票は各端末で候補を追加して共有できます。</small>`});let s=load({items:[]});const render=()=>{s.items.sort((a,b)=>(b.votes||0)-(a.votes||0));root.innerHTML=panel('候補追加',`<form id="vote-form"><div class="tool-grid">${field('name','候補')}</div><div class="tool-actions"><button class="tool-btn primary">追加</button></div></form>`)+panel('投票',`<div class="item-list">${s.items.map((x,i)=>`<div class="item"><div class="item-main"><strong>${esc(x.name)}</strong><small>${x.votes||0}票</small></div><div class="item-actions"><button class="mini active" data-vote="${i}">+1</button><button class="mini" data-del="${i}">削除</button></div></div>`).join('')}</div>`);$('#vote-form').onsubmit=e=>{e.preventDefault();s.items.push({name:formValues(e.currentTarget).name,votes:0});save(s);render()};$$('[data-vote]').forEach(b=>b.onclick=()=>{s.items[+b.dataset.vote].votes=(s.items[+b.dataset.vote].votes||0)+1;save(s);render()});bindDeletes(s,render)};render()}
function captionMaker(){let s=load({text:''});const render=()=>{const t=s.text.trim();const drafts=t?[`${t}\n\n詳しくはプロフィールから。`,`【${t.slice(0,28)}】\n${t}\n保存してあとで見返してください。`,`🔥 ${t}\n\nどう思いますか？ コメントで教えてください！`]:[];root.innerHTML=panel('投稿内容',`${field('caption','伝えたい内容','textarea')}<div class="tool-actions"><button id="cap-make" class="tool-btn primary">3案作る</button></div>`)+panel('3方向の下書き',`<div class="item-list">${drafts.map((x,i)=>`<div class="item"><div class="item-main"><strong>${['短文','丁寧','勢い'][i]}</strong><small style="white-space:pre-wrap">${esc(x)}</small></div><button class="mini" data-copy-cap="${i}">コピー</button></div>`).join('')||'<p class="subtle">内容を入力してください。</p>'}</div>`);$('[name=caption]').value=s.text;$('#cap-make').onclick=()=>{s.text=$('[name=caption]').value;save(s);render()};$$('[data-copy-cap]').forEach(b=>b.onclick=()=>navigator.clipboard?.writeText(drafts[+b.dataset.copyCap]))};render()}
function invoice(){let s=load({issuer:'',client:'',item:'制作費',amount:10000,tax:10,due:''});const render=()=>{const subtotal=+s.amount||0,tax=subtotal*(+s.tax||0)/100,total=subtotal+tax;root.innerHTML=panel('請求内容',`<div class="tool-grid">${field('issuer','発行者')}${field('client','宛先')}${field('item','品目')}${field('amount','金額','number')}${field('tax','税率 %','number')}${field('due','支払期限','date')}</div><div class="tool-actions"><button id="inv-save" class="tool-btn primary">反映</button><button id="inv-print" class="tool-btn">印刷 / PDF保存</button></div>`)+panel('請求書',`<div class="invoice"><h2>請求書</h2><p>宛先: ${esc(s.client||'-')}</p><p>発行者: ${esc(s.issuer||'-')}</p><table><tr><th>品目</th><th>税抜</th><th>税</th></tr><tr><td>${esc(s.item)}</td><td>${money(subtotal)}</td><td>${money(tax)}</td></tr></table><h3>合計 ${money(total)}</h3><p>支払期限: ${esc(s.due||'-')}</p></div>`,'print-target');Object.keys(s).forEach(k=>{const e=$(`[name=${k}]`);if(e)e.value=s[k]});$('#inv-save').onclick=()=>{['issuer','client','item','amount','tax','due'].forEach(k=>s[k]=$(`[name=${k}]`).value);save(s);render()};$('#inv-print').onclick=()=>window.print()};render()}
function linkStats(){let s=load({items:[]});const render=()=>{root.innerHTML=panel('リンク追加',`<form id="link-form"><div class="tool-grid">${field('title','表示名')}${field('url','URL','url')}</div><div class="tool-actions"><button class="tool-btn primary">追加</button></div></form>`)+panel('リンク集',`<div class="item-list">${s.items.map((x,i)=>`<div class="item"><div class="item-main"><strong>${esc(x.title)}</strong><small>${esc(x.url)} / ${x.clicks||0}クリック</small></div><div class="item-actions"><a class="mini" data-link="${i}" href="${esc(x.url)}" target="_blank" rel="noopener">開く</a><button class="mini" data-del="${i}">削除</button></div></div>`).join('')}</div>`);$('#link-form').onsubmit=e=>{e.preventDefault();s.items.push({...formValues(e.currentTarget),clicks:0});save(s);render()};$$('[data-link]').forEach(a=>a.onclick=()=>{s.items[+a.dataset.link].clicks++;save(s)});bindDeletes(s,render)};render()}
function commentSorter(){let s=load({raw:'',items:[]});const render=()=>{root.innerHTML=panel('コメントを貼る',`${field('comments','1行1コメント','textarea')}<div class="tool-actions"><button id="comments-import" class="tool-btn primary">取り込む</button></div>`)+panel('仕分け',`<div class="tool-grid three">${['返信したい','動画ネタ','要対応'].map(cat=>`<div><h3>${cat}</h3><div class="item-list">${s.items.filter(x=>x.cat===cat).map((x,i)=>`<div class="item"><div class="item-main"><small>${esc(x.text)}</small></div></div>`).join('')}</div></div>`).join('')}</div><h3 style="margin-top:16px">未分類</h3><div class="item-list">${s.items.filter(x=>!x.cat).map((x)=>`<div class="item"><div class="item-main"><small>${esc(x.text)}</small></div><div class="item-actions">${['返信したい','動画ネタ','要対応'].map(c=>`<button class="mini" data-sort="${esc(x.id)}" data-cat="${c}">${c}</button>`).join('')}</div></div>`).join('')}</div>`);$('[name=comments]').value=s.raw;$('#comments-import').onclick=()=>{s.raw=$('[name=comments]').value;s.items=s.raw.split(/\n/).map(x=>x.trim()).filter(Boolean).map((text,i)=>({id:`${Date.now()}-${i}`,text,cat:''}));save(s);render()};$$('[data-sort]').forEach(b=>b.onclick=()=>{const x=s.items.find(y=>y.id===b.dataset.sort);if(x)x.cat=b.dataset.cat;save(s);render()})};render()}
function teleprompter(){let s=load({text:'ここに台本を入力してください。',speed:30});let timer=0;const render=()=>{root.innerHTML=panel('台本',`${field('teletext','テキスト','textarea')}<div class="tool-grid">${field('speed','速度','number','min="5" max="200"')}</div><div class="tool-actions"><button id="tele-apply" class="tool-btn">反映</button><button id="tele-start" class="tool-btn primary">開始 / 停止</button><button id="tele-top" class="tool-btn">先頭へ</button></div>`)+panel('プロンプター',`<div id="tele-box" class="tele-box"><div id="tele-content" class="tele-content">${esc(s.text)}</div></div>`);$('[name=teletext]').value=s.text;$('[name=speed]').value=s.speed;$('#tele-apply').onclick=()=>{s.text=$('[name=teletext]').value;s.speed=+$('[name=speed]').value||30;save(s);render()};$('#tele-start').onclick=()=>{if(timer){clearInterval(timer);timer=0;return}timer=setInterval(()=>{$('#tele-box').scrollTop+=1},Math.max(10,110-s.speed));cleanup.push(()=>clearInterval(timer))};$('#tele-top').onclick=()=>$('#tele-box').scrollTop=0};render()}
function filenameMaker(){let s=load({project:'project',type:'video',seq:1});const slug=x=>String(x).trim().replace(/\s+/g,'-').replace(/[^A-Za-z0-9_-]/g,'').toLowerCase()||'file';const render=()=>{const d=today().replaceAll('-',''),name=`${d}_${slug(s.project)}_${slug(s.type)}_${String(s.seq).padStart(3,'0')}`;root.innerHTML=panel('命名ルール',`<div class="tool-grid">${field('project','案件名')}${field('type','種類')}${field('seq','連番','number')}</div><div class="tool-actions"><button id="file-make" class="tool-btn primary">生成</button></div>`)+panel('ファイル名',`<div class="phrase">${esc(name)}</div><div class="tool-actions"><button id="file-copy" class="tool-btn">コピー</button></div>`);Object.keys(s).forEach(k=>$(`[name=${k}]`).value=s[k]);$('#file-make').onclick=()=>{s={project:$('[name=project]').value,type:$('[name=type]').value,seq:+$('[name=seq]').value||1};save(s);render()};$('#file-copy').onclick=()=>navigator.clipboard?.writeText(name)};render()}
function jsonFormatter(){let s=load({text:'{"hello":"world"}'});const render=()=>{root.innerHTML=panel('JSON',`${field('json','入力','textarea')}<div class="tool-actions"><button id="json-format" class="tool-btn primary">整形</button><button id="json-min" class="tool-btn">圧縮</button><button id="json-copy" class="tool-btn">コピー</button></div>`)+panel('結果',`<pre id="json-out" class="json-out"></pre>`);$('[name=json]').value=s.text;const run=min=>{try{const obj=JSON.parse($('[name=json]').value);s.text=$('[name=json]').value;save(s);$('#json-out').textContent=JSON.stringify(obj,null,min?0:2)}catch(e){$('#json-out').textContent=`ERROR: ${e.message}`}};$('#json-format').onclick=()=>run(false);$('#json-min').onclick=()=>run(true);$('#json-copy').onclick=()=>navigator.clipboard?.writeText($('#json-out').textContent);run(false)};render()}
function jsonDiff(){let s=load({a:'{}',b:'{}'});const flatten=(o,p='',r={})=>{if(o&&typeof o==='object')Object.keys(o).forEach(k=>flatten(o[k],p?`${p}.${k}`:k,r));else r[p]=o;return r};const render=()=>{root.innerHTML=panel('2つのJSON',`<div class="split">${field('a','A','textarea')}${field('b','B','textarea')}</div><div class="tool-actions"><button id="diff-run" class="tool-btn primary">比較</button></div>`)+panel('差分',`<div id="diff-out" class="code-out"></div>`);$('[name=a]').value=s.a;$('[name=b]').value=s.b;$('#diff-run').onclick=()=>{try{s.a=$('[name=a]').value;s.b=$('[name=b]').value;save(s);const A=flatten(JSON.parse(s.a)),B=flatten(JSON.parse(s.b)),keys=[...new Set([...Object.keys(A),...Object.keys(B)])].sort();$('#diff-out').innerHTML=keys.map(k=>!(k in A)?`<div class="diff-add">+ ${esc(k)}: ${esc(JSON.stringify(B[k]))}</div>`:!(k in B)?`<div class="diff-del">- ${esc(k)}: ${esc(JSON.stringify(A[k]))}</div>`:JSON.stringify(A[k])!==JSON.stringify(B[k])?`<div class="diff-change">~ ${esc(k)}: ${esc(JSON.stringify(A[k]))} → ${esc(JSON.stringify(B[k]))}</div>`:'').filter(Boolean).join('')||'差分なし'}catch(e){$('#diff-out').textContent=e.message}}};render()}
function regexTester(){let s=load({pattern:'(https?://\\S+)',flags:'gi',text:'URL https://example.com をテスト'});const render=()=>{root.innerHTML=panel('正規表現',`<div class="tool-grid">${field('pattern','パターン')}${field('flags','フラグ')}</div>${field('text','テスト文字列','textarea')}<div class="tool-actions"><button id="regex-run" class="tool-btn primary">テスト</button></div>`)+panel('マッチ',`<div id="regex-out" class="code-out"></div>`);Object.keys(s).forEach(k=>$(`[name=${k}]`).value=s[k]);$('#regex-run').onclick=()=>{s={pattern:$('[name=pattern]').value,flags:$('[name=flags]').value,text:$('[name=text]').value};save(s);try{const re=new RegExp(s.pattern,s.flags.includes('g')?s.flags:s.flags+'g'),arr=[...s.text.matchAll(re)];$('#regex-out').innerHTML=arr.map((m,i)=>`#${i+1} [${m.index}] ${esc(m[0])}${m.length>1?`\n groups: ${esc(JSON.stringify(m.slice(1)))}`:''}`).join('\n\n')||'マッチなし'}catch(e){$('#regex-out').textContent=e.message}};$('#regex-run').click()};render()}
function cronTool(){let s=load({expr:'*/15 * * * *'});const match=(part,val)=>part==='*'||part.split(',').some(t=>t.startsWith('*/')?val%(+t.slice(2)||1)===0:+t===val);const render=()=>{root.innerHTML=panel('Cron式',`${field('expr','分 時 日 月 曜日')}<div class="tool-actions"><button id="cron-run" class="tool-btn primary">次回実行を表示</button></div><p class="notice">標準的な5フィールド形式の *, */n, 数値, カンマ区切りに対応。</p>`)+panel('次回実行',`<div id="cron-out" class="item-list"></div>`);$('[name=expr]').value=s.expr;$('#cron-run').onclick=()=>{s.expr=$('[name=expr]').value.trim();save(s);const p=s.expr.split(/\s+/);if(p.length!==5){$('#cron-out').innerHTML='<p class="subtle">5フィールドで入力してください。</p>';return}const out=[],d=new Date();d.setSeconds(0,0);for(let i=0;i<525600&&out.length<10;i++){d.setMinutes(d.getMinutes()+1);if(match(p[0],d.getMinutes())&&match(p[1],d.getHours())&&match(p[2],d.getDate())&&match(p[3],d.getMonth()+1)&&match(p[4],d.getDay()))out.push(new Date(d))}$('#cron-out').innerHTML=out.map(x=>`<div class="item"><div class="item-main"><strong>${x.toLocaleString('ja-JP')}</strong></div></div>`).join('')};$('#cron-run').click()};render()}
async function stringTool(){let s=load({text:'Hello'});root.innerHTML=panel('入力',`${field('string','文字列','textarea')}<div class="tool-actions"><button class="tool-btn" data-str="b64e">Base64 Encode</button><button class="tool-btn" data-str="b64d">Base64 Decode</button><button class="tool-btn" data-str="urle">URL Encode</button><button class="tool-btn" data-str="urld">URL Decode</button><button class="tool-btn" data-str="uuid">UUID</button><button class="tool-btn primary" data-str="sha">SHA-256</button></div><p id="str-count" class="subtle"></p>`)+panel('結果',`<pre id="str-out" class="code-out"></pre>`);$('[name=string]').value=s.text;const run=async type=>{const t=$('[name=string]').value;s.text=t;save(s);$('#str-count').textContent=`文字数 ${[...t].length} / UTF-8 ${new TextEncoder().encode(t).length} bytes`;try{let o='';if(type==='b64e')o=btoa(unescape(encodeURIComponent(t)));if(type==='b64d')o=decodeURIComponent(escape(atob(t)));if(type==='urle')o=encodeURIComponent(t);if(type==='urld')o=decodeURIComponent(t);if(type==='uuid')o=crypto.randomUUID();if(type==='sha'){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(t));o=[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}$('#str-out').textContent=o}catch(e){$('#str-out').textContent=e.message}};$$('[data-str]').forEach(b=>b.onclick=()=>run(b.dataset.str));$('[name=string]').oninput=()=>run('');run('')}
function webhookLab(){let s=load({url:'',payload:'{"event":"demo","value":1}',logs:[]});const render=()=>{root.innerHTML=panel('Webhook',`<div class="tool-grid">${field('url','送信先URL（任意）','url')}${field('payload','JSON Payload','textarea')}</div><div class="tool-actions"><button id="hook-local" class="tool-btn">ローカルイベント送信</button><button id="hook-send" class="tool-btn primary">HTTP POST</button></div><p class="notice">外部URLは相手側のCORS設定によりブラウザから送れない場合があります。</p>`)+panel('イベントログ',itemList(s.logs,x=>`<strong>${esc(x.time)} / ${esc(x.status)}</strong><small>${esc(x.text)}</small>`));$('[name=url]').value=s.url;$('[name=payload]').value=s.payload;const log=(status,text)=>{s.url=$('[name=url]').value;s.payload=$('[name=payload]').value;s.logs.unshift({time:new Date().toLocaleTimeString(),status,text});s.logs=s.logs.slice(0,30);save(s);render()};$('#hook-local').onclick=()=>{try{JSON.parse($('[name=payload]').value);log('LOCAL OK','JSONイベントを受信しました')}catch(e){log('JSON ERROR',e.message)}};$('#hook-send').onclick=async()=>{try{const payload=JSON.parse($('[name=payload]').value),r=await fetch($('[name=url]').value,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});log(`HTTP ${r.status}`,`送信 ${r.ok?'成功':'完了'}`)}catch(e){log('ERROR',e.message)}};bindDeletes({items:s.logs},()=>{save(s);render()})};render()}
function endpointChecker(){let s=load({url:'https://example.com',items:[]});const render=()=>{root.innerHTML=panel('URLを確認',`${field('url','Endpoint','url')}<div class="tool-actions"><button id="endpoint-run" class="tool-btn primary">今すぐ確認</button></div><p class="notice">CORSで読み取りが禁止されているURLは、ブラウザ版では判定できません。</p>`)+panel('履歴',itemList(s.items,x=>`<strong>${esc(x.status)} / ${esc(x.ms)}ms</strong><small>${esc(x.time)} ${esc(x.url)}</small>`));$('[name=url]').value=s.url;$('#endpoint-run').onclick=async()=>{s.url=$('[name=url]').value;const st=performance.now();let status='';try{const r=await fetch(s.url,{cache:'no-store'});status=`HTTP ${r.status}`}catch(e){status=`ERROR / CORS: ${e.message}`}s.items.unshift({url:s.url,status,ms:Math.round(performance.now()-st),time:new Date().toLocaleString()});s.items=s.items.slice(0,30);save(s);render()};bindDeletes(s,render)};render()}
function changelog(){let s=load({items:[]});const render=()=>{const md=['# Changelog',...['Added','Fix','Change'].flatMap(t=>{const a=s.items.filter(x=>x.type===t);return a.length?[`\n## ${t}`,...a.map(x=>`- ${x.text}`)]:[]})].join('\n');root.innerHTML=panel('変更を追加',`<form id="change-form"><div class="tool-grid">${select('type','種類',['Added','Fix','Change'])}${field('text','変更内容')}</div><div class="tool-actions"><button class="tool-btn primary">追加</button></div></form>`)+panel('Markdown',`<pre id="change-md" class="code-out">${esc(md)}</pre><div class="tool-actions"><button id="change-copy" class="tool-btn">コピー</button></div>`)+panel('項目',itemList(s.items,x=>`<strong>${esc(x.type)}</strong><small>${esc(x.text)}</small>`));$('#change-form').onsubmit=e=>{e.preventDefault();s.items.push(formValues(e.currentTarget));save(s);render()};$('#change-copy').onclick=()=>navigator.clipboard?.writeText(md);bindDeletes(s,render)};render()}
function disaster(){let s=load({people:2,days:3,have:{}});const items=[['水',p=>`${p*3*s.days} L`],['食料',p=>`${p*s.days*3} 食`],['携帯トイレ',p=>`${p*s.days*5} 回分`],['乾電池',()=> '予備1セット以上'],['モバイルバッテリー',p=>`${Math.max(1,p)} 台`],['懐中電灯',()=> '1〜2個'],['常備品・衛生用品',()=> '必要分']];const render=()=>{root.innerHTML=panel('人数・日数',`<div class="tool-grid">${field('people','家族人数','number')}${field('days','備える日数','number')}</div><div class="tool-actions"><button id="dis-set" class="tool-btn">更新</button></div>`)+panel('備蓄チェック',`<div class="item-list">${items.map(([n,f],i)=>`<div class="item"><div class="item-main"><strong>${esc(n)}</strong><small>目安 ${esc(f(s.people))}</small></div><button class="mini ${s.have[i]?'active':''}" data-stockcheck="${i}">${s.have[i]?'準備済み':'未準備'}</button></div>`).join('')}</div><p class="notice warn">一般的な備蓄チェック用の目安です。自治体・家族の事情に合わせて調整してください。</p>`);$('[name=people]').value=s.people;$('[name=days]').value=s.days;$('#dis-set').onclick=()=>{s.people=Math.max(1,+$('[name=people]').value||1);s.days=Math.max(1,+$('[name=days]').value||3);save(s);render()};$$('[data-stockcheck]').forEach(b=>b.onclick=()=>{s.have[b.dataset.stockcheck]=!s.have[b.dataset.stockcheck];save(s);render()})};render()}
function facilityHours(){let s=load({items:[]});const jp=['日','月','火','水','木','金','土'];const render=()=>{const dow=jp[new Date().getDay()],time=new Date().toTimeString().slice(0,5);root.innerHTML=panel('施設追加',`<form id="fac-form"><div class="tool-grid">${field('name','施設名')}${field('open','開館','time')}${field('close','閉館','time')}${field('closed','休館曜日（例: 月）')}</div><div class="tool-actions"><button class="tool-btn primary">追加</button></div></form>`)+panel(`今日: ${dow}曜日`,itemList(s.items,x=>{const closed=(x.closed||'').includes(dow),open=!closed&&time>=x.open&&time<x.close;return `<strong>${esc(x.name)} <span class="badge ${open?'good':'bad'}">${open?'営業中':'営業時間外'}</span></strong><small>${esc(x.open)}〜${esc(x.close)} / 休 ${esc(x.closed||'なし')}</small>`}));$('#fac-form').onsubmit=e=>{e.preventDefault();s.items.push(formValues(e.currentTarget));save(s);render()};bindDeletes(s,render)};render()}
function renderApp(){clearCleanup();
 const CRUD={
2:['引き継ぎを残す',[['today','今日やったこと','textarea'],['unfinished','未完了','textarea'],['notes','注意点','textarea']],x=>`<strong>${new Date(x.createdAt).toLocaleString()}</strong><small>完了: ${esc(x.today)} / 未完了: ${esc(x.unfinished)}</small>`],
6:['意思決定を記録',[['decision','決めたこと'],['reason','理由','textarea'],['assumption','前提','textarea'],['review','見直し日','date']],x=>`<strong>${esc(x.decision)}</strong><small>${esc(x.reason)} / 見直し ${esc(x.review)}</small>`],
7:['定型文を保存',[['tag','タグ'],['text','定型文','textarea']],x=>`<strong>${esc(x.tag)}</strong><small>${esc(x.text)}</small>`],
8:['アクション追加',[['task','やること'],['owner','担当'],['due','期限','date'],['status','状態']],x=>`<strong>${esc(x.task)} / ${esc(x.owner)}</strong><small>${esc(x.due)} / ${esc(x.status)}</small>`],
10:['顧客追加',[['customer','顧客名'],['last','最終連絡日','date'],['next','次にやること'],['due','期限','date']],x=>`<strong>${esc(x.customer)}</strong><small>最終 ${esc(x.last)} / 次: ${esc(x.next)} ${esc(x.due)}</small>`],
12:['食品追加',[['item','食品名'],['date','賞味期限','date']],x=>`<strong>${esc(x.item)}</strong><small>${esc(x.date)} / ${x.date?days(x.date,today()):'-'}日</small>`],
13:['在庫追加',[['item','品名'],['zone','保管','select',['冷蔵','冷凍','常温']],['qty','数量']],x=>`<strong>${esc(x.item)} × ${esc(x.qty)}</strong><small>${esc(x.zone)}</small>`],
15:['掃除場所追加',[['place','場所'],['interval','周期（日）','number'],['last','最後に掃除した日','date']],x=>`<strong>${esc(x.place)}</strong><small>次回まで ${x.last?days(new Date(new Date(x.last).getTime()+(+x.interval||7)*864e5).toISOString().slice(0,10),today()):'-'}日</small>`],
21:['サブスク追加',[['service','サービス'],['monthly','月額','number'],['renewal','更新日','date']],x=>`<strong>${esc(x.service)} ${money(x.monthly)}/月</strong><small>更新 ${esc(x.renewal)}</small>`],
25:['価格記録',[['product','商品'],['store','店'],['price','価格','number'],['date','日付','date']],x=>`<strong>${esc(x.product)} ${money(x.price)}</strong><small>${esc(x.store)} / ${esc(x.date)}</small>`],
26:['入出金予定',[['date','日付','date'],['name','内容'],['amount','金額（支出はマイナス）','number']],x=>`<strong>${esc(x.date)} ${esc(x.name)}</strong><small>${money(x.amount)}</small>`],
28:['ポイント・クーポン追加',[['name','名称'],['balance','残高・内容'],['date','失効日','date']],x=>`<strong>${esc(x.name)} / ${esc(x.balance)}</strong><small>${esc(x.date)} ${x.date?`（あと${days(x.date,today())}日）`:''}</small>`],
29:['保険追加',[['company','保険会社'],['coverage','補償内容','textarea'],['phone','連絡先','tel'],['renewal','更新月']],x=>`<strong>${esc(x.company)}</strong><small>${esc(x.coverage)} / ${esc(x.phone)} / 更新 ${esc(x.renewal)}</small>`],
34:['服薬予定追加',[['name','薬の名前'],['time','時刻','time'],['note','メモ']],x=>`<strong>${esc(x.time)} ${esc(x.name)}</strong><small>${esc(x.note)}</small>`],
39:['診察項目追加',[['topic','項目'],['detail','内容','textarea']],x=>`<strong>${esc(x.topic)}</strong><small>${esc(x.detail)}</small>`],
45:['間違い追加',[['question','問題','textarea'],['answer','答え','textarea'],['note','原因・メモ','textarea']],x=>`<strong>${esc(x.question)}</strong><small>答え: ${esc(x.answer)} / ${esc(x.note)}</small>`],
51:['旅程追加',[['time','日時','datetime-local'],['type','種類'],['detail','内容'],['reservation','予約番号']],x=>`<strong>${esc(x.time)} ${esc(x.detail)}</strong><small>${esc(x.type)} / ${esc(x.reservation)}</small>`],
54:['乗換メモ追加',[['route','路線・区間'],['platform','番線'],['car','号車'],['exit','出口']],x=>`<strong>${esc(x.route)}</strong><small>${esc(x.platform)}番線 / ${esc(x.car)}号車 / ${esc(x.exit)}</small>`],
57:['ホテル追加',[['name','ホテル'],['price','価格','number'],['bath','風呂'],['sauna','サウナ'],['distance','駅距離'],['checkout','チェックアウト']],x=>`<strong>${esc(x.name)} ${money(x.price)}</strong><small>風呂 ${esc(x.bath)} / サウナ ${esc(x.sauna)} / ${esc(x.distance)} / OUT ${esc(x.checkout)}</small>`],
58:['フレーズ追加',[['label','意味・場面'],['phrase','見せる文章','textarea']],x=>`<strong>${esc(x.label)}</strong><small>${esc(x.phrase)}</small>`],
60:['撮影スポット追加',[['place','場所'],['shot','構図・撮りたいもの'],['time','時間帯'],['status','状態','select',['未撮影','撮影済み']]],x=>`<strong>${esc(x.place)} / ${esc(x.status)}</strong><small>${esc(x.shot)} / ${esc(x.time)}</small>`],
63:['家事ポイント追加',[['member','担当'],['task','家事'],['points','ポイント','number']],x=>`<strong>${esc(x.member)} +${esc(x.points)}pt</strong><small>${esc(x.task)}</small>`],
64:['学校予定追加',[['child','子ども'],['date','日付','date'],['event','予定'],['type','種類']],x=>`<strong>${esc(x.date)} ${esc(x.child)}</strong><small>${esc(x.event)} / ${esc(x.type)}</small>`],
65:['購入候補追加',[['item','品物'],['price','価格','number'],['reason','理由','textarea'],['status','状態','select',['申請中','OK','保留']]],x=>`<strong>${esc(x.item)} ${money(x.price)} / ${esc(x.status)}</strong><small>${esc(x.reason)}</small>`],
66:['お世話記録',[['time','日時','datetime-local'],['type','種類','select',['ごはん','散歩','薬','トイレ','その他']],['member','担当'],['note','メモ']],x=>`<strong>${esc(x.time)} ${esc(x.type)}</strong><small>${esc(x.member)} / ${esc(x.note)}</small>`],
67:['連絡先追加',[['person','人'],['last','最後に連絡した日','date'],['interval','目安間隔（日）','number']],x=>`<strong>${esc(x.person)}</strong><small>最後 ${esc(x.last)} / 次の目安まで ${x.last?days(new Date(new Date(x.last).getTime()+(+x.interval||7)*864e5).toISOString().slice(0,10),today()):'-'}日</small>`],
68:['贈り物記録',[['person','相手'],['direction','種類','select',['贈った','もらった']],['item','品物'],['date','日付','date'],['return','お返し状況']],x=>`<strong>${esc(x.person)} / ${esc(x.direction)} ${esc(x.item)}</strong><small>${esc(x.date)} / ${esc(x.return)}</small>`],
69:['イベント追加',[['event','イベント'],['date','日付','date']],x=>`<strong>${esc(x.event)}</strong><small>あと ${x.date?days(x.date,today()):'-'}日 / ${esc(x.date)}</small>`],
72:['サムネ結果追加',[['title','動画・投稿'],['variant','案 A/B'],['impressions','表示数','number'],['clicks','クリック数','number'],['date','投稿日','date']],x=>`<strong>${esc(x.title)} / ${esc(x.variant)}</strong><small>CTR ${(+x.impressions?((+x.clicks/+x.impressions)*100).toFixed(2):'0')}% (${esc(x.clicks)}/${esc(x.impressions)})</small>`],
73:['投稿予定追加',[['platform','SNS/媒体'],['date','公開日','date'],['stage','状態','select',['企画','撮影','編集','公開済み']],['idea','内容']],x=>`<strong>${esc(x.date)} ${esc(x.platform)} / ${esc(x.stage)}</strong><small>${esc(x.idea)}</small>`],
74:['ネタ追加',[['idea','ネタ','textarea'],['genre','ジャンル'],['priority','優先度','select',['高','中','低']]],x=>`<strong>${esc(x.priority)} / ${esc(x.genre)}</strong><small>${esc(x.idea)}</small>`],
75:['案件追加',[['company','企業'],['contact','連絡先'],['fee','金額','number'],['due','納期','date'],['payment','入金','select',['未入金','入金済み']]],x=>`<strong>${esc(x.company)} ${money(x.fee)}</strong><small>納期 ${esc(x.due)} / ${esc(x.payment)}</small>`],
80:['命名履歴',[['name','生成名']],x=>`<strong>${esc(x.name)}</strong>`],
85:['環境変数追加',[['name','変数名']],x=>`<strong>${esc(x.name)}</strong><small>値は保存しません。</small>`],
86:['SQL保存',[['title','タイトル'],['tags','タグ'],['sql','SQL','textarea']],x=>`<strong>${esc(x.title)} / ${esc(x.tags)}</strong><small style="white-space:pre-wrap">${esc(x.sql)}</small>`],
99:['商品追加',[['item','商品'],['price','価格','number'],['qty','在庫数','number'],['sold','販売数','number']],x=>`<strong>${esc(x.item)} ${money(x.price)}</strong><small>在庫 ${Math.max(0,(+x.qty||0)-(+x.sold||0))} / 売れた ${esc(x.sold)}</small>`]
 };
 if(CRUD[id]){const [title,fs,sum]=CRUD[id];crud({formTitle:title,fields:fs.map(a=>({key:a[0],label:a[1],type:a[2]||'text',options:a[3]})),summary:sum,stats:id===21?items=>`<div class="big-number">${money(items.reduce((a,x)=>a+(+x.monthly||0),0)*12)}</div><p class="subtle">年間総額</p>`:id===63?items=>`<div class="item-list">${Object.entries(items.reduce((o,x)=>(o[x.member]=(o[x.member]||0)+(+x.points||0),o),{})).map(([n,p])=>`<div class="item"><div class="item-main"><strong>${esc(n)} ${p}pt</strong></div></div>`).join('')}</div>`:null});return}
 switch(id){
 case 1:countdown({title:'会議5分タイマー',defaultMinutes:5,labelInput:true,subtitle:'議題ごとに開始してください'});break;
 case 3:checklist({title:'定型業務チェッカー',defaults:['毎日の確認','週次レビュー','月次締め']});break;
 case 4:(()=>{let s=load({title:'',date:'',steps:4});const render=()=>{const n=Math.max(2,+s.steps||4),end=new Date(s.date||Date.now()+7*864e5),start=new Date(),span=end-start;root.innerHTML=panel('締切から逆算',`<div class="tool-grid">${field('title','ゴール')}${field('date','締切','date')}${field('steps','中間ステップ数','number')}</div><div class="tool-actions"><button id="plan-run" class="tool-btn primary">逆算する</button></div>`)+panel('中間期限',`<div class="item-list">${s.date?Array.from({length:n},(_,i)=>{const d=new Date(start.getTime()+span*(i+1)/n);return `<div class="item"><div class="item-main"><strong>STEP ${i+1}</strong><small>${d.toLocaleDateString('ja-JP')} ${i===n-1?esc(s.title):'中間成果物'}</small></div></div>`}).join(''):'<p class="subtle">締切を入力してください。</p>'}</div>`);Object.keys(s).forEach(k=>{const e=$(`[name=${k}]`);if(e)e.value=s[k]});$('#plan-run').onclick=()=>{s={title:$('[name=title]').value,date:$('[name=date]').value,steps:+$('[name=steps]').value||4};save(s);render()}};render()})();break;
 case 5:countdown({title:'集中スプリント',defaultMinutes:25,labelInput:true,subtitle:'集中 → 休憩を繰り返します'});break;
 case 9:(()=>{let s=load({active:'',start:0,items:[]});let int=0;const render=()=>{const sec=s.start?Math.floor((Date.now()-s.start)/1000):0,total=s.items.reduce((a,x)=>a+x.seconds,0);root.innerHTML=panel('作業ストップウォッチ',`<div class="timer-face"><strong id="sw-time">${fmtSec(sec)}</strong><small>${esc(s.active||'作業名を入力')}</small></div><div class="tool-grid">${field('task','作業名')}</div><div class="tool-actions"><button id="sw-toggle" class="tool-btn primary">${s.start?'停止':'開始'}</button></div>`)+panel('累計',`<div class="big-number">${fmtSec(total)}</div>`)+panel('履歴',itemList(s.items,x=>`<strong>${esc(x.task)}</strong><small>${fmtSec(x.seconds)}</small>`));$('[name=task]').value=s.active;$('#sw-toggle').onclick=()=>{if(s.start){s.items.unshift({task:s.active||'作業',seconds:Math.max(1,Math.floor((Date.now()-s.start)/1000))});s.start=0}else{s.active=$('[name=task]').value||'作業';s.start=Date.now()}save(s);render()};bindDeletes(s,render)};render();int=setInterval(()=>{if(s.start&&$('#sw-time'))$('#sw-time').textContent=fmtSec((Date.now()-s.start)/1000)},500);cleanup.push(()=>clearInterval(int))})();break;
 case 11:(()=>{let s=load({items:[]});const daysJ=['日','月','火','水','木','金','土'];const render=()=>{const d=new Date(),t=daysJ[d.getDay()],tm=daysJ[(d.getDay()+1)%7];root.innerHTML=panel('曜日を登録',`<form id="trash-form"><div class="tool-grid">${select('day','曜日',daysJ)}${field('type','ゴミ種別')}</div><div class="tool-actions"><button class="tool-btn primary">追加</button></div></form>`)+panel('今日・明日',`<div class="split"><div class="big-card"><h2>今日 ${t}</h2><p>${esc(s.items.filter(x=>x.day===t).map(x=>x.type).join(' / ')||'なし')}</p></div><div class="big-card"><h2>明日 ${tm}</h2><p>${esc(s.items.filter(x=>x.day===tm).map(x=>x.type).join(' / ')||'なし')}</p></div></div>`)+panel('登録',itemList(s.items,x=>`<strong>${esc(x.day)}曜日</strong><small>${esc(x.type)}</small>`));$('#trash-form').onsubmit=e=>{e.preventDefault();s.items.push(formValues(e.currentTarget));save(s);render()};bindDeletes(s,render)};render()})();break;
 case 14:countdown({title:'洗濯終了タイマー',defaultMinutes:45,labelInput:true,subtitle:'洗濯機・乾燥機名も記録できます'});break;
 case 16:case 24:splitExpenses();break;
 case 17:photoLog({titleLabel:'物',geo:false});break;
 case 18:photoLog({titleLabel:'階・区画',geo:true});break;
 case 19:dailyStock();break;
 case 20:leftovers();break;
 case 22:miniCalculator('budget');break;
 case 23:savingsChallenge();break;
 case 27:miniCalculator('tax');break;
 case 30:cooldown();break;
 case 31:waterTracker();break;
 case 32:countdown({title:'ストレッチタイマー',defaultMinutes:30,labelInput:true,subtitle:'首・肩・腰の短いストレッチ休憩'});break;
 case 33:checklist({title:'寝る前ルーティン',defaults:['照明を落とす','入浴','スマホ終了','明日の準備','寝室を整える']});break;
 case 35:healthDiary();break;
 case 36:steps();break;
 case 37:photoLog({titleLabel:'食事',geo:false});break;
 case 38:countdown({title:'姿勢休憩アラーム',defaultMinutes:45,labelInput:false,subtitle:'時間になったら立つ・肩を回す'});break;
 case 40:doctorNote(true);break;
 case 41:spacedCards();break;
 case 42:progressCalc('exam');break;
 case 43:progressCalc('book');break;
 case 44:wordBattle();break;
 case 46:realtimeBoard({formTitle:'自習室メッセージ',fields:[{key:'name',label:'名前'},{key:'status',label:'状態',type:'select',options:['勉強中','休憩中','終了']}],summary:x=>`<strong>${esc(x.name)} / ${esc(x.status)}</strong><small>${new Date(x.createdAt).toLocaleTimeString()}</small>`});break;
 case 47:quizMaker();break;
 case 48:noteOrganizer();break;
 case 49:heatmap();break;
 case 50:recorder();break;
 case 52:checklist({title:'忘れ物ゼロリスト',defaults:['財布','スマホ','充電器','身分証','予約情報','着替え','洗面用品','薬・常備品']});break;
 case 53:travelWallet();break;
 case 55:voteApp(false);break;
 case 56:photoLog({titleLabel:'トイレ・休憩場所',geo:true});break;
 case 59:doctorNote(true);break;
 case 61:realtimeBoard({formTitle:'家族掲示板',fields:[{key:'type',label:'種類',type:'select',options:['予定','買う物','連絡']},{key:'text',label:'内容'}],summary:x=>`<strong>${esc(x.type)} / ${esc(x.text)}</strong>`});break;
 case 62:realtimeBoard({formTitle:'買い物を追加',fields:[{key:'text',label:'買う物'},{key:'by',label:'追加した人'}],summary:x=>`<strong>${esc(x.text)}</strong><small>${esc(x.by)}</small>`});break;
 case 70:voteApp(false);break;
 case 71:captionMaker();break;
 case 76:invoice();break;
 case 77:linkStats();break;
 case 78:commentSorter();break;
 case 79:teleprompter();break;
 case 81:jsonFormatter();break;
 case 82:jsonDiff();break;
 case 83:regexTester();break;
 case 84:cronTool();break;
 case 87:webhookLab();break;
 case 88:endpointChecker();break;
 case 89:changelog();break;
 case 90:stringTool();break;
 case 91:realtimeBoard({formTitle:'近所イベント投稿',fields:[{key:'title',label:'イベント'},{key:'date',label:'日時'},{key:'place',label:'場所'}],summary:x=>`<strong>${esc(x.title)}</strong><small>${esc(x.date)} / ${esc(x.place)}</small>`});break;
 case 92:realtimeBoard({formTitle:'町内お知らせ',fields:[{key:'title',label:'件名'},{key:'text',label:'お知らせ',type:'textarea'}],summary:x=>`<strong>${esc(x.title)}</strong><small>${esc(x.text)}</small>`});break;
 case 93:disaster();break;
 case 94:realtimeBoard({formTitle:'駐車料金メモ',fields:[{key:'name',label:'駐車場'},{key:'area',label:'エリア'},{key:'rate',label:'料金'},{key:'max',label:'最大料金'}],summary:x=>`<strong>${esc(x.name)} / ${esc(x.rate)}</strong><small>${esc(x.area)} / 最大 ${esc(x.max)}</small>`});break;
 case 95:realtimeBoard({formTitle:'落とし物投稿',fields:[{key:'type',label:'種類',type:'select',options:['落とした','拾った']},{key:'place',label:'場所'},{key:'feature',label:'特徴'},{key:'time',label:'日時'}],summary:x=>`<strong>${esc(x.type)} / ${esc(x.place)}</strong><small>${esc(x.feature)} / ${esc(x.time)}</small>`});break;
 case 96:realtimeBoard({formTitle:'待ち時間投稿',fields:[{key:'place',label:'店・施設'},{key:'minutes',label:'待ち時間（分）','type':'number'},{key:'note',label:'メモ'}],summary:x=>`<strong>${esc(x.place)} / ${esc(x.minutes)}分</strong><small>${esc(x.note)} / ${new Date(x.createdAt).toLocaleTimeString()}</small>`});break;
 case 97:realtimeBoard({formTitle:'お得情報投稿',fields:[{key:'shop',label:'店・施設'},{key:'deal',label:'割引・特典'},{key:'expiry',label:'期限','type':'date'}],summary:x=>`<strong>${esc(x.shop)}</strong><small>${esc(x.deal)} / ${esc(x.expiry)}</small>`});break;
 case 98:realtimeBoard({formTitle:'出欠入力',fields:[{key:'name',label:'名前'},{key:'status',label:'出欠',type:'select',options:['参加','不参加','未定']}],summary:x=>`<strong>${esc(x.name)}</strong><small>${esc(x.status)}</small>`});break;
 case 100:facilityHours();break;
 default:root.innerHTML=panel('実装済み',`<p class="subtle">このアプリは共通実装エンジンで利用できます。</p>`)
 }
}
metadata().then(meta=>{document.title=`${meta.name} - 使えるアプリ100`;$('#tool-title').textContent=meta.name;$('#tool-desc').textContent=meta.desc;$('#tool-category').textContent=meta.category;$('#tool-kicker').textContent=`APP ${String(id).padStart(3,'0')} / IMPLEMENTED`;$('#tool-number').textContent=`${String(id).padStart(3,'0')} / 100`;renderApp()});
$('#clear-app').onclick=()=>{if(confirm('このアプリに保存したデータをすべて消去しますか？')){localStorage.removeItem(KEY);renderApp()}};
window.addEventListener('beforeunload',clearCleanup);
})();