import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';

const $=s=>document.querySelector(s);
const canvas=$('#v4-canvas'),root=$('#v4-root'),overlay=$('#v4-overlay'),startBtn=$('#v4-start');
const ui={chapter:$('#v4-chapter'),stage:$('#v4-stage'),objective:$('#v4-objective'),objectiveSub:$('#v4-objective-sub'),boss:$('#v4-boss'),bossName:$('#v4-boss-name'),bossFill:$('#v4-boss-fill'),hearts:$('#v4-hearts'),hp:$('#v4-hpfill'),ammo:$('#v4-ammo'),reserve:$('#v4-reserve'),kills:$('#v4-kills'),target:$('#v4-target'),toast:$('#v4-toast'),crosshair:$('#v4-crosshair'),blood:$('#v4-blood'),flash:$('#v4-flash'),prompt:$('#v4-prompt'),potion:$('#v4-potion')};
const coarse=matchMedia('(pointer:coarse)').matches||(navigator.maxTouchPoints||0)>0;
const STAGES=[
 {title:'THE FALLEN ABBEY',sub:'CHAPTER I — ASHES REMAIN',boss:'THE HOLLOW KING',sky:0x10131b,fog:0x17161c,accent:0xd99a5b,magic:0x62c9ff,ground:'cobble',weather:'rain',enemy:'shambler'},
 {title:'FROSTBOUND KEEP',sub:'CHAPTER II — WHITE SILENCE',boss:'GORAM THE HOWLER',sky:0x0b1621,fog:0x1a2a35,accent:0x9ddcff,magic:0x7be7ff,ground:'snow',weather:'snow',enemy:'hound'},
 {title:'DROWNED RAVINE',sub:'CHAPTER III — THE DEEP REMEMBERS',boss:'ABYSSAL CROCODRAKE',sky:0x0a171a,fog:0x142526,accent:0x7ab89f,magic:0x56f3d0,ground:'wet',weather:'mist',enemy:'crawler'},
 {title:'TEMPEST HARBOR',sub:'CHAPTER IV — NO SHORE, NO SALVATION',boss:'LEVIATHAN REAVER',sky:0x08111c,fog:0x112335,accent:0x93b8d1,magic:0x67d7ff,ground:'wood',weather:'storm',enemy:'mariner'},
 {title:'ARCANE DEADLINE',sub:'CHAPTER V — THE CITY REMEMBERS',boss:'TITAN EXECUTIONER',sky:0x0e0b18,fog:0x24192d,accent:0xd88bff,magic:0x3f8cff,ground:'city',weather:'rain',enemy:'crystal'},
 {title:'DEVIL CASTLE NOCTURNE',sub:'CHAPTER VI — WHEN ALL LIGHT DIES',boss:'ARCHDEMON VALZAROTH',sky:0x18080b,fog:0x2b0c12,accent:0xff764d,magic:0xff3c35,ground:'obsidian',weather:'embers',enemy:'knight'}
];
const state={running:false,stage:0,hp:100,maxHp:100,ammo:8,mag:8,reserve:48,potions:3,kills:0,target:18,boss:null,bossSpawned:false,portal:null,startedAt:0,stageStarted:0,reloading:false,dodgeUntil:0,dodgeCd:0,shotCd:0,shake:0,aiming:false,completed:false};
const input={keys:new Set(),moveX:0,moveY:0,yaw:0,pitch:.16,lookPointer:null,stickPointer:null,lastLook:null,fireTimer:0};
const enemies=[],pickups=[],fx=[],colliders=[],particles=[];
let scene,camera,renderer,clock,player,weaponMuzzle,weaponFlash,hemi,keyLight,moonLight,audio=null,master=null,noiseBuf=null;
const raycaster=new THREE.Raycaster();
const tempV=new THREE.Vector3(),tempV2=new THREE.Vector3(),tempQ=new THREE.Quaternion();

function clamp(v,a,b){return Math.max(a,Math.min(b,v));}
function rand(a=1,b=0){return b+Math.random()*(a-b)}
function toast(t,ms=1100){ui.toast.textContent=t;ui.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>ui.toast.classList.remove('show'),ms)}
function texture(kind,base='#505050',detail='#242424'){
 const c=document.createElement('canvas');c.width=c.height=256;const x=c.getContext('2d');x.fillStyle=base;x.fillRect(0,0,256,256);
 if(kind==='cobble'||kind==='wet'||kind==='city'||kind==='obsidian'){
  x.lineWidth=2;for(let y=0;y<256;y+=36){for(let xx=(y/36%2)*22-22;xx<256;xx+=44){const w=40,h=31;x.fillStyle=detail;x.globalAlpha=.24+Math.random()*.15;x.fillRect(xx+2,y+2,w,h);x.strokeStyle='rgba(255,255,255,.08)';x.strokeRect(xx+2,y+2,w,h)}}
 }else if(kind==='wood'){for(let i=0;i<18;i++){x.strokeStyle=i%2?'rgba(0,0,0,.18)':'rgba(255,255,255,.05)';x.lineWidth=1+Math.random()*2;x.beginPath();x.moveTo(0,i*15+rand(5));x.bezierCurveTo(70,i*15+rand(12),180,i*15-rand(10),256,i*15+rand(8));x.stroke()}}
 else if(kind==='snow'){for(let i=0;i<900;i++){const a=Math.random()*.12;x.fillStyle=`rgba(70,100,120,${a})`;x.fillRect(rand(256),rand(256),rand(3,.3),rand(3,.3))}}
 else if(kind==='cloth'){for(let i=0;i<256;i+=4){x.strokeStyle='rgba(255,255,255,.035)';x.beginPath();x.moveTo(i,0);x.lineTo(0,i);x.stroke()}}
 else if(kind==='stone'){for(let i=0;i<1100;i++){const g=50+Math.floor(Math.random()*80);x.fillStyle=`rgba(${g},${g},${g},${Math.random()*.12})`;x.fillRect(rand(256),rand(256),rand(5,.5),rand(5,.5))}}
 const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.wrapS=t.wrapT=THREE.RepeatWrapping;t.anisotropy=8;return t;
}
const TEX={stone:texture('stone','#4d4d50','#202024'),cobble:texture('cobble','#31343a','#101216'),wet:texture('wet','#263436','#0d1718'),wood:texture('wood','#4a3526','#17100b'),snow:texture('snow','#d7e2e5','#9db2bc'),city:texture('city','#262938','#11131e'),obsidian:texture('obsidian','#24191d','#090607'),cloth:texture('cloth','#5b1d27','#24080d'),metal:texture('stone','#363b40','#0d1012')};
function mat(color,map=null,rough=.7,metal=.05,emissive=0,ei=0){const m=new THREE.MeshStandardMaterial({color,map,roughness:rough,metalness:metal,emissive,emissiveIntensity:ei});return m}
const M={stone:mat(0xffffff,TEX.stone,.9,.02),iron:mat(0x4b5054,TEX.metal,.36,.72),blackIron:mat(0x20242a,TEX.metal,.3,.85),wood:mat(0xffffff,TEX.wood,.86,.02),cloth:mat(0x8d2635,TEX.cloth,.88,.02),bone:mat(0xb9aa88,null,.9,.02),skin:mat(0x6d7366,null,.96,0),skinDark:mat(0x414b43,null,.98,0),leather:mat(0x4c2d20,null,.8,.05),gold:mat(0xb48b46,null,.31,.62),crystal:mat(0x83dfff,null,.17,.18,0x2c9dff,2.6),eye:mat(0xffd86a,null,.2,.05,0xff3c13,3.8)};
function mesh(g,m,x=0,y=0,z=0){const o=new THREE.Mesh(g,m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;return o}
function box(w,h,d,m,x=0,y=0,z=0){return mesh(new THREE.BoxGeometry(w,h,d),m,x,y,z)}
function cyl(r1,r2,h,seg,m,x=0,y=0,z=0){return mesh(new THREE.CylinderGeometry(r1,r2,h,seg),m,x,y,z)}
function sphere(r,m,x=0,y=0,z=0,seg=14){return mesh(new THREE.SphereGeometry(r,seg,Math.max(8,seg-4)),m,x,y,z)}
function cone(r,h,m,x=0,y=0,z=0,seg=8){return mesh(new THREE.ConeGeometry(r,h,seg),m,x,y,z)}

function init(){
 scene=new THREE.Scene();scene.fog=new THREE.FogExp2(STAGES[0].fog,.012);camera=new THREE.PerspectiveCamera(58,innerWidth/innerHeight,.08,320);
 renderer=new THREE.WebGLRenderer({canvas,antialias:!coarse,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,coarse?1.15:1.6));renderer.setSize(innerWidth,innerHeight,false);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;renderer.shadowMap.enabled=!coarse;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
 clock=new THREE.Clock();hemi=new THREE.HemisphereLight(0x9db4c5,0x151015,1.1);scene.add(hemi);keyLight=new THREE.DirectionalLight(0xdde7ff,1.4);keyLight.position.set(-18,28,14);keyLight.castShadow=!coarse;keyLight.shadow.mapSize.set(1024,1024);keyLight.shadow.camera.left=-34;keyLight.shadow.camera.right=34;keyLight.shadow.camera.top=50;keyLight.shadow.camera.bottom=-20;scene.add(keyLight);moonLight=new THREE.PointLight(0x89bfff,1.1,180);moonLight.position.set(-36,44,-110);scene.add(moonLight);
 player=createPlayer();scene.add(player);window.addEventListener('resize',resize);bindInputs();buildStage(0);updateHUD();animate();
}
function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}

function createPlayer(){
 const g=new THREE.Group();g.position.set(0,0,8);g.userData.vel=new THREE.Vector3();
 const coat=mat(0x25312b,null,.92,.02),armor=mat(0x3d4143,TEX.metal,.32,.72),trim=mat(0x8d754b,null,.35,.55),skin=mat(0xb58f78,null,.9,0),hair=mat(0x291b17,null,.94,0),gun=mat(0x24282c,TEX.metal,.26,.88);
 const torso=box(.78,1.15,.42,coat,0,1.55,0);g.add(torso);const chest=box(.86,.62,.48,armor,0,1.7,-.03);chest.rotation.z=.02;g.add(chest);
 const belt=box(.86,.15,.49,M.leather,0,1.06,0);g.add(belt);const head=sphere(.33,skin,0,2.32,0);head.scale.set(.92,1.08,.9);g.add(head);const hairCap=sphere(.35,hair,0,2.43,.03);hairCap.scale.set(1,1.08,.95);g.add(hairCap);
 for(const s of [-1,1]){const shoulder=sphere(.25,armor,s*.54,1.92,0,10);shoulder.scale.set(1.2,.7,1);g.add(shoulder);const arm=cyl(.12,.14,.9,8,coat,s*.5,1.45,-.13);arm.rotation.x=-.68;arm.rotation.z=s*.08;g.add(arm);const leg=cyl(.13,.17,1.03,8,coat,s*.23,.53,0);g.add(leg);const boot=box(.28,.28,.46,M.leather,s*.23,.08,-.11);g.add(boot)}
 const cloakGeo=new THREE.BufferGeometry();cloakGeo.setAttribute('position',new THREE.Float32BufferAttribute([-.43,1.98,.20,.43,1.98,.20,-.6,.42,.33,.43,1.98,.20,.62,.42,.33,-.6,.42,.33],3));cloakGeo.computeVertexNormals();const cloak=new THREE.Mesh(cloakGeo,M.cloth);cloak.material.side=THREE.DoubleSide;g.add(cloak);
 const rifle=new THREE.Group();rifle.position.set(.43,1.55,-.44);rifle.rotation.set(-.08,0,0);const stock=box(.18,.23,.72,M.wood,0,0,.28);rifle.add(stock);const receiver=box(.19,.2,.58,gun,0,.03,-.28);rifle.add(receiver);const barrel=cyl(.045,.055,1.02,10,gun,0,.03,-.94);barrel.rotation.x=Math.PI/2;rifle.add(barrel);const scope=cyl(.075,.075,.38,10,gun,0,.21,-.34);scope.rotation.x=Math.PI/2;rifle.add(scope);const scopeGlow=cyl(.058,.058,.02,10,M.crystal,0,.21,-.54);scopeGlow.rotation.x=Math.PI/2;rifle.add(scopeGlow);weaponMuzzle=new THREE.Object3D();weaponMuzzle.position.set(0,.03,-1.47);rifle.add(weaponMuzzle);weaponFlash=new THREE.PointLight(0xffb457,0,8);weaponMuzzle.add(weaponFlash);g.add(rifle);g.userData.rifle=rifle;
 return g;
}
function addCollBox(o,w,d){colliders.push({o,w,d})}
function addWall(x,z,w,h,d,m=M.stone){const o=box(w,h,d,m,x,h/2,z);scene.add(o);addCollBox(o,w,d);return o}
function addArch(x,z,rot=0,scale=1){const g=new THREE.Group();g.position.set(x,0,z);g.rotation.y=rot;const pillarMat=M.stone;for(const s of [-1,1]){const p=box(.8*scale,5.5*scale,1.2*scale,pillarMat,s*3.2*scale,2.75*scale,0);g.add(p);const cap=box(1.2*scale,.4*scale,1.45*scale,M.gold,s*3.2*scale,5.42*scale,0);g.add(cap)}const top=box(7.2*scale,1.0*scale,1.3*scale,pillarMat,0,5.7*scale,0);g.add(top);for(let i=-2;i<=2;i++){const tooth=box(.38*scale,.65*scale,1.4*scale,pillarMat,i*1.25*scale,6.52*scale,0);g.add(tooth)}scene.add(g);return g}
function addTower(x,z,h=18,accent=0xe0ae66){const g=new THREE.Group();g.position.set(x,0,z);const body=cyl(2.8,3.4,h,10,M.stone,0,h/2,0);g.add(body);const roof=cone(4.2,5.2,mat(0x201b22,null,.8,.15),0,h+2.2,0,10);g.add(roof);for(let i=0;i<4;i++){const a=i*Math.PI/2,w=box(.55,1.8,.14,mat(accent,null,.4,.2,accent,.55),Math.sin(a)*2.82,h*.72,Math.cos(a)*2.82);w.rotation.y=a;g.add(w)}scene.add(g);return g}
function addBanner(x,y,z,rot,color){const m=mat(color,TEX.cloth,.88,.02);const o=box(2.15,4.2,.06,m,x,y,z);o.rotation.y=rot;scene.add(o);const sig=new THREE.Mesh(new THREE.RingGeometry(.35,.48,8),new THREE.MeshBasicMaterial({color:0xd6b76f,side:THREE.DoubleSide}));sig.position.set(x+Math.sin(rot)*.05,y+.35,z+Math.cos(rot)*.05);sig.rotation.y=rot;scene.add(sig)}
function addBrazier(x,z,color=0xffa24d){const g=new THREE.Group();g.position.set(x,0,z);const stem=cyl(.14,.24,1.4,8,M.iron,0,.7,0);g.add(stem);const bowl=cyl(.52,.28,.32,10,M.blackIron,0,1.45,0);g.add(bowl);for(let i=0;i<3;i++){const f=cone(.13,.6,mat(0xffb54f,null,.2,0,color,4),rand(.22,-.22),1.95+rand(.18),rand(.2,-.2),7);g.add(f)}const l=new THREE.PointLight(color,coarse?1.0:1.7,16);l.position.set(0,2.1,0);g.add(l);scene.add(g);fx.push({type:'flame',g,base:1.45,phase:Math.random()*10});return g}
function addCrystal(x,z,color=0x61cfff,s=1){const g=new THREE.Group();g.position.set(x,0,z);for(let i=0;i<5;i++){const c=cone((.18+Math.random()*.18)*s,(1.3+Math.random()*1.8)*s,mat(color,null,.12,.12,color,2.7),rand(.55*s,-.55*s),.7*s,rand(.55*s,-.55*s),6);c.rotation.z=rand(.35,-.35);g.add(c)}const l=new THREE.PointLight(color,.65,10);l.position.y=1.1*s;g.add(l);scene.add(g);return g}
function addPine(x,z,s=1){const g=new THREE.Group();g.position.set(x,0,z);const trunk=cyl(.18,.26,2.3,7,mat(0x3c2920),0,1.15,0);g.add(trunk);for(let i=0;i<3;i++){const c=cone((1.4-i*.18)*s,2.3*s,mat(0x19342c,null,.95),0,2.3+i*.75,0,8);g.add(c)}scene.add(g)}
function addStatue(x,z,rot=0){const g=new THREE.Group();g.position.set(x,0,z);g.rotation.y=rot;const robe=cyl(.62,1.05,3.0,8,mat(0x4a4a4e,TEX.stone,.95),0,1.5,0);g.add(robe);const head=sphere(.42,M.stone,0,3.35,0,10);g.add(head);for(const s of [-1,1]){const arm=cyl(.12,.18,1.45,7,M.stone,s*.42,2.15,-.18);arm.rotation.z=s*.48;g.add(arm)}scene.add(g)}
function groundMaterial(stage){const t=TEX[stage.ground]||TEX.cobble;t.repeat.set(7,38);return new THREE.MeshStandardMaterial({map:t,color:stage.ground==='snow'?0xe9f1f3:0xffffff,roughness:stage.ground==='wet'||stage.ground==='city'?.28:.72,metalness:stage.ground==='city'?.12:.02})}
function clearWorld(){for(let i=scene.children.length-1;i>=0;i--){const o=scene.children[i];if(o!==hemi&&o!==keyLight&&o!==moonLight&&o!==player)scene.remove(o)}enemies.splice(0);pickups.splice(0);fx.splice(0);particles.splice(0);colliders.splice(0);state.boss=null;state.portal=null;state.bossSpawned=false}
function buildStage(idx){
 clearWorld();const s=STAGES[idx];scene.background=new THREE.Color(s.sky);scene.fog.color.setHex(s.fog);renderer.toneMappingExposure=idx===5?1.32:1.18;hemi.color.setHex(idx===5?0xffb2a1:idx===1?0xc8eaff:0xaec8d7);hemi.groundColor.setHex(idx===5?0x2a0608:0x101316);keyLight.color.setHex(idx===5?0xffc1a0:0xdde9ff);moonLight.color.setHex(s.magic);moonLight.intensity=idx===5?1.8:1.1;
 const floor=box(38,.28,185,groundMaterial(s),0,-.13,-77);floor.receiveShadow=true;scene.add(floor);
 for(const side of [-1,1]){for(let z=4;z>-166;z-=9){const w=5+Math.sin(z*.17)*1.2;addWall(side*(19+w*.5),z,w,4+rand(2),4,M.stone);if(Math.floor(Math.abs(z))%18===0)addBrazier(side*17.2,z,s.accent)}for(let z=-10;z>-160;z-=28)addTower(side*26,z,14+rand(10),s.accent)}
 for(let z=-8;z>-160;z-=32){addArch(0,z,0,.95);addBanner(-3.28,3.5,z+.7,0,idx===1?0x263d55:idx===5?0x5f1519:0x4e1723);addBanner(3.28,3.5,z+.7,0,idx===1?0x263d55:idx===5?0x5f1519:0x4e1723)}
 for(let z=-15;z>-150;z-=22){addCrystal((z%44===0?-1:1)*14.6,z+rand(4,-4),s.magic,idx===4?1.4:1)}
 if(idx===0){for(let z=-12;z>-150;z-=31){addStatue(-14.7,z,Math.PI/2);addStatue(14.7,z,-Math.PI/2)}for(let i=0;i<22;i++)addPine((i%2?-1:1)*rand(27,22),rand(10,-160),rand(1.4,.7))}
 if(idx===1){for(let i=0;i<42;i++)addPine((i%2?-1:1)*rand(31,20),rand(8,-164),rand(1.6,.75));for(let i=0;i<24;i++){const rock=mesh(new THREE.DodecahedronGeometry(rand(1.8,.5),0),mat(0x72828b,TEX.stone,.95));rock.position.set(rand(17,-17),rand(.7,.15),rand(-10,-150));rock.scale.y=rand(1.8,.55);scene.add(rock)}}
 if(idx===2){for(const side of [-1,1]){const water=box(7,.08,175,mat(0x0e6471,null,.16,.05,0x0b7890,.3),side*22,-.03,-76);scene.add(water);fx.push({type:'water',g:water,phase:side})}for(let z=-20;z>-145;z-=36){const fall=box(.12,7,5,mat(0xa8e9ff,null,.1,.02,0x4dbfd4,.8),-18,3.5,z);fall.material.transparent=true;fall.material.opacity=.35;scene.add(fall)}}
 if(idx===3){for(let z=0;z>-165;z-=7){for(const side of [-1,1]){const post=cyl(.22,.28,1.7,8,M.wood,side*17,.85,z);scene.add(post)}}for(let i=0;i<12;i++){const crate=box(rand(2.8,1.2),rand(1.5,.8),rand(2.8,1.2),M.wood,rand(14,-14),.75,rand(-15,-145));scene.add(crate)}addTower(-28,-128,26,0xffe0a0)}
 if(idx===4){for(let z=-8;z>-160;z-=18){for(const side of [-1,1]){const rune=box(.08,3.4,2.1,mat(s.magic,null,.2,.1,s.magic,2.2),side*18.1,2.5,z);scene.add(rune);const l=new THREE.PointLight(s.magic,.65,14);l.position.set(side*16.8,2.6,z);scene.add(l)}}}
 if(idx===5){for(const side of [-1,1]){const lava=box(8,.06,180,mat(0x6a0d05,null,.24,.05,0xff3300,1.9),side*23,-.03,-77);scene.add(lava);fx.push({type:'lava',g:lava,phase:side})}for(let z=-18;z>-155;z-=30){addStatue(-15,z,Math.PI/2);addStatue(15,z,-Math.PI/2)}}
 addSkyline(s);makeWeather(s.weather,s.magic);player.position.set(0,0,8);input.yaw=0;input.pitch=.15;state.kills=0;state.target=18+idx*4;state.hp=Math.min(state.maxHp,state.hp+25);state.ammo=state.mag;state.reserve=Math.max(state.reserve,40);state.stageStarted=performance.now();spawnWave(10+idx);ui.chapter.textContent=s.title;ui.stage.textContent=s.sub;ui.objective.textContent='Reach the Inner Sanctum';ui.objectiveSub.textContent=`Purge ${state.target} blighted • then defeat ${s.boss}`;ui.boss.classList.remove('show');updateHUD();toast(`${s.title} — ENTER`,1700)
}
function addSkyline(s){
 const moon=sphere(8,new THREE.MeshBasicMaterial({color:state.stage===5?0xc92b32:0xe6efff}),-38,45,-170,20);moon.material.fog=false;scene.add(moon);for(let i=0;i<13;i++){const x=(i-6)*18+rand(4,-4),z=-195-rand(45),h=rand(38,17);const t=box(rand(8,4),h,rand(8,4),mat(0x11141a,null,.95),x,h/2,z);t.castShadow=false;scene.add(t);const spire=cone(rand(5,2.5),rand(12,5),mat(0x0b0d12),x,h+rand(5,2),z,6);spire.castShadow=false;scene.add(spire)}for(let i=0;i<4;i++){const y=17+i*5,z=-185-i*6;const bridge=box(46,.7,.9,mat(0x171a20),0,y,z);scene.add(bridge)}}
function makeWeather(kind,color){const count=coarse?120:260,pos=new Float32Array(count*3);for(let i=0;i<count;i++){pos[i*3]=rand(48,-48);pos[i*3+1]=rand(28,.5);pos[i*3+2]=rand(18,-175)}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(pos,3));const size=kind==='snow'?.14:kind==='embers'?.11:.065;const pts=new THREE.Points(geo,new THREE.PointsMaterial({color:kind==='embers'?0xff7a36:kind==='snow'?0xf3fbff:color,size,transparent:true,opacity:kind==='mist'?.22:.62,depthWrite:false}));scene.add(pts);particles.push({pts,kind,speed:kind==='snow'?2.2:kind==='embers'?-1.5:kind==='mist'?.2:13})}

function createEnemy(type='shambler',boss=false){
 const g=new THREE.Group();const e={g,type,boss,hp:boss?36+state.stage*12:type==='brute'?7:type==='crystal'?4:3,maxHp:0,speed:boss?.78:type==='hound'?3.7:type==='crawler'?2.8:type==='knight'?1.85:2.15,damage:boss?18:type==='brute'?16:10,lastAttack:0,dead:false,stagger:0,phase:Math.random()*8};e.maxHp=e.hp;g.userData.enemy=e;
 const skin=type==='crystal'?mat(0x4e5e67,null,.75,.05,0x1d6fff,.35):type==='knight'?M.skinDark:M.skin;const cloth=type==='mariner'?mat(0x23393b,null,.9):M.cloth;
 if(type==='hound'){
  const body=box(1.05,.72,1.75,skin,0,.75,0);g.add(body);const head=box(.7,.62,.82,skin,0,.86,-1.05);g.add(head);const jaw=box(.5,.18,.45,M.bone,0,.58,-1.35);g.add(jaw);for(const s of [-1,1])for(const z of [-.55,.55]){const leg=cyl(.09,.13,.65,7,skin,s*.42,.32,z);g.add(leg)}for(const s of [-1,1]){const fang=cone(.07,.28,M.bone,s*.16,.52,-1.6,6);fang.rotation.x=Math.PI;g.add(fang)}
 }else if(type==='crawler'){
  const torso=box(1.0,.65,1.4,skin,0,.62,0);torso.rotation.x=.25;g.add(torso);const head=sphere(.4,skin,0,.75,-.9,10);g.add(head);for(const s of [-1,1]){const arm=cyl(.1,.15,1.2,7,skin,s*.55,.34,-.55);arm.rotation.z=s*.45;arm.rotation.x=-.6;g.add(arm);const leg=cyl(.11,.16,1.0,7,skin,s*.42,.31,.55);leg.rotation.x=.7;g.add(leg)}
 }else{
  const scale=type==='brute'?1.55:boss?1.7:1;const torso=box(.82*scale,1.18*scale,.48*scale,cloth,0,1.45*scale,0);g.add(torso);const chest=box(.95*scale,.58*scale,.56*scale,type==='knight'||boss?M.blackIron:M.leather,0,1.65*scale,-.04);g.add(chest);const head=sphere(.36*scale,skin,0,2.28*scale,-.05,12);head.userData.head=true;g.add(head);const mouth=box(.28*scale,.11*scale,.08*scale,mat(0x230608),0,2.12*scale,-.35*scale);g.add(mouth);for(const s of [-1,1]){const eye=sphere(.055*scale,M.eye,s*.13*scale,2.34*scale,-.34*scale,7);g.add(eye);const arm=cyl(.11*scale,.15*scale,.98*scale,7,skin,s*.54*scale,1.38*scale,-.1);arm.rotation.z=s*.12;g.add(arm);const leg=cyl(.13*scale,.18*scale,1.04*scale,7,cloth,s*.24*scale,.53*scale,0);g.add(leg)}
  if(type==='knight'||boss){for(const s of [-1,1]){const shoulder=sphere(.28*scale,M.blackIron,s*.55*scale,1.95*scale,0,9);shoulder.scale.set(1.3,.65,1);g.add(shoulder);const horn=cone(.13*scale,.75*scale,M.bone,s*.2*scale,2.72*scale,0,7);horn.rotation.z=s*.3;g.add(horn)}const blade=box(.12*scale,1.7*scale,.18*scale,M.iron,.72*scale,1.25*scale,-.2);blade.rotation.z=-.18;g.add(blade)}
  if(type==='crystal'){for(let i=0;i<5;i++){const a=i/5*Math.PI*2;const c=cone(.12*scale,.7*scale,M.crystal,Math.sin(a)*.45*scale,1.9*scale+Math.cos(i)*.25,Math.cos(a)*.25*scale,6);c.rotation.z=a*.18;g.add(c)}}
 }
 if(boss)decorateBoss(g,e);g.traverse(o=>{if(o.isMesh){o.userData.enemy=e;o.castShadow=true;o.receiveShadow=true}});return e
}
function decorateBoss(g,e){const s=STAGES[state.stage];g.scale.setScalar(state.stage===5?1.65:1.4);for(let i=0;i<8;i++){const a=i/8*Math.PI*2;const horn=cone(.18,.95,M.bone,Math.sin(a)*.72,4.2+Math.cos(a)*.18,Math.cos(a)*.3,7);horn.rotation.z=Math.sin(a)*.6;g.add(horn)}if(state.stage===0){const crown=cyl(.55,.7,.45,8,M.gold,0,4.28,0);g.add(crown)}if(state.stage===1){for(const x of [-.45,.45]){const antler=cyl(.06,.1,1.8,6,M.bone,x,4.35,.05);antler.rotation.z=x>0?-.55:.55;g.add(antler)}}if(state.stage===2){g.scale.z=1.35;for(let i=0;i<5;i++){const spike=cone(.18,.9,M.bone,0,2.3+i*.38,.4+i*.34,7);spike.rotation.x=-.45;g.add(spike)}}if(state.stage===3){for(let i=0;i<4;i++){const tent=cyl(.08,.18,3.1,7,M.skinDark,(i-1.5)*.32,1.5,.35);tent.rotation.x=.85+(i%2)*.25;g.add(tent)}}if(state.stage===4){for(let i=0;i<8;i++){const a=i/8*Math.PI*2;const c=cone(.18,.9,M.crystal,Math.sin(a)*.85,2.7+Math.cos(a)*.5,Math.cos(a)*.4,6);g.add(c)}}if(state.stage===5){for(const side of [-1,1]){const wing=new THREE.Mesh(new THREE.ConeGeometry(1.7,4.8,5),mat(0x351015,null,.65,.05,0x8b0a13,.28));wing.position.set(side*1.55,2.8,.5);wing.rotation.z=side*.76;wing.rotation.x=-.2;g.add(wing)}}const weak=sphere(.2,mat(s.magic,null,.1,.1,s.magic,4),0,2.7,-.55,10);weak.userData.weak=true;g.add(weak)}
function spawnEnemy(type,z=null,x=null,boss=false){const e=createEnemy(type,boss);e.g.position.set(x??rand(14,-14),0,z??rand(-28,-145));scene.add(e.g);enemies.push(e);return e}
function spawnWave(n){const s=STAGES[state.stage];for(let i=0;i<n;i++){const r=Math.random();const type=r<.1?'brute':r<.22?(state.stage>0?'hound':'crawler'):r<.34?(state.stage>3?'crystal':'crawler'):s.enemy;spawnEnemy(type,rand(-28,-138),rand(14,-14),false)}}
function spawnBoss(){if(state.bossSpawned)return;state.bossSpawned=true;state.boss=spawnEnemy('knight',-145,0,true);state.boss.g.scale.multiplyScalar(1.22);ui.bossName.textContent=STAGES[state.stage].boss;ui.boss.classList.add('show');ui.objective.textContent='Defeat the guardian';ui.objectiveSub.textContent='Break the glowing core for critical damage';toast(`${STAGES[state.stage].boss} — AWAKENED`,1800);soundBoss()}
function spawnPickup(x,z,type){const color=type==='ammo'?0xffd16a:0x55f2a2;const g=new THREE.Group();const ring=new THREE.Mesh(new THREE.TorusGeometry(.38,.045,7,20),mat(color,null,.12,.12,color,2.8));ring.rotation.x=Math.PI/2;ring.position.y=.4;g.add(ring);const core=type==='ammo'?box(.28,.5,.2,M.gold,0,.65,0):sphere(.24,mat(color,null,.2,.05,color,3),0,.65,0,10);g.add(core);g.position.set(x,0,z);scene.add(g);pickups.push({g,type,phase:Math.random()*5})}

function worldBlocked(x,z){if(x<-16.6||x>16.6||z>10||z<-158)return true;for(const c of colliders){const p=c.o.getWorldPosition(tempV);if(Math.abs(x-p.x)<c.w*.5+.45&&Math.abs(z-p.z)<c.d*.5+.45)return true}return false}
function damagePlayer(n){if(!state.running||performance.now()<state.dodgeUntil)return;state.hp=Math.max(0,state.hp-n);state.shake=Math.min(1.2,state.shake+.55);ui.blood.classList.add('on');setTimeout(()=>ui.blood.classList.remove('on'),130);soundDamage();if(state.hp<=0){state.running=false;showEnd(false);return}updateHUD()}
function heal(){if(!state.running||state.potions<=0||state.hp>=state.maxHp)return;state.potions--;state.hp=Math.min(state.maxHp,state.hp+45);toast('RESTORATIVE ELIXIR +45',900);soundPickup();updateHUD()}
function dodge(){const now=performance.now();if(!state.running||now<state.dodgeCd)return;state.dodgeCd=now+900;state.dodgeUntil=now+430;const f=new THREE.Vector3(-Math.sin(input.yaw),0,-Math.cos(input.yaw));const sx=(input.moveX||0),sy=(input.moveY||-1);const right=new THREE.Vector3(Math.cos(input.yaw),0,-Math.sin(input.yaw));const dir=f.multiplyScalar(-sy).add(right.multiplyScalar(sx)).normalize();const nx=player.position.x+dir.x*3.2,nz=player.position.z+dir.z*3.2;if(!worldBlocked(nx,nz)){player.position.x=nx;player.position.z=nz}state.shake=.28;toast('DODGE',330)}
function reload(){if(!state.running||state.reloading||state.ammo===state.mag||state.reserve<=0)return;state.reloading=true;toast('RELOADING…',700);soundReload();setTimeout(()=>{if(!state.reloading)return;const need=state.mag-state.ammo,take=Math.min(need,state.reserve);state.ammo+=take;state.reserve-=take;state.reloading=false;updateHUD()},850)}
function shoot(){const now=performance.now();if(!state.running||state.reloading||now<state.shotCd)return;if(state.ammo<=0){reload();return}state.shotCd=now+150;state.ammo--;state.shake=Math.min(1,state.shake+.24);weaponFlash.intensity=5;setTimeout(()=>weaponFlash.intensity=0,45);soundGun();
 raycaster.setFromCamera(new THREE.Vector2(.02,.04),camera);const targets=[];for(const e of enemies)if(!e.dead)targets.push(e.g);const hits=raycaster.intersectObjects(targets,true);let hitPoint=camera.position.clone().add(raycaster.ray.direction.clone().multiplyScalar(55));if(hits.length){const h=hits[0],e=h.object.userData.enemy;hitPoint.copy(h.point);if(e&&!e.dead){const weak=h.object.userData.weak||h.object.userData.head;const dmg=weak?3:1;e.hp-=dmg;e.stagger=performance.now()+160;hitFx(h.point,weak);ui.crosshair.classList.add('hit');setTimeout(()=>ui.crosshair.classList.remove('hit'),90);soundHit();if(e.hp<=0)killEnemy(e);if(e.boss)ui.bossFill.style.width=`${Math.max(0,e.hp/e.maxHp*100)}%`}}
 tracer(hitPoint);if(state.ammo===0&&state.reserve>0)setTimeout(reload,170);updateHUD()}
function tracer(end){const start=weaponMuzzle.getWorldPosition(new THREE.Vector3()),geo=new THREE.BufferGeometry().setFromPoints([start,end]);const line=new THREE.Line(geo,new THREE.LineBasicMaterial({color:0xffd37a,transparent:true,opacity:.95}));scene.add(line);fx.push({type:'tracer',g:line,born:performance.now(),life:80});const flash=sphere(.08,new THREE.MeshBasicMaterial({color:0xfff0ae}),start.x,start.y,start.z,6);scene.add(flash);fx.push({type:'tracer',g:flash,born:performance.now(),life:55})}
function hitFx(p,critical){for(let i=0;i<(critical?8:4);i++){const m=sphere(rand(.055,.02),new THREE.MeshBasicMaterial({color:critical?0x7edfff:0xb82a31}),p.x,p.y,p.z,5);m.userData.v=new THREE.Vector3(rand(.08,-.08),rand(.14,.03),rand(.08,-.08));scene.add(m);fx.push({type:'spark',g:m,born:performance.now(),life:420})}}
function killEnemy(e){e.dead=true;scene.remove(e.g);if(e.boss){state.boss=null;ui.boss.classList.remove('show');openPortal();toast(`${STAGES[state.stage].boss} DESTROYED`,1700);soundBossDown();return}state.kills++;if(state.kills%5===0)spawnPickup(e.g.position.x,e.g.position.z,state.kills%10===0?'med':'ammo');if(state.kills>=state.target&&!state.bossSpawned)spawnBoss();else if(enemies.filter(x=>!x.dead&&!x.boss).length<7&&!state.bossSpawned)spawnWave(6+state.stage);updateHUD()}
function openPortal(){const g=new THREE.Group();const ring=new THREE.Mesh(new THREE.TorusGeometry(2.1,.18,12,42),mat(STAGES[state.stage].magic,null,.18,.2,STAGES[state.stage].magic,3.4));ring.position.y=2.3;g.add(ring);const inner=new THREE.Mesh(new THREE.CircleGeometry(1.8,34),new THREE.MeshBasicMaterial({color:STAGES[state.stage].magic,transparent:true,opacity:.18,side:THREE.DoubleSide}));inner.position.y=2.3;inner.rotation.y=Math.PI;g.add(inner);const light=new THREE.PointLight(STAGES[state.stage].magic,2.5,28);light.position.y=2.2;g.add(light);g.position.set(0,0,-151);scene.add(g);state.portal=g;fx.push({type:'portal',g,phase:0});ui.objective.textContent='Enter the sanctuary gate';ui.objectiveSub.textContent='The seal is broken — advance'}
function nextStage(){state.stage++;if(state.stage>=STAGES.length){state.completed=true;state.running=false;showEnd(true);return}buildStage(state.stage)}

function updatePlayer(dt){if(!state.running)return;let f=(input.keys.has('KeyW')?1:0)-(input.keys.has('KeyS')?1:0)-input.moveY,st=(input.keys.has('KeyD')?1:0)-(input.keys.has('KeyA')?1:0)+input.moveX;const m=Math.hypot(f,st);if(m>1){f/=m;st/=m}const speed=performance.now()<state.dodgeUntil?11:5.6;const forward=new THREE.Vector3(-Math.sin(input.yaw),0,-Math.cos(input.yaw)),right=new THREE.Vector3(Math.cos(input.yaw),0,-Math.sin(input.yaw));const v=forward.multiplyScalar(f).add(right.multiplyScalar(st));if(v.lengthSq()>.001){v.normalize();const nx=player.position.x+v.x*speed*dt,nz=player.position.z+v.z*speed*dt;if(!worldBlocked(nx,player.position.z))player.position.x=nx;if(!worldBlocked(player.position.x,nz))player.position.z=nz;const targetYaw=Math.atan2(-v.x,-v.z);player.rotation.y=lerpAngle(player.rotation.y,targetYaw,1-Math.pow(.001,dt))}else player.rotation.y=lerpAngle(player.rotation.y,input.yaw,1-Math.pow(.02,dt));const bob=m?Math.sin(performance.now()*.012)*.028:0;player.position.y=bob;const rifle=player.userData.rifle;if(rifle){rifle.rotation.x=-.08+(state.shake*.08);rifle.rotation.z=Math.sin(performance.now()*.03)*state.shake*.02}if(state.portal&&player.position.distanceTo(state.portal.position)<3.2)nextStage()}
function lerpAngle(a,b,t){let d=(b-a+Math.PI)%(Math.PI*2)-Math.PI;return a+d*t}
function updateCamera(dt){const focus=player.position.clone().add(new THREE.Vector3(0,1.55,0));const dist=state.aiming?4.6:5.4,shoulder=state.aiming?.95:1.15;const yaw=input.yaw,pitch=input.pitch;const back=new THREE.Vector3(Math.sin(yaw)*dist,1.7+Math.sin(pitch)*3.0,Math.cos(yaw)*dist);const side=new THREE.Vector3(Math.cos(yaw)*shoulder,0,-Math.sin(yaw)*shoulder);const desired=focus.clone().add(back).add(side);if(state.shake>.001){desired.x+=rand(state.shake,-state.shake)*.08;desired.y+=rand(state.shake,-state.shake)*.06}camera.position.lerp(desired,1-Math.pow(.00005,dt));camera.lookAt(focus.clone().add(new THREE.Vector3(-Math.sin(yaw)*6,Math.sin(-pitch)*3,-Math.cos(yaw)*6)));state.shake*=Math.pow(.03,dt)}
function updateEnemies(dt,now){if(!state.running)return;for(const e of enemies){if(e.dead)continue;const p=e.g.position,dx=player.position.x-p.x,dz=player.position.z-p.z,d=Math.hypot(dx,dz)||1;e.g.rotation.y=Math.atan2(dx,dz);const stagger=now<e.stagger;if(!stagger&&d>(e.boss?2.4:1.15)){const sp=e.speed*(e.boss&&e.hp/e.maxHp<.4?1.35:1);p.x+=dx/d*sp*dt;p.z+=dz/d*sp*dt}const gait=Math.sin(now*.008*e.speed+e.phase);e.g.position.y=Math.abs(gait)*(e.type==='hound'?.06:.035);if(d<(e.boss?2.65:1.35)&&now-e.lastAttack>(e.boss?850:1100)){e.lastAttack=now;damagePlayer(e.damage)}if(e.boss&&now-e.lastAttack>1600&&d<10&&Math.random()<.012){e.lastAttack=now;bossShock(e)}}}
function bossShock(e){const ring=new THREE.Mesh(new THREE.RingGeometry(.8,1.1,36),new THREE.MeshBasicMaterial({color:STAGES[state.stage].magic,transparent:true,opacity:.75,side:THREE.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.set(e.g.position.x,.08,e.g.position.z);scene.add(ring);fx.push({type:'shock',g:ring,born:performance.now(),life:650});if(player.position.distanceTo(e.g.position)<7.5)damagePlayer(14)}
function updatePickups(now){for(let i=pickups.length-1;i>=0;i--){const p=pickups[i];p.g.rotation.y=now*.001+p.phase;p.g.position.y=.05+Math.sin(now*.003+p.phase)*.11;if(player.position.distanceTo(p.g.position)<1.5){if(p.type==='ammo'){state.reserve=Math.min(96,state.reserve+16);toast('AMMUNITION +16',700)}else{state.potions=Math.min(5,state.potions+1);toast('RESTORATIVE ELIXIR +1',700)}soundPickup();scene.remove(p.g);pickups.splice(i,1);updateHUD()}}}
function updateFx(now,dt){for(let i=fx.length-1;i>=0;i--){const f=fx[i];if(f.type==='flame'){f.g.rotation.y=Math.sin(now*.004+f.phase)*.04;continue}if(f.type==='water'){f.g.position.y=-.03+Math.sin(now*.0012+f.phase)*.02;continue}if(f.type==='lava'){f.g.material.emissiveIntensity=1.6+Math.sin(now*.003+f.phase)*.35;continue}if(f.type==='portal'){f.g.rotation.y+=dt*.45;continue}if(f.type==='spark'){f.g.position.add(f.g.userData.v);f.g.userData.v.y-=.007}else if(f.type==='shock'){const t=(now-f.born)/f.life;if(t<1){f.g.scale.setScalar(1+t*8);f.g.material.opacity=.75*(1-t)}}if(f.born&&now-f.born>f.life){scene.remove(f.g);fx.splice(i,1)}}for(const p of particles){const a=p.pts.geometry.attributes.position.array;for(let i=0;i<a.length;i+=3){a[i+1]-=p.speed*dt;if(p.kind==='rain'||p.kind==='storm')a[i]+=dt*2;if(p.kind==='embers')a[i]+=Math.sin(now*.002+i)*dt*.4;if((p.speed>0&&a[i+1]<0)||(p.speed<0&&a[i+1]>28))a[i+1]=p.speed>0?28:0}p.pts.geometry.attributes.position.needsUpdate=true}if(STAGES[state.stage].weather==='storm'&&Math.random()<dt*.055){ui.flash.classList.add('on');setTimeout(()=>ui.flash.classList.remove('on'),95)}}
function updateHUD(){ui.hp.style.width=`${state.hp/state.maxHp*100}%`;ui.hearts.innerHTML='';const full=Math.ceil(state.hp/20);for(let i=0;i<5;i++){const s=document.createElement('span');s.className='v4-heart'+(i<full?'':' empty');s.textContent='♥';ui.hearts.appendChild(s)}ui.ammo.textContent=state.ammo;ui.reserve.textContent=state.reserve;ui.kills.textContent=state.kills;ui.target.textContent=state.bossSpawned?'BOSS':state.target;ui.potion.textContent=state.potions;if(state.boss)ui.bossFill.style.width=`${Math.max(0,state.boss.hp/state.boss.maxHp*100)}%`}
function animate(){requestAnimationFrame(animate);const dt=Math.min(.035,clock.getDelta()),now=performance.now();updatePlayer(dt);updateEnemies(dt,now);updatePickups(now);updateFx(now,dt);updateCamera(dt);renderer.render(scene,camera)}

function bindInputs(){
 addEventListener('keydown',e=>{input.keys.add(e.code);if(e.code==='KeyR')reload();if(e.code==='KeyQ')heal();if(e.code==='ShiftLeft'||e.code==='ShiftRight')dodge();if(e.code==='Space'){e.preventDefault();shoot()}});addEventListener('keyup',e=>input.keys.delete(e.code));
 canvas.addEventListener('pointerdown',e=>{if(coarse||!state.running)return;if(document.pointerLockElement!==canvas){canvas.requestPointerLock?.();return}if(e.button===0)shoot();if(e.button===2)state.aiming=true});canvas.addEventListener('contextmenu',e=>e.preventDefault());addEventListener('pointerup',e=>{if(e.button===2)state.aiming=false});document.addEventListener('mousemove',e=>{if(document.pointerLockElement!==canvas||!state.running)return;input.yaw-=e.movementX*.0025;input.pitch=clamp(input.pitch-e.movementY*.0019,-.45,.72)});
 const stick=$('#v4-stick-zone'),knob=$('#v4-knob'),look=$('#v4-look-zone'),fire=$('#v4-fire'),dodgeBtn=$('#v4-dodge'),healBtn=$('#v4-heal');
 function stickApply(e){const r=stick.getBoundingClientRect(),cx=Math.max(70,r.width*.22),cy=r.height-82,dx=e.clientX-r.left-cx,dy=e.clientY-r.top-cy,lim=48,mag=Math.hypot(dx,dy),k=Math.min(1,mag/lim),nx=mag?dx/mag:0,ny=mag?dy/mag:0;input.moveX=nx*k;input.moveY=ny*k;knob.style.transform=`translate(${nx*Math.min(mag,lim)}px,${ny*Math.min(mag,lim)}px)`}
 stick?.addEventListener('pointerdown',e=>{input.stickPointer=e.pointerId;stick.setPointerCapture(e.pointerId);stickApply(e)});stick?.addEventListener('pointermove',e=>{if(e.pointerId===input.stickPointer)stickApply(e)});function stopStick(e){if(e.pointerId!==input.stickPointer)return;input.stickPointer=null;input.moveX=input.moveY=0;knob.style.transform='translate(0,0)'}stick?.addEventListener('pointerup',stopStick);stick?.addEventListener('pointercancel',stopStick);
 look?.addEventListener('pointerdown',e=>{input.lookPointer=e.pointerId;input.lastLook={x:e.clientX,y:e.clientY};look.setPointerCapture(e.pointerId)});look?.addEventListener('pointermove',e=>{if(e.pointerId!==input.lookPointer||!input.lastLook)return;const dx=e.clientX-input.lastLook.x,dy=e.clientY-input.lastLook.y;input.yaw-=dx*.0064;input.pitch=clamp(input.pitch-dy*.0048,-.45,.72);input.lastLook={x:e.clientX,y:e.clientY}});function stopLook(e){if(e.pointerId!==input.lookPointer)return;input.lookPointer=null;input.lastLook=null}look?.addEventListener('pointerup',stopLook);look?.addEventListener('pointercancel',stopLook);
 fire?.addEventListener('pointerdown',e=>{e.preventDefault();shoot();clearInterval(input.fireTimer);input.fireTimer=setInterval(shoot,180)});function stopFire(){clearInterval(input.fireTimer);input.fireTimer=0}fire?.addEventListener('pointerup',stopFire);fire?.addEventListener('pointercancel',stopFire);dodgeBtn?.addEventListener('pointerdown',e=>{e.preventDefault();dodge()});healBtn?.addEventListener('pointerdown',e=>{e.preventDefault();heal()});
 startBtn.addEventListener('click',startGame);
}
function startGame(){overlay.classList.add('hidden');root.classList.add('playing');state.running=true;state.completed=false;state.hp=100;state.potions=3;state.reserve=48;state.ammo=state.mag;state.stage=0;state.startedAt=performance.now();audioReady();buildStage(0);try{screen.orientation?.lock?.('landscape')?.catch?.(()=>{})}catch{}if(!coarse){try{root.requestFullscreen?.({navigationUI:'hide'})?.catch?.(()=>{})}catch{}}}
function showEnd(win){overlay.classList.remove('hidden');const title=$('#v4-title'),text=$('#v4-text');if(win){const sec=Math.floor((performance.now()-state.startedAt)/1000);title.innerHTML=`DAWN REMEMBERS<em>CAMPAIGN COMPLETE</em>`;text.textContent=`6つの呪われた領域を突破した。クリアタイム ${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}。再挑戦するたびに敵配置と戦闘展開が変化します。`;startBtn.textContent='NEW GAME'}else{title.innerHTML=`THE BLIGHT WON<em>MISSION FAILED</em>`;text.textContent='亡者の群れに飲み込まれた。回避、弱点射撃、弾薬回収を組み合わせて再挑戦してください。';startBtn.textContent='RETRY'}state.reloading=false}

function audioReady(){if(audio)return audio;const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return null;audio=new AC();master=audio.createGain();master.gain.value=.55;master.connect(audio.destination);noiseBuf=audio.createBuffer(1,audio.sampleRate,audio.sampleRate);const d=noiseBuf.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=Math.random()*2-1;return audio}
function osc(f,type='sine',g=.04,d=.1,slide=1,delay=0){if(!audioReady())return;const t=audio.currentTime+delay,o=audio.createOscillator(),v=audio.createGain();o.type=type;o.frequency.setValueAtTime(f,t);o.frequency.exponentialRampToValueAtTime(Math.max(20,f*slide),t+d);v.gain.setValueAtTime(g,t);v.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(v);v.connect(master);o.start(t);o.stop(t+d+.02)}
function noise(g=.06,d=.07,low=100,high=4000){if(!audioReady())return;const s=audio.createBufferSource(),f=audio.createBiquadFilter(),v=audio.createGain(),t=audio.currentTime;s.buffer=noiseBuf;f.type='bandpass';f.frequency.value=(low+high)/2;f.Q.value=.5;v.gain.setValueAtTime(g,t);v.gain.exponentialRampToValueAtTime(.0001,t+d);s.connect(f);f.connect(v);v.connect(master);s.start(t);s.stop(t+d+.02)}
function soundGun(){noise(.16,.06,160,4800);osc(92,'square',.08,.08,.42)}function soundHit(){osc(760,'triangle',.025,.045,.72);noise(.04,.04,700,3600)}function soundDamage(){noise(.14,.12,50,850);osc(72,'sine',.12,.22,.52)}function soundReload(){osc(850,'square',.025,.035,1.2);setTimeout(()=>osc(430,'triangle',.03,.05,.7),230)}function soundPickup(){[480,680,930].forEach((f,i)=>osc(f,'sine',.03,.1,1.04,i*.05))}function soundBoss(){noise(.16,.45,30,600);osc(42,'sawtooth',.13,.55,.48)}function soundBossDown(){[220,330,440,660].forEach((f,i)=>osc(f,'triangle',.045,.24,1.02,i*.07))}

init();
