'use strict';

const MOBILE_NAMES = ["ゾンビサバイバル", "ヴァンサバ系大量撃破", "見下ろし型ツインスティックシューター", "FPS", "TPS", "スナイパーゲーム", "ガンシューティング", "弾幕シューティング", "縦スクロールSTG", "横スクロールSTG", "全方位シューティング", "タワーディフェンス", "逆タワーディフェンス", "RTS", "オートバトラー", "放置RPG", "コマンドRPG", "アクションRPG", "ローグライクRPG", "ローグライト", "ダンジョン探索", "ハクスラ", "迷宮脱出", "脱出ゲーム", "ホラー脱出", "バックルーム探索", "鬼ごっこ", "かくれんぼ", "非対称対戦", "1対4サバイバル", "バトルロイヤル", "2D格闘", "3D格闘", "ベルトスクロールアクション", "ボスラッシュ", "剣戟アクション", "忍者アクション", "ステルス潜入", "暗殺ミッション", "パルクール", "横スクロールアクション", "メトロイドヴァニア", "プラットフォーマー", "ワンタップジャンプ", "エンドレスランナー", "障害物レース", "物理演算アクション", "ロープアクション", "落下アクション", "登山ゲーム", "レースゲーム", "ドリフトゲーム", "カートレース", "バイクレース", "水上レース", "飛行機レース", "交通シミュレーター", "駐車ゲーム", "電車運転", "フライトシミュレーター", "サッカー", "野球", "バスケットボール", "テニス", "卓球", "ゴルフ", "ボウリング", "ビリヤード", "ダーツ", "ボクシング", "相撲", "競馬", "釣り", "クレーンゲーム", "リズムゲーム", "音ゲー", "タイピングゲーム", "クイズゲーム", "早押しクイズ", "記憶力ゲーム", "間違い探し", "絵合わせ", "マッチ3", "落ち物パズル", "ブロックパズル", "数字パズル", "物理パズル", "配管パズル", "マージゲーム", "街づくり", "箱庭ゲーム", "経営シミュレーション", "コンビニ経営", "飲食店経営", "農場経営", "会社経営", "人生シミュレーション", "ペット育成", "モンスター育成", "オープンワールド探索"];
const CARD_NAMES = ["モンスター召喚対戦", "ゾンビ軍団カードバトル", "魔王対勇者カードゲーム", "ロボット改造カードバトル", "戦国武将デッキバトル", "三国志デッキバトル", "海賊船団カードバトル", "宇宙艦隊カードバトル", "恐竜バトルカード", "昆虫バトルカード", "動物王国カードゲーム", "神話の神々カードバトル", "妖怪カードバトル", "悪魔召喚カードゲーム", "天使対悪魔", "魔法学校カードゲーム", "錬金術カードゲーム", "ダンジョン攻略カードゲーム", "ボス討伐協力カードゲーム", "4人協力ゾンビカードゲーム", "裏切り者入り協力カードゲーム", "正体隠匿カードゲーム", "スパイ発見カードゲーム", "人狼風カードゲーム", "犯人探しカードゲーム", "殺人事件推理カード", "宝探しカードゲーム", "遺跡探索カードゲーム", "海底探索カードゲーム", "宇宙探索カードゲーム", "惑星開拓カードゲーム", "文明発展カードゲーム", "国家運営カードゲーム", "王国経営カードゲーム", "会社経営カードゲーム", "株式投資カードゲーム", "不動産投資カードゲーム", "飲食店経営カードゲーム", "コンビニ経営カードゲーム", "ホテル経営カードゲーム", "テーマパーク経営カード", "ゲーム会社経営カード", "病院経営カードゲーム", "学校経営カードゲーム", "農場経営カードゲーム", "牧場経営カードゲーム", "工場経営カードゲーム", "貿易カードゲーム", "オークションカードゲーム", "転売市場カードゲーム", "商品仕入れカードゲーム", "借金返済カードゲーム", "ギャンブル運勝負カード", "ブラフ勝負カードゲーム", "数字比べカードゲーム", "ハイ＆ローカードゲーム", "21点を目指すカードゲーム", "合計100を作るカードゲーム", "素数集めカードゲーム", "四則演算カードバトル", "数字陣取りカードゲーム", "色合わせカードゲーム", "マーク合わせカードゲーム", "連番作成カードゲーム", "ペア収集カードゲーム", "セットコレクション", "ドラフトカードゲーム", "デッキ構築ゲーム", "デッキ破壊ゲーム", "手札破壊ゲーム", "墓地利用カードゲーム", "時間逆行カードゲーム", "カード合成ゲーム", "カード進化ゲーム", "モンスター育成カード", "武器装備カードゲーム", "魔法コンボカードゲーム", "属性相性カードゲーム", "天候操作カードゲーム", "昼夜切替カードゲーム", "季節変化カードゲーム", "地形変更カードゲーム", "陣地取りカードバトル", "城攻めカードゲーム", "攻城戦カードゲーム", "砦防衛カードゲーム", "トラップ設置カードゲーム", "ダンジョン作成カードゲーム", "罠だらけ宝箱カード", "爆弾押し付けカードゲーム", "毒カード押し付けゲーム", "カードじゃんけん", "同時出し心理戦カード", "5秒以内カード選択ゲーム", "記憶カードバトル", "カード神経衰弱対戦", "早取りカードゲーム", "協力して100点を作るカードゲーム", "1対多数ボスカードゲーム", "100階ダンジョンカードゲーム"];
const BOARD_NAMES = ["王国陣取り", "島取りゲーム", "大陸征服", "世界征服", "都市占領", "城取りゲーム", "戦国領土争奪", "三国志領土争奪", "海賊海域争奪", "宇宙領土争奪", "惑星開拓", "火星開拓", "月面基地建設", "無人島開拓", "文明発展", "原始時代文明ゲーム", "中世王国経営", "未来都市経営", "街づくり", "村づくり", "テーマパーク建設", "動物園建設", "水族館建設", "遊園地経営", "コンビニチェーン経営", "レストラン経営", "ラーメン店経営", "ホテル経営", "カジノ経営", "工場経営", "鉄道会社経営", "航空会社経営", "運送会社経営", "ゲーム会社経営", "IT企業経営", "不動産経営", "株式投資ゲーム", "貿易ゲーム", "農場経営", "牧場経営", "鉱山開発", "石油採掘", "深海資源開発", "ダンジョン探索", "迷宮探索", "ランダムダンジョン", "宝探し", "遺跡探索", "ジャングル探検", "南極探検", "深海探検", "宇宙探検", "ゾンビ街脱出", "ゾンビ籠城", "パンデミック封じ込め", "エイリアン船脱出", "宇宙船修理", "沈没船脱出", "無人島脱出", "雪山遭難", "殺人鬼から逃げる", "幽霊屋敷脱出", "悪魔城攻略", "ドラゴン討伐", "魔王城攻略", "ボス討伐協力", "勇者パーティ協力", "裏切り者入りダンジョン", "人狼村ボードゲーム", "スパイ潜入", "犯人探し", "殺人事件推理", "怪盗対警察", "泥棒対警備員", "警察追跡ゲーム", "カーチェイスボードゲーム", "電車路線建設", "道路建設", "水道管建設", "電力網建設", "通信網建設", "荷物配送ゲーム", "宅配ルート最適化", "タクシー営業ゲーム", "宝石オークション", "美術品オークション", "闇市場取引ゲーム", "競馬育成ボードゲーム", "モンスター育成ボード", "恐竜パーク経営", "ロボット工場競争", "料理対決ボードゲーム", "寿司職人競争", "ラーメン職人競争", "釣り大会ボードゲーム", "登山競争", "無人島サバイバル対戦", "100階塔攻略", "5分間リアルタイム戦争", "4人同時リアルタイム陣取り"];
const PLAYING_NAMES = ["ハイカード", "ブラックジャック", "バカラ", "5カードドロー", "戦争", "スピード", "神経衰弱", "ババ抜き", "大富豪", "七並べ", "クレイジーエイト", "ハーツ", "スペード", "ジンラミー", "ラミー", "ゴーフィッシュ", "ソリティア", "ピラミッド", "ゴルフ", "スナップ"];
const MOBILE_ENGINES = ["tap", "boss", "strategy", "boss", "tap", "timing", "tap", "dodge", "tap", "runner", "tap", "strategy", "strategy", "strategy", "boss", "manage", "boss", "explore", "explore", "explore", "explore", "boss", "explore", "puzzle", "explore", "explore", "dodge", "explore", "strategy", "dodge", "dodge", "boss", "boss", "boss", "boss", "timing", "runner", "explore", "timing", "runner", "runner", "explore", "runner", "runner", "runner", "race", "timing", "runner", "dodge", "runner", "race", "race", "race", "race", "race", "race", "timing", "timing", "race", "timing", "timing", "timing", "timing", "timing", "timing", "timing", "timing", "timing", "timing", "boss", "timing", "race", "timing", "timing", "timing", "timing", "puzzle", "puzzle", "puzzle", "memory", "puzzle", "memory", "puzzle", "puzzle", "puzzle", "puzzle", "puzzle", "puzzle", "puzzle", "manage", "manage", "manage", "manage", "manage", "manage", "manage", "manage", "manage", "explore"];
const CARD_ENGINES = ["duel", "duel", "duel", "duel", "duel", "duel", "duel", "duel", "duel", "duel", "duel", "duel", "duel", "duel", "duel", "duel", "duel", "duel", "duel", "duel", "bluff", "bluff", "bluff", "bluff", "bluff", "bluff", "deck", "deck", "deck", "deck", "market", "market", "market", "market", "market", "market", "market", "market", "market", "market", "market", "market", "market", "market", "market", "market", "market", "market", "market", "market", "market", "market", "highlow", "bluff", "duel", "highlow", "target", "sets", "sets", "sets", "sets", "sets", "sets", "sets", "sets", "sets", "deck", "deck", "deck", "deck", "deck", "deck", "deck", "deck", "duel", "duel", "duel", "duel", "duel", "duel", "duel", "duel", "strategy", "strategy", "strategy", "strategy", "strategy", "strategy", "strategy", "strategy", "strategy", "bluff", "bluff", "duel", "sets", "memory", "memory", "timing", "target", "deck"];
const BOARD_ENGINES = ["territory", "territory", "territory", "territory", "territory", "territory", "territory", "territory", "territory", "territory", "economy", "economy", "economy", "economy", "economy", "economy", "economy", "economy", "economy", "economy", "economy", "economy", "economy", "economy", "economy", "economy", "economy", "economy", "economy", "economy", "economy", "economy", "economy", "economy", "economy", "economy", "economy", "economy", "economy", "economy", "gridquest", "gridquest", "gridquest", "gridquest", "gridquest", "gridquest", "gridquest", "gridquest", "gridquest", "gridquest", "gridquest", "gridquest", "gridquest", "gridquest", "gridquest", "gridquest", "gridquest", "gridquest", "gridquest", "gridquest", "gridquest", "gridquest", "gridquest", "gridquest", "gridquest", "bluffboard", "bluffboard", "bluffboard", "bluffboard", "bluffboard", "bluffboard", "bluffboard", "bluffboard", "bluffboard", "bluffboard", "route", "route", "route", "route", "route", "route", "route", "route", "route", "route", "economy", "economy", "economy", "economy", "economy", "race", "race", "race", "race", "race", "bossboard", "bossboard", "bossboard", "gridquest", "gridquest"];
const PLAYING_RULES = ["highcard","blackjack","baccarat","poker","war","speed","memory","oldmaid","daifugo","sevens","crazy8","hearts","spades","gin","rummy","gofish","solitaire","pyramid","golf","snap"];

const CAT = {
  mobile: {label:"スマホゲーム", short:"MOBILE", icon:"🎮", glow:"rgba(124,92,255,.24)"},
  card: {label:"カードゲーム", short:"CARD", icon:"🃏", glow:"rgba(255,84,112,.22)"},
  board: {label:"ボードゲーム", short:"BOARD", icon:"♟️", glow:"rgba(85,230,156,.20)"},
  playing: {label:"トランプ", short:"PLAYING CARDS", icon:"♠️", glow:"rgba(255,202,87,.22)"}
};

const ENGINE_META = {
  tap:["反射神経","敵やターゲットを素早くタップしてスコアを稼ぐ。"], boss:["ボス戦","弱点を叩いてHPを削り切る。被弾ゲージに注意。"], strategy:["戦略","盤面を読み、CPUより多くのマスを支配する。"], timing:["タイミング","動くゲージをベストゾーンで止めて高得点を狙う。"], dodge:["回避","ドラッグで移動して危険を避け、最後まで生き残る。"], runner:["アクション","タップでジャンプし、障害物を越え続ける。"], race:["レース","BOOSTを連打してCPUより先にゴールへ到達する。"], memory:["記憶","光った順番を覚えて正しく入力する。"], puzzle:["パズル","数字を小さい順にタップして盤面をクリアする。"], manage:["経営","資源を集め、投資して目標値まで成長させる。"], explore:["探索","グリッドを移動して目標物をすべて集める。"], duel:["カード対戦","手札から1枚選び、CPUとのカード勝負を制する。"], bluff:["心理戦","安全策かハイリスクかを選びCPUより多く得点する。"], deck:["デッキ構築","カードを選んでデッキを強化しボスを倒す。"], market:["経営カード","市場からカードを購入し、資産価値を伸ばす。"], highlow:["HIGH & LOW","次のカードが高いか低いかを予想する。"], target:["目標合計","カードを引いて目標値に近づける。超えると失敗。"], sets:["セット作成","指定された合計や組み合わせを手札から作る。"], territory:["陣取り","盤面をCPUと交互に取り合い、より多く支配する。"], economy:["開発","資源を使ってタイルを建設し目標スコアを目指す。"], gridquest:["探索ボード","マスを移動して目的地やアイテムへ到達する。"], bluffboard:["推理","候補マスを絞り込み、CPUより先に正解へ到達する。"], route:["ルート構築","障害物を避けてスタートからゴールまで道をつなぐ。"], connect:["コネクト","駒を落として先に4つ並べる。"], raceboard:["すごろく","サイコロを振ってCPUより先にゴールする。"], bossboard:["協力ボス","移動・攻撃・回復を選びボスを撃破する。"]
};

function mkCatalog(names, category, engines) { return names.map((title, i) => { const engine = engines[i]; const meta = ENGINE_META[engine] || ["PLAY","短時間で遊べるミニゲーム。"]; return { id: category[0] + String(i+1).padStart(3,"0"), category, title, engine, index:i+1, difficulty:1 + ((i * 7 + category.length) % 3), duration: category === "mobile" ? [30,45,60][i%3] : [45,60,90][i%3], mechanic: meta[0], description: `${title}をスマホ向けの短時間ルールに再構成。${meta[1]}` }; }); }
const catalog = [...mkCatalog(MOBILE_NAMES,"mobile",MOBILE_ENGINES), ...mkCatalog(CARD_NAMES,"card",CARD_ENGINES), ...mkCatalog(BOARD_NAMES,"board",BOARD_ENGINES), ...PLAYING_NAMES.map((title,i)=>({id:"p"+String(i+1).padStart(3,"0"),category:"playing",title,index:i+1,engine:"playing",rule:PLAYING_RULES[i],difficulty:1+(i%3),duration:[45,60,90][i%3],mechanic:"トランプ",description:`${title}を1人対CPUまたはソロ向けにブラウザで遊べる形へ最適化。`}))];

const $ = s => document.querySelector(s);
const els = {grid:$("#gameGrid"),search:$("#searchInput"),clear:$("#clearSearch"),tabs:$("#tabs"),visible:$("#visibleCount"),favCount:$("#favCount"),empty:$("#emptyState"),random:$("#randomBtn"),play:$("#playScreen"),stage:$("#gameStage"),close:$("#closeGame"),restart:$("#restartGame"),title:$("#playTitle"),cat:$("#playCategory"),badges:$("#playBadges"),desc:$("#playDescription"),favGame:$("#favGame"),full:$("#fullscreenBtn"),hint:$("#playHint"),toast:$("#toast")};
let activeCat="all",current=null,cleanupFns=[];
let favorites=new Set(JSON.parse(localStorage.getItem("megaArcadeFavorites")||"[]"));
let lastPlayed=JSON.parse(localStorage.getItem("megaArcadeRecent")||"[]");
function safeCleanup(){cleanupFns.splice(0).forEach(fn=>{try{fn()}catch(e){}});els.stage.innerHTML=""}
function onCleanup(fn){cleanupFns.push(fn)}
function rand(n){return Math.floor(Math.random()*n)}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function shuffle(a){const x=[...a];for(let i=x.length-1;i>0;i--){const j=rand(i+1);[x[i],x[j]]=[x[j],x[i]]}return x}
function iconFor(item){const icons={tap:["🎯","🧟","🔫","💥"],boss:["👹","🐉","🤖","🧟‍♂️"],strategy:["🧠","⚔️","🏰","🗺️"],timing:["⚡","🏹","🥊","🎵"],dodge:["🏃","☄️","👻","💣"],runner:["🏃‍♂️","🥷","🛹","🧗"],race:["🏎️","🏍️","🏇","🚤"],memory:["🧩","💡","🧠","🎼"],puzzle:["🔢","🧱","🧩","🔧"],manage:["🏙️","🏪","💰","🌾"],explore:["🗺️","🧭","💎","🚪"],duel:["🐲","⚔️","✨","🃏"],bluff:["🎭","🕵️","❓","💣"],deck:["📚","🪄","🧪","🛡️"],market:["💹","🏪","🏦","💎"],highlow:["↕️","🃏"],target:["🎯","➕"],sets:["🧩","🃏"],territory:["🏴","👑","🗺️"],economy:["🏗️","🏙️","💰"],gridquest:["🧭","🏰","🗝️"],bluffboard:["🔎","🕵️","🎭"],route:["🛤️","🚂","🔌"],playing:["♠️","♥️","♣️","♦️"]};const arr=icons[item.engine]||[CAT[item.category].icon];return arr[item.index%arr.length]}
function diffLabel(d){return ["","EASY","NORMAL","HARD"][d]}
function saveFavs(){localStorage.setItem("megaArcadeFavorites",JSON.stringify([...favorites]));updateFavCount()}
function updateFavCount(){els.favCount.textContent=favorites.size}
function toast(msg){els.toast.textContent=msg;els.toast.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>els.toast.classList.remove("show"),1400)}
function renderCatalog(){const q=els.search.value.trim().toLowerCase();let items=catalog.filter(x=>!q||(x.title+" "+x.mechanic+" "+x.description).toLowerCase().includes(q));if(activeCat==="favorite")items=items.filter(x=>favorites.has(x.id));else if(activeCat!=="all")items=items.filter(x=>x.category===activeCat);els.visible.textContent=items.length;els.empty.classList.toggle("hidden",items.length>0);els.grid.innerHTML=items.map(item=>`<article class="game-card" data-open="${item.id}" style="--card-glow:${CAT[item.category].glow}"><div class="card-top"><span class="game-no">${CAT[item.category].short} · ${String(item.index).padStart(2,"0")}</span><button class="fav-btn ${favorites.has(item.id)?"on":""}" data-fav="${item.id}" type="button" aria-label="お気に入り">${favorites.has(item.id)?"★":"☆"}</button></div><div class="game-icon">${iconFor(item)}</div><h3>${item.title}</h3><p>${item.description}</p><div class="card-meta"><span class="badge">${item.mechanic}</span><span class="play-chip">PLAY →</span></div></article>`).join("")}
els.grid.addEventListener("click",e=>{const fav=e.target.closest("[data-fav]");if(fav){e.stopPropagation();toggleFav(fav.dataset.fav);return}const c=e.target.closest("[data-open]");if(c)openGame(c.dataset.open)});
els.search.addEventListener("input",renderCatalog);els.clear.addEventListener("click",()=>{els.search.value="";renderCatalog();els.search.focus()});els.tabs.addEventListener("click",e=>{const b=e.target.closest("[data-cat]");if(!b)return;activeCat=b.dataset.cat;[...els.tabs.querySelectorAll(".tab")].forEach(x=>x.classList.toggle("active",x===b));renderCatalog()});els.random.addEventListener("click",()=>{const pool=activeCat==="all"||activeCat==="favorite"?catalog:catalog.filter(x=>x.category===activeCat);if(pool.length)openGame(pool[rand(pool.length)].id)});els.close.addEventListener("click",closeGame);els.restart.addEventListener("click",()=>current&&mountGame(current));els.full.addEventListener("click",async()=>{try{if(!document.fullscreenElement){await els.play.requestFullscreen();if(screen.orientation?.lock)screen.orientation.lock("landscape").catch(()=>{})}else await document.exitFullscreen()}catch(e){toast("全画面表示を利用できません")}});els.favGame.addEventListener("click",()=>current&&toggleFav(current.id));
function toggleFav(id){favorites.has(id)?favorites.delete(id):favorites.add(id);saveFavs();renderCatalog();if(current?.id===id)els.favGame.textContent=favorites.has(id)?"★":"☆";toast(favorites.has(id)?"お気に入りに追加":"お気に入りから削除")}
function openGame(id){current=catalog.find(x=>x.id===id);if(!current)return;els.play.classList.remove("hidden");document.body.style.overflow="hidden";els.title.textContent=current.title;els.cat.textContent=CAT[current.category].short;els.desc.textContent=current.description;els.badges.innerHTML=`<span class="badge">${current.mechanic}</span><span class="badge">${diffLabel(current.difficulty)}</span><span class="badge">タッチ対応</span>`;els.favGame.textContent=favorites.has(id)?"★":"☆";lastPlayed=[id,...lastPlayed.filter(x=>x!==id)].slice(0,12);localStorage.setItem("megaArcadeRecent",JSON.stringify(lastPlayed));mountGame(current)}
function closeGame(){safeCleanup();els.play.classList.add("hidden");document.body.style.overflow="";current=null}
function mountGame(item){safeCleanup();els.hint.textContent=item.category==="playing"?"カードをタップして操作":"画面をタップしてプレイ";if(item.category==="mobile")return mountMobile(item);if(item.category==="card")return mountCardGame(item);if(item.category==="board")return mountBoardGame(item);return mountPlaying(item)}
function hud(left,right){return `<div class="g-hud"><div class="g-pill">${left}</div><div class="g-pill">${right}</div></div>`}
function finish(title,sub,win=true){const d=document.createElement("div");d.className="g-result";d.innerHTML=`<div class="result-icon">${win?"🏆":"💀"}</div><h3>${title}</h3><p>${sub}</p><button class="g-primary" type="button">もう一度</button>`;d.querySelector("button").onclick=()=>current&&mountGame(current);els.stage.appendChild(d)}
function countdown(sec,onTick,onEnd){let left=sec,ended=false;onTick(left);const t=setInterval(()=>{left-=.1;onTick(Math.max(0,left));if(left<=0){clearInterval(t);ended=true;onEnd()}},100);onCleanup(()=>clearInterval(t));return ()=>{if(!ended){clearInterval(t);ended=true}}}
