(() => {
'use strict';
const $=s=>document.querySelector(s);
const COLS=6,ROWS=12,CELL=60,OX=15,COLORS=['#ff4f83','#43d98b','#ffd14d','#55a8ff','#a76cff'],GARBAGE=5;
const ui={score:$('#p15-score'),cpuScore:$('#p15-cpu-score'),chain:$('#p15-chain'),cpuChain:$('#p15-cpu-chain'),playerGarbage:$('#p15-player-garbage'),cpuGarbage:$('#p15-cpu-garbage'),playerIncoming:$('#p15-player-incoming'),cpuIncoming:$('#p15-cpu-incoming'),state:$('#p15-state'),elapsed:$('#p15-elapsed'),lastAttack:$('#p15-last-attack'),overlay:$('#p15-overlay'),title:$('#p15-title'),message:$('#p15-message'),start:$('#p15-start'),fullscreen:$('#p15-fullscreen')};
let running=false,startAt=0,raf=0,winner=null;
const randColor=()=>Math.floor(Math.random()*COLORS.length);

class BattleBoard{
  constructor({canvas,next,flash,cpu=false}){
    this.canvas=$(canvas);this.ctx=this.canvas.getContext('2d');this.nextCanvas=$(next);this.nctx=this.nextCanvas.getContext('2d');this.flash=$(flash);this.cpu=cpu;this.reset();
  }
  reset(){this.board=Array.from({length:ROWS},()=>Array(COLS).fill(-1));this.active=null;this.nextPair=[randColor(),randColor()];this.score=0;this.chain=0;this.incoming=0;this.resolving=false;this.lastFall=performance.now();this.fallEvery=this.cpu?720:650;this.cpuTarget=null;this.cpuActAt=0;this.spawn();this.renderStats();this.draw();}
  cells(x=this.active?.x,y=this.active?.y,rot=this.active?.rot,pair=this.active?.c){if(!pair)return[];const d=[[0,-1],[1,0],[0,1],[-1,0]][rot];return[{x,y,c:pair[0]},{x:x+d[0],y:y+d[1],c:pair[1]}];}
  canPlace(x,y,rot,pair=this.active?.c,board=this.board){return this.cells(x,y,rot,pair).every(p=>p.x>=0&&p.x<COLS&&p.y>=0&&p.y<ROWS&&board[p.y][p.x]<0);}
  spawn(){if(!running&&startAt!==0)return;const pair=this.nextPair;this.nextPair=[randColor(),randColor()];this.active={x:2,y:1,rot:0,c:[pair[0],pair[1]]};this.drawNext();if(!this.canPlace(this.active.x,this.active.y,this.active.rot)){endBattle(this.cpu?'YOU':'CPU','盤面が上まで埋まった');return;}if(this.cpu){this.cpuTarget=this.chooseCpuMove();this.cpuActAt=performance.now()+120+Math.random()*120;}}
  move(dx,dy){if(!running||this.resolving||!this.active)return false;if(this.canPlace(this.active.x+dx,this.active.y+dy,this.active.rot)){this.active.x+=dx;this.active.y+=dy;this.draw();return true;}if(dy>0)this.lock();return false;}
  rotate(dir){if(!running||this.resolving||!this.active)return false;const nr=(this.active.rot+dir+4)%4;for(const kick of [0,-1,1])if(this.canPlace(this.active.x+kick,this.active.y,nr)){this.active.x+=kick;this.active.rot=nr;this.draw();return true;}return false;}
  hardDrop(){if(!running||this.resolving||!this.active)return;let cells=0;while(this.canPlace(this.active.x,this.active.y+1,this.active.rot)){this.active.y++;cells++;}this.score+=cells;this.renderStats();this.lock();}
  lock(){if(!running||this.resolving||!this.active)return;for(const p of this.cells())this.board[p.y][p.x]=p.c;this.active=null;this.resolving=true;this.resolve(1,0);}
  gravity(){for(let x=0;x<COLS;x++){let write=ROWS-1;for(let y=ROWS-1;y>=0;y--){if(this.board[y][x]>=0){const v=this.board[y][x];this.board[y][x]=-1;this.board[write--][x]=v;}}}}
  findGroups(){const seen=Array.from({length:ROWS},()=>Array(COLS).fill(false)),groups=[];for(let y=0;y<ROWS;y++)for(let x=0;x<COLS;x++){const color=this.board[y][x];if(seen[y][x]||color<0||color===GARBAGE)continue;const stack=[[x,y]],group=[];seen[y][x]=true;while(stack.length){const [cx,cy]=stack.pop();group.push([cx,cy]);for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){const nx=cx+dx,ny=cy+dy;if(nx>=0&&nx<COLS&&ny>=0&&ny<ROWS&&!seen[ny][nx]&&this.board[ny][nx]===color){seen[ny][nx]=true;stack.push([nx,ny]);}}}if(group.length>=4)groups.push(group);}return groups;}
  resolve(depth,totalAttack){if(!running){this.resolving=false;return;}const groups=this.findGroups();if(!groups.length){this.chain=0;this.renderStats();if(totalAttack>0)sendAttack(this,totalAttack);this.applyIncoming();if(!running)return;this.resolving=false;this.spawn();return;}this.chain=depth;let removed=0;const garbageToClear=new Set();for(const group of groups){removed+=group.length;for(const [x,y] of group){this.board[y][x]=-1;for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){const nx=x+dx,ny=y+dy;if(nx>=0&&nx<COLS&&ny>=0&&ny<ROWS&&this.board[ny][nx]===GARBAGE)garbageToClear.add(`${nx},${ny}`);}}}for(const key of garbageToClear){const [x,y]=key.split(',').map(Number);this.board[y][x]=-1;}const gain=removed*30*depth*depth+garbageToClear.size*12;this.score+=gain;const generated=Math.max(1,Math.floor(removed/4))*depth+Math.max(0,depth-1)*2;totalAttack+=generated;this.renderStats();this.flash.textContent=`${depth} CHAIN!  +${generated}`;this.flash.classList.remove('show');void this.flash.offsetWidth;this.flash.classList.add('show');this.draw();setTimeout(()=>{if(!running)return;this.gravity();this.draw();setTimeout(()=>this.resolve(depth+1,totalAttack),120);},170);}
  applyIncoming(){if(this.incoming<=0||!running)return;const count=Math.min(this.incoming,30);this.incoming-=count;for(let i=0;i<count;i++){let candidates=[];for(let x=0;x<COLS;x++){let first=ROWS;for(let y=0;y<ROWS;y++)if(this.board[y][x]>=0){first=y;break;}const target=first===ROWS?ROWS-1:first-1;if(target>=0)candidates.push([x,target]);}if(!candidates.length){endBattle(this.cpu?'YOU':'CPU','おじゃまで盤面が埋まった');return;}const [x,y]=candidates[Math.floor(Math.random()*candidates.length)];this.board[y][x]=GARBAGE;}this.renderStats();this.draw();if(this.board[0].some(v=>v>=0)){endBattle(this.cpu?'YOU':'CPU','おじゃまで盤面が上まで埋まった');}}
  chooseCpuMove(){if(!this.active)return null;let best=null,bestScore=-Infinity;for(let rot=0;rot<4;rot++)for(let x=-1;x<COLS+1;x++){let y=1;if(!this.canPlace(x,y,rot,this.active.c))continue;while(this.canPlace(x,y+1,rot,this.active.c))y++;const clone=this.board.map(r=>r.slice());for(const p of this.cells(x,y,rot,this.active.c))clone[p.y][p.x]=p.c;let value=Math.random()*9;for(const p of this.cells(x,y,rot,this.active.c)){let same=0;for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){const nx=p.x+dx,ny=p.y+dy;if(nx>=0&&nx<COLS&&ny>=0&&ny<ROWS&&clone[ny][nx]===p.c)same++;}value+=same*15+(ROWS-p.y)*.35;}const groups=countGroupsOn(clone);value+=groups.clears*180+groups.maxSize*20-valueHeight(clone)*4;if(value>bestScore){bestScore=value;best={x,rot};}}return best||{x:2,rot:0};}
  cpuStep(now){if(!this.cpu||!running||this.resolving||!this.active||now<this.cpuActAt)return;const t=this.cpuTarget||{x:2,rot:0};if(this.active.rot!==t.rot){const diff=(t.rot-this.active.rot+4)%4;this.rotate(diff===3?-1:1);this.cpuActAt=now+75;return;}if(this.active.x!==t.x){this.move(this.active.x<t.x?1:-1,0);this.cpuActAt=now+70;return;}this.hardDrop();this.cpuActAt=now+300;}
  tick(now){if(!running||this.resolving||!this.active)return;if(this.cpu)this.cpuStep(now);if(now-this.lastFall>=this.fallEvery){this.move(0,1);this.lastFall=now;}}
  renderStats(){if(this.cpu){ui.cpuScore.textContent=this.score.toLocaleString();ui.cpuChain.textContent=this.chain;ui.cpuGarbage.textContent=this.incoming;ui.cpuIncoming.style.width=`${Math.min(100,this.incoming/30*100)}%`;}else{ui.score.textContent=this.score.toLocaleString();ui.chain.textContent=this.chain;ui.playerGarbage.textContent=this.incoming;ui.playerIncoming.style.width=`${Math.min(100,this.incoming/30*100)}%`;}}
  draw(){const g=this.ctx;g.clearRect(0,0,this.canvas.width,this.canvas.height);const bg=g.createLinearGradient(0,0,0,this.canvas.height);bg.addColorStop(0,this.cpu?'#111e35':'#1a1239');bg.addColorStop(1,'#060813');g.fillStyle=bg;g.fillRect(0,0,this.canvas.width,this.canvas.height);for(let y=0;y<ROWS;y++)for(let x=0;x<COLS;x++){g.fillStyle=(x+y)%2?'rgba(255,255,255,.018)':'rgba(255,255,255,.035)';g.fillRect(OX+x*CELL,y*CELL,CELL,CELL);const v=this.board[y][x];if(v>=0)this.drawOrb(g,OX+x*CELL+CELL/2,y*CELL+CELL/2,CELL*.41,v);}if(this.active){let gy=this.active.y;while(this.canPlace(this.active.x,gy+1,this.active.rot))gy++;for(const p of this.cells(this.active.x,gy,this.active.rot))this.drawOrb(g,OX+p.x*CELL+CELL/2,p.y*CELL+CELL/2,CELL*.37,p.c,.14);for(const p of this.cells())this.drawOrb(g,OX+p.x*CELL+CELL/2,p.y*CELL+CELL/2,CELL*.41,p.c);}g.strokeStyle='rgba(255,255,255,.09)';g.strokeRect(OX+.5,.5,COLS*CELL-1,ROWS*CELL-1);const grad=g.createLinearGradient(0,0,this.canvas.width,0);grad.addColorStop(0,'rgba(255,255,255,0)');grad.addColorStop(.5,'rgba(255,255,255,.035)');grad.addColorStop(1,'rgba(255,255,255,0)');g.fillStyle=grad;g.fillRect(0,0,this.canvas.width,90);}
  drawOrb(g,x,y,r,value,alpha=1){g.save();g.globalAlpha=alpha;if(value===GARBAGE){const grad=g.createRadialGradient(x-r*.28,y-r*.3,r*.12,x,y,r);grad.addColorStop(0,'#fff');grad.addColorStop(.22,'#cfd2db');grad.addColorStop(1,'#626878');g.fillStyle=grad;g.shadowColor='#e8ebff';g.shadowBlur=10;g.beginPath();g.arc(x,y,r*.9,0,Math.PI*2);g.fill();g.shadowBlur=0;g.fillStyle='#424755';g.beginPath();g.arc(x-r*.25,y-r*.02,r*.09,0,Math.PI*2);g.arc(x+r*.25,y-r*.02,r*.09,0,Math.PI*2);g.fill();g.restore();return;}const color=COLORS[value],grad=g.createRadialGradient(x-r*.3,y-r*.35,r*.12,x,y,r);grad.addColorStop(0,'#fff');grad.addColorStop(.16,color);grad.addColorStop(1,shade(color,-38));g.fillStyle=grad;g.shadowColor=color;g.shadowBlur=15;g.beginPath();g.arc(x,y,r,0,Math.PI*2);g.fill();g.shadowBlur=0;g.fillStyle='rgba(255,255,255,.72)';g.beginPath();g.ellipse(x-r*.28,y-r*.3,r*.16,r*.09,-.5,0,Math.PI*2);g.fill();g.fillStyle='rgba(15,12,35,.6)';g.beginPath();g.arc(x-r*.17,y+r*.03,r*.055,0,Math.PI*2);g.arc(x+r*.17,y+r*.03,r*.055,0,Math.PI*2);g.fill();g.restore();}
  drawNext(){const g=this.nctx;g.clearRect(0,0,this.nextCanvas.width,this.nextCanvas.height);this.drawOrb(g,56,29,20,this.nextPair[1]);this.drawOrb(g,56,65,20,this.nextPair[0]);}
}

function countGroupsOn(board){const seen=Array.from({length:ROWS},()=>Array(COLS).fill(false));let clears=0,maxSize=0;for(let y=0;y<ROWS;y++)for(let x=0;x<COLS;x++){const color=board[y][x];if(color<0||color===GARBAGE||seen[y][x])continue;const stack=[[x,y]];seen[y][x]=true;let n=0;while(stack.length){const [cx,cy]=stack.pop();n++;for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){const nx=cx+dx,ny=cy+dy;if(nx>=0&&nx<COLS&&ny>=0&&ny<ROWS&&!seen[ny][nx]&&board[ny][nx]===color){seen[ny][nx]=true;stack.push([nx,ny]);}}}if(n>=4)clears++;maxSize=Math.max(maxSize,n);}return{clears,maxSize};}
function valueHeight(board){let sum=0;for(let x=0;x<COLS;x++)for(let y=0;y<ROWS;y++)if(board[y][x]>=0){sum+=ROWS-y;break;}return sum;}
function shade(hex,amt){const n=parseInt(hex.slice(1),16),r=Math.max(0,Math.min(255,(n>>16)+amt)),g=Math.max(0,Math.min(255,((n>>8)&255)+amt)),b=Math.max(0,Math.min(255,(n&255)+amt));return `rgb(${r},${g},${b})`;}

const player=new BattleBoard({canvas:'#p15-canvas',next:'#p15-next',flash:'#p15-flash'}),cpu=new BattleBoard({canvas:'#p15-cpu-canvas',next:'#p15-cpu-next',flash:'#p15-cpu-flash',cpu:true});
function sendAttack(source,count){if(!running||count<=0)return;let attack=count;if(source.incoming>0){const cancel=Math.min(source.incoming,attack);source.incoming-=cancel;attack-=cancel;source.renderStats();}if(attack<=0){ui.lastAttack.textContent='CANCEL';return;}const target=source===player?cpu:player;target.incoming+=attack;target.renderStats();ui.lastAttack.textContent=String(attack);ui.state.textContent=source===player?'YOU ATTACK':'CPU ATTACK';setTimeout(()=>{if(running)ui.state.textContent='BATTLE';},550);}
function startBattle(){cancelAnimationFrame(raf);running=false;winner=null;startAt=performance.now();player.reset();cpu.reset();running=true;player.spawn();cpu.spawn();ui.state.textContent='BATTLE';ui.lastAttack.textContent='0';ui.overlay.classList.add('hidden');loop(startAt);}
function endBattle(win,reason){if(!running)return;running=false;winner=win;cancelAnimationFrame(raf);ui.state.textContent=win==='YOU'?'YOU WIN':'YOU LOSE';ui.title.textContent=win==='YOU'?'YOU WIN!':'YOU LOSE';const elapsed=formatElapsed((performance.now()-startAt)/1000);ui.message.innerHTML=win==='YOU'?`CPUの盤面を埋め切った。<br><strong>${elapsed}</strong> / SCORE ${player.score.toLocaleString()}`:`${reason}。<br>CPU SCORE ${cpu.score.toLocaleString()} / <strong>${elapsed}</strong>`;ui.start.textContent='再戦する';ui.overlay.classList.remove('hidden');player.draw();cpu.draw();}
function loop(now){if(!running)return;player.tick(now);cpu.tick(now);player.draw();cpu.draw();ui.elapsed.textContent=formatElapsed((now-startAt)/1000);raf=requestAnimationFrame(loop);}
function formatElapsed(sec){const m=Math.floor(sec/60),s=Math.floor(sec%60);return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;}
function action(name){if(player.cpu)return;({left:()=>player.move(-1,0),right:()=>player.move(1,0),down:()=>player.move(0,1),rotateL:()=>player.rotate(-1),rotateR:()=>player.rotate(1),drop:()=>player.hardDrop()}[name]||(()=>{}))();}
addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowDown',' ','z','Z','x','X'].includes(e.key))e.preventDefault();if(e.repeat&&['z','Z','x','X',' '].includes(e.key))return;if(e.key==='ArrowLeft')action('left');else if(e.key==='ArrowRight')action('right');else if(e.key==='ArrowDown')action('down');else if(e.key==='z'||e.key==='Z')action('rotateL');else if(e.key==='x'||e.key==='X')action('rotateR');else if(e.key===' ')action('drop');});
document.querySelectorAll('[data-p15]').forEach(btn=>btn.addEventListener('pointerdown',e=>{e.preventDefault();action(btn.dataset.p15);}));
ui.start.addEventListener('click',startBattle);ui.fullscreen.addEventListener('click',()=>{if(!document.fullscreenElement)document.documentElement.requestFullscreen?.();else document.exitFullscreen?.();});document.addEventListener('fullscreenchange',()=>ui.fullscreen.textContent=document.fullscreenElement?'EXIT FULLSCREEN':'FULLSCREEN');
player.draw();cpu.draw();
})();
