(() => {
'use strict';
const canvas=document.getElementById('p15-canvas'),ctx=canvas.getContext('2d'),nextCanvas=document.getElementById('p15-next'),nctx=nextCanvas.getContext('2d');
const timeEl=document.getElementById('p15-time'),scoreEl=document.getElementById('p15-score'),chainEl=document.getElementById('p15-chain'),bestEl=document.getElementById('p15-best'),overlay=document.getElementById('p15-overlay'),titleEl=document.getElementById('p15-title'),messageEl=document.getElementById('p15-message'),startBtn=document.getElementById('p15-start'),flash=document.getElementById('p15-flash');
const COLS=6,ROWS=12,CELL=60,OX=30,OY=0,COLORS=['#ff4f83','#49d98d','#ffce4a','#58a8ff','#a86cff'];
let board,active,nextPair,score=0,chain=0,best=Number(localStorage.getItem('game15-best')||0),running=false,resolving=false,startAt=0,lastFall=0,fallEvery=610,raf=0;
bestEl.textContent=best;
const randColor=()=>Math.floor(Math.random()*COLORS.length);
function reset(){board=Array.from({length:ROWS},()=>Array(COLS).fill(-1));nextPair=[randColor(),randColor()];score=0;chain=0;fallEvery=610;scoreEl.textContent='0';chainEl.textContent='0';spawn();draw();}
function spawn(){const pair=nextPair;nextPair=[randColor(),randColor()];active={x:2,y:1,rot:0,c:[pair[0],pair[1]]};drawNext();if(!canPlace(active.x,active.y,active.rot)){endGame('盤面がいっぱい！');}}
function cells(x=active.x,y=active.y,rot=active.rot){const d=[[0,-1],[1,0],[0,1],[-1,0]][rot];return [{x,y,c:active.c[0]},{x:x+d[0],y:y+d[1],c:active.c[1]}];}
function canPlace(x,y,rot){return cells(x,y,rot).every(p=>p.x>=0&&p.x<COLS&&p.y<ROWS&&p.y>=0&&board[p.y][p.x]<0);}
function move(dx,dy){if(!running||resolving||!active)return false;if(canPlace(active.x+dx,active.y+dy,active.rot)){active.x+=dx;active.y+=dy;draw();return true}if(dy>0)lock();return false;}
function rotate(dir){if(!running||resolving||!active)return;const nr=(active.rot+dir+4)%4;for(const kick of [0,-1,1]){if(canPlace(active.x+kick,active.y,nr)){active.x+=kick;active.rot=nr;draw();return;}}}
function hardDrop(){if(!running||resolving||!active)return;while(canPlace(active.x,active.y+1,active.rot))active.y++;score+=3;scoreEl.textContent=score;lock();}
function lock(){if(resolving||!active)return;for(const p of cells())board[p.y][p.x]=p.c;active=null;resolving=true;resolveBoard(1);}
function gravity(){for(let x=0;x<COLS;x++){let write=ROWS-1;for(let y=ROWS-1;y>=0;y--){if(board[y][x]>=0){const v=board[y][x];board[y][x]=-1;board[write--][x]=v;}}}}
function findGroups(){const seen=Array.from({length:ROWS},()=>Array(COLS).fill(false)),groups=[];for(let y=0;y<ROWS;y++)for(let x=0;x<COLS;x++){if(seen[y][x]||board[y][x]<0)continue;const color=board[y][x],stack=[[x,y]],group=[];seen[y][x]=true;while(stack.length){const [cx,cy]=stack.pop();group.push([cx,cy]);for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){const nx=cx+dx,ny=cy+dy;if(nx>=0&&nx<COLS&&ny>=0&&ny<ROWS&&!seen[ny][nx]&&board[ny][nx]===color){seen[ny][nx]=true;stack.push([nx,ny]);}}}if(group.length>=4)groups.push(group);}return groups;}
function resolveBoard(depth){if(!running){resolving=false;return;}const groups=findGroups();if(!groups.length){chain=0;chainEl.textContent='0';resolving=false;spawn();return;}chain=depth;chainEl.textContent=String(depth);let removed=0;for(const g of groups){removed+=g.length;for(const [x,y] of g)board[y][x]=-1;}const gain=removed*20*depth*depth;score+=gain;scoreEl.textContent=score;flash.textContent=`${depth} CHAIN +${gain}`;flash.classList.remove('show');void flash.offsetWidth;flash.classList.add('show');draw();setTimeout(()=>{gravity();draw();setTimeout(()=>resolveBoard(depth+1),130);},170);}
function drawOrb(g,x,y,r,color,alpha=1){g.save();g.globalAlpha=alpha;const grad=g.createRadialGradient(x-r*.3,y-r*.35,r*.15,x,y,r);grad.addColorStop(0,'#fff');grad.addColorStop(.18,color);grad.addColorStop(1,shade(color,-36));g.fillStyle=grad;g.shadowColor=color;g.shadowBlur=15;g.beginPath();g.arc(x,y,r,0,Math.PI*2);g.fill();g.shadowBlur=0;g.fillStyle='rgba(255,255,255,.55)';g.beginPath();g.ellipse(x-r*.28,y-r*.28,r*.18,r*.1,-.5,0,Math.PI*2);g.fill();g.restore();}
function shade(hex,amt){let n=parseInt(hex.slice(1),16),r=Math.max(0,Math.min(255,(n>>16)+amt)),g=Math.max(0,Math.min(255,((n>>8)&255)+amt)),b=Math.max(0,Math.min(255,(n&255)+amt));return `rgb(${r},${g},${b})`;}
function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);const bg=ctx.createLinearGradient(0,0,0,canvas.height);bg.addColorStop(0,'#171632');bg.addColorStop(1,'#070b1d');ctx.fillStyle=bg;ctx.fillRect(0,0,canvas.width,canvas.height);for(let y=0;y<ROWS;y++)for(let x=0;x<COLS;x++){ctx.fillStyle=(x+y)%2?'rgba(255,255,255,.025)':'rgba(255,255,255,.045)';ctx.fillRect(OX+x*CELL,OY+y*CELL,CELL,CELL);if(board[y][x]>=0)drawOrb(ctx,OX+x*CELL+CELL/2,OY+y*CELL+CELL/2,CELL*.41,COLORS[board[y][x]]);}if(active){let ghostY=active.y;while(canPlace(active.x,ghostY+1,active.rot))ghostY++;for(const p of cells(active.x,ghostY,active.rot))drawOrb(ctx,OX+p.x*CELL+CELL/2,OY+p.y*CELL+CELL/2,CELL*.38,COLORS[p.c],.18);for(const p of cells())drawOrb(ctx,OX+p.x*CELL+CELL/2,OY+p.y*CELL+CELL/2,CELL*.41,COLORS[p.c]);}ctx.strokeStyle='rgba(255,255,255,.11)';ctx.strokeRect(OX+.5,.5,COLS*CELL-1,ROWS*CELL-1);}
function drawNext(){nctx.clearRect(0,0,140,140);drawOrb(nctx,70,45,25,COLORS[nextPair[1]]);drawOrb(nctx,70,95,25,COLORS[nextPair[0]]);}
function start(){cancelAnimationFrame(raf);running=true;resolving=false;startAt=performance.now();lastFall=startAt;reset();overlay.classList.add('hidden');loop(startAt);}
function loop(now){if(!running)return;const elapsed=(now-startAt)/1000,remain=Math.max(0,20-elapsed);timeEl.textContent=remain.toFixed(1);if(remain<=0){endGame('20秒終了！');return;}fallEvery=Math.max(310,610-elapsed*10);if(!resolving&&active&&now-lastFall>=fallEvery){move(0,1);lastFall=now;}draw();raf=requestAnimationFrame(loop);}
function endGame(reason){if(!running&&reason!=='盤面がいっぱい！')return;running=false;cancelAnimationFrame(raf);if(score>best){best=score;localStorage.setItem('game15-best',String(best));bestEl.textContent=best;}titleEl.textContent='RESULT';messageEl.innerHTML=`${reason}<br><strong>${score.toLocaleString()} POINTS</strong><br>BEST ${best.toLocaleString()}`;startBtn.textContent='もう一度';overlay.classList.remove('hidden');timeEl.textContent='0.0';draw();}
function action(name){({left:()=>move(-1,0),right:()=>move(1,0),down:()=>move(0,1),rotateL:()=>rotate(-1),rotateR:()=>rotate(1),drop:hardDrop}[name]||(()=>{}))();}
window.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowDown',' ','z','Z','x','X'].includes(e.key))e.preventDefault();if(e.repeat&&['z','Z','x','X',' '].includes(e.key))return;if(e.key==='ArrowLeft')action('left');else if(e.key==='ArrowRight')action('right');else if(e.key==='ArrowDown')action('down');else if(e.key==='z'||e.key==='Z')action('rotateL');else if(e.key==='x'||e.key==='X')action('rotateR');else if(e.key===' ')action('drop');});
document.querySelectorAll('[data-p15]').forEach(btn=>{btn.addEventListener('pointerdown',e=>{e.preventDefault();action(btn.dataset.p15);});});startBtn.addEventListener('click',start);reset();
})();
