(()=>{'use strict';
const E=window.RonbunEngine,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const btn=(act,label,id='',cls='btn',extra='')=>`<button type="button" class="${cls}" data-act="${act}" data-id="${esc(id)}" ${extra}>${esc(label)}</button>`;
const link=(url,label)=>`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(label)} ↗</a>`;
const title=(kicker,h,desc='')=>`<div class="page-heading"><div><span class="eyebrow">${esc(kicker)}</span><h1>${esc(h)}</h1>${desc?`<p class="lead">${esc(desc)}</p>`:''}</div></div>`;
const empty=(h,p,button='')=>`<div class="panel empty"><h2>${esc(h)}</h2><p>${esc(p)}</p>${button?`<div class="actions">${button}</div>`:''}</div>`;
const date=t=>new Date(t).toLocaleDateString('ja-JP',{year:'numeric',month:'short',day:'numeric'}),clock=ms=>{const n=Math.ceil(ms/1000);return`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;};
let papers=[],lessons=[],sources={},articles={},data=E.fresh(),ready=false,current={view:'home',id:''},toastTimer,storageBroken=false;
let unreadableBackup='';
let paperFilter={subject:'',year:'',status:'',query:''},reviewFilter={subject:'',status:''};
const byPaper=new Map(),byLesson=new Map(),years=Array.from({length:15},(_,i)=>2025-i);
const guide={
 '答案の基本':{sub:'設問を読む → 構成する → 根拠を示して書く',checks:['主体・相手方・求める法律効果を特定した','全設問の見出しと結論を用意した','規範と事実評価を分けた','反対事情に応答した','時間と紙幅を配分した']},
 '憲法':{sub:'権利と制約を捉え、審査の密度を説明する',checks:['主張する主体・活動・保障条文を特定した','規制の内容と制約の強さを示した','権利の性質と規制態様から審査の密度を説明した','目的・手段を分けて事実を評価した','指定された立場・反論・自説の全てに答えた']},
 '行政法':{sub:'個別法の仕組みから、救済と違法性を考える',checks:['法令の目的・主体・要件・効果を整理した','求める救済に対応する訴訟を選んだ','処分性・原告適格等の必要な訴訟要件を検討した','実体と手続の違法を分け、具体的条文に即して論じた','判決や仮の救済の効果まで確認した']},
 '民法':{sub:'請求権の要件から、抗弁・再抗弁へ進む',checks:['誰の誰に対する何の請求かを特定した','請求の根拠条文と要件を示した','権利発生・対抗関係・消滅を区別した','抗弁と再抗弁を事実と対応させた','複数の請求・当事者関係の結論が整合している']},
 '商法':{sub:'会社の構造と利害関係から、手段を選ぶ',checks:['公開・非公開、機関設計、当事者の地位を確認した','行為・決議の瑕疵と責任を区別した','訴えや差止めの要件・期間・主体を確認した','株主・会社・取締役・第三者の利益を評価した','救済の効果と責任の範囲を結論に示した']},
 '民事訴訟法':{sub:'訴訟の段階と原則の趣旨を押さえる',checks:['訴訟物・当事者・手続段階を特定した','当事者の主張と裁判所の判断範囲を区別した','適用条文と訴訟原則の趣旨を示した','手続保障・不意打ち・紛争解決の事情を評価した','判決の効力や次に採る手続を確認した']},
 '刑法':{sub:'人・行為・時間を分け、成立犯罪と罪数へ',checks:['行為者・行為・結果を時系列で分けた','構成要件と故意・因果関係を検討した','違法性阻却と責任の問題を整理した','共犯の認識・役割・関与時期を示した','成立犯罪と罪数を結論に示した']},
 '刑事訴訟法':{sub:'行為の根拠と要証事実から判断する',checks:['捜査・公判の対象行為と時点を特定した','強制処分性・法律の根拠・要件を区別した','必要性・相当性を具体的事情から評価した','証拠ごとに要証事実と証拠能力を確認した','違法性と排除、訴因変更の必要性と可否等を混同していない']},
 '民事実務基礎':{sub:'相談記録を、主張・証拠・対応に整理する',checks:['依頼者の目的と請求の趣旨を確認した','請求原因・抗弁・再抗弁の主要事実を区別した','主要事実と証拠を対応させた','反対仮説と証拠の信用性を検討した','倫理を含め弁護士として採る行動を示した']},
 '刑事実務基礎':{sub:'証拠の読み方と、弁護・訴追の行動を学ぶ',checks:['犯罪要件と証拠の対応を整理した','証拠能力と証明力を区別した','供述経過と客観証拠、反対事情を評価した','身柄・公判の段階に応じた手段を選んだ','倫理・本人への説明・具体的対応を示した']}
};
function toast(s){$('#toast').textContent=s;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,4200);}
function storageAlert(s){storageBroken=true;$('#storageAlert').hidden=false;$('#storageAlert').textContent=s;}
function save(){data.updated=Date.now();if(storageBroken)return false;try{localStorage.setItem(E.KEY,JSON.stringify(data));return true;}catch{storageAlert('端末への保存ができません。現在の答案はこの画面に残っています。「出典・使い方」からバックアップを書き出し、ページを閉じる前に保管してください。');return false;}}
function font(){document.body.classList.toggle('large',data.settings.large);$('#fontButton').setAttribute('aria-pressed',String(data.settings.large));$('#fontButton').textContent=data.settings.large?'文字 標準':'文字 大';}
function go(view,id=''){const h='#'+view+(id?'/'+encodeURIComponent(id):'');if(location.hash===h)render(view,id);else location.hash=h;}
function route(){if(!ready)return;let [view,id='']=location.hash.slice(1).split('/');try{id=decodeURIComponent(id);}catch{id='';}render(view||'home',id);}
function render(view,id=''){
 if(!['home','course','lesson','papers','exam','desk','review','sources'].includes(view))view='home';
 if(view==='lesson'&&!byLesson.has(id)){view='course';id='';}
 if(view==='desk'&&!data.session){view='exam';id='';}
 if(view==='desk'&&data.session.duration&&!data.session.paused&&E.remaining(data.session)===0){finish(true);return;}
 current={view,id};$$('.view').forEach(el=>el.hidden=true);const el=$('#'+view+'View');el.hidden=false;
 const nav=view==='lesson'?'course':view==='desk'?'exam':view;$$('#navigation button').forEach(b=>{if(b.dataset.view===nav)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});
 ({home:renderHome,course:renderCourse,lesson:renderLesson,papers:renderPapers,exam:renderExam,desk:renderDesk,review:renderReview,sources:renderSources}[view])(el,id);
 document.title=(view==='lesson'?byLesson.get(id).title:({home:'今日の学習',course:'科目別講義',papers:'公式過去問',exam:'時間演習',desk:'答案作成',review:'答案・復習',sources:'出典・使い方'}[view]))+'｜論文ノート';
 $('#main').focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});
}
function counts(subject){const ls=lessons.filter(l=>l.subject===subject),ps=papers.filter(p=>p.subject===subject);return{ls,ps,done:ls.filter(l=>data.lessons[l.id]?.confidence==='sure').length,written:ps.filter(p=>data.attempts.some(a=>a.paperId===p.id&&a.answer.trim())).length};}
function subjectCard(s,i){const c=counts(s);return`<button class="subject" data-act="course" data-id="${esc(s)}"><span class="number">${String(i+1).padStart(2,'0')} / ${s==='答案の基本'?'WRITING':'SUBJECT'}</span><h3>${esc(s)}</h3><p>${esc(guide[s].sub)}</p><p>${c.ls.length}講義${c.ps.length?'・過去問15題':''}</p><div class="progress" aria-label="確認済み ${c.done} / ${c.ls.length}"><i style="width:${100*c.done/c.ls.length}%"></i></div><p>説明できた ${c.done} / ${c.ls.length}</p></button>`;}
function dueLessons(){return lessons.filter(l=>data.lessons[l.id]?.due<=Date.now());}
function dueAnswers(){return data.attempts.filter(a=>a.status==='pending'||a.status==='weak'||a.due<=Date.now());}
function nextLesson(){return dueLessons()[0]||lessons.find(l=>!data.lessons[l.id])||lessons.slice().sort((a,b)=>(data.lessons[a.id]?.due||0)-(data.lessons[b.id]?.due||0))[0];}
function nextPaper(){const order=E.SUBJECTS.slice().sort((a,b)=>counts(a).written-counts(b).written);return papers.filter(p=>p.subject===order[0]).sort((a,b)=>b.year-a.year).find(p=>!data.attempts.some(a=>a.paperId===p.id))||papers[0];}
function renderHome(el){const n=nextLesson(),due=dueAnswers(),p=nextPaper(),confirmed=Object.values(data.lessons).filter(x=>x.confidence==='sure').length,distinct=new Set(data.attempts.filter(a=>a.answer.trim()).map(a=>a.paperId));
 el.innerHTML=title('YOUR STUDY DESK','今日の一歩を、答案につなげる。','講義で理解し、過去問で構成し、出題趣旨と照合して書き直す。必須9分野を一つずつ積み上げます。')+
 `<div class="welcome"><div class="panel focus-panel"><span class="eyebrow">NEXT STEP</span><h2>${data.session?'途中の答案から再開':esc(n.title)}</h2><p>${data.session?esc(data.session.title)+'の答案を保存しています。タイマーは一時停止中を除き、ページを閉じても進みます。':esc(n.subject)+' / 約'+n.minutes+'分。読み終えたら、資料を閉じて確認問題に答えましょう。'}</p><div class="actions">${data.session?btn('desk','答案を再開'):btn('lesson','講義を開く',n.id)}${btn('review','復習ノートへ','','quiet')}</div></div><div class="panel"><span class="eyebrow">REVIEW FIRST</span><h2>今日の復習</h2><p class="lead">答案 ${due.length}件・講義 ${dueLessons().length}件</p><p class="small muted">未点検の答案と、復習日を迎えた記録を優先します。日を空けた再現で、理解を確かめます。</p><div class="actions">${due.length?btn('review','最初の答案を点検',due[0].id,'btn secondary'):btn('papers','過去問を選ぶ','','btn secondary')}</div></div></div>`+
 `<div class="metrics"><div class="metric"><strong>${confirmed}<small> / ${lessons.length}</small></strong><span>説明できた講義</span></div><div class="metric"><strong>${distinct.size}<small> / 135</small></strong><span>本文を起案した過去問</span></div><div class="metric"><strong>${data.attempts.filter(a=>a.rewrite.trim()).length}</strong><span>書き直しのある答案</span></div><div class="metric"><strong>${data.attempts.filter(a=>a.status==='retained').length}</strong><span>別日に3回以上復習した答案</span></div></div>`+
 `<div class="two"><div class="panel"><span class="eyebrow">BALANCE YOUR SUBJECTS</span><h2>次の過去問候補</h2><p class="lead">${esc(p.era)}年 ${esc(p.subject)}</p><p class="small muted">起案数の少ない科目から、未演習の問題を提案します。</p><div class="actions">${btn('paper','問題を読む',p.id,'btn secondary')}</div></div><div class="panel"><span class="eyebrow">THIS WEEK</span><h2>週の学習配分</h2><label class="field">週に確保する時間<select data-setting="hours">${[5,10,12,15,20,25].map(n=>`<option value="${n}" ${n===data.settings.hours?'selected':''}>${n}時間</option>`).join('')}</select></label><p id="weeklyPlan" class="small lead">${weeklyText()}</p></div></div>`+
 `<div class="section-heading"><h2>必須科目を一巡する</h2>${btn('course','講義一覧','','link-button')}</div><div class="subject-grid">${E.SUBJECTS.map(subjectCard).join('')}</div>`+
 `<div class="section-heading"><h2>学習の進め方</h2><p class="small">期間より、できることを目標に</p></div><div class="panel">${[
 ['土台を作る','「答案の基本」6講義と各科目の入口を学ぶ。条文を開き、要件と効果を資料なしで説明する。'],
 ['全科目で構成する','各科目の直近3年分から20分の構成練習。設問の結論・規範・有利不利の事実を出題趣旨と照合する。'],
 ['全科目で全文を書く','基本科目70分・実務90分を目安に起案。途中でも保存し、原因を一つに絞って書き直す。'],
 ['古い年度まで広げる','同じ論点の別事案で判断を再現する。改正法の基準日と問題文の指定、実務問題の図表を確認する。'],
 ['本番の科目群で仕上げる','公法140分・民事210分・刑事140分・実務180分。全科目の完答と配分を練習し、復習ノートの重大な不足を潰す。']
 ].map(([h,p],i)=>`<div class="schedule-row"><strong>${i+1}</strong><div><h3>${h}</h3><p>${p}</p></div></div>`).join('')}</div>`;
}
function weeklyText(){const h=data.settings.hours;return`基礎 ${Math.round(h/3*10)/10}時間・構成 ${Math.round(h/4*10)/10}時間・起案 ${Math.round(h/4*10)/10}時間・復習 ${Math.round(h/6*10)/10}時間を出発点に。起案の不足に合わせて配分を変えます。`;}
function renderCourse(el,id){const subject=guide[id]?id:'';el.innerHTML=title('CURRICULUM',subject||'科目別講義',subject?guide[subject].sub:'答案の基本6講義と、必須9分野80講義。各講義に条文・判断の順序・短い例・確認問題・過去問への導線を用意しました。')+
 (subject?`<div class="actions">${btn('course','全科目へ','','quiet')}${subject!=='答案の基本'?btn('subject-papers','この科目の過去問',subject,'quiet'):''}</div><div class="notice info">${esc(subject)}の学習目標：${esc(guide[subject].checks.join('／'))}</div><div class="list">${lessons.filter(l=>l.subject===subject).map((l,i)=>lessonRow(l,i)).join('')}</div>`:`<div class="subject-grid">${['答案の基本',...E.SUBJECTS].map(subjectCard).join('')}</div>`);}
function lessonRow(l,i){const r=data.lessons[l.id];return`<div class="list-item"><div><span class="number">LESSON ${String(i+1).padStart(2,'0')} / 約${l.minutes}分</span><h3>${esc(l.title)}</h3><p>${r?`${r.confidence==='sure'?'説明できた':'もう一度'}・次回 ${date(r.due)}`:'未学習'} ${r?.due<=Date.now()?'<span class="badge orange">復習日</span>':''}</p></div>${btn('lesson','学ぶ',l.id,'quiet')}</div>`;}
function renderLesson(el,id){const l=byLesson.get(id),related=papers.filter(p=>p.subject===l.subject).map(p=>({p,n:l.keywords.filter(k=>(p.text+p.purpose).includes(k)).length})).filter(x=>x.n>0).sort((a,b)=>b.n-a.n||b.p.year-a.p.year).slice(0,4),all=lessons.filter(x=>x.subject===l.subject),index=all.findIndex(x=>x.id===id);
 el.innerHTML=title(l.subject,l.title,`講義 ${index+1} / ${all.length}・約${l.minutes}分`)+`<div class="lesson-layout"><article class="panel reading"><h2>押さえる考え方</h2><p class="rule">${esc(l.rule)}</p><h2>答案で考える順序</h2><ol>${l.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol><div class="callout"><strong>ここで崩れやすい</strong><p>${esc(l.pitfall)}</p></div><h2>短い答案例</h2><p class="small muted">教材用の架空事例・独自の解説です。公式過去問の模範答案ではありません。</p><p>${esc(l.example)}</p><h2>条文を確かめる</h2>${l.sources.length?l.sources.map(s=>`<details class="recall"><summary>${esc(s.name)} ${s.articles.map(n=>n.replace('_','の')+'条').join('・')}</summary>${s.articles.map(n=>{const a=articles[s.lawId+':'+n];return a?`<h3>${esc(a.article)}</h3><div class="paper-text small">${esc(a.text)}</div>`:'';}).join('')}<p>${link(s.url,'e-Govで法令を確認')}</p></details>`).join(''):`<p>試験方式は「出典・使い方」の令和8年公式資料を確認してください。</p>`}<p class="small muted">条文は取得時点の参照用です。過去問は出題時の法令・問題文の指定を確認し、現行法と区別してください。</p><h2>資料を閉じて説明する</h2>${l.recall.map(q=>`<p><strong>${esc(q.question)}</strong></p><details class="recall"><summary>自分で答えてから、確認の答えを見る</summary><p>${esc(q.answer)}</p></details>`).join('')}<label>自分の言葉で要点を残す<textarea class="note" data-note="${id}" maxlength="20000" placeholder="要件／判断の理由／迷った点">${esc(data.notes[id]||'')}</textarea></label><div class="actions">${btn('learn-sure','説明できた',id)}${btn('learn-again','もう一度学ぶ',id,'btn secondary')}</div><p class="small muted" id="lessonStatus">${data.lessons[id]?`記録済み・次回 ${date(data.lessons[id].due)}`:'理解度を記録すると、復習日に今日の学習へ表示します。'}</p><div class="actions">${index>0?btn('lesson','前の講義',all[index-1].id,'quiet'):''}${index+1<all.length?btn('lesson','次の講義',all[index+1].id,'quiet'):btn('course','科目一覧へ','','quiet')}</div></article><aside class="lesson-side"><div class="panel"><span class="eyebrow">USE IT IN AN ANSWER</span><h2>関連する公式過去問</h2><p class="small muted">教材の語句を含む同科目の問題。公式の論点分類ではありません。</p>${related.length?related.map(({p})=>`<div class="schedule-row"><div><h3>${esc(p.era)}年 ${esc(p.subject)}</h3>${btn('paper','問題を読む',p.id,'link-button')}</div></div>`).join(''):'<p class="small">まず各科目の問題で、今回の書き方を使いましょう。</p>'}<div class="actions">${btn('course','この科目の講義',l.subject,'quiet')}</div></div></aside></div>`;
}
function paperTitle(p){return`${p.era}年（${p.year}）${p.subject}`;}
function pdfLinks(p,purpose=false){return`<div class="row small">${link(p.pdf+'#page='+(purpose?p.purposePage:p.sourcePage),purpose?'公式出題趣旨 PDF':'公式原本 PDF（問題のページ）')}${!purpose&&p.questionPdf&&p.questionPdf!==p.pdf?link(p.questionPdf,'公式問題冊子'):''}</div>`;}
function paperNotice(p){return`<div class="notice ${p.layoutNote?'':'info'}">${p.layoutNote?'図表・別紙等を含む問題です。起案前に必ず原本PDFを開き、図の位置関係・表・記録の様式を確認してください。':'本文は公式PDFから抽出しています。レイアウトや文字の疑義は原本PDFで確認してください。'} 問題文の基準日・法改正の指定を優先します。</div>`;}
function selectOptions(values,selected,first){return`<option value="">${esc(first)}</option>`+values.map(v=>`<option value="${esc(v)}" ${String(v)===String(selected)?'selected':''}>${esc(v)}</option>`).join('');}
function renderPapers(el,id){const p=byPaper.get(id);if(p){el.innerHTML=title('OFFICIAL PAST PAPER',paperTitle(p),'法務省の実際の論文式試験問題。答案構成から全文起案まで、この問題で練習します。')+`<div class="actions">${btn('papers','一覧へ','','quiet')}${btn('bookmark',data.bookmarks[id]?'★ 保存済み':'☆ 後で解く',id,'quiet')}${btn('start-outline','20分で答案構成',id)}${btn('start-essay',`${p.minutes}分で起案`,id)}${btn('start-free','時間制限なし',id,'btn secondary')}</div>${paperNotice(p)}<div class="panel reading">${pdfLinks(p)}<div class="paper-text">${esc(p.text)}</div></div><div class="panel reading" style="margin-top:20px"><h2>この問題の学習メモ</h2><label>気になった条文・論点<textarea class="note" data-note="${id}" maxlength="20000" placeholder="自分用のメモ。検索の対象になります。">${esc(data.notes[id]||'')}</textarea></label><details class="recall"><summary>公式出題趣旨を読む（起案前は閉じたまま推奨）</summary><p class="small muted">出題趣旨は検討の方向を示す資料であり、完成答案ではありません。</p>${pdfLinks(p,true)}<div class="paper-text">${esc(p.purpose)}</div></details><h2>関連講義</h2><div class="actions">${E.topicMatches(p,lessons).map(l=>btn('lesson',l.title,l.id,'quiet')).join('')}</div></div>`;return;}
 el.innerHTML=title('135 OFFICIAL PAPERS','公式過去問','平成23年〜令和7年の15年分。必須9分野・全135題を、問題本文と公式出題趣旨付きで収録しています。')+`<div class="filters"><label class="field">科目<select data-paper-filter="subject">${selectOptions(E.SUBJECTS,paperFilter.subject,'全科目')}</select></label><label class="field">年度<select data-paper-filter="year">${selectOptions(years,paperFilter.year,'全年度')}</select></label><label class="field">演習状況<select data-paper-filter="status">${[['','すべて'],['new','未演習'],['written','演習済み'],['saved','後で解く']].map(([v,t])=>`<option value="${v}" ${paperFilter.status===v?'selected':''}>${t}</option>`).join('')}</select></label><label class="field wide">本文・趣旨・メモを検索<input type="search" data-paper-filter="query" value="${esc(paperFilter.query)}" placeholder="例：原告適格、共謀、利益相反"></label></div><p id="paperCount" class="small muted" aria-live="polite"></p><div id="paperResults" style="margin-top:12px"></div>`;filterPapers();
}
function filterPapers(){const f=paperFilter,q=f.query.trim().toLocaleLowerCase(),seen=new Set(data.attempts.map(a=>a.paperId)),ps=papers.filter(p=>(!f.subject||p.subject===f.subject)&&(!f.year||p.year===Number(f.year))&&(!f.status||(f.status==='new'?!seen.has(p.id):f.status==='written'?seen.has(p.id):data.bookmarks[p.id]))&&(!q||(p.text+p.purpose+(data.notes[p.id]||'')+paperTitle(p)).toLocaleLowerCase().includes(q))).sort((a,b)=>b.year-a.year||E.SUBJECTS.indexOf(a.subject)-E.SUBJECTS.indexOf(b.subject));
 $('#paperCount').textContent=`${ps.length}題 / 全135題`;
 $('#paperResults').innerHTML=ps.length?`<div class="list">${ps.map(p=>`<div class="list-item"><div><span class="number">${p.year} / ${esc(p.subject)}</span><h3>${esc(p.era)}年 ${esc(p.subject)} ${data.bookmarks[p.id]?'★':''}</h3><p>${seen.has(p.id)?'演習済み':'未演習'}${p.layoutNote?'・原本の図表確認あり':''}・${p.minutes}分は単科目練習の目安</p></div>${btn('paper','問題を開く',p.id,'quiet')}</div>`).join('')}</div>`:empty('条件に合う問題がありません','検索語・年度・演習状況の条件を変更してください。',btn('clear-filters','条件を解除','','btn secondary'));
}
function renderExam(el){el.innerHTML=title('TIMED WRITING','時間を測って起案する','一題の構成練習から、本番と同じ科目群の時間配分まで。問題選択後にタイマーが始まります。')+
 (data.session?`<div class="notice info"><strong>途中の演習があります：${esc(data.session.title)}</strong><p>原稿を保存しています。新しい演習の前に、この答案を提出して残してください。</p><div class="actions">${btn('desk','途中から再開')}</div></div>`:'')+
 `<div class="three"><div class="panel"><span class="eyebrow">01 / OUTLINE</span><h2>20分の答案構成</h2><p class="lead small">設問の結論、条文・規範、重要な事実、反対事情を箇条書きにする練習。</p><div class="actions">${btn('papers','過去問を選ぶ','','btn secondary')}</div></div><div class="panel"><span class="eyebrow">02 / SINGLE SUBJECT</span><h2>一科目を最後まで</h2><p class="lead small">基本科目70分・実務90分の学習上の配分で起案。時間制限なしでも練習できます。</p><div class="actions">${btn('papers','過去問を選ぶ','','btn secondary')}</div></div><div class="panel"><span class="eyebrow">03 / EXAM BLOCK</span><h2>科目群の演習</h2><p class="lead small">一つのタイマーで同じ年度の2〜3科目を書く。残り時間を見て、科目間の配分を練習します。</p></div></div>`+
 `<div class="section-heading"><h2>科目群と年度を選ぶ</h2></div><div class="panel"><label class="field">演習する年度<select id="examYear">${years.map(y=>`<option value="${y}">${y}年（${y>2018?'令和'+(y-2018):'平成'+(y-1988)}年）</option>`).join('')}</select></label><div class="two" style="margin-top:22px">${E.BLOCKS.map(b=>`<div class="panel"><span class="eyebrow">${b.minutes} MINUTES</span><h2>${b.name}</h2><p class="lead small">${b.subjects.join('・')}</p><div class="actions">${btn('start-block',b.minutes+'分の演習を開始',b.id)}</div></div>`).join('')}</div></div>`+
 `<div class="notice info">令和8年の公式案内に基づく時間です。各科目の答案は4頁・1頁23行・1行最大30文字。このサイトの行数・頁数は練習の目安です。実際のCBTの入力・表示は公式案内で確認してください。</div><p class="small muted">タイマーはブラウザを閉じても進み、時間切れの際は入力済みの答案を保存して復習へ移します。一時停止は可能ですが、記録に回数が残ります。出題趣旨は提出後に表示します。</p>`;}
function start(ids,mode,minutes,name){if(data.session){toast('途中の答案があります。先に提出して保存してください。');go('desk');return;}if(!ids.length||ids.some(id=>!byPaper.has(id))){toast('問題を選択してください。');return;}data.session=E.newSession(ids,mode,minutes,name);save();go('desk');}
function renderDesk(el){const s=data.session,p=byPaper.get(s.paperIds[s.index]),d=s.drafts[p.id],checks=guide[p.subject].checks;
 el.innerHTML=`<div class="desk-head"><div><span class="eyebrow">${s.mode==='exam'?'EXAM BLOCK':s.mode==='outline'?'OUTLINE PRACTICE':'ESSAY PRACTICE'}</span><h1>${esc(p.era)}年 ${esc(p.subject)}</h1><p class="small muted">${esc(s.title)} ${s.paperIds.length>1?'／科目 '+(s.index+1)+' / '+s.paperIds.length:''}</p></div><div class="row"><div><div id="clock" class="clock" role="timer" aria-label="残り時間">${s.duration?clock(E.remaining(s)):'制限なし'}</div><span class="small muted" id="clockState">${s.paused?'一時停止中':s.duration?'残り時間':'自由起案'}${s.pauses?'・中断 '+s.pauses+'回':''}</span></div>${s.duration?btn('pause',s.paused?'計測を再開':'一時停止','','quiet'):''}${btn('finish',s.paperIds.length>1?'全科目を提出':'提出して復習へ')}</div></div>`+
 (s.paperIds.length>1?`<div class="tabs" aria-label="答案の科目">${s.paperIds.map((id,i)=>`<button class="${i===s.index?'active':''}" data-act="switch-paper" data-id="${i}" aria-pressed="${i===s.index}">${esc(byPaper.get(id).subject)} ${s.drafts[id].answer.trim()?'・入力あり':''}</button>`).join('')}</div>`:'')+
 `${paperNotice(p)}<div class="desk-layout"><div class="panel desk-pane"><div class="pane-head"><h2>公式問題</h2>${link(p.pdf+'#page='+p.sourcePage,'原本PDF')}</div><div class="pane-body"><div class="paper-text">${esc(p.text)}</div></div></div><div class="stack"><div class="panel desk-pane"><div class="editor-tabs"><button data-act="stage" data-id="outline" class="${s.stage==='outline'?'active':''}" aria-pressed="${s.stage==='outline'}">答案構成</button><button data-act="stage" data-id="answer" class="${s.stage==='answer'?'active':''}" aria-pressed="${s.stage==='answer'}">答案本文</button></div><label class="sr-only" for="draftEditor">${s.stage==='outline'?'答案構成':'答案本文'}</label><textarea id="draftEditor" class="writing-area ${s.stage==='outline'?'outline':''}" data-draft="${s.stage}" maxlength="50000" spellcheck="false" placeholder="${s.stage==='outline'?'設問ごとの結論 → 根拠条文・規範 → 重要な事実 → 反対事情と応答を、先に整理します。':'見出しを置き、規範・具体的な事実・評価・結論のつながりを書きます。'}">${esc(d[s.stage])}</textarea><div id="editorMeta" class="editor-meta"></div><div class="print-only">${esc(d[s.stage])}</div></div><div class="panel"><h2>構成の点検</h2><p class="small muted">科目共通の確認です。この問題の出題趣旨は提出後に確認します。</p><div class="hint-steps">${checks.map((c,i)=>`<label><input type="checkbox" data-draft-check="${i}" ${d.checks[i]?'checked':''}>${esc(c)}</label>`).join('')}</div><p class="small muted">端末に自動保存します。科目やタブを切り替えても入力内容は残ります。</p></div></div></div>`;editorMeta();tick();}
function editorMeta(){const el=$('#editorMeta');if(!el||!data.session)return;const s=data.session,m=E.measure(s.drafts[s.paperIds[s.index]][s.stage]);el.classList.toggle('over',s.stage==='answer'&&m.over);el.innerHTML=`<span>${m.characters.toLocaleString()}文字${s.stage==='answer'?` / ${m.rows}行・約${m.pages}頁 ${m.over?'（4頁の目安を超過）':''}`:'（構成用）'}</span><span>${storageBroken?'端末保存不可・書出しが必要':'端末に保存済み'}</span>`;}
function tick(){if(!ready||!data.session)return;const s=data.session;if(s.duration&&!s.paused&&E.remaining(s)===0){finish(true);return;}const c=$('#clock');if(c&&current.view==='desk'){c.textContent=s.duration?clock(E.remaining(s)):'制限なし';c.classList.toggle('low',!!s.duration&&E.remaining(s)<300000);}}
function finish(automatic=false){if(!data.session)return;if(!automatic&&!confirm('この演習を提出して保存します。科目群の場合は、全科目の答案をまとめて提出します。よろしいですか？'))return;const attempts=E.completeSession(data,Date.now(),automatic);save();go('review',attempts[0].id);toast(automatic?'時間になりました。入力済みの答案を保存しました。':'答案を保存しました。公式出題趣旨と照合しましょう。');}
const statusLabel=a=>({pending:'未点検',weak:'もう一度',reviewed:'点検・復習済み',retained:'別日に3回以上復習'})[a.status];
function renderReview(el,id){const a=data.attempts.find(x=>x.id===id);if(a){renderAnswer(el,a);return;}
 const due=dueLessons();el.innerHTML=title('REVIEW NOTEBOOK','答案・復習ノート','元の答案を残し、点検の根拠と書き直しを保存します。自己点検は本試験の点数や合否の判定ではありません。')+`<div class="actions">${btn('backup','全データを書き出す','','quiet')}</div>`+
 (due.length?`<div class="section-heading"><h2>復習日を迎えた講義</h2><p class="small">${due.length}講義</p></div><div class="list">${due.map((l,i)=>lessonRow(l,i)).join('')}</div>`:'')+
 `<div class="section-heading"><h2>保存した答案</h2><p class="small">${data.attempts.length}件</p></div><div class="filters"><label class="field">科目<select data-review-filter="subject">${selectOptions(E.SUBJECTS,reviewFilter.subject,'全科目')}</select></label><label class="field">状態<select data-review-filter="status">${[['','すべて'],['due','今日の復習'],['pending','未点検'],['weak','もう一度'],['rewrite','書き直しあり'],['retained','別日に3回以上']].map(([v,t])=>`<option value="${v}" ${reviewFilter.status===v?'selected':''}>${t}</option>`).join('')}</select></label></div><div id="reviewResults"></div>`;filterReviews();}
function filterReviews(){const f=reviewFilter,as=data.attempts.filter(a=>(!f.subject||byPaper.get(a.paperId).subject===f.subject)&&(!f.status||(f.status==='due'?(a.status==='pending'||a.status==='weak'||a.due<=Date.now()):f.status==='rewrite'?a.rewrite.trim():a.status===f.status)));
 $('#reviewResults').innerHTML=as.length?`<div class="list">${as.map(a=>{const p=byPaper.get(a.paperId),r=E.rubricResult(a);return`<div class="list-item"><div><span class="number">${date(a.created)} / ${a.mode==='outline'?'構成':a.mode==='exam'?'科目群':'起案'}</span><h3>${esc(p.era)}年 ${esc(p.subject)}</h3><p><span class="badge ${a.status==='weak'?'orange':a.status==='retained'?'green':''}">${statusLabel(a)}</span> 点検 ${r.filled}/6・本文 ${E.measure(a.answer).characters}文字${a.rewrite.trim()?'・書き直しあり':''}</p><p>次回 ${date(a.due)}${a.pauses?'・中断 '+a.pauses+'回':''}${a.automatic?'・時間切れで提出':''}</p></div>${btn('review','点検する',a.id,'quiet')}</div>`;}).join('')}</div>`:empty('表示する答案がありません',data.attempts.length?'絞り込み条件を変更してください。':'過去問の構成や答案を提出すると、ここに保存されます。',btn('papers','過去問を選ぶ','','btn secondary'));
}
function renderAnswer(el,a){const p=byPaper.get(a.paperId),r=E.rubricResult(a),related=E.topicMatches(p,lessons);
 el.innerHTML=title('ANSWER REVIEW',`${p.era}年 ${p.subject}の答案`,`${date(a.created)}・${a.mode==='outline'?'構成練習':a.mode==='exam'?'科目群演習':'起案'}・${Math.round(a.elapsed/60000)}分${a.mode==='exam'?'（科目群全体の経過時間）':''}${a.pauses?'・中断 '+a.pauses+'回':''}`)+
 `<div class="actions">${btn('review','答案一覧へ','','quiet')}${btn('download-answer','この答案を書き出す',a.id,'quiet')}${btn('print','印刷する','','quiet')}${btn('paper','問題をもう一度解く',p.id,'quiet')}</div>`+
 (a.automatic?'<div class="notice info">時間切れで保存された答案です。空欄・未完成の部分も記録に残しています。</div>':'')+
 `<div class="notice info">公式出題趣旨は完成答案ではありません。まず設問の要求を確認し、6項目について自分の答案の対応箇所や不足を記録してください。点検件数を本試験の点数・合格率には換算しません。</div>`+
 `<div class="desk-layout"><div class="panel desk-pane"><div class="pane-head"><h2>元の答案</h2><span class="badge">提出時の記録</span></div><div class="pane-body"><details ${a.answer.trim()?'':'open'}><summary>答案構成</summary><div class="review-answer">${esc(a.outline||'構成の入力はありません。')}</div></details><h3 style="margin:20px 0 12px">答案本文</h3><div class="review-answer">${esc(a.answer||'答案本文の入力はありません。')}</div><p class="small muted">${E.measure(a.answer).characters}文字・約${E.measure(a.answer).pages}頁</p></div></div><div class="panel desk-pane"><div class="pane-head"><h2>公式出題趣旨</h2>${link(p.pdf+'#page='+p.purposePage,'原本PDF')}</div><div class="pane-body"><div class="paper-text">${esc(p.purpose)}</div><details class="recall"><summary>問題文を再確認</summary>${pdfLinks(p)}<div class="paper-text">${esc(p.text)}</div></details></div></div></div>`+
 `<div class="section-heading"><h2>01 / 出題趣旨の要求を書き出す</h2></div><div class="panel"><label>この問題で求められた主要な検討<textarea class="note" data-answer-field="purposeNotes" data-answer-id="${a.id}" maxlength="50000" placeholder="設問1：求める結論、主要争点、評価すべき事実…">${esc(a.purposeNotes)}</textarea></label></div>`+
 `<div class="section-heading"><h2>02 / 答案を6項目で点検する</h2><p class="small" id="rubricSummary">${r.filled}/6項目を点検</p></div><div class="panel">${E.RUBRIC.map(c=>`<div class="rubric-row"><h3>${c.title}</h3><p>${c.detail}</p><div class="rating" role="group" aria-label="${c.title}">${[[0,'不足'],[1,'一部できた'],[2,'根拠を示してできた']].map(([n,t])=>`<label><input type="radio" name="rating-${c.id}" value="${n}" data-rating="${c.id}" data-answer-id="${a.id}" ${a.ratings[c.id]===n?'checked':''}>${t}</label>`).join('')}</div><label class="small">答案の対応箇所・不足の根拠<textarea data-evidence="${c.id}" data-answer-id="${a.id}" maxlength="12000" placeholder="該当する一文を引用するか、落とした検討を具体的に記録">${esc(a.evidence[c.id]||'')}</textarea></label></div>`).join('')}</div>`+
 `<div class="section-heading"><h2>03 / 一番大きな不足を直す</h2></div><div class="panel"><label>次の答案で変えること<textarea class="note" data-answer-field="improvement" data-answer-id="${a.id}" maxlength="50000" placeholder="例：原告適格で、根拠法だけでなく関係法令が保護する利益を具体的に読む。">${esc(a.improvement)}</textarea></label><h3 style="margin-top:22px">書き直し答案</h3><p class="small muted">元の答案は上書きしません。不足した一段落だけの修正から始めても構いません。</p><label class="sr-only" for="rewriteAnswer">書き直し答案</label><textarea id="rewriteAnswer" class="note" style="min-height:310px;line-height:1.9" data-answer-field="rewrite" data-answer-id="${a.id}" maxlength="50000" placeholder="重要な不足を直し、規範と事実評価を自分の言葉で書き直す">${esc(a.rewrite)}</textarea><p class="small muted" id="rewriteCount">書き直し ${E.measure(a.rewrite).characters}文字</p><div class="print-only">${esc(a.rewrite)}</div></div>`+
 `<div class="section-heading"><h2>04 / 次の復習を決める</h2></div><div class="panel"><p>資料を閉じ、結論までの構成と主要な当てはめを口頭かメモで再現してください。できなければ翌日へ。できた答案は、別の日の復習ごとに間隔を広げます。</p><div class="actions">${btn('review-sure','点検・再現できた',a.id)}${btn('review-again','翌日にもう一度',a.id,'btn secondary')}</div><p class="small muted" id="reviewStatus">${statusLabel(a)}・次回 ${date(a.due)}・別日での復習 ${a.round}回</p><p class="small muted">「点検・再現できた」は、6項目の点検と各根拠、出題趣旨の要点、次に変えることを記録してから押せます。</p></div>`+
 `<div class="section-heading"><h2>関連講義に戻る</h2></div><div class="actions">${related.map(l=>btn('lesson',l.title,l.id,'quiet')).join('')}${btn('course',p.subject+'の全講義',p.subject,'quiet')}</div><div class="actions no-print">${btn('delete-answer','この答案を削除',a.id,'btn danger')}</div>`;
}
function renderSources(el){el.innerHTML=title('GUIDE & SOURCES','出典・使い方','収録範囲、試験方式、答案の扱いを確認できます。公式の問題・出題趣旨と、このサイトの教材を区別して利用してください。')+
 `<div class="panel"><h2>答案と進捗のバックアップ</h2><p class="lead">答案はこの端末・このブラウザの保存領域に残ります。ログインやクラウド同期はありません。ブラウザのデータ消去や端末変更に備えて、定期的に書き出してください。</p><div class="actions">${btn('backup','バックアップを書き出す')}${btn('import','バックアップを読み込む','','btn secondary')}${unreadableBackup?btn('raw-backup','読み込めなかった元データを救出','','quiet'):''}</div><p class="small muted">読み込みは、現在の答案・講義進捗・メモを置き換えます。内容と形式を検証した後、件数を確認してから反映します。書き出したファイルは他の端末でも読み込めます。</p>${storageBroken?'<p class="notice danger">現在は端末への保存を停止しています。バックアップを保管してから、他のタブを閉じ、保存領域やブラウザの設定を確認してページを開き直してください。</p>':''}</div>`+
 `<div class="section-heading"><h2>学習範囲と使い方</h2></div><div class="panel reading"><h3>1. 必須9分野・135題</h3><p>平成23年（2011年）〜令和7年（2025年）の予備試験論文式試験を収録。法律基本7科目と、法律実務基礎の民事・刑事が対象です。サイトでは選択科目を扱いません。実際の予備試験には選択科目もあるため、このサイトの範囲と本試験全体の科目は区別してください。</p><h3>2. 講義 → 構成 → 起案 → 照合 → 書き直し</h3><p>86講義は重要事項を整理する学習用ノートです。短い事例・答案例・確認問題はこのサイトの独自教材で、公式の模範答案ではありません。演習用の長文問題135題は全て公式過去問です。関連講義の候補は本文・趣旨に含まれる語句から提示しています。</p><h3>3. 自分で根拠を記録する</h3><p>公式出題趣旨と答案を並べ、問いへの応答・争点・規範・事実評価・反対事情・完答を点検します。専門家による添削やAIによる内容採点は実装していません。確認できた項目数は試験得点でも合格率でもありません。合格に必要な到達度は、実際の起案の内容と外部の講評等も使って判断してください。</p><h3>4. 復習日</h3><p>「もう一度」は翌日へ。「説明できた」「点検・再現できた」は別日の記録ごとに3日・7日・14日・30日へ間隔を広げます。同じ日に何度押しても復習段階は進みません。原答案と書き直しは別々に保存します。</p></div>`+
 `<div class="section-heading"><h2>令和8年の公式方式</h2></div><div class="panel"><div class="table-wrap"><table><thead><tr><th>科目群</th><th>対象科目</th><th>試験時間</th></tr></thead><tbody>${E.BLOCKS.map(b=>`<tr><td>${b.name}</td><td>${b.subjects.join('・')}</td><td>${b.minutes}分</td></tr>`).join('')}</tbody></table></div><p class="lead small">基本科目70分、実務各90分は等分した学習上の目安です。各科目に独立した本番の締切があるわけではありません。令和8年の公式答案形式は1科目4頁、1頁23行、1行最大30文字です。</p><p class="small muted">本サイトの頁数は30文字ごとの折返しと改行で算出する目安です。本番CBTの文字幅・編集・表示を完全には再現しません。令和8年の問題は原則として同年1月1日現在の施行法令に基づき、例外・出題範囲は公式案内を確認してください。</p><ul class="source-list"><li>${link('https://www.moj.go.jp/content/001451383.pdf','法務省：令和8年論文式試験の実施方針・採点等')}</li><li>${link('https://www.moj.go.jp/content/001451385.pdf','法務省：試験時間（令和8年案内掲載）')}</li><li>${link('https://www.moj.go.jp/content/001451386.pdf','法務省：出題に係る法令等')}</li><li>${link('https://www.moj.go.jp/content/001451387.pdf','法務省：民事系科目の出題範囲')}</li><li>${link('https://www.moj.go.jp/content/001451388.pdf','法務省：刑事系科目の出題範囲')}</li></ul></div>`+
 `<div class="section-heading"><h2>過去問・出題趣旨の原本</h2><p class="small">収録確認 ${esc(sources.checked)}</p></div><div class="panel"><p>出典：法務省「司法試験予備試験 論文式試験問題・出題趣旨」。権利は原資料の権利者に帰属します。表示用に改行や空白を整え、必須科目の本文を抽出しています。図表・別紙や文字の疑義は各問題の原本PDFを確認してください。</p><div class="table-wrap" style="margin-top:18px"><table><thead><tr><th>年度</th><th>収録</th><th>法務省原本</th></tr></thead><tbody>${sources.documents.slice().sort((a,b)=>b.year-a.year).map(d=>`<tr><td>${d.year}年</td><td>9分野・9題</td><td>${link(d.url,'問題・出題趣旨')}</td></tr>`).join('')}</tbody></table></div><details class="recall"><summary>取得経路・照合情報</summary><p>公開された原本PDFのミラーを取得に使用しています。サイト独自の解答や市販教材の解説は過去問本文・出題趣旨に混入させていません。</p><ul class="source-list"><li>${link(sources.questionMirror,'問題PDFの公開リポジトリ')}</li><li>${link(sources.purposeMirror,'出題趣旨PDFの公開ミラー')}</li><li>${link('assets/ronbun/sources.json','年度・原本URL・PDFのSHA-256・抽出文字数')}</li></ul></details></div>`+
 `<div class="section-heading"><h2>条文と改正法</h2></div><div class="panel reading"><p>条文はe-Gov法令APIから取得した参照用データです。取得日：2026年9月10日。過去問の出題時に適用された条文と、現在の条文が異なる場合があります。施行日・経過措置・問題文の指定を確認し、古い出題趣旨をそのまま現行法の結論にしないでください。</p><ul class="source-list">${[...new Map(lessons.flatMap(l=>l.sources).map(s=>[s.lawId,s])).values()].map(s=>`<li>${link(s.url,s.name)}</li>`).join('')}</ul><p>このサイトは法務省・e-Gov等が提供又は監修するサービスではありません。答案とメモの外部送信、アクセス解析、広告はこの学習ページに設置していません。外部の公式資料はリンクを開いたときにその提供元へ接続します。</p></div>`;
}
function download(name,text,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type:type+';charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function backup(){download('ronbun-notebook-'+new Date().toISOString().slice(0,10)+'.json',JSON.stringify({app:'ronbun-notebook',exported:new Date().toISOString(),data},null,2));toast('答案・進捗・メモを書き出しました。');}
function answerText(a){const p=byPaper.get(a.paperId);return`${paperTitle(p)}\n${date(a.created)}\n\n【答案構成】\n${a.outline}\n\n【提出時の答案】\n${a.answer}\n\n【出題趣旨の要求メモ】\n${a.purposeNotes}\n\n【自己点検（試験得点ではありません）】\n${E.RUBRIC.map(r=>`${r.title}：${({0:'不足',1:'一部できた',2:'根拠を示してできた'})[a.ratings[r.id]]||'未点検'}\n${a.evidence[r.id]||''}`).join('\n\n')}\n\n【次に変えること】\n${a.improvement}\n\n【書き直し】\n${a.rewrite}\n\n出典：${p.pdf}\n`;}
document.addEventListener('click',event=>{const nav=event.target.closest('[data-view]');if(nav&&ready){go(nav.dataset.view);return;}const b=event.target.closest('[data-act]');if(!b||!ready)return;const {act,id}=b.dataset;
 if(['home','course','lesson','papers','exam','desk','review','sources'].includes(act)){go(act,id);return;}
 if(act==='paper'){go('papers',id);return;}
 if(act==='subject-papers'){paperFilter={subject:id,year:'',status:'',query:''};go('papers');return;}
 if(act==='bookmark'){data.bookmarks[id]=!data.bookmarks[id];save();b.textContent=data.bookmarks[id]?'★ 保存済み':'☆ 後で解く';return;}
 if(act==='clear-filters'){paperFilter={subject:'',year:'',status:'',query:''};render('papers');return;}
 if(act==='learn-sure'||act==='learn-again'){const r=E.recordLesson(data,id,act==='learn-sure'?'sure':'again');save();$('#lessonStatus').textContent=`${act==='learn-sure'?'説明できた':'もう一度'}・次回 ${date(r.due)}`;toast('講義の理解度を記録しました。');return;}
 if(['start-outline','start-essay','start-free'].includes(act)){const p=byPaper.get(id);if(!p)return;start([id],act==='start-outline'?'outline':'essay',act==='start-outline'?20:act==='start-free'?0:p.minutes,paperTitle(p));return;}
 if(act==='start-block'){const b=E.BLOCKS.find(x=>x.id===id),y=Number($('#examYear').value);if(!b)return;const ids=b.subjects.map(s=>papers.find(p=>p.year===y&&p.subject===s)?.id);start(ids,'exam',b.minutes,y+'年 '+b.name);return;}
 if(act==='pause'&&data.session){data.session.paused?E.resume(data.session):E.pause(data.session);save();render('desk');return;}
 if(act==='switch-paper'&&data.session){data.session.index=Math.max(0,Math.min(data.session.paperIds.length-1,Number(id)||0));save();render('desk');return;}
 if(act==='stage'&&data.session&&['outline','answer'].includes(id)){data.session.stage=id;save();render('desk');return;}
 if(act==='finish'){finish();return;}
 if(act==='backup'){backup();return;}
 if(act==='raw-backup'){download('ronbun-recovery-original.txt',unreadableBackup,'text/plain');return;}
 if(act==='import'){$('#backupInput').click();return;}
 if(act==='download-answer'){const a=data.attempts.find(x=>x.id===id);if(a)download('ronbun-'+a.paperId+'-'+a.created+'.txt',answerText(a),'text/plain');return;}
 if(act==='print'){const a=data.attempts.find(x=>x.id===current.id);if(a){let print=$('#answerPrint');if(!print){print=document.createElement('pre');print.id='answerPrint';document.body.append(print);}print.textContent=answerText(a);document.body.classList.add('printing-answer');}window.print();return;}
 if(act==='review-sure'||act==='review-again'){const a=data.attempts.find(x=>x.id===id);if(!a)return;if(act==='review-sure'&&(E.rubricResult(a).filled!==6||E.RUBRIC.some(r=>!a.evidence[r.id]?.trim())||!a.purposeNotes.trim()||!a.improvement.trim())){toast('6項目の点検と各根拠、出題趣旨の要点、次に変えることを記録してください。');return;}E.reviewAttempt(a,act==='review-sure'?'sure':'again');save();$('#reviewStatus').textContent=`${statusLabel(a)}・次回 ${date(a.due)}・別日での復習 ${a.round}回`;toast('次の復習日を記録しました。');return;}
 if(act==='delete-answer'){const a=data.attempts.find(x=>x.id===id);if(a&&confirm('この答案・点検メモ・書き直しを削除します。元に戻せません。必要な場合は先に書き出してください。削除しますか？')){data.attempts=data.attempts.filter(x=>x.id!==id);save();go('review');toast('答案を削除しました。');}return;}
});
document.addEventListener('input',event=>{if(!ready)return;const el=event.target;
 if(el.dataset.note){data.notes[el.dataset.note]=el.value;save();return;}
 if(el.dataset.draft&&data.session){const s=data.session;s.drafts[s.paperIds[s.index]][el.dataset.draft]=el.value;save();editorMeta();return;}
 if(el.dataset.answerField||el.dataset.evidence){const a=data.attempts.find(x=>x.id===el.dataset.answerId);if(!a)return;if(el.dataset.answerField)a[el.dataset.answerField]=el.value;else a.evidence[el.dataset.evidence]=el.value;save();if(el.dataset.answerField==='rewrite')$('#rewriteCount').textContent=`書き直し ${E.measure(a.rewrite).characters}文字`;return;}
 if(el.dataset.paperFilter==='query'){paperFilter.query=el.value;filterPapers();}
});
document.addEventListener('change',event=>{if(!ready)return;const el=event.target;
 if(el.dataset.paperFilter){paperFilter[el.dataset.paperFilter]=el.value;filterPapers();return;}
 if(el.dataset.reviewFilter){reviewFilter[el.dataset.reviewFilter]=el.value;filterReviews();return;}
 if(el.dataset.setting==='hours'){data.settings.hours=Number(el.value);save();$('#weeklyPlan').textContent=weeklyText();return;}
 if(el.dataset.draftCheck!==undefined&&data.session){const s=data.session;s.drafts[s.paperIds[s.index]].checks[el.dataset.draftCheck]=el.checked;save();return;}
 if(el.dataset.rating){const a=data.attempts.find(x=>x.id===el.dataset.answerId);if(a){a.ratings[el.dataset.rating]=Number(el.value);save();$('#rubricSummary').textContent=`${E.rubricResult(a).filled}/6項目を点検`;}return;}
});
$('#fontButton').addEventListener('click',()=>{if(!ready)return;data.settings.large=!data.settings.large;font();save();});
$('#backupInput').addEventListener('change',async event=>{const file=event.target.files[0];event.target.value='';if(!file)return;if(file.size>20*1024*1024){toast('20MB以下のバックアップを選んでください。');return;}try{const imported=E.validateBackup(JSON.parse(await file.text()),new Set(byPaper.keys()),new Set(byLesson.keys()));if(!confirm(`答案 ${imported.attempts.length}件・講義記録 ${Object.keys(imported.lessons).length}件${imported.session?'・途中答案あり':''}を読み込みます。現在の記録を置き換えます。よろしいですか？`))return;data=imported;unreadableBackup='';storageBroken=false;$('#storageAlert').hidden=true;save();font();go('home');toast('バックアップを読み込みました。');}catch(error){toast('読み込めません：'+error.message);}});
window.addEventListener('hashchange',route);
window.addEventListener('afterprint',()=>document.body.classList.remove('printing-answer'));
window.addEventListener('storage',event=>{if(ready&&event.key===E.KEY&&event.newValue!==JSON.stringify(data))storageAlert('別のタブで学習記録が更新されました。上書きを避けるため、このタブの保存を停止しました。必要な答案はバックアップを書き出し、他のタブを閉じてページを開き直してください。');});
document.addEventListener('visibilitychange',()=>{if(!document.hidden)tick();});
async function init(){try{const urls=['papers','lessons','sources','articles'];const loaded=await Promise.all(urls.map(async n=>{const r=await fetch('assets/ronbun/'+n+'.json?v=20260910');if(!r.ok)throw Error(n+'の取得に失敗しました');return r.json();}));[papers,lessons,sources]=loaded;articles=loaded[3].articles;if(papers.length!==135||lessons.length!==86)throw Error('教材の構成を確認できませんでした');const order=['答案の基本',...E.SUBJECTS];lessons.sort((a,b)=>order.indexOf(a.subject)-order.indexOf(b.subject)||a.id.localeCompare(b.id));papers.forEach(p=>byPaper.set(p.id,p));lessons.forEach(l=>byLesson.set(l.id,l));
 try{const raw=localStorage.getItem(E.KEY);if(raw){try{data=E.validateBackup(JSON.parse(raw),new Set(byPaper.keys()),new Set(byLesson.keys()));}catch{unreadableBackup=raw;storageAlert('保存データを読み込めませんでした。元データの上書きを停止しています。「出典・使い方」から元データを救出できます。');}}}catch{storageAlert('ブラウザの保存領域を利用できません。ページを閉じる前にバックアップを書き出してください。');}
 ready=true;$('#loading').hidden=true;font();route();setInterval(tick,1000);
 }catch(error){$('#loading').innerHTML=`<h1>教材を読み込めませんでした</h1><p>${esc(error.message)}</p><p>通信状態を確認して、ページを再読み込みしてください。</p><div class="actions"><a class="btn" href="yobi-ronbun.html">再読み込み</a><a class="btn secondary" href="yobi-quiz.html">短答ノートへ</a></div>`;}}
init();
})();
