(function(root){'use strict';
 const DAY=86400000,VERSION=1,KEY='yobiRonbunNotebookV1';
 const SUBJECTS=['憲法','行政法','民法','商法','民事訴訟法','刑法','刑事訴訟法','民事実務基礎','刑事実務基礎'];
 const BLOCKS=[{id:'public',name:'公法系',subjects:['憲法','行政法'],minutes:140},{id:'civil',name:'民事系',subjects:['民法','商法','民事訴訟法'],minutes:210},{id:'criminal',name:'刑事系',subjects:['刑法','刑事訴訟法'],minutes:140},{id:'practice',name:'法律実務基礎',subjects:['民事実務基礎','刑事実務基礎'],minutes:180}];
 const RUBRIC=[{id:'demand',title:'問いに答える',detail:'主体・相手方・請求や罪責を特定し、すべての設問に結論を示した。'},{id:'issue',title:'争点と法的構成',detail:'出題趣旨の主要な争点を捉え、関係の薄い論点に紙幅を使っていない。'},{id:'rule',title:'条文・規範・理由',detail:'適用条文と要件、解釈が必要な点の規範と理由を区別して示した。'},{id:'facts',title:'事実の評価',detail:'具体的な事実を引用し、要件にとっての意味を説明した。'},{id:'counter',title:'反対事情・整合性',detail:'不利な事実や反対説を検討し、結論まで理由がつながっている。'},{id:'finish',title:'時間と答案の完成',detail:'制限時間内に最後まで書き、設問間の配分・誤記・答案欄を確認した。'}];
 const now=()=>Date.now(),obj=x=>x!==null&&typeof x==='object'&&!Array.isArray(x),finite=x=>typeof x==='number'&&Number.isFinite(x),safeId=x=>typeof x==='string'&&/^[a-zA-Z0-9_-]{1,90}$/.test(x);
 function fresh(){return{schema:VERSION,settings:{hours:12,large:false},lessons:{},attempts:[],session:null,bookmarks:{},notes:{},updated:now()};}
 function measure(text){text=String(text).replace(/\r\n?/g,'\n');const lines=text.split('\n');let rows=0;for(const line of lines)rows+=Math.max(1,Math.ceil(Array.from(line).length/30));if(!text)rows=0;return{characters:Array.from(String(text).replace(/\n/g,'')).length,rows,pages:Math.ceil(rows/23),limit:2760,over:rows>92};}
 function remaining(session,time=now()){if(!session||!session.duration)return 0;return Math.max(0,session.paused?session.remaining:session.deadline-time);}
 function pause(session,time=now()){if(!session||session.paused||!session.duration)return;session.remaining=remaining(session,time);session.paused=true;session.pauses++;}
 function resume(session,time=now()){if(!session||!session.paused)return;session.deadline=time+session.remaining;session.paused=false;}
 function newSession(ids,mode,minutes,title,time=now()){return{id:'session-'+time+'-'+Math.random().toString(36).slice(2,7),paperIds:[...ids],index:0,mode,title,started:time,duration:minutes*60000,deadline:time+minutes*60000,remaining:minutes*60000,paused:false,pauses:0,drafts:Object.fromEntries(ids.map(id=>[id,{outline:'',answer:'',checks:{}}])),stage:'outline',revealed:false};}
 function completeSession(data,time=now(),automatic=false){const s=data.session;if(!s)return[];const elapsed=s.duration?Math.max(0,s.duration-remaining(s,time)):Math.max(0,time-s.started);const attempts=s.paperIds.map((paperId,i)=>({id:s.id+'-'+i,paperId,sessionId:s.id,title:s.title,mode:s.mode,outline:s.drafts[paperId]?.outline||'',answer:s.drafts[paperId]?.answer||'',rewrite:'',created:time,elapsed,pauses:s.pauses,automatic,revealed:s.revealed,ratings:{},evidence:{},purposeNotes:'',improvement:'',status:'pending',due:time+DAY,round:0,lastReviewedDay:'',checks:s.drafts[paperId]?.checks||{}}));data.attempts.unshift(...attempts);data.session=null;data.updated=time;return attempts;}
 function recordLesson(data,id,confidence,time=now()){const r=data.lessons[id]||{stage:0,lastDay:'',visits:0};const day=new Date(time).toLocaleDateString('sv-SE');r.visits++;r.confidence=confidence;r.last=time;if(confidence==='again'){r.stage=0;r.due=time+DAY;}else{if(r.lastDay!==day)r.stage=Math.min(4,r.stage+1);r.due=time+[1,3,7,14,30][r.stage]*DAY;}r.lastDay=day;data.lessons[id]=r;return r;}
 function reviewAttempt(a,confidence,time=now()){const day=new Date(time).toLocaleDateString('sv-SE');if(confidence==='again'){a.round=0;a.status='weak';a.due=time+DAY;}else{if(a.lastReviewedDay!==day)a.round=Math.min(4,a.round+1);a.status=a.round>=3?'retained':'reviewed';a.due=time+[1,3,7,14,30][a.round]*DAY;}a.lastReviewedDay=day;}
 function rubricResult(attempt){const values=RUBRIC.map(r=>attempt.ratings[r.id]);return{filled:values.filter(x=>[0,1,2].includes(x)).length,clear:values.filter(x=>x===2).length,gaps:RUBRIC.filter(r=>attempt.ratings[r.id]===0||attempt.ratings[r.id]===1).map(r=>r.title)};}
 function topicMatches(paper,lessons,limit=4){const text=paper.text+' '+paper.purpose;return lessons.filter(l=>l.subject===paper.subject).map(l=>({lesson:l,score:l.keywords.reduce((s,k)=>s+(text.includes(k)?1:0),0)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,limit).map(x=>x.lesson);}
 function validateBackup(input,paperIds,lessonIds){const x=input?.data||input;if(!obj(x)||x.schema!==VERSION||!obj(x.settings)||!obj(x.lessons)||!Array.isArray(x.attempts)||!obj(x.bookmarks)||!obj(x.notes))throw Error('このサイトのバックアップではありません。');if(x.attempts.length>3000)throw Error('答案数が上限を超えています。');const out=fresh();out.settings={hours:[5,10,12,15,20,25].includes(x.settings.hours)?x.settings.hours:12,large:!!x.settings.large};const keepText=(v,max)=>{if(typeof v!=='string'||v.length>max)throw Error('答案またはメモの形式が不正です。');return v;};
  for(const [id,r] of Object.entries(x.lessons)){if(!lessonIds.has(id)||!obj(r))continue;out.lessons[id]={stage:Math.min(4,Math.max(0,Math.floor(Number(r.stage)||0))),lastDay:typeof r.lastDay==='string'?r.lastDay.slice(0,10):'',visits:Math.max(0,Number(r.visits)||0),confidence:r.confidence==='sure'?'sure':'again',last:finite(r.last)?r.last:0,due:finite(r.due)?r.due:now()};}
  const attemptIds=new Set();for(const a of x.attempts){if(!obj(a)||!safeId(a.id)||!paperIds.has(a.paperId)||!finite(a.created)||attemptIds.has(a.id))throw Error('答案の識別情報が不正です。');attemptIds.add(a.id);const b={id:a.id,paperId:a.paperId,sessionId:safeId(a.sessionId)?a.sessionId:'imported',title:typeof a.title==='string'?a.title.slice(0,150):'保存答案',mode:['outline','essay','exam'].includes(a.mode)?a.mode:'essay',created:a.created,elapsed:finite(a.elapsed)?Math.max(0,a.elapsed):0,pauses:Math.max(0,Number(a.pauses)||0),automatic:!!a.automatic,revealed:!!a.revealed,ratings:{},evidence:{},checks:{},status:['pending','weak','reviewed','retained'].includes(a.status)?a.status:'pending',due:finite(a.due)?a.due:now(),round:Math.min(4,Math.max(0,Math.floor(Number(a.round)||0))),lastReviewedDay:typeof a.lastReviewedDay==='string'?a.lastReviewedDay.slice(0,10):''};for(const k of ['outline','answer','rewrite','purposeNotes','improvement'])b[k]=keepText(a[k]??'',50000);for(const r of RUBRIC){if([0,1,2].includes(a.ratings?.[r.id]))b.ratings[r.id]=a.ratings[r.id];b.evidence[r.id]=keepText(a.evidence?.[r.id]??'',12000);}if(obj(a.checks))for(const [k,v] of Object.entries(a.checks))if(/^\d{1,3}$/.test(k))b.checks[k]=!!v;out.attempts.push(b);}
  for(const [id,v] of Object.entries(x.bookmarks))if(paperIds.has(id)&&v===true)out.bookmarks[id]=true;for(const [id,v] of Object.entries(x.notes))if(paperIds.has(id)||lessonIds.has(id))out.notes[id]=keepText(v,20000);
  if(x.session!==null&&x.session!==undefined){const s=x.session;if(!obj(s)||!safeId(s.id)||!Array.isArray(s.paperIds)||!s.paperIds.length||s.paperIds.length>3||new Set(s.paperIds).size!==s.paperIds.length||s.paperIds.some(id=>!paperIds.has(id))||!obj(s.drafts)||!finite(s.duration)||s.duration<0||s.duration>210*60000||!finite(s.deadline)||!finite(s.started))throw Error('途中答案の形式が不正です。');const ss=newSession(s.paperIds,['outline','essay','exam'].includes(s.mode)?s.mode:'essay',s.duration/60000,typeof s.title==='string'?s.title.slice(0,150):'途中答案',s.started);Object.assign(ss,{id:s.id,deadline:s.deadline,remaining:finite(s.remaining)?Math.max(0,Math.min(s.duration,s.remaining)):0,paused:!!s.paused,pauses:Math.max(0,Number(s.pauses)||0),index:Math.max(0,Math.min(s.paperIds.length-1,Math.floor(Number(s.index)||0))),stage:['outline','answer'].includes(s.stage)?s.stage:'outline',revealed:!!s.revealed});for(const id of s.paperIds){const d=s.drafts[id];if(!obj(d))throw Error('途中答案が欠けています。');ss.drafts[id]={outline:keepText(d.outline??'',50000),answer:keepText(d.answer??'',50000),checks:{}};if(obj(d.checks))for(const [k,v] of Object.entries(d.checks))if(/^\d{1,3}$/.test(k))ss.drafts[id].checks[k]=!!v;}out.session=ss;}
  return out;}
 const api={DAY,KEY,VERSION,SUBJECTS,BLOCKS,RUBRIC,fresh,measure,remaining,pause,resume,newSession,completeSession,recordLesson,reviewAttempt,rubricResult,topicMatches,validateBackup};root.RonbunEngine=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;
})(typeof window==='undefined'?globalThis:window);
