import {OnlineRoom} from './arcade100/network.mjs';
const $=id=>document.getElementById(id),bridge=window.SKYBREAK_BRIDGE;
let net=null,busy=false,remoteFighter=1,started=false,guestStarted=false,lastState=0,lastControl=0,lastSave=0,lastReceived=0,lastRemoteControl=0,pendingControl={};
const message=text=>$('online-notice').textContent=text;
async function setup(){if(net)return net;net=await new OnlineRoom().init();net.addEventListener('room',e=>room(e.detail));net.addEventListener('message',e=>receive(e.detail));net.addEventListener('error',e=>message(e.detail));return net;}
async function attempt(fn){if(busy)return;busy=true;message('');try{await fn();}catch(e){message(e.message);}finally{busy=false;}}
$('online-create').onclick=()=>attempt(async()=>{const n=await setup();await n.create('skybreak',$('online-name').value||'PLAYER');});
$('online-join').onclick=()=>attempt(async()=>{const n=await setup();const r=await n.join($('online-code').value,$('online-name').value||'PLAYER');if(r.game!=='skybreak'){await n.leave();throw new Error('SKYBREAKのルームコードを入力してください。');}sendConfig();});
$('online-resume').onclick=()=>attempt(async()=>{const n=await setup(),r=await n.resume();if(!r||r.game!=='skybreak')throw new Error('復帰できるSKYBREAKルームがありません。');if(r.checkpoint){bridge.restore(r.checkpoint,r.side);started=true;}sendConfig();});
$('online-ready-btn').onclick=()=>attempt(async()=>{sendConfig();await net.setReady(true);});
$('online-start-btn').onclick=()=>attempt(async()=>{await net.start();beginHost();});
$('online-copy').onclick=async()=>{const url=new URL(location.href);url.searchParams.set('room',net.room.room);try{await navigator.clipboard.writeText(url.href);message('招待リンクをコピーしました。');}catch{message('ルームコード：'+net.room.room);}};
function room(r){if(r.game!=='skybreak')return;$('online-entry').classList.add('hidden');$('online-waiting').classList.remove('hidden');$('online-room-code').textContent=r.room;$('online-members').textContent=r.members.map((m,i)=>(i===0?'HOST':'P2')+' '+m.name+' '+(m.ready?'準備OK':'準備中')).join(' / ');$('online-ready-btn').classList.toggle('hidden',r.side===0||r.status!=='waiting');$('online-start-btn').classList.toggle('hidden',r.side!==0||r.status!=='waiting');$('online-start-btn').disabled=r.members.length<2||r.members.some(m=>!m.ready);if(r.status==='closed'){bridge.message('ルームが終了しました');started=false;}if(r.status==='waiting'&&started){started=false;guestStarted=false;bridge.stop();document.querySelector('[data-mode="online"]').click();}}
function sendConfig(){if(net?.room?.side===1)net.send(net.room.members[0].id,{type:'fighter',fighter:bridge.getConfig().fighter});}
function beginHost(){if(started||net?.room?.side!==0)return;const c=bridge.getConfig(),config={fighters:[c.fighter,remoteFighter],stage:c.stage,items:c.items};bridge.start(config,0);started=true;lastSave=performance.now();net.send(net.room.members[1].id,{type:'begin',config});}
function receive({side,body}){if(body.type==='fighter'&&side===1&&Number.isInteger(body.fighter)&&body.fighter>=0&&body.fighter<4)remoteFighter=body.fighter;
 if(body.type==='begin'&&side===0&&!guestStarted){if(!body.config?.fighters?.every(v=>Number.isInteger(v)&&v>=0&&v<4))return;bridge.start(body.config,1);guestStarted=true;started=true;lastReceived=performance.now();}
 if(body.type==='control'&&side===1&&net.room.side===0&&started){bridge.controls(body.control||{});lastRemoteControl=performance.now();}
 if(body.type==='smash-state'&&side===0&&net.room.side===1){if(!guestStarted){bridge.restore(body.state,1);guestStarted=true;started=true;}else bridge.apply(body.state);lastReceived=performance.now();}
 }
window.addEventListener('skybreak-control',e=>{for(const [k,v] of Object.entries(e.detail)){if(k.endsWith('Press')||k.endsWith('Release'))pendingControl[k]=pendingControl[k]||v;else pendingControl[k]=v;}if(!net||net.room.side!==1)return;const now=performance.now(),id=net.room.members[0].id;if(now-lastControl<(net.direct(id)?40:120))return;lastControl=now;net.send(id,{type:'control',control:pendingControl});pendingControl={};if(now-lastReceived>6000)bridge.message('ホストとの再接続を待っています');});
window.addEventListener('skybreak-frame',()=>{if(!net?.ready||!started||net.room.side!==0||net.room.members.length<2)return;const now=performance.now(),id=net.room.members[1].id;if(now-lastState<(net.direct(id)?65:300))return;lastState=now;if(now-lastRemoteControl>1200)bridge.controls({});const state=bridge.snapshot();net.send(id,{type:'smash-state',state});if(now-lastSave>6000||state.phase==='over'&&net.room.status==='playing'){lastSave=now;net.checkpoint(state);}});
window.addEventListener('skybreak-start-request',()=>attempt(async()=>{if(net?.room?.side===0&&net.room.status==='finished'){await net.rematch();started=false;guestStarted=false;bridge.stop();document.querySelector('[data-mode="online"]').click();message('全員が準備OKになったら再戦できます。');}else bridge.message('オンラインルームで全員の準備を待ってください');}));
window.addEventListener('skybreak-leave-request',async()=>{await net?.leave();net=null;started=false;guestStarted=false;$('online-entry').classList.remove('hidden');$('online-waiting').classList.add('hidden');});
document.querySelectorAll('[data-fighter]').forEach(button=>button.addEventListener('click',sendConfig));setInterval(()=>{if(net?.room?.status==='waiting')sendConfig();},2500);
const code=new URLSearchParams(location.search).get('room');if(code){document.querySelector('[data-mode="online"]').click();$('online-code').value=code;message('名前を入力して参加してください。');}
