import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.185.1/build/three.module.js';

const $=s=>document.querySelector(s),root=$('#mountain-game');
const ui={objective:$('#s16-objective'),distance:$('#s16-distance'),time:$('#s16-time'),stance:$('#s16-stance'),status:$('#s16-status'),detect:$('.s16-detect'),detectFill:$('#s16-detect-fill'),alert:$('#s16-alert-label'),minimap:$('#s16-minimap'),prompt:$('#s16-prompt'),interact:$('#s16-interact'),interactFill:$('#s16-interact-fill'),interactLabel:$('#s16-interact-label'),overlay:$('#s16-overlay'),overlayTitle:$('#s16-overlay-title'),overlayMessage:$('#s16-overlay-message'),start:$('#s16-start'),fullscreen:$('#s16-fullscreen'),result:$('#s16-result'),resultLabel:$('#s16-result-label'),resultTime:$('#s16-result-time'),resultStealth:$('#s16-result-stealth'),steps:[$('#s16-step-1'),$('#s16-step-2'),$('#s16-step-3')]};
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;root.appendChild(renderer.domElement);
const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x8fa59a,.00043);const camera=new THREE.PerspectiveCamera(62,innerWidth/innerHeight,.1,6000);
const skyGeo=new THREE.SphereGeometry(4800,32,18),skyMat=new THREE.ShaderMaterial({side:THREE.BackSide,depthWrite:false,uniforms:{top:{value:new THREE.Color(0x3f6680)},mid:{value:new THREE.Color(0xb7c9bd)},bottom:{value:new THREE.Color(0xe8c99d)}},vertexShader:`varying vec3 vPos;void main(){vPos=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}`,fragmentShader:`uniform vec3 top;uniform vec3 mid;uniform vec3 bottom;varying vec3 vPos;void main(){float h=normalize(vPos).y;vec3 c=mix(mid,top,smoothstep(.0,.75,h));c=mix(bottom,c,smoothstep(-.18,.18,h));gl_FragColor=vec4(c,1.0);}`});scene.add(new THREE.Mesh(skyGeo,skyMat));
const sunDisc=new THREE.Mesh(new THREE.SphereGeometry(72,20,14),new THREE.MeshBasicMaterial({color:0xffe7ac}));sunDisc.position.set(-1650,1150,-2300);scene.add(sunDisc);scene.add(new THREE.HemisphereLight(0xd8e8df,0x24392d,1.7));const sun=new THREE.DirectionalLight(0xffe4b4,2.5);sun.position.set(-1100,1250,-750);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-850;sun.shadow.camera.right=850;sun.shadow.camera.top=850;sun.shadow.camera.bottom=-850;sun.shadow.bias=-.00025;scene.add(sun);
const WORLD=3200,rand=mulberry32(16092026),covers=[];
function h(x,z){const basin=20*Math.sin(x*.0032)+17*Math.cos(z*.0041)+9*Math.sin((x+z)*.0068)+8*Math.cos((x-z)*.008),edge=Math.max(0,(Math.max(Math.abs(x),Math.abs(z))-1120)/430);return basin+edge*edge*330;}
const terrainGeo=new THREE.PlaneGeometry(WORLD,WORLD,120,120);terrainGeo.rotateX(-Math.PI/2);const pos=terrainGeo.attributes.position,terrainColors=[];for(let i=0;i<pos.count;i++){const x=pos.getX(i),z=pos.getZ(i),y=h(x,z);pos.setY(i,y);const high=THREE.MathUtils.clamp((y+10)/260,0,1),noise=(Math.sin(x*.021)+Math.cos(z*.017))*.018,c=new THREE.Color().setRGB(.15+.25*high+noise,.29+.18*high+noise,.17+.15*high);terrainColors.push(c.r,c.g,c.b);}terrainGeo.setAttribute('color',new THREE.Float32BufferAttribute(terrainColors,3));terrainGeo.computeVertexNormals();const terrain=new THREE.Mesh(terrainGeo,new THREE.MeshStandardMaterial({vertexColors:true,roughness:.98}));terrain.receiveShadow=true;scene.add(terrain);
const mountainMat=new THREE.MeshStandardMaterial({color:0x536a62,roughness:1});for(let i=0;i<24;i++){const a=i/24*Math.PI*2,r=1850+rand()*520,height=300+rand()*520,base=260+rand()*270,m=new THREE.Mesh(new THREE.ConeGeometry(base,height,5+Math.floor(rand()*3)),mountainMat);m.position.set(Math.cos(a)*r,-40+height*.42,Math.sin(a)*r);m.rotation.y=rand()*Math.PI;m.scale.z=.7+rand()*.7;scene.add(m);}
const cloudGeo=new THREE.SphereGeometry(58,8,6),cloudMat=new THREE.MeshStandardMaterial({color:0xf5eee2,transparent:true,opacity:.23,roughness:1,depthWrite:false}),clouds=new THREE.InstancedMesh(cloudGeo,cloudMat,90),dummy=new THREE.Object3D();for(let i=0;i<90;i++){dummy.position.set((rand()-.5)*3600,520+rand()*620,(rand()-.5)*3600);dummy.scale.set(1.4+rand()*2.2,.45+rand()*.7,.8+rand()*1.5);dummy.rotation.y=rand()*Math.PI;dummy.updateMatrix();clouds.setMatrixAt(i,dummy.matrix);}scene.add(clouds);
const lake=new THREE.Mesh(new THREE.CircleGeometry(360,64),new THREE.MeshPhysicalMaterial({color:0x4d7773,transparent:true,opacity:.76,roughness:.16,clearcoat:.9,clearcoatRoughness:.15}));lake.rotation.x=-Math.PI/2;lake.scale.set(1.35,.78,1);lake.position.set(1000,h(1000,380)+3.5,380);scene.add(lake);
function nearMissionLane(x,z){return [[-1280,1080],[-620,-940],[690,-420],[1260,1080]].some(([a,b])=>Math.hypot(x-a,z-b)<125);}
const trunkGeo=new THREE.CylinderGeometry(2.2,3.9,23,7),trunkMat=new THREE.MeshStandardMaterial({color:0x44392d,roughness:1}),crownGeo=new THREE.ConeGeometry(14,42,8),crownMat=new THREE.MeshStandardMaterial({color:0x163c2c,roughness:.96}),trunks=new THREE.InstancedMesh(trunkGeo,trunkMat,560),crowns=new THREE.InstancedMesh(crownGeo,crownMat,560);trunks.castShadow=crowns.castShadow=true;let ti=0;for(let i=0;i<760&&ti<560;i++){const x=(rand()-.5)*2920,z=(rand()-.5)*2920;if(nearMissionLane(x,z)||Math.hypot(x-1000,z-380)<350)continue;const y=h(x,z),s=.64+rand()*1.1;dummy.position.set(x,y+11.5*s,z);dummy.scale.set(s,s,s);dummy.rotation.y=rand()*Math.PI*2;dummy.updateMatrix();trunks.setMatrixAt(ti,dummy.matrix);dummy.position.y=y+35*s;dummy.updateMatrix();crowns.setMatrixAt(ti,dummy.matrix);if(ti%2===0)covers.push({x,z,r:10*s});ti++;}trunks.count=crowns.count=ti;scene.add(trunks,crowns);
const rockGeo=new THREE.DodecahedronGeometry(9,1),rockMat=new THREE.MeshStandardMaterial({color:0x69736d,roughness:1}),rocks=new THREE.InstancedMesh(rockGeo,rockMat,150);rocks.castShadow=true;for(let i=0;i<150;i++){const x=(rand()-.5)*2800,z=(rand()-.5)*2800,y=h(x,z),s=.55+rand()*1.8;dummy.position.set(x,y+5*s,z);dummy.scale.set(s*1.4,s*.72,s);dummy.rotation.set(rand()*.45,rand()*6,rand()*.35);dummy.updateMatrix();rocks.setMatrixAt(i,dummy.matrix);if(i<90)covers.push({x,z,r:10*s});}scene.add(rocks);
const grassGeo=new THREE.ConeGeometry(.55,6,3),grassMat=new THREE.MeshStandardMaterial({color:0x55764d,roughness:1}),grass=new THREE.InstancedMesh(grassGeo,grassMat,900);for(let i=0;i<900;i++){const x=(rand()-.5)*2600,z=(rand()-.5)*2600,y=h(x,z);dummy.position.set(x,y+2.5,z);dummy.scale.set(.7+rand(),.7+rand()*1.2,.7+rand());dummy.rotation.y=rand()*6;dummy.updateMatrix();grass.setMatrixAt(i,dummy.matrix);}scene.add(grass);
function building(x,z,w,d,height,color=0x525c50){const g=new THREE.Group(),body=new THREE.Mesh(new THREE.BoxGeometry(w,height,d),new THREE.MeshStandardMaterial({color,roughness:.92}));body.position.y=height/2;body.castShadow=body.receiveShadow=true;g.add(body);const roof=new THREE.Mesh(new THREE.ConeGeometry(Math.max(w,d)*.72,18,4),new THREE.MeshStandardMaterial({color:0x303a32,roughness:.95}));roof.position.y=height+7;roof.rotation.y=Math.PI/4;roof.castShadow=true;g.add(roof);for(let i=-1;i<=1;i+=2){const win=new THREE.Mesh(new THREE.PlaneGeometry(12,7),new THREE.MeshBasicMaterial({color:0xffd89b,transparent:true,opacity:.65}));win.position.set(i*w*.27,height*.55,d/2+.02);g.add(win);}g.position.set(x,h(x,z),z);scene.add(g);covers.push({x,z,r:Math.max(w,d)*.46});return g;}
building(-620,-940,96,74,52,0x59635c);building(690,-420,118,84,47,0x4c5a51);building(555,-525,76,58,36,0x4b554c);building(825,-515,72,62,38,0x4e594f);
const tower=new THREE.Group(),mast=new THREE.Mesh(new THREE.CylinderGeometry(3,5,110,8),new THREE.MeshStandardMaterial({color:0x919b95,metalness:.55,roughness:.45}));mast.position.y=55;tower.add(mast);for(let y=18;y<104;y+=17){const ring=new THREE.Mesh(new THREE.TorusGeometry(16,1.3,6,20),new THREE.MeshStandardMaterial({color:0xaeb8b1,metalness:.7,roughness:.3}));ring.rotation.x=Math.PI/2;ring.position.y=y;tower.add(ring);}tower.position.set(-620,h(-620,-940)+3,-940);scene.add(tower);
const extractRing=new THREE.Mesh(new THREE.RingGeometry(34,44,56),new THREE.MeshBasicMaterial({color:0xb8e3aa,transparent:true,opacity:.7,side:THREE.DoubleSide}));extractRing.rotation.x=-Math.PI/2;extractRing.position.set(1260,h(1260,1080)+2,1080);scene.add(extractRing);const beacon=new THREE.Mesh(new THREE.CylinderGeometry(2.5,2.5,170,8,1,true),new THREE.MeshBasicMaterial({color:0xd9eaa8,transparent:true,opacity:.45}));scene.add(beacon);
function makeHuman(primary,accent,enemy=false){const root=new THREE.Group(),skin=new THREE.MeshStandardMaterial({color:enemy?0xb99072:0xb49379,roughness:.9}),cloth=new THREE.MeshStandardMaterial({color:primary,roughness:.92}),trim=new THREE.MeshStandardMaterial({color:accent,roughness:.88}),dark=new THREE.MeshStandardMaterial({color:0x1b211f,roughness:1}),rig={};const pelvis=new THREE.Mesh(new THREE.BoxGeometry(10,7,7),cloth);pelvis.position.y=18;pelvis.castShadow=true;root.add(pelvis);const torso=new THREE.Mesh(new THREE.BoxGeometry(13,20,8),cloth);torso.position.y=30;torso.castShadow=true;root.add(torso);rig.torso=torso;const neck=new THREE.Mesh(new THREE.CylinderGeometry(2.4,2.5,4,8),skin);neck.position.y=42;root.add(neck);const head=new THREE.Mesh(new THREE.SphereGeometry(5.5,12,9),skin);head.position.y=47;head.scale.z=.92;head.castShadow=true;root.add(head);const hair=new THREE.Mesh(new THREE.SphereGeometry(5.6,10,7,0,Math.PI*2,0,Math.PI*.52),dark);hair.position.y=49.3;root.add(hair);const chest=new THREE.Mesh(new THREE.BoxGeometry(8,8,1.5),trim);chest.position.set(0,31,-4.6);root.add(chest);for(const side of [-1,1]){const arm=new THREE.Group();arm.position.set(side*8,37,0);const upper=new THREE.Mesh(new THREE.CylinderGeometry(2.3,2.5,13,8),cloth);upper.position.y=-6.5;upper.castShadow=true;arm.add(upper);const hand=new THREE.Mesh(new THREE.SphereGeometry(2.3,8,7),skin);hand.position.y=-13;arm.add(hand);root.add(arm);rig[side<0?'armL':'armR']=arm;const leg=new THREE.Group();leg.position.set(side*3.2,17,0);const thigh=new THREE.Mesh(new THREE.CylinderGeometry(2.8,3,16,8),cloth);thigh.position.y=-8;thigh.castShadow=true;leg.add(thigh);const boot=new THREE.Mesh(new THREE.BoxGeometry(5,5,8),dark);boot.position.set(0,-17,-1.2);boot.castShadow=true;leg.add(boot);root.add(leg);rig[side<0?'legL':'legR']=leg;}const pack=new THREE.Mesh(new THREE.BoxGeometry(10,14,6),trim);pack.position.set(0,31,6);pack.castShadow=true;root.add(pack);if(enemy){const cap=new THREE.Mesh(new THREE.CylinderGeometry(5.8,5.8,2,12),dark);cap.position.y=51.3;root.add(cap);}root.userData.rig=rig;return root;}
function animateHuman(human,speed,now,crouch=false){const r=human.userData.rig;if(!r)return;const phase=now*.009*(.35+speed*.9),s=Math.sin(phase)*(.15+speed*.55);r.armL.rotation.x=s;r.armR.rotation.x=-s;r.legL.rotation.x=-s*.9;r.legR.rotation.x=s*.9;human.scale.y=THREE.MathUtils.lerp(human.scale.y,crouch?.74:1,.13);}
const player=makeHuman(0x22322c,0x405249,false);scene.add(player);
const objectives=[{name:'山岳レーダーを停止せよ',x:-620,z:-940,verb:'HACKING',hold:2},{name:'研究棟から機密データを回収せよ',x:690,z:-420,verb:'DOWNLOADING',hold:2.4},{name:'南東の渓谷から脱出せよ',x:1260,z:1080,verb:'EXTRACT',hold:0}];let objectiveIndex=0;
const guards=[];function addGuard(points,phase=0){const g=makeHuman(0x5a4539,0x34342d,true);scene.add(g);const cone=new THREE.Mesh(new THREE.CircleGeometry(260,34,0,THREE.MathUtils.degToRad(58)),new THREE.MeshBasicMaterial({color:0xffbf68,transparent:true,opacity:.05,side:THREE.DoubleSide,depthWrite:false}));cone.rotation.x=-Math.PI/2;scene.add(cone);const data={g,cone,points,i:phase%points.length,dir:new THREE.Vector2(1,0),speed:24+rand()*8};guards.push(data);setGuardPos(data,points[data.i]);}function setGuardPos(d,p){d.g.position.set(p[0],h(p[0],p[1]),p[1]);}
addGuard([[-820,-1030],[-500,-1100],[-430,-820],[-760,-770]]);addGuard([[-720,-820],[-520,-820],[-520,-1040]],1);addGuard([[-900,-930],[-660,-700],[-420,-900]],2);addGuard([[500,-560],[820,-590],[900,-350],[600,-300]]);addGuard([[590,-300],[760,-260],[850,-470]],2);addGuard([[440,-420],[600,-650],[760,-670]],1);addGuard([[920,-450],[720,-180],[530,-240]],1);addGuard([[1080,800],[1320,790],[1420,1060],[1190,1240]]);addGuard([[980,1120],[1180,920],[1400,1040]],2);addGuard([[1120,1250],[1380,1260],[1460,980]],1);
const keys={},moveInput={x:0,y:0};let running=false,startedAt=0,last=performance.now(),remaining=300,crouched=false,sprinting=false,detect=0,maxDetect=0,alerted=false,alerts=0,captureLock=0,clearSightTime=0,interactProgress=0,interacting=false,camYaw=Math.PI*.78,pointerId=null,lastPX=0;
function resetGame(){objectiveIndex=0;player.position.set(-1280,h(-1280,1080),1080);player.rotation.y=0;remaining=300;crouched=false;sprinting=false;detect=0;maxDetect=0;alerted=false;alerts=0;captureLock=0;clearSightTime=0;interactProgress=0;interacting=false;ui.result.classList.add('hidden');ui.result.classList.remove('win','lose');guards.forEach((g,idx)=>{g.i=idx%g.points.length;setGuardPos(g,g.points[g.i]);});updateObjectiveUI();updateSteps();ui.status.textContent='INFILTRATING';ui.alert.textContent='HIDDEN';}
function updateObjectiveUI(){const o=objectives[Math.min(objectiveIndex,objectives.length-1)];ui.objective.textContent=o.name;beacon.position.set(o.x,h(o.x,o.z)+85,o.z);beacon.visible=objectiveIndex<objectives.length;}
function updateSteps(){ui.steps.forEach((el,i)=>{el.classList.toggle('done',i<objectiveIndex);el.classList.toggle('active',i===objectiveIndex);});}
function missionStart(){resetGame();running=true;startedAt=performance.now();last=startedAt;ui.overlay.classList.add('hidden');}
function finish(success,reason){if(!running)return;running=false;const used=300-remaining,grade=maxDetect<25?'S':alerts===0?'A':alerts<=1?'B':'C';ui.overlayTitle.textContent=success?'YOU WIN':'YOU LOSE';ui.overlayMessage.innerHTML=success?'レーダーを停止し、機密データを確保。追跡を振り切って渓谷から脱出した。':`${reason}<br>遮蔽物と警備兵の向きを確認して再挑戦しよう。`;ui.result.classList.remove('hidden','win','lose');ui.result.classList.add(success?'win':'lose');ui.resultLabel.textContent=success?'WIN':'LOSE';ui.resultTime.textContent=formatTime(used);ui.resultStealth.textContent=success?grade:'---';ui.start.textContent='もう一度潜入';ui.status.textContent=success?'MISSION CLEAR':'MISSION FAILED';ui.overlay.classList.remove('hidden');}
function update(dt,now){if(!running)return;remaining=Math.max(0,300-(now-startedAt)/1000);ui.time.textContent=formatTime(remaining);if(remaining<=0){finish(false,'制限時間5分を超過した。');return;}updatePlayer(dt,now);updateGuards(dt,now);updateInteraction(dt);updateUI();}
function updatePlayer(dt,now){const kx=(keys.KeyD?1:0)-(keys.KeyA?1:0)+moveInput.x,ky=(keys.KeyW?1:0)-(keys.KeyS?1:0)-moveInput.y;let ix=THREE.MathUtils.clamp(kx,-1,1),iy=THREE.MathUtils.clamp(ky,-1,1);const len=Math.hypot(ix,iy);sprinting=!!(keys.ShiftLeft||keys.ShiftRight||$('#s16-sprint').classList.contains('active'));const speed=crouched?21:sprinting?54:34,moveAmount=Math.min(1,len)*(sprinting?1.25:1);if(len>.08){ix/=Math.max(1,len);iy/=Math.max(1,len);const forward=new THREE.Vector2(-Math.sin(camYaw),-Math.cos(camYaw)),right=new THREE.Vector2(Math.cos(camYaw),-Math.sin(camYaw)),vx=right.x*ix+forward.x*iy,vz=right.y*ix+forward.y*iy;player.position.x=THREE.MathUtils.clamp(player.position.x+vx*speed*dt,-1490,1490);player.position.z=THREE.MathUtils.clamp(player.position.z+vz*speed*dt,-1490,1490);player.rotation.y=Math.atan2(vx,vz);if(interacting&&len>.25){interacting=false;interactProgress=0;}}player.position.y=h(player.position.x,player.position.z);animateHuman(player,moveAmount,now,crouched);ui.stance.textContent=crouched?'CROUCH':sprinting?'SPRINT':'WALK';const target=new THREE.Vector3(player.position.x+Math.sin(camYaw)*94,player.position.y+62,player.position.z+Math.cos(camYaw)*94),look=new THREE.Vector3(player.position.x,player.position.y+27,player.position.z);camera.position.lerp(target,1-Math.pow(.001,dt));camera.lookAt(look);}
function updateGuards(dt,now){let seen=false,closest=99999;for(const gd of guards){const gx=gd.g.position.x,gz=gd.g.position.z;let tx,tz;if(alerted){tx=player.position.x;tz=player.position.z;}else{const p=gd.points[gd.i];tx=p[0];tz=p[1];if(Math.hypot(tx-gx,tz-gz)<14)gd.i=(gd.i+1)%gd.points.length;}const dx=tx-gx,dz=tz-gz,dist=Math.hypot(dx,dz)||1,spd=gd.speed*(alerted?1.75:1);gd.g.position.x+=dx/dist*spd*dt;gd.g.position.z+=dz/dist*spd*dt;gd.g.position.y=h(gd.g.position.x,gd.g.position.z);gd.dir.set(dx/dist,dz/dist);gd.g.rotation.y=Math.atan2(gd.dir.x,gd.dir.y);animateHuman(gd.g,alerted?1:.55,now);const pdx=player.position.x-gd.g.position.x,pdz=player.position.z-gd.g.position.z,pdist=Math.hypot(pdx,pdz);closest=Math.min(closest,pdist);const range=270*(crouched?.6:1)*(sprinting?1.18:1),dot=gd.dir.x*(pdx/(pdist||1))+gd.dir.y*(pdz/(pdist||1)),inView=pdist<range&&dot>Math.cos(THREE.MathUtils.degToRad(29))&&!blocked(gd.g.position.x,gd.g.position.z,player.position.x,player.position.z),heard=sprinting&&pdist<135;if(inView||heard)seen=true;gd.cone.position.set(gd.g.position.x,gd.g.position.y+1,gd.g.position.z);gd.cone.rotation.z=-Math.atan2(gd.dir.y,gd.dir.x);gd.cone.visible=!alerted;}
if(seen){detect=Math.min(100,detect+dt*(crouched?23:38));maxDetect=Math.max(maxDetect,detect);clearSightTime=0;}else{detect=Math.max(0,detect-dt*(alerted?7:18));if(alerted)clearSightTime+=dt;}if(detect>=100&&!alerted){alerted=true;alerts++;captureLock=0;ui.status.textContent='COMPROMISED';}if(alerted&&seen)captureLock+=dt;else captureLock=Math.max(0,captureLock-dt*1.5);if(alerted&&clearSightTime>9&&detect<30){alerted=false;clearSightTime=0;captureLock=0;ui.status.textContent='INFILTRATING';}if(alerted&&captureLock>4.4){finish(false,'警備兵に位置を完全特定された。');return;}if(alerted&&closest<14)finish(false,'警備兵に確保された。');}
function blocked(ax,az,bx,bz){for(const c of covers){const dx=bx-ax,dz=bz-az,l2=dx*dx+dz*dz;if(l2<1)continue;const t=THREE.MathUtils.clamp(((c.x-ax)*dx+(c.z-az)*dz)/l2,0,1),px=ax+t*dx,pz=az+t*dz;if((px-c.x)**2+(pz-c.z)**2<c.r*c.r&&t>.08&&t<.92)return true;}return false;}
function updateInteraction(dt){if(objectiveIndex>=objectives.length)return;const o=objectives[objectiveIndex],d=Math.hypot(player.position.x-o.x,player.position.z-o.z),near=d<52;ui.prompt.classList.toggle('hidden',!near||o.hold===0);ui.distance.textContent=`${Math.round(d)} m`;if(o.hold===0&&near){objectiveIndex++;updateSteps();finish(true);return;}if(interacting){if(!near){interacting=false;interactProgress=0;}else{interactProgress+=dt;ui.interact.classList.remove('hidden');ui.interactLabel.textContent=o.verb;ui.interactFill.style.width=`${Math.min(100,interactProgress/o.hold*100)}%`;if(interactProgress>=o.hold){objectiveIndex++;interacting=false;interactProgress=0;ui.interact.classList.add('hidden');updateSteps();if(objectiveIndex<objectives.length)updateObjectiveUI();}}}else ui.interact.classList.add('hidden');}
function tryInteract(){if(!running||objectiveIndex>=objectives.length)return;const o=objectives[objectiveIndex];if(Math.hypot(player.position.x-o.x,player.position.z-o.z)<52&&o.hold>0){interacting=true;interactProgress=0;}}
function updateUI(){ui.detectFill.style.width=`${detect}%`;ui.detect.classList.toggle('alert',alerted||detect>60);ui.alert.textContent=alerted?`LOCK ${Math.max(0,4.4-captureLock).toFixed(1)}`:detect>55?'DANGER':detect>18?'SUSPICIOUS':'HIDDEN';if(!alerted)ui.status.textContent=detect>55?'EVADING':'INFILTRATING';drawMinimap();}
function drawMinimap(){const c=ui.minimap.getContext('2d'),w=ui.minimap.width;c.clearRect(0,0,w,w);const grad=c.createRadialGradient(w*.5,w*.5,5,w*.5,w*.5,w*.72);grad.addColorStop(0,'rgba(25,55,42,.96)');grad.addColorStop(1,'rgba(5,17,14,.96)');c.fillStyle=grad;c.fillRect(0,0,w,w);c.strokeStyle='rgba(255,255,255,.07)';for(let i=1;i<4;i++){c.beginPath();c.moveTo(i*w/4,0);c.lineTo(i*w/4,w);c.stroke();c.beginPath();c.moveTo(0,i*w/4);c.lineTo(w,i*w/4);c.stroke();}const map=v=>(v+1600)/3200*w;if(objectiveIndex<objectives.length){const o=objectives[objectiveIndex];c.fillStyle='#dceba9';c.beginPath();c.arc(map(o.x),map(o.z),6,0,Math.PI*2);c.fill();}if(alerted){c.fillStyle='#ef7965';for(const g of guards){c.beginPath();c.arc(map(g.g.position.x),map(g.g.position.z),2.4,0,Math.PI*2);c.fill();}}c.save();c.translate(map(player.position.x),map(player.position.z));c.rotate(-player.rotation.y);c.fillStyle='#fff';c.beginPath();c.moveTo(0,-7);c.lineTo(5,6);c.lineTo(-5,6);c.closePath();c.fill();c.restore();c.strokeStyle='rgba(255,255,255,.26)';c.strokeRect(.5,.5,w-1,w-1);}
function actionCrouch(){crouched=!crouched;$('#s16-crouch').classList.toggle('active',crouched);}
addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='KeyC'&&!e.repeat)actionCrouch();if(e.code==='KeyE'&&!e.repeat)tryInteract();if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();});addEventListener('keyup',e=>keys[e.code]=false);
renderer.domElement.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&e.button!==0)return;pointerId=e.pointerId;lastPX=e.clientX;renderer.domElement.setPointerCapture?.(e.pointerId);});renderer.domElement.addEventListener('pointermove',e=>{if(pointerId!==e.pointerId)return;const dx=e.clientX-lastPX;lastPX=e.clientX;camYaw-=dx*.006;});renderer.domElement.addEventListener('pointerup',e=>{if(pointerId===e.pointerId)pointerId=null;});
const stick=$('#s16-stick'),knob=$('#s16-knob');let stickId=null;function stickMove(e){const r=stick.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=e.clientX-cx,dy=e.clientY-cy,m=Math.hypot(dx,dy),max=r.width*.34,s=Math.min(1,max/(m||1));moveInput.x=dx/max*s;moveInput.y=dy/max*s;knob.style.transform=`translate(${dx*s}px,${dy*s}px)`;}stick.addEventListener('pointerdown',e=>{stickId=e.pointerId;stick.setPointerCapture(e.pointerId);stickMove(e)});stick.addEventListener('pointermove',e=>{if(e.pointerId===stickId)stickMove(e)});stick.addEventListener('pointerup',e=>{if(e.pointerId===stickId){stickId=null;moveInput.x=moveInput.y=0;knob.style.transform='translate(0,0)';}});
$('#s16-crouch').addEventListener('click',actionCrouch);$('#s16-action').addEventListener('pointerdown',tryInteract);const sprintBtn=$('#s16-sprint');sprintBtn.addEventListener('pointerdown',()=>sprintBtn.classList.add('active'));['pointerup','pointercancel','pointerleave'].forEach(ev=>sprintBtn.addEventListener(ev,()=>sprintBtn.classList.remove('active')));ui.fullscreen.addEventListener('click',()=>{if(!document.fullscreenElement)document.documentElement.requestFullscreen?.();else document.exitFullscreen?.();});document.addEventListener('fullscreenchange',()=>ui.fullscreen.textContent=document.fullscreenElement?'EXIT FULLSCREEN':'FULLSCREEN');ui.start.addEventListener('click',missionStart);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});
function animate(now){requestAnimationFrame(animate);const dt=Math.min(.05,(now-last)/1000||.016);last=now;update(dt,now);extractRing.rotation.z+=dt*.35;beacon.material.opacity=.32+Math.sin(now*.003)*.16;clouds.position.x=Math.sin(now*.000025)*70;lake.material.opacity=.72+Math.sin(now*.0012)*.025;renderer.render(scene,camera);}resetGame();camera.position.set(-1190,115,1190);camera.lookAt(player.position.x,player.position.y+25,player.position.z);requestAnimationFrame(animate);
function formatTime(sec){sec=Math.max(0,sec);const m=Math.floor(sec/60),s=Math.floor(sec%60);return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;}
function mulberry32(a){return function(){let t=a+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296;}}
