import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.185.1/build/three.module.js';

const root=document.getElementById('mountain-game');
const ui={objective:document.getElementById('s16-objective'),distance:document.getElementById('s16-distance'),time:document.getElementById('s16-time'),stance:document.getElementById('s16-stance'),detect:document.querySelector('.s16-detect'),detectFill:document.getElementById('s16-detect-fill'),alert:document.getElementById('s16-alert-label'),minimap:document.getElementById('s16-minimap'),prompt:document.getElementById('s16-prompt'),interact:document.getElementById('s16-interact'),interactFill:document.getElementById('s16-interact-fill'),interactLabel:document.getElementById('s16-interact-label'),overlay:document.getElementById('s16-overlay'),overlayTitle:document.getElementById('s16-overlay-title'),overlayMessage:document.getElementById('s16-overlay-message'),start:document.getElementById('s16-start'),fullscreen:document.getElementById('s16-fullscreen')};
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.8));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.0;root.appendChild(renderer.domElement);
const scene=new THREE.Scene();scene.background=new THREE.Color(0x92aaa1);scene.fog=new THREE.FogExp2(0x91a69c,.00048);
const camera=new THREE.PerspectiveCamera(63,innerWidth/innerHeight,.1,5000);
scene.add(new THREE.HemisphereLight(0xcfe1dc,0x24372a,1.55));const sun=new THREE.DirectionalLight(0xffe8bd,2.35);sun.position.set(-700,900,500);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-700;sun.shadow.camera.right=700;sun.shadow.camera.top=700;sun.shadow.camera.bottom=-700;sun.shadow.bias=-.0002;scene.add(sun);
const WORLD=3200;
function h(x,z){const edge=Math.max(0,(Math.max(Math.abs(x),Math.abs(z))-1100)/500);return 24*Math.sin(x*.0031)+18*Math.cos(z*.0042)+11*Math.sin((x+z)*.007)+edge*edge*360;}
const terrainGeo=new THREE.PlaneGeometry(WORLD,WORLD,96,96);const pos=terrainGeo.attributes.position;const colors=[];for(let i=0;i<pos.count;i++){const x=pos.getX(i),z=pos.getY(i),y=h(x,z);pos.setZ(i,y);const t=THREE.MathUtils.clamp((y+20)/220,0,1),c=new THREE.Color().setRGB(.19+.16*t,.31+.11*t,.19+.10*t);colors.push(c.r,c.g,c.b);}terrainGeo.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));terrainGeo.computeVertexNormals();terrainGeo.rotateX(-Math.PI/2);const terrain=new THREE.Mesh(terrainGeo,new THREE.MeshStandardMaterial({vertexColors:true,roughness:.98,metalness:0}));terrain.receiveShadow=true;scene.add(terrain);
const lake=new THREE.Mesh(new THREE.PlaneGeometry(620,420),new THREE.MeshPhysicalMaterial({color:0x567e79,transparent:true,opacity:.73,roughness:.25,metalness:.05}));lake.rotation.x=-Math.PI/2;lake.position.set(970,h(970,380)+4,380);scene.add(lake);
const rand=mulberry32(16092026),covers=[];
const trunkGeo=new THREE.CylinderGeometry(2.2,3.6,20,6),trunkMat=new THREE.MeshStandardMaterial({color:0x493f2f,roughness:1});const crownGeo=new THREE.ConeGeometry(13,38,7),crownMat=new THREE.MeshStandardMaterial({color:0x173b2b,roughness:.95});const trunks=new THREE.InstancedMesh(trunkGeo,trunkMat,430),crowns=new THREE.InstancedMesh(crownGeo,crownMat,430);trunks.castShadow=crowns.castShadow=true;const dummy=new THREE.Object3D();let ti=0;for(let i=0;i<560&&ti<430;i++){const x=(rand()-.5)*2900,z=(rand()-.5)*2900;if(Math.abs(x)<160&&Math.abs(z)<160)continue;if(nearMissionLane(x,z))continue;const y=h(x,z),s=.72+rand()*.85;dummy.position.set(x,y+10*s,z);dummy.scale.set(s,s,s);dummy.rotation.y=rand()*Math.PI*2;dummy.updateMatrix();trunks.setMatrixAt(ti,dummy.matrix);dummy.position.y=y+32*s;dummy.updateMatrix();crowns.setMatrixAt(ti,dummy.matrix);if(ti%3===0)covers.push({x,z,r:10*s});ti++;}trunks.count=crowns.count=ti;scene.add(trunks,crowns);
const rockGeo=new THREE.DodecahedronGeometry(8,0),rockMat=new THREE.MeshStandardMaterial({color:0x68716a,roughness:1});const rocks=new THREE.InstancedMesh(rockGeo,rockMat,100);rocks.castShadow=true;for(let i=0;i<100;i++){const x=(rand()-.5)*2750,z=(rand()-.5)*2750,y=h(x,z),s=.6+rand()*1.5;dummy.position.set(x,y+5*s,z);dummy.scale.set(s*1.3,s*.75,s);dummy.rotation.set(rand(),rand()*3,rand());dummy.updateMatrix();rocks.setMatrixAt(i,dummy.matrix);if(i<55)covers.push({x,z,r:9*s});}scene.add(rocks);
function nearMissionLane(x,z){return [[-1280,1080],[-620,-940],[690,-420],[1260,1080]].some(([a,b])=>Math.hypot(x-a,z-b)<115);}
function building(x,z,w,d,height,color=0x525c50){const g=new THREE.Group(),body=new THREE.Mesh(new THREE.BoxGeometry(w,height,d),new THREE.MeshStandardMaterial({color,roughness:.92}));body.position.y=height/2;body.castShadow=body.receiveShadow=true;g.add(body);const roof=new THREE.Mesh(new THREE.ConeGeometry(Math.max(w,d)*.72,18,4),new THREE.MeshStandardMaterial({color:0x313830,roughness:.95}));roof.position.y=height+7;roof.rotation.y=Math.PI/4;roof.castShadow=true;g.add(roof);g.position.set(x,h(x,z),z);scene.add(g);covers.push({x,z,r:Math.max(w,d)*.45});return g;}
building(-620,-940,96,74,52,0x5b635d);building(690,-420,116,84,46,0x4c584f);building(560,-520,76,58,36,0x4b544b);building(820,-520,72,62,38,0x4e574d);
const tower=new THREE.Group();const mast=new THREE.Mesh(new THREE.CylinderGeometry(3,5,105,8),new THREE.MeshStandardMaterial({color:0x89928b,metalness:.5,roughness:.5}));mast.position.y=52;tower.add(mast);for(let y=20;y<95;y+=17){const ring=new THREE.Mesh(new THREE.TorusGeometry(16,1.4,6,18),new THREE.MeshStandardMaterial({color:0xa5afa8,metalness:.7,roughness:.35}));ring.rotation.x=Math.PI/2;ring.position.y=y;tower.add(ring);}tower.position.set(-620,h(-620,-940)+4,-940);scene.add(tower);
const extractRing=new THREE.Mesh(new THREE.RingGeometry(34,43,48),new THREE.MeshBasicMaterial({color:0xa6d9a0,transparent:true,opacity:.65,side:THREE.DoubleSide}));extractRing.rotation.x=-Math.PI/2;extractRing.position.set(1260,h(1260,1080)+2,1080);scene.add(extractRing);
const beaconMat=new THREE.MeshBasicMaterial({color:0xd9eaa8,transparent:true,opacity:.55});const beacon=new THREE.Mesh(new THREE.CylinderGeometry(3,3,160,10,1,true),beaconMat);scene.add(beacon);
const player=new THREE.Group();const bodyMat=new THREE.MeshStandardMaterial({color:0x202b26,roughness:.9});const pb=new THREE.Mesh(new THREE.CapsuleGeometry(7,18,5,8),bodyMat);pb.castShadow=true;pb.position.y=16;player.add(pb);const pack=new THREE.Mesh(new THREE.BoxGeometry(11,15,7),new THREE.MeshStandardMaterial({color:0x38443a,roughness:1}));pack.position.set(0,18,7);pack.castShadow=true;player.add(pack);scene.add(player);
const objectives=[{name:'山岳レーダーを停止せよ',x:-620,z:-940,verb:'HACKING',hold:2.0},{name:'研究棟から機密データを回収せよ',x:690,z:-420,verb:'DOWNLOADING',hold:2.4},{name:'南東の渓谷から脱出せよ',x:1260,z:1080,verb:'EXTRACT',hold:0}];let objectiveIndex=0;
const guardMat=new THREE.MeshStandardMaterial({color:0x5d4337,roughness:.9}),guardHead=new THREE.MeshStandardMaterial({color:0xc5a588,roughness:.9});const guards=[];function addGuard(points,phase=0){const g=new THREE.Group(),b=new THREE.Mesh(new THREE.CapsuleGeometry(6,17,4,7),guardMat),head=new THREE.Mesh(new THREE.SphereGeometry(5.6,10,8),guardHead);b.position.y=15;head.position.y=31;b.castShadow=head.castShadow=true;g.add(b,head);scene.add(g);const cone=new THREE.Mesh(new THREE.CircleGeometry(250,28,0,THREE.MathUtils.degToRad(56)),new THREE.MeshBasicMaterial({color:0xffc678,transparent:true,opacity:.055,side:THREE.DoubleSide,depthWrite:false}));cone.rotation.x=-Math.PI/2;scene.add(cone);const data={g,cone,points,i:phase%points.length,dir:new THREE.Vector2(1,0),speed:25+rand()*8};guards.push(data);setGuardPos(data,points[data.i]);}
function setGuardPos(d,p){d.g.position.set(p[0],h(p[0],p[1]),p[1]);}
addGuard([[-820,-1030],[-500,-1100],[-430,-820],[-760,-770]]);addGuard([[-720,-820],[-520,-820],[-520,-1040]],1);addGuard([[-900,-930],[-660,-700],[-420,-900]],2);addGuard([[500,-560],[820,-590],[900,-350],[600,-300]]);addGuard([[590,-300],[760,-260],[850,-470]],2);addGuard([[440,-420],[600,-650],[760,-670]],1);addGuard([[920,-450],[720,-180],[530,-240]],1);addGuard([[1080,800],[1320,790],[1420,1060],[1190,1240]]);addGuard([[980,1120],[1180,920],[1400,1040]],2);addGuard([[1120,1250],[1380,1260],[1460,980]],1);
const keys={},moveInput={x:0,y:0};let running=false,startedAt=0,last=performance.now(),remaining=300,crouched=false,sprinting=false,detect=0,alerted=false,clearSightTime=0,interactProgress=0,interacting=false,camYaw=Math.PI*.78,pointerId=null,lastPX=0;
function resetGame(){objectiveIndex=0;player.position.set(-1280,h(-1280,1080),1080);player.rotation.y=0;remaining=300;crouched=false;sprinting=false;detect=0;alerted=false;clearSightTime=0;interactProgress=0;interacting=false;guards.forEach((g,idx)=>{g.i=idx%g.points.length;setGuardPos(g,g.points[g.i]);});updateObjectiveUI();}
function updateObjectiveUI(){const o=objectives[Math.min(objectiveIndex,objectives.length-1)];ui.objective.textContent=o.name;beacon.position.set(o.x,h(o.x,o.z)+80,o.z);beacon.visible=objectiveIndex<objectives.length;}
function missionStart(){resetGame();running=true;startedAt=performance.now();last=startedAt;ui.overlay.classList.add('hidden');renderer.domElement.focus?.();}
function finish(success,reason){if(!running)return;running=false;ui.overlayTitle.textContent=success?'MISSION COMPLETE':'MISSION FAILED';ui.overlayMessage.innerHTML=success?`機密データを確保し、山岳地帯から離脱した。<br><strong>${formatTime(300-remaining)}</strong> で作戦完了。`:`${reason}<br>ルートと警備兵の視界を読み直して再挑戦しよう。`;ui.start.textContent='もう一度潜入';ui.overlay.classList.remove('hidden');}
function update(dt,now){if(!running)return;remaining=Math.max(0,300-(now-startedAt)/1000);ui.time.textContent=formatTime(remaining);if(remaining<=0){finish(false,'制限時間5分を超過した。');return;}updatePlayer(dt);updateGuards(dt);updateInteraction(dt);updateUI();}
function updatePlayer(dt){const kx=(keys.KeyD?1:0)-(keys.KeyA?1:0)+moveInput.x,ky=(keys.KeyW?1:0)-(keys.KeyS?1:0)-moveInput.y;let ix=THREE.MathUtils.clamp(kx,-1,1),iy=THREE.MathUtils.clamp(ky,-1,1);const len=Math.hypot(ix,iy);sprinting=!!(keys.ShiftLeft||keys.ShiftRight||document.getElementById('s16-sprint').classList.contains('active'));let speed=crouched?21:sprinting?53:34;if(len>.08){ix/=Math.max(1,len);iy/=Math.max(1,len);const forward=new THREE.Vector2(-Math.sin(camYaw),-Math.cos(camYaw)),right=new THREE.Vector2(Math.cos(camYaw),-Math.sin(camYaw));const vx=right.x*ix+forward.x*iy,vz=right.y*ix+forward.y*iy;player.position.x=THREE.MathUtils.clamp(player.position.x+vx*speed*dt,-1490,1490);player.position.z=THREE.MathUtils.clamp(player.position.z+vz*speed*dt,-1490,1490);player.rotation.y=Math.atan2(vx,vz);if(interacting&&len>.25){interacting=false;interactProgress=0;}}player.position.y=h(player.position.x,player.position.z);pb.scale.y=THREE.MathUtils.lerp(pb.scale.y,crouched?.72:1,dt*10);ui.stance.textContent=crouched?'CROUCH':sprinting?'SPRINT':'WALK';
const target=new THREE.Vector3(player.position.x+Math.sin(camYaw)*82,player.position.y+55,player.position.z+Math.cos(camYaw)*82),look=new THREE.Vector3(player.position.x,player.position.y+16,player.position.z);camera.position.lerp(target,1-Math.pow(.001,dt));camera.lookAt(look);}
function updateGuards(dt){let seen=false,closest=99999;for(const gd of guards){const gx=gd.g.position.x,gz=gd.g.position.z;let tx,tz;if(alerted){tx=player.position.x;tz=player.position.z;}else{const p=gd.points[gd.i];tx=p[0];tz=p[1];if(Math.hypot(tx-gx,tz-gz)<14)gd.i=(gd.i+1)%gd.points.length;}const dx=tx-gx,dz=tz-gz,dist=Math.hypot(dx,dz)||1,spd=gd.speed*(alerted?1.75:1);gd.g.position.x+=dx/dist*spd*dt;gd.g.position.z+=dz/dist*spd*dt;gd.g.position.y=h(gd.g.position.x,gd.g.position.z);gd.dir.set(dx/dist,dz/dist);gd.g.rotation.y=Math.atan2(gd.dir.x,gd.dir.y);const pdx=player.position.x-gd.g.position.x,pdz=player.position.z-gd.g.position.z,pdist=Math.hypot(pdx,pdz);closest=Math.min(closest,pdist);const range=250*(crouched?.62:1)*(sprinting?1.15:1),dot=gd.dir.x*(pdx/(pdist||1))+gd.dir.y*(pdz/(pdist||1));const inView=pdist<range&&dot>Math.cos(THREE.MathUtils.degToRad(28))&&!blocked(gd.g.position.x,gd.g.position.z,player.position.x,player.position.z);const heard=sprinting&&pdist<125;if(inView||heard)seen=true;gd.cone.position.set(gd.g.position.x,gd.g.position.y+1,gd.g.position.z);gd.cone.rotation.z=-Math.atan2(gd.dir.y,gd.dir.x);gd.cone.visible=!alerted;}
if(seen){detect=Math.min(100,detect+dt*(crouched?22:35));clearSightTime=0;}else{detect=Math.max(0,detect-dt*(alerted?8:17));if(alerted)clearSightTime+=dt;}if(detect>=100&&!alerted){alerted=true;ui.alert.textContent='ALERT';}if(alerted&&clearSightTime>8&&detect<35){alerted=false;clearSightTime=0;ui.alert.textContent='HIDDEN';}if(alerted&&closest<13)finish(false,'警備兵に確保された。');}
function blocked(ax,az,bx,bz){for(const c of covers){const dx=bx-ax,dz=bz-az,l2=dx*dx+dz*dz;if(l2<1)continue;const t=THREE.MathUtils.clamp(((c.x-ax)*dx+(c.z-az)*dz)/l2,0,1),px=ax+t*dx,pz=az+t*dz;if((px-c.x)**2+(pz-c.z)**2<c.r*c.r&&t>.08&&t<.92)return true;}return false;}
function updateInteraction(dt){if(objectiveIndex>=objectives.length)return;const o=objectives[objectiveIndex],d=Math.hypot(player.position.x-o.x,player.position.z-o.z),near=d<50;ui.prompt.classList.toggle('hidden',!near||o.hold===0);ui.distance.textContent=`${Math.round(d)} m`;if(o.hold===0&&near){objectiveIndex++;finish(true);return;}if(interacting){if(!near){interacting=false;interactProgress=0;}else{interactProgress+=dt;ui.interact.classList.remove('hidden');ui.interactLabel.textContent=o.verb;ui.interactFill.style.width=`${Math.min(100,interactProgress/o.hold*100)}%`;if(interactProgress>=o.hold){objectiveIndex++;interacting=false;interactProgress=0;ui.interact.classList.add('hidden');if(objectiveIndex<objectives.length)updateObjectiveUI();}}}else ui.interact.classList.add('hidden');}
function tryInteract(){if(!running||objectiveIndex>=objectives.length)return;const o=objectives[objectiveIndex],d=Math.hypot(player.position.x-o.x,player.position.z-o.z);if(d<50&&o.hold>0){interacting=true;interactProgress=0;}}
function updateUI(){ui.detectFill.style.width=`${detect}%`;ui.detect.classList.toggle('alert',alerted||detect>60);ui.alert.textContent=alerted?'ALERT':detect>55?'DANGER':detect>18?'SUSPICIOUS':'HIDDEN';drawMinimap();}
function drawMinimap(){const c=ui.minimap.getContext('2d'),w=ui.minimap.width;c.clearRect(0,0,w,w);c.fillStyle='rgba(7,24,19,.88)';c.fillRect(0,0,w,w);c.strokeStyle='rgba(255,255,255,.08)';for(let i=1;i<4;i++){c.beginPath();c.moveTo(i*w/4,0);c.lineTo(i*w/4,w);c.stroke();c.beginPath();c.moveTo(0,i*w/4);c.lineTo(w,i*w/4);c.stroke();}const map=(v)=>((v+1600)/3200)*w;if(objectiveIndex<objectives.length){const o=objectives[objectiveIndex];c.fillStyle='#dceba9';c.beginPath();c.arc(map(o.x),map(o.z),6,0,Math.PI*2);c.fill();}if(alerted){c.fillStyle='#ef7965';for(const g of guards){c.beginPath();c.arc(map(g.g.position.x),map(g.g.position.z),2.5,0,Math.PI*2);c.fill();}}c.save();c.translate(map(player.position.x),map(player.position.z));c.rotate(-player.rotation.y);c.fillStyle='#fff';c.beginPath();c.moveTo(0,-7);c.lineTo(5,6);c.lineTo(-5,6);c.closePath();c.fill();c.restore();c.strokeStyle='rgba(255,255,255,.28)';c.strokeRect(.5,.5,w-1,w-1);}
function actionCrouch(){crouched=!crouched;document.getElementById('s16-crouch').classList.toggle('active',crouched);}
addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='KeyC'&&!e.repeat)actionCrouch();if(e.code==='KeyE'&&!e.repeat)tryInteract();if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();});addEventListener('keyup',e=>keys[e.code]=false);
renderer.domElement.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&e.button!==0)return;pointerId=e.pointerId;lastPX=e.clientX;renderer.domElement.setPointerCapture?.(e.pointerId);});renderer.domElement.addEventListener('pointermove',e=>{if(pointerId!==e.pointerId)return;const dx=e.clientX-lastPX;lastPX=e.clientX;camYaw-=dx*.006;});renderer.domElement.addEventListener('pointerup',e=>{if(pointerId===e.pointerId)pointerId=null;});
const stick=document.getElementById('s16-stick'),knob=document.getElementById('s16-knob');let stickId=null;function stickMove(e){const r=stick.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=e.clientX-cx,dy=e.clientY-cy,m=Math.hypot(dx,dy),max=r.width*.34,s=Math.min(1,max/(m||1));moveInput.x=dx/max*s;moveInput.y=dy/max*s;knob.style.transform=`translate(${dx*s}px,${dy*s}px)`;}stick.addEventListener('pointerdown',e=>{stickId=e.pointerId;stick.setPointerCapture(e.pointerId);stickMove(e)});stick.addEventListener('pointermove',e=>{if(e.pointerId===stickId)stickMove(e)});stick.addEventListener('pointerup',e=>{if(e.pointerId===stickId){stickId=null;moveInput.x=moveInput.y=0;knob.style.transform='translate(0,0)';}});
document.getElementById('s16-crouch').addEventListener('click',actionCrouch);document.getElementById('s16-action').addEventListener('pointerdown',tryInteract);const sprintBtn=document.getElementById('s16-sprint');sprintBtn.addEventListener('pointerdown',()=>sprintBtn.classList.add('active'));['pointerup','pointercancel','pointerleave'].forEach(ev=>sprintBtn.addEventListener(ev,()=>sprintBtn.classList.remove('active')));
ui.fullscreen.addEventListener('click',()=>{if(!document.fullscreenElement)document.documentElement.requestFullscreen?.();else document.exitFullscreen?.();});ui.start.addEventListener('click',missionStart);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});
function animate(now){requestAnimationFrame(animate);const dt=Math.min(.05,(now-last)/1000||.016);last=now;update(dt,now);extractRing.rotation.z+=dt*.35;beacon.material.opacity=.35+Math.sin(now*.003)*.18;renderer.render(scene,camera);}resetGame();camera.position.set(-1200,100,1180);camera.lookAt(player.position);requestAnimationFrame(animate);
function formatTime(sec){sec=Math.max(0,sec);const m=Math.floor(sec/60),s=Math.floor(sec%60);return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;}
function mulberry32(a){return function(){let t=a+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296;}}
