/** Deterministic ONE PIECE CARD GAME engine. Supported pool: ST01 / ST02 only. */
import catalog from './cards.mjs?v=20260919-art1';
export const CARDS = Object.freeze(Object.fromEntries(Object.entries(catalog).map(([id,c])=>[id,Object.freeze({...c,id,name:c.nameJa||c.name,nameJa:c.nameJa||c.name,type:c.type.toLowerCase(),colors:c.colors||[id.startsWith('ST01')?'red':'green'],traits:c.traits||[],cost:Number(c.cost)||0,power:Number(c.power)||0,counter:Number(c.counter)||0})])));
const counts01=[4,4,4,4,4,4,4,4,2,4,2,2,2,2,2,2];
const counts02=[4,4,4,4,2,4,4,2,2,4,4,2,2,2,4,2];
const deckOf=(set,counts,name)=>({id:set,name,leader:`${set}-001`,cards:counts.flatMap((n,i)=>Array(n).fill(`${set}-${String(i+2).padStart(3,'0')}`)),don:10});
export const STARTER_DECKS={ST01:deckOf('ST01',counts01,'麦わらの一味'),ST02:deckOf('ST02',counts02,'最悪の世代')};
export const RULES_VERSION='ST01/ST02 · official comprehensive rules 1.2.1';
const copy=x=>structuredClone(x);
const definition=c=>CARDS[c.id];
const name=c=>definition(c)?.nameJa||c.id;
const board=p=>[p.leader,...p.characters];
const at=(s,p,uid)=>board(s.players[p]).find(c=>c.uid===uid)|| (s.players[p].stage?.uid===uid?s.players[p].stage:null);
const has=(c,t)=>definition(c).traits.includes(t);
const blockers=new Set(['ST01-006','ST02-004','ST02-013']);
const triggers=new Set(['ST01-002','ST01-014','ST01-015','ST01-016','ST02-005','ST02-015','ST02-017']);
const mainEvents=new Set(['ST01-015','ST01-016','ST02-017']);
const counterEvents=new Set(['ST01-014','ST02-015','ST02-016']);
function log(s,text){s.log.push({turn:s.turn,text});if(s.log.length>160)s.log.shift();}
function random(s){let x=s.rng|0;x^=x<<13;x^=x>>>17;x^=x<<5;s.rng=x>>>0;return s.rng/4294967296;}
function shuffle(s,deck){for(let i=deck.length-1;i>0;i--){const j=Math.floor(random(s)*(i+1));[deck[i],deck[j]]=[deck[j],deck[i]];}return deck;}
function seedNumber(seed){if(typeof seed==='number')return (seed>>>0)||1;let h=2166136261;for(const c of String(seed||'grandline'))h=Math.imul(h^c.charCodeAt(0),16777619);return(h>>>0)||1;}
function instance(s,id){return{uid:`c${s.nextUid++}`,id,rested:false,don:0,enteredTurn:0,used:{},turnPower:0,battlePower:0,noBlockTurn:false};}
export function validateDeck(input){const d=typeof input==='string'?STARTER_DECKS[input]:input;const errors=[];if(!d)return{valid:false,errors:['未対応のデッキです。']};const leader=CARDS[d.leader];if(!leader||leader.type!=='leader')errors.push('対応するリーダーを1枚選んでください。');if(!Array.isArray(d.cards)||d.cards.length!==50)errors.push('メインデッキは50枚必要です。');const counts={};for(const id of d.cards||[]){const c=CARDS[id];if(!c){errors.push(`未対応カード: ${id}`);continue;}if(c.type==='leader')errors.push('リーダーはメインデッキに入れられません。');if(leader&&!c.colors.some(x=>leader.colors.includes(x)))errors.push(`${id}: リーダーと異なる色です。`);counts[id]=(counts[id]||0)+1;if(counts[id]===5)errors.push(`${id}: 同一番号は4枚までです。`);}if(d.don!==undefined&&d.don!==10)errors.push('ドン!!デッキは10枚必要です。');return{valid:errors.length===0,errors:[...new Set(errors)]};}
export function createGame({decks=['ST01','ST02'],first=0,seed=Date.now()}={}){if(![0,1].includes(first)||decks.length!==2)throw new Error('プレイヤー設定が不正です。');const s={version:1,rules:RULES_VERSION,rng:seedNumber(seed),nextUid:1,players:[],active:first,first,turn:0,phase:'setup',winner:null,reason:null,battle:null,prompt:null,queue:[],resolving:[],log:[]};for(let i=0;i<2;i++){const test=validateDeck(decks[i]);if(!test.valid)throw new Error(test.errors.join('\n'));const d=typeof decks[i]==='string'?STARTER_DECKS[decks[i]]:decks[i];const p={name:`PLAYER ${i+1}`,deckName:d.name||'カスタムデッキ',leader:instance(s,d.leader),deck:[],hand:[],life:[],characters:[],stage:null,trash:[],don:{active:0,rested:0,total:0},turns:0,mulligan:null};p.deck=shuffle(s,d.cards.map(id=>instance(s,id)));p.hand=p.deck.splice(0,5);s.players.push(p);}log(s,'対戦開始。手札5枚を確認し、1度だけ引き直せます。');return s;}
function lose(s,p,reason){s.winner=1-p;s.reason=reason;s.phase='ended';s.prompt=null;s.queue=[];log(s,`PLAYER ${2-p} の勝利 — ${reason}`);}
function checkDeck(s,p){if(s.players[p].deck.length===0){lose(s,p,'デッキが0枚になりました');return true;}return false;}
function draw(s,p,n){for(let i=0;i<n;i++){if(checkDeck(s,p))return; s.players[p].hand.push(s.players[p].deck.shift());if(checkDeck(s,p))return;}}
function pay(s,p,n){s.players[p].don.active-=n;s.players[p].don.rested+=n;}
function readyDon(s,p,n){const d=s.players[p].don;const a=Math.min(n,d.rested);d.rested-=a;d.active+=a;}
function removeCharacter(s,p,uid,reason='トラッシュ'){const player=s.players[p],i=player.characters.findIndex(c=>c.uid===uid);if(i<0)return;const[c]=player.characters.splice(i,1);player.don.rested+=c.don;c.don=0;c.turnPower=0;c.battlePower=0;c.noBlockTurn=false;player.trash.push(c);log(s,`${name(c)}を${reason}。`);}
function startTurn(s,p){s.active=p;s.turn++;s.phase='main';const player=s.players[p];player.turns++;for(const c of board(player)){player.don.rested+=c.don;c.don=0;c.rested=false;c.used={};}if(player.stage){player.stage.rested=false;player.stage.used={};}player.don.active+=player.don.rested;player.don.rested=0;if(!(s.turn===1&&p===s.first)){draw(s,p,1);if(s.winner!==null)return;}const add=Math.min(s.turn===1?1:2,10-player.don.total);player.don.total+=add;player.don.active+=add;log(s,`PLAYER ${p+1} のターン ${player.turns}：ドン!! ${player.don.total}枚。`);}
function endTurn(s){const p=s.players[s.active];for(const c of p.characters)if(c.id==='ST02-013'&&c.don>=1){c.rested=false;log(s,`${name(c)}がターン終了時にアクティブ。`);}for(const pl of s.players)for(const c of board(pl)){c.turnPower=0;c.battlePower=0;c.noBlockTurn=false;}startTurn(s,1-s.active);}
export function powerOf(s,p,cardOrUid){const c=typeof cardOrUid==='string'?at(s,p,cardOrUid):cardOrUid;if(!c||!CARDS[c.id])return 0;let power=definition(c).power+(c.turnPower||0)+(c.battlePower||0);if(s.active===p)power+=c.don*1000;if(c.id==='ST01-013'&&c.don>=1)power+=1000;if(c.id==='ST02-003'&&c.don>=1&&s.players[p].characters.length>=3)power+=2000;if(s.active===p&&(has(c,'超新星')||has(c,'海軍')))power+=1000*s.players[p].characters.filter(x=>x.id==='ST02-014'&&x.don>=1&&x.rested).length;return power;}
function rush(c){return c.id==='ST01-012'||(c.id==='ST01-004'&&c.don>=2);}
function canAttack(s,p,c){return s.active===p&&s.players[p].turns>1&&!c.rested&&(definition(c).type==='leader'||c.enteredTurn<s.players[p].turns||rush(c));}
function ask(s,p,title,kind,options,data={}){s.prompt={player:p,title,kind,options:options.map((o,i)=>({...o,key:String(i)})),data};s.phase='prompt';}
function option(c,extra={}){return{label:name(c),uid:c.uid,cardId:c.id,...extra};}
const skip={label:'選ばない',skip:true};
function askTargets(s,p,title,effect,targets,data={},optional=true){ask(s,p,title,'target',[...targets.map(c=>option(c)),...(optional?[skip]:[])],{effect,...data});}
function attachRested(s,p,max){const n=Math.min(max,s.players[p].don.rested);const options=[];for(const c of board(s.players[p]))for(let amount=1;amount<=n;amount++)options.push(option(c,{amount,label:`${name(c)}にレストのドン!! ${amount}枚を付与`}));options.push(skip);ask(s,p,'レストのドン!!の付与先を選択','attachRested',options);}
function readyDonPrompt(s,p,max){const n=Math.min(max,s.players[p].don.rested);if(!n)return;ask(s,p,'アクティブにするドン!!を選択','readyDon',Array.from({length:n+1},(_,amount)=>({amount,label:amount?`ドン!! ${amount}枚をアクティブ`:'選ばない'})));}
function effect(s,t){const p=t.player,pl=s.players[p],enemy=s.players[1-p],src=at(s,p,t.uid),id=t.id,mode=t.mode;if(mode==='activate'){
 if(id==='ST01-001'||id==='ST01-007'){src.used.main=true;attachRested(s,p,1);return;}
 if(id==='ST01-017'){src.rested=true;askTargets(s,p,'サニー号：麦わらの一味を強化','buff',board(pl).filter(c=>has(c,'麦わらの一味')),{amount:1000,duration:'turn'});return;}
 if(id==='ST02-001'){ask(s,p,'キッド：3ドン!!と手札1枚を支払う','kidCost',pl.hand.map(c=>option(c)),{uid:src.uid});return;}
 if(id==='ST02-007'){pay(s,p,1);src.rested=true;const cards=pl.deck.slice(0,5);ask(s,p,'ボニー：上から5枚の超新星を1枚まで手札へ','search',[...cards.filter(c=>has(c,'超新星')).map(c=>option(c)),skip],{cards});return;}
 }
 if(mode==='attack'){
 if(id==='ST01-002'&&src.don>=2)s.battle.forbidLargeBlockers=true;
 if(id==='ST01-012'&&src.don>=2)s.battle.noBlock=true;
 if(id==='ST01-005'&&src.don>=1)askTargets(s,p,'ジンベエ：ほかの味方を+1000','buff',board(pl).filter(c=>c.uid!==src.uid),{amount:1000,duration:'turn'});
 if(id==='ST02-008'&&src.don>=1&&enemy.don.active>0)ask(s,p,'アプー：相手のドン!!を1枚までレスト','restEnemyDon',[{label:'相手のドン!!を1枚レスト',amount:1},skip]);return;
 }
 if(mode==='play'){
 if(id==='ST01-011')attachRested(s,p,2);
 if(id==='ST02-005')askTargets(s,p,'キラー：レストのコスト3以下をKO','ko',enemy.characters.filter(c=>c.rested&&definition(c).cost<=3),{owner:1-p});
 if(id==='ST02-009')askTargets(s,p,'ロー：コスト5以下の味方をアクティブ','ready',pl.characters.filter(c=>c.rested&&definition(c).cost<=5&&(has(c,'超新星')||has(c,'ハートの海賊団'))));
 }
 if((id==='ST01-002'||id==='ST02-005')&&mode==='trigger'){s.queue.unshift({kind:'enter',player:p,card:t.card});return;}
 if(id==='ST01-014')askTargets(s,p,mode==='trigger'?'ガードポイント：このターン+1000':'ガードポイント：このバトル+3000','buff',board(pl),{amount:mode==='trigger'?1000:3000,duration:mode==='trigger'?'turn':'battle'});
 if(id==='ST01-015')askTargets(s,p,'JET銃：パワー6000以下をKO','ko',enemy.characters.filter(c=>powerOf(s,1-p,c)<=6000),{owner:1-p});
 if(id==='ST01-016'){
 if(mode==='trigger')askTargets(s,p,'悪魔風脚：コスト3以下のブロッカーをKO','ko',enemy.characters.filter(c=>definition(c).cost<=3&&blockers.has(c.id)),{owner:1-p});
 else askTargets(s,p,'悪魔風脚：麦わらの一味をブロック不可に','noBlock',board(pl).filter(c=>has(c,'麦わらの一味')));
 }
 if(id==='ST02-015'||id==='ST02-016'){
 if(mode==='trigger')readyDonPrompt(s,p,2);
 else {s.queue.unshift({kind:'readyDonPrompt',player:p,max:1});askTargets(s,p,`${id==='ST02-015'?'ROOM シャンブルズ':'反発'}：カウンター対象を選択`,'buff',board(pl),{amount:id==='ST02-015'?2000:4000,duration:'battle'});}
 }
 if(id==='ST02-017'){
 if(mode==='trigger')askTargets(s,p,'藁備手刀：手札からコスト2以下の超新星を登場','playHand',pl.hand.filter(c=>['character','stage'].includes(definition(c).type)&&definition(c).cost<=2&&has(c,'超新星')));
 else askTargets(s,p,'藁備手刀：相手キャラをレスト','rest',enemy.characters,{owner:1-p});
 }
}
function enter(s,t){const p=s.players[t.player],c=t.card;if(definition(c).type==='stage'){s.resolving=s.resolving.filter(x=>x.uid!==c.uid);if(p.stage)p.trash.push(p.stage);p.stage=c;log(s,`${name(c)}を設置。`);return;}if(p.characters.length>=5){ask(s,t.player,'キャラは5枚まで。登場前に1枚をトラッシュ','replace',p.characters.map(c=>option(c)),{entry:t});return;}s.resolving=s.resolving.filter(x=>x.uid!==c.uid);c.rested=false;c.don=0;c.enteredTurn=p.turns;c.used={};c.turnPower=0;c.battlePower=0;c.noBlockTurn=false;p.characters.push(c);log(s,`${name(c)}が登場。`);s.queue.unshift({kind:'effect',player:t.player,id:c.id,uid:c.uid,mode:'play'});}
function beginBlock(s){s.battle.step='block';s.phase='battle';if(!availableBlockers(s).length){s.battle.step='counter';log(s,'カウンターステップ。');}}
function availableBlockers(s){const b=s.battle;if(!b||b.noBlock)return[];return s.players[b.defender].characters.filter(c=>!c.rested&&blockers.has(c.id)&&(!b.forbidLargeBlockers||powerOf(s,b.defender,c)<5000));}
function resolveBattle(s){const b=s.battle,a=at(s,b.attacker,b.attackerUid),target=at(s,b.defender,b.targetUid);if(!a||!target){finishBattle(s);return;}b.compared=true;b.targetWasCharacter=definition(target).type==='character';b.attackPower=powerOf(s,b.attacker,a);b.defendPower=powerOf(s,b.defender,target);log(s,`バトル：${name(a)} ${b.attackPower} vs ${name(target)} ${b.defendPower}。`);s.queue.push({kind:'finishBattle'});if(b.attackPower<b.defendPower){log(s,'アタックを防ぎました。');return;}if(b.targetWasCharacter){removeCharacter(s,b.defender,target.uid,'KO');return;}const p=s.players[b.defender];if(!p.life.length){lose(s,b.defender,'ライフ0でリーダーがダメージを受けました');return;}const card=p.life.shift();log(s,`PLAYER ${b.defender+1} がライフ1枚を確認。残り${p.life.length}。`);if(triggers.has(card.id))ask(s,b.defender,`${name(card)}：トリガーを発動しますか？`,'trigger',[{label:'トリガーを発動',activate:true,cardId:card.id},{label:'手札に加える',activate:false}],{card});else p.hand.push(card);}
function finishBattle(s){const b=s.battle;if(b){const a=at(s,b.attacker,b.attackerUid);if(a&&a.id==='ST02-010'&&a.don>=1&&!a.used.hawkins&&b.compared&&b.targetWasCharacter){a.used.hawkins=true;a.rested=false;log(s,'ホーキンスがバトル終了時にアクティブ。');}}for(const p of s.players)for(const c of board(p))c.battlePower=0;s.battle=null;s.phase='main';}
function pump(s){while(!s.prompt&&s.queue.length&&s.winner===null){const t=s.queue.shift();if(t.kind==='effect')effect(s,t);else if(t.kind==='enter')enter(s,t);else if(t.kind==='block')beginBlock(s);else if(t.kind==='finishBattle')finishBattle(s);else if(t.kind==='readyDonPrompt')readyDonPrompt(s,t.player,t.max);else if(t.kind==='cleanup'){s.resolving=s.resolving.filter(c=>c.uid!==t.card.uid);if(t.trash)s.players[t.player].trash.push(t.card);}}if(!s.prompt&&s.winner===null)s.phase=s.battle?'battle':s.phase==='setup'?'setup':'main';}
function resolvePrompt(s,opt){const q=s.prompt,p=q.player,pl=s.players[p],d=q.data;s.prompt=null;
 if(q.kind==='target'&&!opt.skip){const owner=d.owner??p,c=at(s,owner,opt.uid);if(d.effect==='buff'){c[d.duration==='battle'?'battlePower':'turnPower']+=d.amount;log(s,`${name(c)}を+${d.amount}。`);}if(d.effect==='ko')removeCharacter(s,owner,opt.uid,'KO');if(d.effect==='ready')c.rested=false;if(d.effect==='rest')c.rested=true;if(d.effect==='noBlock')c.noBlockTurn=true;if(d.effect==='playHand'){const i=pl.hand.findIndex(c=>c.uid===opt.uid);const[card]=pl.hand.splice(i,1);s.queue.unshift({kind:'enter',player:p,card});}}
 if(q.kind==='attachRested'&&!opt.skip){pl.don.rested-=opt.amount;at(s,p,opt.uid).don+=opt.amount;log(s,`${name(at(s,p,opt.uid))}にレストのドン!! ${opt.amount}枚を付与。`);}
 if(q.kind==='readyDon')readyDon(s,p,opt.amount);
 if(q.kind==='restEnemyDon'&&!opt.skip)pay(s,1-p,1);
 if(q.kind==='kidCost'){pay(s,p,3);const i=pl.hand.findIndex(c=>c.uid===opt.uid);const[c]=pl.hand.splice(i,1);pl.trash.push(c);pl.leader.rested=false;pl.leader.used.main=true;log(s,`手札の${name(c)}を捨て、キッドをアクティブ。`);}
 if(q.kind==='replace'){removeCharacter(s,p,opt.uid);s.queue.unshift(d.entry);}
 if(q.kind==='trigger'){const c=d.card;if(opt.activate){log(s,`${name(c)}のトリガー発動。`);s.resolving.push(c);s.queue.unshift({kind:'effect',player:p,id:c.id,card:c,mode:'trigger'},{kind:'cleanup',player:p,card:c,trash:definition(c).type!=='character'});}else pl.hand.push(c);}
 if(q.kind==='search'){let rest=d.cards;if(!opt.skip){const chosen=pl.deck.find(c=>c.uid===opt.uid);pl.deck=pl.deck.filter(c=>c.uid!==opt.uid);pl.hand.push(chosen);rest=rest.filter(c=>c.uid!==opt.uid);log(s,`ボニーで${name(chosen)}を公開して手札へ。`);if(checkDeck(s,p))return;}if(rest.length>1)ask(s,p,'残りをデッキ下へ：上に置く順に選択','bottomOrder',rest.map(c=>option(c)),{cards:rest,ordered:[]});else{pl.deck=pl.deck.filter(c=>!rest.some(x=>x.uid===c.uid));pl.deck.push(...rest);}}
 if(q.kind==='bottomOrder'){const chosen=d.cards.find(c=>c.uid===opt.uid),rest=d.cards.filter(c=>c.uid!==opt.uid),ordered=[...d.ordered,chosen];if(rest.length>1)ask(s,p,'残りをデッキ下へ：次の1枚を選択','bottomOrder',rest.map(c=>option(c)),{cards:rest,ordered});else{const all=[...ordered,...rest];pl.deck=pl.deck.filter(c=>!all.some(x=>x.uid===c.uid));pl.deck.push(...all);}}
}
export function legalActions(s,p){if(![0,1].includes(p)||s.winner!==null)return[];if(s.phase==='setup')return s.players[p].mulligan===null&&actingPlayer(s)===p?[{type:'mulligan',redraw:false,label:'この手札で開始'},{type:'mulligan',redraw:true,label:'5枚すべて引き直す（1回のみ）'}]:[];if(s.prompt)return s.prompt.player===p?s.prompt.options.map(o=>({type:'pick',key:o.key,label:o.label,...(o.cardId?{cardId:o.cardId}:{}),...(o.uid?{uid:o.uid}:{})})):[];if(s.battle){const b=s.battle;if(b.defender!==p)return[];if(b.step==='block')return[...availableBlockers(s).map(c=>({type:'block',uid:c.uid,cardId:c.id,label:`${name(c)}でブロック`})),{type:'skipBlock',label:'ブロックしない'}];if(b.step==='counter'){const pl=s.players[p];return[...pl.hand.filter(c=>(definition(c).type==='character'&&definition(c).counter>0)||(counterEvents.has(c.id)&&pl.don.active>=definition(c).cost)).map(c=>({type:'counter',uid:c.uid,cardId:c.id,label:definition(c).type==='character'?`${name(c)}でカウンター +${definition(c).counter}`:`${name(c)}をカウンター発動（${definition(c).cost}ドン!!）`})),{type:'resolve',label:'カウンターを終了・バトル判定'}];}return[];}if(s.active!==p)return[];const pl=s.players[p],actions=[];for(const c of pl.hand)if(definition(c).cost<=pl.don.active&&(definition(c).type==='character'||definition(c).type==='stage'||mainEvents.has(c.id)))actions.push({type:'play',uid:c.uid,cardId:c.id,label:`${name(c)}を${definition(c).type==='event'?'発動':'登場'}（${definition(c).cost}ドン!!）`});for(const c of board(pl)){if(canAttack(s,p,c))for(const target of [s.players[1-p].leader,...s.players[1-p].characters.filter(x=>x.rested)])actions.push({type:'attack',attackerUid:c.uid,targetUid:target.uid,cardId:c.id,label:`${name(c)} → ${name(target)} にアタック`});for(let amount=1;amount<=pl.don.active;amount++)actions.push({type:'attach',targetUid:c.uid,amount,cardId:c.id,label:`${name(c)}にドン!! ${amount}枚を付与`});if(['ST01-001','ST01-007'].includes(c.id)&&!c.used.main)actions.push({type:'activate',uid:c.uid,cardId:c.id,label:`${name(c)}：レストのドン!!を付与`});if(c.id==='ST02-001'&&!c.used.main&&pl.don.active>=3&&pl.hand.length)actions.push({type:'activate',uid:c.uid,cardId:c.id,label:'キッド：3ドン!!＋手札1枚で再びアクティブ'});if(c.id==='ST02-007'&&!c.rested&&pl.don.active>=1)actions.push({type:'activate',uid:c.uid,cardId:c.id,label:'ボニー：1ドン!!＋自身レストで5枚から超新星を探す'});}if(pl.stage?.id==='ST01-017'&&!pl.stage.rested)actions.push({type:'activate',uid:pl.stage.uid,cardId:pl.stage.id,label:'サニー号：自身レストで麦わらの一味を+1000'});actions.push({type:'end',label:'ターンを終了'});return actions;}
function actionKey(a){return JSON.stringify(Object.fromEntries(Object.entries(a).filter(([k])=>!['label','cardId','uid'].includes(k)||k==='uid'&&a.type!=='pick').sort(([a],[b])=>a.localeCompare(b))));}
export function act(state,p,action){const legal=legalActions(state,p);const matching=legal.find(a=>actionKey(a)===actionKey(action));if(!matching)throw new Error('現在の状態では選べないアクションです。');const a=matching,s=copy(state),pl=s.players[p];if(a.type==='mulligan'){if(a.redraw){pl.deck.push(...pl.hand);pl.hand=shuffle(s,pl.deck).splice(0,5);}pl.mulligan=a.redraw;pl.life=pl.deck.splice(0,CARDS[pl.leader.id].life||5).reverse();log(s,`PLAYER ${p+1} が${a.redraw?'手札を引き直して':'手札を確定して'}準備完了。`);if(s.players.every(x=>x.mulligan!==null))startTurn(s,s.first);return s;}
 if(a.type==='pick')resolvePrompt(s,s.prompt.options.find(o=>o.key===a.key));
 if(a.type==='play'){const i=pl.hand.findIndex(c=>c.uid===a.uid),[c]=pl.hand.splice(i,1);pay(s,p,definition(c).cost);if(definition(c).type==='event'){s.resolving.push(c);log(s,`${name(c)}を発動。`);s.queue.push({kind:'effect',player:p,id:c.id,mode:'main'},{kind:'cleanup',player:p,card:c,trash:true});}else s.queue.push({kind:'enter',player:p,card:c});}
 if(a.type==='attach'){pl.don.active-=a.amount;at(s,p,a.targetUid).don+=a.amount;log(s,`${name(at(s,p,a.targetUid))}にドン!! ${a.amount}枚を付与。`);}
 if(a.type==='activate'){const c=at(s,p,a.uid);s.queue.push({kind:'effect',player:p,id:c.id,uid:c.uid,mode:'activate'});}
 if(a.type==='attack'){const c=at(s,p,a.attackerUid);c.rested=true;s.battle={attacker:p,defender:1-p,attackerUid:c.uid,targetUid:a.targetUid,originalTargetUid:a.targetUid,step:'attack',noBlock:!!c.noBlockTurn,forbidLargeBlockers:false,compared:false};s.phase='battle';log(s,`${name(c)}が${name(at(s,1-p,a.targetUid))}へアタック。`);s.queue.push({kind:'effect',player:p,id:c.id,uid:c.uid,mode:'attack'},{kind:'block'});}
 if(a.type==='block'){const c=at(s,p,a.uid);c.rested=true;s.battle.targetUid=c.uid;s.battle.step='counter';log(s,`${name(c)}がブロック。`);}
 if(a.type==='skipBlock')s.battle.step='counter';
 if(a.type==='counter'){const i=pl.hand.findIndex(c=>c.uid===a.uid),[c]=pl.hand.splice(i,1);log(s,`${name(c)}をカウンターに使用。`);if(definition(c).type==='character'){pl.trash.push(c);askTargets(s,p,`${name(c)}：カウンター +${definition(c).counter} の対象`,'buff',board(pl),{amount:definition(c).counter,duration:'battle'},false);}else{s.resolving.push(c);pay(s,p,definition(c).cost);s.queue.push({kind:'effect',player:p,id:c.id,mode:'counter'},{kind:'cleanup',player:p,card:c,trash:true});}}
 if(a.type==='resolve')resolveBattle(s);
 if(a.type==='end')endTurn(s);
 pump(s);return s;
}
export function viewFor(state,p){const s=copy(state);delete s.rng;delete s.nextUid;delete s.queue;for(let i=0;i<2;i++){const pl=s.players[i];pl.deck=pl.deck.map((_,n)=>({uid:`hidden-deck-${i}-${n}`,hidden:true}));pl.life=pl.life.map((_,n)=>({uid:`hidden-life-${i}-${n}`,hidden:true}));if(i!==p)pl.hand=pl.hand.map((_,n)=>({uid:`hidden-hand-${i}-${n}`,hidden:true}));for(const c of board(pl))c.power=powerOf(state,i,c);}if(s.prompt){if(s.prompt.player===p){s.prompt={player:p,title:s.prompt.title,kind:s.prompt.kind,options:s.prompt.options.map(({key,label,uid,cardId})=>({key,label,uid,cardId})),...(s.prompt.kind==='trigger'?{card:s.prompt.data.card}:{}),...(['search','bottomOrder'].includes(s.prompt.kind)?{cards:s.prompt.data.cards}:{})};}else{s.prompt={player:s.prompt.player,title:'相手が効果を解決しています',kind:'waiting',options:[]};}}return s;}
/** Heuristic opponent. Scores public board + its own hand; never consults deck/life identities. */
export function chooseAI(s,p){const actions=legalActions(s,p);if(!actions.length)return null;const pl=s.players[p],foe=s.players[1-p];const worth=c=>definition(c).cost*2+(blockers.has(c.id)?3:0)+(c.id==='ST01-012'?5:0)+(c.id==='ST02-007'?3:0);function score(a){
 if(a.type==='mulligan')return a.redraw?(pl.hand.some(c=>definition(c).type==='character'&&definition(c).cost<=2)?-1:2):1;
 if(a.type==='pick'){const q=s.prompt,o=q.options.find(o=>o.key===a.key);if(q.kind==='trigger'){const id=q.data.card.id;const useful=(id==='ST02-015'?pl.don.rested>0:id==='ST02-017'?pl.hand.some(c=>definition(c).type==='character'&&definition(c).cost<=2&&has(c,'超新星')):id==='ST01-015'?foe.characters.some(c=>powerOf(s,1-p,c)<=6000):id==='ST01-016'?foe.characters.some(c=>blockers.has(c.id)&&definition(c).cost<=3):true);return o.activate?(useful?10:-1):0;}if(o.skip)return-10;if(q.kind==='readyDon')return o.amount;if(q.kind==='restEnemyDon')return 10;if(q.kind==='search')return worth(pl.deck.find(c=>c.uid===o.uid));if(q.kind==='bottomOrder')return-worth(q.data.cards.find(c=>c.uid===o.uid));if(q.kind==='kidCost')return-worth(pl.hand.find(c=>c.uid===o.uid));if(q.kind==='replace')return-worth(at(s,p,o.uid));if(q.kind==='attachRested'){const c=at(s,p,o.uid);return (canAttack(s,p,c)?20:0)+o.amount+(definition(c).type==='leader'?1:0)+(c.id==='ST01-004'&&c.don+o.amount>=2?20:0)+(c.id==='ST02-013'&&c.don===0?12:0);}if(q.kind==='target'){const d=q.data,c=d.effect==='playHand'?pl.hand.find(c=>c.uid===o.uid):at(s,d.owner??p,o.uid);if(d.effect==='ko')return worth(c);if(d.effect==='playHand')return worth(c);if(d.effect==='ready')return(c.rested?20:0)+worth(c);if(d.effect==='rest')return(c.rested?-20:0)+(blockers.has(c.id)?12:0)+worth(c);if(d.effect==='buff'&&s.battle&&s.battle.defender===p)return c.uid===s.battle.targetUid?100:0;return(canAttack(s,p,c)?20:0)+worth(c);}return 1;}
 if(a.type==='block'){const b=s.battle,att=powerOf(s,b.attacker,b.attackerUid),def=powerOf(s,p,b.targetUid),c=at(s,p,a.uid);if(att<def)return-30;const isLeader=b.targetUid===pl.leader.uid;return(isLeader?(pl.life.length<=1?70:pl.life.length<=2?25:-15):worth(at(s,p,b.targetUid))*2)-worth(c);}
 if(a.type==='skipBlock')return 0;
 if(a.type==='counter'){const b=s.battle,need=powerOf(s,b.attacker,b.attackerUid)-powerOf(s,p,b.targetUid)+1000;if(need<=0)return-50;const target=at(s,p,b.targetUid),isLeader=definition(target).type==='leader';if(isLeader&&pl.life.length>2)return-20;const c=pl.hand.find(c=>c.uid===a.uid),amount=counterEvents.has(c.id)?c.id==='ST01-014'?3000:c.id==='ST02-015'?2000:4000:definition(c).counter;let budget=pl.don.active,total=0;for(const h of pl.hand){if(definition(h).type==='character')total+=definition(h).counter;else if(counterEvents.has(h.id)&&budget>=definition(h).cost){budget-=definition(h).cost;total+=h.id==='ST01-014'?3000:h.id==='ST02-015'?2000:4000;}}if(total<need)return-30;return 40-(amount>=need?amount-need:1000)/1000-worth(c)*0.1;}
 if(a.type==='resolve')return 0;
 if(a.type==='play'){const c=pl.hand.find(c=>c.uid===a.uid),d=definition(c);if(d.type==='event'){if(c.id==='ST01-015')return foe.characters.some(x=>powerOf(s,1-p,x)<=6000&&definition(x).cost>=3)?68:-15;if(c.id==='ST02-017')return foe.characters.some(x=>!x.rested&&blockers.has(x.id))?35:-15;if(c.id==='ST01-016')return foe.characters.some(x=>!x.rested&&blockers.has(x.id))&&board(pl).some(x=>canAttack(s,p,x)&&has(x,'麦わらの一味'))?30:-15;}if(d.type==='stage')return pl.stage?-15:24;if(pl.characters.length>=5&&worth(c)<=Math.min(...pl.characters.map(worth)))return-20;return 30+d.cost*3+(blockers.has(c.id)?10:0)+(c.id==='ST01-012'?10:0);}
 if(a.type==='activate'){const c=at(s,p,a.uid);if(c.id==='ST02-001')return c.rested&&pl.turns>1?80:-20;if(c.id==='ST02-007')return pl.hand.length<7?35:-10;if(c.id==='ST01-017')return board(pl).some(x=>canAttack(s,p,x))?55:-5;return pl.don.rested>0?60:-10;}
 if(a.type==='attack'){const att=powerOf(s,p,a.attackerUid),def=powerOf(s,1-p,a.targetUid),target=at(s,1-p,a.targetUid);if(att<def)return-10;if(target.uid===foe.leader.uid)return foe.life.length===0?100:at(s,p,a.attackerUid).id==='ST02-001'&&pl.don.active>=3&&pl.hand.length?75:20+(att-def)/2000;return 30+worth(target)+(att-def)/3000;}
 if(a.type==='attach'){const c=at(s,p,a.targetUid),d=definition(c);const reserve=pl.hand.some(x=>counterEvents.has(x.id))&&foe.characters.length?Math.min(2,pl.don.active):0;if(a.amount>pl.don.active-reserve)return-10;const targets=[foe.leader,...foe.characters.filter(x=>x.rested)];const now=powerOf(s,p,c),after=now+a.amount*1000+(c.id==='ST01-013'&&c.don===0?1000:0)+(c.id==='ST02-003'&&c.don===0&&pl.characters.length>=3?2000:0);const attackable=canAttack(s,p,c)||(c.id==='ST01-004'&&!c.rested&&pl.turns>1&&c.don+a.amount>=2);if(!attackable)return c.id==='ST02-013'&&c.don===0?10-a.amount:-10;const gain=targets.some(x=>now<powerOf(s,1-p,x)&&after>=powerOf(s,1-p,x));return(gain?28:12)-a.amount*0.1+(c.id==='ST01-012'&&c.don<2&&c.don+a.amount>=2?15:0)+(d.type==='leader'?1:0);}
 if(a.type==='end')return 0;return-100;
 }return actions.map((a,i)=>({a,i,score:score(a)})).sort((a,b)=>b.score-a.score||a.i-b.i)[0].a;}

export function actingPlayer(s){if(s.winner!==null)return null;if(s.phase==='setup')return s.players[s.first].mulligan===null?s.first:1-s.first;return s.prompt?.player??s.battle?.defender??s.active;}
