import * as T from 'three';
import {rng,ROADS} from './core.mjs';
// Lightweight authored environment pass: continuous terrain replaces placeholder peaks.
export function enrichCity(view){
 const {scene}=view;
 for(const mesh of [...scene.children])if(mesh.geometry?.type==='ConeGeometry'&&Math.hypot(mesh.position.x,mesh.position.z)>900){scene.remove(mesh);mesh.geometry.dispose();}
 const hash=(x,y)=>{let n=Math.sin(x*127.1+y*311.7)*43758.5453;return n-Math.floor(n);};
 const noise=(x,y)=>{let ix=Math.floor(x),iy=Math.floor(y),a=x-ix,b=y-iy;a=a*a*(3-2*a);b=b*b*(3-2*b);return T.MathUtils.lerp(T.MathUtils.lerp(hash(ix,iy),hash(ix+1,iy),a),T.MathUtils.lerp(hash(ix,iy+1),hash(ix+1,iy+1),a),b);};
 for(let side=0;side<2;side++){
  const g=new T.PlaneGeometry(5000,1900,120,40).rotateX(-Math.PI/2),pos=g.attributes.position,colors=[];
  for(let i=0;i<pos.count;i++){const x=pos.getX(i),z=pos.getZ(i),edge=Math.sin((z/1900+.5)*Math.PI),h=Math.pow(Math.max(0,edge),.65)*(70+noise(x*.0016+side*7,z*.0019)*230+noise(x*.004,z*.005)*58);pos.setY(i,h-12);const c=new T.Color().setRGB(.10+h*.00016,.16+h*.00017,.18+h*.00023);colors.push(c.r,c.g,c.b);}
  g.setAttribute('color',new T.Float32BufferAttribute(colors,3));g.computeVertexNormals();const m=new T.Mesh(g,new T.MeshStandardMaterial({vertexColors:true,roughness:1,metalness:0}));if(side===0)m.position.set(0,-12,-1850);else{m.rotation.y=Math.PI/2;m.position.set(-1850,-12,0);}scene.add(m);
 }
 view.sky.material.fragmentShader=`varying vec3 vDirection;uniform float phase;float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}void main(){vec3 d=normalize(vDirection);float h=clamp(d.y,0.,1.);vec3 sun=normalize(vec3(-.7,.105,-.65));float s=max(dot(d,sun),0.);float warm=pow(s,7.)*(1.-phase*.7);vec3 horizon=mix(vec3(.16,.25,.33),vec3(.60,.29,.115),warm);vec3 top=mix(vec3(.024,.083,.17),vec3(.005,.018,.048),phase);vec3 col=mix(horizon,top,pow(h,.38));float cloud=sin(d.x*19.+sin(d.z*13.))*sin(d.z*28.+d.y*15.);float band=smoothstep(.025,.08,h)*(1.-smoothstep(.19,.30,h));col+=vec3(.08,.06,.047)*smoothstep(.48,.95,cloud)*band;col+=vec3(.9,.41,.13)*pow(s,240.)*(1.-phase)*.42;col+=vec3(2.2,1.3,.55)*smoothstep(.99955,.9998,s)*(1.-phase);float stars=step(.99935,hash(floor(d.xz/max(.15,h)*1300.)))*smoothstep(.2,.55,h)*phase;col+=stars*.32;gl_FragColor=vec4(col,1.);}`;
 view.sky.material.needsUpdate=true;view.scene.fog.color.set(0x6e8591);view.scene.fog.density=.00085;
 const seen=new Set();scene.traverse(object=>{const mats=Array.isArray(object.material)?object.material:[object.material];for(const mat of mats){if(!mat||seen.has(mat))continue;seen.add(mat);if(mat.emissiveMap===view.tex.emission){mat.bumpMap=view.tex.wall;mat.bumpScale=.10;mat.roughness=.43;mat.metalness=.26;mat.envMapIntensity=.8;mat.needsUpdate=true;}if(mat.map===view.tex.asphalt){mat.roughness=.39;mat.metalness=.28;}}});
 // Irregular wet patches catch the environment in the street without expensive screen-space reflections.
 const random=rng(1287),wet=new T.MeshStandardMaterial({color:0x263d49,roughness:.12,metalness:.57,transparent:true,opacity:.34,depthWrite:false,polygonOffset:true,polygonOffsetFactor:-1});
 for(let i=0;i<34;i++){const road=ROADS[i%7],along=-460+random()*920,shape=new T.Shape(),radius=1.2+random()*2.5;for(let j=0;j<=16;j++){const a=j/16*Math.PI*2,r=radius*(.72+hash(j,i)*.4),x=Math.cos(a)*r,y=Math.sin(a)*r*.42;if(!j)shape.moveTo(x,y);else shape.lineTo(x,y);}const m=new T.Mesh(new T.ShapeGeometry(shape),wet);m.rotation.x=-Math.PI/2;m.position.set(i%2?road+7:along,.028,i%2?along:road-7);scene.add(m);}
 // Street-level service signage and a small garage forecourt identify the starting district.
 const canvas=document.createElement('canvas');canvas.width=1024;canvas.height=256;const ctx=canvas.getContext('2d');ctx.fillStyle='#0b202b';ctx.fillRect(0,0,1024,256);ctx.strokeStyle='#d5b579';ctx.lineWidth=5;ctx.strokeRect(10,10,1004,236);ctx.fillStyle='#e9d7b1';ctx.textAlign='center';ctx.font='bold 92px sans-serif';ctx.fillText('SOUTHSIDE',512,117);ctx.font='30px sans-serif';ctx.fillText('G A R A G E  /  R E P A I R  &  T U N I N G',512,181);const tx=new T.CanvasTexture(canvas);tx.colorSpace=T.SRGBColorSpace;const signMat=new T.MeshStandardMaterial({map:tx,emissiveMap:tx,emissive:0xffd399,emissiveIntensity:.6,roughness:.6,side:T.DoubleSide}),sign=new T.Mesh(new T.PlaneGeometry(11.8,2.95),signMat);sign.position.set(-305,4.2,436);sign.rotation.y=Math.PI/2;scene.add(sign);const poleMat=new T.MeshStandardMaterial({color:0x28343a,roughness:.7,metalness:.5});for(const z of [430.5,441.5]){const pole=new T.Mesh(new T.CylinderGeometry(.07,.07,5.8,8),poleMat);pole.position.set(-305,2.9,z);scene.add(pole);}
 // Rounded crowns retain a small vertex budget while avoiding large flat faceted silhouettes.
 scene.traverse(m=>{if(m.isInstancedMesh&&m.geometry.type==='IcosahedronGeometry'){const old=m.geometry;m.geometry=new T.SphereGeometry(1,12,9);old.dispose();m.computeBoundingSphere();}});
}
