import * as C from './core.mjs';
import {CityView} from './world.mjs';
import {enrichCity} from './atmosphere.mjs';
import {Room,invitation} from './net.mjs';
const $=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const touch=matchMedia('(pointer:coarse)').matches||navigator.maxTouchPoints>0;
if(touch)document.body.classList.add('touch');
const readLocal=key=>{try{return JSON.parse(localStorage.getItem(key)||'null');}catch{return null;}};
const setLocal=(key,v)=>{try{localStorage.setItem(key,JSON.stringify(v));return true;}catch{return false;}};
let saved=readLocal(C.SAVE_KEY),settings={quality:touch?'low':'high',sound:true,rain:false,...(readLocal('bayline.settings.v1')||{})};
settings.quality=['low','medium','high'].includes(settings.quality)?settings.quality:'medium';
let state=C.newGame(saved),view,running=false,mode='solo',localId=0,inviteText='',onlineText='SOLO / ログイン不要',peerInput={},peerAt=0,frameAt=0,networkAccumulator=0,sendAccumulator=0,saveAccumulator=0,uiAccumulator=0,accumulator=0,lastTime=0,toastUntil=0,lastMessage=-1,lastHP=100,lastAudioEvent=0,waypoint=null,currentPanel='',slowTime=0;
const cam={yaw:Math.PI,pitch:.22},keys=new Set(),stick={x:0,y:0},held={fire:false,interact:false,boost:false},command={seq:0,action:'',choice:0};
let looking=false,lookAt=0,lastPointer=null;
class CityAudio{
 constructor(){this.context=null;this.muted=false;this.nextBeat=0;this.beat=0;}
 start(){if(!this.context){try{const A=window.AudioContext||window.webkitAudioContext;if(!A)return;const a=this.context=new A(),master=this.master=a.createGain();master.gain.value=settings.sound?.14:0;master.connect(a.destination);this.motor=a.createOscillator();this.motor.type='sawtooth';this.motorGain=a.createGain();this.motorGain.gain.value=0;const filter=a.createBiquadFilter();filter.type='lowpass';filter.frequency.value=180;this.motor.connect(filter);filter.connect(this.motorGain);this.motorGain.connect(master);this.motor.start();const data=new Float32Array(a.sampleRate);for(let i=0;i<data.length;i++)data[i]=Math.random()*2-1;this.noise=a.createBuffer(1,data.length,a.sampleRate);this.noise.copyToChannel(data,0);}catch{return;}}this.context?.resume().catch(()=>{});}
 setSound(value){settings.sound=!!value;if(this.context)this.master.gain.setTargetAtTime(settings.sound?.14:0,this.context.currentTime,.1);}
 tone(freq,duration=.22,vol=.22,type='sine'){const a=this.context;if(!a||a.state!=='running'||!settings.sound)return;const o=a.createOscillator(),g=a.createGain(),t=a.currentTime;o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(vol,t+.015);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g);g.connect(this.master);o.start(t);o.stop(t+duration+.02);o.onended=()=>{o.disconnect();g.disconnect();};}
 hit(kind){const a=this.context;if(!a||!settings.sound)return;if(kind==='success'||kind==='checkpoint'){this.tone(523,.2,.35);setTimeout(()=>this.tone(784,.3,.22),120);return;}if(!['shot','enemyshot','crash'].includes(kind))return;const n=a.createBufferSource(),g=a.createGain(),f=a.createBiquadFilter(),t=a.currentTime;n.buffer=this.noise;f.type='lowpass';f.frequency.value=kind==='crash'?450:1600;g.gain.setValueAtTime(kind==='shot'?.48:.22,t);g.gain.exponentialRampToValueAtTime(.001,t+.13);n.connect(f);f.connect(g);g.connect(this.master);n.start(t);n.stop(t+.15);n.onended=()=>{n.disconnect();f.disconnect();g.disconnect();};}
 update(s,p){if(!this.context)return;const a=this.context,car=s.cars[p?.car];this.motor.frequency.setTargetAtTime(car?32+Math.abs(car.speed)*4:30,a.currentTime,.08);this.motorGain.gain.setTargetAtTime(car?.17:0,a.currentTime,.12);if(running&&a.currentTime>this.nextBeat&&settings.sound){this.nextBeat=a.currentTime+.48;const progression=[110,110,130.81,146.83,110,164.81,130.81,98],note=progression[Math.floor(this.beat/8)%8];if(this.beat%2===0)this.tone(note,.37,.07,'triangle');if(this.beat%4===0)this.tone(note*4,.6,.026);this.beat++;}for(const e of s.events||[])if(e.id>lastAudioEvent){lastAudioEvent=e.id;if(C.distance(e,p)<80)this.hit(e.type);}}
}
const audio=new CityAudio();
const room=new Room(window.SUPABASE_CONFIG,onPacket,onNetworkStatus);
function onNetworkStatus(info){onlineText=info.text;$('onlineStatus').textContent=onlineText;$('frontStatus').textContent=['error','full','missing','ended'].includes(info.kind)?info.text:'';const line=$('roomStatus');if(line)line.textContent=info.text;if(['error','full','missing','ended'].includes(info.kind))showToast(info.text,10);if(info.kind==='ended'&&mode==='guest')openPanel('coop');}
function onPacket(p){
 if(mode==='host'){
  if(p.type==='admit'){if(state.players.length>1)C.removeGuest(state);C.addPlayer(state);peerInput={};peerAt=performance.now();room.send('state',{frame:C.snapshot(state)});showToast('相棒が合流しました。同じ車への同乗と、E長押しでの救助ができます。',9);}
  if(p.type==='input'){peerInput=C.cleanInput(p.input);peerAt=performance.now();}
  if(p.type==='left'){C.removeGuest(state);peerInput={};}
 }else if(mode==='guest'&&p.type==='state'){
  const next=C.readSnapshot(p.frame);if(!next)return;state=next;frameAt=performance.now();if(!running){enterWorld(false);cam.yaw=state.players[1]?.yaw||Math.PI;showToast('相棒の街に参加しました。ミッションと車両はホストの街で共有されます。',9);}
 }
}
function showToast(text,seconds=7){$('toast').textContent=text;$('toast').classList.add('show');toastUntil=performance.now()+seconds*1000;}
function persist(){if(mode==='guest'||!running)return;saved=C.saveGame(state);const ok=setLocal(C.SAVE_KEY,saved);$('saveStatus').textContent=ok?'自動保存済み':'保存できません：ブラウザの保存設定を確認してください';if(ok)setTimeout(()=>{$('saveStatus').textContent='';},1800);}
function action(name,choice=0){if(mode==='guest'&&['start','retry','job','race','cancel','engine','armor'].includes(name)){showToast('仕事の選択と共有アップグレードはホストが操作します。');return;}command.seq++;command.action=name;command.choice=choice;if(mode==='guest')room.send('input',{input:readInput()});}
function clearInput(){keys.clear();stick.x=stick.y=0;held.fire=held.interact=held.boost=false;looking=false;lastPointer=null;$('stickKnob').style.transform='';}
function readInput(){
 if(!running||$('panel').open)return{seq:command.seq,yaw:cam.yaw};
 const p=state.players[localId]||state.players[0];
 const x=C.clamp((keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0)+stick.x,-1,1),y=C.clamp((keys.has('KeyW')||keys.has('ArrowUp')?1:0)-(keys.has('KeyS')||keys.has('ArrowDown')?1:0)+stick.y,-1,1);
 return C.cleanInput({x,y,yaw:cam.yaw,run:held.boost||keys.has('ShiftLeft')||keys.has('ShiftRight'),fire:held.fire||(p.car<0&&keys.has('Space')),brake:keys.has('Space')||held.boost,interact:held.interact||keys.has('KeyE'),...command});
}
function enterWorld(reset){if(reset){state=C.newGame(saved);view.lastEvent=0;lastAudioEvent=0;}running=true;$('front').classList.add('hidden');$('hud').classList.remove('hidden');$('touch').classList.toggle('hidden',!touch);closePanel();audio.start();cam.yaw=state.players[localId]?.yaw||Math.PI;view.cameraReady=false;lastMessage=-1;accumulator=0;lastHP=state.players[localId]?.hp||100;}
function solo(fresh=false){room.close();mode='solo';localId=0;onlineText='SOLO / ログイン不要';if(fresh){saved=null;try{localStorage.removeItem(C.SAVE_KEY);}catch{}}enterWorld(true);if(!state.active)openPanel('jobs');}
function host(){persist();room.close();mode='host';localId=0;enterWorld(true);try{const code=room.create(),url=new URL('./',location.href);url.search='';url.hash='join='+code;inviteText=url.href;openPanel('coop');}catch(e){showToast(e.message,9);mode='solo';onlineText='SOLO / 通信を開始できませんでした';}}
function join(text){const invite=invitation(text);if(!invite){$('frontStatus').textContent='招待リンクをそのまま貼り付けてください。';showToast('招待リンクを読み取れません。コピーしたリンクを確認してください。');return;}persist();room.close();mode='guest';localId=1;running=false;$('front').classList.remove('hidden');$('hud').classList.add('hidden');$('touch').classList.add('hidden');closePanel();$('frontStatus').textContent='相棒の街へ接続しています…';audio.start();try{room.join(`${invite.code}.${invite.host}`);}catch(e){$('frontStatus').textContent=e.message;mode='solo';localId=0;}}
function leaveRoom(){room.close();mode='solo';localId=0;onlineText='SOLO / ログイン不要';saved=readLocal(C.SAVE_KEY);enterWorld(true);showToast('自分のソロセーブに戻りました。');}
function closePanel(){if($('panel').open)$('panel').close();currentPanel='';clearInput();}
function panelShell(title){$('panelTitle').textContent=title;clearInput();if(!$('panel').open)$('panel').showModal();}
function openPanel(type){currentPanel=type;const s=state,ch=C.CHAPTERS[s.chapter],step=C.currentStep(s),b=$('panelBody');
 if(type==='jobs'){
  panelShell('仕事とストーリー');
  b.innerHTML=`<div class="panel-lead"><div class="eyebrow">${s.complete?'AFTERLIGHT / STORY COMPLETE':esc(ch?.contact||'BAYLINE DISPATCH')}</div><h3>${esc(s.complete?'この街の続きを、自由に。':ch?.name||'BAYLINE')}</h3><p>${esc(s.active?step?.text||'':s.complete?'配達、レース、24個の隠しケース。クリア後も街で自由に遊べます。':ch?.intro||'')}</p><div class="panel-actions">${s.active||s.side?'<button data-act="retry">現在の目標をやり直す</button><button data-act="cancel">仕事を中断</button>':s.complete?'':'<button class="primary" data-act="start">この章を開始 →</button>'}<button data-open="map">街のマップ</button></div>${mode==='guest'?'<p>ストーリーの開始・中断はホストが操作します。現場での運転、戦闘、端末操作は2人で協力できます。</p>':''}</div><h3>12 CHAPTERS</h3><div class="chapter-grid">${C.CHAPTERS.map((c,i)=>`<div class="chapter ${i<s.chapter?'done':i===s.chapter?'current':''}"><b>${i<s.chapter?'✓ ':''}${esc(c.name)}</b><small>${i<s.chapter?'完了':i===s.chapter?'現在の章':'未到達'} / 報酬 $${c.reward.toLocaleString()}</small></div>`).join('')}</div><h3>街の依頼 / 何度でも挑戦</h3><div class="job-list">${C.JOBS.map((j,i)=>`<button data-act="job" data-choice="${i}" ${s.active||s.side?'disabled':''}>${esc(j.name)}<small>${esc(C.POI[j.from].name)} → ${esc(C.POI[j.to].name)}<br>$${j.reward} / ${j.limit}秒</small></button>`).join('')}</div><h3>フリー・レース</h3><div class="job-list">${['サウスサイド・ループ','コースト・エクスプレス','クロスタウン'].map((n,i)=>`<button data-act="race" data-choice="${i}" ${s.active||s.side?'disabled':''}>${n}<small>完走報酬 $900</small></button>`).join('')}</div><h3>ガレージ</h3><p>南のガレージに近づいて購入。エンジンと装甲は各3段階。修理は車両・体力・弾薬を回復します。</p><div class="panel-actions"><button data-act="repair">修理・補給 $100</button><button data-act="engine">エンジン ${s.engine}/3 / $${700*(s.engine+1)}</button><button data-act="armor">装甲 ${s.armor}/3 / $${600*(s.armor+1)}</button></div><p class="privacy-note">ストーリーは約60分を想定した12章構成です。実際の所要時間は運転・探索・難易度で変わり、60分間の実測を保証するものではありません。メインの進行はホスト端末に自動保存します。</p>`;
 }else if(type==='coop'){
  panelShell('2人協力 / ログイン不要');
  b.innerHTML=`<div class="panel-lead"><div class="eyebrow">INVITE YOUR PARTNER</div><h3>${mode==='host'?'招待リンクを相棒へ送る':mode==='guest'?'相棒の街に参加中':'一つの街を、二人で。'}</h3><p id="roomStatus">${esc(onlineText)}</p>${mode==='host'?`<input id="inviteOutput" class="invite-output" readonly value="${esc(inviteText)}" aria-label="招待リンク"><div class="panel-actions"><button id="copyInvite" class="primary">招待リンクをコピー</button><button id="shareInvite">共有する</button></div>`:mode==='solo'?'<div class="panel-actions"><button id="makeRoom" class="primary">協力ルームを作る</button></div><form id="panelJoin"><label>相棒の招待リンク</label><input id="panelJoinCode" class="invite-output" placeholder="招待リンクを貼り付け"><div class="panel-actions"><button type="submit">参加する</button></div></form>':''}</div><h3>同じ車へ同乗</h3><p>一人が運転席へ乗り、もう一人が車に近づいて「乗降」を押すと助手席に乗れます。別々の車でも行動できます。端末は二人で操作すると早くなり、倒れた相棒は近づいて「操作」を3秒長押しすると救助できます。</p><h3>セーブと接続について</h3><p>ログイン・名前・メールアドレスの入力はありません。部屋は2人までで、招待リンクを知る人が参加できます。リンクを不特定多数には公開しないでください。ホストはゲーム画面を開いたままにしてください。ホストが終了すると協力セッションも終了します。</p><p class="privacy-note">接続には既存のSupabase Realtimeを利用します。位置・車両・ゲーム内操作を中継し、個人プロフィールは収集しません。進行データはホストのブラウザ内に保存します。通信障害時はソロへ戻って続けられます。共有したリンクの取り消しは部屋を閉じて新しい部屋を作成してください。</p>${mode!=='solo'?'<div class="panel-actions"><button id="leaveRoom">協力を終了して自分のソロへ戻る</button></div>':''}`;
  $('makeRoom')?.addEventListener('click',host);$('leaveRoom')?.addEventListener('click',leaveRoom);
  $('copyInvite')?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(inviteText);$('copyInvite').textContent='コピーしました';}catch{$('inviteOutput').focus();$('inviteOutput').select();$('roomStatus').textContent='リンクを選択しました。コピーして友だちに送ってください。';}});
  $('shareInvite')?.addEventListener('click',async()=>{if(navigator.share){try{await navigator.share({title:'BAYLINE — 2人協力',text:'一緒に街を走ろう。',url:inviteText});}catch{}}else $('copyInvite').click();});
  $('panelJoin')?.addEventListener('submit',e=>{e.preventDefault();join($('panelJoinCode').value);});
 }else if(type==='map'){
  panelShell('BAYLINE CITY');b.innerHTML=`<div class="map-layout"><div><canvas id="fullMap" width="900" height="900" aria-label="街の全体マップ"></canvas><p class="map-legend">● 金：目標　● 青：相棒　◆：ガレージ<br>クリック / タップ：個人の目的地を設定</p></div><div><div class="eyebrow">CITY DIRECTORY</div><p>${Object.entries(C.POI).map(([id,p])=>`<button class="quiet" data-poi="${id}">${esc(p.name)} ↗</button><br>`).join('')}</p><p>ストーリー ${Math.min(12,s.chapter)}/12章 完了<br>隠しケース ${s.caches.length}/24<br>配達依頼 ${s.jobsDone.length}/6種類</p><button id="clearWaypoint" class="quiet">個人の目的地を消す</button></div></div>`;
  $('fullMap').addEventListener('pointerdown',e=>{const r=e.currentTarget.getBoundingClientRect();waypoint={x:(e.clientX-r.left)/r.width*1120-560,z:(e.clientY-r.top)/r.height*1120-560,name:'個人の目的地'};drawMap($('fullMap'),true);});
  b.querySelectorAll('[data-poi]').forEach(el=>el.onclick=()=>{waypoint={...C.POI[el.dataset.poi]};drawMap($('fullMap'),true);});$('clearWaypoint').onclick=()=>{waypoint=null;drawMap($('fullMap'),true);};drawMap($('fullMap'),true);
 }else{
  panelShell(type==='help'?'操作方法':'設定と操作');
  b.innerHTML=`${type==='settings'?`<div class="setting-row"><span>描画品質<small>高画質：陰影・反射・ブルーム。重い場合は標準または軽量へ。</small></span><select id="quality"><option value="high">高画質</option><option value="medium">標準</option><option value="low">軽量</option></select></div><div class="setting-row"><span>音楽・効果音<small>オリジナルのシンセ音楽とエンジン音</small></span><input id="sound" type="checkbox" ${settings.sound?'checked':''}></div><div class="setting-row"><span>小雨<small>空気感を変える雨の表現</small></span><input id="rain" type="checkbox" ${settings.rain?'checked':''}></div><div class="panel-actions"><button id="fullscreen">全画面にする</button><button data-act="rescue">動けなくなったとき：道路へ復帰</button><button id="backTitle">タイトルへ戻る</button></div>`:''}<h3>PC</h3><div class="controls-grid"><b>W A S D / 矢印</b><span>徒歩移動 / 車の加減速・ハンドル</span><b>右ドラッグ</b><span>カメラを回す。車では少し待つと後方へ戻る</span><b>左クリック</b><span>前方へ射撃（近い敵に照準補助）</span><b>F</b><span>乗車 / 降車 / 同乗</span><b>E 長押し</b><span>端末・アイテム操作 / 相棒の救助</span><b>Shift</b><span>徒歩でダッシュ</span><b>Space</b><span>車のブレーキ / 徒歩で射撃</span><b>R</b><span>リロード</span><b>M / J / Esc</b><span>マップ / 仕事 / 設定</span></div><h3>スマートフォン</h3><p>横画面を推奨。左スティックで移動・運転し、画面右側の空いている場所をドラッグしてカメラを回します。「操作」は押し続けると端末操作や救助が進みます。スティックを上に倒すと車が加速し、下に倒すと減速・後退します。</p><h3>プレイの流れ</h3><p>「仕事」で章を開始 → マップの金色の目標へ移動。端末は車から降りて操作します。車は低速時に乗り降りでき、弾薬はリロードで補充できます。倒れるとガレージから再開。追跡中は視線を切り、指定の隠れ場所で車を降りて静止すると追跡を外せます。</p><p class="privacy-note">ソロ中はこのメニューで一時停止。協力中は相棒のプレイを止めないため世界が進みます。ブラウザの保存データを削除すると進行も消えます。市販GTAと同じ規模・画質ではなく、独自のリアル調3Dで制作したブラウザ向け作品です。</p>`;
  if(type==='settings'){$('quality').value=settings.quality;$('quality').onchange=e=>setQuality(e.target.value);$('sound').onchange=e=>{audio.setSound(e.target.checked);setLocal('bayline.settings.v1',settings);};$('rain').onchange=e=>{settings.rain=e.target.checked;view.setWeather(settings.rain);setLocal('bayline.settings.v1',settings);};$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{showToast('このブラウザでは全画面切り替えを利用できません。');}};$('backTitle').onclick=()=>{persist();room.close();mode='solo';localId=0;running=false;state=C.newGame(readLocal(C.SAVE_KEY));closePanel();$('front').classList.remove('hidden');$('hud').classList.add('hidden');$('touch').classList.add('hidden');onlineText='SOLO / ログイン不要';};}
 }
 b.querySelectorAll('[data-act]').forEach(el=>el.addEventListener('click',()=>{const a=el.dataset.act,n=Number(el.dataset.choice||0);closePanel();action(a,n);}));b.querySelectorAll('[data-open]').forEach(el=>el.addEventListener('click',()=>openPanel(el.dataset.open)));
}
function setQuality(q){settings.quality=q;view?.setQuality(q);$('frontQuality').value=q;setLocal('bayline.settings.v1',settings);slowTime=0;}
const mapBG=document.createElement('canvas');mapBG.width=mapBG.height=1120;{
 const g=mapBG.getContext('2d');g.fillStyle='#132f3d';g.fillRect(0,0,1120,1120);g.fillStyle='#29414a';g.fillRect(30,30,1060,1060);g.strokeStyle='#526169';g.lineWidth=23;for(const r of C.ROADS){g.beginPath();g.moveTo(r+560,22);g.lineTo(r+560,1098);g.stroke();g.beginPath();g.moveTo(22,r+560);g.lineTo(1098,r+560);g.stroke();}g.fillStyle='#334e43';g.fillRect(426,574,132,132);for(const b of C.BUILDINGS){g.fillStyle=b.style===1?'#7e8988':'#667779';g.fillRect(b.x+560-b.w/2,b.z+560-b.d/2,b.w,b.d);}g.strokeStyle='#c2b690';g.lineWidth=2;g.strokeRect(29,29,1062,1062);
}
function drawMap(canvas,full=false){if(!canvas)return;const g=canvas.getContext('2d'),w=canvas.width,h=canvas.height,p=state.players[localId]||state.players[0],span=full?1120:p.car>=0?290:190,cx=full?0:p.x,cz=full?0:p.z,scale=w/span,X=x=>(x-cx)*scale+w/2,Y=z=>(z-cz)*scale+h/2;
 g.clearRect(0,0,w,h);g.fillStyle='#142f3b';g.fillRect(0,0,w,h);g.drawImage(mapBG,X(-560),Y(-560),1120*scale,1120*scale);
 const goal=C.target(state),nav=waypoint||goal;if(nav){const route=C.gps(p,nav);g.strokeStyle=waypoint?'#a5c9d8':'#e9c58a';g.lineWidth=full?5:4;g.beginPath();route.forEach((q,i)=>i?g.lineTo(X(q.x),Y(q.z)):g.moveTo(X(q.x),Y(q.z)));g.stroke();}
 const dot=(q,color,r=full?5:5)=>{g.fillStyle=color;g.beginPath();g.arc(X(q.x),Y(q.z),r,0,Math.PI*2);g.fill();};
 if(full){for(const q of Object.values(C.POI))dot(q,'#c1c8bd',4);for(const c of C.CACHES)if(!state.caches.includes(c.id))dot(c,'#8e916d',2.5);g.fillStyle='#e1d6bc';g.font='16px sans-serif';g.fillText('NORTHSIDE',85,90);g.fillText('DOWNTOWN',450,350);g.fillText('OLD TOWN',100,700);g.fillText('SOUTHSIDE',310,1000);g.fillText('COAST',995,710);}
 for(const e of state.enemies)if(e.hp>0)dot(e,'#ed8b75',full?4:4);if(state.wanted>.5)for(const c of state.cars)if(c.police)dot(c,'#e07576',4);
 if(goal){dot(goal,'#edc488',full?9:8);g.strokeStyle='#ffe3a6';g.lineWidth=2;g.beginPath();g.arc(X(goal.x),Y(goal.z),full?14:13,0,Math.PI*2);g.stroke();}if(waypoint)dot(waypoint,'#a2cfe1',full?7:7);
 for(const u of state.players){g.save();g.translate(X(u.x),Y(u.z));g.rotate(-u.yaw+Math.PI);g.fillStyle=u.id===localId?'#fff0c5':'#78d4f5';g.strokeStyle='#162d38';g.lineWidth=2;g.beginPath();g.moveTo(0,-(full?11:10));g.lineTo(7,7);g.lineTo(0,4);g.lineTo(-7,7);g.closePath();g.fill();g.stroke();g.restore();}
 const garage=C.POI.garage;g.strokeStyle='#dce5d3';g.lineWidth=2;g.strokeRect(X(garage.x)-4,Y(garage.z)-4,8,8);
}
function updateHUD(){const s=state,p=s.players[localId]||s.players[0],ch=C.CHAPTERS[s.chapter],q=C.currentStep(s),goal=C.target(s),car=s.cars[p.car];
 $('cash').textContent='$'+Math.floor(s.cash).toLocaleString();$('wanted').textContent='★'.repeat(Math.ceil(s.wanted))+'☆'.repeat(Math.max(0,5-Math.ceil(s.wanted)));$('healthText').textContent=Math.ceil(p.hp);$('healthBar').style.width=C.clamp(p.hp/(100+s.armor*20)*100,0,100)+'%';const buddy=s.players.find(u=>u.id!==localId);$('partnerHealth').classList.toggle('hidden',!buddy);if(buddy){$('partnerText').textContent=Math.ceil(buddy.hp);$('partnerBar').style.width=C.clamp(buddy.hp/(100+s.armor*20)*100,0,100)+'%';}
 $('onlineStatus').textContent=onlineText;$('missionTag').textContent=s.side?'CITY CONTRACT':s.active?'STORY / '+(s.chapter+1)+' OF 12':s.complete?'AFTERLIGHT / COMPLETE':'FREE ROAM';$('missionTitle').textContent=s.side?s.side.kind==='race'?'ベイライン・レース':C.JOBS[s.side.index].name:s.active?ch.name:s.complete?'この街の、その先へ':'BAYLINE CITY';$('objective').textContent=q?.text||'「仕事」からミッションを選択。街は自由に探索できます。';$('objectiveDistance').textContent=goal?`${Math.round(C.distance(p,goal))} m / ${q.type==='race'?'チェックポイント':C.POI[q.place]?.name||''}`:'';
 let progress='',ratio=0;if(q){if(q.type==='hack'||q.type==='defend'||q.type==='interact'){const n=q.duration||1;ratio=C.clamp(s.progress/n,0,1);progress=`${Math.floor(ratio*100)}%`;}else if(q.type==='combat'){progress='残り '+s.enemies.filter(e=>e.hp>0).length+'人';}else if(q.type==='race'){ratio=s.checkpoint/C.CIRCUITS[q.circuit].length;progress=`${s.checkpoint}/${C.CIRCUITS[q.circuit].length} ・ ${Math.max(0,Math.ceil(q.limit-s.stageTime))}秒`;}else if(q.type==='escape')progress='追跡を外して合流';}
 if(s.side?.kind==='delivery'&&s.side.phase===1)progress='残り '+Math.max(0,Math.ceil(C.JOBS[s.side.index].limit-s.stageTime))+'秒';$('objectiveProgress').textContent=progress;$('missionBar').style.width=ratio*100+'%';
 $('speed').textContent=car?Math.round(Math.abs(car.speed)*3.6):Math.floor(p.moving||0);$('speedUnit').textContent=car?'KM/H':'M/S';$('vehicleLabel').textContent=car?(p.seat===1?'PASSENGER / ':'')+['COUPE / NIGHTFALL','SEDAN / METRO','SUV / HIGHLAND','VAN / CARGO','INTERCEPTOR'][car.type]:'ON FOOT';$('ammo').innerHTML=p.reload>0?'RELOADING':`${p.ammo} <small>/ ∞</small>`;$('vehicleHealth').textContent=car?'車両耐久 '+Math.ceil(car.hp)+'%':'';$('touchBrake').textContent=car?'制動':'ダッシュ';
 const district=p.z>320?'SOUTHSIDE':p.x>320?'COAST / MARINA':p.x<-320?'WEST YARD':p.z<-160?'DOWNTOWN':'OLD TOWN';$('district').textContent=district;
 let prompt='';if(p.hp<=0)prompt=buddy?'ダウン中：相棒が近づいて「操作」長押しで救助':'ガレージへ復帰します…';else if(buddy&&buddy.hp<=0&&C.distance(p,buddy)<4&&p.car<0)prompt=`E / 操作 長押しで相棒を救助 ${Math.round((buddy.revive||0)/3*100)}%`;else if(q&&['interact','hack'].includes(q.type)&&goal&&C.distance(p,goal)<15)prompt=p.car>=0?'F / 乗降：車を降りて端末へ':'E / 操作 を長押し';else if(q?.type==='escape'&&goal&&C.distance(p,goal)<18)prompt=p.car>=0?'車を降りて隠れよう':'ここで静止して追跡を外す';else if(p.car<0&&s.cars.some(c=>c.hp>0&&C.distance(p,c)<9&&Math.abs(c.speed)<12))prompt='F / 乗降：近くの車へ乗る';else if(p.car>=0&&Math.abs(car.speed)<8)prompt=p.seat===1?'助手席：射撃で相棒を援護 / F で降車':'F / 乗降：車を降りる';else if(C.distance(p,C.POI.garage)<28)prompt='「仕事」→ ガレージで修理・アップグレード';$('prompt').textContent=prompt;
 if(s.messageId!==lastMessage){lastMessage=s.messageId;showToast(s.message,9);persist();}if(performance.now()>toastUntil)$('toast').classList.remove('show');if(p.hp<lastHP){$('damage').style.opacity='.7';setTimeout(()=>{$('damage').style.opacity='0';},180);}lastHP=p.hp;drawMap($('minimap'));if(currentPanel==='map')drawMap($('fullMap'),true);
}
function loop(now){const wallDt=(now-(lastTime||now))/1000,dt=Math.min(.12,wallDt);lastTime=now;if(running&&!$('panel').open&&settings.quality!=='low'){if(wallDt>.052)slowTime+=Math.min(wallDt,.2);else slowTime=Math.max(0,slowTime-dt);if(slowTime>7){setQuality(settings.quality==='high'?'medium':'low');showToast('動作を優先して画質を調整しました。設定から変更できます。');}}
 if(running){const input=readInput();if(mode!=='guest'&&!(mode==='solo'&&$('panel').open)){
   accumulator=Math.min(.2,accumulator+dt);let steps=0;while(accumulator>=1/60&&steps++<8){const remote=performance.now()-peerAt<1200?peerInput:{seq:state.players[1]?._seq||0};C.tick(state,[input,remote],1/60);accumulator-=1/60;}
  }else accumulator=0;
  networkAccumulator+=dt;sendAccumulator+=dt;if(mode==='host'&&room.connected&&networkAccumulator>=.125){networkAccumulator=0;room.send('state',{frame:C.snapshot(state)});}if(mode==='guest'&&room.connected&&sendAccumulator>=1/12){sendAccumulator=0;room.send('input',{input});}
  if(mode==='guest'&&frameAt&&now-frameAt>3500)onlineText='相手の画面更新を待っています。ホストの画面を開いてください。';
  const p=state.players[localId]||state.players[0],car=state.cars[p.car];if(car&&!looking&&now-lookAt>1700){cam.yaw+=C.angle(car.yaw-cam.yaw)*(1-Math.exp(-dt*2.4));}
  audio.update(state,p);uiAccumulator+=dt;if(uiAccumulator>.1){updateHUD();uiAccumulator=0;}saveAccumulator+=dt;if(saveAccumulator>12){saveAccumulator=0;persist();}
 }
 try{view.draw(state,localId,dt,cam,!running);}catch(error){console.error('BAYLINE render error',error);showToast('描画に問題が発生しました。画質を軽量にして再読み込みしてください。',30);return;}
 requestAnimationFrame(loop);
}
$('continue').onclick=()=>solo();$('new').onclick=()=>{if(saved&&!confirm('保存済みのソロ進行を消して、新しいゲームを始めますか？'))return;solo(true);};$('host').onclick=host;$('joinForm').onsubmit=e=>{e.preventDefault();join($('joinCode').value);};$('frontHelp').onclick=()=>openPanel('help');$('frontQuality').value=settings.quality;$('frontQuality').onchange=e=>setQuality(e.target.value);$('closePanel').onclick=closePanel;$('panel').addEventListener('cancel',e=>{e.preventDefault();closePanel();});document.querySelectorAll('[data-panel]').forEach(b=>b.onclick=()=>openPanel(b.dataset.panel));
window.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,select'))return;if(e.code==='Escape'){if(running&&!$('panel').open)openPanel('settings');return;}if($('panel').open||!running)return;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();keys.add(e.code);if(e.repeat)return;const a={KeyF:'enter',KeyR:'reload'}[e.code];if(a)action(a);if(e.code==='KeyJ')openPanel('jobs');if(e.code==='KeyM')openPanel('map');});
window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',clearInput);document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInput();persist();}});window.addEventListener('pagehide',()=>{persist();room.close();});
$('scene').addEventListener('contextmenu',e=>e.preventDefault());$('scene').addEventListener('pointerdown',e=>{if(!running||$('panel').open)return;audio.start();if(e.pointerType==='touch'||e.button===2){looking=true;lookAt=performance.now();lastPointer={x:e.clientX,y:e.clientY,id:e.pointerId};e.currentTarget.setPointerCapture(e.pointerId);}else if(e.button===0)held.fire=true;});
$('scene').addEventListener('pointermove',e=>{if(!looking||!lastPointer||lastPointer.id!==e.pointerId)return;cam.yaw=C.angle(cam.yaw-(e.clientX-lastPointer.x)*.006);cam.pitch=C.clamp(cam.pitch+(e.clientY-lastPointer.y)*.004,-.05,.82);lastPointer.x=e.clientX;lastPointer.y=e.clientY;lookAt=performance.now();});
window.addEventListener('pointerup',e=>{if(lastPointer?.id===e.pointerId){looking=false;lastPointer=null;lookAt=performance.now();}if(e.pointerType!=='touch'&&e.button===0)held.fire=false;});$('scene').addEventListener('pointercancel',()=>{looking=false;lastPointer=null;held.fire=false;});
let stickPointer=null;const updateStick=e=>{const r=$('stick').getBoundingClientRect(),rad=r.width*.36,dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),length=Math.max(rad,Math.hypot(dx,dy));stick.x=dx/length;stick.y=-dy/length;$('stickKnob').style.transform=`translate(${stick.x*rad}px,${-stick.y*rad}px)`;};
$('stick').addEventListener('pointerdown',e=>{e.preventDefault();stickPointer=e.pointerId;e.currentTarget.setPointerCapture(e.pointerId);updateStick(e);audio.start();});$('stick').addEventListener('pointermove',e=>{if(e.pointerId===stickPointer)updateStick(e);});for(const type of ['pointerup','pointercancel'])$('stick').addEventListener(type,e=>{if(e.pointerId===stickPointer){stickPointer=null;stick.x=stick.y=0;$('stickKnob').style.transform='';}});
function holdButton(id,key){const b=$(id);b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);held[key]=true;audio.start();});for(const ev of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,()=>held[key]=false);}
holdButton('touchFire','fire');holdButton('touchInteract','interact');holdButton('touchBrake','boost');$('touchEnter').onclick=()=>action('enter');$('touchReload').onclick=()=>action('reload');window.addEventListener('resize',()=>view?.resize());
try{
 await new Promise(resolve=>requestAnimationFrame(resolve));view=new CityView($('scene'),settings.quality);enrichCity(view);view.setWeather(settings.rain);view.draw(state,0,0,cam,true);$('loading').classList.add('hidden');$('front').classList.remove('hidden');$('continue').firstChild.textContent=saved?'続きから街へ入る ':'街へ入る ';$('saveNote').textContent=saved?`保存あり / ${Math.min(12,saved.chapter||0)}章 完了`:'12章 / 約60分を想定 / 自由探索';const inv=invitation(location.hash);if(inv){$('joinCode').value=`${inv.code}.${inv.host}`;$('frontStatus').textContent='招待リンクを受け取りました。「参加」を押すと合流できます。';}
 window.__BAYLINE_READY__=true;
 if(['127.0.0.1','localhost'].includes(location.hostname)&&new URLSearchParams(location.search).has('test'))window.__BAYLINE_TEST__={C,view,room,action,solo,host,join,openPanel,closePanel,get state(){return state;},set state(v){state=v;},get mode(){return mode;},get running(){return running;},get localId(){return localId;},get invite(){return inviteText;},keys,held,cam};
 requestAnimationFrame(loop);
}catch(error){console.error(error);$('loadText').textContent='3D画面を起動できませんでした。ブラウザのハードウェアアクセラレーションを有効にし、最新のChrome / Edge / Safariで再読み込みしてください。';}
