import {games,safeTCGURL,validPage} from './tcg-config.mjs';
const game=document.body.dataset.game,config=games[game],$=id=>document.getElementById(id);
const endpoint='https://dcvtubivtextycifngtk.supabase.co/functions/v1/commons-tcg';
const publicKey='sb_publishable_IcEN-3GgzcLCHiyNLyRiCQ_RpkAhCGI';
const form=$('search-form'),dialog=$('reader-dialog');
let cards=[],page=1,total=0,pageSize=12,generation=0,selected=-1,controller;
const details=new Map(),inflight=new Map();
const node=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
const link=(label,url)=>{const a=node('a','',label);a.href=safeTCGURL(url)||config.source;a.target='_blank';a.rel='noopener noreferrer';return a;};
async function api(params,signal){const r=await fetch(endpoint+'?'+new URLSearchParams({game,...params}),{headers:{apikey:publicKey,'x-region':'ap-southeast-2'},credentials:'omit',signal:signal?AbortSignal.any([signal,AbortSignal.timeout(30000)]):AbortSignal.timeout(30000)});let data;try{data=await r.json();}catch{throw Error('応答を読み取れませんでした。もう一度お試しください。');}if(!r.ok)throw Error(data.error||'カード情報を取得できませんでした。');return data;}
function updateURL(){const u=new URL(location.href);u.search='';for(const [k,v] of new FormData(form))if(v)u.searchParams.set(k,v);if(page>1)u.searchParams.set('page',page);history.replaceState(null,'',u.pathname+u.search);}
function textBlock(parent,label,text,cls='effect'){if(!text)return;parent.append(node('p','text-label',label),node(cls==='flavor'?'blockquote':'p',cls,text));}
function cardText(parent,c){parent.append(node('h2','',c.name||c.id),node('p','metadata',[c.number||c.id,c.rarity,c.type].filter(Boolean).join(' · ')));if(c.set)parent.append(node('p','metadata',c.set));if(c.stats)parent.append(node('p','metadata',c.stats));textBlock(parent,'フレーバー・説明',c.flavor,'flavor');textBlock(parent,'ワザ・能力・効果',c.effect);if(c.detailLoaded&&!c.flavor&&!c.effect)parent.append(node('p','empty-flavor','掲載元に本文の提供がありません。カード画像から確認できます。'));}
function picture(c,index,reader=false){const button=node('button',reader?'tcg-image':'image-button');button.type='button';button.setAttribute('aria-label',c.name+(reader?'の画像表示サイズを切り替え':'の画像と本文を拡大'));const img=node('img');const src=safeTCGURL(c.image);if(src)img.src=src;img.alt=c.name;img.width=252;img.height=352;img.loading=reader?'eager':'lazy';img.decoding='async';const hint=node('span','img-hint',reader?'タップで画像をさらに拡大':'タップで拡大');img.onerror=()=>{img.hidden=true;hint.textContent='画像を取得できません。公式ページで確認できます。';};if(!src){img.hidden=true;hint.textContent='詳細を開いて画像を確認';}button.append(img,hint);button.onclick=()=>reader?button.classList.toggle('reader-image-full'):openReader(index);return button;}
function drawCard(c,index){const article=node('article','card');article.id='tcg-'+index;const inner=node('div','card-inner'),content=node('div','card-content');inner.append(picture(c,index),content);cardText(content,c);if(!c.detailLoaded){const button=node('button','detail-button','本文を読み込む');button.type='button';button.onclick=async()=>{button.disabled=true;button.textContent='本文を読み込んでいます…';try{await hydrate(index); }catch(e){button.disabled=false;button.textContent='再試行';let err=content.querySelector('.page-error');if(!err){err=node('p','page-error');content.append(err);}err.textContent=e.message;}};content.append(button);}const bottom=node('div','card-bottom'),read=node('button','','拡大して読む');read.type='button';read.onclick=()=>openReader(index);bottom.append(link('公式ページ ↗',c.sourceUrl),read);article.append(inner,bottom);return article;}
async function getDetail(c){if(c.detailLoaded)return c;if(details.has(c.id))return details.get(c.id);if(!inflight.has(c.id)){const work=api({kind:'detail',id:c.id}).then(d=>{const full={...c,...d,detailLoaded:true};if(details.size>150)details.delete(details.keys().next().value);details.set(c.id,full);return full;}).finally(()=>inflight.delete(c.id));inflight.set(c.id,work);}return inflight.get(c.id);}
async function hydrate(index){const c=cards[index],run=generation;const full=await getDetail(c);if(run!==generation||cards[index]?.id!==c.id)return;cards[index]=full;$('tcg-'+index)?.replaceWith(drawCard(full,index));if(dialog.open&&selected===index)drawReader(full,index);}
function drawReader(c,index,error=''){const images=node('div','reader-images'),content=node('div','card-content');images.append(picture(c,index,true));cardText(content,c);content.querySelector('h2').id='reader-title';if(c.artist)content.append(node('p','artist','Illustrator: '+c.artist));if(!c.detailLoaded)content.append(node('p','detail-message',error||'本文を読み込んでいます…'));if(error){const b=node('button','','本文の取得を再試行');b.onclick=()=>openReader(index);content.append(b);}content.append(link('公式のカード情報を開く ↗',c.sourceUrl));$('reader-body').replaceChildren(images,content);$('reader-position').textContent=`${(page-1)*pageSize+index+1} / ${total.toLocaleString()} 件`;$('reader-prev').disabled=index===0;$('reader-next').disabled=index===cards.length-1;}
async function openReader(index){if(!cards[index])return;selected=index;drawReader(cards[index],index);if(!dialog.open)dialog.showModal();dialog.scrollTop=0;try{await hydrate(index);}catch(e){if(selected===index&&dialog.open)drawReader(cards[index],index,e.message);}}
function setCount(data){total=data.total;page=data.page;pageSize=data.pageSize;$('count').replaceChildren(node('strong','',total.toLocaleString('ja-JP')),document.createTextNode('収録版'));$('stamp').textContent=`取得 ${new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(data.fetchedAt))}\n${total?(page-1)*pageSize+1:0}–${Math.min(page*pageSize,total)} 件`;$('page-input').value=page;$('page-input').max=Math.max(1,Math.ceil(total/pageSize));$('page-total').textContent='/ '+Math.max(1,Math.ceil(total/pageSize)).toLocaleString()+' ページ';$('prev').disabled=page<=1;$('next').disabled=page*pageSize>=total;$('pager').hidden=total===0;$('result-source').href=safeTCGURL(data.sourceUrl)||config.source;$('view-note').textContent=data.note||'公式検索の掲載版を表示しています。';$('announcement').textContent=total.toLocaleString()+'件。'+page+'ページ目を表示。';}
async function search(){controller?.abort();controller=new AbortController();const run=++generation;document.body.classList.add('loading');$('results').setAttribute('aria-busy','true');$('search-button').disabled=true;$('error').hidden=true;updateURL();try{const data=await api({kind:'search',...Object.fromEntries(new FormData(form)),page:String(page)},controller.signal);if(run!==generation)return;cards=data.cards.map(c=>details.get(c.id)||c);setCount(data);if(data.effectiveSet){if(![...$('set').options].some(o=>o.value===data.effectiveSet)){const o=node('option','',cards[0]?.set||data.effectiveSet);o.value=data.effectiveSet;$('set').append(o);}$('set').value=data.effectiveSet;}$('results').replaceChildren(...(cards.length?cards.map(drawCard):[node('p','message tcg-empty','条件に合うカードが見つかりませんでした。カード名や収録商品を変えて検索してください。')]));updateURL();let cursor=0;const fill=async()=>{while(cursor<cards.length&&run===generation){const i=cursor++;if(!cards[i].detailLoaded)try{await hydrate(i);}catch{/* Per-card retry preserves usable search results. */}}};void Promise.all([fill(),fill()]);}catch(e){if(run!==generation)return;$('count').textContent='カードを取得できませんでした';$('results').replaceChildren();$('pager').hidden=true;$('error').hidden=false;$('error-text').textContent=e.name==='TimeoutError'?'読み込みに時間がかかっています。もう一度お試しください。':e.message;$('announcement').textContent='取得できませんでした。再試行できます。';}finally{if(run===generation){document.body.classList.remove('loading');$('results').setAttribute('aria-busy','false');$('search-button').disabled=false;}}}
async function loadSets(){try{const data=await api({kind:'sets'});const previous=$('set').value;$('set').replaceChildren(...[{id:'',name:game==='onepiece'?'全商品（キーワード検索）':'すべての収録商品'},...data.sets].map(s=>{const o=node('option','',s.name);o.value=s.id;return o;}));if([...$('set').options].some(o=>o.value===previous))$('set').value=previous;$('set-status').textContent='';}catch{$('set-status').textContent='収録商品を取得できませんでした。カード名検索は利用できます。';}}
const u=new URL(location.href);for(const k of ['q','sort'])if(u.searchParams.has(k))$(k).value=u.searchParams.get(k);const set=u.searchParams.get('set');if(set){const o=node('option','',set);o.value=set;$('set').append(o);$('set').value=set;}page=validPage(u.searchParams.get('page'));if(matchMedia('(min-width:900px)').matches)$('filters').open=true;
form.onsubmit=e=>{e.preventDefault();page=1;search();};$('reset').onclick=()=>{form.reset();$('set').value='';page=1;search();};$('retry').onclick=search;$('prev').onclick=()=>{if(page>1){page--;search();$('result-bar').scrollIntoView();}};$('next').onclick=()=>{if(page*pageSize<total){page++;search();$('result-bar').scrollIntoView();}};$('page-jump').onsubmit=e=>{e.preventDefault();page=Math.min(validPage($('page-input').value),Math.max(1,Math.ceil(total/pageSize)));search();$('result-bar').scrollIntoView();};$('reader-close').onclick=()=>dialog.close();$('reader-prev').onclick=()=>openReader(selected-1);$('reader-next').onclick=()=>openReader(selected+1);dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});dialog.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'&&selected>0)openReader(selected-1);if(e.key==='ArrowRight'&&selected<cards.length-1)openReader(selected+1);});
void loadSets();void search();
