import assert from 'node:assert/strict';
import {GAMES,createGame,tick,action,view} from '../arcade100/engine.mjs';
const make=(id,seed=731)=>{const g=GAMES.find(g=>g.id===id);return createGame(id,Array.from({length:g.minPlayers},(_,i)=>({id:'p'+i,name:'PLAYER '+(i+1)})),seed);};
assert.equal(GAMES.length,100);assert.equal(new Set(GAMES.map(g=>g.id)).size,100);
for(const g of GAMES){const s=make(g.id),replay=make(g.id);assert(g.onlineRequired);for(let t=0;t<180;t++){const input=Object.fromEntries(s.players.map(p=>[p.side,{x:Math.sin(t*.1+p.side),y:Math.cos(t*.13+p.side),primary:t%11===0,aimX:510,aimY:160}]));tick(s,input,.05);tick(replay,input,.05);if(t%9===0){const a={type:'cell',i:t%(s.board?.cells.length||8),choice:t%3,value:2,x:500,y:250};action(s,t%s.players.length,a);action(replay,t%replay.players.length,a);}}assert.deepEqual(s,replay,g.id+' deterministic replay');for(let side=0;side<s.players.length;side++){const v=view(s,side);assert.equal(v.id,g.id);if(g.family==='social')assert(!('answer' in v.data));if([34,47].includes(g.number))assert(!('orders' in v.data));for(const key of ['hands','seed'])assert(!(key in v),g.id+' exposes '+key);for(const key of ['secret','deck','solution','mines','roles','hidden','targets','fleets','bids','impostor'])assert(!(key in v.data),g.id+' exposes '+key);assert(s.players.every(p=>Number.isFinite(p.hp)&&Number.isFinite(p.x)&&Number.isFinite(p.y)),g.id+' invalid actor');}if(s.phase==='playing'){s.duration=s.t+.001;tick(s,{},.02);}assert.equal(s.phase,'over',g.id+' deadline');assert(s.result?.reason,g.id+' result');}
let s=make('g011');const bombCount=s.objects.length;action(s,0,{type:'primary'});assert(s.objects.length>bombCount);assert(s.objects.some(o=>o.kind==='bomb'));for(let i=0;i<70;i++)tick(s,{},.05);assert(s.players[0].lives<3,'bomb blast damages the actor');
s=make('g031');assert.equal(action(s,1,{type:'cell',i:8}),false,'reject wrong turn');assert(action(s,0,{type:'cell',i:9}));assert.equal(s.board.cells[15],1,'reversi flips enclosed stone');
s=make('g032');for(const i of [0,1,0,1,0,1,0])assert(action(s,s.turn,{type:'cell',i}));assert.equal(s.result.winner,0,'connect four vertical win');
s=make('g037');const positions=[...s.data.fleets[1]];for(const i of positions){s.turn=0;assert(action(s,0,{type:'cell',i}));}assert.equal(s.result.winner,0,'hidden fleet destroyed');assert(!('fleets' in view(s,1).data));
s=make('g043');while(s.phase==='playing'){const cards=s.hands.flatMap((h,side)=>h.map((c,i)=>({side,i,rank:c.rank}))).sort((a,b)=>a.rank-b.rank);const c=cards[0];assert(action(s,c.side,{type:'card',i:c.i}));}assert.equal(s.result.winner,'team','cooperative ordered numbers');
s=make('g073');const safe=s.board.cells.flatMap((_,i)=>s.data.mines.includes(i)?[]:[i]);for(const i of safe)if(s.phase==='playing'&&s.board.cells[i]<0)action(s,0,{type:'cell',i});assert.equal(s.result.winner,'team','minefield can be cleared');
s=make('g075');for(const [k,m] of s.data.mirrors.entries())if(m.rot!==0)action(s,k%s.players.length,{type:'cell',i:m.i});tick(s,{},.05);assert.equal(s.result.winner,'team','mirror path reaches receiver');
s=make('g098');for(const station of s.data.solution)action(s,0,{type:'cell',i:station-1});action(s,1,{type:'confirm'});assert.equal(s.result.winner,'team','shared train clues resolve');
s=make('g042');assert(action(s,0,{type:'bid',value:5}));assert(!('bids' in view(s,1).data));assert.equal(action(s,0,{type:'bid',value:10}),false,'one sealed bid per round');
console.log('PASS: 100 deterministic games, private projections, deadlines; bomb, reversi, connect-four, fleet, number relay, mines, mirrors, train clues and sealed bidding');
