import {chromium} from 'playwright';
import {mkdir,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const root=process.env.BAYLINE_BASE_URL||'http://127.0.0.1:4173/';
const url=new URL('bayline/?test=1',root).href,dir='test-output/bayline';await mkdir(dir,{recursive:true});
const report={url,started:new Date().toISOString(),errors:[],checks:[],network:[],sockets:[],render:[]};
const browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist','--disable-background-timer-throttling','--disable-renderer-backgrounding','--disable-backgrounding-occluded-windows']});
const contexts=[];
async function pageFor(options={}){
 const context=await browser.newContext({viewport:{width:1024,height:700},...options});contexts.push(context);
 await context.addInitScript(()=>{try{localStorage.setItem('bayline.settings.v1',JSON.stringify({quality:'low',sound:false,rain:false}));}catch{}});
 const p=await context.newPage();p.setDefaultTimeout(90000);p.on('pageerror',e=>report.errors.push(String(e)));p.on('console',m=>{if(m.type()==='error')report.errors.push(m.text().slice(0,1000));});p.on('response',r=>{if(r.status()>=400)report.network.push({url:r.url(),status:r.status()});});p.on('websocket',ws=>{ws.on('framereceived',e=>{try{const m=JSON.parse(String(e.payload));if(m.event==='phx_reply'||m.event==='system')report.sockets.push({event:m.event,payload:m.payload});}catch{}});ws.on('socketerror',e=>report.sockets.push({error:String(e)}));});return p;
}
const until=(p,fn,arg)=>p.waitForFunction(fn,arg,{polling:100,timeout:120000});
async function load(p){await p.goto(url,{waitUntil:'networkidle'});await until(p,()=>window.__BAYLINE_READY__===true);}
let host,guest,mobile;
try{
 host=await pageFor();await load(host);await host.screenshot({path:dir+'/01-title.png'});report.checks.push('3D scene initializes in the supported lightweight quality preset');
 await host.click('#continue');await host.click('[data-act="start"]');await until(host,()=>window.__BAYLINE_TEST__.state.active);await host.screenshot({path:dir+'/02-on-foot.png'});report.checks.push('Japanese mission UI starts chapter one');
 await host.keyboard.press('KeyF');await until(host,()=>window.__BAYLINE_TEST__.state.players[0].car>=0);const z=await host.evaluate(()=>window.__BAYLINE_TEST__.state.players[0].z);await host.keyboard.down('KeyW');await until(host,z=>window.__BAYLINE_TEST__.state.players[0].z<z-5,z);await host.keyboard.up('KeyW');await host.screenshot({path:dir+'/03-driving.png'});report.checks.push('Vehicle entry and sustained real keyboard driving move the player more than five metres');
 await host.keyboard.press('KeyM');await host.waitForSelector('#fullMap');await host.screenshot({path:dir+'/04-map.png'});await host.click('#closePanel');report.checks.push('World map opens and closes');report.render.push(await host.evaluate(()=>window.__BAYLINE_TEST__.view.stats()));
 await host.evaluate(()=>window.__BAYLINE_TEST__.host());await until(host,()=>window.__BAYLINE_TEST__.room.joined);const invite=await host.evaluate(()=>window.__BAYLINE_TEST__.invite);assert.ok(invite.includes('#join='));await host.click('#closePanel');
 guest=await pageFor({viewport:{width:900,height:600}});await load(guest);await guest.fill('#joinCode',invite);await guest.click('#joinForm button');await until(guest,()=>window.__BAYLINE_TEST__.mode==='guest'&&window.__BAYLINE_TEST__.running&&window.__BAYLINE_TEST__.state.players.length===2);await until(host,()=>window.__BAYLINE_TEST__.state.players.length===2);report.checks.push('Two independent browsers connect through the real Supabase Realtime service without login');
 const before=await host.evaluate(()=>window.__BAYLINE_TEST__.state.players[1].z);await guest.keyboard.down('KeyW');await until(host,z=>Math.abs(window.__BAYLINE_TEST__.state.players[1].z-z)>3,before);await guest.keyboard.up('KeyW');report.checks.push('Guest keyboard movement is simulated on the host and replicated back');
 await host.evaluate(()=>{const s=window.__BAYLINE_TEST__.state,c=s.cars[0];c.x=-315;c.z=430;c.speed=0;c.driver=-1;c.passenger=-1;for(const p of s.players){p.car=-1;p.seat=-1;p.x=-310;p.z=430+p.id;}});await host.keyboard.press('KeyF');await until(host,()=>window.__BAYLINE_TEST__.state.players[0].car===0);await until(guest,()=>window.__BAYLINE_TEST__.state.players[0].car===0);await guest.keyboard.press('KeyF');await until(host,()=>window.__BAYLINE_TEST__.state.players[1].car===0&&window.__BAYLINE_TEST__.state.players[1].seat===1);await until(guest,()=>window.__BAYLINE_TEST__.state.players[1].seat===1);await guest.screenshot({path:dir+'/05-coop-passenger.png'});report.checks.push('Both browsers ride the same vehicle with distinct driver and passenger seats');
 const third=await pageFor({viewport:{width:700,height:500}});await load(third);await third.fill('#joinCode',invite);await third.click('#joinForm button');await until(third,()=>document.getElementById('frontStatus').textContent.includes('2人でプレイ中'));assert.equal(await host.evaluate(()=>window.__BAYLINE_TEST__.state.players.length),2);report.checks.push('A third player is rejected while the two-player room is full');await third.context().close();
 await host.evaluate(()=>window.__BAYLINE_TEST__.room.close());await until(guest,()=>document.getElementById('onlineStatus').textContent.includes('閉じ')||document.getElementById('roomStatus')?.textContent.includes('閉じ'));report.checks.push('Host exit is communicated to the guest');await guest.context().close();
 await host.evaluate(()=>{const h=window.__BAYLINE_TEST__,s=h.state;s.active=true;s.chapter=1;s.stage=2;s.started=true;s.wanted=0;s.enemies=[{id:'browser-combat-fixture',x:480,z:425,yaw:Math.PI,hp:70,shot:50,moving:0}];s.cars[0].driver=-1;s.players=s.players.slice(0,1);Object.assign(s.players[0],{x:480,z:400,yaw:0,car:-1,seat:-1,hp:100,ammo:30});h.cam.yaw=0;});await host.mouse.move(512,350);await host.mouse.down();await until(host,()=>window.__BAYLINE_TEST__.state.kills>=1);await host.mouse.up();await host.screenshot({path:dir+'/06-combat.png'});report.checks.push('Mouse firing damages and defeats a hostile through the normal simulation');await host.context().close();
 mobile=await pageFor({viewport:{width:844,height:390},isMobile:true,hasTouch:true,deviceScaleFactor:1});await load(mobile);await mobile.screenshot({path:dir+'/07-mobile-title.png'});await mobile.click('#continue');await mobile.click('#closePanel');await mobile.waitForSelector('#touch:not(.hidden)');await mobile.screenshot({path:dir+'/08-mobile-play.png'});const bounds=await mobile.evaluate(()=>{const r=document.getElementById('touchFire').getBoundingClientRect();return{x:r.x,y:r.y,r:r.right,b:r.bottom,w:innerWidth,h:innerHeight};});assert.ok(bounds.x>=0&&bounds.y>=0&&bounds.r<=bounds.w&&bounds.b<=bounds.h);report.checks.push('Landscape mobile controls render inside the viewport');await mobile.tap('#touchEnter');await until(mobile,()=>window.__BAYLINE_TEST__.state.players[0].car>=0);report.checks.push('Real touch input enters a vehicle');report.render.push(await mobile.evaluate(()=>window.__BAYLINE_TEST__.view.stats()));await mobile.setViewportSize({width:390,height:844});await mobile.screenshot({path:dir+'/09-mobile-portrait.png'});
 assert.equal(report.errors.length,0,report.errors.join('\n'));
}catch(error){report.failure=String(error.stack||error);if(host&&!host.isClosed()){report.host=await host.evaluate(()=>({text:document.getElementById('onlineStatus')?.textContent,room:window.__BAYLINE_TEST__?{joined:window.__BAYLINE_TEST__.room.joined,role:window.__BAYLINE_TEST__.room.role,connected:window.__BAYLINE_TEST__.room.connected}:null})).catch(()=>null);await host.screenshot({path:dir+'/failure-host.png'}).catch(()=>{});}if(guest&&!guest.isClosed())await guest.screenshot({path:dir+'/failure-guest.png'}).catch(()=>{});process.exitCode=1;
}finally{report.finished=new Date().toISOString();await writeFile(dir+'/browser-results.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));for(const c of contexts)await c.close().catch(()=>{});await browser.close();}
