import {chromium} from 'playwright';
import {mkdir,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const root=process.env.BAYLINE_BASE_URL||'http://127.0.0.1:4173/';
const url=new URL('bayline/?test=1',root).href,dir='test-output/bayline';await mkdir(dir,{recursive:true});
const report={url,started:new Date().toISOString(),errors:[],checks:[],network:[],render:[]};
const browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist']});
const contexts=[];
async function pageFor(options={}){const context=await browser.newContext({viewport:{width:1280,height:800},...options});contexts.push(context);const p=await context.newPage();p.setDefaultTimeout(35000);p.on('pageerror',e=>report.errors.push(String(e)));p.on('console',m=>{if(m.type()==='error')report.errors.push(m.text().slice(0,1000));});p.on('response',r=>{if(r.status()>=400)report.network.push({url:r.url(),status:r.status()});});return p;}
let host,guest,mobile;
try{
 host=await pageFor();await host.goto(url,{waitUntil:'networkidle'});await host.waitForFunction(()=>window.__BAYLINE_READY__===true);await host.screenshot({path:dir+'/01-title.png'});report.checks.push('3D scene initializes without a loading error');
 await host.click('#continue');await host.click('[data-act="start"]');await host.waitForFunction(()=>window.__BAYLINE_TEST__.state.active);await host.waitForTimeout(500);await host.screenshot({path:dir+'/02-on-foot.png'});report.checks.push('Japanese mission UI starts chapter one');
 await host.keyboard.press('KeyF');await host.waitForFunction(()=>window.__BAYLINE_TEST__.state.players[0].car>=0);const z=await host.evaluate(()=>window.__BAYLINE_TEST__.state.players[0].z);await host.keyboard.down('KeyW');await host.waitForTimeout(1500);await host.keyboard.up('KeyW');await host.waitForTimeout(200);const after=await host.evaluate(()=>window.__BAYLINE_TEST__.state.players[0].z);assert.ok(after<z-2);await host.screenshot({path:dir+'/03-driving.png'});report.checks.push('Vehicle entry and actual keyboard driving move the player');
 await host.keyboard.press('KeyM');await host.waitForSelector('#fullMap');await host.screenshot({path:dir+'/04-map.png'});await host.click('#closePanel');report.checks.push('World map opens and closes');
 report.render.push(await host.evaluate(()=>window.__BAYLINE_TEST__.view.stats()));
 await host.evaluate(()=>{const h=window.__BAYLINE_TEST__;h.host();});await host.waitForFunction(()=>window.__BAYLINE_TEST__.room.joined);const invite=await host.evaluate(()=>window.__BAYLINE_TEST__.invite);assert.ok(invite.includes('#join='));await host.click('#closePanel');
 guest=await pageFor({viewport:{width:960,height:640}});await guest.goto(url,{waitUntil:'networkidle'});await guest.waitForFunction(()=>window.__BAYLINE_READY__);await guest.fill('#joinCode',invite);await guest.click('#joinForm button');await guest.waitForFunction(()=>window.__BAYLINE_TEST__.mode==='guest'&&window.__BAYLINE_TEST__.running&&window.__BAYLINE_TEST__.state.players.length===2);await host.waitForFunction(()=>window.__BAYLINE_TEST__.state.players.length===2);report.checks.push('Two independent browsers connect through the real Supabase Realtime service without login');
 const before=await host.evaluate(()=>window.__BAYLINE_TEST__.state.players[1].z);await guest.keyboard.down('KeyW');await guest.waitForTimeout(1300);await guest.keyboard.up('KeyW');await host.waitForTimeout(700);const moved=await host.evaluate(()=>window.__BAYLINE_TEST__.state.players[1].z);assert.ok(Math.abs(moved-before)>2);report.checks.push('Guest keyboard movement is simulated on the host and replicated back');
 await host.evaluate(()=>{const s=window.__BAYLINE_TEST__.state,c=s.cars[0];c.x=-315;c.z=430;c.speed=0;c.driver=-1;c.passenger=-1;for(const p of s.players){p.car=-1;p.seat=-1;p.x=-310;p.z=430+p.id;}});await host.keyboard.press('KeyF');await host.waitForFunction(()=>window.__BAYLINE_TEST__.state.players[0].car===0);await guest.waitForTimeout(500);await guest.keyboard.press('KeyF');await host.waitForFunction(()=>window.__BAYLINE_TEST__.state.players[1].car===0&&window.__BAYLINE_TEST__.state.players[1].seat===1);await guest.waitForFunction(()=>window.__BAYLINE_TEST__.state.players[1].seat===1);await guest.screenshot({path:dir+'/05-coop-passenger.png'});report.checks.push('Both browsers ride the same vehicle with distinct driver and passenger seats');
 const third=await pageFor();await third.goto(url,{waitUntil:'networkidle'});await third.waitForFunction(()=>window.__BAYLINE_READY__);await third.fill('#joinCode',invite);await third.click('#joinForm button');await third.waitForFunction(()=>document.getElementById('frontStatus').textContent.includes('2人でプレイ中'));assert.equal(await host.evaluate(()=>window.__BAYLINE_TEST__.state.players.length),2);report.checks.push('A third player is rejected while the two-player room is full');
 await host.evaluate(()=>window.__BAYLINE_TEST__.room.close());await guest.waitForFunction(()=>document.getElementById('onlineStatus').textContent.includes('閉じ')||document.getElementById('roomStatus')?.textContent.includes('閉じ'));report.checks.push('Host exit is communicated to the guest');
 mobile=await pageFor({viewport:{width:844,height:390},isMobile:true,hasTouch:true,deviceScaleFactor:1});await mobile.goto(url,{waitUntil:'networkidle'});await mobile.waitForFunction(()=>window.__BAYLINE_READY__);await mobile.screenshot({path:dir+'/06-mobile-title.png'});await mobile.click('#continue');await mobile.click('#closePanel');await mobile.waitForSelector('#touch:not(.hidden)');await mobile.screenshot({path:dir+'/07-mobile-play.png'});const bounds=await mobile.evaluate(()=>{const r=document.getElementById('touchFire').getBoundingClientRect();return{x:r.x,y:r.y,r:r.right,b:r.bottom,w:innerWidth,h:innerHeight};});assert.ok(bounds.x>=0&&bounds.y>=0&&bounds.r<=bounds.w&&bounds.b<=bounds.h);report.checks.push('Landscape mobile controls render inside the viewport');report.render.push(await mobile.evaluate(()=>window.__BAYLINE_TEST__.view.stats()));
}catch(error){report.failure=String(error.stack||error);if(host)await host.screenshot({path:dir+'/failure-host.png'}).catch(()=>{});if(guest)await guest.screenshot({path:dir+'/failure-guest.png'}).catch(()=>{});process.exitCode=1;
}finally{report.finished=new Date().toISOString();await writeFile(dir+'/browser-results.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));for(const c of contexts)await c.close();await browser.close();}
