import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_PACKAGE||'playwright');
const base=(process.env.CONSTITUTION_BASE_URL||'http://127.0.0.1:4178').replace(/\/$/,'');
const data=JSON.parse(await readFile(new URL('../commons/constitution/content.json',import.meta.url),'utf8'));
const nodes=[],topics=[];
function walk(n,depth=1){nodes.push({...n,depth});if(n.children?.length)n.children.forEach(c=>walk(c,depth+1));else topics.push(n)}walk(data.root);
assert.equal(new Set(nodes.map(n=>n.id)).size,nodes.length,'Unique stable topic IDs');
assert(topics.length>=200,'Coverage includes at least 200 substantive topics');
assert(Math.max(...nodes.map(n=>n.depth))>=5,'Knowledge is deeply hierarchical');
for(const n of topics){for(const k of ['rule','short','essay','pitfalls','check','sources'])assert(n[k],`${n.id}: ${k}`);assert(n.rule.length>=100,`${n.id}: substantive explanation`);assert(n.short.length>=2&&n.essay.length>=2);assert(n.check.q&&n.check.a);for(const s of n.sources)assert.equal(new URL(s.url).protocol,'https:')}
const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE}:{}),args:['--no-sandbox','--disable-dev-shm-usage']});
const errors=[];
const page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('pageerror',e=>errors.push(e.message));
await page.goto(base+'/commons/constitution/');await page.waitForFunction(()=>window.__CONSTITUTION__?.topics>=200);
assert.equal(await page.locator('.map-node').count(),5,'Root and four main branches');
await page.locator('[data-toggle="rights-group"]').click();assert(await page.locator('.map-node').count()>5,'Branch expansion');
await page.locator('#collapse').click();assert.equal(await page.locator('.map-node').count(),5);
const word='政教';await page.fill('#search',word);assert(await page.locator('.result').count()>0,'Cross-chapter text search');
await page.locator('.result').first().click();assert(await page.locator('#detail').textContent().then(t=>t.includes('論文で使う')));
await page.click('[data-mode="short"]');assert.equal(await page.locator('#detail h3').filter({hasText:'論文で使う'}).count(),0);
await page.click('[data-mode="essay"]');assert.equal(await page.locator('#detail h3').filter({hasText:'短答で押さえる'}).count(),0);
await page.click('[data-mode="all"]');await page.click('#recall-answer summary');await page.click('#mark-known');
assert.equal(await page.locator('#mark-known').getAttribute('aria-pressed'),'true');const selectedHash=new URL(page.url()).hash;
await page.reload();await page.waitForSelector('#mark-known');assert.equal(await page.locator('#mark-known').getAttribute('aria-pressed'),'true','Progress survives reload');
await page.click('#unlearned');assert.equal(await page.locator(`.result[data-select="${decodeURIComponent(selectedHash.slice(1))}"]`).count(),0,'Mastered topic excluded');
await page.click('[data-chapter="constitution"]');await page.click('#view-tree');await page.click('#expand');assert.equal(await page.locator('.outline-select').count(),nodes.length,'All hierarchy nodes accessible');
await page.evaluate(()=>window.dispatchEvent(new Event('beforeprint')));assert.equal(await page.locator('#print-content article').count(),topics.length,'Print includes every topic');
await page.click('#view-map');await page.click('#collapse');await page.screenshot({path:'/workspace/scratch/319bb88ae874/constitution-desktop.png',fullPage:true});
const mobile=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});mobile.on('pageerror',e=>errors.push(e.message));
await mobile.goto(base+'/commons/constitution/');await mobile.waitForFunction(()=>window.__CONSTITUTION__);assert.equal(await mobile.locator('#view-tree').getAttribute('aria-pressed'),'true');
await mobile.selectOption('#chapter-select',data.chapters[0]);await mobile.click('#expand');const first=topics[0];await mobile.locator(`[data-select="${first.id}"]`).first().click();assert(await mobile.locator('#detail h2').textContent().then(t=>t===first.title));
assert(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'No mobile horizontal overflow');
await mobile.screenshot({path:'/workspace/scratch/319bb88ae874/constitution-mobile.png',fullPage:true});
await mobile.locator('[data-back]').click();await mobile.click('#view-map');assert(await mobile.locator('.map-node').count()>1);
const nojs=await browser.newPage({javaScriptEnabled:false});await nojs.goto(base+'/commons/constitution/textbook.html');assert.equal(await nojs.locator('article').count(),topics.length,'Full readable fallback without JS');
await page.goto(base+'/commons/study/');await page.waitForSelector('a[href="/commons/constitution/"]');
await page.goto(base+'/commons/');await page.waitForSelector('a[href="/commons/constitution/"]');
assert.deepEqual(errors,[]);await browser.close();console.log(JSON.stringify({passed:true,topics:topics.length,nodes:nodes.length,chapters:data.chapters.length,desktop:true,mobile:true,search:true,recall:true,print:true,nojs:true,commonsLinks:true}));
