import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
const base=process.env.CYBER_BASE_URL||'http://127.0.0.1:4191/';
const bank=JSON.parse(await readFile('cyber-quiz/bank.json','utf8')),by=new Map(bank.questions.map(q=>[q.id,q]));
await mkdir('test-output/cyber-quiz',{recursive:true});
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});const errors=[];const report={checks:[]};
const context=await browser.newContext({viewport:{width:1366,height:1100}});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
async function open(p){await p.goto(base+'cyber-quiz/');await p.locator('#start').waitFor({state:'visible'});await p.waitForFunction(()=>!document.querySelector('#start').disabled);}
async function correct(p,side){const card=p.locator(`[data-player="${side}"]`),tag=await card.locator('.q-tags').innerText(),id=tag.match(/#([a-z0-9-]+)/)?.[1],q=by.get(id);assert(q,'Known visible question ID');const buttons=card.locator('.answer');for(let n=0;n<await buttons.count();n++){if((await buttons.nth(n).locator('span').nth(1).innerText())===q.choices[q.answer]){await buttons.nth(n).click();return;}}throw Error('Correct option not rendered');}
try{
 await open(page);await page.screenshot({path:'test-output/cyber-quiz/desktop-lobby.png',fullPage:true});await page.locator('#difficulty').selectOption('relaxed');await page.locator('#start').click();
 for(let n=0;n<10;n++){await correct(page,0);await correct(page,1);await page.locator('#result').waitFor({state:'visible'});assert((await page.locator('#result').innerText()).includes('LINK ATTACK')||(await page.locator('#result').innerText()).includes('OVERDRIVE'));if(n===0)await page.screenshot({path:'test-output/cyber-quiz/desktop-battle.png',fullPage:true});await page.locator('[data-next]').click();}
 await page.locator('#summary').waitFor({state:'visible'});assert((await page.locator('#summary').innerText()).includes('作戦成功'));report.checks.push('Local co-op: both players, 10 rounds, links, overdrive and victory');await page.locator('[data-lobby]').click();
 await page.locator('#open-codex').click();await page.locator('#codex-search').fill('XSS');assert((await page.locator('#codex-list').innerText()).includes('XSS'));await page.locator('#close-modal').click();report.checks.push('Learning codex and keyword search');
 const mobile=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});const mp=await mobile.newPage();mp.on('pageerror',e=>errors.push(e.message));await open(mp);assert(await mp.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await mp.screenshot({path:'test-output/cyber-quiz/mobile-lobby.png',fullPage:true});await mp.locator('[data-mode="solo"]').click();await mp.locator('#difficulty').selectOption('relaxed');await mp.locator('#start').click();await correct(mp,0);await mp.locator('#result').waitFor({state:'visible'});assert(await mp.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await mp.screenshot({path:'test-output/cyber-quiz/mobile-battle.png',fullPage:true});report.checks.push('390px touch layout, solo answers, no horizontal overflow');await mobile.close();
 const hc=await browser.newContext(),gc=await browser.newContext(),tc=await browser.newContext();const hp=await hc.newPage(),gp=await gc.newPage(),tp=await tc.newPage();for(const p of[hp,gp,tp]){p.on('pageerror',e=>errors.push(e.message));await open(p);await p.locator('[data-mode="online"]').click();}
 await hp.locator('#difficulty').selectOption('relaxed');await hp.locator('#create-room').click();await hp.locator('#room-code').filter({hasText:/^[A-Z0-9]{6}$/}).waitFor({timeout:30000});const code=await hp.locator('#room-code').innerText();await gp.locator('#room-input').fill(code);await gp.locator('#join-form button').click();await hp.waitForFunction(()=>!document.querySelector('#start').disabled,{timeout:30000});await gp.locator('#room-message').filter({hasText:'合流しました'}).waitFor({timeout:30000});
 await tp.locator('#room-input').fill(code);await tp.locator('#join-form button').click();await tp.locator('#net-error').filter({hasText:'満員'}).waitFor({timeout:30000});
 await hp.locator('#start').click();await gp.locator('#play').waitFor({state:'visible',timeout:15000});assert.equal(await gp.locator('[data-side="0"]').first().isEnabled(),false);assert.equal(await hp.locator('[data-side="1"]').first().isEnabled(),false);await correct(hp,0);await correct(gp,1);await hp.locator('#result').waitFor({state:'visible'});await gp.locator('#result').waitFor({state:'visible'});assert.equal(await hp.locator('#score').innerText(),await gp.locator('#score').innerText());
 await hp.locator('[data-next]').click();await gp.locator('#round-title').filter({hasText:'ROUND 02'}).waitFor();await gp.locator('#pause').click();await hp.locator('#pause').filter({hasText:'再開する'}).waitFor();await gp.locator('#pause').click();await hp.locator('#pause').filter({hasText:'一時停止'}).waitFor();await hp.screenshot({path:'test-output/cyber-quiz/online-host.png',fullPage:true});await gp.screenshot({path:'test-output/cyber-quiz/online-guest.png',fullPage:true});
 await gp.locator('#exit').click();await gp.locator('[data-lobby]').click();await hp.locator('#play-status').filter({hasText:'通信を確認中'}).waitFor({timeout:15000});await hp.locator('#exit').click();await hp.locator('[data-lobby]').click();report.checks.push('Independent online browsers: join, full-room rejection, side-specific controls, shared scores, next round, guest pause/resume and disconnect pause');await hc.close();await gc.close();await tc.close();assert.deepEqual(errors,[]);report.ok=true;
}catch(e){report.ok=false;report.error=String(e.stack||e);report.errors=errors;await page.screenshot({path:'test-output/cyber-quiz/failure.png',fullPage:true}).catch(()=>{});throw e;}finally{await writeFile('test-output/cyber-quiz/report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));await browser.close();}
