import { chromium } from 'playwright';

const root=(process.env.GAME23_BASE_URL||'http://127.0.0.1:4173/').replace(/\/?$/,'/');
const browser=await chromium.launch({headless:true,args:['--ignore-gpu-blocklist','--enable-webgl','--use-angle=swiftshader']});
const context=await browser.newContext({viewport:{width:915,height:412},isMobile:true,hasTouch:true,userAgent:'Mozilla/5.0 (Linux; Android 16; Pixel 10) AppleWebKit/537.36 Chrome/140 Mobile Safari/537.36'});
const page=await context.newPage();
const errors=[];const failed=[];
page.on('pageerror',e=>errors.push(`pageerror: ${e.message}`));
page.on('console',m=>{if(m.type()==='error'&&!/Failed to load resource/i.test(m.text()))errors.push(`console: ${m.text()}`)});
page.on('response',r=>{if(r.status()>=400&&/game23-v4\.(?:js|css)/i.test(r.url()))failed.push(`${r.status()} ${r.url()}`)});
const fail=where=>{const all=[...errors,...failed];if(all.length)throw new Error(`${where}\n${all.join('\n')}`)};
await page.goto(root+'game23.html',{waitUntil:'domcontentloaded',timeout:30000});
await page.waitForFunction(()=>document.querySelector('#v4-start')&&!document.querySelector('#v4-start').disabled,null,{timeout:25000});
const initial=await page.evaluate(()=>({title:document.querySelector('#v4-title')?.textContent||'',chapter:document.querySelector('#v4-chapter')?.textContent||'',canvasW:document.querySelector('#v4-canvas')?.width||0,canvasH:document.querySelector('#v4-canvas')?.height||0,module:[...document.scripts].map(s=>s.src).find(s=>s.includes('game23-v4.js'))||''}));
if(!/BLIGHTED/i.test(initial.title)||!initial.module)throw new Error(`v4 shell missing: ${JSON.stringify(initial)}`);
if(initial.canvasW<10||initial.canvasH<10)throw new Error(`canvas not initialized: ${JSON.stringify(initial)}`);
fail('before start');
await page.locator('#v4-start').tap();
await page.waitForFunction(()=>document.querySelector('#v4-overlay')?.classList.contains('hidden'),null,{timeout:10000});
await page.waitForTimeout(1800);
const started=await page.evaluate(()=>({overlayHidden:document.querySelector('#v4-overlay')?.classList.contains('hidden')||false,chapter:document.querySelector('#v4-chapter')?.textContent||'',ammo:document.querySelector('#v4-ammo')?.textContent||'',hp:document.querySelector('#v4-hpfill')?.style.width||'',canvasW:document.querySelector('#v4-canvas')?.width||0,canvasH:document.querySelector('#v4-canvas')?.height||0}));
if(!started.overlayHidden||!/FALLEN ABBEY/i.test(started.chapter))throw new Error(`v4 did not start: ${JSON.stringify(started)}`);
if(Number(started.ammo)<=0||!started.hp)throw new Error(`HUD not live: ${JSON.stringify(started)}`);
fail('after start');
console.log('GAME23 v4 smoke OK',JSON.stringify({initial,started}));
await browser.close();
