import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {parseAvailability,isFree,inFreePeriod,checkEpisode,verifyBatch,coverage,VERIFIED_FOR,CHECK_LIMIT} from '../supabase/functions/commons-manga/availability.mjs';
import {collectSource,INTERVAL} from '../supabase/functions/commons-manga/core.mjs';
const sources=JSON.parse(await readFile(new URL('../commons/manga/sources.json',import.meta.url)));
const source=sources[0],now=Date.parse('2026-09-15T00:00:00Z'),url=source.website+'episode/9253191256637715958';
const item={url,sourceId:source.id,title:'漫画の第1話',updatedAt:new Date(now-3600000).toISOString(),freeFrom:null,freeUntil:null};
const reader=(overrides={})=>`<script id='episode-json' type='text/json' data-value='${JSON.stringify({readableProduct:{id:'9253191256637715958',typeName:'episode',permalink:url,isPublic:true,hasPurchased:false,pageStructure:{pages:[{type:'main',src:'https://images.invalid/1.jpg'}]},series:{title:'漫画'},...overrides}}).replaceAll('&','&amp;').replaceAll("'",'&apos;').replaceAll('"','&quot;')}'></script>`;
const parsed=parseAvailability(reader(),item,source);
assert.equal(parsed.access,'free');assert.equal(parsed.series,'漫画');assert.equal(Object.hasOwn(parsed,'pageStructure'),false);
assert.equal(parseAvailability(reader({isPublic:false,pageStructure:null}),item,source).access,'restricted');
assert.equal(parseAvailability(reader({hasPurchased:true}),item,source).access,'unknown');
assert.equal(parseAvailability(reader({pageStructure:null}),item,source).access,'unknown');
assert.throws(()=>parseAvailability(reader({permalink:'https://elsewhere.invalid/episode/9253191256637715958'}),item,source));
assert.throws(()=>parseAvailability(reader({id:9253191256637715958}),item,source));
assert.throws(()=>parseAvailability('<html>challenge</html>',item,source));
const free={...item,...parsed,verifiedAt:new Date(now).toISOString()};
assert.equal(isFree(free,now),true);
assert.equal(isFree({...item,freeFrom:new Date(now-60000).toISOString()},now),false,'free-start alone cannot grant access');
assert.equal(isFree(free,now+VERIFIED_FOR),false);
assert.equal(isFree({...free,verifiedAt:new Date(now+3600000).toISOString()},now),false);
assert.equal(isFree({...free,freeUntil:new Date(now).toISOString()},now),false);
assert.equal(inFreePeriod({...free,freeFrom:new Date(now+60000).toISOString()},now),false);
const checked=await checkEpisode(item,source,async(u,o)=>{assert.equal(u,url);assert.equal(o.redirect,'manual');assert.equal(o.credentials,'omit');assert.equal(o.headers.Cookie,undefined);return new Response(reader());},now);
assert.equal(checked.access,'free');assert.equal(checked.verifiedAt,new Date(now).toISOString());
const failed=await checkEpisode(free,source,async()=>new Response(null,{status:302,headers:{location:'https://elsewhere.invalid'}}),now);
assert.equal(isFree(failed,now),false,'failed rechecks revoke old evidence');
const atom=`<feed><entry><title>第1話</title><link href="${url}"/><updated>${item.updatedAt}</updated></entry></feed>`;
const same=await collectSource(source,{},[free],async()=>new Response(atom),now);
assert.equal(same.items[0].access,'free','unchanged feed metadata preserves the reader check');
const changed=await collectSource(source,{},[free],async()=>new Response(atom.replace(item.updatedAt,new Date(now).toISOString())),now);
assert.equal(changed.items[0].access,undefined,'changed publication metadata requires another check');
let requested=0;
const future={...item,verifyAfter:new Date(now+INTERVAL).toISOString()};
assert.deepEqual(await verifyBatch([future],sources,async()=>{requested++;},now),[future]);assert.equal(requested,0);
const many=Array.from({length:80},(_,i)=>({...item,url:source.website+'episode/'+String(i+1)}));
await verifyBatch(many,sources,async()=>{requested++;return new Response('<html>unknown</html>');},now,Date.now()+45000);
assert.equal(requested,CHECK_LIMIT);
requested=0;await verifyBatch(many,sources,async()=>{requested++;},now,Date.now());assert.equal(requested,0,'do not exceed collection lease budget');
assert.deepEqual(coverage([free,{...free,access:'restricted'},item],now),{candidates:3,free:1,restricted:1,pending:1});
console.log('PASS: anonymous public-reader proof, paid/unknown exclusion, six-hour expiry, publication deadlines, URL identity, metadata invalidation, request bounds');
