import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {parseFeed,safeEpisode,collectSource,retryDelay,limitedText,INTERVAL} from '../supabase/functions/commons-manga/core.mjs';
const sources=JSON.parse(await readFile(new URL('../supabase/functions/commons-manga/sources.json',import.meta.url)));
assert.deepEqual(sources,JSON.parse(await readFile(new URL('../commons/manga/sources.json',import.meta.url))));
assert.equal(new Set(sources.map(s=>s.id)).size,sources.length);
assert.equal(sources.length,36);
assert.equal(sources.filter(s=>s.feed).length,13);
assert.ok(sources.every(s=>new URL(s.website).protocol==='https:'&&s.freeNote&&s.kind));
const source=sources[0],now=Date.parse('2026-09-15T01:00:00Z');
const episode=(url,title='第1話',time='2026-09-15T00:00:00Z')=>`<entry><title>${title}</title><link href="${url}"/><link rel="enclosure" href="https://images.invalid/1.jpg"/><updated>${time}</updated><content type="html">作品名</content><author><name>作者</name></author><giga:freeTermStartDate>2026-09-15T00:00:00Z</giga:freeTermStartDate></entry>`;
const valid='https://shonenjumpplus.com/episode/123';
const feed='<feed xmlns="http://www.w3.org/2005/Atom">'+episode(valid+'?tracking=a')+episode(valid)+episode('https://shonenjumpplus.com.evil.invalid/episode/999')+episode('javascript:alert(1)')+episode('https://shonenjumpplus.com/login')+episode(valid+'4','future','2027-01-01T00:00:00Z')+episode(valid+'5','old','2020-01-01T00:00:00Z')+'</feed>';
const parsed=parseFeed(feed,source,now);assert.equal(parsed.items.length,1);assert.equal(parsed.items[0].title,'作品名 / 第1話');assert.equal(parsed.items[0].url,valid);assert.equal(parsed.items[0].freeFrom,'2026-09-15T00:00:00.000Z');
assert.equal(safeEpisode('http://shonenjumpplus.com/episode/123',source),null);assert.equal(safeEpisode('https://a@shonenjumpplus.com/episode/123',source),null);assert.equal(safeEpisode('https://shonenjumpplus.com:99/episode/123',source),null);
assert.throws(()=>parseFeed('<html>Security challenge</html>',source,now));assert.throws(()=>parseFeed('<!DOCTYPE feed [<!ENTITY x SYSTEM "file:///etc/passwd">]><feed></feed>',source,now));assert.throws(()=>parseFeed('<feed><entry>',source,now));
const good=await collectSource(source,{},[],async()=>new Response(feed,{headers:{etag:'"abc"'}}),now);assert.equal(good.source.status,'ok');assert.equal(good.items.length,1);
const failed=await collectSource(source,{...good.source,nextCheckAt:null},good.items,async()=>new Response('no',{status:503}),now+INTERVAL);assert.equal(failed.source.lastSuccessAt,good.source.lastSuccessAt);assert.equal(failed.source.status,'error');assert.equal(failed.items[0].url,valid);assert.equal(failed.source.lastCheckedAt,new Date(now+INTERVAL).toISOString());
let requested=false;await collectSource(source,{nextCheckAt:new Date(now+INTERVAL).toISOString()},[],async()=>{requested=true;},now);assert.equal(requested,false);
const unchanged=await collectSource(source,{...good.source,nextCheckAt:null},good.items,async(url,options)=>{assert.equal(options.headers['If-None-Match'],'"abc"');return new Response(null,{status:304});},now+INTERVAL);assert.equal(unchanged.source.contentFetchedAt,good.source.contentFetchedAt);assert.equal(unchanged.source.lastSuccessAt,new Date(now+INTERVAL).toISOString());
assert.equal(retryDelay(1,'3600',now),3600000);assert.ok(retryDelay(2,null,now)>INTERVAL);await assert.rejects(limitedText(new Response('abcd'),3));
const redirect=await collectSource(source,{},[],async()=>new Response(null,{status:302,headers:{location:'https://evil.invalid/'}}),now);assert.equal(redirect.source.status,'error');assert.match(redirect.source.error,/転送/);
console.log('PASS: 36 source identities, 13 feeds, strict episode URLs, Atom parsing, deduplication, dates, stale preservation, conditional requests, limits and redirect rejection');
