import assert from 'node:assert/strict';
import { mkdir,writeFile } from 'node:fs/promises';
import { chromium } from 'playwright';
import { createTrack } from '../touge/world.js';
import { fresh,step,clamp } from '../touge/physics.mjs';
const base=process.env.TOUGE_BASE_URL||'http://127.0.0.1:4173/';const live=!base.includes('127.0.0.1')&&!base.includes('localhost');
await mkdir('test-output',{recursive:true});const track=createTrack(),report={length:track.length,checks:[]};
let r=fresh();r.v=30;const before=r.v;step(r,1,{brake:1},track);assert(r.v<before-10);report.checks.push('braking');
r=fresh();r.v=30;r.rival=600;for(let i=0;i<90;i++)step(r,1/120,{gas:1,steer:.6,drift:true},track);assert(r.score>0&&Math.abs(r.slip)>.1&&r.contacts===0);report.checks.push('isolated drift and score');
r=fresh();r.v=35;r.x=5.44;step(r,.1,{steer:1},track);assert(r.contacts>0&&r.v<35);report.checks.push('guardrail impact');
r=fresh();r.v=30;r.rival=11;r.x=track.rivalLane(11);step(r,.01,{gas:1},track);assert(r.contacts>0&&r.v<30);report.checks.push('rival collision');
r=fresh();for(let j=0;j<36001&&!r.finished;j++)step(r,1/120,{gas:0},track);assert(r.finished&&r.reason==='time'&&r.t===300);report.checks.push('300-second timeout');
for(const hz of [60,120]){r=fresh();for(let j=0;j<hz*301&&!r.finished;j++){const k=track.at(r.s).k,steer=clamp((k*r.v*r.v*.092*.24+(-2.7-r.x)*2)/(1.5+r.v*.105),-1,1);step(r,1/hz,{gas:1,steer},track);}assert.equal(r.reason,'finish');report['lap'+hz]={time:r.t,contacts:r.contacts,s:r.s};}
assert(Math.abs(report.lap60.time-report.lap120.time)<.15);report.checks.push('full-course finish and frame-rate independence');
const browser=await chromium.launch({headless:true,args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage']});
try{const context=await browser.newContext({viewport:{width:1440,height:900},deviceScaleFactor:1});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('favicon'))errors.push(m.text());});
await page.goto(base+'touge/'+(live?'':'?test=1'),{waitUntil:'networkidle',timeout:120000});await page.waitForFunction(()=>window.__touge?.state==='menu',null,{timeout:120000});await page.screenshot({path:'test-output/01-garage.png'});assert.equal(errors.length,0,errors.join('\n'));report.checks.push('WebGL scene and shaders boot');
await page.locator('#quality').selectOption('balanced');await page.locator('#start-btn').click();if(!live){await page.evaluate(()=>{const t=__touge.test;t.step(3.5,{gas:1});t.set({s:1200,x:-1.5,v:30,rival:1225,rv:30});});}else{await page.waitForFunction(()=>__touge.state==='race',null,{timeout:45000});}
await page.waitForTimeout(1200);await page.screenshot({path:'test-output/02-race.png'});await page.locator('#pause-btn').click();assert.equal(await page.evaluate(()=>__touge.state),'paused');const time=await page.evaluate(()=>__touge.stats.t);await page.waitForTimeout(300);assert.equal(await page.evaluate(()=>__touge.stats.t),time);await page.locator('#resume-btn').click();report.checks.push('pause and resume');
await page.keyboard.press('KeyC');await page.waitForTimeout(500);await page.screenshot({path:'test-output/03-bonnet.png'});await page.keyboard.press('KeyC');await page.keyboard.press('KeyC');
if(!live){await page.evaluate(()=>{const t=__touge.test;t.set({s:__touge.stats.length-1,v:30,rival:__touge.stats.length-15,rivalFinish:null});t.step(.1,{gas:1});});await page.locator('#finish-layer:not(.hidden)').waitFor();assert.match(await page.locator('#finish-title').innerText(),/WIN|FINISH/);await page.screenshot({path:'test-output/04-finish.png'});await page.locator('#retry-btn').click();assert.equal(await page.evaluate(()=>__touge.stats.score),0);assert.equal(await page.evaluate(()=>__touge.state),'count');report.checks.push('finish UI and clean retry');}
assert.equal(errors.length,0,errors.join('\n'));await context.close();const mobile=await browser.newContext({viewport:{width:915,height:412},deviceScaleFactor:1,isMobile:true,hasTouch:true});await mobile.addInitScript(()=>{HTMLElement.prototype.requestFullscreen=()=>Promise.resolve();});const mp=await mobile.newPage();mp.on('pageerror',e=>errors.push(e.message));await mp.goto(base+'touge/'+(live?'':'?test=1'),{waitUntil:'networkidle',timeout:120000});await mp.waitForFunction(()=>window.__touge?.state==='menu',null,{timeout:120000});await mp.locator('#start-btn').scrollIntoViewIfNeeded();assert(await mp.locator('#start-btn').isVisible());await mp.locator('#start-btn').click();if(!live){await mp.evaluate(()=>{__touge.test.step(3.5,{gas:1});__touge.test.set({s:100,v:30,rival:160,x:0});__touge.test.clear();});}await mp.waitForFunction(()=>__touge.state==='race',null,{timeout:45000});
const left=await mp.locator('[data-hold="left"]').boundingBox(),drift=await mp.locator('[data-hold="drift"]').boundingBox();const session=await mobile.newCDPSession(mp);await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:left.x+left.width/2,y:left.y+left.height/2,id:0},{x:drift.x+drift.width/2,y:drift.y+drift.height/2,id:1}]});await mp.waitForTimeout(1300);await mp.screenshot({path:'test-output/05-mobile-drift.png'});if(!live)assert((await mp.evaluate(()=>__touge.stats.score))>0);await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});report.checks.push('landscape touch, scrolling menu and simultaneous steering/drift');await mp.locator('#pause-btn').click();await mp.setViewportSize({width:412,height:915});await mp.screenshot({path:'test-output/06-portrait.png'});assert.equal(errors.length,0,errors.join('\n'));report.checks.push('portrait resize');await mobile.close();report.ok=true;await writeFile('test-output/report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));}finally{await browser.close();}
