import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { parseSearch, parseDetail, parseSets, searchParams, classify, safeURL, validId, japanDate, filterPack } from '../supabase/functions/commons-yugioh/core.mjs';

assert.equal(japanDate(new Date('2026-09-14T15:01:00Z')), '2026-09-15');
assert.equal(classify('ドラゴン族／通常', '光属性'), 'flavor');
assert.equal(classify('ドラゴン族／ペンデュラム／通常', '闇属性'), 'flavor');
assert.equal(classify('ドラゴン族／融合', '光属性'), 'effect');
assert.equal(classify('魔法使い族／効果', '闇属性'), 'effect');
assert.equal(classify('通常', '魔法'), 'effect');
assert.equal(classify('通常', '罠'), 'effect');
assert.equal(validId('../4007'), false);
assert.equal(safeURL('https://www.db.yugioh-card.com.evil.test/yugiohdb/card_search.action'), '');
assert.equal(safeURL('https://user@www.db.yugioh-card.com/yugiohdb/card_search.action'), '');
assert.equal(safeURL('javascript:alert(1)'), '');
assert.equal(safeURL('/yugiohdb/other.action?url=https://evil.test', true), '');
const makeRow = (body = '独自の検証文。&lt;br&gt;次の行。', type = 'ドラゴン族／ペンデュラム／通常') => `<div class="t_row c_normal open"><span class="card_name">テストカード</span><span class="card_ruby">てすと</span><span class="card_info_species_and_other_item"><span>【${type}】</span></span><span class="box_card_attribute"><span>光属性</span></span>${body === null ? '' : `<dd class="box_card_text c_text text_linebreak">${body}</dd>`}<dd class="box_card_text biko text_linebreak">検証用注記</dd><span class="box_card_pen_effect">効果の検証文。</span><input class="link_value" value="/yugiohdb/card_search.action?ope=2&cid=4007"></div><!-- .t_row c_normal -->`;
const wrap = row => `検索結果 1件中 1～1件を表示${row}<script>$('#card_image_0_1').attr('src', '/yugiohdb/get_image.action?type=1&cid=4007&ciid=1&enc=public');</script>`;
const card = parseSearch(wrap(makeRow())).cards[0];
assert.equal(card.text, '独自の検証文。\n次の行。');
assert.equal(card.pendulum, '効果の検証文。');
assert.equal(card.notes, '検証用注記');
assert.equal(card.textKind, 'flavor');
assert.equal(card.images.length, 1);
assert.equal(new URL(card.images[0].url).searchParams.get('type'), '2');
assert.equal(parseSearch(wrap(makeRow(null))).cards[0].textStatus, 'unavailable');
assert.equal(parseSearch(wrap(makeRow('<script>bad()</script>安全'))).cards[0].text, '安全');
assert.throws(() => parseSearch('<h1>Upstream error</h1>'));
assert.throws(() => parseSearch(wrap(makeRow()).replace('1～1件', '1～2件')));
assert.equal(parseSearch(wrap(makeRow()).replace('検索結果 1件中 1～1件を表示', '全1枚'), true).total, 1);
assert.throws(() => parseSearch(wrap(makeRow()).replace('検索結果 1件中 1～1件を表示', '全2枚'), true));
const pack = { cards: Array.from({ length: 23 }, (_, i) => ({ ...card, id: String(i + 1), name: `カード${i}`, text: i % 2 ? '星の話' : '海の話' })) };
assert.equal(filterPack(pack, new URLSearchParams({ type: 'all' }), 3).cards.length, 3);
assert.equal(filterPack(pack, new URLSearchParams({ scope: 'text', q: '海', type: 'normal' })).total, 12);
assert.equal(filterPack(pack, new URLSearchParams({ attribute: 'dark' })).total, 0);
assert.equal(filterPack(pack, new URLSearchParams({ scope: 'name', q: 'カード２２' })).cards[0].id, '23');
assert.equal(parseSearch('<div class="no_data">該当データがありません。</div>').total, 0);
assert.throws(() => parseDetail('<h1>No card</h1>', '4007'));
for (const page of [1, 2, 73, 1428, 10000]) {
  const spec = searchParams(new URLSearchParams({ page, type: 'normal', scope: 'text', q: 'a&pid=123' }), '2026-09-15');
  assert.equal(Number(spec.params.get('page')), page); assert.equal(Number(spec.params.get('rp')), 10);
  assert.equal(spec.params.get('keyword'), 'a&pid=123'); assert.equal(spec.params.get('pid'), null);
  assert.equal(spec.params.get('other'), '0'); assert.equal(spec.params.get('stype'), '2');
  assert.equal(spec.params.get('releaseYEnd'), '2026'); assert.equal(spec.params.get('releaseMEnd'), '09'); assert.equal(spec.params.get('releaseDEnd'), '15');
}
for (const bad of [{ page: -1 }, { page: '1.1' }, { page: 10001 }, { q: 'a'.repeat(51) }, { type: 'unknown' }, { set: '../admin' }]) assert.throws(() => searchParams(new URLSearchParams(bad)));
const setBlock = (date, id) => `<div class="t_row packc1"><div class="time">${date}</div><div class="main"><p>検証セット</p><input value="?pid=${id}"></div></div>`;
assert.deepEqual(parseSets(setBlock('2026/09/01', '100') + setBlock('2026/10/01', '200'), '2026-09-15').map(s => s.id), ['100']);
assert.throws(() => parseSets('<h1>Unreachable</h1>'));
const html = await readFile('commons/yugioh-flavor/index.html', 'utf8');
assert.match(html, /id="reader-dialog"/); assert.match(html, /通常モンスター/); assert.match(html, /収録範囲/);
assert.doesNotMatch(html, /maximum-scale=1|user-scalable=no/);
console.log('Yu-Gi-Oh: normal/effect/pendulum classification, source parsing, images, empty vs failure, safe URLs, dates and pagination passed.');
