const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeUrl=url=>{try{const u=new URL(url);return u.protocol==='https:'?u.href:'#'}catch{return '#'}};
const link=(url,title)=>`<a href="${esc(safeUrl(url))}" target="_blank" rel="noopener noreferrer">${esc(title)} ↗</a>`;
const storageKey='commons:constitution:recall:v1';
let root,chapters=[],nodes=new Map(),leaves=[],opened=new Set(['constitution']),selected='constitution',chapter='constitution',view='map',mode='all',zoom=1,onlyNew=false,known=new Set(),mapSize={w:1,h:1};
let data;
try{known=new Set(JSON.parse(localStorage.getItem(storageKey)||'[]').filter(x=>typeof x==='string'))}catch{}
const leafCount=n=>n.children?.length?n.children.reduce((a,c)=>a+leafCount(c),0):n.rule?1:0;
const walk=(n,fn)=>{fn(n);n.children?.forEach(c=>walk(c,fn))};
const pathTo=n=>{const list=[];while(n){list.unshift(n);n=nodes.get(n.parent)}return list};
const normalize=s=>String(s).normalize('NFKC').toLocaleLowerCase('ja');
const describe=n=>n.children?.length?`${leafCount(n)}論点 · ${n.children.length}の枝`:n.articles?.join('・')||'論文・短答';
const lists=(title,items,ordered=false)=>items?.length?`<h3>${title}</h3><${ordered?'ol':'ul'}>${items.map(x=>`<li>${esc(x)}</li>`).join('')}</${ordered?'ol':'ul'}>`:'';
function notice(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(notice.timer);notice.timer=setTimeout(()=>$('#toast').classList.remove('visible'),2800)}
function updateProgress(){const total=leaves.length,count=leaves.filter(n=>known.has(n.id)).length;$('#progress').max=total;$('#progress').value=count;$('#progress-text').textContent=`${count} / ${total} 論点`;const cases=new Set(leaves.flatMap(n=>(n.cases||[]).map(c=>c.name+'|'+(c.date||''))));$('#stats').innerHTML=`<strong>${total}</strong> 論点 <span>／</span> <strong>${cases.size}</strong> 判例項目 <span>／</span> <strong>${nodes.size}</strong> 階層項目<br>想起済み ${count} · 2026年9月版`}
function renderChapters(){const all=[root,...chapters];$('#chapters').innerHTML=all.map((n,i)=>`<button data-chapter="${n.id}" class="${chapter===n.id?'active':''}"><span class="chapter-num">${i?String(i).padStart(2,'0'):'◎'}</span><span>${esc(i?n.title:'全体図')}</span></button>`).join('');$('#chapter-select').innerHTML=all.map((n,i)=>`<option value="${n.id}" ${chapter===n.id?'selected':''}>${i?String(i).padStart(2,'0')+' '+esc(n.title):'全体図'}</option>`).join('')}
function renderDetail(){const n=nodes.get(selected)||root;const ancestors=pathTo(n);const crumbs=ancestors.slice(0,-1).map(p=>`<button data-select="${p.id}">${esc(p.title)}</button><span>›</span>`).join('');let html=`<button class="mobile-back" data-back>↑ マップへ戻る</button><div class="breadcrumbs">${crumbs}</div><div class="article-tags">${(n.articles||[]).map(a=>link('https://laws.e-gov.go.jp/law/321CONSTITUTION',a)).join('')}</div><h2>${esc(n.title)}</h2><p class="summary">${esc(n.summary)}</p>`;
  if(n.children?.length){html+=`<p>${esc(n.id==='constitution'?'総論から人権・統治へ。条文、規範、判例、答案の使い方をつなげて学びます。':`${leafCount(n)}の論点を収録。下の枝を選んで理解を深めてください。`)}</p><div class="learning-path"><span>保障・制度</span><span>→ 規範</span><span>→ 判例</span><span>→ 当てはめ</span></div><h3>この分野の枝</h3><ul class="topic-index">${n.children.map(c=>`<li><button data-select="${c.id}" data-open="true">${esc(c.title)}<small>${esc(describe(c))}</small></button></li>`).join('')}</ul>`;if(n.id==='constitution')html+='<h3>短答と論文への使い方</h3><ol><li>階層を見て、論点がどこに位置するか説明する。</li><li>規範と判例の事案・射程を理解し、想起チェックに答える。</li><li>短答の正誤を理由付きで判断する。</li><li>論文は問題文の事実を使い、規範に当てはめる。</li></ol><p>この教材を知識の地図として使い、公式過去問と起案で定着を確認してください。</p><p><a href="./textbook.html">全範囲のテキスト版を読む ↗</a></p>';
  }else{html+=`<h3>理解する規範</h3><p>${esc(n.rule)}</p><div class="mode-tabs" aria-label="短答・論文の切替">${[['all','両方'],['short','短答'],['essay','論文']].map(([id,label])=>`<button data-mode="${id}" aria-pressed="${mode===id}">${label}</button>`).join('')}</div>${mode!=='essay'?lists('短答で押さえる',n.short):''}${mode!=='short'?lists('論文で使う',n.essay,true):''}<div class="pitfalls">${lists('混同しない',n.pitfalls)}</div>`;
    if(n.cases?.length)html+=`<h3>判例と射程</h3>${n.cases.map(c=>`<div class="case"><strong>${esc(c.name)}</strong>${c.date?`<time>${esc(c.date)}</time>`:''}<p>${esc(c.holding)}</p>${c.url?link(c.url,'判例の出典'):''}</div>`).join('')}`;
    if(n.check)html+=`<section class="recall"><h3>想起チェック</h3><p>${esc(n.check.q)}</p><details id="recall-answer"><summary>答えを確認する</summary><p>${esc(n.check.a)}</p></details><button id="mark-known" aria-pressed="${known.has(n.id)}">${known.has(n.id)?'✓ 想起できた · 取り消す':'説明できたら「想起済み」にする'}</button></section>`;
    const sources=n.sources||[];if(sources.length)html+=`<h3>条文・確認資料</h3><ul class="source-list">${sources.map(s=>`<li>${link(s.url,s.title)}</li>`).join('')}</ul>`;
    const index=leaves.findIndex(l=>l.id===n.id);html+=`<nav class="next-prev" aria-label="次の論点">${index>0?`<button data-select="${leaves[index-1].id}">← 前の論点<br>${esc(leaves[index-1].title)}</button>`:'<span></span>'}${index<leaves.length-1?`<button data-select="${leaves[index+1].id}">次の論点 →<br>${esc(leaves[index+1].title)}</button>`:''}</nav>`;
  }$('#detail').innerHTML=html;
}
function renderMap(){const current=nodes.get(chapter)||root;const visible=[],edges=[];let row=0,maxDepth=0;function place(n,depth){maxDepth=Math.max(maxDepth,depth);let kids=opened.has(n.id)?n.children||[]:[];const childPositions=kids.map(c=>place(c,depth+1));const y=childPositions.length?(childPositions[0].y+childPositions.at(-1).y)/2:28+row++*113;const p={node:n,x:24+depth*272,y};visible.push(p);childPositions.forEach(c=>edges.push([p,c]));return p}place(current,0);mapSize={w:48+maxDepth*272+216,h:Math.max(200,row*113+40)};$('#map-canvas').style.width=mapSize.w+'px';$('#map-canvas').style.height=mapSize.h+'px';$('#map-canvas').innerHTML=`<svg width="${mapSize.w}" height="${mapSize.h}" aria-hidden="true">${edges.map(([p,c])=>`<path d="M${p.x+216},${p.y+46} C${p.x+246},${p.y+46} ${c.x-30},${c.y+46} ${c.x},${c.y+46}" fill="none" stroke="#9aaf91" stroke-width="1.5"/>`).join('')}</svg>`+visible.map(({node:n,x,y})=>`<div class="map-node ${n.id===selected?'active':''} ${n.id===current.id?'is-root':''}" style="left:${x}px;top:${y}px"><button class="node-select" data-select="${n.id}" title="${esc(n.title)}"><span class="node-title">${esc(n.title)}</span><span class="node-meta">${esc(describe(n))}${known.has(n.id)?' <span class="node-done">✓</span>':''}</span></button>${n.children?.length?`<button class="node-toggle" data-toggle="${n.id}" aria-expanded="${opened.has(n.id)}" aria-label="${esc(n.title)}の枝を${opened.has(n.id)?'閉じる':'開く'}">${opened.has(n.id)?'−':'＋'}</button>`:''}</div>`).join('');applyZoom();}
function applyZoom(){const oldScale=Number($('#map-canvas').dataset.zoom||zoom);$('#map-canvas').style.transform=`scale(${zoom})`;$('#map-canvas').dataset.zoom=zoom;$('#map-sizer').style.width=Math.ceil(mapSize.w*zoom)+'px';$('#map-sizer').style.height=Math.ceil(mapSize.h*zoom)+'px';$('#zoom-reset').textContent=Math.round(zoom*100)+'%';if(oldScale!==zoom){const port=$('#map-viewport');port.scrollLeft*=zoom/oldScale;port.scrollTop*=zoom/oldScale}}
function outlineNode(n){const has=n.children?.length;return `<li><div class="outline-row">${has?`<button data-toggle="${n.id}" aria-expanded="${opened.has(n.id)}" aria-label="${esc(n.title)}の枝を開閉">${opened.has(n.id)?'−':'＋'}</button>`:'<span class="leaf-marker">•</span>'}<button class="outline-select ${n.id===selected?'active':''}" data-select="${n.id}">${esc(n.title)}${known.has(n.id)?' ✓':''}</button></div>${has&&opened.has(n.id)?'<ul>'+n.children.map(outlineNode).join('')+'</ul>':''}</li>`}
function isSearch(){return !!$('#search').value.trim()||onlyNew}
function renderSurface(){const search=isSearch();$('#map-viewport').hidden=search||view!=='map';$('#outline').hidden=search||view!=='tree';$('#results').hidden=!search;$('#zoom-controls').hidden=search||view!=='map';$('.branch-actions').hidden=search;$('#view-map').setAttribute('aria-pressed',view==='map');$('#view-tree').setAttribute('aria-pressed',view==='tree');$('#unlearned').setAttribute('aria-pressed',onlyNew);$('#map-label').textContent=search?'全分野から検索':pathTo(nodes.get(chapter)||root).map(n=>n.title).join(' / ');if(search){const terms=normalize($('#search').value).split(/\s+/).filter(Boolean);const found=leaves.filter(n=>(!onlyNew||!known.has(n.id))&&terms.every(t=>n.searchText.includes(t)));$('#results').innerHTML=`<p class="results-count">${found.length}論点${onlyNew?' · 未習得のみ':''}</p>`+found.map(n=>`<button class="result" data-select="${n.id}"><small>${esc(pathTo(n).slice(1,-1).map(x=>x.title).join(' › '))}</small><strong>${esc(n.title)}${known.has(n.id)?' ✓':''}</strong><p>${esc(n.summary)}</p></button>`).join('')+(found.length?'':'<p>該当する論点がありません。別の言葉で検索するか、未習得の絞り込みを解除してください。</p>');return}if(view==='map')renderMap();else $('#outline').innerHTML='<ul>'+outlineNode(nodes.get(chapter)||root)+'</ul>'}
function chooseChapter(id){if(!nodes.has(id))return;chapter=id;selected=id;opened.add(id);$('#search').value='';onlyNew=false;renderChapters();renderSurface();renderDetail();$('#map-viewport').scrollTo(0,0);$('#outline').scrollTo(0,0);$('#detail').scrollTo(0,0);setHash(id)}
function setHash(id){try{history.replaceState(null,'','#'+encodeURIComponent(id))}catch{}}
function chooseNode(id,showChildren=false){const n=nodes.get(id);if(!n)return;selected=id;const path=pathTo(n);path.forEach(p=>opened.add(p.id));if(showChildren)opened.add(id);if(!path.some(p=>p.id===chapter)){chapter=chapters.find(c=>path.some(p=>p.id===c.id))?.id||'constitution'}renderChapters();renderSurface();renderDetail();setHash(id);if(matchMedia('(max-width:680px)').matches){$('#detail').scrollIntoView({behavior:'smooth',block:'start'});$('#detail').focus({preventScroll:true})}else $('#detail').scrollTo(0,0)}
function buildPrint(){return `<h1>憲法マインドマップ｜予備試験</h1><p>2026年9月版 · ${leaves.length}論点 · 短答と論文の体系教材</p><p>判例と学説、原則と例外を区別し、公式過去問・起案と併用してください。出典は各論点に掲載しています。</p>`+chapters.map(c=>`<h2>${esc(c.title)}</h2><p>${esc(c.summary)}</p>`+leaves.filter(n=>pathTo(n).some(p=>p.id===c.id)).map(n=>`<article><p class="print-path">${esc(pathTo(n).slice(1,-1).map(p=>p.title).join(' › '))}</p><h3>${esc(n.title)}（${esc((n.articles||[]).join('・'))}）</h3><p><strong>${esc(n.summary)}</strong></p><p>${esc(n.rule)}</p>${lists('短答',n.short)}${lists('論文',n.essay,true)}${lists('混同しない',n.pitfalls)}${(n.cases||[]).map(c=>`<p class="print-case"><strong>${esc(c.name)} ${esc(c.date||'')}</strong>：${esc(c.holding)}<br>${c.url?link(c.url,'判例原典'):''}</p>`).join('')}<h4>想起チェック</h4><p>${esc(n.check?.q)}<br>答：${esc(n.check?.a)}</p><p class="print-sources">${(n.sources||[]).map(s=>link(s.url,s.title)).join(' / ')}</p></article>`).join('')).join('')}
document.addEventListener('click',e=>{const el=e.target.closest('button');if(!el)return;if(el.dataset.chapter)return chooseChapter(el.dataset.chapter);if(el.dataset.toggle){const id=el.dataset.toggle;opened.has(id)?opened.delete(id):opened.add(id);renderSurface();return}if(el.dataset.select)return chooseNode(el.dataset.select,!!el.dataset.open);if(el.dataset.mode){mode=el.dataset.mode;const scroll=$('#detail').scrollTop;renderDetail();$('#detail').scrollTop=scroll;return}if(el.hasAttribute('data-back')){$('.map-panel').scrollIntoView({behavior:'smooth'});return}if(el.id==='mark-known'){known.has(selected)?known.delete(selected):known.add(selected);try{localStorage.setItem(storageKey,JSON.stringify([...known]))}catch{notice('ブラウザに保存できません。この画面内では記録します。')}const scroll=$('#detail').scrollTop;const answerOpen=$('#recall-answer')?.open;renderDetail();if(answerOpen&&$('#recall-answer'))$('#recall-answer').open=true;$('#detail').scrollTop=scroll;renderSurface();updateProgress();return}});
$('#chapter-select').addEventListener('change',e=>chooseChapter(e.target.value));
$('#search').addEventListener('input',renderSurface);
$('#unlearned').addEventListener('click',()=>{onlyNew=!onlyNew;renderSurface()});
$('#view-map').addEventListener('click',()=>{view='map';renderSurface()});$('#view-tree').addEventListener('click',()=>{view='tree';renderSurface()});
$('#expand').addEventListener('click',()=>{walk(nodes.get(chapter),n=>opened.add(n.id));renderSurface()});$('#collapse').addEventListener('click',()=>{walk(nodes.get(chapter),n=>opened.delete(n.id));opened.add(chapter);renderSurface()});
$('#zoom-in').addEventListener('click',()=>{zoom=Math.min(1.6,Math.round((zoom+.1)*10)/10);applyZoom()});$('#zoom-out').addEventListener('click',()=>{zoom=Math.max(.5,Math.round((zoom-.1)*10)/10);applyZoom()});$('#zoom-reset').addEventListener('click',()=>{zoom=1;applyZoom()});
$('#print').addEventListener('click',()=>{$('#print-content').innerHTML=buildPrint();window.print()});
window.addEventListener('beforeprint',()=>{if(data&&!$('#print-content').children.length)$('#print-content').innerHTML=buildPrint()});
window.addEventListener('hashchange',()=>{const id=decodeURIComponent(location.hash.slice(1));if(nodes.has(id)&&id!==selected)chooseNode(id)});
const port=$('#map-viewport');let drag;port.addEventListener('pointerdown',e=>{if(e.pointerType!=='mouse'||e.target.closest('button'))return;drag={x:e.clientX,y:e.clientY,left:port.scrollLeft,top:port.scrollTop};port.setPointerCapture(e.pointerId);port.classList.add('dragging')});port.addEventListener('pointermove',e=>{if(drag){port.scrollLeft=drag.left+drag.x-e.clientX;port.scrollTop=drag.top+drag.y-e.clientY}});['pointerup','pointercancel'].forEach(event=>port.addEventListener(event,()=>{drag=null;port.classList.remove('dragging')}));
try{const response=await fetch('./content.json?v=20260919');if(!response.ok)throw new Error('読込エラー');data=await response.json();root=data.root;chapters=data.chapters.map(id=>{let found;walk(root,n=>{if(n.id===id)found=n});return found}).filter(Boolean);function index(n,parent){n.parent=parent;n.searchText=normalize(JSON.stringify({...n,children:undefined}));nodes.set(n.id,n);if(!n.children?.length&&n.rule)leaves.push(n);n.children?.forEach(c=>index(c,n.id))}index(root,null);known=new Set([...known].filter(id=>nodes.has(id)));$('#review-date').textContent=`作成・確認日：${data.reviewedAt}。確認した判例・資料の範囲を記載。更新は自動ではありません。`;const initial=decodeURIComponent(location.hash.slice(1));if(nodes.has(initial)){selected=initial;const p=pathTo(nodes.get(initial));chapter=chapters.find(c=>p.some(n=>n.id===c.id))?.id||'constitution';p.forEach(n=>opened.add(n.id))}if(matchMedia('(max-width:680px)').matches)view='tree';renderChapters();renderSurface();renderDetail();updateProgress();window.__CONSTITUTION__={nodes:nodes.size,topics:leaves.length,chapters:chapters.length};}
catch(error){$('#stats').textContent='教材を読み込めませんでした';$('#detail').innerHTML='<h2>読み込みに失敗しました</h2><p>通信を確認し、ページを再読み込みしてください。</p><p><a href="./textbook.html">全範囲のテキスト版を読む</a></p>';console.error(error)}
