import {BOSSES,RULES,shuffle,newRaid,resolveRound,nextRound,useSkill,selectQuestions} from './core.mjs';
const $=id=>document.getElementById(id),storeKey='aitech-quiz-raid-v1';let dataset,subject=['law','it'].includes(new URLSearchParams(location.search).get('subject'))?new URLSearchParams(location.search).get('subject'):'mix',mode='duo',raid,deck=[],pool=[],question,answers=[null,null],eliminated=[],timeLeft=30,cpuAt=0,paused=false,lastTick=performance.now(),scene,callTimer,sound=false,audioContext,lastResult,review=false,names=['プレイヤー1','プレイヤー2'];
let storageOK=true,progress={seen:[],wrong:[],best:0,clears:0};
try{const p=JSON.parse(localStorage.getItem(storeKey)||'null');if(p&&Array.isArray(p.seen)&&Array.isArray(p.wrong))progress={seen:p.seen.filter(x=>typeof x==='string'),wrong:p.wrong.filter(x=>typeof x==='string'),best:Number(p.best)||0,clears:Number(p.clears)||0};}catch{storageOK=false;}
function save(){try{localStorage.setItem(storeKey,JSON.stringify(progress));}catch{storageOK=false;}}
function progressUI(){$('wrong-count').textContent=progress.wrong.length;$('review-start').disabled=!dataset||progress.wrong.length===0;$('progress-text').textContent=`挑戦済み ${new Set(progress.seen).size} / 1,000問 · BEST ${progress.best.toLocaleString()}`;}
function tone(good,combo=false){if(!sound)return;try{audioContext??=new (window.AudioContext||window.webkitAudioContext)();audioContext.resume();const now=audioContext.currentTime;for(let i=0;i<(combo?3:2);i++){const o=audioContext.createOscillator(),g=audioContext.createGain();o.type=good?'sine':'triangle';o.frequency.value=good?[523,659,784][i]:[180,140][i];g.gain.setValueAtTime(.001,now+i*.08);g.gain.exponentialRampToValueAtTime(.08,now+i*.08+.01);g.gain.exponentialRampToValueAtTime(.001,now+i*.08+.3);o.connect(g).connect(audioContext.destination);o.start(now+i*.08);o.stop(now+i*.08+.31);}}catch{}}
function call(text){clearTimeout(callTimer);$('battle-call').textContent=text;$('battle-call').classList.add('show');callTimer=setTimeout(()=>$('battle-call').classList.remove('show'),1900);}
function updateCategories(){const cats=[...new Set(dataset.questions.filter(q=>subject==='mix'||q.domain===subject).map(q=>q.category))];$('category').replaceChildren(new Option('すべての分野','all'),...cats.map(c=>new Option(c,c)));updateCount();}
function updateCount(){if(!dataset)return;const count=selectQuestions(dataset.questions,subject,$('category').value).length;$('start').textContent=`${mode==='duo'?'2人で':'仲間と'}レイド開始 →`;$('load-message').textContent=`選択中：${count}問 · 5体のボス · 1回 約10〜20分`;$('start').disabled=count===0;}
for(const button of $('subjects').querySelectorAll('button'))button.addEventListener('click',()=>{subject=button.dataset.subject;for(const b of $('subjects').querySelectorAll('button'))b.setAttribute('aria-pressed',b===button);if(dataset)updateCategories();});
for(const button of $('modes').querySelectorAll('button'))button.addEventListener('click',()=>{mode=button.dataset.mode;for(const b of $('modes').querySelectorAll('button'))b.setAttribute('aria-pressed',b===button);$('name2').disabled=mode==='solo';if(dataset)updateCount();});
$('category').addEventListener('change',updateCount);
function show(id){for(const x of ['setup','play','result'])$(x).hidden=x!==id;document.body.classList.toggle('playing',id==='play');}
function start(isReview=false){if(!dataset)return;review=isReview;pool=isReview?dataset.questions.filter(q=>progress.wrong.includes(q.id)):selectQuestions(dataset.questions,subject,$('category').value);if(!pool.length){$('load-message').textContent=isReview?'復習する問題はありません。':'別の分野を選んでください。';return;}deck=shuffle(pool);names=[$('name1').value.trim()||'プレイヤー1',mode==='solo'?'ルミナ（CPU）':$('name2').value.trim()||'プレイヤー2'];raid=newRaid({difficulty:review?'easy':$('difficulty').value,roles:[$('role1').value,$('role2').value],review});paused=false;$('pause-dialog').close();scene?.pause(false);show('play');$('player-name1').textContent=names[0];$('player-name2').textContent=names[1];nextQuestion();window.scrollTo({top:0,behavior:'instant'});}
function nextQuestion(){if(!deck.length){if(review){finish('review');return;}deck=shuffle(pool);if(deck.length>1&&deck.at(-1).id===question?.id)[deck[0],deck[deck.length-1]]=[deck.at(-1),deck[0]];}
 const raw=deck.pop(),order=shuffle([0,1,2,3]);question={...raw,options:order.map(i=>raw.options[i]),correct:order.indexOf(raw.correct)};answers=[null,null];eliminated=[];timeLeft=RULES[raid.difficulty].seconds||Infinity;cpuAt=3+Math.random()*3;lastTick=performance.now();$('explanation').hidden=true;$('question').textContent=question.question;$('question-number').textContent=`QUESTION ${String(raid.round+1).padStart(2,'0')}`;$('question-category').textContent=`${question.domain==='law'?'法律':'IT'} / ${question.category}`;
 renderAnswers();hud();timerUI();scene?.setWave(raid.wave,BOSSES[raid.wave].color);
}
function renderAnswers(){for(let p=0;p<2;p++){const root=$('answers'+(p+1));root.replaceChildren();question.options.forEach((option,i)=>{const button=document.createElement('button');button.type='button';button.dataset.index=i;const k=document.createElement('kbd');k.textContent=(p===0?['A','S','D','F']:['J','K','L',';'])[i];const label=document.createElement('span');label.textContent=option;button.append(k,label);button.addEventListener('click',()=>answer(p,i));root.append(button);});}answerUI();}
function answerUI(){for(let p=0;p<2;p++){const revealed=raid.phase==='explanation';$('answer-state'+(p+1)).textContent=revealed?(answers[p]===question.correct?'正解！':answers[p]===-1?'時間切れ':'次は正解しよう'):answers[p]!==null?'回答済み ✓':mode==='solo'&&p===1?'考え中…':'回答してください';for(const [i,b] of [...$('answers'+(p+1)).children].entries()){b.disabled=paused||revealed||answers[p]!==null||eliminated.includes(i)||(mode==='solo'&&p===1);b.className=eliminated.includes(i)?'eliminated':'';if(!revealed&&answers[p]===i)b.classList.add('locked');if(revealed&&i===question.correct)b.classList.add('correct');if(revealed&&answers[p]===i&&i!==question.correct)b.classList.add('wrong');b.setAttribute('aria-label',`${p+1}P 回答${i+1} ${question.options[i]}`);}}}
function answer(player,index,fromCPU=false){if(!raid||raid.phase!=='question'||paused||answers[player]!==null||eliminated.includes(index)||(!fromCPU&&mode==='solo'&&player===1))return;if(!Number.isInteger(index)||index<-1||index>3)return;answers[player]=index;answerUI();if(answers.every(v=>v!==null))resolve();}
function resolve(){lastResult=resolveRound(raid,answers.map(a=>a===question.correct));if(!lastResult)return;const r=lastResult;progress.seen=[...new Set([...progress.seen,question.id])];if(mode==='solo'?r.right[0]:r.right.every(Boolean))progress.wrong=progress.wrong.filter(id=>id!==question.id);else progress.wrong=[...new Set([...progress.wrong,question.id])];save();progressUI();answerUI();hud();scene?.hit(r);tone(r.attack>0,r.dual||r.unison);call(r.unison?'UNISON STRIKE!':r.clear?'BOSS BREAK!':r.dual?`${raid.combo} CHAIN · 連携攻撃！`:r.attack?'ナイスカバー！':'立て直そう！');
 $('verdict').textContent=r.dual?'2人とも正解！':r.right.some(Boolean)?'味方がカバー！':'解説で知識をチャージ';$('damage').textContent=`攻撃 ${r.attack} / ダメージ ${r.hurt}${r.heal?' / 回復 '+r.heal:''}`;$('correct-answer').textContent='正解：'+question.options[question.correct];$('explain-text').textContent=question.explanation;$('source-link').href=question.source;$('source-link').textContent=question.sourceLabel+' ↗';$('explanation').hidden=false;$('next').textContent=!review&&(r.lost||r.won)?'結果を見る →':review&&!deck.length?'復習の結果を見る →':r.clear?'次のボスへ · 体力＋35 →':'次の問題へ →';
}
function hud(){const b=BOSSES[raid.wave];$('stage').textContent=review?'REVIEW / KNOWLEDGE RECOVERY':b.title;$('boss-name').textContent=b.name;$('boss-hp').textContent=`${raid.bossHp} / ${raid.bossMax}`;$('boss-bar').max=raid.bossMax;$('boss-bar').value=raid.bossHp;$('team-hp').textContent=`${raid.hp} / ${raid.maxHp}`;$('team-bar').max=raid.maxHp;$('team-bar').value=raid.hp;$('combo').textContent=raid.combo?`${raid.combo} CHAIN`:'READY';$('wave').textContent=`BOSS ${raid.wave+1} / 5 · SCORE ${raid.score}`;
 const active=raid.phase==='question'&&!paused;$('hint').disabled=!active||raid.hints<1||eliminated.length>0;$('guard').disabled=!active||raid.guards<1||raid.guard;$('guard').setAttribute('aria-pressed',raid.guard);$('unison').disabled=!active||raid.charge<100||raid.unison;$('hint').querySelector('small').textContent=`${raid.hints} / 2`;$('guard').querySelector('small').textContent=raid.guard?'発動中':`${raid.guards} / 2`;$('unison').querySelector('small').textContent=raid.unison?'発動中':`${raid.charge}%`;$('intent').textContent=raid.phase!=='question'?'解説を読んだら、次の問題へ':(raid.waveRound+1)%3===0?'⚠ 次は敵の大技！「守る」も活用しよう':'正解で攻撃。2人とも正解なら反撃を防ぐ';
}
function timerUI(){$('timer').textContent=Number.isFinite(timeLeft)?String(Math.max(0,Math.ceil(timeLeft))):'∞';$('timer').style.color=timeLeft<=5?'var(--red)':'var(--gold)';}
setInterval(()=>{const now=performance.now(),dt=Math.min(.5,(now-lastTick)/1000);lastTick=now;if(!raid||raid.phase!=='question'||paused||$('play').hidden)return;if(mode==='solo'&&answers[1]===null){cpuAt-=dt;if(cpuAt<=0){const available=[0,1,2,3].filter(i=>!eliminated.includes(i)),wrong=available.filter(i=>i!==question.correct);answer(1,Math.random()<RULES[raid.difficulty].cpu?question.correct:wrong[Math.floor(Math.random()*wrong.length)],true);}}
 if(raid.phase!=='question')return;timeLeft-=dt;timerUI();if(timeLeft<=0){for(let p=0;p<2;p++)if(answers[p]===null)answers[p]=-1;resolve();}},100);
$('hint').addEventListener('click',()=>{if(!paused&&useSkill(raid,'hint')){eliminated=shuffle([0,1,2,3].filter(i=>i!==question.correct)).slice(0,2);answerUI();hud();call('2択に絞った！');}});
$('guard').addEventListener('click',()=>{if(!paused&&useSkill(raid,'guard')){hud();call('チームシールド！');tone(true);}});
$('unison').addEventListener('click',()=>{if(!paused&&useSkill(raid,'unison')){hud();call('次の攻撃にユニゾン！');tone(true,true);}});
 $('next').addEventListener('click',()=>{if(paused||!raid||raid.phase!=='explanation')return;if(!review&&(lastResult.lost||lastResult.won)){finish();return;}if(review&&!deck.length){finish('review');return;}if(nextRound(raid)){nextQuestion();if(window.scrollY>100)$('play').scrollIntoView({block:'start',behavior:'instant'});}});
function finish(reason){raid.phase='result';const won=raid.cleared===5,isReview=reason==='review';if(won)progress.clears++;progress.best=Math.max(progress.best,raid.score);save();progressUI();show('result');$('result-label').textContent=isReview?'REVIEW COMPLETE':won?'RAID COMPLETE':'TRY AGAIN';$('result-title').textContent=isReview?'復習、おつかれさま！':won?'知識の力で、完全勝利！':'次は、きっと突破できる。';$('result-copy').textContent=isReview?'解説で確かめた知識を、次のレイドへ。':won?'5体のボスを撃破しました。分野や役割を変えて、次の挑戦へ。':`${raid.cleared}体のボスを撃破。防御役やヒーラーを組み合わせたり、「じっくり」で再挑戦しよう。`;
 const stats=[['スコア',raid.score.toLocaleString()],['最大連携',raid.maxCombo+'連続'],[names[0],`${raid.correct[0]} / ${raid.round}`],[names[1],`${raid.correct[1]} / ${raid.round}`]];$('result-stats').replaceChildren(...stats.map(([label,value])=>{const d=document.createElement('div'),s=document.createElement('strong'),l=document.createElement('span');s.textContent=value;l.textContent=label;d.append(s,l);return d;}));$('result-review').disabled=!progress.wrong.length;$('save-status').textContent=storageOK?`この端末に成績を保存しました。復習する問題：${progress.wrong.length}問。`:'このブラウザでは成績を保存できませんでした。ゲームはそのまま遊べます。';$('result').scrollIntoView({behavior:'instant',block:'start'});}
function pause(){if(!raid||$('play').hidden||paused)return;paused=true;scene?.pause(true);$('pause-dialog').showModal();hud();answerUI();}
function resume(){paused=false;lastTick=performance.now();scene?.pause(false);$('pause-dialog').close();if(raid){hud();answerUI();}}
$('pause').addEventListener('click',pause);$('resume').addEventListener('click',resume);$('pause-dialog').addEventListener('cancel',e=>{e.preventDefault();resume();});$('quit').addEventListener('click',()=>{resume();raid=null;show('setup');updateCount();window.scrollTo({top:0,behavior:'instant'});});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&raid?.phase==='question'&&!$('play').hidden)pause();});
$('start').addEventListener('click',()=>start());$('review-start').addEventListener('click',()=>start(true));$('again').addEventListener('click',()=>start(review));$('result-review').addEventListener('click',()=>start(true));$('home').addEventListener('click',()=>{raid=null;show('setup');updateCount();window.scrollTo({top:0,behavior:'instant'});});
$('sound').addEventListener('click',()=>{sound=!sound;$('sound').textContent='音 '+(sound?'ON':'OFF');$('sound').setAttribute('aria-pressed',sound);if(sound)tone(true);});
$('fullscreen').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();else call('画面を横向きにすると広く遊べます');}catch{call('この端末では全画面に切り替えられません');}});
document.addEventListener('fullscreenchange',()=>$('fullscreen').textContent=document.fullscreenElement?'全画面終了':'全画面');
document.addEventListener('keydown',e=>{if(/INPUT|SELECT|TEXTAREA/.test(e.target.tagName)||e.repeat||e.ctrlKey||e.metaKey||e.altKey)return;if(e.key==='Escape'&&!$('play').hidden){e.preventDefault();paused?resume():pause();return;}if(paused||!raid)return;if(e.key==='Enter'&&raid.phase==='explanation') {e.preventDefault();$('next').click();return;}const k=e.key.toLowerCase(),p1=['a','s','d','f'].indexOf(k),p2=['j','k','l',';'].indexOf(k);if(p1>=0){e.preventDefault();answer(0,p1);}if(p2>=0){e.preventDefault();answer(1,p2);}});
async function init(){try{const response=await fetch('questions.json?v=20260914-1');if(!response.ok)throw new Error();dataset=await response.json();if(dataset.questions?.length!==1000)throw new Error();const ids=new Set(dataset.questions.map(q=>q.id));progress.seen=progress.seen.filter(id=>ids.has(id));progress.wrong=progress.wrong.filter(id=>ids.has(id));for(const b of $('subjects').querySelectorAll('button'))b.setAttribute('aria-pressed',b.dataset.subject===subject);updateCategories();progressUI();}catch{$('load-message').textContent='問題を読み込めませんでした。接続を確認して「再読み込み」を押してください。';$('start').disabled=false;$('start').textContent='再読み込み';$('start').addEventListener('click',()=>location.reload(),{once:true});}}
progressUI();init();import('./scene.mjs').then(({createArena})=>{scene=createArena($('scene'));}).catch(()=>{$('scene').replaceChildren();const p=document.createElement('p');p.className='scene-loading';p.textContent='この端末では3D表示を利用できません。クイズはそのまま遊べます。';$('scene').append(p);});
