import {CARDS,BY_ID,ABILITIES} from './catalog.mjs';
export const W=19,H=13,CAP=99;
export const CRESTS={move:['➜','移動'],attack:['⚔','攻撃'],defend:['⬡','防御'],magic:['✦','魔法'],trap:['⌁','罠'],summon:['◇','召喚']};
export const DIRS=[[1,0],[-1,0],[0,1],[0,-1]];
const key=(x,y)=>`${x},${y}`;
export const inside=(x,y)=>Number.isInteger(x)&&Number.isInteger(y)&&x>=0&&x<W&&y>=0&&y<H;
export const at=(s,x,y)=>inside(x,y)?s.board[y*W+x]:null;
export const distance=(a,b)=>Math.abs(a.x-b.x)+Math.abs(a.y-b.y);
const neg=v=>v.map(n=>-n);
// Enumerate free hexominoes and keep precisely the 11 that fold into a cube.
const normalize=p=>{let x=Math.min(...p.map(a=>a[0])),y=Math.min(...p.map(a=>a[1]));return p.map(a=>[a[0]-x,a[1]-y]).sort((a,b)=>a[1]-b[1]||a[0]-b[0]);};
export function transformNet(p,r=0,flip=false){return normalize(p.map(([x,y])=>{if(flip)x=-x;for(let i=0;i<r%4;i++)[x,y]=[-y,x];return [x,y];}));}
const signature=p=>JSON.stringify(normalize(p));
const canonical=p=>[0,1,2,3].flatMap(r=>[false,true].map(f=>signature(transformNet(p,r,f)))).sort()[0];
function folds(p){const tiles=new Set(p.map(a=>key(...a))),poses=new Map([[key(...p[0]),[[1,0,0],[0,1,0],[0,0,1]]]]),queue=[p[0]];while(queue.length){const [x,y]=queue.shift(),[u,v,n]=poses.get(key(x,y));for(const [dx,dy]of DIRS){let k=key(x+dx,y+dy);if(!tiles.has(k))continue;let pose=dx===1?[neg(n),v,u]:dx===-1?[n,v,neg(u)]:dy===1?[u,neg(n),v]:[u,n,neg(v)];if(poses.has(k)){if(JSON.stringify(poses.get(k))!==JSON.stringify(pose))return false;}else{poses.set(k,pose);queue.push([x+dx,y+dy]);}}}return new Set([...poses.values()].map(p=>p[2].join(','))).size===6;}
function makeNets(){let polys=[[[0,0]]];for(let n=2;n<=6;n++){let next=new Map();for(const p of polys)for(const [x,y]of p)for(const [dx,dy]of DIRS){if(p.some(a=>a[0]===x+dx&&a[1]===y+dy))continue;const q=[...p,[x+dx,y+dy]],k=canonical(q);if(!next.has(k))next.set(k,JSON.parse(k));}polys=[...next.values()];}return polys.filter(folds).sort((a,b)=>Math.max(...b.map(p=>p[0]))-Math.max(...a.map(p=>p[0])));}
export const NETS=makeNets();
export const ORIENTATIONS=NETS.flatMap((net,i)=>{let seen=new Set();return [0,1,2,3].flatMap(r=>[false,true].flatMap(f=>{const p=transformNet(net,r,f),k=signature(p);if(seen.has(k))return [];seen.add(k);return [{i,r,f,points:p}];}));});
export function defaultDeck(style='balanced',edition='physical'){
 const pool=CARDS.filter(c=>c.edition===edition&&c.tribe!=='item');
 const favorites={balanced:['Mystical Elf','Baby Dragon','Kuriboh','Celtic Guardian','Flame Swordsman','Knight of Twin Swords','Dark Magician','Blue-Eyes White Dragon','Orgoth the Relentless'],dragon:['Baby Dragon','Petit Dragon','Darkfire Dragon','Parrot Dragon','Curse of Dragon','Blue-Eyes White Dragon','Blue-Eyes Ultimate Dragon','Red-Eyes B. Dragon','Lord of D.'],magic:['Mystical Elf','Kuriboh','Time Wizard','Dark Magician Girl','Dark Magician','Magician of Black Chaos','Mighty Mage','Relinquished','Jinzo']}[style]||[];
 const chosen=[];for(const en of favorites){const c=pool.find(c=>c.en===en);if(c)chosen.push(c.id);}
 for(const lv of [1,1,1,2,2,3,4,1,2,3,4,1,2,3,4]){if(chosen.length>=15)break;const c=pool.find(c=>c.level===lv&&!chosen.includes(c.id));if(c)chosen.push(c.id);}
 return chosen.slice(0,15);
}
export function validateDeck(ids){if(!Array.isArray(ids)||ids.length!==15)return '15個のダイスを編成してください。';if(ids.some(id=>!BY_ID[id]))return '不明なダイスが含まれています。';if(ids.some(id=>ids.filter(x=>x===id).length>3))return '同じダイスは3個までです。';if(ids.filter(id=>BY_ID[id].tribe!=='item').length<3)return 'モンスターを3体以上入れてください。';return '';}
export function newGame({deck=defaultDeck(),enemyDeck=defaultDeck('dragon'),mode='cpu',difficulty='normal',pace='quick',seed=Date.now()}={}){
 const err=validateDeck(deck)||validateDeck(enemyDeck);if(err)throw Error(err);
 const s={version:1,seed:(seed>>>0)||1,mode,difficulty,pace,turn:0,round:1,phase:'roll',winner:null,reason:'',serial:0,board:Array(W*H).fill(null),units:[],items:[],grave:[],players:[deck,enemyDeck].map((d,i)=>({hp:3,deck:d.map((id,slot)=>({id,slot,used:false})),bank:{move:pace==='quick'?4:0,attack:pace==='quick'?2:0,defend:pace==='quick'?1:0,magic:pace==='quick'?2:0,trap:0},x:i?18:0,y:6})),rolls:[],candidates:[],pending:null,logs:[]};
 s.players.forEach((p,i)=>s.board[p.y*W+p.x]={owner:i,home:true});log(s,'ダンジョンの扉が開いた。相手のマスターへ3回攻撃すると勝利。');return s;
}
export function random(s){s.seed^=s.seed<<13;s.seed^=s.seed>>>17;s.seed^=s.seed<<5;return (s.seed>>>0)/4294967296;}
function log(s,text){s.logs.unshift({turn:s.round,player:s.turn,text});s.logs=s.logs.slice(0,70);}
function earn(s,p,k,n){s.players[p].bank[k]=Math.max(0,Math.min(CAP,s.players[p].bank[k]+n));}
export function available(s,p=s.turn){return s.players[p].deck.filter(d=>!d.used);}
export function diceFaces(card){const summonCount=[0,4,3,2,1][card.level];const variants={warrior:['attack','move','defend','magic','trap'],dragon:['attack','move','magic','defend','trap'],mage:['magic','move','trap','attack','defend'],beast:['move','attack','defend','trap','magic'],undead:['trap','move','defend','magic','attack'],item:['move','trap','magic','defend','attack']};let rest=variants[card.tribe]||variants.warrior;return [...Array(summonCount).fill('summon'),...rest.slice(0,6-summonCount)];}
export function rollDice(s,slots){if(s.winner!==null||s.phase!=='roll')return '今はダイスを振れません。';const avail=available(s);if(!Array.isArray(slots)||slots.length!==Math.min(3,avail.length)||new Set(slots).size!==slots.length||slots.some(slot=>!avail.some(d=>d.slot===slot)))return '未使用のダイスを3個選んでください。';
 s.rolls=slots.map(slot=>{const d=s.players[s.turn].deck[slot],c=BY_ID[d.id],face=diceFaces(c)[Math.floor(random(s)*6)];return {slot,id:d.id,level:c.level,face,amount:face==='move'?Math.min(3,c.level+1):c.level===4&&face!=='summon'?2:1};});
 for(const r of s.rolls)if(r.face!=='summon')earn(s,s.turn,r.face,r.amount);
 s.candidates=s.rolls.filter(r=>r.face==='summon'&&s.rolls.filter(t=>t.face==='summon'&&t.level===r.level).length>=2).map(r=>r.slot);
 if(s.pace==='quick'){earn(s,s.turn,'move',3);earn(s,s.turn,'attack',1);earn(s,s.turn,'magic',1);}
 s.phase=s.candidates.length?'summon':'action';log(s,s.candidates.length?'召喚の紋章が揃った。1体を選び、道を展開しよう。':'紋章を蓄えた。行動するかターンを終了しよう。');return null;
}
export function canPlace(s,points,x,y,p=s.turn){if(!inside(x,y))return false;const cells=points.map(([dx,dy])=>[x+dx,y+dy]);if(cells.some(([x,y])=>!inside(x,y)||at(s,x,y)))return false;return cells.some(([x,y])=>DIRS.some(([dx,dy])=>at(s,x+dx,y+dy)?.owner===p));}
export function legalPlacements(s,orientation,p=s.turn){const out=[];for(let y=0;y<H;y++)for(let x=0;x<W;x++)if(canPlace(s,orientation.points,x,y,p))out.push({x,y});return out;}
export function summon(s,slot,netIndex,r,flip,x,y,spawnIndex=0){if(s.winner!==null||s.phase!=='summon'||!s.candidates.includes(slot))return 'そのダイスは召喚できません。';if(!NETS[netIndex])return '展開図を選んでください。';const points=transformNet(NETS[netIndex],r,flip);if(!Number.isInteger(spawnIndex)||spawnIndex<0||spawnIndex>=6||!canPlace(s,points,x,y))return '自分の道につながる空きマスへ展開してください。';const d=s.players[s.turn].deck[slot],c=BY_ID[d.id];for(const [dx,dy]of points)s.board[(y+dy)*W+x+dx]={owner:s.turn};const [sx,sy]=points[spawnIndex],unit={uid:++s.serial,id:c.id,owner:s.turn,x:x+sx,y:y+sy,hp:c.hp,maxHp:c.hp,attacks:0,skillUsed:false,buff:0,permanent:0,guard:0,stunned:0,poison:0};d.used=true;if(c.tribe==='item')s.items.push(unit);else s.units.push(unit);s.phase='action';s.candidates=[];log(s,`${c.name}を${c.tribe==='item'?'設置':'召喚'}。道が6マス広がった。`);checkVictory(s);return null;}
export function skipSummon(s){if(s.phase==='summon'){s.phase='action';s.candidates=[];log(s,'召喚を見送り、紋章で行動する。');}}
export function unitAt(s,x,y){return s.units.find(u=>u.x===x&&u.y===y);}
export function reachable(s,u,budget=s.players[u.owner].bank.move){let result=new Map();if(u.stunned)return result;const c=BY_ID[u.id],cost=c.movement==='ground'?1:2,queue=[{x:u.x,y:u.y,cost:0,path:[]}],visited=new Set([key(u.x,u.y)]);while(queue.length){const prev=queue.shift();for(const [dx,dy]of DIRS){const x=prev.x+dx,y=prev.y+dy,k=key(x,y),tile=at(s,x,y);if(!tile||tile.home||visited.has(k)||prev.cost+cost>budget)continue;const occupant=unitAt(s,x,y);if(occupant&&c.movement==='ground')continue;visited.add(k);const node={x,y,cost:prev.cost+cost,path:[...prev.path,[x,y]]};queue.push(node);if(!occupant)result.set(k,node);}}return result;}
function permitted(s,u){return s.winner===null&&s.phase==='action'&&u&&u.owner===s.turn;}
function cleanup(s){for(const u of s.units.filter(u=>u.hp<=0)){s.grave.push({...u});log(s,`${BY_ID[u.id].name}が倒れた。`);}s.units=s.units.filter(u=>u.hp>0);}
function triggerItem(s,u){for(const item of s.items.filter(i=>i.x===u.x&&i.y===u.y)){const skill=BY_ID[item.id].skill,hostile=['item-mine','item-bind','item-steal','item-drain','item-crater'].includes(skill);if((hostile&&u.owner===item.owner)||(!hostile&&u.owner!==item.owner))continue;log(s,`${BY_ID[item.id].name}が発動。`);if(skill==='item-heal')u.hp=Math.min(u.maxHp,u.hp+30);if(skill==='item-time')u.hp=u.maxHp;if(skill==='item-mine')u.hp-=30;if(skill==='item-boost')u.permanent+=20;if(skill==='item-bind')u.stunned=2;if(skill==='item-steal'){const n=Math.min(5,s.players[u.owner].bank.move);earn(s,u.owner,'move',-n);earn(s,item.owner,'move',n);}if(skill==='item-drain'){s.players[u.owner].bank.magic=0;s.players[u.owner].bank.trap=0;}if(skill==='item-crater')s.units.forEach(t=>t.hp-=40);if(skill==='item-revive'){const g=[...s.grave].reverse().find(g=>g.owner===u.owner),spot=emptyPath(s,u.owner);if(g&&spot){s.grave.splice(s.grave.indexOf(g),1);s.units.push({...g,...spot,uid:++s.serial,hp:BY_ID[g.id].hp,attacks:0,skillUsed:false,stunned:0,poison:0});}}if(skill==='item-warp'){const spot=emptyPath(s,1-u.owner);if(spot){u.x=spot.x;u.y=spot.y;}}s.items=s.items.filter(i=>i.uid!==item.uid);cleanup(s);}}
function emptyPath(s,nearOwner){let cells=[];for(let y=0;y<H;y++)for(let x=0;x<W;x++)if(at(s,x,y)&&!at(s,x,y).home&&!unitAt(s,x,y))cells.push({x,y});return cells.sort((a,b)=>distance(a,s.players[nearOwner])-distance(b,s.players[nearOwner]))[0];}
export function moveUnit(s,uid,x,y){const u=s.units.find(u=>u.uid===uid);if(!permitted(s,u))return '行動できる味方を選んでください。';const path=reachable(s,u).get(key(x,y));if(!path)return '移動先までの道か、移動の紋章が不足しています。';earn(s,u.owner,'move',-path.cost);for(const [tx,ty]of path.path){u.x=tx;u.y=ty;triggerItem(s,u);if(u.hp<=0||u.stunned||u.x!==tx||u.y!==ty)break;}log(s,`${BY_ID[u.id].name}が移動。移動紋章−${path.cost}。`);checkVictory(s);return null;}
export function attackValue(s,u,target){const c=BY_ID[u.id];return c.atk+u.buff+u.permanent+(c.skill==='dragonbane'&&target&&BY_ID[target.id].tribe==='dragon'?20:0);}
export function attackTargets(s,u){if(!permitted(s,u)||s.players[u.owner].bank.attack<1||u.attacks>=(BY_ID[u.id].skill==='double'?2:1))return [];return [...s.units.filter(t=>t.owner!==u.owner&&distance(u,t)===1).map(t=>({uid:t.uid,x:t.x,y:t.y})),...(distance(u,s.players[1-u.owner])===1?[{lord:1-u.owner,x:s.players[1-u.owner].x,y:6}]:[])];}
export function attack(s,uid,target){const u=s.units.find(u=>u.uid===uid);if(!u||!attackTargets(s,u).some(t=>target.lord!==undefined?t.lord===target.lord:t.uid===target.uid))return '攻撃できる隣接した敵を選んでください。';earn(s,u.owner,'attack',-1);u.attacks++;if(target.lord!==undefined){s.players[target.lord].hp--;log(s,'ダンジョンマスターに1ダメージ！');checkVictory(s);return null;}s.pending={attacker:uid,defender:target.uid};s.phase='defense';return null;}
export function defenseOptions(s){if(s.phase!=='defense'||!s.pending)return {guard:false,trap:false};const d=s.units.find(u=>u.uid===s.pending.defender),a=s.units.find(u=>u.uid===s.pending.attacker);const sealed=s.units.some(u=>u.owner===a.owner&&BY_ID[u.id].skill==='seal');return {guard:s.players[d.owner].bank.defend>0,trap:!sealed&&s.players[d.owner].bank.trap>=2};}
export function resolveDefense(s,choice='none'){if(s.phase!=='defense'||!s.pending)return '防御待ちではありません。';const opts=defenseOptions(s);if(choice!=='none'&&!opts[choice])return '必要な紋章がありません。';const a=s.units.find(u=>u.uid===s.pending.attacker),d=s.units.find(u=>u.uid===s.pending.defender);if(choice==='trap'){earn(s,d.owner,'trap',-2);a.hp-=10;log(s,'迎撃の罠で攻撃を無効化。攻撃側に10ダメージ。');}else{if(choice==='guard')earn(s,d.owner,'defend',-1);const dmg=Math.max(0,attackValue(s,a,d)-(choice==='guard'?BY_ID[d.id].def+d.guard:0));d.hp-=dmg;log(s,`${BY_ID[a.id].name} → ${BY_ID[d.id].name}：${dmg}ダメージ${choice==='guard'?'（防御）':''}。`);}cleanup(s);s.pending=null;s.phase='action';checkVictory(s);return null;}
export function skillTargets(s,u){if(!permitted(s,u))return [];const c=BY_ID[u.id],[, ,cost,type]=ABILITIES[c.skill];if(u.skillUsed||s.players[u.owner].bank.magic<cost||['passive','item'].includes(type))return [];if(type==='self')return [{uid:u.uid}];if(type==='tile')return [...Array(W*H)].flatMap((_,i)=>{const x=i%W,y=Math.floor(i/W);return at(s,x,y)&&!at(s,x,y).home&&!unitAt(s,x,y)&&distance(u,{x,y})<=5?[{x,y}]:[];});let range=['absorb','push','drain'].includes(c.skill)?1:['focus','poison'].includes(c.skill)?2:3;return s.units.filter(t=>(type==='ally'?t.owner===u.owner:t.owner!==u.owner)&&distance(u,t)<=range).map(t=>({uid:t.uid,x:t.x,y:t.y}));}
export function useSkill(s,uid,target={}){const u=s.units.find(u=>u.uid===uid);if(!u)return '味方を選んでください。';const c=BY_ID[u.id],def=ABILITIES[c.skill],type=def[3],targets=skillTargets(s,u);if(!targets.length)return '能力を使えません。紋章・対象・使用回数を確認してください。';let t=type==='self'?u:s.units.find(t=>t.uid===target.uid);if(type==='tile'?!targets.some(p=>p.x===target.x&&p.y===target.y):!targets.some(p=>p.uid===t?.uid))return '能力の対象範囲外です。';earn(s,u.owner,'magic',-def[2]);u.skillUsed=true;const sk=c.skill;
 if(sk==='strike')u.buff+=10;if(sk==='roar')u.buff+=20;if(sk==='focus')t.hp-=10;if(['bolt','breath'].includes(sk)){t.hp-=20;if(sk==='breath')s.units.filter(v=>v.owner!==u.owner&&v.uid!==t.uid&&distance(v,t)===1).forEach(v=>v.hp-=10);}
 if(sk==='drain'){t.hp-=10;u.hp=Math.min(u.maxHp,u.hp+10);}if(sk==='heal')t.hp=Math.min(t.maxHp,t.hp+20);if(sk==='shield')u.guard+=20;if(['rush','haste'].includes(sk))earn(s,u.owner,'move',sk==='rush'?3:4);if(sk==='fortune'){const n=1+Math.floor(random(s)*6);u.buff+=n*10;log(s,`運命の賽：${n}`);}if(sk==='orgoth'){const dice=[1,2,3].map(()=>1+Math.floor(random(s)*6));u.buff+=dice.reduce((a,b)=>a+b)*5;log(s,`三つの運命：${dice.join('・')}`);}if(sk==='ninja'){u.x=target.x;u.y=target.y;triggerItem(s,u);}if(sk==='blast'){t.hp-=30;u.hp-=10;}if(sk==='apprentice')u.buff+=10+10*s.units.filter(v=>v.owner===u.owner&&BY_ID[v.id].tribe==='mage'&&v.uid!==u.uid).length;if(sk==='absorb'){t.hp-=20;u.hp=Math.min(u.maxHp,u.hp+20);u.buff+=20;}if(sk==='time'){const n=1+Math.floor(random(s)*6);log(s,`時の賽：${n}`);if(n>=4)s.units.filter(v=>v.owner!==u.owner).forEach(v=>v.hp-=10);else u.hp-=10;}if(sk==='curse')t.stunned=2;if(sk==='push'){const spot=emptyPath(s,t.owner);if(spot){t.x=spot.x;t.y=spot.y;triggerItem(s,t);}}if(sk==='poison'){t.hp-=10;t.poison=10;}if(sk==='link')s.units.filter(v=>v.owner===u.owner).forEach(v=>v.buff+=10);if(sk==='dragonward')s.units.filter(v=>v.owner===u.owner&&BY_ID[v.id].tribe==='dragon').forEach(v=>v.hp=Math.min(v.maxHp,v.hp+20));if(sk==='gather'){earn(s,u.owner,'attack',2);earn(s,u.owner,'defend',2);}if(sk==='god')s.units.filter(v=>v.owner!==u.owner&&BY_ID[v.id].skill!=='god').forEach(v=>v.hp-=20);
 log(s,`${c.name}：${def[0]}。`);cleanup(s);checkVictory(s);return null;}
function checkVictory(s){for(let p=0;p<2;p++){if(s.players[1-p].hp<=0){s.winner=p;s.reason='相手のダンジョンマスターを撃破';}const army=s.units.filter(u=>u.owner===p);if(army.some(u=>BY_ID[u.id].skill==='exodia')&&new Set(army.filter(u=>BY_ID[u.id].skill==='exodia-part').map(u=>BY_ID[u.id].en)).size===4){s.winner=p;s.reason='封印されしエクゾディアが完成';}}if(s.winner!==null)s.phase='over';}
export function endTurn(s){if(s.winner!==null||!['action','summon'].includes(s.phase))return 'ダイスを振り、行動を終えてからターンを終了してください。';s.turn=1-s.turn;s.round++;s.phase='roll';s.rolls=[];s.candidates=[];for(const u of s.units.filter(u=>u.owner===s.turn)){u.attacks=0;u.skillUsed=false;u.buff=0;u.guard=0;u.stunned=Math.max(0,u.stunned-1);if(u.poison){u.hp-=u.poison;u.poison=0;}}cleanup(s);if(s.round>160){s.winner=2;s.reason='160ターン到達：引き分け';s.phase='over';}return null;}
export function bestPlacement(s,slot){const c=BY_ID[s.players[s.turn].deck[slot].id],p=s.turn,enemy=s.players[1-p];let best=null,bestScore=-Infinity;for(const o of ORIENTATIONS)for(const pos of legalPlacements(s,o)){const cells=o.points.map(([dx,dy])=>({x:pos.x+dx,y:pos.y+dy}));const ranked=cells.map((p,i)=>({i,d:distance(p,enemy)})).sort((a,b)=>a.d-b.d);const score=-ranked[0].d*7-cells.reduce((a,c)=>a+Math.abs(c.y-6),0)*0.12+cells.filter(c=>DIRS.some(([dx,dy])=>at(s,c.x+dx,c.y+dy)?.owner===1-p)).length*8+(c.tribe==='item'?0:c.level);if(score>bestScore){bestScore=score;best={...pos,netIndex:o.i,r:o.r,flip:o.f,spawnIndex:ranked[0].i};}}return best;}
export function chooseDice(s){const av=available(s),groups=[1,2,3,4].map(l=>av.filter(d=>BY_ID[d.id].level===l));const enough=groups.filter(g=>g.length>=3);let g=enough[0]||groups.sort((a,b)=>b.length-a.length)[0]||[];if(enough.length>1&&s.units.filter(u=>u.owner===s.turn).length>=3)g=enough[Math.min(enough.length-1,s.difficulty==='hard'?1:0)];return [...g,...av.filter(d=>!g.includes(d))].slice(0,3).map(d=>d.slot);}
export function aiStep(s){if(s.winner!==null)return false;if(s.phase==='defense'){const o=defenseOptions(s);resolveDefense(s,o.trap?'trap':o.guard?'guard':'none');return true;}if(s.phase==='roll'){rollDice(s,chooseDice(s));return true;}if(s.phase==='summon'){const choices=[...s.candidates].sort((a,b)=>BY_ID[s.players[s.turn].deck[b].id].atk-BY_ID[s.players[s.turn].deck[a].id].atk);for(const slot of choices){const pos=bestPlacement(s,slot);if(pos){summon(s,slot,pos.netIndex,pos.r,pos.flip,pos.x,pos.y,pos.spawnIndex);return true;}}skipSummon(s);return true;}
 const own=s.units.filter(u=>u.owner===s.turn).sort((a,b)=>distance(a,s.players[1-s.turn])-distance(b,s.players[1-s.turn]));
 for(const u of own){const ts=attackTargets(s,u);if(ts.length){attack(s,u.uid,ts.find(t=>t.lord!==undefined)||ts.sort((a,b)=>s.units.find(u=>u.uid===a.uid).hp-s.units.find(u=>u.uid===b.uid).hp)[0]);return true;}}
 if(s.difficulty!=='easy')for(const u of own){const ts=skillTargets(s,u),c=BY_ID[u.id],type=ABILITIES[c.skill][3];if(!ts.length||['heal','dragonward'].includes(c.skill)&&!s.units.some(v=>v.owner===u.owner&&v.hp<v.maxHp))continue;if(type==='enemy'){useSkill(s,u.uid,ts[0]);return true;}if(['strike','roar','shield','fortune','orgoth','apprentice','link','time','god','haste','rush','gather'].includes(c.skill)){useSkill(s,u.uid,{uid:u.uid});return true;}if(type==='ally'){const t=ts.find(t=>s.units.find(v=>v.uid===t.uid).hp<s.units.find(v=>v.uid===t.uid).maxHp);if(t){useSkill(s,u.uid,t);return true;}}}
 for(const u of own){const targets=[s.players[1-s.turn],...s.units.filter(v=>v.owner!==u.owner)],spots=[...reachable(s,u).values()];let best=null,score=0;for(const p of spots){const progress=distance(u,targets[0])-distance(p,targets[0]),nearEnemy=targets.slice(1).some(t=>distance(p,t)===1),value=progress*4+(nearEnemy?3:0)-p.cost*.15;if(value>score){score=value;best=p;}}if(best){moveUnit(s,u.uid,best.x,best.y);return true;}}
 endTurn(s);return true;
}
