import {base,grid,int,shuffle,neighbors,validCell,finish,winTeam,byScore,publicView,copy} from './common.mjs';
export const realtime=false;
export function create(spec,players,seed){const s=base(spec,players,seed),n=s.n;grid(s,6,6);s.goal='盤面を選んで操作。色は各プレイヤーの陣営を表します。';s.data.selected={};s.data.lastMove=0;
 for(const p of s.players){p.coins=10;p.score=0;}
 if(n===31){s.board.kind='reversi';s.board.cells[14]=s.board.cells[21]=1;s.board.cells[15]=s.board.cells[20]=2;s.goal='相手の石を挟めるマスへ置く。置けない場合はパス。最後に石が多い方の勝ち。';}
 if(n===32){grid(s,7,6);s.board.kind='connect';s.data.gravity=1;s.data.flips=s.players.map(()=>1);s.goal='列を選んで石を落とす。縦横斜め4個で勝利。Bで一度だけ重力反転。';}
 if(n===33){s.board.kind='chess';s.data.pieces=Array(36).fill(null);const order=shuffle(s,['R','N','B','K','B','R']);for(let x=0;x<6;x++){s.data.pieces[x]={side:1,type:order[x]};s.data.pieces[x+6]={side:1,type:'P'};s.data.pieces[x+24]={side:0,type:'P'};s.data.pieces[x+30]={side:0,type:order[5-x]};}s.goal='駒→移動先を選ぶ。相手の王を取れば勝ち。王手・キャスリングなしの短期戦。';}
 if(n===34){s.board.kind='tactics';s.data.units=[];for(const p of s.players)for(let k=0;k<3;k++)s.data.units.push({id:p.side*3+k,side:p.side,cell:p.side?3+k:30+k,hp:3,type:k});s.data.orders=s.players.map(()=>[]);s.data.committed=s.players.map(()=>false);s.goal='自分の駒→目的地で移動、敵の駒を選ぶと攻撃予約。3体を予約して決定。全員の指令を同時解決。';}
 if(n===35){s.board.kind='route';s.data.ends=s.players.map((_,i)=>i?5:30);for(const p of s.players)s.board.cells[s.data.ends[p.side]]=p.side+1;s.data.market=[1,2,3];s.goal='自分の線路の隣へ延ばす。A/B/Cで線路を選択。反対の角へ接続するとボーナス。';}
 if(n===36){s.board.kind='numbers';s.board.owners=Array(36).fill(-1);s.hands=s.players.map(()=>shuffle(s,[1,2,3,4,5,6,7,8,9]));s.goal='手札の数字→空きマスへ置く。隣接する弱い数字を自分の陣地に変える。';}
 if(n===37){s.board.kind='fleet';s.data.fleets=s.players.map(()=>shuffle(s,Array.from({length:36},(_,i)=>i)).slice(0,6));s.data.shots=s.players.map(()=>Array(36).fill(0));s.data.sonar=s.players.map(()=>2);s.goal='海域を選んで砲撃。船を6マス撃沈すると勝利。Bで選択地点周辺をソナー探索。';}
 if(n===38){s.board.kind='maze';s.data.pawns=[32,3];s.data.bricks=[8,8];s.goal='自分の駒の隣を選んで進む。B→マスで壁を置く。相手側の端へ先に到着。道を完全には塞げません。';}
 if(n===39){s.board.kind='domino';s.data.tiles=Array(36).fill(null);s.data.tiles[18]=[3,3];s.hands=s.players.map(()=>Array.from({length:7},()=>[int(s,6),int(s,6)]));s.goal='手札のドミノ→数字の合う隣接マスを選ぶ。置けないときは1枚引く。手札を使い切ろう。';}
 if(n===40){s.board.kind='island';s.board.resources=Array.from({length:36},()=>1+int(s,3));s.goal='土地を選んで採集。Aで採集、Bで建設（資材4）、Cで交換。8巡で拠点と資材を競う。';s.data.rounds=8;}
 if(n===70){s.board.kind='disaster';s.data.water=Array(36).fill(0);s.data.people=Array(36).fill(2);s.data.forecast=0;s.data.material=24;s.target=55;s.goal='Bで堤防（2資材）、Aで避難所（4資材）。全員が決定すると次の洪水。8波から住民を守ろう。';s.data.committed=s.players.map(()=>false);}
 if([82,83,90].includes(n)){grid(s,12,8);s.board.kind='strategy';s.data.units=[];s.data.towers=[];s.data.spawn=0;s.data.health=s.players.map(()=>20);s.data.bank=s.players.map(()=>35);s.data.wave=0;s.target=n===82?10:1;s.goal=n===82?'道の外を選んで塔を建設（10資材）。Aは速射、Bは長射程、Cは減速。10波を守る。':n===83?'自分側へ塔を建設（10資材）。送るボタンで相手へ敵を送り込む（8資材）。城の耐久を守ろう。':'自分の城から採集・射手・戦士を生産（8資材）。敵の司令塔を破壊しよう。';}
 return s;}
function next(s){s.turn=(s.turn+1)%s.players.length;s.ply++;s.data.lastMove=s.t;}
function flips(s,i,side){if(s.board.cells[i])return [];let found=[];for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){if(!dx&&!dy)continue;let x=i%6+dx,y=Math.floor(i/6)+dy,a=[];while(x>=0&&x<6&&y>=0&&y<6&&s.board.cells[y*6+x]===2-side){a.push(y*6+x);x+=dx;y+=dy;}if(x>=0&&x<6&&y>=0&&y<6&&s.board.cells[y*6+x]===side+1)found.push(...a);}return found;}
function path(s,start,side){const todo=[start],seen=new Set(todo);while(todo.length){const i=todo.shift();if(side===0?i<6:i>=30)return true;for(const k of neighbors(i,6,6))if(!s.board.cells[k]&&!seen.has(k)){seen.add(k);todo.push(k);}}return false;}
function line4(s,i,side){const w=s.board.w,h=s.board.h;for(const [dx,dy] of [[1,0],[0,1],[1,1],[1,-1]]){let count=1;for(const sign of [-1,1]){let x=i%w+dx*sign,y=Math.floor(i/w)+dy*sign;while(x>=0&&x<w&&y>=0&&y<h&&s.board.cells[y*w+x]===side+1){count++;x+=dx*sign;y+=dy*sign;}}if(count>=4)return true;}return false;}
function chessLegal(s,a,b){const p=s.data.pieces[a],q=s.data.pieces[b];if(!p||q?.side===p.side)return false;const dx=b%6-a%6,dy=Math.floor(b/6)-Math.floor(a/6);if(p.type==='N')return Math.abs(dx)*Math.abs(dy)===2;if(p.type==='K')return Math.max(Math.abs(dx),Math.abs(dy))===1;if(p.type==='P')return dy===(p.side?1:-1)&&(dx===0&&!q||Math.abs(dx)===1&&q);if(p.type==='R'&&dx&&dy||p.type==='B'&&Math.abs(dx)!==Math.abs(dy))return false;if(!dx&&!dy)return false;const steps=Math.max(Math.abs(dx),Math.abs(dy));for(let k=1;k<steps;k++)if(s.data.pieces[a+Math.sign(dx)*k+Math.sign(dy)*6*k])return false;return true;}
function resolveOrders(s){for(const orders of s.data.orders)for(const o of orders){const u=s.data.units.find(u=>u.id===o.id&&u.hp>0);if(!u)continue;const enemy=s.data.units.find(v=>v.side!==u.side&&v.cell===o.to&&v.hp>0);const distance=Math.abs(o.to%6-u.cell%6)+Math.abs(Math.floor(o.to/6)-Math.floor(u.cell/6));if(enemy&&distance<=(u.type===1?3:1))enemy.hp-=u.type===2?2:1;else if(distance<=(u.type===0?2:1)&&!s.data.units.some(v=>v.hp>0&&v.cell===o.to))u.cell=o.to;}s.data.orders=s.players.map(()=>[]);s.data.committed=s.players.map(()=>false);s.round++;s.ply++;s.data.lastMove=s.t;const alive=s.players.filter(p=>s.data.units.some(u=>u.side===p.side&&u.hp>0));if(alive.length<=1)finish(s,alive[0]?.side??'draw','戦術戦決着');}
export function act(s,side,a){if(s.phase!=='playing'||!s.players[side])return false;const n=s.n,p=s.players[side],i=a.i;const free=[34,70,82,83,90].includes(n);if(!free&&s.turn!==side)return false;
 if(a.type==='select'){s.data.selected[side]=i;return true;}
 if(n===31){const moves=s.board.cells.flatMap((v,k)=>!v&&flips(s,k,side).length?[k]:[]);if(a.type==='pass'&&!moves.length){next(s);if(!s.board.cells.some((v,k)=>!v&&flips(s,k,s.turn).length)){s.players.forEach(p=>p.score=s.board.cells.filter(c=>c===p.side+1).length);byScore(s,'置ける場所がなく対局終了');}return true;}if(!validCell(s,i))return false;const f=flips(s,i,side);if(!f.length)return false;for(const k of [i,...f])s.board.cells[k]=side+1;s.players.forEach(p=>p.score=s.board.cells.filter(c=>c===p.side+1).length);next(s);if(s.board.cells.every(Boolean))byScore(s,'全マス確定');return true;}
 if(n===32){if(a.type==='secondary'&&s.data.flips[side]){s.data.flips[side]=0;s.data.gravity*=-1;for(let x=0;x<7;x++){const stones=[];for(let y=0;y<6;y++)if(s.board.cells[y*7+x])stones.push(s.board.cells[y*7+x]);for(let y=0;y<6;y++)s.board.cells[y*7+x]=0;stones.forEach((c,k)=>s.board.cells[(s.data.gravity===1?6-stones.length+k:k)*7+x]=c);}for(let k=0;k<42;k++)if(s.board.cells[k]&&line4(s,k,s.board.cells[k]-1)){finish(s,s.board.cells[k]-1,'重力反転で4連！');return true;}next(s);return true;}if(!validCell(s,i))return false;const x=i%7;const ys=s.data.gravity===1?[5,4,3,2,1,0]:[0,1,2,3,4,5];const y=ys.find(y=>!s.board.cells[y*7+x]);if(y===undefined)return false;const k=y*7+x;s.board.cells[k]=side+1;p.score++;if(line4(s,k,side))finish(s,side,'4個つながった！');else if(s.board.cells.every(Boolean))finish(s,'draw','引き分け');next(s);return true;}
 if(n===33){if(!validCell(s,i))return false;if(s.data.pieces[i]?.side===side){s.data.selected[side]=i;return true;}const from=s.data.selected[side];if(!Number.isInteger(from)||!chessLegal(s,from,i))return false;const q=s.data.pieces[i];if(q){p.score+=q.type==='K'?100:10;if(q.type==='K')finish(s,side,'相手の王を捕獲！');}s.data.pieces[i]=s.data.pieces[from];s.data.pieces[from]=null;if(s.data.pieces[i].type==='P'&&(i<6||i>=30))s.data.pieces[i].type='R';s.data.selected[side]=-1;next(s);return true;}
 if(n===34){if(a.type==='confirm'){s.data.committed[side]=true;if(s.data.committed.every(Boolean))resolveOrders(s);return true;}if(!validCell(s,i)||s.data.committed[side])return false;const mine=s.data.units.find(u=>u.cell===i&&u.side===side&&u.hp>0);if(mine){s.data.selected[side]=mine.id;return true;}const u=s.data.units.find(u=>u.id===s.data.selected[side]&&u.side===side);if(!u)return false;const list=s.data.orders[side];const old=list.find(o=>o.id===u.id);if(old)old.to=i;else list.push({id:u.id,to:i});return true;}
 if(n===37){if(!validCell(s,i))return false;const enemy=(side+1)%s.players.length;if(a.type==='secondary'&&s.data.sonar[side]>0){s.data.sonar[side]--;s.data.hints??={};s.data.hints[side]={i,count:neighbors(i,6,6,true).concat(i).filter(k=>s.data.fleets[enemy].includes(k)).length};next(s);return true;}if(s.data.shots[side][i])return false;const hit=s.data.fleets[enemy].includes(i);s.data.shots[side][i]=hit?2:1;p.score+=hit?1:0;if(p.score>=6)finish(s,side,'相手艦隊を全滅！');next(s);return true;}
 if(n===38){if(!validCell(s,i)||s.board.cells[i])return false;if(a.type==='secondary'||a.choice===1){if(s.data.bricks[side]<=0||s.data.pawns.includes(i))return false;s.board.cells[i]=-1;if(!path(s,s.data.pawns[0],0)||!path(s,s.data.pawns[1],1)){s.board.cells[i]=0;return false;}s.data.bricks[side]--;}else{if(!neighbors(s.data.pawns[side],6,6).includes(i)||s.data.pawns.includes(i))return false;s.data.pawns[side]=i;p.score=side?Math.floor(i/6):5-Math.floor(i/6);if(side?i>=30:i<6)finish(s,side,'迷路を突破！');}next(s);return true;}
 if(n===35){if(!validCell(s,i)||s.board.cells[i]||!neighbors(s.data.ends[side],6,6).includes(i))return false;const old=s.data.ends[side],type=Math.max(0,a.choice)%3;if(type===0&&Math.floor(old/6)!==Math.floor(i/6)||type===1&&old%6!==i%6)return false;s.board.cells[i]=side+1;s.data.ends[side]=i;p.score+=3;if(i===(side?30:5)){p.score+=30;byScore(s,'目的駅に到着');}next(s);if(s.board.cells.every(Boolean))byScore(s,'路線が埋まった');return true;}
 if(n===36){if(!validCell(s,i)||s.board.cells[i])return false;const hand=s.hands[side],k=a.choice<0?0:a.choice;if(!Number.isInteger(hand[k]))return false;const value=hand.splice(k,1)[0];s.board.cells[i]=value;s.board.owners[i]=side;for(const k of neighbors(i,6,6))if(s.board.cells[k]&&s.board.cells[k]<value)s.board.owners[k]=side;s.players.forEach(p=>p.score=s.board.owners.filter(v=>v===p.side).length);next(s);if(s.hands.every(h=>!h.length))byScore(s,'数字の配置が完了');return true;}
 if(n===39){if(a.type==='pass'){s.hands[side].push([int(s,6),int(s,6)]);next(s);return true;}if(!validCell(s,i)||s.data.tiles[i])return false;const k=a.choice<0?0:a.choice,tile=s.hands[side][k];if(!tile||!neighbors(i,6,6).some(k=>s.data.tiles[k]?.some(n=>tile.includes(n))))return false;s.data.tiles[i]=tile;s.board.cells[i]=side+1;s.hands[side].splice(k,1);p.score+=tile[0]+tile[1];if(!s.hands[side].length)finish(s,side,'ドミノを使い切った！');else if(s.data.tiles.every(Boolean))byScore(s,'航路完成');next(s);return true;}
 if(n===40){if(!validCell(s,i))return false;if(a.choice===1){if(p.coins<4||s.board.cells[i])return false;p.coins-=4;s.board.cells[i]=side+1;p.score+=6;}else if(a.choice===2){if(p.coins<3)return false;p.coins-=3;p.score+=4;}else{if(s.board.cells[i]&&s.board.cells[i]!==side+1)return false;p.coins+=s.board.resources[i]+(s.board.cells[i]?2:0);p.score++;}next(s);if(s.ply>=s.players.length*8){s.players.forEach(p=>p.score+=Math.floor(p.coins/2));byScore(s,'8ラウンド終了');}return true;}
 if(n===70){if(a.type==='confirm'){s.data.committed[side]=true;if(s.data.committed.every(Boolean)){const x=s.data.forecast;for(let y=0;y<6;y++){const k=y*6+x;if(s.board.cells[k]!==2){s.data.water[k]++;if(s.board.cells[k]!==1)s.data.people[k]=Math.max(0,s.data.people[k]-1);}}s.data.material+=8;s.round++;s.data.forecast=int(s,6);s.data.committed=s.players.map(()=>false);s.progress=s.data.people.reduce((a,b)=>a+b,0);if(s.round>8)finish(s,s.progress>=55?'team':'failed',s.progress+'人が避難できた');}return true;}if(!validCell(s,i)||s.board.cells[i])return false;const kind=a.choice===1?2:1,cost=kind===2?2:4;if(s.data.material<cost)return false;s.data.material-=cost;s.board.cells[i]=kind;return true;}
 if([82,83,90].includes(n)){const bank=s.data.bank;if(n===90||a.type==='send'){if(bank[side]<8)return false;bank[side]-=8;const enemy=(side+1)%s.players.length;s.data.units.push({side:n===90?side:-1,target:enemy,x:n===90?(side?11:0):0,y:3.5,hp:a.choice===2?8:4,speed:.5+(a.choice===0?.3:0),type:a.choice>=0?a.choice:1,attack:0});return true;}if(!validCell(s,i)||i%12===0||Math.floor(i/12)===3||Math.floor(i/12)===4||s.data.towers.some(t=>t.cell===i)||bank[side]<10)return false;if(n===83&&Math.floor(i/12)%2!==side%2)return false;bank[side]-=10;s.data.towers.push({cell:i,side,type:Math.max(0,a.choice)%3,cooldown:0});return true;}
 return false;}
export function step(s,inputs,dt){const n=s.n;if(n===34&&s.t-s.data.lastMove>30)resolveOrders(s);
 if([82,83,90].includes(n)){for(let side=0;side<s.players.length;side++)s.data.bank[side]+=dt*(n===90?1.5:.6);s.data.spawn-=dt;if(s.data.spawn<=0&&n!==90){s.data.spawn=12;s.data.wave++;for(let k=0;k<2+s.data.wave;k++)s.data.units.push({side:-1,target:n===82?0:k%s.players.length,x:-k*.35,y:3.5,hp:3+s.data.wave,speed:.6,type:0});}
 for(const u of s.data.units){if(u.hp<=0)continue;if(n===90&&u.type===0){s.data.bank[u.side]+=dt*1.1;u.x+=(u.side?-1:1)*dt*.15;continue;}u.x+=(n===90&&u.side===1?-1:1)*dt*u.speed;for(const tower of s.data.towers){const x=tower.cell%12,y=Math.floor(tower.cell/12);if(n===83&&tower.side!==u.target)continue;if(Math.hypot(x-u.x,y-u.y)<(tower.type===1?4:2.3)&&tower.cooldown<=0){u.hp-=tower.type===1?2:1;tower.cooldown=tower.type===0?.45:.9;if(tower.type===2)u.speed=Math.min(u.speed,.3);}}if(n===90){const v=s.data.units.find(v=>v.side!==u.side&&v.hp>0&&Math.abs(v.x-u.x)<(u.type===1?2:.6));if(v){u.x-=(u.side===1?-1:1)*dt*u.speed;u.attack-=dt;if(u.attack<=0){v.hp-=u.type===2?2:1;u.attack=.7;}}}if(u.x>=11.5||n===90&&u.x<=-.5){s.data.health[u.target]-=n===90?3:1;u.hp=0;}if(u.hp<=0){if(n===82)s.data.bank.forEach((_,i)=>s.data.bank[i]+=2);else s.data.bank[u.target]+=2;}}
 for(const t of s.data.towers)t.cooldown-=dt;s.data.units=s.data.units.filter(u=>u.hp>0).slice(-150);for(const p of s.players)p.score=s.data.health[p.side]*10+Math.floor(s.data.bank[p.side]);if(n===82){s.progress=s.data.wave-1;if(s.data.health[0]<=0)finish(s,'failed','拠点が陥落');else if(s.data.wave>=10&&!s.data.units.length)winTeam(s,'10波を防衛！');if(s.data.wave>=10)s.data.spawn=9999;}else {const lost=s.data.health.findIndex(h=>h<=0);if(lost>=0)finish(s,(lost+1)%s.players.length,'相手の司令塔を破壊！');}return;}
 if(![34,70].includes(n)&&s.t-s.data.lastMove>35){if(n===31)act(s,s.turn,{type:'pass'});else next(s);s.message='持ち時間を過ぎたため手番を交代';s.data.lastMove=s.t;}
}
export function view(s,side){const v=publicView(s,side);if(s.n===37){v.board.cells=copy(s.data.shots[side]);v.private={fleet:s.data.fleets[side],hint:s.data.hints?.[side]};delete v.data.fleets;delete v.data.shots;delete v.data.hints;}if(s.n===34){v.private={orders:copy(s.data.orders[side])};delete v.data.orders;}return v;}
