import {base,int,shuffle,finish,winTeam,byScore,publicView,copy} from './common.mjs';
export const realtime=false;
const card=(id,rank,suit=0)=>({id,rank,suit});
function deck(s){return shuffle(s,Array.from({length:52},(_,i)=>card('c'+i,3+i%13,Math.floor(i/13))));}
function draw(s,side,count=1){for(let i=0;i<count;i++){if(!s.data.decks[side].length){s.data.decks[side]=shuffle(s,s.data.discards[side]);s.data.discards[side]=[];}const c=s.data.decks[side].pop();if(c)s.hands[side].push(c);}}
function next(s){s.turn=(s.turn+1)%s.players.length;s.ply++;s.data.lastMove=s.t;}
export function create(spec,players,seed){const s=base(spec,players,seed),n=s.n;s.data.lastMove=0;s.hands=s.players.map(()=>[]);s.data.table=[];s.data.market=[];s.data.committed=s.players.map(()=>false);for(const p of s.players){p.coins=30;p.hp=30;}
 if([41,44,48].includes(n)){s.data.deck=deck(s);for(const h of s.hands)for(let i=0;i<(n===48?10:8);i++)h.push(s.data.deck.pop());s.hands.forEach(h=>h.sort((a,b)=>a.rank-b.rank));}
 if(n===41){s.goal='同じ枚数で、場より強い数字を出す。8切り・4枚革命あり。最初に手札をなくそう。';s.data.reverse=false;s.data.passes=0;s.data.pile=null;}
 if(n===42){s.goal='数字を入力して秘密入札。全員が決定すると開札。自分だけの価値ヒントを参考に8箱を競う。';s.data.bids={};auction(s);}
 if(n===43){s.goal='手札の数字を小さい順に、相談しながら1枚ずつ出す。誰かにより小さい手札があるとハートを失う。';const d=shuffle(s,Array.from({length:60},(_,i)=>card('n'+i,i+1)));for(const h of s.hands)h.push(...d.splice(0,5).sort((a,b)=>a.rank-b.rank));s.data.hearts=3;s.target=players.length*5;}
 if(n===44){s.goal='同じマークがあれば必ず出す。スペードが切り札。4人では向かいの席とペアで8トリック。';s.data.trick=[];s.data.trump=0;s.data.teams=[0,0];}
 if(n===45){s.goal='共通市場から商品を選び、同じ色を集めて商会を作る。3枚セットは大きな得点。8巡。';s.data.market=Array.from({length:6},(_,i)=>card('m'+i,1+int(s,5),int(s,4)));s.data.collections=s.players.map(()=>[]);}
 if(n===46){s.goal='手札で攻撃・盾・回復・コイン。市場の札を購入してデッキを育てる。全員の終了後に敵が反撃。';s.data.decks=s.players.map((_,j)=>shuffle(s,Array.from({length:10},(_,i)=>({...card('d'+j+'-'+i,i<5?1:i<8?2:3,i<5?0:i<8?1:2),type:i<5?'coin':i<8?'attack':'shield'}))));s.data.discards=s.players.map(()=>[]);s.data.enemy={hp:55,max:55,attack:9};s.data.teamHp=80;s.data.block=0;s.data.floor=1;s.target=3;for(const p of s.players){p.coins=0;draw(s,p.side,5);}s.data.market=[{id:'blade',type:'attack',rank:7,cost:4,suit:1},{id:'guard',type:'shield',rank:7,cost:3,suit:2},{id:'heal',type:'heal',rank:8,cost:4,suit:3},{id:'gold',type:'coin',rank:3,cost:3,suit:0}];}
 if(n===47){s.goal='移動・防御・攻撃・回復を3枚まで予約して決定。同時に解決し、相手のHPを0にする。';s.data.orders=s.players.map(()=>[]);for(const p of s.players){p.pos=p.side?7:1;s.hands[p.side]=Array.from({length:6},(_,i)=>card('a'+p.side+'-'+i,1+i%4));}}
 if(n===48){s.goal='どちらかの場札と数字が1つ違う札を素早く出す。全員が出せない時は場を更新。先に10枚出そう。';s.data.table=[s.data.deck.pop(),s.data.deck.pop()];}
 if(n===49){s.goal='同じ絵柄を2枚めくる。Bで一度だけ伏せた札を入れ替え、相手の記憶を崩そう。';s.board={w:6,h:4,cells:Array(24).fill(0),kind:'memory'};s.data.solution=shuffle(s,Array.from({length:24},(_,i)=>1+i%12));s.data.open=[];s.data.matched=[];s.data.swaps=s.players.map(()=>1);s.data.resolveAt=0;}
 if(n===50){s.goal='順番に値を上げるか降りる。最後の1人が購入。同じ画家の作品セットで得点。8作品。';s.data.collections=s.players.map(()=>[]);s.data.bid=0;s.data.bidder=-1;s.data.passed=[];s.data.art=card('art1',1+int(s,5),int(s,4));}
 return s;}
function auction(s){const value=6+int(s,20);s.data.value=value;s.data.treasure={min:Math.max(0,value-6),max:value+6};s.data.secret=s.players.map(()=>({hint:value-2+int(s,5)}));s.data.bids={};}
function settleArt(s){const side=s.data.bidder;if(side>=0){s.players[side].coins-=s.data.bid;s.data.collections[side].push(s.data.art);s.players[side].score=collectionScore(s.data.collections[side]);}if(s.round++>=8){s.players.forEach(p=>p.score+=Math.floor(p.coins/3));byScore(s,'美術館が完成');}else{s.data.art=card('art'+s.round,1+int(s,5),int(s,4));s.data.bid=0;s.data.bidder=-1;s.data.passed=[];s.turn=side>=0?side:0;}s.data.lastMove=s.t;}
const collectionScore=cards=>{const counts=[0,0,0,0];for(const c of cards)counts[c.suit]++;return cards.reduce((v,c)=>v+c.rank,0)+counts.reduce((v,n)=>v+n*n*3,0);};
function resolveProgram(s){const incoming=s.players.map(()=>0);for(let k=0;k<3;k++){for(const p of s.players){p.block=0;const c=s.data.orders[p.side][k];if(c?.rank===1)p.pos=Math.max(0,Math.min(8,p.pos+(p.side?-2:2)));if(c?.rank===2)p.block=6;if(c?.rank===4)p.hp=Math.min(30,p.hp+4);}for(const p of s.players){const c=s.data.orders[p.side][k];if(c?.rank!==3)continue;const other=s.players.find(q=>q.side!==p.side&&q.hp>0&&Math.abs(q.pos-p.pos)<=3);if(other)incoming[other.side]+=Math.max(0,8-other.block);}s.players.forEach(p=>{p.hp-=incoming[p.side];incoming[p.side]=0;});}const alive=s.players.filter(p=>p.hp>0);if(alive.length<2)finish(s,alive[0]?.side??'draw','予約した連携で決着');s.players.forEach(p=>{p.score=30-Math.min(...s.players.filter(q=>q.side!==p.side).map(q=>q.hp));s.hands[p.side]=Array.from({length:6},(_,i)=>card('a'+s.round+'-'+p.side+'-'+i,1+int(s,4)));});s.round++;s.data.orders=s.players.map(()=>[]);s.data.committed=s.players.map(()=>false);s.data.lastMove=s.t;}
export function act(s,side,a){if(s.phase!=='playing'||!s.players[side])return false;const n=s.n,p=s.players[side],h=s.hands[side],i=a.i;
 if([41,44,45,49,50].includes(n)&&s.turn!==side)return false;
 if(n===41){if(a.type==='pass'){if(!s.data.pile)return false;s.data.passes++;next(s);if(s.data.passes>=s.players.length-1){s.turn=s.data.pile.side;s.data.pile=null;s.data.passes=0;}return true;}const c=h[i];if(!c)return false;const count=Math.max(1,Math.min(4,a.choice||1)),cards=h.filter(v=>v.rank===c.rank).slice(0,count);if(cards.length<count)return false;const pile=s.data.pile;if(pile&&(pile.count!==count||(s.data.reverse?c.rank>=pile.rank:c.rank<=pile.rank)))return false;s.hands[side]=h.filter(v=>!cards.includes(v));s.data.table=cards;s.data.pile={rank:c.rank,count,side};s.data.passes=0;p.score+=count;if(count===4)s.data.reverse=!s.data.reverse;if(!s.hands[side].length)finish(s,side,'手札を使い切った！');if(c.rank===8)s.data.pile=null;else next(s);s.data.lastMove=s.t;return true;}
 if(n===42){if(s.data.bids[side]!==undefined)return false;const bid=Number(a.value);if(!Number.isInteger(bid)||bid<0||bid>p.coins)return false;s.data.bids[side]=bid;s.data.committed[side]=true;if(Object.keys(s.data.bids).length===s.players.length){const max=Math.max(...Object.values(s.data.bids)),tied=s.players.filter(p=>s.data.bids[p.side]===max),winner=tied[(s.round-1)%tied.length];winner.coins-=max;winner.score+=s.data.value;s.message=winner.name+'が'+max+'で落札。宝箱の価値は'+s.data.value;s.round++;s.data.committed=s.players.map(()=>false);if(s.round>8){s.players.forEach(p=>p.score+=p.coins);byScore(s,'8箱の競りが終了');}else auction(s);}return true;}
 if(n===43){if(a.type==='hint'){s.message=p.name+'：'+(h[0]?.rank<=20?'小さな数字があります':'先にどうぞ');return true;}const c=h[i];if(!c)return false;const min=Math.min(...s.hands.flat().map(c=>c.rank));if(c.rank!==min){s.data.hearts--;s.message='より小さい数字が残っていた！';}else s.message=p.name+'が'+c.rank+'を出した';h.splice(i,1);s.data.table=[c];s.progress++;if(s.data.hearts<=0)finish(s,'failed','ハートを使い切った');else if(s.progress>=s.target)winTeam(s,'数字を最後までつないだ！');return true;}
 if(n===44){const c=h[i],lead=s.data.trick[0]?.card.suit;if(!c||lead!==undefined&&c.suit!==lead&&h.some(c=>c.suit===lead))return false;h.splice(i,1);s.data.trick.push({side,card:c});s.data.table=s.data.trick.map(t=>t.card);if(s.data.trick.length===s.players.length){const t=s.data.trick;const relevant=t.some(x=>x.card.suit===s.data.trump)?s.data.trump:t[0].card.suit;const winner=t.filter(x=>x.card.suit===relevant).sort((a,b)=>b.card.rank-a.card.rank)[0].side;s.data.teams[winner%2]++;s.players.forEach(p=>p.score=s.data.teams[p.side%2]);s.turn=winner;s.data.trick=[];s.round++;s.message=s.players[winner].name+'のトリック';if(s.hands.every(h=>!h.length))finish(s,s.data.teams[0]===s.data.teams[1]?'draw':'team'+(s.data.teams[0]>s.data.teams[1]?0:1),'8トリック終了');s.data.lastMove=s.t;}else next(s);return true;}
 if(n===45){const c=s.data.market[i];if(!c)return false;s.data.collections[side].push(c);p.score=collectionScore(s.data.collections[side]);s.data.market[i]=card('m'+s.ply+'-'+i,1+int(s,5),int(s,4));next(s);if(s.ply>=8*s.players.length)byScore(s,'商会の仕入れ終了');return true;}
 if(n===46){if(s.data.committed[side])return false;if(a.type==='buy'){const c=s.data.market[i];if(!c||p.coins<c.cost)return false;p.coins-=c.cost;s.data.discards[side].push({...c,id:c.id+'-'+s.ply++});return true;}if(a.type==='confirm'){s.data.committed[side]=true;if(s.data.committed.every(Boolean)){s.data.teamHp-=Math.max(0,s.data.enemy.attack-s.data.block);s.data.block=0;if(s.data.teamHp<=0){finish(s,'failed','パーティーが全滅');return true;}for(const p of s.players){s.data.discards[p.side].push(...s.hands[p.side]);s.hands[p.side]=[];p.coins=0;draw(s,p.side,5);}s.data.committed=s.players.map(()=>false);s.round++;s.data.lastMove=s.t;}return true;}const c=h[i];if(!c)return false;h.splice(i,1);s.data.discards[side].push(c);if(c.type==='coin')p.coins+=c.rank;if(c.type==='attack'){s.data.enemy.hp-=c.rank;p.score+=c.rank;}if(c.type==='shield')s.data.block+=c.rank;if(c.type==='heal')s.data.teamHp=Math.min(80,s.data.teamHp+c.rank);if(s.data.enemy.hp<=0){s.progress++;s.data.floor++;if(s.data.floor>3)winTeam(s,'ダンジョンを踏破！');else{s.data.enemy={hp:45+s.data.floor*20,max:45+s.data.floor*20,attack:7+s.data.floor*3};s.data.teamHp=Math.min(80,s.data.teamHp+15);}}return true;}
 if(n===47){if(s.data.committed[side])return false;if(a.type==='confirm'){s.data.committed[side]=true;if(s.data.committed.every(Boolean))resolveProgram(s);return true;}if(a.type==='undo'){h.push(...s.data.orders[side]);s.data.orders[side]=[];return true;}if(!h[i]||s.data.orders[side].length>=3)return false;s.data.orders[side].push(h.splice(i,1)[0]);return true;}
 if(n===48){if(a.type==='pass'){if(s.hands.some(h=>h.some(c=>s.data.table.some(t=>Math.abs(c.rank-t.rank)===1))))return false;s.data.table=[card('r'+s.ply++,3+int(s,13)),card('r'+s.ply++,3+int(s,13))];return true;}const c=h[i];if(!c)return false;let target=a.choice>=0?a.choice:s.data.table.findIndex(t=>Math.abs(t.rank-c.rank)===1);if(!s.data.table[target]||Math.abs(s.data.table[target].rank-c.rank)!==1)return false;s.data.table[target]=h.splice(i,1)[0];p.score++;if(!h.length)finish(s,side,'10枚を先に出し切った！');return true;}
 if(n===49){if(!Number.isInteger(i)||i<0||i>=24||s.data.matched.includes(i)||s.data.resolveAt>s.t)return false;if(a.type==='secondary'&&s.data.swaps[side]&&a.j>=0&&a.j<24&&!s.data.matched.includes(a.j)&&!s.data.open.length){[s.data.solution[i],s.data.solution[a.j]]=[s.data.solution[a.j],s.data.solution[i]];s.data.swaps[side]=0;next(s);return true;}if(s.data.open.includes(i))return false;s.data.open.push(i);s.board.cells[i]=s.data.solution[i];if(s.data.open.length===2){if(s.data.solution[s.data.open[0]]===s.data.solution[i]){s.data.matched.push(...s.data.open);s.data.open=[];p.score++;if(s.data.matched.length===24)byScore(s,'すべてのペアを発見');}else s.data.resolveAt=s.t+1.4;}return true;}
 if(n===50){if(a.type==='pass'){s.data.passed.push(side);}else{const bid=Number(a.value);if(!Number.isInteger(bid)||bid<=s.data.bid||bid>p.coins)return false;s.data.bid=bid;s.data.bidder=side;}const active=s.players.filter(p=>!s.data.passed.includes(p.side));if(active.length<=1){settleArt(s);return true;}do{next(s);}while(s.data.passed.includes(s.turn));if(s.turn===s.data.bidder)settleArt(s);return true;}
 return false;}
export function step(s,inputs,dt){if(s.n===49&&s.data.resolveAt&&s.t>=s.data.resolveAt){for(const i of s.data.open)s.board.cells[i]=0;s.data.open=[];s.data.resolveAt=0;next(s);}if(s.n===47&&s.t-s.data.lastMove>40)resolveProgram(s);if([41,44,45,49,50].includes(s.n)&&s.t-s.data.lastMove>40){if([41,50].includes(s.n))act(s,s.turn,{type:'pass'});else if(s.n===44){const h=s.hands[s.turn],lead=s.data.trick[0]?.card.suit;act(s,s.turn,{i:Math.max(0,h.findIndex(c=>c.suit===lead))});}else next(s);s.data.lastMove=s.t;}}
export function view(s,side){const v=publicView(s,side);delete v.data.value;delete v.data.bids;if(s.n===47){v.private={orders:copy(s.data.orders[side])};delete v.data.orders;}if(s.n===46){v.private={deckCount:s.data.decks[side].length,discard:copy(s.data.discards[side])};delete v.data.decks;delete v.data.discards;}return v;}
