import {base,grid,int,shuffle,neighbors,validCell,finish,winTeam,byScore,publicView,copy} from './common.mjs';
export const realtime=false;
const N=[0,1,2,3];
function refreshGoal(s){if(s.progress>=s.target)winTeam(s,'全員でミッション達成！');}
export function create(spec,players,seed){const s=base(spec,players,seed),n=s.n;grid(s,6,6);s.data.choice=0;s.data.lastMove=0;s.data.selected={};s.data.cooldowns=s.players.map(()=>0);s.target=10;
 if(n===2){grid(s,8,players.length*2);s.board.kind='switch';s.data.pawns=s.players.map((_,i)=>i*16);s.data.gates=s.players.map(()=>false);s.goal='自分の色の通路を進み、丸いスイッチを押すと相棒の扉が開く。全員で右端の出口へ。';s.target=players.length;}
 if(n===9){s.board.kind='circuit';s.board.cells=Array.from({length:36},()=>int(s,4));s.data.solution=Array.from({length:36},()=>int(s,4));s.data.secret=s.players.map((_,side)=>({clues:s.data.solution.map((v,i)=>i%players.length===side?v:null)}));s.data.power=100;s.goal='回路をタップして回転。自分だけに見える正しい向きを伝え合う。担当はマス番号の色で表示。決定で通電。';s.target=36;}
 if([58,76].includes(n)){s.board.kind=n===58?'guide':'teleport';s.board.cells=Array(36).fill(0);for(const i of [7,8,9,10,16,19,20,21,22,28])s.board.cells[i]=-1;s.data.pawns=n===58?[30]:[30,5];s.data.exit=n===58?5:35;s.data.portals=[null,null];s.goal=n===58?'P1は地図を見て、定型ヒントでP2を案内。P2は矢印で一歩ずつ動き、星へ。':'自分の駒の隣を選んで移動。B→マスで相棒の出口を設置。両方の駒を右下の出口へ。';s.target=n===58?1:2;}
 if(n===63){s.board.kind='rail';s.data.switches=Array(6).fill(0);s.data.trains=[];s.data.spawn=0;s.data.lives=3;s.goal='各自の色の分岐をタップして切り替える。列車と同じ色の駅へ案内。衝突・誤着に注意。';s.target=16;}
 if(n===64){s.board.kind='factory';s.data.belt=Array(12).fill(null);s.data.stock=players.map(()=>0);s.data.products=[];s.data.tick=0;s.goal='担当部品をAで投入。ベルトの空きマスを選んで部品をつなぐ。全員分の部品が揃うと完成品。';s.target=12;grid(s,12,1);}
 if(n===66){grid(s,4,3);s.board.kind='supply';s.data.ships=Array.from({length:4},(_,i)=>({fuel:0,oxygen:0,repair:0,need:[3,4,5][i%3],deadline:50+i*15}));s.data.power=12;s.data.charge=0;s.goal='船を選び、Aで燃料、Bで酸素、Cで修理。共有電力を分配し、出港時刻までに補給。';s.target=8;}
 if(n===67){grid(s,8,3);s.board.kind='bridge';s.data.stock=s.players.map(()=>8);s.data.load=0;s.goal='上段に床（A）、下段に支柱（B）を分担して建設。決定で荷台を渡す。床だけの橋は重さに耐えません。';s.target=8;}
 if(n===71){s.board.kind='orbs';s.data.boards=s.players.map(()=>Array.from({length:36},()=>1+int(s,4)));s.data.shields=s.players.map(()=>0);s.goal='同色の隣接オーブ3個以上をタップで消す。大連鎖は相手におじゃまを送る。Bで盾をためる。';}
 if(n===72){grid(s,6,10);s.board.kind='falling';s.data.boards=s.players.map(()=>Array(60).fill(0));s.data.blocks=s.players.map(()=>({x:2,y:0,rotation:0,color:1+int(s,4)}));s.data.fall=0;s.data.garbage=s.players.map(()=>0);s.goal='左右で移動、Aで回転、Bで一気に落とす。列を消しておじゃまを送る。天井まで積むと敗北。';}
 if(n===73){grid(s,8,6);s.board.kind='mines';s.board.cells=Array(48).fill(-2);s.data.mines=shuffle(s,Array.from({length:48},(_,i)=>i)).slice(0,8);s.data.flags=[];s.data.hearts=3;s.goal='マスを開く。数字は周囲の地雷数。Bを選んで旗。ハート3個で地雷以外をすべて開こう。';s.target=40;s.data.first=true;}
 if(n===75){s.board.kind='laser';s.data.mirrors=[{i:20,rot:1},{i:8,rot:0},{i:11,rot:1}];s.data.path=[];s.data.receiver=5;s.goal='自分の色の鏡を回転し、左の光を右上の受光器へ。スラッシュの向きで反射方向が変わる。';s.target=1;}
 if(n===77){s.board.kind='equation';s.board.cells=Array.from({length:36},()=>1+int(s,9));s.board.owners=Array(36).fill(-1);s.data.target=6+int(s,12);s.goal='隣り合う2マスを選び、足す・引く・掛けるで目標の数を作って占領。合計領地を競おう。';}
 if(n===78){grid(s,6,2);s.board.kind='time';s.data.past=[0,0,0,0,0,0];s.data.future=[0,0,0,0,0,0];s.data.solution=[2,1,3,2,1,3];s.data.secret=s.players.map((_,i)=>({clues:i===1?[2,1,3,2,1,3]:null}));s.goal='P1は過去の種・橋・箱を変更。P2は未来の手掛かりを伝え、育った姿を調査。6つの鍵を揃えよう。';s.target=6;}
 if(n===79){s.board.kind='pipes';s.board.cells=Array.from({length:36},()=>int(s,4));s.board.owners=Array(36).fill(-1);s.data.water=s.players.map(()=>0);s.goal='共通の水源から自分の槽へパイプをつなぐ。Aで回転、Bで分岐を所有。通水した長さで貯水。';}
 if(n===80){grid(s,5,1);s.board.kind='relay';s.data.number=1;s.data.target=24;s.data.sequence=[];s.data.secret=s.players.map((_,i)=>({numbers:[i+1,i+2,i+3]}));s.goal='手番のプレイヤーが担当数字と演算を選ぶ。現在値を目標と同じにすると次の数列へ。10問をつなごう。';s.target=10;}
 if(n===95){s.board.kind='sand';s.data.wave=0;s.data.water=Array(36).fill(0);s.data.sand=30;s.data.clock=0;s.data.flagHp=10;s.goal='Aで砂壁、Bで水路。10秒ごとの波が上から押し寄せる。旗の前に壁と水の逃げ道を作る。8波を守ろう。';s.target=8;}
 if(n===97){grid(s,4,3);s.board.kind='firework';s.data.mix=[0,0,0];s.data.order=[1,2,1];s.data.readyAt={};s.goal='P1は3色の粉を調合。仲間は打ち上げを担当。お題と同じ色数にして、全員が2秒以内に決定。';s.target=8;}
 if(n===98){grid(s,5,1);s.board.kind='train-code';s.data.solution=shuffle(s,[1,2,3,4,5]);s.data.answer=[];s.data.secret=s.players.map((_,i)=>({clues:s.data.solution.map((v,k)=>k%players.length===i?{position:k+1,station:v}:null).filter(Boolean)}));s.goal='自分の車両の停車順の手掛かりを伝え合う。駅を順に選び、決定で終着駅へ。Bで一駅戻す。';s.target=1;}
 return s;}
function orbGroup(b,i){const todo=[i],seen=new Set(todo),v=b[i];while(todo.length){const k=todo.pop();for(const j of neighbors(k,6,6))if(b[j]===v&&!seen.has(j)){seen.add(j);todo.push(j);}}return [...seen];}
function settleOrbs(s,side,cells){const b=s.data.boards[side];for(const k of cells)b[k]=0;for(let x=0;x<6;x++){const values=[];for(let y=5;y>=0;y--)if(b[y*6+x])values.push(b[y*6+x]);for(let y=5;y>=0;y--)b[y*6+x]=values[5-y]||1+int(s,4);}}
function fallingCells(b){return b.rotation%2?[b.y*6+b.x,b.y*6+b.x+1]:[b.y*6+b.x,(b.y+1)*6+b.x];}
function canFall(board,b){return b.x>=0&&b.x<(b.rotation%2?5:6)&&b.y>=0&&fallingCells(b).every(i=>i>=0&&i<60&&!board[i]);}
function lock(s,side){const b=s.data.blocks[side],board=s.data.boards[side];for(const k of fallingCells(b))if(k>=0&&k<60)board[k]=b.color;let lines=0;for(let y=9;y>=0;y--)if(board.slice(y*6,y*6+6).every(Boolean)){board.splice(y*6,6);board.unshift(0,0,0,0,0,0);lines++;y++;}s.players[side].score+=lines*100;const cancel=Math.min(s.data.garbage[side],lines);s.data.garbage[side]-=cancel;if(lines>cancel)s.data.garbage[(side+1)%s.players.length]+=lines-cancel;while(s.data.garbage[side]>0){board.splice(0,6);const hole=int(s,6);board.push(...Array.from({length:6},(_,x)=>x===hole?0:5));s.data.garbage[side]--;}s.data.blocks[side]={x:2,y:0,rotation:0,color:1+int(s,4)};if(!canFall(board,s.data.blocks[side]))finish(s,(side+1)%s.players.length,'相手のフィールドがいっぱいになった');}
function laser(s){let x=-1,y=3,dx=1,dy=0;const path=[];for(let k=0;k<40;k++){x+=dx;y+=dy;if(x<0||x>=6||y<0||y>=6)break;const i=y*6+x;path.push(i);if(i===s.data.receiver){s.progress=1;refreshGoal(s);break;}const m=s.data.mirrors.find(m=>m.i===i);if(m){const old=dx;if(m.rot===0){dx=-dy;dy=-old;}else{dx=dy;dy=old;}}}s.data.path=path;}
export function act(s,side,a){const n=s.n,p=s.players[side],i=a.i;if(!p||s.phase!=='playing')return false;
 if(a.type==='hint'){s.message=p.name+'：'+(a.text||['上へ','右へ','下へ','左へ','待って','今です'][Math.max(0,a.choice)%6]);return true;}
 if(n===2){if(!validCell(s,i)||Math.floor(i/16)!==side)return false;const from=s.data.pawns[side];if(!neighbors(from,8,s.board.h).includes(i))return false;if(i%8===5&&!s.data.gates[side])return false;s.data.pawns[side]=i;if(i%8===2)s.data.gates[(side+1)%s.players.length]=true;s.progress=s.data.pawns.filter(k=>k%8===7).length;refreshGoal(s);return true;}
 if(n===9){if(a.type==='confirm'){s.progress=s.board.cells.filter((v,k)=>v===s.data.solution[k]).length;s.data.power-=Math.ceil((36-s.progress)/3);s.message=s.progress+'/36 回路が正しい向き';if(s.data.power<=0)finish(s,'failed','過負荷で電力がなくなった');refreshGoal(s);return true;}if(!validCell(s,i)||i%s.players.length!==side)return false;s.board.cells[i]=(s.board.cells[i]+1)%4;return true;}
 if(n===58){if(side===0)return false;const from=s.data.pawns[0],dir=Math.max(0,a.choice)%4,j=[from-6,from+1,from+6,from-1][dir];if(!neighbors(from,6,6).includes(j)||s.board.cells[j]===-1){s.message='壁に当たった';return true;}s.data.pawns[0]=j;if(j===s.data.exit){s.progress=1;refreshGoal(s);}return true;}
 if(n===76){if(!validCell(s,i)||s.board.cells[i]===-1)return false;if(a.choice===1||a.type==='secondary'){s.data.portals[(side+1)%2]=i;return true;}const from=s.data.pawns[side];if(!neighbors(from,6,6).includes(i))return false;s.data.pawns[side]=i;if(i===(side?12:23)&&s.data.portals[side]!==null)s.data.pawns[side]=s.data.portals[side];s.progress=s.data.pawns.filter(k=>k===35).length;refreshGoal(s);return true;}
 if(n===63){const k=i%6;if(k<0||k%s.players.length!==side)return false;s.data.switches[k]=(s.data.switches[k]+1)%3;return true;}
 if(n===64){const k=i>=0?i:0;if(k<0||k>=12)return false;let item=s.data.belt[k];if(!item){if(k>1)return false;item={parts:[],age:0};s.data.belt[k]=item;}if(item.parts.includes(side))return false;item.parts.push(side);if(item.parts.length===s.players.length){s.progress++;p.score++;s.data.belt[k]=null;refreshGoal(s);}return true;}
 if(n===66){const k=i>=0?i%4:0,ship=s.data.ships[k],type=['fuel','oxygen','repair'][Math.max(0,a.choice)%3];if(s.data.power<1||ship[type]>=ship.need)return false;ship[type]++;s.data.power--;if(['fuel','oxygen','repair'].every(t=>ship[t]>=ship.need)){s.progress++;s.data.ships[k]={fuel:0,oxygen:0,repair:0,need:3+int(s,3),deadline:s.t+65};refreshGoal(s);}return true;}
 if(n===67){if(a.type==='confirm'){let safe=0;for(let x=0;x<8;x++)if(s.board.cells[x]&&s.board.cells[8+x])safe++;s.progress=safe;s.message=safe===8?'橋は安定している':'床と支柱の両方が必要です';refreshGoal(s);return true;}if(!validCell(s,i)||s.data.stock[side]<=0)return false;const x=i%8,k=(a.choice===1?8:0)+x;if(s.board.cells[k])return false;s.board.cells[k]=side+1;s.data.stock[side]--;return true;}
 if(n===71){if(a.type==='secondary'){s.data.shields[side]=Math.min(3,s.data.shields[side]+1);p.score=Math.max(0,p.score-15);return true;}if(!validCell(s,i))return false;const b=s.data.boards[side];if(b[i]===5){b[i]=1+int(s,4);return true;}const cells=orbGroup(b,i);if(cells.length<3)return false;p.score+=cells.length*cells.length*5;settleOrbs(s,side,cells);const enemy=(side+1)%s.players.length,damage=Math.max(0,cells.length-3-s.data.shields[enemy]);s.data.shields[enemy]=Math.max(0,s.data.shields[enemy]-(cells.length-3));for(let k=0;k<damage;k++)s.data.boards[enemy][int(s,36)]=5;return true;}
 if(n===72){const b=s.data.blocks[side],board=s.data.boards[side];if(a.type==='secondary'||a.choice===3){while(canFall(board,{...b,y:b.y+1}))b.y++;lock(s,side);return true;}const candidate={...b};if(a.choice===0)candidate.x--;else if(a.choice===1)candidate.x++;else candidate.rotation=1-candidate.rotation;if(!canFall(board,candidate))return false;s.data.blocks[side]=candidate;return true;}
 if(n===73){if(!validCell(s,i)||s.board.cells[i]>=0)return false;if(a.choice===1||a.type==='secondary'){if(s.data.flags.includes(i))s.data.flags=s.data.flags.filter(k=>k!==i);else s.data.flags.push(i);return true;}if(s.data.flags.includes(i))return false;if(s.data.first){s.data.first=false;if(s.data.mines.includes(i)){const replacement=Array.from({length:48},(_,k)=>k).find(k=>k!==i&&!s.data.mines.includes(k));s.data.mines[s.data.mines.indexOf(i)]=replacement;}}if(s.data.mines.includes(i)){s.data.hearts--;s.board.cells[i]=-3;if(s.data.hearts<=0)finish(s,'failed','ハートがなくなった');return true;}const todo=[i],seen=new Set();while(todo.length){const k=todo.pop();if(seen.has(k)||s.board.cells[k]>=0||s.data.flags.includes(k))continue;seen.add(k);const near=neighbors(k,8,6,true),count=near.filter(j=>s.data.mines.includes(j)).length;s.board.cells[k]=count;s.progress++;if(count===0)todo.push(...near.filter(j=>!s.data.mines.includes(j)));}refreshGoal(s);return true;}
 if(n===75){const k=s.data.mirrors.findIndex(m=>m.i===i);if(k<0||k%s.players.length!==side)return false;s.data.mirrors[k].rot^=1;laser(s);return true;}
 if(n===77){if(!validCell(s,i))return false;const from=s.data.selected[side];if(!Number.isInteger(from)||from<0||!neighbors(from,6,6).includes(i)){s.data.selected[side]=i;return true;}const x=s.board.cells[from],y=s.board.cells[i],value=a.choice===1?Math.abs(x-y):a.choice===2?x*y:x+y;if(value!==s.data.target){s.message='目標の数字と違います';s.data.selected[side]=i;return false;}s.board.owners[from]=s.board.owners[i]=side;s.players.forEach(p=>p.score=s.board.owners.filter(v=>v===p.side).length);s.data.target=6+int(s,12);s.data.selected[side]=-1;return true;}
 if(n===78){const k=i%6;if(k<0)return false;if(side===0){s.data.past[k]=(s.data.past[k]+1)%4;s.data.future[k]=s.data.past[k];}else{if(s.data.future[k]===s.data.solution[k]&&!s.board.cells[6+k]){s.board.cells[6+k]=1;s.progress++;refreshGoal(s);}else s.message='未来の姿が手掛かりと違う';}return true;}
 if(n===79){if(!validCell(s,i))return false;if(a.choice===1){if(s.board.owners[i]>=0&&s.board.owners[i]!==side)return false;s.board.owners[i]=side;}else s.board.cells[i]=(s.board.cells[i]+1)%4;return true;}
 if(n===80){if(s.turn!==side)return false;const num=side+1+Math.max(0,a.i)%3,op=Math.max(0,a.choice)%3;s.data.number=op===0?s.data.number+num:op===1?s.data.number-num:s.data.number*num;s.data.sequence.push({side,num,op});s.turn=(side+1)%s.players.length;if(s.data.number===s.data.target){s.progress++;s.data.number=1;s.data.target=12+int(s,24);s.data.sequence=[];refreshGoal(s);}if(Math.abs(s.data.number)>500){s.data.number=1;s.message='500を超えたため1から再開';}return true;}
 if(n===95){if(!validCell(s,i)||s.data.sand<1)return false;if(a.choice===1){s.board.cells[i]=-1;s.data.sand--;}else{s.board.cells[i]=Math.min(5,Math.max(0,s.board.cells[i])+1);s.data.sand--;}return true;}
 if(n===97){if(a.type==='confirm'){s.data.readyAt[side]=s.t;if(s.players.every(p=>s.t-(s.data.readyAt[p.side]??-99)<2)){if(s.data.mix.every((v,k)=>v===s.data.order[k])){s.progress++;s.data.mix=[0,0,0];s.data.order=[1+int(s,3),1+int(s,3),1+int(s,3)];s.message='打ち上げ成功！';refreshGoal(s);}else s.message='色の調合がお題と違う';s.data.readyAt={};}return true;}if(side!==0||i<0)return false;const k=i%3;s.data.mix[k]=(s.data.mix[k]+1)%4;return true;}
 if(n===98){if(a.type==='secondary'){s.data.answer.pop();return true;}if(a.type==='confirm'){if(s.data.answer.length===5&&s.data.answer.every((v,k)=>v===s.data.solution[k])){s.progress=1;refreshGoal(s);}else s.message='停車順が違う。手掛かりをもう一度共有しよう';return true;}const station=i+1;if(station<1||station>5||s.data.answer.includes(station))return false;s.data.answer.push(station);return true;}
 return false;}
export function step(s,inputs,dt){const n=s.n;if(n===63){s.data.spawn-=dt;if(s.data.spawn<=0){s.data.spawn=4;s.data.trains.push({x:0,segment:0,branch:1,color:int(s,3)});}for(const t of s.data.trains){t.x+=dt*.7;const segment=Math.min(5,Math.floor(t.x));if(segment!==t.segment){t.segment=segment;t.branch=s.data.switches[segment];}if(t.x>=6){if(t.branch===t.color)s.progress++;else s.data.lives--;t.done=true;}}s.data.trains=s.data.trains.filter(t=>!t.done);if(s.data.lives<=0)finish(s,'failed','列車の誤着が3回発生');refreshGoal(s);}
 if(n===64){s.data.tick+=dt;if(s.data.tick>2){s.data.tick=0;if(s.data.belt[11]){s.message='未完成の部品が流れてしまった';s.data.belt[11]=null;}for(let i=10;i>=0;i--)if(!s.data.belt[i+1]){s.data.belt[i+1]=s.data.belt[i];s.data.belt[i]=null;}}}
 if(n===66){s.data.power=Math.min(12,s.data.power+dt*.8);if(s.data.ships.some(ship=>ship.deadline<s.t))finish(s,'failed','補給が間に合わなかった');}
 if(n===72){s.data.fall+=dt;if(s.data.fall>.65){s.data.fall=0;for(const p of s.players){const b=s.data.blocks[p.side];if(canFall(s.data.boards[p.side],{...b,y:b.y+1}))b.y++;else lock(s,p.side);}}}
 if(n===75&&!s.data.path.length)laser(s);
 if(n===79){for(const p of s.players){let i=18,seen=new Set(),count=0;while(!seen.has(i)){seen.add(i);const dir=s.board.cells[i],next=[i-6,i+1,i+6,i-1][dir];if(s.board.owners[i]===p.side)count++;if(!neighbors(i,6,6).includes(next))break;i=next;}p.score+=dt*count;s.data.water[p.side]=p.score;} }
 if(n===95){s.data.clock+=dt;if(s.data.clock>=10){s.data.clock=0;s.data.wave++;for(let x=0;x<6;x++){let force=2+Math.floor(s.data.wave/3);for(let y=0;y<6;y++){const k=y*6+x;if(s.board.cells[k]===-1){force=Math.max(0,force-1);continue;}const blocked=Math.min(force,s.board.cells[k]);s.board.cells[k]-=blocked;force-=blocked;s.data.water[k]=force;}if(x===3)s.data.flagHp-=force;}s.data.sand+=14;s.progress=s.data.wave;if(s.data.flagHp<=0)finish(s,'failed','大波で旗が流された');else refreshGoal(s);}}
}
export function view(s,side){const v=publicView(s,side);if([71,72].includes(s.n)){v.board.cells=copy(s.data.boards[side]);v.data.opponents=s.data.boards.map((b,i)=>i===side?null:copy(b));delete v.data.boards;if(s.n===72)v.data.block=copy(s.data.blocks[side]);}if(s.n===58&&side!==0){v.board.cells=v.board.cells.map((c,i)=>Math.abs(i%6-s.data.pawns[0]%6)+Math.abs(Math.floor(i/6)-Math.floor(s.data.pawns[0]/6))<=1?c:0);v.data.fog=true;}return v;}
