import {base,grid,int,shuffle,neighbors,validCell,finish,winTeam,byScore,publicView,copy} from './common.mjs';
export const realtime=false;
const TOPICS=[['ねこ',['動物','にゃ','猫']],['ロケット',['宇宙','飛ぶ','星']],['カレー',['ご飯','辛い','インド']],['ゆきだるま',['雪','冬','にんじん']],['じてんしゃ',['ペダル','車輪','乗る']],['おばけ',['幽霊','怖い','透明']],['すいか',['夏','果物','種']],['ピアノ',['音楽','鍵盤','弾く']],['くじら',['海','大きい','魚']],['おしろ',['王様','城','塔']],['たこやき',['大阪','たこ','丸い']],['にじ',['雨','色','空']]];
const normalize=s=>String(s||'').normalize('NFKC').replace(/[\s。、！？!?]/g,'').replace(/[ァ-ヶ]/g,c=>String.fromCharCode(c.charCodeAt(0)-96));
function topic(s){const t=TOPICS[int(s,TOPICS.length)];s.data.answer=t[0];s.data.forbidden=t[1];return t;}
function prompt(s){topic(s);s.data.secret=s.players.map((_,side)=>side===s.data.speaker?{word:s.data.answer,forbidden:s.data.forbidden}:{});s.data.messages=[];}
function vote(s,side,a){const choice=Number(a.value??a.choice);if(!Number.isInteger(choice)||choice<0||choice>=s.players.length)return false;s.data.votes[side]=choice;s.data.committed[side]=true;if(Object.keys(s.data.votes).length===s.players.filter(p=>p.hp>0).length){const counts=s.players.map(p=>Object.values(s.data.votes).filter(v=>v===p.side).length);const max=Math.max(...counts),tied=counts.flatMap((v,i)=>v===max?[i]:[]);const out=tied.length===1?tied[0]:-1;finish(s,out===s.data.impostor?'crew':s.data.impostor,out===s.data.impostor?'正体を見抜いた！':'正体を隠し通した');s.data.revealed=s.data.impostor;}return true;}
export function create(spec,players,seed){const s=base(spec,players,seed),n=s.n;s.data.messages=[];s.data.strokes=[];s.data.votes={};s.data.committed=s.players.map(()=>false);s.data.lastMove=0;s.data.speaker=0;s.data.stage='play';s.data.cooldowns=s.players.map(()=>0);s.target=5;
 if(n===51){s.goal='手番の人が絵か言葉で伝え、決定で次へ。最後の回答がお題と一致すれば成功。';topic(s);s.data.secret=s.players.map((_,i)=>i===0?{word:s.data.answer}:{});s.data.relay=[];s.data.stage='draw';s.target=1;}
 if(n===52){s.goal='説明役は秘密の禁止ワードを使わずヒントを送る。仲間は回答を送る。5問当てよう。';s.data.hearts=5;prompt(s);}
 if(n===53){s.goal='1人だけお題を知らない偽絵師。順に絵へ線を加え、2巡後に怪しい相手へ投票。';topic(s);s.data.impostor=int(s,players.length);s.data.secret=s.players.map((_,i)=>({word:i===s.data.impostor?'あなたは偽絵師です':s.data.answer,role:i===s.data.impostor?'fake':'artist'}));}
 if(n===54){grid(s,5,2);s.board.kind='ship-social';s.data.impostor=int(s,players.length);s.data.positions=s.players.map((_,i)=>i%5);s.data.tasks=Array(5).fill(0);s.data.meeting=false;s.data.secret=s.players.map((_,i)=>({role:i===s.data.impostor?'妨害者':'乗員'}));s.target=15;s.goal='部屋へ移動し、乗員はAで修理。妨害者はBで破壊。会議は一度だけ開ける。会議で正体を投票。';}
 if(n===55){grid(s,6,4);s.board.kind='props';s.board.cells=Array.from({length:24},()=>int(s,8));s.data.positions=s.players.map((_,i)=>i?int(s,24):-1);s.data.caught=[];s.data.hunterShots=18;s.goal='P1は家具をタップして探索。隠れる側は隣の家具へ移動できるが移動跡が残る。180秒隠れよう。';s.data.secret=s.players.map((_,i)=>({role:i===0?'探す人':'隠れる人'}));}
 if(n===56){s.goal='売り手だけが商品の価値を知る。説明を送り、買い手は価格を秘密入力。Bで一度だけ鑑定（3コイン）。';s.data.seller=0;s.data.bids={};s.data.appraised=s.players.map(()=>false);for(const p of s.players)p.coins=30;s.data.goods=5+int(s,26);s.data.secret=s.players.map((_,i)=>i===0?{value:s.data.goods}:{});}
 if(n===57){s.goal='運び屋は合法品か密輸を選び、申告額を送る。検査官は通すか検査。正直なら検査官が賠償、密輸なら没収。';s.data.inspector=0;s.data.cargo=s.players.map((_,i)=>i?{illegal:false,value:0,submitted:false}:null);for(const p of s.players)p.coins=20;s.data.checked=[];}
 if(n===59){s.goal='質問に答え、ほかの人の多数派を予想。予想的中は3点、少数派は2点。8問を読み合おう。';s.data.questions=['休日は山？ 海？','朝型？ 夜型？','魔法？ 科学？','犬？ 猫？','ひとり旅？ グループ旅？','甘い？ 辛い？','冒険？ のんびり？','過去へ？ 未来へ？'];s.data.answers={};s.data.predictions={};}
 if(n===60){grid(s,5,1);s.board.kind='chests';s.data.real=int(s,5);s.data.suspect=0;s.data.evidence=[];s.data.inspections=2;s.data.secret=s.players.map((_,i)=>i===0?{chest:s.data.real,role:'すり替え役'}:{role:'探偵'});s.goal='P1はBで本物の宝箱をすり替え、決定で確定。探偵は2回まで調査し、本物へ投票。';s.data.stage='hide';}
 if(n===91){grid(s,8,6);s.board.kind='hunt';s.data.positions=s.players.map((_,i)=>i===0?0:40+i);s.data.keys=[];s.data.noises=[];s.data.caged=[];s.data.secret=s.players.map((_,i)=>({role:i===0?'追跡者':'探索者'}));s.goal='隣の部屋へ移動。探索者は鍵を3つ集めて右上から脱出。追跡者はAで捕獲。仲間はBで救助。';s.data.items=[13,27,44];s.target=3;}
 return s;}
function chat(s,side,text){if(!text.trim())return false;s.data.messages.push({side,text:text.slice(0,120),t:s.t});s.data.messages=s.data.messages.slice(-30);return true;}
export function act(s,side,a){const p=s.players[side],n=s.n,i=a.i;if(!p||s.phase!=='playing'||p.hp<=0)return false;
 if(a.type==='chat'){if(s.n===52&&side===s.data.speaker&&s.data.forbidden.some(w=>normalize(a.text).includes(normalize(w)))){s.data.hearts--;s.message='禁止ワードが含まれていた！';if(!s.data.hearts)finish(s,'failed','禁止ワードを5回使ってしまった');return false;}return chat(s,side,a.text);}
 if([51,53].includes(n)){if(s.data.stage==='vote')return a.type==='vote'?vote(s,side,a):false;if(side!==s.turn)return false;if(a.type==='draw'){if(n===51&&s.data.stage!=='draw')return false;s.data.strokes.push({side,x:a.x,y:a.y,px:Math.max(0,Math.min(1000,a.i)),py:Math.max(0,Math.min(600,a.j))});s.data.strokes=s.data.strokes.slice(-800);return true;}if(a.type!=='confirm')return false;
 if(n===51){if(s.data.stage==='guess'){const text=a.text.trim();if(!text)return false;s.data.relay.push({side,text});if(side===s.players.length-1){const correct=normalize(text)===normalize(s.data.answer);s.progress=correct?1:0;finish(s,correct?'team':'failed','お題「'+s.data.answer+'」→ 回答「'+text+'」');return true;}s.data.secret=s.players.map((_,i)=>i===side+1?{word:text}:{});s.data.strokes=[];s.data.stage='draw';}else{s.data.relay.push({side,drawing:copy(s.data.strokes)});s.data.stage='guess';}s.turn++;}else{s.turn=(s.turn+1)%s.players.length;s.ply++;if(s.ply>=s.players.length*2)s.data.stage='vote';}s.data.lastMove=s.t;return true;}
 if(n===52){if(a.type!=='answer'||side===s.data.speaker)return false;chat(s,side,a.text);if(normalize(a.text)===normalize(s.data.answer)){s.progress++;s.players.forEach(p=>p.score=s.progress);s.message='正解！ '+s.data.answer;if(s.progress>=s.target)winTeam(s,'5問の説明に成功！');else{s.data.speaker=(s.data.speaker+1)%s.players.length;prompt(s);}}return true;}
 if(n===54){if(s.data.stage==='vote')return a.type==='vote'?vote(s,side,a):false;if(a.type==='meeting'&&!s.data.meeting){s.data.meeting=true;s.data.stage='vote';s.data.lastMove=s.t;return true;}if(a.type==='cell'&&i>=0&&i<5){s.data.positions[side]=i;return true;}if(s.data.cooldowns[side]>s.t)return false;const room=s.data.positions[side];if(side===s.data.impostor){if(a.type==='secondary'){const victim=s.players.find(q=>q.side!==side&&q.hp>0&&s.data.positions[q.side]===room);if(victim){victim.hp=0;s.data.cooldowns[side]=s.t+20;if(s.players.filter(p=>p.hp>0&&p.side!==side).length<=1)finish(s,side,'妨害者が船を掌握');}else{s.data.tasks[room]=Math.max(0,s.data.tasks[room]-2);s.data.cooldowns[side]=s.t+5;}return true;}}else if(a.type==='primary'&&s.data.tasks[room]<3){s.data.tasks[room]++;s.data.cooldowns[side]=s.t+1.5;s.progress=s.data.tasks.reduce((a,b)=>a+b,0);p.score++;if(s.progress>=15)finish(s,'crew','すべての修理が完了！');return true;}return false;}
 if(n===55){if(!validCell(s,i))return false;if(side===0){if(s.data.cooldowns[0]>s.t||!s.data.hunterShots)return false;s.data.cooldowns[0]=s.t+.7;s.data.hunterShots--;const found=s.data.positions.flatMap((v,j)=>j>0&&v===i&&!s.data.caught.includes(j)?[j]:[]);s.data.caught.push(...found);p.score+=found.length;s.data.lastSearch={i,hit:!!found.length,t:s.t};if(s.data.caught.length===s.players.length-1)finish(s,0,'全員を見つけた！');else if(!s.data.hunterShots)finish(s,'hiders','家具に紛れて逃げ切った！');return true;}if(s.data.caught.includes(side)||s.data.cooldowns[side]>s.t||!neighbors(s.data.positions[side],6,4).includes(i))return false;s.data.trail={from:s.data.positions[side],to:i,t:s.t};s.data.positions[side]=i;s.data.cooldowns[side]=s.t+2;return true;}
 if(n===56){if(side===s.data.seller){if(a.type==='confirm'){s.data.committed[side]=true;return true;}return false;}if(a.type==='secondary'&&!s.data.appraised[side]&&p.coins>=3){p.coins-=3;s.data.appraised[side]=true;s.data.secret[side]={value:s.data.goods};return true;}const bid=Number(a.value);if(!Number.isInteger(bid)||bid<0||bid>p.coins||s.data.bids[side]!==undefined)return false;s.data.bids[side]=bid;s.data.committed[side]=true;if(Object.keys(s.data.bids).length===s.players.length-1){const max=Math.max(...Object.values(s.data.bids)),winner=s.players.find(p=>s.data.bids[p.side]===max);winner.coins-=max;winner.score+=s.data.goods;s.players[s.data.seller].coins+=max;s.message='価値は'+s.data.goods+'。'+winner.name+'が購入';if(s.round++>=s.players.length*2){s.players.forEach(p=>p.score+=p.coins);byScore(s,'全員が2回販売');}else{s.data.seller=(s.data.seller+1)%s.players.length;s.data.bids={};s.data.goods=5+int(s,26);s.data.secret=s.players.map((_,i)=>i===s.data.seller?{value:s.data.goods}:{});s.data.appraised=s.players.map(()=>false);s.data.committed=s.players.map(()=>false);}}return true;}
 if(n===57){if(side!==s.data.inspector){if(s.data.cargo[side]?.submitted)return false;const value=Number(a.value);if(!Number.isInteger(value)||value<1||value>8)return false;s.data.cargo[side]={illegal:a.choice===1,value,submitted:true};s.data.committed[side]=true;return true;}const target=Number(a.value),cargo=s.data.cargo[target];if(!cargo?.submitted||s.data.checked.includes(target))return false;const check=a.choice===1;if(check&&cargo.illegal){s.players[target].coins-=cargo.value;p.coins+=cargo.value;}else if(check){p.coins-=cargo.value;s.players[target].coins+=cargo.value*2;}else s.players[target].coins+=cargo.value*(cargo.illegal?2:1);s.data.checked.push(target);s.message=s.players[target].name+'：'+(cargo.illegal?'密輸品':'合法品');if(s.data.checked.length===s.players.length-1){s.round++;if(s.round>s.players.length*2){s.players.forEach(p=>p.score=p.coins);byScore(s,'検査が終了');}else{s.data.inspector=(s.data.inspector+1)%s.players.length;s.data.cargo=s.players.map((_,i)=>i===s.data.inspector?null:{illegal:false,value:0,submitted:false});s.data.checked=[];s.data.committed=s.players.map(()=>false);}}return true;}
 if(n===59){if(s.data.answers[side]!==undefined)return false;s.data.answers[side]=Math.max(0,a.choice)%2;s.data.predictions[side]=Math.max(0,Number(a.value)||0)%2;s.data.committed[side]=true;if(Object.keys(s.data.answers).length===s.players.length){const zero=Object.values(s.data.answers).filter(v=>v===0).length,majority=zero>s.players.length/2?0:zero<s.players.length/2?1:-1;for(const p of s.players){if(s.data.predictions[p.side]===majority)p.score+=3;if(majority>=0&&s.data.answers[p.side]!==majority)p.score+=2;}s.message='回答：'+zero+' 対 '+(s.players.length-zero);s.data.answers={};s.data.predictions={};s.data.committed=s.players.map(()=>false);if(s.round++>=8)byScore(s,'8問終了');}return true;}
 if(n===60){if(s.data.stage==='hide'){if(side!==0)return false;if(a.type==='confirm'){s.data.stage='investigate';s.data.lastMove=s.t;return true;}if(validCell(s,i)){const old=s.data.real;s.data.real=i;s.data.evidence.push({from:old,to:i});s.data.evidence=s.data.evidence.slice(-4);s.data.secret[0].chest=i;return true;}return false;}if(side===0||!validCell(s,i))return false;if(a.type==='secondary'&&s.data.inspections>0){s.data.inspections--;s.message='宝箱'+(i+1)+'：'+(Math.abs(i-s.data.real)<=1?'金の気配が近い':'金の気配は遠い');return true;}s.data.votes[side]=i;s.data.committed[side]=true;if(Object.keys(s.data.votes).length===s.players.length-1){const votes=Array.from({length:5},(_,k)=>Object.values(s.data.votes).filter(v=>v===k).length),max=Math.max(...votes),guess=votes.indexOf(max);s.data.revealed=s.data.real;finish(s,guess===s.data.real?'detectives':0,guess===s.data.real?'本物の宝箱を特定！':'すり替え成功！');}return true;}
 if(n===91){if(s.data.caged.includes(side)||s.data.cooldowns[side]>s.t)return false;const pos=s.data.positions[side];if(a.type==='secondary'&&side>0){const mate=s.data.caged.find(k=>neighbors(pos,8,6).concat(pos).includes(s.data.positions[k]));if(mate!==undefined){s.data.caged=s.data.caged.filter(k=>k!==mate);s.data.cooldowns[side]=s.t+2;return true;}}if(a.type==='primary'&&side===0){const victim=s.players.find(p=>p.side>0&&!s.data.caged.includes(p.side)&&neighbors(pos,8,6).concat(pos).includes(s.data.positions[p.side]));if(victim){s.data.caged.push(victim.side);p.score++;if(s.data.caged.length===s.players.length-1)finish(s,0,'探索者を全員捕獲');}s.data.cooldowns[0]=s.t+3;return true;}if(!validCell(s,i)||!neighbors(pos,8,6).includes(i))return false;s.data.positions[side]=i;s.data.cooldowns[side]=s.t+(side? .5:.65);if(side){s.data.noises.push({i,t:s.t});if(s.data.items.includes(i)&&!s.data.keys.includes(i))s.data.keys.push(i);if(i===7&&s.data.keys.length===3)finish(s,'explorers','鍵を集めて脱出！');}return true;}
 return false;}
export function step(s,inputs,dt){if(s.n===91)s.data.noises=s.data.noises.filter(n=>s.t-n.t<3);if(s.n===53&&s.data.stage!=='vote'&&s.t-s.data.lastMove>30)act(s,s.turn,{type:'confirm'});if(s.n===54&&s.data.stage==='vote'&&s.t-s.data.lastMove>35)finish(s,s.data.impostor,'投票がまとまらず妨害者が逃げた');if(s.t>=s.duration-1){if(s.n===55)finish(s,'hiders','時間まで隠れ切った！');if(s.n===91)finish(s,0,'追跡者が脱出を阻止');if(s.n===54)finish(s,s.data.impostor,'修理が間に合わなかった');}}
export function view(s,side){const v=publicView(s,side);delete v.data.answer;delete v.data.forbidden;delete v.data.impostor;delete v.data.votes;delete v.data.answers;delete v.data.predictions;delete v.data.goods;delete v.data.real;delete v.data.bids;if(s.n===51){delete v.data.relay;if(side!==s.turn)v.data.strokes=[];}if(s.n===55){v.private={...v.private,position:s.data.positions[side]};delete v.data.positions;}if(s.n===57){v.private={cargo:copy(s.data.cargo[side])};v.data.cargo=s.data.cargo.map(c=>c?{submitted:c.submitted,value:c.submitted?c.value:null}:null);}if(s.n===91){const mine=s.data.positions[side];v.data.positions=s.data.positions.map((v,i)=>i===side||Math.abs(v%8-mine%8)+Math.abs(Math.floor(v/8)-Math.floor(mine/8))<=2?v:null);v.data.fog=true;}return v;}
