import {useEffect,useState,type ReactNode} from 'react';
import {LockKeyhole,ArrowLeft,LoaderCircle} from 'lucide-react';
import {account,activateFromLink,getSession,setPassword,signIn,signOut} from './auth';
import './auth.css';

export default function AuthGate({children,onReady}:{children?:ReactNode;onReady?:()=>void}){
 const [state,setState]=useState<'checking'|'signin'|'password'|'ready'>('checking');
 const [email,setEmail]=useState(''),[password,setPass]=useState(''),[confirm,setConfirm]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function ready(){const value=await account();setEmail(value.email);setState('ready');onReady?.()}
 useEffect(()=>{let active=true;(async()=>{try{const activated=await activateFromLink();if(!await getSession()){if(active)setState('signin');return}const user=await account();if(!active)return;setEmail(user.email);if(activated)setState('password');else{setState('ready');onReady?.()}}catch(e){if(active){setError((e as Error).message);setState('signin')}}})();return()=>{active=false}},[]);
 if(state==='ready')return <>{children}<details className="commons-account"><summary aria-label="アカウント">アカウント</summary><div><span>{email}</span><button onClick={()=>{setPass('');setConfirm('');setError('');setState('password')}}>パスワードを設定</button><button onClick={()=>void signOut()}>ログアウト</button></div></details></>;
 if(state==='checking')return <main className="auth-loading" role="status"><LoaderCircle className="auth-spin" size={24}/><p>コモンズを開いています…</p></main>;
 async function submit(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');try{if(state==='password'){if(password.length<12)throw new Error('パスワードは12文字以上で設定してください。');if(password!==confirm)throw new Error('2つのパスワードが一致していません。');await setPassword(password)}else await signIn(email,password);await ready()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <div className="auth-page"><a className="auth-back" href="/"><ArrowLeft size={17}/>AITECHトップ</a><main className="auth-card"><span className="auth-icon"><LockKeyhole size={26}/></span><p className="auth-brand">COMMONS</p><h1>{state==='password'?'パスワードを設定':'コモンズにサインイン'}</h1><p>{state==='password'?'次回から、このドメインでサインインできます。':'このコモンズのアカウントで開いてください。'}</p><form onSubmit={submit}><label htmlFor="commons-email">メールアドレス</label><input id="commons-email" type="email" autoComplete="username" required value={email} readOnly={state==='password'} onChange={e=>setEmail(e.target.value)}/><label htmlFor="commons-password">パスワード</label><input id="commons-password" type="password" autoComplete={state==='password'?'new-password':'current-password'} required minLength={state==='password'?12:1} value={password} onChange={e=>setPass(e.target.value)}/>{state==='password'&&<><label htmlFor="commons-confirm">パスワードをもう一度</label><input id="commons-confirm" type="password" autoComplete="new-password" required minLength={12} value={confirm} onChange={e=>setConfirm(e.target.value)}/></>}{error&&<p className="auth-error" role="alert">{error}</p>}<button className="auth-submit" disabled={busy}>{busy?'確認中…':state==='password'?'設定してコモンズを開く':'サインイン'}</button></form>{state==='password'&&<button className="auth-later" onClick={()=>void ready().catch(e=>setError(e.message))}>今は設定せず開く</button>}</main></div>;
}
