import {build} from 'vite';
import {createRequire} from 'node:module';
import react from '@vitejs/plugin-react';
import {writeHelp,guides} from './help.mjs';
import {applySaunaReviews} from './sauna-reviews.mjs';
import {resolve,join} from 'node:path';
import {mkdir,readFile,writeFile,cp,rm,realpath,readdir} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
const source=resolve(fileURLToPath(new URL('..',import.meta.url)));
const root=resolve(source,'..');
const output=join(root,'commons');
const input=join(source,'aitech/index.html');
await applySaunaReviews(source);
// Preserve independent Commons sites (for example hotels and rentals).
// Only the routes and files generated below belong to this application.
await writeFile(input,'<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#253654"><meta name="robots" content="noindex"><title>コモンズ | AITECH</title><link rel="canonical" href="https://aitechd.com/commons/"><link rel="icon" href="/commons/favicon.svg"></head><body><div id="root"><main style="max-width:640px;margin:15vh auto;padding:24px;font-family:system-ui;line-height:1.8"><h1>コモンズを開いています</h1><p>画面が切り替わらない場合は、通信状態を確認してください。</p><a href="/commons/help/">使い方・読み込めないときは</a><noscript><p>このサービスの操作にはJavaScriptが必要です。使い方ページはJavaScriptなしで読めます。</p></noscript></main></div><script type="module" src="/main.tsx"></script></body></html>');
const existingAssets=await readdir(join(output,'assets')).catch(()=>[]);
const lastAssets=await readFile(join(source,'aitech/assets-current.json'),'utf8').then(JSON.parse).catch(()=>existingAssets);
await rm(join(output,'camera-auth.js'),{force:true});
await rm(join(output,'auth.css'),{force:true});
const clientBuild=await build({configFile:false,root:join(source,'aitech'),base:'/commons/',plugins:[react()],resolve:{alias:{'@':source}},css:{postcss:source},publicDir:false,build:{outDir:output,emptyOutDir:false,assetsInlineLimit:100000,rollupOptions:{input:{index:input},output:{entryFileNames:'assets/[name]-[hash].js'}}}});
const outputs=Array.isArray(clientBuild)?clientBuild:[clientBuild];
const currentAssets=outputs.flatMap(result=>result.output.map(file=>file.fileName)).filter(name=>name.startsWith('assets/')).map(name=>name.slice(7));
const keepAssets=new Set([...lastAssets,...currentAssets]);
for(const name of await readdir(join(output,'assets')))if(!keepAssets.has(name))await rm(join(output,'assets',name),{force:true});
await writeFile(join(source,'aitech/assets-current.json'),JSON.stringify(currentAssets,null,2));
const html=await readFile(join(output,'index.html'),'utf8');
await writeHelp(output);
const paths=['study','tools/whiteboard','tools/chat','r','weather','bitcoin','onion','ramen','openings/restaurants','openings/ramen','openings/sauna','sauna'];
paths.push(...['supermarkets','saunas','sento','fishmongers'].map(kind=>'local/'+kind));
const localTitles={supermarkets:'スーパー',saunas:'サウナ',sento:'銭湯',fishmongers:'魚屋'};
for(const path of paths){await mkdir(join(output,path),{recursive:true});let page=html.replace('href="https://aitechd.com/commons/"',`href="https://aitechd.com/commons/${path}/"`);if(path.startsWith('local/'))page=page.replace('<title>コモンズ | AITECH</title>',`<title>今開いてる${localTitles[path.split('/')[1]]}一覧｜岐阜・愛知 | AITECH</title>`);const guide=guides.find(g=>g[2]===path);if(guide){const name=guide[1];page=page.replace(/<title>.*?<\/title>/,`<title>${name} | COMMONS</title>`).replace('</head>',`<meta name="description" content="${name}。${guide[3]}${guide[4]}"></head>`)}await writeFile(join(output,path,'index.html'),page)}
// Advertise on the public catalog only, after writing the tool and room shells.
const adsHead='<meta name="google-adsense-account" content="ca-pub-5820558629755748"><script src="/ads-config.js?v=20260913-adsense" defer></script><script src="/ads-bootstrap.js?v=20260913-adsense" defer></script>';
const adsFooter='<footer aria-label="サイト情報" style="padding:20px;text-align:center;font-size:14px"><a href="/legal.html#privacy">プライバシー</a> · <a href="/legal.html#transmission">外部送信</a></footer>';
await writeFile(join(output,'index.html'),html.replace('</head>',adsHead+'</head>').replace('</body>',adsFooter+'</body>'));
await cp(join(source,'public/favicon.svg'),join(output,'favicon.svg'));
await mkdir(join(output,'camera'),{recursive:true});
await cp(join(source,'public/camera'),join(output,'camera'),{recursive:true});
let camera=await readFile(join(source,'app/camera/document.html'),'utf8');
await writeFile(join(output,'camera/index.html'),camera);
await cp(join(source,'data/onion-snapshot.json'),join(output,'onion/snapshot.json'));
await cp(join(source,'public/sauna-data.json'),join(output,'sauna-data.json'));
await cp(join(source,'public/sauna-inventory.json'),join(output,'sauna-inventory.json'));
await cp(join(source,'public/local-data.json'),join(output,'local-data.json'));
await build({configFile:false,root:source,publicDir:false,resolve:{alias:[{find:'opening_hours',replacement:'npm:opening_hours@3.14.0'},{find:'@/db',replacement:join(source,'edge/database.ts')},{find:'@',replacement:source}]},build:{outDir:join(source,'edge-output'),emptyOutDir:true,minify:false,lib:{entry:join(source,'edge/index.ts'),formats:['es'],fileName:()=> 'index.js'},rollupOptions:{external:id=>id.startsWith('npm:')||id.startsWith('node:')}}});
const require=createRequire(await realpath(join(source,'node_modules/vite/package.json')));
const transformed=await require('esbuild').transform(await readFile(join(source,'edge-output/index.js'),'utf8'),{minify:true,target:'es2022',format:'esm'});
await writeFile(join(source,'edge-output/index.js'),transformed.code);
console.log(JSON.stringify({frontend:output,server:join(source,'edge-output/index.js'),routes:paths.length+2}));
