import {mkdir,writeFile} from 'node:fs/promises';
import {join} from 'node:path';

export const guides=[
  ['whiteboard','ホワイトボード','tools/whiteboard','ルーム名と表示名を入力してルームを作る。','招待リンクを相手に共有する。','ペンや図形で書き込み、保存状態を確認する。','招待リンクを知る人が参加できます。共有先を確認してください。'],
  ['study','予備試験対策集','study','短答ノートか論文ノートを選ぶ。','科目・問題を選び、解答または答案を入力する。','採点や解説を確認し、間違えた問題を復習する。','進捗は端末・ブラウザに保存されます。ブラウザのデータ削除や別端末への切り替えでは引き継がれません。'],
  ['chat','ルームチャット','tools/chat','ルーム名と表示名を入力してルームを作る。','招待リンクを共有し、参加者を確認する。','メッセージを入力して送信し、送信結果を確認する。','表示名は本人確認を伴わないニックネームです。招待リンクの扱いに注意してください。'],
  ['hotels','全国ホテル検索','hotels','宿泊地・チェックイン日・チェックアウト日・人数を指定する。','検索して、表示プランの料金と対象人数・泊数を比較する。','予約サイトを開き、最終料金・空室・キャンセル条件を確認する。','予約手続きは掲載元で行います。表示料金は取得時点の情報で、全予約サイトの最安値を保証するものではありません。'],
  ['rentals','岐阜・愛知の賃貸検索','rentals','都道府県と駅を選ぶ。','徒歩分数と間取りを指定して検索する。','気になる物件を掲載元で開き、空室と総費用を確認する。','家賃順には管理費や初期費用が含まれません。駅からの徒歩条件や現在の募集状況は掲載元で確認してください。'],
  ...[['supermarkets','スーパー'],['saunas','サウナ'],['sento','銭湯'],['fishmongers','魚屋']].map(([id,name])=>['local-'+id,'岐阜・愛知の'+name,'local/'+id,'県・市町村・店名で候補を絞る。','営業時間と出典を開き、確認できる情報を読む。','地図で場所を確認し、必要に応じて施設に電話する。','「営業時間内」は登録時間からの判定です。臨時休業や最終受付は反映されない場合があります。「要確認」は休業の意味ではありません。']),
  ['ramen','岐阜のラーメン','ramen','市町村や店名で候補を探す。','登録営業時間と判定の根拠を確認する。','地図や電話から来店前に場所と営業を確認する。','売り切れによる早仕舞い・臨時休業は登録時間だけでは判定できません。'],
  ['sauna','全国のサウナ','sauna','都道府県と施設名で候補を絞る。','「要確認」「すべて」も使い、営業時間が未登録の施設を確認する。','施設サイトでサウナの稼働時間・利用条件・最終受付を確認する。','施設全体の営業時間とサウナ室の稼働時間は異なる場合があります。全国の全施設を網羅した一覧ではありません。'],
  ['ramen-news','ラーメン屋オープン予定','openings/ramen','表示期間に含まれる開店予定を探す。','所在地と予定日、掲載元を確認する。','来店前に公式情報で延期や変更がないか確認する。','掲載情報がないことは、その地域に新店がないことを意味しません。'],
  ['sauna-news','サウナ開業情報','openings/sauna','前後2か月の開業・新設情報を見る。','開業日と情報源を確認する。','施設サイトで予約の要否や利用開始日を確認する。','予定日は変更されることがあります。プレオープンと通常営業開始は区別して確認してください。'],
  ['camera','カメラ','camera','カメラを開き、ブラウザでカメラの使用を許可する。','カメラと撮影設定を選び、撮影ボタンを押す。','写真を保存し、端末の写真アプリやダウンロード先を確認する。','アクセス許可を取り消した場合はブラウザのサイト設定を確認してください。保存先や端末の動作はOS・ブラウザにより異なります。'],
  ['weather','岐阜の天気','weather','知りたい地域を選ぶ。','時間別・週間予報で気温や降水確率を確認する。','更新時刻を確認し、取得に失敗した場合は再試行する。','予報は変わります。取得に失敗したデータを最新情報として扱わないでください。'],
  ['bitcoin','ビットコイン送金マップ','bitcoin','確認する公開アドレスまたは取引IDを入力する。','送金図で取引と入出力を確認する。','次の取引を選び、公開ブロックチェーン上の動きをたどる。','秘密鍵やシードフレーズを入力する機能はありません。図は公開取引のつながりを示し、アドレス所有者の本人特定を保証しません。'],
  ['onion','Onion URL確認','onion','カテゴリやキーワードで公開URLを探す。','応答状況と最終測定時刻を確認する。','必要なURLをコピーし、対応するブラウザで開く。','測定時点の応答は現在の接続やリンク先の安全性を保証しません。通常のブラウザではonion URLに接続できません。'],
];
const esc=text=>text.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
export async function writeHelp(output){
  await mkdir(join(output,'help'),{recursive:true});
  const cards=guides.map(([id,name,path,...body],i)=>`<article id="${id}"><div class="number">${String(i+1).padStart(2,'0')}</div><h2>${esc(name)}</h2><ol>${body.slice(0,3).map(step=>`<li>${esc(step)}</li>`).join('')}</ol><p class="note">${esc(body[3])}</p><a class="open" href="/commons/${path}/">${esc(name)}を開く <span aria-hidden="true">→</span></a></article>`).join('');
  await writeFile(join(output,'help/index.html'),`<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>使い方・困ったときは | COMMONS</title><meta name="description" content="コモンズ全17サービスの使い方、保存方法、通信エラーからの復旧と情報の確認方法。"><link rel="icon" href="/commons/favicon.svg"><link rel="stylesheet" href="/commons/help/help.css"></head><body><a class="skip" href="#main">本文へ移動</a><header><a class="brand" href="/commons/">COMMONS</a><a href="/commons/">サイト一覧へ</a></header><main id="main"><div class="hero"><p class="eyebrow">COMMONS GUIDE</p><h1>使いたいことから、<br>すぐに始める。</h1><p>17サービスの使い方と、困ったときの確認方法。</p><a href="#trouble">読み込めない・保存できないときは ↓</a></div><nav aria-label="サービスごとの使い方">${guides.map(([id,name])=>`<a href="#${id}">${esc(name)}</a>`).join('')}</nav><div class="grid">${cards}</div><section id="trouble" class="trouble"><p class="eyebrow">SUPPORT</p><h2>困ったときは</h2><details open><summary>ページが読み込めない・通信が止まった</summary><p>通信状態を確認し、画面の「再試行」を押してください。再読み込みの前に、未保存の文章を手元に控えてください。データを消すためにブラウザの保存領域を削除する必要はありません。</p></details><details><summary>最近のルームや学習記録が見つからない</summary><p>作成・参加したときと同じ端末・ブラウザで開いてください。プライベートブラウズやブラウザデータの削除では、端末に保存した情報が失われる場合があります。ルームの招待リンクがあれば、そのリンクから開けます。</p></details><details><summary>営業時間・料金・募集情報が違う</summary><p>情報の出典と取得・確認時刻を確認し、掲載元の最新情報を優先してください。「未登録」「要確認」は情報が足りない状態です。空欄を営業中や無料として扱わないでください。</p></details><details><summary>写真を保存できない</summary><p>端末の空き容量、ブラウザのダウンロード先、写真への保存操作を確認してください。カメラの許可と写真の保存は別の操作です。保存完了を確認するまで撮影画面を閉じないでください。</p></details></section><footer><a href="/commons/">コモンズに戻る</a><span>COMMONS · AITECH</span></footer></main></body></html>`);
  await writeFile(join(output,'help/help.css'),`*{box-sizing:border-box}html{scroll-behavior:smooth;scroll-padding-top:24px}body{margin:0;background:#f4f6f9;color:#23334b;font-family:system-ui,-apple-system,"Segoe UI",sans-serif;line-height:1.8}a{color:#2459a8;text-underline-offset:4px}a:focus-visible,summary:focus-visible{outline:3px solid #3269ca;outline-offset:5px}.skip{position:absolute;top:-100px;left:16px;background:#fff;padding:12px;z-index:10}.skip:focus{top:8px}header{display:flex;align-items:center;justify-content:space-between;gap:20px;padding:20px max(24px,calc((100vw - 1120px)/2));background:#fff;border-bottom:1px solid #dce3ed}header a{padding-block:8px}.brand{font-size:22px;font-weight:800;letter-spacing:.08em;color:#23334b;text-decoration:none}main{max-width:1120px;margin:auto;padding:0 24px}.hero{padding:64px 0 40px}.eyebrow{letter-spacing:.15em;font-size:12px;font-weight:750;color:#41708f}.hero h1{font-size:clamp(32px,5vw,52px);line-height:1.3;letter-spacing:-.04em;margin:16px 0}.hero>p:not(.eyebrow){color:#52647b}.hero>a{display:inline-block;padding:12px 0}nav{display:flex;flex-wrap:wrap;gap:8px;margin-bottom:40px}nav a{border:1px solid #d4deea;border-radius:24px;padding:8px 16px;background:#fff;text-decoration:none;font-size:14px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px}article{display:flex;flex-direction:column;min-width:0;background:#fff;border:1px solid #dce3ed;border-radius:18px;padding:28px;scroll-margin-top:24px}.number{font-size:12px;letter-spacing:.14em;font-weight:700;color:#56728f}h2{font-size:22px;line-height:1.5;margin:8px 0 16px}ol{padding-left:24px;margin-top:0}li{padding:4px 0}.note{font-size:14px;color:#52647b;background:#f4f6f9;padding:16px;border-radius:10px}.open{display:inline-flex;justify-content:space-between;gap:12px;padding:12px 0;margin-top:auto;font-weight:650}.trouble{padding:48px 0}details{border-bottom:1px solid #d4deea;padding:12px 0}summary{cursor:pointer;padding:12px 0;font-weight:650}details p{max-width:800px;color:#52647b}footer{display:flex;justify-content:space-between;flex-wrap:wrap;gap:16px;padding:24px 0 40px;font-size:14px}footer a{padding:8px 0}@media(max-width:680px){.grid{grid-template-columns:1fr}.hero{padding-top:40px}main{padding:0 20px}article{padding:22px}header{padding:12px 20px}}@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}}`);
}
