import {useEffect,useMemo,useState} from 'react';
import {ArrowLeft,ArrowUpRight,Search,MapPin,Phone,ShoppingBasket,Flame,Waves,Fish,RefreshCw,Clock3} from 'lucide-react';
import {localStatus,readableHours,type LocalKind,type LocalSnapshot} from '@/lib/local-hours';
import './local-directory.css';

export const localKinds={supermarkets:{name:'スーパー',color:'#287451',icon:ShoppingBasket},saunas:{name:'サウナ',color:'#b35729',icon:Flame},sento:{name:'銭湯',color:'#217b91',icon:Waves},fishmongers:{name:'魚屋',color:'#365b9c',icon:Fish}};
const number=(v:number)=>v.toLocaleString('ja-JP');
function safeUrl(value:string){try{const u=new URL(value);return ['http:','https:'].includes(u.protocol)?u.href:undefined;}catch{return undefined;}}
export default function LocalDirectory({kind}:{kind:LocalKind}){
 const spec=localKinds[kind],Icon=spec.icon;
 const [data,setData]=useState<LocalSnapshot|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[now,setNow]=useState(Date.now());
 const [pref,setPref]=useState('all'),[city,setCity]=useState('all'),[query,setQuery]=useState(''),[state,setState]=useState('open');
 async function refresh(signal?:AbortSignal){setLoading(true);setError('');try{const response=await fetch('/commons/local-data.json',{cache:'no-cache',signal});if(!response.ok)throw new Error('店舗情報を読み込めませんでした。');const value=await response.json() as LocalSnapshot;if(!Array.isArray(value.stores)||!value.updatedAt)throw new Error('店舗情報の形式を確認できません。');setData(value);setNow(Date.now());}catch(e){if((e as Error).name!=='AbortError')setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{const controller=new AbortController();void refresh(controller.signal);const timer=setInterval(()=>{if(!document.hidden)setNow(Date.now());},30000);const visible=()=>{if(!document.hidden)setNow(Date.now());};document.addEventListener('visibilitychange',visible);return()=>{controller.abort();clearInterval(timer);document.removeEventListener('visibilitychange',visible);};},[]);
 useEffect(()=>{document.title=`今開いてる${spec.name}一覧｜岐阜・愛知 | AITECH`;},[spec.name]);
 const all=useMemo(()=>data?.stores.filter(x=>x.categories.includes(kind))??[],[data,kind]);
 const cities=useMemo(()=>[...new Set(all.filter(x=>pref==='all'||x.prefecture===pref).map(x=>x.city||'市町村未登録'))].sort((a,b)=>a.localeCompare(b,'ja')),[all,pref]);
 const statuses=useMemo(()=>new Map(all.map(x=>[x.id,localStatus(x,now)])),[all,now]);
 const matched=useMemo(()=>{const q=query.normalize('NFKC').toLowerCase().trim();return all.filter(x=>(pref==='all'||x.prefecture===pref)&&(city==='all'||(x.city||'市町村未登録')===city)&&(!q||(x.name+' '+x.address+' '+x.city).normalize('NFKC').toLowerCase().includes(q)));},[all,pref,city,query]);
 const counts={open:0,closed:0,unknown:0,all:matched.length};for(const x of matched)counts[statuses.get(x.id)!.state]++;
 const results=matched.filter(x=>state==='all'||statuses.get(x.id)!.state===state).sort((a,b)=>a.prefecture.localeCompare(b.prefecture,'ja')||a.city.localeCompare(b.city,'ja')||a.name.localeCompare(b.name,'ja'));
 const time=new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',month:'long',day:'numeric',weekday:'short',hour:'2-digit',minute:'2-digit'}).format(now);
 const tabs=[['open','営業中'],['unknown','要確認'],['closed','営業時間外'],['all','収録全件']] as const;
 return <div className="local-page" style={{'--local-accent':spec.color} as React.CSSProperties}>
  <header className="local-top"><a href="/commons/"><ArrowLeft size={17}/><b>AITECH</b><span>コモンズ</span></a><span className="local-area">岐阜県 / 愛知県</span></header>
  <main className="local-main"><nav className="local-types" aria-label="店舗の種類">{Object.entries(localKinds).map(([key,v])=>{const I=v.icon;return <a key={key} href={`/commons/local/${key}/`} aria-current={key===kind?'page':undefined}><I size={19}/>{v.name}</a>;})}</nav>
   <div className="local-title"><div><p className="local-kicker">いま、行ける場所を。</p><h1><Icon aria-hidden size={32}/>{spec.name}の営業中一覧</h1></div><div className="local-clock"><span><i/>日本時間・30秒ごとに判定</span><time dateTime={new Date(now).toISOString()}>{time}</time></div></div>
   <p className="local-note">登録された営業時間から判定しています。臨時休業・売り切れ・最終受付は店舗へご確認ください。</p>
   <section className="local-controls" aria-label="店舗を絞り込む"><div className="local-prefs" role="group" aria-label="都道府県">{[['all','2県すべて'],['岐阜県','岐阜県'],['愛知県','愛知県']].map(([key,label])=><button key={key} aria-pressed={pref===key} onClick={()=>{setPref(key);setCity('all');}}>{label}<small>{number(all.filter(x=>key==='all'||x.prefecture===key).length)}</small></button>)}</div><div className="local-searchrow"><label className="local-search"><Search size={20}/><input aria-label="店名・住所を検索" placeholder="店名・住所で検索" value={query} onChange={e=>setQuery(e.target.value)}/></label><label className="local-city"><span>市町村</span><select value={city} onChange={e=>setCity(e.target.value)}><option value="all">すべての市町村</option>{cities.map(x=><option key={x}>{x}</option>)}</select></label><button className="local-refresh" onClick={()=>void refresh()} disabled={loading} aria-label="店舗情報を再読み込み"><RefreshCw size={18} className={loading?'local-spin':''}/><span>更新</span></button></div></section>
   <div className="local-tabs" role="group" aria-label="営業状況">{tabs.map(([key,label])=><button key={key} aria-pressed={state===key} onClick={()=>setState(key)}>{label}<b>{number(counts[key])}</b></button>)}</div>
   <div className="local-count"><h2>{tabs.find(x=>x[0]===state)?.[1]} <b>{number(results.length)}</b><span>件</span></h2><a href="#local-coverage">収録範囲・情報源</a></div>
   {counts.unknown>0&&state==='open'&&<button className="local-unknown" onClick={()=>setState('unknown')}>営業時間を確認できない店舗が {number(counts.unknown)} 件あります <ArrowUpRight size={17}/></button>}
   {error&&<p className="local-error" role="alert">{error} {data?'前回読み込んだ店舗情報を表示しています。':''}<button onClick={()=>void refresh()}>再試行</button></p>}
   {!data&&loading?<div className="local-empty" role="status">店舗情報を読み込んでいます…</div>:<><div className="local-list">{results.map(store=>{const status=statuses.get(store.id)!,website=safeUrl(store.website),source=safeUrl(store.sourceUrl),map='https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(store.address?store.name+' '+store.address:store.lat!==undefined?`${store.lat},${store.lon}`:store.prefecture+' '+store.name);return <article className="local-store" key={store.id}><div className="local-store-main"><p className="local-location">{store.prefecture}<span>{store.city||'市町村未登録'}</span></p><h3>{store.name}</h3><p className="local-address">{store.address||'住所表記は未登録。地図で場所を確認できます。'}</p>{store.note&&<p className="local-store-note">{store.note}</p>}</div><div className="local-store-hours"><span className={`local-status local-${status.state}`}><i/>{status.state==='open'?'営業中（時間表）':status.state==='closed'?'営業時間外':'要確認'}</span><p><Clock3 size={16}/><span>{store.hoursText||readableHours(store.hours)}</span></p>{status.reason&&<small>{status.reason}</small>}{store.scope==='facility'&&kind==='saunas'&&<small>施設全体の時間。サウナの利用時間・受付は施設へ確認。</small>}</div><div className="local-actions"><a className="local-map" href={map} target="_blank" rel="noopener noreferrer"><MapPin size={17}/>地図を見る</a><div>{website&&<a href={website} target="_blank" rel="noopener noreferrer">店舗サイト<ArrowUpRight size={15}/></a>}{store.phone&&<a href={'tel:'+store.phone.replace(/[^+\d]/g,'')}><Phone size={15}/>電話</a>}</div><details><summary>出典・確認日</summary>{source&&<a href={source} target="_blank" rel="noopener noreferrer">{store.sourceName}<ArrowUpRight size={13}/></a>}{store.otherSources?.map(s=><a key={s.url} href={safeUrl(s.url)} target="_blank" rel="noopener noreferrer">併記：{s.name}<ArrowUpRight size={13}/></a>)}<p>取得日 {store.checkedAt.slice(0,10)}</p><p>{store.sourceType==='osm'?'地図の登録情報。現地での確認日とは異なります。':store.sourceType==='directory'?'公開施設一覧の登録情報。現地の営業は施設へ確認。':store.sourceType==='registry'?'公開許可台帳の掲載施設。現在の営業・小売利用は未確認。':'公式ページの掲載情報。訪問時の営業を保証するものではありません。'}</p></details></div></article>;})}</div>{!results.length&&data&&<div className="local-empty"><Icon size={32}/><h3>この条件で表示できる店舗はありません</h3><p>未収録・営業時間未確認の店舗があるため、実際に営業中の店舗がないとは限りません。</p><button onClick={()=>{setState('all');setQuery('');setCity('all');}}>収録店舗をすべて見る</button></div>}{results.length>0&&<p className="local-end">該当する {number(results.length)} 件をすべて表示しました</p>}</>}
   <section id="local-coverage" className="local-coverage"><h2>収録範囲と営業判定について</h2><p><b>地域内の全店舗の網羅は未達成です。</b> {data?.coverageNote||'店舗情報を確認しています。'} 営業時間がない店舗も「要確認」「収録全件」に残しています。</p><div className="local-coverage-stats"><div><span>この種類の収録店舗</span><strong>{number(all.length)}<small>件</small></strong></div><div><span>データ更新日</span><strong>{data?.updatedAt.slice(0,10)||'—'}</strong></div></div><p>サウナは専用施設とサウナありと確認できた施設、銭湯は一般銭湯・スーパー銭湯・日帰り温浴施設、魚屋は鮮魚小売店・一般客向け鮮魚市場に加え、鮮魚販売の許可施設を収録しています。許可情報だけの施設はスーパー内売場・卸売を含む可能性があり、一般客の利用を要確認としています。</p><details><summary>情報源ごとの取得状況</summary><p>件数は情報源ごとの照合前の件数です。重複する店舗は統合しています。</p><ul>{data?.sources.map((s,i)=><li key={s.url+i}><a href={safeUrl(s.url)} target="_blank" rel="noopener noreferrer">{s.name}</a><span>{number(s.count)} 件{!s.complete?'・一部取得':''}</span><p>{s.note}</p></li>)}</ul></details><p className="local-attribution">地図データ © <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener noreferrer">OpenStreetMap contributors</a>（ODbL）。公式店舗情報は各出典を参照。営業時間による推定であり、現地のリアルタイム監視ではありません。</p></section>
  </main><footer className="local-footer"><a href="/commons/">← コモンズに戻る</a><span>AITECH / LOCAL</span></footer>
 </div>;
}
