import{Game,games}from'./model.mjs';import{loadArt,render}from'./render.mjs';
const $=s=>document.querySelector(s),canvas=$('#canvas'),ctx=canvas.getContext('2d'),keys=new Set,pulses=new Set,pointers=new Map;
let game=null,mode='ready',last=0,acc=0,ready=false,records={},muted=true,audio=null,lastBeat=-1,statusClock=0;
try{records=JSON.parse(localStorage.getItem('paper-arcade-records-v1'))||{};}catch{}
const cards=$('#cards');games.forEach((g,i)=>{const card=document.createElement('article');card.className='card';card.style.setProperty('--accent','#'+g[4]);card.innerHTML=`<div><span class="number">${String(i+1).padStart(2,'0')} / ${g[1]}</span><h2>${g[0]}</h2><p>${g[2]}</p></div><img src="assets/${g[5]}.png" alt="" width="92" height="92"><button type="button" data-game="${i}"><span>プレイする</span><span aria-hidden="true">↗</span></button>`;card.querySelector('button').onclick=()=>select(i);cards.append(card);});
function sound(freq=660,len=.09){if(muted)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),v=audio.createGain();o.type='sine';o.frequency.value=freq;v.gain.setValueAtTime(.09,audio.currentTime);v.gain.exponentialRampToValueAtTime(.001,audio.currentTime+len);o.connect(v);v.connect(audio.destination);o.start();o.stop(audio.currentTime+len);}catch{}}
function clear(){keys.clear();pulses.clear();pointers.clear();document.querySelectorAll('.held').forEach(b=>b.classList.remove('held'));if(game)game.previous.clear();acc=0;}
function overlay(title,copy,button){$('#overlay').hidden=false;$('#overlay-title').textContent=title;$('#overlay-copy').textContent=copy;$('#primary').textContent=button;$('#primary').disabled=!ready;$('#overlay-tag').textContent=game?games[game.index][1]:'';}
function start(){if(!ready||!game)return;if(mode!=='paused'){const i=game.index;game=new Game(i);lastBeat=-1;}clear();mode='playing';$('#overlay').hidden=true;$('#pause').textContent='一時停止';canvas.focus({preventScroll:true});last=performance.now();sound(440);updateStatus();}
function pause(){if(mode==='playing'){mode='paused';clear();overlay('ひと休み', 'タイマーは止まっています。','再開する');$('#pause').textContent='再開';}else if(mode==='paused')start();}
function select(i,writeHash=true){if(!Number.isInteger(i)||i<0||i>9)i=0;game=new Game(i);mode='ready';clear();$('#library').hidden=true;$('#player').hidden=false;document.documentElement.style.setProperty('--accent','#'+games[i][4]);$('#title').textContent=games[i][0];$('#help').textContent=games[i][3]+'。下のボタンでも操作できます。';$('#pause').textContent='一時停止';makeControls();overlay(games[i][0],games[i][2],ready?'プレイ開始':'素材を読み込み中…');updateStatus();if(writeHash)history.replaceState(null,'',`#game-${i+1}`);if(ready)render(ctx,game);window.scrollTo({top:0});}
function library(){clear();mode='library';game=null;$('#player').hidden=true;$('#library').hidden=false;history.replaceState(null,'',location.pathname);document.documentElement.style.setProperty('--accent','#83e3b2');}
function retry(){if(!game)return;if(game.index===4&&game.state==='playing'){game.loadPuzzle();clear();mode='playing';$('#overlay').hidden=true;$('#pause').textContent='一時停止';}else{mode='ready';start();}}
function updateStatus(){if(!game)return;$('#status').textContent=game.status();$('#record').textContent=`ベストスコア ${Number(records[game.index])||0}　／　現在 ${game.score}`;}
const controls=[ [['left','←'],['right','→'],['action','ジャンプ']], [['left','←'],['up','↑'],['down','↓'],['right','→'],['action','連射']], [['left','←'],['right','→'],['action','発射']], [['left','←'],['up','↑'],['down','↓'],['right','→']], [['left','←'],['up','↑'],['down','↓'],['right','→'],['undo','戻す']], [['lane0','D'],['lane1','F'],['lane2','J'],['lane3','K']], [['action','釣る！']], [['build0','1 下の塔'],['build1','2 中の塔'],['build2','3 上の塔'],['action','次の波']], [['left','←'],['right','→'],['up','加速'],['down','減速']], [['left','←'],['up','↑'],['down','↓'],['right','→'],['action','めくる']] ];
function makeControls(){const el=$('#touch');el.replaceChildren();for(const[k,label]of controls[game.index]){const b=document.createElement('button');b.type='button';b.textContent=label;b.dataset.key=k;b.setAttribute('aria-label',label);b.onpointerdown=e=>{e.preventDefault();if(mode!=='playing')return;b.setPointerCapture(e.pointerId);pointers.set(e.pointerId,k);keys.add(k);pulses.add(k);b.classList.add('held');};const release=e=>{const held=pointers.get(e.pointerId);pointers.delete(e.pointerId);if(![...pointers.values()].includes(held))keys.delete(held);b.classList.remove('held');};b.onpointerup=release;b.onpointercancel=release;b.onlostpointercapture=release;el.append(b);}}
function keyName(code){if(game?.index===5&&['KeyD','KeyF','KeyJ','KeyK'].includes(code))return'lane'+['KeyD','KeyF','KeyJ','KeyK'].indexOf(code);return{ArrowLeft:'left',KeyA:'left',ArrowRight:'right',KeyD:'right',ArrowUp:'up',KeyW:'up',ArrowDown:'down',KeyS:'down',Space:'action',KeyZ:'undo',Digit1:'build0',Digit2:'build1',Digit3:'build2'}[code];}
document.addEventListener('keydown',e=>{if(!game||e.ctrlKey||e.metaKey||e.altKey)return;const k=keyName(e.code);if(k)e.preventDefault();if(e.repeat)return;if(e.code==='Escape'){library();return;}if(e.code==='KeyP'){pause();return;}if(e.code==='KeyR'){retry();return;}if(e.code==='Enter'&&mode!=='playing'){e.preventDefault();start();return;}if(k&&mode==='playing'){keys.add(k);pulses.add(k);}});document.addEventListener('keyup',e=>{const k=keyName(e.code);if(k)keys.delete(k);});
canvas.onpointerdown=e=>{if(mode!=='playing'||game.index!==9)return;const b=canvas.getBoundingClientRect(),x=(e.clientX-b.left)*960/b.width,y=540-(e.clientY-b.top)*540/b.height;for(let n=0;n<16;n++)if(Math.abs(x-(315+n%4*110))<47&&Math.abs(y-(410-Math.floor(n/4)*96))<40){game.selected=n;game.previous.delete('action');game.step(0,['action']);game.previous.delete('action');updateStatus();}};
window.addEventListener('blur',()=>{clear();if(mode==='playing')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&mode==='playing')pause();});window.addEventListener('hashchange',()=>{const n=Number(location.hash.replace('#game-',''))-1;if(Number.isInteger(n)&&n>=0&&n<10)select(n,false);});
$('#primary').onclick=start;$('#back').onclick=library;$('#pause').onclick=pause;$('#retry').onclick=retry;$('#sound').onclick=()=>{muted=!muted;$('#sound').textContent='音：'+(muted?'OFF':'ON');$('#sound').setAttribute('aria-pressed',String(!muted));sound();};
function finish(){mode='result';clear();records[game.index]=Math.max(Number(records[game.index])||0,game.score);try{localStorage.setItem('paper-arcade-records-v1',JSON.stringify(records));}catch{}overlay(game.state==='won'?'クリア！':'もう一度、挑戦。',`スコア ${game.score}　・　${game.state==='won'?'次のゲームも遊んでみよう。':'コツをつかんでリトライ！'}`,'もう一度遊ぶ');sound(game.state==='won'?880:180,.3);updateStatus();}
function frame(now){const dt=Math.min(.1,(now-last)/1000||0);last=now;if(ready&&game){if(mode==='playing'){acc+=dt;while(acc>=1/120){const old=game.score;game.step(1/120,new Set([...keys,...pulses]));pulses.clear();acc-=1/120;if(game.score>old&&game.index!==8)sound(660+game.index*30);if(game.index===5&&game.time>=2){const beat=Math.floor((game.time-2)/.6);if(beat!==lastBeat){lastBeat=beat;sound(440,.045);}}if(game.state!=='playing'){finish();break;}}}render(ctx,game);statusClock+=dt;if(statusClock>.25){updateStatus();statusClock=0;}}requestAnimationFrame(frame);}
loadArt().then(()=>{ready=true;$('#primary').disabled=false;if(mode==='ready')$('#primary').textContent='プレイ開始';}).catch(()=>{if(game)overlay('素材を読み込めませんでした','通信を確認してページを再読み込みしてください。','読み込み失敗');else{const p=document.createElement('p');p.textContent='素材の読み込みに失敗しました。ページを再読み込みしてください。';cards.prepend(p);}});
const initial=location.hash.match(/^#game-(\d+)$/);if(initial)select(Number(initial[1])-1,false);requestAnimationFrame(frame);
// Read-only snapshot used by smoke tests and support. No input/score bypass is exposed.
window.arcadeSnapshot=()=>({index:game?.index,mode,state:game?.state,score:game?.score,time:game?.time,x:game?.x,ready});
