// SPDX-License-Identifier: GPL-3.0-or-later
// Rules for the AITECH board table. All state transitions are independent of UI.
export const other = p => 3 - p;
export const clone = s => structuredClone(s);
export const neighbors = (i,n) => [i%n>0?i-1:-1,i%n<n-1?i+1:-1,i>=n?i-n:-1,i<n*(n-1)?i+n:-1].filter(x=>x>=0);
const validIndex = (i,n) => Number.isInteger(i)&&i>=0&&i<n;
export function createOthello(){const b=Array(64).fill(0); b[27]=b[36]=2;b[28]=b[35]=1;return {kind:'othello',board:b,turn:1,winner:null,last:-1,passes:0,message:'黒から始めます。点のあるマスに置けます。'};}
export function flips(b,i,p){if(!validIndex(i,64)||b[i])return [];const out=[];for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++){if(!dr&&!dc)continue;let r=(i/8|0)+dr,c=i%8+dc,line=[];while(r>=0&&r<8&&c>=0&&c<8&&b[r*8+c]===other(p)){line.push(r*8+c);r+=dr;c+=dc;}if(line.length&&r>=0&&r<8&&c>=0&&c<8&&b[r*8+c]===p)out.push(...line);}return out;}
export function othelloMoves(s,p=s.turn){return s.board.flatMap((_,i)=>flips(s.board,i,p).length?[i]:[]);}
export function othelloMove(s,i){if(s.winner!==null)return false;const f=flips(s.board,i,s.turn);if(!f.length)return false;s.board[i]=s.turn;f.forEach(j=>s.board[j]=s.turn);s.last=i;s.turn=other(s.turn);s.message=`${f.length}枚を裏返しました。`;if(!othelloMoves(s).length){s.turn=other(s.turn);s.message+=' 相手は置けないためパス。';if(!othelloMoves(s).length){const score=[1,2].map(p=>s.board.filter(x=>x===p).length);s.winner=score[0]===score[1]?'draw':score[0]>score[1]?1:2;s.message=`終局：黒 ${score[0]} 対 白 ${score[1]}`;}}return true;}
export function othelloAI(s){const corners=[0,7,56,63];return othelloMoves(s).map(i=>{const t=clone(s);othelloMove(t,i);const r=i/8|0,c=i%8;return {i,v:(corners.includes(i)?1000:0)+(r===0||r===7||c===0||c===7?30:0)-([9,14,49,54].includes(i)?100:0)+flips(s.board,i,s.turn).length*2-othelloMoves(t).length*5};}).sort((a,b)=>b.v-a.v)[0]?.i;}
export function createGo(){return {kind:'go',board:Array(81).fill(0),turn:1,winner:null,last:-1,history:['0'.repeat(81)],captures:[0,0],passes:0,moveNo:0,message:'9路盤。黒から始めます。白にコミ7.5目。',phase:'play',removed:[],scoreAccepted:[]};}
export function group(b,i){const color=b[i],stones=new Set([i]),liberties=new Set(),todo=[i];if(!color)return {stones:[],liberties:[]};while(todo.length){for(const j of neighbors(todo.pop(),9)){if(!b[j])liberties.add(j);else if(b[j]===color&&!stones.has(j)){stones.add(j);todo.push(j);}}}return {stones:[...stones],liberties:[...liberties]};}
export function goTrial(s,i,p=s.turn){if(!validIndex(i,81)||s.board[i])return null;const b=s.board.slice();b[i]=p;let taken=0;for(const j of neighbors(i,9)){if(b[j]===other(p)){const g=group(b,j);if(!g.liberties.length){taken+=g.stones.length;g.stones.forEach(k=>b[k]=0);}}}if(!group(b,i).liberties.length)return null;const key=b.join('');if(s.history.includes(key))return null;return {b,key,taken};}
export function goMove(s,i){if(s.winner!==null||s.phase!=='play')return false;const t=goTrial(s,i);if(!t)return false;s.board=t.b;s.history.push(t.key);s.captures[s.turn-1]+=t.taken;s.last=i;s.passes=0;s.moveNo++;s.message=t.taken?`${t.taken}子を取りました。`:'次の手を置いてください。';s.turn=other(s.turn);return true;}
export function goPass(s){if(s.winner!==null||s.phase!=='play')return false;s.passes++;s.turn=other(s.turn);s.message='パスしました。';if(s.passes>=2){s.phase='score';s.scoringBoard=s.board.slice();s.scoreAccepted=[];s.message='双方パス。死に石があればクリックして除去し、双方が得点を確定してください。';}return true;}
export function goScore(b){const score=[0,7.5],seen=new Set();for(let i=0;i<81;i++){if(b[i]){score[b[i]-1]++;continue;}if(seen.has(i))continue;const area=[i],edge=new Set();seen.add(i);for(let k=0;k<area.length;k++)for(const j of neighbors(area[k],9)){if(b[j])edge.add(b[j]);else if(!seen.has(j)){seen.add(j);area.push(j);}}if(edge.size===1)score[[...edge][0]-1]+=area.length;}return score;}
export function goRemove(s,i){if(s.phase!=='score'||!s.board[i])return false;const g=group(s.board,i);g.stones.forEach(j=>s.board[j]=0);s.scoreAccepted=[];return true;}
export function goAccept(s,p){if(s.phase!=='score'||s.scoreAccepted.includes(p))return false;s.scoreAccepted.push(p);if(s.scoreAccepted.length===2){s.score=goScore(s.board);s.winner=s.score[0]>s.score[1]?1:2;s.phase='done';s.message=`黒 ${s.score[0]}目 ／ 白 ${s.score[1]}目（コミ7.5込み）`;}return true;}
export function goResume(s){if(s.phase!=='score')return;s.board=s.scoringBoard.slice();s.phase='play';s.passes=0;s.scoreAccepted=[];s.message='対局を再開しました。';}
export function goAI(s){let best=-1,value=-Infinity;for(let i=0;i<81;i++){const t=goTrial(s,i);if(!t)continue;const near=neighbors(i,9),own=near.filter(j=>s.board[j]===s.turn).length,enemy=near.filter(j=>s.board[j]===other(s.turn)).length;if(!t.taken&&own===near.length)continue;const g=group(t.b,i);if(g.liberties.length===1&&!t.taken)continue;let rescue=0;for(const j of near)if(s.board[j]===s.turn&&group(s.board,j).liberties.length===1)rescue+=group(s.board,j).stones.length;const row=i/9|0,col=i%9;const v=t.taken*40+rescue*35+Math.min(g.liberties.length,5)*2+enemy*3-(own>2?10:0)+(row>0&&row<8&&col>0&&col<8?4:0)+Math.random()*3;if(v>value){best=i;value=v;}}if(s.passes&&s.moveNo>35&&goScore(s.board)[s.turn-1]>goScore(s.board)[other(s.turn)-1])return -1;return best;}

// Compact Monopoly table: original locations, 24 spaces and a declared 20-round limit.
export const ESTATES = [
 ['START','start'],['港通り','land',100,12,0],['チャンス','chance'],['灯台通り','land',120,16,0],['市税','tax'],['駅前通り','land',140,20,1],
 ['面会 / 刑務所','jail'],['並木通り','land',160,24,1],['チャンス','chance'],['図書館通り','land',180,28,2],['美術館通り','land',200,32,2],['公共料金','tax'],
 ['フリーパーク','park'],['丘の上','land',220,36,3],['チャンス','chance'],['湖畔','land',240,40,3],['市場通り','land',260,44,4],['劇場通り','land',280,48,4],
 ['刑務所へ','gotojail'],['庭園通り','land',300,52,5],['チャンス','chance'],['王宮通り','land',320,56,5],['宝石通り','land',340,60,6],['星の大通り','land',360,64,6]
];
export function createProperty(){return {kind:'monopoly',turn:1,winner:null,players:[{cash:1500,pos:0,jail:0},{cash:1500,pos:0,jail:0}],owners:Array(24).fill(0),houses:Array(24).fill(0),mortgages:Array(24).fill(false),round:1,actions:0,phase:'roll',dice:[],message:'各プレイヤーの所持金は1,500。サイコロを振りましょう。',last:-1};}
export function estateGroup(s,i,p=s.turn){return ESTATES[i][1]==='land'&&ESTATES.every((e,j)=>e[1]!=='land'||e[4]!==ESTATES[i][4]||s.owners[j]===p);}
export function propertyWorth(s,p){return s.players[p-1].cash+ESTATES.reduce((sum,e,i)=>sum+(s.owners[i]===p?(s.mortgages[i]?e[2]/2:e[2])+s.houses[i]*50:0),0);}
export function rent(s,i,dice=7){if(s.mortgages[i])return 0;return ESTATES[i][3]*(s.houses[i]?[1,5,15,30][s.houses[i]]:estateGroup(s,i,s.owners[i])?2:1);}
function propertyPay(s,amount,to=0){const p=s.players[s.turn-1];p.cash-=amount;if(to)s.players[to-1].cash+=amount;if(p.cash<0){s.phase='debt';s.message+=' 資産を売却・抵当に入れて支払うか、破産を選んでください。';}}
export function propertyRoll(s,dice=[1+Math.floor(Math.random()*6),1+Math.floor(Math.random()*6)],card=Math.floor(Math.random()*6)){if(s.winner!==null||s.phase!=='roll'||dice.length!==2||dice.some(x=>!Number.isInteger(x)||x<1||x>6))return false;const p=s.players[s.turn-1];s.dice=dice;s.phase='end';if(p.jail){p.jail=0;propertyPay(s,50);s.message='保釈金50を支払い、次のターンから移動できます。';if(p.cash<0){s.phase='debt';s.message+=' 資産を処分してください。';}return true;}const total=dice[0]+dice[1];p.pos+=total;s.message=`${dice.join(' + ')} = ${total}。`;if(p.pos>=24){p.cash+=200;p.pos%=24;s.message+=' START通過で200を受け取りました。';}s.last=p.pos;const e=ESTATES[p.pos];s.message+=` ${e[0]}に到着。`;if(e[1]==='land'){if(!s.owners[p.pos]){s.phase='buy';s.message+=` 価格${e[2]}。購入するか競売へ。`;}else if(s.owners[p.pos]!==s.turn){const price=rent(s,p.pos);s.message+=` 家賃${price}を支払います。`;propertyPay(s,price,s.owners[p.pos]);}}else if(e[1]==='tax'){s.message+=' 税金100。';propertyPay(s,100);}else if(e[1]==='gotojail'){p.pos=6;p.jail=1;s.message+=' 次のターンは保釈金50を支払い休み。';}else if(e[1]==='chance'){const values=[100,-75,150,-100,50,200],v=values[card%6];s.message+=v>0?` ボーナス${v}！`:` 修繕費${-v}。`;if(v>0)p.cash+=v;else propertyPay(s,-v);}return true;}
export function propertyBuy(s){if(s.winner!==null||s.phase!=='buy')return false;const p=s.players[s.turn-1],i=p.pos;if(p.cash<ESTATES[i][2])return false;p.cash-=ESTATES[i][2];s.owners[i]=s.turn;s.phase='end';s.message=`${ESTATES[i][0]}を購入しました。`;return true;}
export function propertyAuction(s){if(s.phase!=='buy')return false;s.phase='auction';s.auction={i:s.players[s.turn-1].pos,bid:0,leader:0,turn:other(s.turn)};s.message='競売：10ずつ入札、または降ります。';return true;}
export function propertyBid(s,bid){if(s.phase!=='auction'||s.winner!==null)return false;const a=s.auction;const award=()=>{s.owners[a.i]=a.leader;s.players[a.leader-1].cash-=a.bid;s.message=`プレイヤー${a.leader}が${a.bid}で落札。`;s.phase='end';};if(bid){const next=a.bid+10;if(s.players[a.turn-1].cash<next)return false;a.bid=next;a.leader=a.turn;a.turn=other(a.turn);s.message=`最高入札：プレイヤー${a.leader}・${a.bid}。`;if(a.passed)award();}else if(a.leader){award();}else if(a.passed){s.message='入札なし。土地は銀行に残ります。';s.phase='end';}else{a.passed=true;a.turn=other(a.turn);s.message='相手は降りました。10で落札するか、降りてください。';}return true;}
export function propertyManage(s,i,action){if(s.winner!==null||!['roll','end','debt'].includes(s.phase)||s.owners[i]!==s.turn)return false;const p=s.players[s.turn-1];if(action==='build'){const peers=ESTATES.flatMap((e,j)=>e[1]==='land'&&e[4]===ESTATES[i][4]?[j]:[]);if(!estateGroup(s,i)||peers.some(j=>s.mortgages[j])||s.houses[i]>=3||s.houses[i]>Math.min(...peers.map(j=>s.houses[j]))||p.cash<100||s.phase==='debt')return false;p.cash-=100;s.houses[i]++;}else if(action==='sell'){if(!s.houses[i])return false;s.houses[i]--;p.cash+=50;}else if(action==='mortgage'){if(s.mortgages[i]||ESTATES.some((e,j)=>e[1]==='land'&&e[4]===ESTATES[i][4]&&s.houses[j]))return false;s.mortgages[i]=true;p.cash+=ESTATES[i][2]/2;}else if(action==='redeem'){const cost=Math.ceil(ESTATES[i][2]*.55);if(!s.mortgages[i]||p.cash<cost)return false;s.mortgages[i]=false;p.cash-=cost;}else return false;if(s.phase==='debt'&&p.cash>=0)s.phase='end';s.message='資産を更新しました。';return true;}
export function propertyEnd(s){if(s.phase!=='end'||s.winner!==null)return false;s.actions++;if(s.actions>=40){const scores=[propertyWorth(s,1),propertyWorth(s,2)];s.winner=scores[0]===scores[1]?'draw':scores[0]>scores[1]?1:2;s.message=`20ラウンド終了。総資産 ${scores[0]} 対 ${scores[1]}`;return true;}s.turn=other(s.turn);s.round=1+Math.floor(s.actions/2);s.phase='roll';s.message='サイコロを振ってください。';return true;}
export function propertyBankrupt(s){if(s.phase!=='debt')return false;s.winner=other(s.turn);s.message=`プレイヤー${s.turn}が破産しました。`;return true;}

export const LIFE_SPACES=Array.from({length:37},(_,i)=>i===0?['出発','start']:i===36?['ゴール','goal']:i===8?['結婚','marry']:i===13||i===24?['家族が増えた','child']:i===17?['マイホーム','house']:i===28?['転職のチャンス','career']:i%5===0?['給料日','salary']:i%4===0?['ハプニング','event']:i%3===0?['お祝い','bonus']:['日々のくらし','day']);
export const CAREERS=[{name:'デザイナー',salary:180,cost:0},{name:'エンジニア',salary:260,cost:300},{name:'医師',salary:340,cost:600}];
export function createLife(){return {kind:'life',turn:1,winner:null,players:[1,2].map(()=>({cash:1000,pos:0,career:null,salary:0,debt:0,kids:0,married:false,house:false,insurance:false,finished:false})),phase:'career',pending:null,roll:0,message:'仕事を選んで出発しましょう。学費は所持金から支払います。',last:-1};}
export function lifeWorth(p){return p.cash+(p.house?700:0)+p.kids*150-p.debt;}
export function lifeCareer(s,i){if(s.phase!=='career'||!CAREERS[i]||s.winner!==null)return false;const p=s.players[s.turn-1],c=CAREERS[i];if(p.cash<c.cost)return false;p.cash-=c.cost;p.career=c.name;p.salary=c.salary;s.phase='roll';s.message=`${c.name}になりました。給料は${c.salary}です。`;return true;}
function lifeDebit(p,c){if(p.cash<c){const loan=Math.ceil((c-p.cash)/100)*100;p.cash+=loan;p.debt+=Math.ceil(loan*1.1);}p.cash-=c;}
export function lifeRoll(s,roll=1+Math.floor(Math.random()*6),event=Math.floor(Math.random()*6)){if(s.winner!==null||s.phase!=='roll'||!Number.isInteger(roll)||roll<1||roll>6)return false;const p=s.players[s.turn-1],from=p.pos;p.pos=Math.min(36,p.pos+roll);s.roll=roll;s.last=p.pos;s.phase='end';let salary=0;for(let i=from+1;i<=p.pos;i++)if(LIFE_SPACES[i][1]==='salary')salary+=p.salary;p.cash+=salary;s.message=`${roll}マス進みました。${salary?`給料${salary}を受け取りました。`:''}`;const e=LIFE_SPACES[p.pos];s.message+=e[0]+'。';if(e[1]==='marry'){p.married=true;p.cash+=200;s.message+=' お祝い200。';}else if(e[1]==='child'){p.kids++;s.message+=' ゴールでお祝い150。';}else if(e[1]==='house'){s.phase='choice';s.pending='house';s.message+=' 600で購入できます。ゴール時の資産は700。';}else if(e[1]==='career'){s.phase='choice';s.pending='career';s.message+=' 200で資格取得。以後の給料が100アップ。';}else if(e[1]==='bonus'){p.cash+=150;s.message+=' 臨時収入150。';}else if(e[1]==='event'){const events=[['旅行へ',-120],['作品が入賞',300],['家の修理',-250],['臨時ボーナス',200],['ケガで通院',-180],['贈り物を受け取った',100]];const [label,v]=events[event%6];s.message+=`${label}：${v>0?'+':''}${v}。`;if(v<0){if(p.insurance&&[2,4].includes(event%6))s.message+=' 保険で全額カバー。';else lifeDebit(p,-v);}else p.cash+=v;}if(p.pos===36){p.finished=true;s.message+=' 退職、お疲れさまでした！';if(s.players.every(x=>x.finished)){const scores=s.players.map(lifeWorth);s.winner=scores[0]===scores[1]?'draw':scores[0]>scores[1]?1:2;s.message=`全員ゴール！総資産 ${scores[0]} 対 ${scores[1]}`;}}return true;}
export function lifeChoice(s,yes){if(s.phase!=='choice')return false;const p=s.players[s.turn-1];if(yes){if(s.pending==='house'){lifeDebit(p,600);p.house=true;}else{lifeDebit(p,200);p.salary+=100;}}s.phase='end';s.pending=null;s.message=yes?'新しい一歩を選びました。':'今回は見送りました。';return true;}
export function lifeInsure(s){const p=s.players[s.turn-1];if(s.phase!=='roll'||p.insurance||p.cash<100)return false;p.cash-=100;p.insurance=true;s.message='保険に加入。修繕費・通院費をカバーします。';return true;}
export function lifeRepay(s){const p=s.players[s.turn-1];if(!['roll','end'].includes(s.phase)||!p.debt||!p.cash)return false;const amount=Math.min(p.cash,p.debt);p.cash-=amount;p.debt-=amount;s.message=`借入${amount}を返済しました。`;return true;}
export function lifeEnd(s){if(s.winner!==null||s.phase!=='end')return false;if(!s.players[other(s.turn)-1].finished)s.turn=other(s.turn);s.phase=s.players[s.turn-1].career?'roll':'career';s.message=s.phase==='career'?'仕事を選んでください。':'ルーレットを回してください。';return true;}
