// Copyright (c) 2026 AItechjp. All rights reserved.
// Third-party libraries retain their own licenses.
import {Chess,parseSfen,initialSfen,makeSfen,parseSquareName,makeSquareName,makeUsi} from './vendor/rules.mjs';
export const SHOGI_LABEL={pawn:'歩',lance:'香',knight:'桂',silver:'銀',gold:'金',bishop:'角',rook:'飛',king:'王',tokin:'と',promotedpawn:'と',promotedlance:'杏',promotedknight:'圭',promotedsilver:'全',horse:'馬',dragon:'龍'};
export const chessSquare=i=>String.fromCharCode(97+i%8)+(8-(i/8|0));
export const chessIndex=s=>(8-Number(s[1]))*8+s.charCodeAt(0)-97;
export const shogiSquare=i=>parseSquareName(`${9-i%9}${String.fromCharCode(97+(i/9|0))}`);
export const shogiIndex=s=>{const v=makeSquareName(s);return (v.charCodeAt(1)-97)*9+9-Number(v[0]);};
const key=p=>makeSfen(p).split(' ').slice(0,3).join(' ');
export function createChess(){return {kind:'chess',pos:new Chess(),turn:1,winner:null,last:-1,message:'白から始めます。駒を選ぶと移動先が表示されます。',ply:0};}
export function chessMoves(s,from){return s.winner!==null?[]:s.pos.moves(from===undefined?{verbose:true}:{square:chessSquare(from),verbose:true});}
export function chessMove(s,m){if(s.winner!==null)return false;try{const move=s.pos.move(m);if(!move)return false;s.ply++;s.last=chessIndex(move.to);s.turn=s.pos.turn()==='w'?1:2;s.message=move.san+(s.pos.isCheck()?'：王手です。':'');if(s.pos.isCheckmate()){s.winner=3-s.turn;s.message='チェックメイト。';}else if(s.pos.isDraw()){s.winner='draw';s.message=s.pos.isStalemate()?'ステイルメイトで引き分け。':s.pos.isThreefoldRepetition()?'同一局面3回で引き分け。':s.pos.isInsufficientMaterial()?'詰ませる戦力がないため引き分け。':'50手ルールで引き分け。';}return true;}catch{return false;}}
const CV={p:100,n:320,b:330,r:500,q:900,k:20000};
function chessEval(pos){if(pos.isCheckmate())return -100000;let v=0;const color=pos.turn();for(const row of pos.board())for(const p of row)if(p){const i=chessIndex(p.square),center=7-Math.abs(i%8-3.5)-Math.abs((i/8|0)-3.5);v+=(p.color===color?1:-1)*(CV[p.type]+center*(p.type==='k'?0:4));}return v;}
export function chessAI(s){let best=null,score=-Infinity;const options=chessMoves(s).sort((a,b)=>(CV[b.captured]||0)-(CV[a.captured]||0));for(const m of options){s.pos.move(m);let worst=Infinity;const replies=s.pos.moves({verbose:true});if(!replies.length)worst=-chessEval(s.pos);else for(const r of replies){s.pos.move(r);const v=chessEval(s.pos);s.pos.undo();worst=Math.min(worst,v);if(worst<score)break;}s.pos.undo();const v=worst+Math.random()*3;if(v>score){score=v;best=m;}}return best;}
export function createShogi(){const pos=parseSfen('standard',initialSfen('standard')).unwrap();return {kind:'shogi',pos,turn:1,winner:null,last:-1,message:'先手から始めます。駒を選んで動かしてください。',history:[{key:key(pos),mover:0,check:false}],ply:0};}
export function shogiMoves(s,source){if(s.winner!==null)return [];const p=s.pos,out=[];const add=(m)=>{if(p.isLegal(m))out.push(m);};if(typeof source==='string'){for(let i=0;i<81;i++)add({role:source,to:shogiSquare(i)});}else{const squares=source===undefined?[...p.board].filter(([,v])=>v.color===p.turn).map(([i])=>i):[shogiSquare(source)];for(const from of squares){for(const to of p.moveDests(from)){add({from,to});add({from,to,promotion:true});}}if(source===undefined)for(const [role,count] of p.hands.color(p.turn))if(count>0)for(const to of p.dropDests({role,color:p.turn}))add({role,to});}return out;}
export function shogiMove(s,m){if(s.winner!==null||!s.pos.isLegal(m))return false;const mover=s.turn;s.pos.play(m);s.ply++;s.last=shogiIndex(m.to);s.turn=s.pos.turn==='sente'?1:2;s.message=makeUsi(m)+(s.pos.isCheck()?'：王手です。':'');s.history.push({key:key(s.pos),mover,check:s.pos.isCheck()});const outcome=s.pos.outcome();if(outcome){s.winner=outcome.winner?(outcome.winner==='sente'?1:2):'draw';s.message='合法手がなくなり、終局しました。';}else{const repeats=s.history.flatMap((h,i)=>h.key===key(s.pos)?[i]:[]);if(repeats.length>=4){const recent=s.history.slice(repeats.at(-4)+1);const checking=[1,2].find(p=>recent.filter(h=>h.mover===p).every(h=>h.check));s.winner=checking?3-checking:'draw';s.message=checking?'連続王手の千日手。王手を続けた側の負けです。':'同一局面4回。千日手で引き分けです。';}}return true;}
const SV={pawn:100,lance:280,knight:300,silver:400,gold:500,bishop:700,rook:850,king:20000,tokin:510,promotedlance:510,promotedknight:510,promotedsilver:510,horse:1000,dragon:1150};
function shogiEval(pos,color){let score=0;for(const [sq,p] of pos.board){const i=shogiIndex(sq),row=i/9|0,advance=p.color==='sente'?8-row:row;score+=(p.color===color?1:-1)*((SV[p.role]||500)+(p.role==='king'?0:advance*3));}for(const c of ['sente','gote'])for(const [role,n] of pos.hands.color(c))score+=(c===color?1:-1)*n*(SV[role]||500)*.85;return score;}
export function shogiAI(s){const p=s.pos,color=p.turn;const ranked=shogiMoves(s).map(m=>{const n=p.clone();n.play(m);return {m,n,score:shogiEval(n,color)+(n.isCheck()?35:0)+(n.isEnd()?100000:0)};}).sort((a,b)=>b.score-a.score).slice(0,10);let best,score=-Infinity;for(const item of ranked){const fake={pos:item.n,winner:null};let worst=item.score;for(const reply of shogiMoves(fake)){const n=item.n.clone();n.play(reply);worst=Math.min(worst,shogiEval(n,color)-(n.isEnd()?100000:0));if(worst<score)break;}const v=worst+Math.random()*4;if(v>score){score=v;best=item.m;}}return best;}
