// Copyright (c) 2026 AItechjp. All rights reserved.
// Third-party libraries retain their own licenses.
import * as E from './engines.mjs';
import * as R from './royal.mjs';
import {makeSfen} from './vendor/rules.mjs';
import {TITLES,RULES,EDITIONS} from './rules.mjs';
import {installBoardKeyboard} from './keyboard.mjs?v=20260914-commercial2';
const $=s=>document.querySelector(s),el=id=>document.getElementById(id),G=globalThis.GomokuRules;
const query=new URLSearchParams(location.search);let kind=Object.hasOwn(TITLES,query.get('game'))?query.get('game'):'gomoku',mode=query.get('mode')==='local'?'local':'solo';
const boardKeyboard=installBoardKeyboard(el('board'));
let state,selected=null,moves=[],promotion=null,busy=false,generation=0,timer,worker,scene,log=[],confirmAction;
const names=p=>mode==='solo'?(p===1?'あなた':'CPU'):`プレイヤー${p}`;
const turn=()=>kind==='gomoku'?state.turn+1:state.turn;
const winner=()=>kind==='gomoku'&&typeof state.winner==='number'?state.winner+1:state.winner;
const cpuTurn=()=>mode==='solo'&&!(kind==='go'&&state.phase==='score')&&(kind==='monopoly'&&state.phase==='auction'?state.auction.turn:turn())===2&&winner()===null;
const playable=()=>!busy&&!cpuTurn()&&winner()===null&&!promotion&&!document.hidden&&!document.documentElement.hasAttribute('data-aitech-guide-open')&&!el('confirm-dialog').open&&!el('rules-dialog').open&&!document.getElementById('aitech-assist-dialog')?.open;
const node=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
const button=(text,fn,disabled=false,cls='')=>{const b=node('button',cls,text);b.type='button';b.disabled=disabled;b.onclick=fn;return b;};
const act=(text,fn,disabled=false,cls='')=>el('actions').append(button(text,()=>{if(!cpuTurn())perform(fn);},disabled||busy||cpuTurn(),cls));
function notice(text){el('status').textContent=text;}
function init(){generation++;clearTimeout(timer);worker?.terminate();worker=null;el('game').value=kind;el('mode').value=mode;state=kind==='gomoku'?G.create():kind==='chess'?R.createChess():kind==='shogi'?R.createShogi():({othello:E.createOthello,go:E.createGo,monopoly:E.createProperty,life:E.createLife}[kind])();selected=null;moves=[];promotion=null;busy=false;log=[];document.title=`${TITLES[kind]} | AITECH GAMES`;el('title').textContent=TITLES[kind];el('rules-title').textContent=TITLES[kind]+'の遊び方';el('edition').textContent=EDITIONS[kind]||'1人はCPU対戦。2人は同じ端末で交互に操作します。';for(const id of ['rules-full','rules-short']){el(id).replaceChildren();const ul=node('ul');for(const line of (id==='rules-short'?RULES[kind].slice(0,2):RULES[kind]))ul.append(node('li','',line));el(id).append(ul);if(id==='rules-short')el(id).append(button('すべてのルールを見る',()=>{pauseCPU();el('rules-dialog').showModal();}));}const q=new URLSearchParams({game:kind,mode});history.replaceState(null,'',`?${q}`);render();}
function perform(fn){if(winner()!==null)return;const ok=fn();if(ok===false){if(!el('confirm-dialog').open)notice('この操作はできません。条件や所持金を確認してください。');return;}selected=null;moves=[];promotion=null;if(kind==='gomoku'){state.message=state.winner==='draw'?'盤面が埋まり、引き分けです。':state.winner!==null?'5つ以上の石が連続しました。':`最後の一手：${state.lastMove%15+1}列 ${(state.lastMove/15|0)+1}行。`;}if(state.message)log.unshift(state.message);log=log.slice(0,10);render();scheduleCPU();}
function render(){const focus=boardKeyboard.before();el('name1').textContent=names(1);el('name2').textContent=names(2);$('.p1').classList.toggle('active',turn()===1&&winner()===null);$('.p2').classList.toggle('active',turn()===2&&winner()===null);scene?.set(turn(),winner());const result=winner();el('turn-badge').textContent=result!==null?(result==='draw'?'引き分け':`${names(result)}の勝ち`):busy?'CPUが考えています…':`${names(kind==='monopoly'&&state.phase==='auction'?state.auction.turn:turn())}の番`;el('status').classList.toggle('result',result!==null);el('status').textContent=state.message||(kind==='gomoku'?'空いている交点に石を置いてください。':'');el('instruction').textContent=result!==null?'対局終了':busy?'次の一手を考え中':kind==='chess'||kind==='shogi'?'駒を選んで動かす':kind==='go'&&state.phase==='score'?'死に石と得点を確認':kind==='monopoly'?'土地を集めて街を育てる':kind==='life'?'仕事を選んで人生を進む':'石を置く';el('round').textContent=kind==='monopoly'?`ROUND ${state.round} / 20`:kind==='life'?`1P ${state.players[0].pos} / 36 · 2P ${state.players[1].pos} / 36`:kind==='chess'||kind==='shogi'?`${state.ply}手`:kind==='go'?`${state.moveNo}手 · コミ7.5`:'1人 / 最大2人';for(const id of ['board','hand1','hand2','actions','assets','choice','history'])el(id).replaceChildren();el('resign').disabled=result!==null||busy||cpuTurn();
 if(['monopoly','life'].includes(kind))renderTrack();else renderGrid();renderScores();renderActions();log.forEach(t=>el('history').append(node('div','',t)));if(promotion)renderPromotion();if(result!==null)el('actions').append(button('もう一度遊ぶ',init,false,'primary'));boardKeyboard.after(focus);
}
const CHARS={w:{k:'♚',q:'♛',r:'♜',b:'♝',n:'♞',p:'♟'},b:{k:'♚',q:'♛',r:'♜',b:'♝',n:'♞',p:'♟'}};
function renderScores(){for(const p of [1,2]){let txt;if(kind==='chess')txt=p===1?'白・先手':'黒・後手';else if(kind==='shogi')txt=p===1?'先手':'後手';else if(kind==='othello')txt=`${p===1?'黒':'白'} ${state.board.filter(x=>x===p).length}枚`;else if(kind==='go')txt=state.phase==='score'||winner()!==null?`${p===1?'黒':'白'} ${E.goScore(state.board)[p-1]}目`:`${p===1?'黒':'白'} · 取った石 ${state.captures[p-1]}`;else if(kind==='monopoly')txt=`所持金 ${state.players[p-1].cash.toLocaleString()} / 総資産 ${E.propertyWorth(state,p).toLocaleString()}`;else if(kind==='life'){const u=state.players[p-1];txt=`${u.career||'仕事を選択'} · ${u.cash.toLocaleString()}${u.finished?' · ゴール':''}`;}else txt=p===1?'黒・先手':'白・後手';el('score'+p).textContent=txt;}}
function renderGrid(){const n=kind==='gomoku'?15:kind==='go'||kind==='shogi'?9:8,board=el('board');board.className='';board.style.setProperty('--n',n);const dests=new Set(moves.map(m=>kind==='chess'?R.chessIndex(m.to):R.shogiIndex(m.to)));const legalO=kind==='othello'?new Set(E.othelloMoves(state)):null;
 for(let i=0;i<n*n;i++){const b=button('',()=>clickCell(i),false,'cell');b.dataset.index=i;let label=`${i%n+1}列 ${(i/n|0)+1}行`;if(kind==='chess'){const p=state.pos.get(R.chessSquare(i));b.classList.add('chess',((i/8|0)+i%8)%2?'dark':'light');if(p){b.textContent=CHARS[p.color][p.type];b.classList.add(p.color==='w'?'piece-white':'piece-black');label=R.chessSquare(i)+' '+(p.color==='w'?'白':'黒')+' '+({k:'キング',q:'クイーン',r:'ルーク',b:'ビショップ',n:'ナイト',p:'ポーン'}[p.type]);}else label=R.chessSquare(i)+' 空き';}else if(kind==='shogi'){b.classList.add('shogi');const p=state.pos.board.get(R.shogiSquare(i));if(p){const s=node('span','shogi-piece'+(p.color==='gote'?' enemy':'')+(/promoted|tokin|horse|dragon/.test(p.role)?' promoted':''),R.SHOGI_LABEL[p.role]||p.role);b.append(s);label=`${9-i%9}筋 ${(i/9|0)+1}段 ${p.color==='sente'?'先手':'後手'} ${s.textContent}`;}}else{b.classList.add(kind==='othello'?'othello':'grid');const color=state.board[i];if(color){b.append(node('span','stone'+(color===2?' white':'')));label+=color===1?' 黒':' 白';}else label+=' 空き';if(legalO?.has(i))b.classList.add('legal');}
 if(dests.has(i))b.classList.add('legal');if(selected===i)b.classList.add('selected');if(i===(state.last??state.lastMove))b.classList.add('last');b.setAttribute('aria-label',label);b.disabled=!playable();board.append(b);
 }
 if(kind==='shogi')for(const p of [1,2]){const hand=el('hand'+p);hand.append(node('span','',`${names(p)}の持ち駒：`));let count=0;for(const [role,num] of state.pos.hands.color(p===1?'sente':'gote'))if(num){count++;hand.append(button(`${R.SHOGI_LABEL[role]||role} ×${num}`,()=>{selected=role;moves=R.shogiMoves(state,role);render();},turn()!==p||!playable(),selected===role?'selected':''));}if(!count)hand.append(node('span','','なし'));}
}
function clickCell(i){if(!playable())return;if(kind==='chess'||kind==='shogi'){const targets=moves.filter(m=>(kind==='chess'?R.chessIndex(m.to):R.shogiIndex(m.to))===i);if(targets.length){if(targets.length>1){promotion=targets;render();}else perform(()=>kind==='chess'?R.chessMove(state,targets[0]):R.shogiMove(state,targets[0]));return;}const p=kind==='chess'?state.pos.get(R.chessSquare(i)):state.pos.board.get(R.shogiSquare(i));if(p&&p.color===(kind==='chess'?state.pos.turn():state.pos.turn)){selected=i;moves=kind==='chess'?R.chessMoves(state,i):R.shogiMoves(state,i);render();}else{selected=null;moves=[];render();}return;}
 if(kind==='gomoku')perform(()=>G.move(state,i,state.turn));if(kind==='othello')perform(()=>E.othelloMove(state,i));if(kind==='go'){if(state.phase==='score')perform(()=>E.goRemove(state,i));else{const t=E.goTrial(state,i);if(!t){notice('ここには置けません。占有・自殺手・同じ盤面の繰り返しを確認してください。');return;}perform(()=>E.goMove(state,i));}}
}
function renderPromotion(){el('choice').append(node('strong','',kind==='shogi'?'成りますか？':'昇格する駒を選択'));for(const m of promotion){const label=kind==='shogi'?(m.promotion?'成る':'成らない'):({q:'クイーン',r:'ルーク',b:'ビショップ',n:'ナイト'}[m.promotion]);el('choice').append(button(label,()=>perform(()=>kind==='shogi'?R.shogiMove(state,m):R.chessMove(state,m)),false,'primary'));}el('choice').append(button('選び直す',()=>{promotion=null;render();}));el('choice').querySelector('button')?.focus();}
const GROUPS=['#bd9675','#79cfe5','#c999de','#f5a359','#e47775','#edcd58','#74ba96'];
function renderTrack(){const b=el('board');b.className='track'+(kind==='life'?' life-track':'');b.style.setProperty('--n',7);const spaces=kind==='monopoly'?E.ESTATES:E.LIFE_SPACES;spaces.forEach((e,i)=>{const cell=node('div','space'+(state.owners?.[i]?' owned'+state.owners[i]:'')+(state.last===i?' current':'')+(e[1]==='goal'?' goal':''));cell.dataset.index=i;if(kind==='monopoly'){let row,col;if(i<=6){row=7;col=7-i;}else if(i<=12){row=13-i;col=1;}else if(i<=18){row=1;col=i-11;}else{row=i-17;col=7;}cell.style.gridRow=row;cell.style.gridColumn=col;if(e[1]==='land')cell.style.setProperty('--group',GROUPS[e[4]]);}else cell.style.setProperty('--group',e[1]==='salary'?'#64b69e':e[1]==='event'?'#df8b78':'#7695bf');cell.append(node('small','',i===0?'START':String(i).padStart(2,'0')),node('b','',e[0]));if(kind==='monopoly'&&e[1]==='land')cell.append(node('small','',state.houses[i]?'家'.repeat(state.houses[i]):state.mortgages[i]?'抵当中':String(e[2])));const tokens=node('div','tokens');state.players.forEach((p,k)=>{if(p.pos===i)tokens.append(node('span','token'+(k?' p2token':''),k+1));});cell.append(tokens);b.append(cell);});if(kind==='monopoly'){const center=node('div','track-center');center.append(node('p','eyebrow','AITECH CITY'),node('h2','','MONOPOLY'));const dice=node('div','dice');(state.dice.length?state.dice:['?','?']).forEach(x=>dice.append(node('span','die',x)));center.append(dice,node('p','',`ラウンド ${state.round} / 20`),node('small','','24マス · 2人用短時間ルール'));b.append(center);}else{const dice=node('div','dice');dice.append(node('span','die',state.roll||'?'));el('choice').append(dice);}}
function renderActions(){if(winner()!==null)return;if(kind==='go'){if(state.phase==='score'){act(`${names(1)}：得点を確定`,()=>{E.goAccept(state,1);if(mode==='solo')E.goAccept(state,2);},state.scoreAccepted.includes(1),'primary');if(mode==='local')act(`${names(2)}：得点を確定`,()=>E.goAccept(state,2),state.scoreAccepted.includes(2),'primary');act('除去を戻して対局再開',()=>E.goResume(state));}else act('パスする',()=>E.goPass(state));}
 if(kind==='shogi'||kind==='chess')act('引き分けを提案',()=>askConfirm('引き分けにしますか？',()=>{state.winner='draw';state.message=mode==='solo'?'CPUが引き分けを受け入れました。':'双方の合意で引き分けです。';render();},'引き分けに合意'));
 if(kind==='monopoly'){if(state.phase==='roll')act('サイコロを振る',()=>E.propertyRoll(state),false,'primary');if(state.phase==='buy'){act(`土地を購入 · ${E.ESTATES[state.players[turn()-1].pos][2]}`,()=>E.propertyBuy(state),state.players[turn()-1].cash<E.ESTATES[state.players[turn()-1].pos][2],'primary');act('購入せず競売へ',()=>E.propertyAuction(state));}if(state.phase==='auction'){const a=state.auction;act(`${a.bid+10}で入札`,()=>E.propertyBid(state,true),state.players[a.turn-1].cash<a.bid+10,'primary');act('競売から降りる',()=>E.propertyBid(state,false));}if(state.phase==='end')act('ターンを終える',()=>E.propertyEnd(state),false,'primary');if(state.phase==='debt')act('破産を認める',()=>E.propertyBankrupt(state));if(['roll','end','debt'].includes(state.phase))renderAssets();}
 if(kind==='life'){const p=state.players[turn()-1];if(state.phase==='career')E.CAREERS.forEach((c,i)=>act(`${c.name} · 学費${c.cost} / 給料${c.salary}`,()=>E.lifeCareer(state,i),p.cash<c.cost,'primary'));if(state.phase==='roll'){act('ルーレットを回す',()=>E.lifeRoll(state),false,'primary');if(!p.insurance)act('保険に入る · 100',()=>E.lifeInsure(state),p.cash<100);}if(state.phase==='choice'){act(state.pending==='house'?'家を買う · 600':'資格を取る · 200',()=>E.lifeChoice(state,true),false,'primary');act('見送る',()=>E.lifeChoice(state,false));}if(state.phase==='end')act('ターンを終える',()=>E.lifeEnd(state),false,'primary');if(p.debt)act(`借入を返す · 残${p.debt}`,()=>E.lifeRepay(state),p.cash<=0);for(const [i,u] of state.players.entries()){el('assets').append(node('div','asset',`${names(i+1)}：給料${u.salary} / 子ども${u.kids}人 / ${u.house?'家あり':'家なし'} / 借入${u.debt} / ${u.insurance?'保険あり':'保険なし'}`));}}
}
function renderAssets(){const assets=el('assets');assets.append(node('strong','',`${names(turn())}の土地`));let count=0;E.ESTATES.forEach((e,i)=>{if(state.owners[i]!==turn())return;count++;const item=node('div','asset');item.append(node('strong','',`${e[0]} · 家${state.houses[i]} · 家賃${E.rent(state,i)}`));const action=(text,key,disabled)=>item.append(button(text,()=>perform(()=>E.propertyManage(state,i,key)),disabled||busy||cpuTurn()));action('建設100','build',!E.estateGroup(state,i)||state.houses[i]>=3||state.mortgages[i]||state.players[turn()-1].cash<100||state.phase==='debt');if(state.houses[i])action('家売却50','sell',false);else if(state.mortgages[i])action('抵当解除','redeem',false);else action('抵当に入れる','mortgage',false);assets.append(item);});if(!count)assets.append(node('p','','まだ土地がありません。'));}
function pauseCPU(){clearTimeout(timer);generation++;worker?.terminate();worker=null;busy=false;}
function scheduleCPU(){clearTimeout(timer);if(document.hidden||document.documentElement.hasAttribute('data-aitech-guide-open')||el('confirm-dialog').open||el('rules-dialog').open||document.getElementById('aitech-assist-dialog')?.open||!cpuTurn()||(kind==='go'&&state.phase==='score')){busy=false;return;}busy=true;render();const id=generation;timer=setTimeout(()=>{if(id!==generation||!cpuTurn())return;if(kind==='monopoly'||kind==='life'){busy=false;runTrackCPU();return;}if(!worker){worker=new Worker(new URL('./cpu.mjs',import.meta.url),{type:'module'});worker.onerror=()=>cpuFailure();worker.onmessage=({data})=>{if(data.id!==generation||!cpuTurn())return;busy=false;if(data.error){cpuFailure();return;}const m=data.move;if(kind==='gomoku')perform(()=>G.move(state,m,state.turn));if(kind==='othello')perform(()=>E.othelloMove(state,m));if(kind==='go')perform(()=>m===-1?E.goPass(state):E.goMove(state,m));if(kind==='chess')perform(()=>R.chessMove(state,m));if(kind==='shogi')perform(()=>R.shogiMove(state,m));};}const data={id,kind};if(kind==='chess')data.fen=state.pos.fen();else if(kind==='shogi')data.fen=makeSfen(state.pos);else data.state=state;worker.postMessage(data);},650);}
function cpuFailure(){busy=false;worker?.terminate();worker=null;render();notice('CPUの処理を再開できませんでした。再試行してください。');el('actions').prepend(button('CPUを再試行',scheduleCPU));}
function runTrackCPU(){if(kind==='monopoly'){const p=state.players[1],phase=state.phase;if(phase==='buy')perform(()=>p.cash>E.ESTATES[p.pos][2]+100?E.propertyBuy(state):E.propertyAuction(state));else if(phase==='auction'){const a=state.auction;perform(()=>E.propertyBid(state,a.bid+10<=Math.min(p.cash-100,E.ESTATES[a.i][2]*1.15)));}else if(phase==='roll')perform(()=>E.propertyRoll(state));else if(phase==='end'){const i=E.ESTATES.findIndex((e,i)=>state.owners[i]===2&&E.estateGroup(state,i,2)&&!state.mortgages[i]&&state.houses[i]<3&&p.cash>600);if(i>=0)E.propertyManage(state,i,'build');perform(()=>E.propertyEnd(state));}else if(phase==='debt'){const house=state.houses.findIndex((n,i)=>n>0&&state.owners[i]===2);if(house>=0)perform(()=>E.propertyManage(state,house,'sell'));else{const land=state.owners.findIndex((n,i)=>n===2&&!state.mortgages[i]);perform(()=>land>=0?E.propertyManage(state,land,'mortgage'):E.propertyBankrupt(state));}}}else{const p=state.players[1];if(state.phase==='career')perform(()=>E.lifeCareer(state,1));else if(state.phase==='roll'){if(!p.insurance&&p.cash>=100)E.lifeInsure(state);perform(()=>E.lifeRoll(state));}else if(state.phase==='choice')perform(()=>E.lifeChoice(state,p.cash>600));else if(state.phase==='end')perform(()=>E.lifeEnd(state));}}
function askConfirm(title,fn,label='やり直す'){pauseCPU();confirmAction=fn;el('confirm-title').textContent=title;el('confirm-yes').textContent=label;el('confirm-dialog').showModal();return false;}
el('confirm-no').onclick=()=>el('confirm-dialog').close();el('confirm-yes').onclick=()=>{el('confirm-dialog').close();confirmAction?.();};el('restart').onclick=()=>askConfirm('対局を最初からやり直しますか？',init);el('resign').onclick=()=>askConfirm('投了しますか？',()=>{generation++;clearTimeout(timer);state.winner=kind==='gomoku'?1-state.turn:3-turn();state.message=`${names(turn())}が投了しました。`;busy=false;render();},'投了する');
el('game').onchange=()=>{const next=el('game').value;el('game').value=kind;askConfirm('ゲームを変更しますか？',()=>{kind=next;init();},'変更する');};el('mode').onchange=()=>{const next=el('mode').value;el('mode').value=mode;askConfirm('人数を変更して始め直しますか？',()=>{mode=next;init();},'変更する');};el('rules-open').onclick=()=>{pauseCPU();el('rules-dialog').showModal();};el('rules-close').onclick=()=>el('rules-dialog').close();el('motion').onclick=()=>{if(!scene)return;const paused=scene.pause();el('motion').textContent=paused?'動きを再開':'動きを止める';el('motion').setAttribute('aria-pressed',String(paused));};
for(const id of ['confirm-dialog','rules-dialog'])el(id).addEventListener('close',scheduleCPU);
document.addEventListener('aitech:guide-open',pauseCPU);
document.addEventListener('aitech:guide-close',scheduleCPU);
document.addEventListener('aitech:assist',e=>{if(e.detail.open)pauseCPU();else scheduleCPU();});
document.addEventListener('visibilitychange',()=>{if(document.hidden)pauseCPU();else scheduleCPU();});
init();import('./scene.mjs').then(({startScene})=>{try{scene=startScene(el('scene'));scene.set(turn(),winner());el('motion').textContent=scene.paused?'動きを再開':'動きを止める';el('motion').setAttribute('aria-pressed',String(scene.paused));}catch{el('scene-fallback').hidden=false;el('motion').hidden=true;}}).catch(()=>{el('scene-fallback').hidden=false;el('motion').hidden=true;});
