import {DESIGNS,THEMES} from './catalog.mjs';
import {WallpaperRenderer} from './renderer.mjs';

const $=id=>document.getElementById(id);
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
let preferences={sparkle:65,depth:60,brightness:100,motion:!reduced.matches,clock:true};
let favorites=new Set(),theme=-1,savedOnly=false,selected=DESIGNS[0],loadToken=0,ready=false,toastTimer;
try{const p=JSON.parse(localStorage.getItem('nocturne-preferences')||'null');if(p&&typeof p==='object')for(const k of Object.keys(preferences))if(typeof p[k]===typeof preferences[k])preferences[k]=p[k];const ids=JSON.parse(localStorage.getItem('nocturne-favorites')||'[]');if(Array.isArray(ids))favorites=new Set(ids.filter(n=>Number.isInteger(n)&&n>=1&&n<=100));}catch{}
for(const [key,min,max]of [['sparkle',0,100],['depth',0,100],['brightness',50,130]])preferences[key]=Math.min(max,Math.max(min,preferences[key]));
if(reduced.matches)preferences.motion=false;
function persist(){try{localStorage.setItem('nocturne-preferences',JSON.stringify(preferences));localStorage.setItem('nocturne-favorites',JSON.stringify([...favorites]));}catch{}}
function toast(message){$('toast').textContent=message;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),4500);}
const renderer=new WallpaperRenderer($('scene'),{onError:message=>{toast(typeof message==='string'?message:'立体表示を切り替えています。');}});
function options(){renderer.setOptions({sparkle:preferences.sparkle/100,depth:preferences.depth/100,brightness:preferences.brightness/100,motion:preferences.motion});}
for(const key of ['sparkle','depth','brightness']){$(key).value=preferences[key];$(key+'Value').value=preferences[key]+'%';$(key).addEventListener('input',()=>{preferences[key]=Number($(key).value);$(key+'Value').value=preferences[key]+'%';options();persist();});}
$('motion').checked=preferences.motion;$('motion').addEventListener('change',()=>{preferences.motion=$('motion').checked;options();persist();});
$('clockToggle').checked=preferences.clock;$('clock').hidden=!preferences.clock;$('clockToggle').addEventListener('change',()=>{preferences.clock=$('clockToggle').checked;$('clock').hidden=!preferences.clock;persist();});
reduced.addEventListener('change',e=>{if(e.matches){preferences.motion=false;$('motion').checked=false;options();persist();}});
function clock(){const d=new Date();$('clock').querySelector('span').textContent=new Intl.DateTimeFormat('ja-JP',{month:'long',day:'numeric',weekday:'long'}).format(d);$('clock').querySelector('b').textContent=new Intl.DateTimeFormat('ja-JP',{hour:'2-digit',minute:'2-digit',hour12:false}).format(d);}
clock();const clockInterval=setInterval(clock,60000);
function filtered(){return DESIGNS.filter(d=>(theme<0||d.theme===theme)&&(!savedOnly||favorites.has(d.id))).sort((a,b)=>theme<0?a.variant-b.variant||a.theme-b.theme:a.id-b.id);}
function favoriteButton(){const yes=favorites.has(selected.id);$('favorite').textContent=yes?'★':'☆';$('favorite').setAttribute('aria-pressed',String(yes));$('favorite').setAttribute('aria-label',yes?'お気に入りから削除':'お気に入りに追加');}
function renderGrid(){const items=filtered();$('grid').replaceChildren(...items.map(d=>{const b=document.createElement('button');b.type='button';b.className='wallpaper-card';b.dataset.id=d.id;b.setAttribute('aria-pressed',String(d.id===selected.id));b.setAttribute('aria-label',`${String(d.id).padStart(3,'0')} ${d.name}、${d.world}、${d.effect}`);b.innerHTML=`<span class="thumb"><img src="${d.thumb}" alt="" loading="lazy" decoding="async" width="216" height="360"><span class="design-number">${String(d.id).padStart(3,'0')}</span><span class="selected-check" aria-hidden="true">✓</span><span class="effect-tag">${d.effect}</span></span><span class="card-title">${d.name}${favorites.has(d.id)?' ★':''}</span><span class="card-world">${d.world}</span>`;b.addEventListener('click',()=>{void select(d.id);if(matchMedia('(max-width:760px)').matches&&!isExpanded())document.querySelector('.viewer').scrollIntoView({behavior:reduced.matches?'instant':'smooth',block:'start'});});return b;}));$('empty').hidden=items.length>0;$('empty').textContent=favorites.size?'この条件に合う壁紙はありません。別の世界か「すべて」を選んでください。':'お気に入りはまだありません。プレビューの ☆ で追加できます。';$('resultCount').textContent=`${savedOnly?'お気に入り':theme<0?'すべての世界':THEMES[theme].name} · ${items.length}件`;}
for(const [index,name]of [[-1,'すべて'],...THEMES.map((t,i)=>[i,t.short])]){const b=document.createElement('button');b.type='button';b.textContent=name;b.dataset.theme=index;b.setAttribute('aria-pressed',String(index===theme));b.addEventListener('click',()=>{theme=index;for(const other of $('filters').children)other.setAttribute('aria-pressed',String(Number(other.dataset.theme)===theme));renderGrid();});$('filters').append(b);}
$('savedFilter').addEventListener('click',()=>{savedOnly=!savedOnly;$('savedFilter').setAttribute('aria-pressed',String(savedOnly));renderGrid();});
$('favorite').addEventListener('click',()=>{if(favorites.has(selected.id))favorites.delete(selected.id);else favorites.add(selected.id);favoriteButton();persist();renderGrid();});
async function select(id,updateURL=true){const d=DESIGNS.find(d=>d.id===Number(id));if(!d)return;const token=++loadToken;selected=d;ready=false;$('loading').hidden=false;$('loading').textContent='壁紙を読み込み中…';$('save').disabled=true;$('sceneTitle').textContent=d.name;$('sceneWorld').textContent=d.world+' / '+d.effect;$('sceneNumber').textContent=String(d.id).padStart(2,'0')+' / 100';$('scene').setAttribute('aria-label',`${d.name}。${d.description} 指でなぞると奥行きが変わります。`);document.documentElement.style.setProperty('--accent',d.color);favoriteButton();for(const card of $('grid').children)card.setAttribute('aria-pressed',String(Number(card.dataset.id)===d.id));if(updateURL){const url=new URL(location.href);url.searchParams.set('id',d.id);history.replaceState(null,'',url);}try{await renderer.setDesign(d);if(token!==loadToken)return;options();ready=true;$('loading').hidden=true;$('save').disabled=false;}catch(e){if(token!==loadToken)return;$('loading').textContent='画像を読み込めませんでした。別の絵柄を選ぶか、通信を確認して再読み込みしてください。';toast('壁紙を読み込めませんでした。');console.error(e);}}
function step(delta){const list=filtered();const choices=list.length?list:DESIGNS;let index=choices.findIndex(d=>d.id===selected.id);if(index<0)index=delta>0?-1:0;void select(choices[(index+delta+choices.length)%choices.length].id);}
$('previous').addEventListener('click',()=>step(-1));$('next').addEventListener('click',()=>step(1));
$('scene').addEventListener('pointermove',e=>{const r=$('scene').getBoundingClientRect();renderer.setPointer((e.clientX-r.left)/r.width*2-1,(e.clientY-r.top)/r.height*2-1);});
for(const name of ['pointerleave','pointerup','pointercancel'])$('scene').addEventListener(name,()=>renderer.setPointer(0,0));
const stage=$('stage');function isExpanded(){return document.fullscreenElement===stage||stage.classList.contains('expanded');}
async function expand(){try{if(stage.requestFullscreen)await stage.requestFullscreen();else throw Error('unsupported');}catch{stage.classList.add('expanded');document.body.classList.add('has-expanded');}}
async function closeExpanded(){if(document.fullscreenElement)try{await document.exitFullscreen();}catch{}stage.classList.remove('expanded');document.body.classList.remove('has-expanded');}
$('expand').addEventListener('click',()=>void expand());$('closeFullscreen').addEventListener('click',()=>void closeExpanded());
document.addEventListener('keydown',e=>{if(e.key==='Escape'){void closeExpanded();return;}if(e.target instanceof HTMLInputElement||e.target instanceof HTMLButtonElement||e.target instanceof HTMLSelectElement)return;if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();step(e.key==='ArrowLeft'?-1:1);}});
$('save').addEventListener('click',async()=>{if(!ready)return;const token=loadToken;const d=selected;$('save').disabled=true;$('save').textContent='画像を作成中…';try{const blob=await renderer.renderStill(1080,2424);if(!blob||!blob.size)throw Error('Empty image');if(token!==loadToken){toast('絵柄が変わりました。もう一度保存してください。');return;}const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`nocturne-pixel10-${String(d.id).padStart(3,'0')}.png`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);toast('保存を開始しました。ダウンロードした画像を壁紙に設定できます。');}catch(e){toast('保存できませんでした。ページを再読み込みしてお試しください。');console.error(e);}finally{$('save').innerHTML='<span>↓</span> 壁紙を保存 <small>PNG · 1080 × 2424</small>';$('save').disabled=!ready;}});
// Optional browser-native tools expose exactly the same selection and local controls.
if(navigator.modelContext?.registerTool){try{navigator.modelContext.registerTool({name:'select_nocturne_wallpaper',description:'Preview one of the 100 dark fantasy wallpapers by id, 1 through 100.',inputSchema:{type:'object',properties:{id:{type:'integer',minimum:1,maximum:100}},required:['id'],additionalProperties:false},execute:async({id})=>{if(!Number.isInteger(id)||id<1||id>100)throw Error('id must be 1–100');await select(id);return{content:[{type:'text',text:JSON.stringify({id:selected.id,name:selected.name,ready})}]};}});}catch{}}
renderGrid();const initial=Number(new URL(location.href).searchParams.get('id'));void select(initial>=1&&initial<=100&&Number.isInteger(initial)?initial:1,false);
window.addEventListener('pagehide',e=>{if(!e.persisted){clearInterval(clockInterval);renderer.destroy();}});
