import {sqliteTable,text,integer,index,primaryKey} from 'drizzle-orm/sqlite-core';
export const rooms=sqliteTable('rooms',{id:text('id').primaryKey(),tool:text('tool').notNull(),title:text('title').notNull(),owner:text('owner').notNull(),created:integer('created').notNull(),updated:integer('updated').notNull(),canvasEpoch:integer('canvas_epoch').notNull().default(0),canvasRevision:integer('canvas_revision').notNull().default(0)});
export const members=sqliteTable('members',{room:text('room').notNull().references(()=>rooms.id,{onDelete:'cascade'}),actor:text('actor').notNull(),name:text('name').notNull(),seen:integer('seen').notNull()},t=>[primaryKey({columns:[t.room,t.actor]}),index('idx_members_actor').on(t.actor),index('idx_members_room_seen').on(t.room,t.seen)]);
export const items=sqliteTable('items',{room:text('room').notNull().references(()=>rooms.id,{onDelete:'cascade'}),id:text('id').notNull(),kind:text('kind').notNull(),body:text('body').notNull(),author:text('author').notNull(),name:text('name').notNull(),created:integer('created').notNull(),updated:integer('updated').notNull(),revision:integer('revision').notNull().default(1)},t=>[primaryKey({columns:[t.room,t.id]}),index('idx_items_room_created').on(t.room,t.created)]);
export const votes=sqliteTable('votes',{room:text('room').notNull().references(()=>rooms.id,{onDelete:'cascade'}),scope:text('scope').notNull(),actor:text('actor').notNull(),choice:text('choice').notNull(),updated:integer('updated').notNull()},t=>[primaryKey({columns:[t.room,t.scope,t.actor]}),index('idx_votes_room_actor').on(t.room,t.actor)]);
export const rateLimits=sqliteTable('rate_limits',{key:text('key').primaryKey(),window:integer('window').notNull(),count:integer('count').notNull()});

export const canvasResets=sqliteTable('canvas_resets',{room:text('room').primaryKey().references(()=>rooms.id,{onDelete:'cascade'}),id:text('id').notNull(),actor:text('actor').notNull(),created:integer('created').notNull(),revision:integer('revision').notNull(),state:text('state').notNull(),snapshot:text('snapshot').notNull()});

export const openingCache=sqliteTable('opening_cache',{key:text('key').primaryKey(),payload:text('payload').notNull(),updated:integer('updated').notNull().default(0),lockedUntil:integer('locked_until').notNull().default(0)});
