import * as T from 'three';
import { EffectComposer } from 'three/addons/postprocessing/EffectComposer.js';
import { RenderPass } from 'three/addons/postprocessing/RenderPass.js';
import { UnrealBloomPass } from 'three/addons/postprocessing/UnrealBloomPass.js';
import { OutputPass } from 'three/addons/postprocessing/OutputPass.js';
import { ShaderPass } from 'three/addons/postprocessing/ShaderPass.js';
import { FXAAShader } from 'three/addons/shaders/FXAAShader.js';
import { buildWorld,createTrack,v,canvasTexture,up } from './world.js';
import { buildCar } from './car.js';
import { fresh,step,clamp,damp,LIMIT,cornerSpeed } from './physics.mjs';
const $=id=>document.getElementById(id),coarse=matchMedia('(pointer:coarse)').matches;
const renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.14;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;$('stage').append(renderer.domElement);
const scene=new T.Scene(),camera=new T.PerspectiveCamera(55,innerWidth/innerHeight,.08,6000),target=new T.WebGLRenderTarget(1,1,{type:T.HalfFloatType});target.samples=0;
const composer=new EffectComposer(renderer,target);composer.addPass(new RenderPass(scene,camera));const bloom=new UnrealBloomPass(new T.Vector2(innerWidth,innerHeight),.24,.55,1.25);composer.addPass(bloom);composer.addPass(new OutputPass());const fxaa=new ShaderPass(FXAAShader);composer.addPass(fxaa);
const track=createTrack(),world=buildWorld(scene,renderer,track),player=buildCar(),rival=buildCar(0x9d522b,true);scene.add(player,rival);
$('route-length').textContent=(track.length/1000).toFixed(1)+' KM';
// Keep light counts constant to avoid recompiling shaders during a race.
const roadLights=[];scene.traverse(o=>{if(o.isPointLight)roadLights.push(o);});
for(const chunk of world.chunks)chunk.group.traverse(o=>{if(o.isMesh){o.userData.baseShadow=o.castShadow;o.updateMatrix();o.matrixAutoUpdate=false;}});
function updateWorld(s,p){world.update(s,p);for(const l of roadLights){l.intensity=l.visible?105:0;l.visible=true;}for(const chunk of world.chunks){const near=chunk.to>s-55&&chunk.from<s+110;for(const mesh of chunk.group.children)if(mesh.isMesh)mesh.castShadow=!!mesh.userData.baseShadow&&near;}rival.visible=true;}
let race=fresh(),state='menu',previous='race',count=3.4,last=0,accumulator=0,cameraMode=0,menuTime=0,frameNo=0,toastTimer=0,currentQuality='auto',qualityScale=1,lowFrames=0,emaFPS=60,best=null,warming=false,frameFrozen=false,drawDirty=true,driftTime=0,sound=false,audio=null,virtualInput=null;
try{best=JSON.parse(localStorage.getItem('touge-best-v1')||'null');if(best&&!Number.isFinite(best.time))best=null;const saved=JSON.parse(localStorage.getItem('touge-settings-v1')||'null');if(saved){for(const id of ['quality','difficulty'])if([...$(id).options].some(o=>o.value===saved[id]))$(id).value=saved[id];for(const id of ['assist','auto-gas','guide'])if(typeof saved[id]==='boolean')$(id).checked=saved[id];}}catch{}
const holds=new Map(),keys=new Set();
function saveSettings(){const o={};for(const id of ['quality','difficulty'])o[id]=$(id).value;for(const id of ['assist','auto-gas','guide'])o[id]=$(id).checked;try{localStorage.setItem('touge-settings-v1',JSON.stringify(o));}catch{}}
const lights=[];
for(const car of [player,rival])for(const side of [-1,1]){const light=new T.SpotLight(0xd6eaff,650,100,.31,.52,1.55);light.position.set(side*.55,.84,1.85);light.target.position.set(side*.7,-.6,43);car.add(light,light.target);light.castShadow=car===player&&side===-1;light.shadow.mapSize.set(1024,1024);light.shadow.bias=-.0001;light.shadow.normalBias=.025;lights.push(light);}
const smokeTex=canvasTexture(64,64,(c,w,h)=>{const g=c.createRadialGradient(32,32,0,32,32,32);g.addColorStop(0,'#c8d9e07f');g.addColorStop(.4,'#98abba49');g.addColorStop(1,'#778a9900');c.fillStyle=g;c.fillRect(0,0,w,h);});
const smoke=[];for(let j=0;j<48;j++){const m=new T.Sprite(new T.SpriteMaterial({map:smokeTex,color:0xb0c8dc,transparent:true,depthWrite:false,opacity:0}));m.visible=false;scene.add(m);smoke.push({mesh:m,life:0,age:0,vel:v()});}let smokeIndex=0,emit=0;
const maxMarks=1400,marks=new Float32Array(maxMarks*18),markGeo=new T.BufferGeometry();markGeo.setAttribute('position',new T.BufferAttribute(marks,3).setUsage(T.DynamicDrawUsage));markGeo.setDrawRange(0,0);const markMesh=new T.Mesh(markGeo,new T.MeshBasicMaterial({color:0x0c1420,transparent:true,opacity:.48,depthWrite:false,side:T.DoubleSide,polygonOffset:true,polygonOffsetFactor:-2}));markMesh.frustumCulled=false;scene.add(markMesh);let markIndex=0,markCount=0,previousTyres=null;
function effects(dt){for(const s of smoke)if(s.life>0){s.life-=dt;s.age+=dt;s.mesh.position.addScaledVector(s.vel,dt);s.mesh.position.y+=dt*.6;s.mesh.scale.setScalar(.38+s.age*2);s.mesh.material.opacity=Math.max(0,s.life)*.19;s.mesh.visible=s.life>0;}
if(state!=='race'||!race.drift){previousTyres=null;return;}driftTime+=dt;emit+=dt;const tyres=[v(-.89,.05,-1.32).applyMatrix4(player.matrixWorld),v(.89,.05,-1.32).applyMatrix4(player.matrixWorld)];
if(emit>.045){emit=0;for(const p of tyres){const s=smoke[smokeIndex++%smoke.length];s.mesh.position.copy(p).add(v(0,.15,0));s.life=.8;s.age=0;s.vel.copy(track.at(race.s).f).multiplyScalar(-race.v*.07);s.mesh.visible=true;}}
if(previousTyres)for(let k=0;k<2;k++){const a=previousTyres[k],b=tyres[k],right=track.at(race.s).r.clone().multiplyScalar(.10),aa=a.clone().sub(right),ab=a.clone().add(right),ba=b.clone().sub(right),bb=b.clone().add(right);[aa,ba,ab,ab,ba,bb].forEach((p,j)=>{const ix=(markIndex%maxMarks)*18+j*3;marks[ix]=p.x;marks[ix+1]=p.y;marks[ix+2]=p.z;});markIndex++;markCount=Math.min(maxMarks,markCount+1);markGeo.attributes.position.needsUpdate=true;markGeo.setDrawRange(0,markCount*6);}previousTyres=tyres;
}
const guideGeo=new T.BufferGeometry();guideGeo.setAttribute('position',new T.Float32BufferAttribute([-.26,0,-.4,0,0,.2,.26,0,-.4],3));guideGeo.computeVertexNormals();const guideMesh=new T.InstancedMesh(guideGeo,new T.MeshBasicMaterial({color:0xffffff,transparent:true,opacity:.46,side:T.DoubleSide,depthWrite:false}),32);guideMesh.frustumCulled=false;scene.add(guideMesh);
function updateGuide(){guideMesh.visible=$('guide').checked&&(state==='race'||state==='count');if(!guideMesh.visible)return;const matrix=new T.Matrix4(),color=new T.Color();for(let j=0;j<32;j++){const s=Math.min(track.length-1,race.s+8+j*5),a=track.frame(s,0,.048);matrix.compose(a.p,a.q,v(1.2,1,1.6));guideMesh.setMatrixAt(j,matrix);color.set(race.v>cornerSpeed(track.at(s+25).k)+3?0xff905d:0xc2e486);guideMesh.setColorAt(j,color);}guideMesh.instanceMatrix.needsUpdate=true;if(guideMesh.instanceColor)guideMesh.instanceColor.needsUpdate=true;}
function clearControls(){keys.clear();holds.clear();virtualInput=null;document.querySelectorAll('[data-hold]').forEach(b=>b.classList.remove('active'));}
function controls(){if(virtualInput)return virtualInput;const set=new Set([...holds.values(),...keys]);let gas=set.has('gas')?1:0,brake=set.has('brake')?1:0,drift=set.has('drift'),steer=(set.has('left')?1:0)-(set.has('right')?1:0);const pad=navigator.getGamepads?.()[0];if(pad){const x=pad.axes[0]||0;if(Math.abs(x)>.1)steer=-x;gas=Math.max(gas,pad.buttons[7]?.value||0);brake=Math.max(brake,pad.buttons[6]?.value||0);drift=drift||!!pad.buttons[0]?.pressed;}if($('auto-gas').checked)gas=brake?0:1;return {steer,gas,brake,drift};}
for(const b of document.querySelectorAll('[data-hold]')){b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);holds.set(e.pointerId,b.dataset.hold);b.classList.add('active');},{passive:false});const release=e=>{holds.delete(e.pointerId);b.classList.remove('active');};for(const name of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(name,release);}
const keyMap={ArrowLeft:'left',KeyA:'left',ArrowRight:'right',KeyD:'right',ArrowUp:'gas',KeyW:'gas',ArrowDown:'brake',KeyS:'brake',Space:'drift'};
addEventListener('keydown',e=>{if(['SELECT','INPUT','BUTTON'].includes(e.target.tagName)&&state==='menu')return;if(keyMap[e.code]){e.preventDefault();keys.add(keyMap[e.code]);}if(e.repeat)return;if(e.code==='KeyC')switchCamera();if(e.code==='KeyP'||e.code==='Escape')pause();if(e.code==='KeyR'&&state==='race')recover();});addEventListener('keyup',e=>{if(keyMap[e.code]){keys.delete(keyMap[e.code]);e.preventDefault();}});
function pause(){drawDirty=true;if(state==='paused'){state=previous;$('pause-layer').classList.add('hidden');last=performance.now();accumulator=0;}else if(state==='race'||state==='count'){previous=state;state='paused';clearControls();$('pause-layer').classList.remove('hidden');}}
addEventListener('blur',()=>{clearControls();if(state==='race'||state==='count')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearControls();if(state==='race'||state==='count')pause();}});$('pause-btn').onclick=pause;$('resume-btn').onclick=pause;
async function full(){try{if(!document.fullscreenElement)await $('shell').requestFullscreen?.();else await document.exitFullscreen?.();}catch{}try{await screen.orientation?.lock?.('landscape');}catch{}}$('fullscreen-btn').onclick=full;
function start(){if(warming)return;drawDirty=true;clearControls();saveSettings();race=fresh();count=3.4;state='count';driftTime=0;markIndex=markCount=0;markGeo.setDrawRange(0,0);previousTyres=null;smoke.forEach(s=>{s.life=0;s.mesh.visible=false});['start-layer','finish-layer','pause-layer'].forEach(id=>$(id).classList.add('hidden'));['hud','touch','countdown'].forEach(id=>$(id).classList.remove('hidden'));document.body.classList.add('racing');$('countdown').textContent='3';last=performance.now();accumulator=0;cameraMode=0;if(coarse&&!document.fullscreenElement)full();updateCar(player,race.s,race.x,0,0,0);updateCamera(1,true);if(sound)startAudio();}
$('start-btn').onclick=start;$('retry-btn').onclick=start;$('reset-btn').onclick=start;$('garage-btn').onclick=()=>{state='menu';clearControls();document.body.classList.remove('racing');['finish-layer','hud','touch'].forEach(id=>$(id).classList.add('hidden'));$('start-layer').classList.remove('hidden');race=fresh();};
function recover(){race.x=-1.5;race.v=Math.min(race.v,8);race.slip=0;race.contacts++;race.score=Math.max(0,race.score-150);showToast('コース復帰 / 減速ペナルティ',1.8);}
function switchCamera(){drawDirty=true;cameraMode=(cameraMode+1)%3;$('camera-btn').textContent=['追走','ボンネット','ワイド'][cameraMode];showToast(['CHASE CAMERA','BONNET CAMERA','WIDE CAMERA'][cameraMode],1);}$('camera-btn').onclick=switchCamera;
function showToast(text,seconds=2){$('toast').textContent=text;toastTimer=seconds;}
function format(t){const m=Math.floor(t/60);return String(m).padStart(2,'0')+':'+(t-m*60).toFixed(1).padStart(4,'0');}
function finish(){state='finish';clearControls();document.body.classList.remove('racing');['hud','touch','countdown'].forEach(id=>$(id).classList.add('hidden'));$('finish-layer').classList.remove('hidden');const success=race.reason==='finish',win=success?(race.rivalFinish===null||race.t<=race.rivalFinish):race.s>race.rival;$('finish-kicker').textContent=success?'DOWNHILL COMPLETE':'SESSION COMPLETE / 05:00';$('finish-title').textContent=success?(win?'YOU WIN.':'FINISH.'):'TIME UP.';$('finish-copy').textContent=success?(win?'ライバルを制し、峠を走り切りました。':'峠を走破。次はブレーキングを詰めて、ライバルの前へ。'):'5分のセッションが終了しました。ブレーキで速度を落としてから曲がると、安定して走れます。';$('result-rank').textContent=(win?'1':'2')+' / 2';$('result-time').textContent=format(race.t);$('result-score').textContent=String(Math.floor(race.score));$('result-speed').textContent=Math.round(race.top)+' km/h';if(success&&(!best||race.t<best.time)){best={time:race.t,score:Math.floor(race.score)};try{localStorage.setItem('touge-best-v1',JSON.stringify(best));}catch{}$('finish-kicker').textContent='NEW PERSONAL BEST';}}
function updateCar(car,s,l,slip,steer,dt){const a=track.frame(s,l,.014);car.position.copy(a.p);car.quaternion.copy(a.q);car.rotateY(slip);car.userData.body.rotation.z=damp(car.userData.body.rotation.z,-steer*.025,7,dt);car.userData.body.position.y=Math.sin(s*3.1)*.003*Math.min(1,race.v/20);for(const w of car.userData.wheels){w.spin.rotation.x+=(car===rival?race.rv:race.v)*dt/.36;w.pivot.rotation.y=damp(w.pivot.rotation.y,w.front?steer*.22-slip*.3:0,12,dt);}car.updateMatrixWorld(true);return a;}
function setPlayerVisible(on){player.visible=true;player.userData.body.visible=on;for(const w of player.userData.wheels)w.pivot.visible=on;player.userData.contact.visible=on;}
function updateCamera(dt,snap=false){const a=track.at(race.s),pos=v(),look=v();if(state==='menu'){const f=track.frame(8,-1.5),angle=-.75+Math.sin(menuTime*.1)*.11;pos.copy(f.p).addScaledVector(f.r,7.8*Math.cos(angle)).addScaledVector(f.f,7.8*Math.sin(angle)).addScaledVector(f.u,2.6);look.copy(f.p).addScaledVector(f.u,.8).addScaledVector(f.r,innerWidth>innerHeight?2.4:0);camera.fov=44;setPlayerVisible(true);}else if(state==='finish'){pos.copy(player.position).addScaledVector(a.r,6).addScaledVector(a.f,-6).add(v(0,2.5,0));look.copy(player.position).add(v(0,.7,0));setPlayerVisible(true);camera.fov=49;}else{setPlayerVisible(true);if(cameraMode===1){pos.copy(player.position).addScaledVector(a.f,.94).addScaledVector(a.u,1.07);look.copy(track.at(Math.min(track.length,race.s+35)).p).addScaledVector(a.r,race.x).addScaledVector(a.u,1.1);setPlayerVisible(false);}else{const far=cameraMode===2;pos.copy(player.position).addScaledVector(a.f,far?-10.5:-7.2).addScaledVector(a.u,far?4:2.75).addScaledVector(a.r,race.slip*2);look.copy(track.at(Math.min(track.length,race.s+13)).p).addScaledVector(a.r,race.x*.6).addScaledVector(a.u,.85);}camera.fov=damp(camera.fov,55+race.v*.14,2,dt);}if(snap)camera.position.copy(pos);else camera.position.lerp(pos,1-Math.exp(-7*dt));camera.up.copy(up);camera.lookAt(look);camera.updateProjectionMatrix();}
const mc=$('map').getContext('2d'),route=track.samples.filter((_,i)=>i%24===0),minX=Math.min(...route.map(a=>a.p.x)),maxX=Math.max(...route.map(a=>a.p.x)),maxZ=track.at(track.length).p.z,scale=Math.min(156/(maxX-minX),185/maxZ),mapXY=p=>[95+(p.x-(minX+maxX)/2)*scale,15+p.z*scale];
function map(){mc.clearRect(0,0,190,220);mc.lineWidth=6;mc.strokeStyle='#0a1723bb';mc.lineJoin='round';mc.beginPath();route.forEach((a,i)=>{const [x,y]=mapXY(a.p);i?mc.lineTo(x,y):mc.moveTo(x,y)});mc.stroke();mc.lineWidth=1.5;mc.strokeStyle='#acc0ccaa';mc.stroke();for(const [s,c,size] of [[race.rival,'#ffb06c',3],[race.s,'#e5ff70',4]]){const [x,y]=mapXY(track.at(s).p);mc.fillStyle=c;mc.beginPath();mc.arc(x,y,size,0,Math.PI*2);mc.fill();}}
function hud(){const gap=race.rival-race.s;$('rank').innerHTML=(gap>0?'2':'1')+'<span>/ 2</span>';$('gap').textContent=gap>0?'RIVAL +'+Math.round(gap)+' M':'LEAD '+Math.round(-gap)+' M';$('timer').textContent=format(Math.max(0,LIMIT-race.t));$('best').textContent='BEST '+(best?format(best.time):'—');$('distance').textContent=(race.s/1000).toFixed(1)+' / '+(track.length/1000).toFixed(1)+' KM';$('progress').style.width=(race.s/track.length*100)+'%';$('speed').textContent=Math.round(race.v*3.6);const gear=clamp(Math.floor(race.v*3.6/28)+1,1,5);$('gear').textContent=gear;$('rpm').style.width=(40+(race.v*3.6%28)/28*60)+'%';$('score').textContent=String(Math.floor(race.score)).padStart(5,'0');$('combo').textContent=race.drift?'DRIFT +'+Math.floor(race.combo):'';$('surface').textContent=race.drift?'SIDEWAYS':race.grip<.8?'SHOULDER':'GRIP';$('sector').textContent=race.s<track.length*.32?'01 / SUMMIT APPROACH':race.s<track.length*.68?'02 / FOREST SWITCHBACKS':'03 / VALLEY RUN';let max=0,at=0;for(let d=25;d<145;d+=10){const k=track.at(race.s+d).k;if(Math.abs(k)>Math.abs(max)){max=k;at=d;}}$('corner-symbol').textContent=Math.abs(max)>.013?(max>0?'↶':'↷'):Math.abs(max)>.002?(max>0?'↖':'↗'):'↑';$('corner-text').textContent=Math.abs(max)>.013?'HAIRPIN / '+at+' M':Math.abs(max)>.002?(max>0?'LEFT':'RIGHT')+' / '+at+' M':'STRAIGHT';map();}
async function applyQuality(){warming=true;$('start-btn').disabled=true;currentQuality=$('quality').value;const q=currentQuality==='auto'?(coarse?'balanced':'high'):currentQuality;qualityScale=q==='high'?Math.min(devicePixelRatio,2):q==='balanced'?Math.min(devicePixelRatio,1.3):Math.min(devicePixelRatio,1);qualityScale=Math.min(qualityScale,Math.sqrt((q==='high'?3200000:q==='balanced'?1350000:750000)/(innerWidth*innerHeight)));bloom.enabled=q!=='low';lights.forEach((l,i)=>l.castShadow=q==='high'&&i===0);world.sun.castShadow=q!=='low';resize();saveSettings();updateWorld(race.s,player.position);try{await renderer.compileAsync(scene,camera);}finally{warming=false;drawDirty=true;$('start-btn').disabled=false;last=performance.now();accumulator=0;}}
function resize(){drawDirty=true;const w=innerWidth,h=innerHeight;renderer.setPixelRatio(qualityScale);renderer.setSize(w,h);composer.setPixelRatio(qualityScale);composer.setSize(w,h);fxaa.material.uniforms.resolution.value.set(1/(w*qualityScale),1/(h*qualityScale));camera.aspect=w/h;camera.updateProjectionMatrix();$('render-mode').textContent=currentQuality.toUpperCase()+' '+qualityScale.toFixed(1)+'×';}
$('quality').onchange=()=>applyQuality().catch(console.error);addEventListener('resize',()=>{if(currentQuality==='auto')applyQuality();else resize();});renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();if(state==='race'||state==='count')pause();$('loading-layer').classList.remove('hidden');$('loading-text').textContent='3D描画が中断されました。再読み込みしてください。';$('reload-btn').classList.remove('hidden');});
function startAudio(){if(audio){audio.ctx.resume();return;}try{const ctx=new (window.AudioContext||window.webkitAudioContext)(),master=ctx.createGain(),filter=ctx.createBiquadFilter();master.gain.value=.065;master.connect(ctx.destination);filter.type='lowpass';filter.frequency.value=650;filter.connect(master);const oscs=[ctx.createOscillator(),ctx.createOscillator()];oscs.forEach((o,j)=>{o.type=j?'triangle':'sawtooth';o.connect(filter);o.start();});const buffer=ctx.createBuffer(1,ctx.sampleRate,ctx.sampleRate),data=buffer.getChannelData(0);for(let j=0;j<data.length;j++)data[j]=(Math.random()*2-1)*.2;const noise=ctx.createBufferSource();noise.buffer=buffer;noise.loop=true;const tyre=ctx.createGain();tyre.gain.value=0;const band=ctx.createBiquadFilter();band.type='bandpass';band.frequency.value=1500;noise.connect(band);band.connect(tyre);tyre.connect(master);noise.start();audio={ctx,master,filter,oscs,tyre};}catch{sound=false;}}
$('sound-btn').onclick=()=>{sound=!sound;if(sound)startAudio();$('sound-btn').textContent=sound?'音 ON':'音 OFF';};
function audioUpdate(){if(!audio)return;const t=audio.ctx.currentTime,gear=clamp(Math.floor(race.v*3.6/28),0,4),freq=45+(race.v*3.6-gear*28)*2.4;audio.master.gain.setTargetAtTime(sound&&(state==='race'||state==='count')?.065:0,t,.08);audio.oscs[0].frequency.setTargetAtTime(freq,t,.07);audio.oscs[1].frequency.setTargetAtTime(freq*1.995,t,.07);audio.filter.frequency.setTargetAtTime(500+race.v*28,t,.07);audio.tyre.gain.setTargetAtTime(race.drift?.55:race.grip<.8?.2:0,t,.09);}
function simulate(dt){if(state==='count'){count-=dt;$('countdown').textContent=count>.4?String(Math.ceil(count-.4)):'GO';if(count<=0){state='race';$('countdown').classList.add('hidden');showToast('白影峠 / DOWNHILL START',1.8);}}else if(state==='race'){const hits=race.contacts;step(race,dt,controls(),track,$('assist').checked,$('difficulty').value);if(race.contacts>hits){$('flash').style.borderWidth='6px';showToast('CONTACT / 減速',.75);}if(race.finished)finish();}}
function draw(now){requestAnimationFrame(draw);if(warming||frameFrozen){last=now;return;}const raw=last?Math.max(0,(now-last)/1000):.016;last=now;if(state==='paused'&&!drawDirty)return;drawDirty=false;const dt=Math.min(.1,raw);if(state!=='paused'){accumulator+=dt;while(accumulator>=1/120){simulate(1/120);accumulator-=1/120;}}else accumulator=0;menuTime+=dt;frameNo++;updateCar(player,state==='menu'?8:race.s,state==='menu'?-1.5:race.x,race.slip,race.steer,dt);updateCar(rival,state==='menu'?30:race.rival,track.rivalLane(race.rival),Math.sin(race.rival*.01)*.02,-track.at(race.rival).k*4,dt);rival.visible=true;updateWorld(state==='menu'?8:race.s,player.position);player.userData.tail.emissiveIntensity=controls().brake?6:2.2;updateCamera(dt);if(state!=='paused')effects(dt);if(frameNo%3===0){updateGuide();if(state==='race'||state==='count')hud();}if(toastTimer>0){toastTimer-=dt;if(toastTimer<=0){$('toast').textContent='';$('flash').style.borderWidth='0';}}audioUpdate();composer.render();emaFPS=damp(emaFPS,1/Math.max(.001,raw),.4,dt);if(currentQuality==='auto'&&state==='race'&&raw<2){lowFrames=emaFPS<27?lowFrames+1:Math.max(0,lowFrames-1);if(lowFrames>45&&qualityScale>.65){qualityScale=Math.max(.65,qualityScale*.82);lowFrames=0;resize();}}}
updateCar(player,8,-1.5,0,0,.1);updateCar(rival,30,track.rivalLane(30),0,0,.1);updateWorld(8,player.position);updateCamera(1,true);await applyQuality();composer.render();$('loading-layer').classList.add('hidden');$('start-layer').classList.remove('hidden');requestAnimationFrame(draw);
window.__touge={get state(){return state},get stats(){return {...race,length:track.length,quality:qualityScale,warming,frames:frameNo,version:'touge-3'};}};
if(['localhost','127.0.0.1'].includes(location.hostname)&&new URLSearchParams(location.search).has('test'))window.__touge.test={track,start,step:(dt,i)=>{virtualInput=i;simulate(dt);return {...race};},set:o=>{Object.assign(race,o);snapshot();},state:s=>{state=s;drawDirty=true;},render:snapshot,freeze:on=>{frameFrozen=on;last=performance.now();accumulator=0;},clear:()=>{virtualInput=null;},metrics:()=>({camera:camera.position.toArray(),player:player.position.toArray(),calls:renderer.info.render.calls})};
function snapshot(){updateCar(player,race.s,race.x,race.slip,race.steer,.016);updateCar(rival,race.rival,track.rivalLane(race.rival),0,0,.016);updateWorld(race.s,player.position);updateCamera(1,true);updateGuide();hud();composer.render();}
