import * as T from 'three';
import { createFoliage } from './foliage.js';
export const up=new T.Vector3(0,1,0),v=(x=0,y=0,z=0)=>new T.Vector3(x,y,z);
let seed=83475;export function rnd(){seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;}
export function canvasTexture(w,h,draw,srgb=true){const c=document.createElement('canvas');c.width=w;c.height=h;draw(c.getContext('2d'),w,h);const t=new T.CanvasTexture(c);if(srgb)t.colorSpace=T.SRGBColorSpace;return t;}
export function textTexture(text,bg='#152323',fg='#e7e9cd',w=512,h=128){return canvasTexture(w,h,(c)=>{c.fillStyle=bg;c.fillRect(0,0,w,h);c.strokeStyle=fg;c.lineWidth=5;c.strokeRect(6,6,w-12,h-12);c.fillStyle=fg;c.font=`bold ${h*.43}px sans-serif`;c.textAlign='center';c.textBaseline='middle';c.fillText(text,w/2,h/2,w-30)});}
export function createTrack(){
const pts=[[0,400,0],[0,395,160],[65,387,310],[230,376,430],[350,364,500],[390,350,620],[310,338,715],[130,322,680],[-80,308,610],[-220,295,670],[-255,282,770],[-175,268,860],[70,254,920],[240,240,1000],[270,226,1110],[180,212,1200],[-100,198,1270],[-240,184,1360],[-250,170,1470],[-100,156,1580],[170,142,1650],[280,135,1760],[260,125,1880],[70,116,1980],[-160,108,2070],[-230,101,2180],[-190,94,2300],[10,88,2410],[170,82,2510],[230,76,2630],[180,70,2730],[0,65,2800],[-170,60,2890],[-240,55,3010],[-200,50,3130],[-70,46,3250],[130,42,3380],[170,38,3510],[100,34,3630],[0,30,3790],[0,28,3930]].map(p=>v(...p));
const curve=new T.CatmullRomCurve3(pts,false,'centripetal');curve.arcLengthDivisions=16000;curve.updateArcLengths();const length=curve.getLength(),samples=[],N=Math.ceil(length/2);
for(let j=0;j<=N;j++){const t=j/N,p=curve.getPointAt(t),f=curve.getTangentAt(t).normalize(),r=v().crossVectors(up,f).normalize(),u=v().crossVectors(f,r).normalize();samples.push({p,f,r,u,yaw:Math.atan2(f.x,f.z),k:0});}
for(let j=0;j<=N;j++){const a=samples[Math.max(0,j-3)],b=samples[Math.min(N,j+3)],angle=Math.atan2(Math.sin(b.yaw-a.yaw),Math.cos(b.yaw-a.yaw));samples[j].k=angle/Math.max(1,(Math.min(N,j+3)-Math.max(0,j-3))*length/N);}
function at(s){const t=T.MathUtils.clamp(s/length,0,1)*N,j=Math.min(N-1,Math.floor(t)),a=samples[j],b=samples[j+1],q=t-j;return {p:a.p.clone().lerp(b.p,q),f:a.f.clone().lerp(b.f,q).normalize(),r:a.r.clone().lerp(b.r,q).normalize(),u:a.u.clone().lerp(b.u,q).normalize(),k:T.MathUtils.lerp(a.k,b.k,q)};}
function frame(s,l=0,y=0){const a=at(s);a.p.addScaledVector(a.r,l).addScaledVector(a.u,y);a.q=new T.Quaternion().setFromRotationMatrix(new T.Matrix4().makeBasis(a.r,a.u,a.f));return a;}
return {length,curve,samples,at,frame,rivalLane:s=>.5+Math.sin(s*.012)*1.3};}
function noiseTexture(){return canvasTexture(512,512,(c,w,h)=>{const image=c.createImageData(w,h);for(let i=0;i<w*h;i++){const z=30+rnd()*29;image.data[i*4]=z;image.data[i*4+1]=z+2;image.data[i*4+2]=z+4;image.data[i*4+3]=255;}c.putImageData(image,0,0);c.strokeStyle='#131b22';c.lineWidth=1.5;for(let j=0;j<12;j++){c.beginPath();let x=rnd()*w,y=rnd()*h;c.moveTo(x,y);for(let k=0;k<8;k++)c.lineTo(x+=rnd()*32-12,y+=rnd()*26);c.stroke();}});}
function makeBatch(group,geo,mat,frames,shadows=false){if(!frames.length)return;const m=new T.InstancedMesh(geo,mat,frames.length),matrix=new T.Matrix4();frames.forEach((f,i)=>{matrix.compose(f.p,f.q||new T.Quaternion(),f.scale||v(1,1,1));m.setMatrixAt(i,matrix);if(f.color)m.setColorAt(i,new T.Color(f.color));});m.castShadow=shadows;m.receiveShadow=true;m.computeBoundingSphere();group.add(m);return m;}
export function buildWorld(scene,renderer,track){
const chunks=[],lamps=[];
const envTex=canvasTexture(1024,512,(c,w,h)=>{const g=c.createLinearGradient(0,0,0,h);g.addColorStop(0,'#142b55');g.addColorStop(.45,'#799dbb');g.addColorStop(.52,'#58646a');g.addColorStop(.54,'#101b26');g.addColorStop(1,'#050a12');c.fillStyle=g;c.fillRect(0,0,w,h);c.fillStyle='#b9d4df';c.fillRect(690,70,130,36);for(let j=0;j<25;j++){c.fillStyle='#0e1b29';c.beginPath();c.moveTo(j*45-40,290);c.lineTo(j*45,210+rnd()*30);c.lineTo(j*45+70,290);c.fill();}c.fillStyle='#ffdda5';c.fillRect(130,235,8,15);});envTex.mapping=T.EquirectangularReflectionMapping;const pmrem=new T.PMREMGenerator(renderer),env=pmrem.fromEquirectangular(envTex).texture;scene.environment=env;scene.environmentIntensity=1.05;pmrem.dispose();envTex.dispose();
const sky=new T.Mesh(new T.SphereGeometry(4900,24,16),new T.ShaderMaterial({side:T.BackSide,depthWrite:false,uniforms:{},vertexShader:`varying vec3 dir;void main(){dir=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`varying vec3 dir;float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hash(i),hash(i+vec2(1,0)),f.x),mix(hash(i+vec2(0,1)),hash(i+1.),f.x),f.y);}void main(){vec3 d=normalize(dir);float h=max(0.,d.y);vec3 col=mix(vec3(.22,.29,.36),vec3(.018,.043,.10),pow(h,.42));vec2 p=d.xz/(h+.15);float cloud=noise(p*2.)*.55+noise(p*5.)*.3+noise(p*11.)*.15;col=mix(col,vec3(.18,.24,.30),smoothstep(.53,.77,cloud)*smoothstep(0.,.3,h)*.55);float stars=step(.9985,hash(floor(d.xz*1500.)))*pow(h,.8);col+=stars*.8;gl_FragColor=vec4(col,1.);}`}));sky.frustumCulled=false;scene.add(sky);
const moon=new T.Mesh(new T.SphereGeometry(17,24,16),new T.MeshBasicMaterial({color:0xc7e0f6}));moon.position.set(-650,1400,2600);scene.add(moon);scene.fog=new T.FogExp2(0x243646,.00155);
const ambient=new T.HemisphereLight(0x88b8ec,0x465349,2.15);scene.add(ambient);
const sun=new T.DirectionalLight(0xa9caff,2.2);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-22,right:22,top:22,bottom:-22,near:1,far:125});sun.shadow.bias=-.00015;sun.shadow.normalBias=.035;scene.add(sun,sun.target);
const tex=noiseTexture();tex.wrapS=tex.wrapT=T.RepeatWrapping;tex.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());
const asphalt=new T.MeshPhysicalMaterial({map:tex,color:0xb0bac2,roughness:.38,metalness:.1,clearcoat:.65,clearcoatRoughness:.19,envMapIntensity:.65,bumpMap:tex,bumpScale:.012});
asphalt.onBeforeCompile=shader=>{shader.vertexShader=shader.vertexShader.replace('#include <common>','#include <common>\nvarying vec3 wpos;').replace('#include <worldpos_vertex>','#include <worldpos_vertex>\nwpos=(modelMatrix*vec4(transformed,1.)).xyz;');shader.fragmentShader=shader.fragmentShader.replace('#include <common>','#include <common>\nvarying vec3 wpos;').replace('#include <roughnessmap_fragment>',`#include <roughnessmap_fragment>\nfloat puddleMask=sin(wpos.x*.37+sin(wpos.z*.19)*3.)*sin(wpos.z*.43);roughnessFactor*=mix(.38,1.45,smoothstep(-.3,.7,puddleMask));`);};
const verge=new T.MeshStandardMaterial({color:0x687063,roughness:.95,map:tex}),terrainMat=new T.MeshStandardMaterial({vertexColors:true,roughness:1,map:tex});
const lineMat=new T.MeshStandardMaterial({color:0xcba04b,roughness:.5,emissive:0x332007,emissiveIntensity:.12}),white=new T.MeshStandardMaterial({color:0xdbe0dc,roughness:.6}),steel=new T.MeshStandardMaterial({color:0x859097,metalness:.75,roughness:.35});
const {crown,trunk,leaf,bark}=createFoliage();
const rockMat=new T.MeshStandardMaterial({color:0x828781,roughness:.94,map:tex,bumpMap:tex,bumpScale:.09}),glow=new T.MeshBasicMaterial({color:0xffbb65}),rock=new T.DodecahedronGeometry(1,2);
const rp=rock.attributes.position;for(let j=0;j<rp.count;j++){const x=rp.getX(j),y=rp.getY(j),z=rp.getZ(j),n=1+Math.sin(x*9+z*13)*.14+Math.sin(y*15)*.09;rp.setXYZ(j,x*n,y*n,z*n);}rock.computeVertexNormals();
const curb=new T.BoxGeometry(.28,.16,1),rail=new T.BoxGeometry(.13,.38,1),post=new T.BoxGeometry(.15,1.05,.13),reflect=new T.BoxGeometry(.19,.07,.16);
function ribbon(from,to,lo,hi,height,mat){const positions=[],uv=[],indices=[],n=Math.ceil((to-from)/3);for(let j=0;j<=n;j++){const s=from+(to-from)*j/n,a=track.at(s);for(const l of [lo,hi]){const p=a.p.clone().addScaledVector(a.r,l).addScaledVector(a.u,height);positions.push(p.x,p.y,p.z);uv.push((l+6)/5,s/5);}if(j<n){const k=j*2;indices.push(k,k+2,k+1,k+1,k+2,k+3);}}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(positions,3));g.setAttribute('uv',new T.Float32BufferAttribute(uv,2));g.setIndex(indices);g.computeVertexNormals();const mesh=new T.Mesh(g,mat);mesh.receiveShadow=true;return mesh;}
const mountain=new T.MeshStandardMaterial({color:0x263c4c,roughness:1});
for(let i=0;i<22;i++){const geo=new T.SphereGeometry(1,32,24),p=geo.attributes.position;for(let j=0;j<p.count;j++){const x=p.getX(j),y=p.getY(j),z=p.getZ(j),ridge=1+.11*Math.sin(x*9+z*7)+.09*Math.sin(x*21-z*12);p.setXYZ(j,x,y>0?y*ridge:y,z);}geo.computeVertexNormals();const m=new T.Mesh(geo,mountain);m.scale.set(380+rnd()*500,180+rnd()*340,480+rnd()*400);m.position.set((i%2?1:-1)*(600+rnd()*500),-100+rnd()*160,i*220-200);scene.add(m);}
for(let from=0;from<track.length;from+=180){const to=Math.min(track.length,from+180),group=new T.Group();group.add(ribbon(from,to,-6.5,6.5,-.08,verge),ribbon(from,to,-5.7,5.7,0,asphalt));group.add(ribbon(from,to,-.11,.11,.015,lineMat));for(const side of [-1,1])group.add(ribbon(from,to,side*5.24-.07,side*5.24+.07,.018,white));
const positions=[],colors=[],uv=[],indices=[],widths=[-80,-40,-18,-8,-6,0,6,8,18,40,80],N=Math.ceil((to-from)/5);
for(let j=0;j<=N;j++){const s=from+(to-from)*j/N,a=track.at(s);for(let k=0;k<widths.length;k++){const w=widths[k],n=Math.sin(s*.032+w*.5)+Math.sin(s*.071-w*.3)*.4,p=a.p.clone().addScaledVector(a.r,w);p.y+=Math.abs(w)<7?-.28:Math.max(0,Math.abs(w)-7)*(w<0?.33:-.30)+n*Math.max(0,Math.abs(w)-8)*.045;positions.push(p.x,p.y,p.z);uv.push(p.x/9,p.z/9);const c=new T.Color().setHSL(.22+n*.012,.2,.34+n*.04);colors.push(c.r,c.g,c.b);if(j<N&&k<widths.length-1){const q=j*widths.length+k;indices.push(q,q+widths.length,q+1,q+1,q+widths.length,q+widths.length+1);}}}
const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(positions,3));g.setAttribute('color',new T.Float32BufferAttribute(colors,3));g.setAttribute('uv',new T.Float32BufferAttribute(uv,2));g.setIndex(indices);g.computeVertexNormals();const land=new T.Mesh(g,terrainMat);land.receiveShadow=true;group.add(land);
const rails=[],posts=[],reflectors=[],trees=[],rocks=[],curbs=[];
for(let s=from+1;s<to;s+=5){for(const side of [-1,1]){rails.push({...track.frame(s,side*6.1,.67),scale:v(1,1,5.1)});posts.push(track.frame(s,side*6.15,.45));if(Math.floor(s/5)%3===0)reflectors.push(track.frame(s,side*6,.83));curbs.push({...track.frame(s,side*5.8,.03),scale:v(1,1,5.1)});}}
for(let j=0;j<75;j++){const s=from+rnd()*(to-from),side=j%2?1:-1,l=side*(10+Math.pow(rnd(),1.5)*39),a=track.frame(s,l),n=Math.sin(s*.032+l*.5)+Math.sin(s*.071-l*.3)*.4;a.p.y+=Math.max(0,Math.abs(l)-7)*(side<0?.33:-.3)+n*Math.max(0,Math.abs(l)-8)*.045-.5;const size=.7+rnd()*1.1;a.scale=v(size,size*(1+rnd()*.3),size);a.q=new T.Quaternion().setFromAxisAngle(up,rnd()*6.28);trees.push(a);}
for(let j=0;j<12;j++){const s=from+rnd()*(to-from),l=-(7.6+rnd()*5),f=track.frame(s,l,.3);f.scale=v(1+rnd()*2,1+rnd()*2.5,1+rnd()*2);rocks.push(f);}
makeBatch(group,rail,steel,rails,true);makeBatch(group,post,steel,posts);makeBatch(group,reflect,glow,reflectors);makeBatch(group,curb,verge,curbs);makeBatch(group,trunk,bark,trees,true);makeBatch(group,crown,leaf,trees,true);makeBatch(group,rock,rockMat,rocks,true);
const s=from+85;if(s<track.length){const a=track.frame(s,-6.8),pole=new T.Mesh(new T.CylinderGeometry(.11,.16,8,8),steel);pole.position.copy(a.p).add(v(0,4,0));group.add(pole);const arm=new T.Mesh(new T.BoxGeometry(2,.09,.09),steel);arm.position.copy(a.p).addScaledVector(a.r,1);arm.position.y+=7.8;arm.quaternion.copy(a.q);group.add(arm);const bulb=new T.Mesh(new T.BoxGeometry(.7,.09,.3),new T.MeshBasicMaterial({color:0xffd1a0}));bulb.position.copy(a.p).addScaledVector(a.r,1.8);bulb.position.y+=7.76;bulb.quaternion.copy(a.q);group.add(bulb);lamps.push(bulb.position.clone());
const k=track.at(s+35).k,sign=new T.Mesh(new T.PlaneGeometry(1.25,1.25),new T.MeshStandardMaterial({map:textTexture(Math.abs(k)>.002?(k>0?'↶':'↷'):'40','#d6a326','#181c20',128,128),roughness:.5,side:T.DoubleSide}));sign.position.copy(a.p).addScaledVector(a.r,.3).add(v(0,2.2,0));sign.quaternion.copy(a.q);sign.rotateY(Math.PI);group.add(sign);
if(Math.abs(k)>.007){for(let j=0;j<5;j++){const f=track.frame(s+j*7,k>0?-6.35:6.35,1.25),board=new T.Mesh(new T.PlaneGeometry(1.3,.7),new T.MeshStandardMaterial({map:textTexture(k>0?'‹‹':'››','#d7b43a','#161b20',128,64),side:T.DoubleSide,roughness:.5}));board.position.copy(f.p);board.quaternion.copy(f.q);board.rotateY(Math.PI);group.add(board);}}
}
scene.add(group);chunks.push({from,to,group});}
for(const [s,label] of [[3,'白影峠  /  CLOSED COURSE'],[track.length-8,'FINISH  /  NIGHT RUNNERS']]){const a=track.frame(s),gate=new T.Group();for(const x of [-6.7,6.7]){const m=new T.Mesh(new T.BoxGeometry(.25,6,.25),steel);m.position.set(x,3,0);gate.add(m);}const board=new T.Mesh(new T.BoxGeometry(13.6,1.1,.2),new T.MeshStandardMaterial({color:0x192834,roughness:.4}));board.position.set(0,5.4,0);gate.add(board);const sign=new T.Mesh(new T.PlaneGeometry(13.2,.8),new T.MeshBasicMaterial({map:textTexture(label,'#172736','#e5edc9',1024,128)}));sign.position.set(0,5.4,-.12);sign.rotation.y=Math.PI;gate.add(sign);gate.position.copy(a.p);gate.quaternion.copy(a.q);scene.add(gate);}
const cabin=new T.Group(),wall=new T.Mesh(new T.BoxGeometry(6,3.5,8),new T.MeshStandardMaterial({color:0x465152,roughness:.9}));wall.position.set(0,1.75,0);cabin.add(wall);const roof=new T.Mesh(new T.ConeGeometry(6.5,2.2,4),new T.MeshStandardMaterial({color:0x242f38,roughness:.7}));roof.rotation.y=Math.PI/4;roof.position.y=4.5;cabin.add(roof);const window=new T.Mesh(new T.PlaneGeometry(3.5,1.4),new T.MeshBasicMaterial({map:textTexture('NIGHT  RUNNERS','#7a4c2f','#ffdd9a')}));window.position.set(0,2,-4.02);window.rotation.y=Math.PI;cabin.add(window);const cp=track.frame(38,12);cabin.position.copy(cp.p);cabin.quaternion.copy(cp.q);scene.add(cabin);
const roadLights=[];for(let i=0;i<4;i++){const light=new T.PointLight(0xffc584,105,25,1.7);scene.add(light);roadLights.push(light);}
return {sky,sun,asphalt,chunks,update(s,p){for(const c of chunks)c.group.visible=c.to>s-180&&c.from<s+750;sky.position.copy(p);sun.position.copy(p).add(v(-28,65,35));sun.target.position.copy(p);const nearest=lamps.map(pos=>({pos,d:pos.distanceToSquared(p)})).sort((a,b)=>a.d-b.d);roadLights.forEach((l,i)=>{l.position.copy(nearest[i].pos);l.visible=nearest[i].d<25000;});}};
}
