CREATE SCHEMA IF NOT EXISTS commons;
REVOKE ALL ON SCHEMA commons FROM PUBLIC, anon, authenticated;
CREATE TABLE commons.rooms (id text PRIMARY KEY, tool text NOT NULL, title text NOT NULL, owner text NOT NULL, created bigint NOT NULL, updated bigint NOT NULL, canvas_epoch integer NOT NULL DEFAULT 0, canvas_revision integer NOT NULL DEFAULT 0);
CREATE TABLE commons.members (room text NOT NULL REFERENCES commons.rooms(id) ON DELETE CASCADE, actor text NOT NULL, name text NOT NULL, seen bigint NOT NULL, PRIMARY KEY(room,actor));
CREATE INDEX commons_members_actor ON commons.members(actor);
CREATE INDEX commons_members_room_seen ON commons.members(room,seen);
CREATE TABLE commons.items (room text NOT NULL REFERENCES commons.rooms(id) ON DELETE CASCADE,id text NOT NULL,kind text NOT NULL,body text NOT NULL,author text NOT NULL,name text NOT NULL,created bigint NOT NULL,updated bigint NOT NULL,revision integer NOT NULL DEFAULT 1,PRIMARY KEY(room,id));
CREATE INDEX commons_items_room_created ON commons.items(room,created,id);
CREATE TABLE commons.votes(room text NOT NULL REFERENCES commons.rooms(id) ON DELETE CASCADE,scope text NOT NULL,actor text NOT NULL,choice text NOT NULL,updated bigint NOT NULL,PRIMARY KEY(room,scope,actor));
CREATE INDEX commons_votes_room_actor ON commons.votes(room,actor);
CREATE TABLE commons.canvas_resets(room text PRIMARY KEY REFERENCES commons.rooms(id) ON DELETE CASCADE,id text NOT NULL,actor text NOT NULL,created bigint NOT NULL,revision integer NOT NULL,state text NOT NULL,snapshot text NOT NULL);
CREATE TABLE commons.rate_limits(key text PRIMARY KEY,window_bucket bigint NOT NULL,count integer NOT NULL);
CREATE TABLE commons.opening_cache(key text PRIMARY KEY,payload text NOT NULL,updated bigint NOT NULL DEFAULT 0,locked_until bigint NOT NULL DEFAULT 0);
CREATE TABLE commons.config(key text PRIMARY KEY,value jsonb NOT NULL);
CREATE TABLE commons.account_actors(user_id uuid NOT NULL,actor text NOT NULL,PRIMARY KEY(user_id,actor));
CREATE TABLE commons.migration_snapshot(id text PRIMARY KEY,exported_at timestamptz NOT NULL,payload jsonb NOT NULL);
ALTER TABLE commons.rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE commons.members ENABLE ROW LEVEL SECURITY;
ALTER TABLE commons.items ENABLE ROW LEVEL SECURITY;
ALTER TABLE commons.votes ENABLE ROW LEVEL SECURITY;
ALTER TABLE commons.canvas_resets ENABLE ROW LEVEL SECURITY;
ALTER TABLE commons.rate_limits ENABLE ROW LEVEL SECURITY;
ALTER TABLE commons.opening_cache ENABLE ROW LEVEL SECURITY;
ALTER TABLE commons.config ENABLE ROW LEVEL SECURITY;
ALTER TABLE commons.account_actors ENABLE ROW LEVEL SECURITY;
ALTER TABLE commons.migration_snapshot ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON ALL TABLES IN SCHEMA commons FROM PUBLIC,anon,authenticated;
COMMENT ON SCHEMA commons IS 'Private Commons data. Access through the authenticated, owner-authorized commons-api function only.';
