import {MISSIONS,LEVELS,DECKS,GOALS,SUPPORTS,ENEMIES} from './missions.mjs';
import {createRun,getMission,getStep,command,resolveTurn,nextTurn,rank,validSnapshot} from './engine.mjs';
import {DefenseRoom,roomCode} from './room.mjs';
import {network,playSound} from './scene.mjs';
const app=document.getElementById('app'),dialog=document.getElementById('dialog');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const btn=(text,action,cls='',attrs='')=>`<button type="button" class="${cls}" data-action="${action}" ${attrs}>${text}</button>`;
const storage={get(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}},set(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true;}catch{return false;}}};
let progress=storage.get('aegis-progress-v1',{});if(!progress||typeof progress!=='object'||Array.isArray(progress))progress={};
let localSide=0;
let run=null,selected=1,level=0,mode='local',timed=true,room=null,busy=false,roomInput='',roomText='',sound=false,animationTimer,toastTimer,processed=new Set(),shownResult='',lastTick=performance.now(),helpPaused=false;
const host=()=>!room||room.side===0;
const blocked=()=>!!run&&(run.paused||!!room&&!room.online);
const permitted=side=>!room||room.side===side;
function toast(msg){const el=document.getElementById('toast');el.textContent=msg;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),4200);}
function tone(type){playSound(type,sound);}
function connection(){const el=document.getElementById('connection');el.textContent=room?`${room.code} · ${room.online?'2人接続':'相棒を待機'} · あなたはP${room.side+1}`:'ふたりのサイバー防衛戦';}
function missionButton(m){const p=progress[m.id];return btn(`<span class="mission-no">${String(m.id).padStart(3,'0')}</span><span class="mission-name"><strong>${esc(m.title)}</strong><small>${esc(m.place)} · ${DECKS[m.type].name}</small></span><span class="mission-rank ${p?'cleared':''}">${p?.rank?esc(p.rank):m.boss?'BOSS':'→'}</span>`,'mission',`mission ${m.id===selected?'selected':''} ${m.boss?'boss':''}`,`data-id="${m.id}" aria-pressed="${m.id===selected}" ${room&&!host()?'disabled':''}`);}
function lobby(){
 const m=getMission(selected),goal=GOALS[m.goal],enemy=ENEMIES[m.level],saved=storage.get('aegis-run-v1',null);
 return `<div class="lobby"><aside class="command-sidebar"><div class="menu-title"><p class="eyebrow">SELECT OPERATION</p><h1>夜明けまで、<br>守り抜け。</h1><p>対処するP1。支えるP2。<br>二人の選択が、街の運命を変える。</p></div><div class="completion"><b>${Object.keys(progress).filter(k=>+k>=1&&+k<=100).length}</b><span>/ 100<br>防衛成功</span></div><nav class="levels" aria-label="難易度">${LEVELS.map((d,i)=>btn(`<span>${d.name}</span><small>${d.en}</small><b>${String(i+1).padStart(2,'0')}</b>`,'level',level===i?'active':'',`data-id="${i}" aria-pressed="${level===i}" ${room&&!host()?'disabled':''}`)).join('')}</nav><p class="sidebar-note">全任務を最初から選択可能<br>1任務 約4〜8分 / 6回の判断</p><a class="back-link" href="../games-2d.html">← 2Dゲーム集</a></aside><section class="mission-catalog"><div class="catalog-heading"><div><p class="eyebrow">${LEVELS[level].en} / 20 MISSIONS</p><h2>${LEVELS[level].name}の防衛任務</h2></div><span class="mini-dot" style="background:${LEVELS[level].color}"></span></div><p class="difficulty-note">${LEVELS[level].description}</p><div class="mission-list">${MISSIONS.filter(m=>m.level===level).map(missionButton).join('')}</div></section><section class="briefing"><div class="briefing-scroll"><div class="brief-meta"><span>OP. ${String(m.id).padStart(3,'0')}</span><span>${m.boss?'⚠ BOSS ENCOUNTER':DECKS[m.type].name}</span></div><h2>${esc(m.title)}</h2><p class="opening">${esc(m.opening)}</p><div class="brief-network">${network(m,null)}</div><div class="mission-goal"><small>防衛目標</small><strong>${goal.name} ${m.floor}%以上で生還</strong><p>侵入率100% または いずれかの機能0%で敗北。</p></div><blockquote><b>${enemy.name}</b>${enemy.line}</blockquote><div class="mode-label">プレイ人数・接続方法</div><div class="mode-selector">${[['local','同じ端末で2人'],['solo','1人＋相棒CPU'],['online','オンライン2人']].map(([id,name])=>btn(name,'mode',mode===id?'active':'',`data-id="${id}" aria-pressed="${mode===id}" ${room?'disabled':''}`)).join('')}</div><p class="mode-help">${mode==='local'?'P1は左、P2は右を担当。手掛かりを声に出して共有しよう。':mode==='solo'?'P1を操作。相棒CPUは状況に合う支援を自動選択します。':'P1が部屋を作成し、P2が6文字のコードで参加。通話しながら遊ぼう。'}</p>${mode==='online'?roomPanel():''}<label class="time-option"><input id="timed" type="checkbox" ${timed?'checked':''} ${room&&!host()?'disabled':''}> 難易度に応じた制限時間を使う<span>入門は常に時間制限なし</span></label></div><div class="launch-actions">${btn(room&&room.side===1?(room.ready?'準備完了・P1を待機':'準備完了にする'):'防衛を開始する　→',room&&room.side===1?'ready':'start','primary launch',busy||mode==='online'&&(!room?.online||host()&&!room?.remoteReady)?'disabled':'')}${validSnapshot(saved)&&saved.phase!=='result'&&!room?btn('途中の任務を再開','resume','resume'):''}<span>ログイン不要 · スマホは横向き＋全画面がおすすめ</span></div></section></div>`;
}
function roomPanel(){return `<div class="room-panel">${room?`<div class="room-code"><span>ROOM CODE</span><strong>${esc(room.code)}</strong>${btn('招待をコピー','invite','small')}</div><p class="room-status">${room.online?'相棒と接続しました。'+(host()?(room.remoteReady?' 準備完了です。':' 相棒の準備を待っています。'):' 準備完了を押してください。'):'相棒の参加を待っています。'}</p>${btn('部屋を退出','leave','small')}`:`${btn('P1：部屋を作る','create','secondary',busy?'disabled':'')}<div class="join-row"><input id="room-code" aria-label="6文字のルームコード" maxlength="6" placeholder="6文字のコード" value="${esc(roomInput)}" autocomplete="off" autocapitalize="characters">${btn('P2：参加','join','secondary',busy?'disabled':'')}</div>`}<p role="status">${esc(roomText)}</p></div>`;}
function meters(){return `<div class="meters">${[['service','サービス稼働'],['data','データ保全'],['trust','信用'],['threat','敵の侵入率']].map(([key,label])=>`<div class="meter ${key} ${run[key]<35&&key!=='threat'||key==='threat'&&run[key]>65?'critical':''}"><div><span>${label}</span><strong>${Math.round(run[key])}<small>%</small></strong></div><progress max="100" value="${run[key]}" aria-label="${label}">${run[key]}%</progress></div>`).join('')}</div>`;}
function player(side,step){
 const disabled=blocked()||!permitted(side)||(mode==='solo'&&side===1),locked=run.locked[side],pick=run.picks[side];
 return `<section class="player player-${side} ${(room?room.side:localSide)===side?'role-active':''}" aria-label="P${side+1}の操作"><div class="player-heading"><span class="player-tag">P${side+1}</span><strong>${side===0?'対処担当 / NOVA':'支援担当 / ECHO'}</strong><span class="lock-status">${locked?'✓ 確定':!permitted(side)?'相棒の操作':mode==='solo'&&side===1?'CPU':'選択待ち'}</span>${btn('手掛かり','intel','intel-button',`data-side="${side}"`)}${mode==='local'?btn(side===0?'P2へ →':'← P1へ','switch-side','switch-side',`data-side="${1-side}"`):''}</div><p class="intel-inline"><span>${side===0?'観測':'現場'}</span>${esc(side===0?step.clue:step.supportClue)}</p><div class="${side===0?'action-options':'support-options'}">${side===0?step.options.map((o,i)=>btn(`<kbd>${i+1}</kbd><span>${esc(o.label)}</span><small>指揮 ${o.cost}</small>`,'pick',`choice ${pick===o.id?'chosen':''}`,`data-side="0" data-id="${o.id}" aria-pressed="${pick===o.id}" ${disabled||locked||run.cp<o.cost?'disabled':''}`)).join(''):SUPPORTS.map(s=>btn(`<span class="support-glyph">${{scan:'⌕',seal:'◇',keep:'↻',proof:'▤'}[s.id]}</span><span><strong>${s.name}</strong><small>${s.description}</small></span><kbd>${s.key}</kbd>`,'pick',`support-choice ${pick===s.id?'chosen':''}`,`data-side="1" data-id="${s.id}" aria-pressed="${pick===s.id}" ${disabled||locked?'disabled':''}`)).join('')}</div>${side===1?`<div class="link-row"><div><span>AEGIS LINK</span><progress max="100" value="${run.charge}" aria-label="連携ゲージ">${run.charge}%</progress></div>${btn(run.charge>=100?'連携技 発動！':`充填 ${run.charge}%`,'link','link-button',disabled||run.charge<100||run.ultimate?'disabled':'')}</div>`:`<div class="action-note">指揮力 <b>${run.cp}</b> · 判断後に1回復 / ${run.combo}連携</div>`}${btn(locked?'✓ 選択を確定しました':`P${side+1}：${side===0?'対処':'支援'}を確定`, 'lock',`lock-button ${locked?'is-locked':''}`,`data-side="${side}" ${disabled||locked||!pick?'disabled':''}`)}</section>`;
}
function play(){const m=getMission(run.id),step=getStep(run),enemy=ENEMIES[m.level],goal=GOALS[m.goal];
 return `<div class="operation ${m.boss?'boss-operation':''}"><div class="operation-heading"><div><span class="eyebrow">OP. ${String(m.id).padStart(3,'0')} / ${LEVELS[m.level].name} ${!run.timed&&m.level?'・時間制限なし':''}</span><h1>${esc(m.title)}</h1></div><div class="operation-tools">${btn('作戦記録','journal','small')}${btn(run.paused?'再開':'一時停止','pause','small',!host()?'disabled':'')}${btn('任務一覧','home','small')}</div></div>${meters()}<section class="situation"><div class="enemy-panel"><small>${m.boss?'BOSS ENCOUNTER':'THREAT ACTOR'}</small><b>${enemy.name}</b><p>${run.turn===0?enemy.line:run.threat>=65?'「守るものが多いほど、迷いは増える。」':run.combo>=2?'「その連携…目障りだ。」':'「次の扉が、もう開きかけている。」'}</p></div>${network(m,run)}<div class="goal-panel"><span>防衛目標</span><strong>${goal.unit} ${m.floor}%</strong><small>${run.combo>=2?`${run.combo} CHAIN / 連携中`:'二人の判断を重ねよう'}</small></div></section><div class="decision-heading"><div class="turn-number"><b>${String(run.turn+1).padStart(2,'0')}</b><span>/ 06</span></div><div class="decision-text"><p class="story-context">${esc(step.pressure)}</p><h2>${esc(step.prompt)}</h2></div><div id="clock" class="clock ${run.remaining>0&&run.remaining<=10?'urgent':''}">${clockText()}</div></div>${run.phase==='choose'?`<div class="player-grid">${player(0,step)}${player(1,step)}</div>`:resultPanel()}<div class="operation-foot"><span>${run.phase==='choose'?'二人が確定すると対処を実行。P1：1 / 2 / 3、P2：J / K / L / ;':''}</span><span>${esc(m.place)} · ${run.score.toLocaleString()} PT</span></div>${blocked()?`<div class="pause-layer"><div><p class="eyebrow">${run.paused?'PAUSED':'CONNECTION LOST'}</p><h2>${run.paused?'作戦を一時停止':'相棒との接続を待っています'}</h2><p>${run.paused?'準備ができたら続きを守ろう。':'接続が戻るまで判断時間を止めています。'}</p>${host()?btn(run.paused?'作戦を再開':'同じ端末で続ける',run.paused?'pause':'offline','primary'):''}${btn('任務一覧へ','home','secondary')}</div></div>`:''}</div>`;
}
function clockText(){return LEVELS[getMission(run.id).level].seconds&&run.timed?`${Math.max(0,Math.ceil(run.remaining))}<small>SEC</small>`:'∞<small>時間制限なし</small>';}
function resultPanel(){const h=run.history.at(-1);if(!h)return '';const ended=run.phase==='result';
 return `<section class="report ${h.sync?'report-sync':''} ${ended?'final-report':''}" aria-live="polite"><div class="report-emblem">${ended?rank(run):h.sync?'LINK':h.quality===2?'GOOD':h.quality===1?'HOLD':'HIT'}<small>${ended?'MISSION RANK':h.sync?`${run.combo} CHAIN`:'ACTION RESULT'}</small></div><div class="report-main"><p class="eyebrow">${ended?run.won?'MISSION COMPLETE':'MISSION FAILED':`ROUND ${run.turn+1} COMPLETE`}</p><h2>${ended?run.won?'防衛成功。夜明けは、二人のもの。':'防衛失敗。次の夜に、つなげよう。':h.label}</h2><p>${esc(ended?run.cause:h.summary+(h.sync?' 相棒の支援が噛み合い、被害を抑えた。':' 支援との組合せを見直す余地がある。'))}</p><div class="delta-row">${[['service','稼働'],['data','データ'],['trust','信用'],['threat','侵入']].map(([key,label])=>`<span class="${key==='threat'?h.delta[key]<=0?'positive':'negative':h.delta[key]>=0?'positive':'negative'}">${label} ${h.delta[key]>0?'+':''}${h.delta[key]}</span>`).join('')}</div><div class="lesson"><b>今回の判断から</b><span>${esc(h.lesson)}</span></div>${h.timeout?'<p class="negative">時間切れ：未確定の選択は実行されませんでした。</p>':''}<div class="report-actions">${ended?`${btn('もう一度挑む','retry','secondary',!host()?'disabled':'')}${run.id<100?btn('次の任務へ →','next-mission','primary',!host()?'disabled':''):btn('100の任務一覧へ','home','primary')}${btn('全判断を振り返る','journal','small')}`:btn('次の局面へ →','next','primary',!host()?'disabled':'')}</div></div></section>`;
}
function render(){connection();document.body.classList.toggle('playing',!!run);app.innerHTML=run?play():lobby();document.documentElement.style.setProperty('--level',LEVELS[getMission(run?.id||selected).level].color);}
function publish(){if(room?.side!==0||!room.online)return;if(run)room.send('snapshot',{run});else room.send('setup',{mission:selected,timed,ready:room.remoteReady});}
function remember(){if(!run)return;if(!room)storage.set('aegis-run-v1',run);if(run.phase==='result'&&run.won){const old=progress[run.id];if(!old||run.score>old.score){progress[run.id]={rank:rank(run),score:run.score};if(!storage.set('aegis-progress-v1',progress))toast('この端末ではクリア記録を保存できませんでした。');}}}
function update(next){if(next===run)return;const prior=run;run=next;remember();publish();render();if(prior?.phase==='choose'&&run.phase!=='choose'){tone(run.won?'win':run.history.at(-1)?.sync?'sync':'hit');if(run.history.at(-1)?.quality===0){app.classList.add('shake');clearTimeout(animationTimer);animationTimer=setTimeout(()=>app.classList.remove('shake'),350);}}}
function start(){localSide=0;if(mode==='online'&&(!room?.online||!host()||!room.remoteReady))return;processed.clear();run=createRun(selected,mode,timed,Date.now());lastTick=performance.now();update({...run});tone('tap');}
function maybeResolve(){if(!run||run.phase!=='choose'||!host()||blocked())return;
 if(mode==='solo'&&run.locked[0]&&run.charge>=100)run=command(run,1,'link');
 if(mode==='solo'&&run.locked[0]&&!run.locked[1]){const op=getStep(run).options.find(o=>o.id===run.picks[0]);run=command(run,1,'pick',op?.quality>0?op.support:getStep(run).support);run=command(run,1,'lock');}
 if(run.locked.every(Boolean))update(resolveTurn(run));else{remember();publish();render();}
}
function input(side,action,value){if(!run||blocked()||!permitted(side))return;if(room?.side===1){room.command({action,value,epoch:run.epoch,turn:run.turn});toast('P2の選択を送信しました');return;}const next=command(run,side,action,value);if(next!==run){if(action==='lock'&&mode==='local')localSide=1-side;update(next);if(action==='link')tone('link');else tone('tap');maybeResolve();}}
function showDialog(html){document.getElementById('dialog-content').innerHTML=html;if(!dialog.open)dialog.showModal();}
function journal(){showDialog(`<p class="eyebrow">OPERATION RECORD</p><h2>二人の作戦記録</h2>${run?.history.length?run.history.map(h=>`<article class="journal-entry"><b>${h.turn+1}. ${h.label}</b><p>P1：${esc(h.action)}<br>P2：${esc(h.support)}</p><p>${esc(h.lesson)}</p></article>`).join(''):'<p>判断を実行すると、選択と結果がここに残ります。</p>'}`);}
function help(){if(run&&host()&&!run.paused){helpPaused=true;update({...run,paused:true,revision:run.revision+1});}showDialog(`<p class="eyebrow">FIELD MANUAL</p><h2>二人で、夜明けを守る</h2><ol><li>任務と人数を選ぶ。オンラインならP1が部屋を作り、P2がコードで参加して準備完了。</li><li>P1は「対処」、P2は「支援」を選ぶ。手掛かりを声に出して共有しよう。横画面の小さい端末では「手掛かり」ボタンで確認できる。</li><li>二人が確定すると作戦実行。確定後の選び直しはできない。未確定のまま時間切れになると、その担当は行動できない。</li><li>的確な対処は指揮力3、応急手段は1、無消費の判断もある。毎回1回復。支援は無料。</li><li>対処に合った支援で連携成功。3連携でゲージが100になり、P2の「連携技」で全機能を13回復、侵入を18低下、指揮力を3回復。</li><li>6局面を終え、目標機能を規定値以上に守れば成功。どれかが0、または侵入100で敗北。</li></ol><p>P1：1 / 2 / 3 → Fで確定。P2：J / K / L / ; → Enterで確定。マウスやタッチでも操作できます。</p><p>1人モードでは相棒CPUが対処に合う支援を選ぶ。全100任務は最初から開放。クリア記録と同じ端末での途中経過は、このブラウザに保存します。</p><p class="fine">架空の組織・事件を描いたゲームです。実際の対応手順を簡略化しています。参考：<a href="https://www.cisa.gov/stopransomware/ransomware-guide" target="_blank" rel="noopener">CISA Ransomware Guide</a> / <a href="https://www.ipa.go.jp/security/" target="_blank" rel="noopener">IPA 情報セキュリティ</a></p>`);}
dialog.addEventListener('close',()=>{if(helpPaused&&run&&host()){helpPaused=false;update({...run,paused:false,revision:run.revision+1});lastTick=performance.now();}});
async function leave(){if(room)await room.close();room=null;roomText='';processed.clear();}
async function connect(side,code){if(busy)return;busy=true;roomText='通信を接続しています…';render();const n=new DefenseRoom();
 n.addEventListener('status',e=>{if(room!==n)return;if(!e.detail)roomText='通信が戻るまで作戦を待機します。';else roomText='相棒と接続しました。';lastTick=performance.now();publish();render();});
 n.addEventListener('hello',()=>{if(room!==n)return;if(n.side===0)publish();else n.send('ready',{ready:n.ready,mission:selected,timed});});
 n.addEventListener('message',e=>{if(room===n)receive(e.detail);});
 try{await leave();room=n;await n.connect(side,code);roomText=side===0?'相棒にコードを伝えてください。':'P1の作戦を受信しています。';}
 catch(e){roomText=e.message;await n.close();if(room===n)room=null;toast(e.message);}
 finally{busy=false;render();}
}
function receive(m){
 if(host()){
  if(m.kind==='ready'&&!run&&m.mission===selected&&m.timed===timed){room.remoteReady=m.ready===true;publish();render();return;}
  if(m.kind==='command'&&typeof m.commandId==='string'&&m.commandId.length<80){room.ack(m.commandId);if(processed.has(m.commandId)){publish();return;}processed.add(m.commandId);if(processed.size>500)processed.delete(processed.values().next().value);if(run&&m.epoch===run.epoch&&m.turn===run.turn&&run.phase==='choose'&&!blocked()){const previous=run;const next=command(run,1,m.action,m.value);update(next);if(m.action==='link'&&next!==previous)tone('link');maybeResolve();}publish();}
 }else{
  if(m.kind==='setup'&&Number.isInteger(m.mission)&&m.mission>=1&&m.mission<=100){if(selected!==m.mission||timed!==m.timed||run){room.ready=false;run=null;}selected=m.mission;level=getMission(selected).level;timed=m.timed===true;render();}
  if(m.kind==='snapshot'&&validSnapshot(m.run)){if(run&&m.run.epoch===run.epoch&&m.run.revision<=run.revision){run.remaining=m.run.remaining;const clock=document.getElementById('clock');if(clock)clock.innerHTML=clockText();return;}selected=m.run.id;level=getMission(selected).level;const previous=run;run=m.run;mode='online';remember();render();if(previous?.phase==='choose'&&run.phase!=='choose')tone(run.won?'win':run.history.at(-1)?.sync?'sync':'hit');}
 }
}
app.addEventListener('change',e=>{if(e.target.id==='timed'&&host()){timed=e.target.checked;if(room){room.remoteReady=false;publish();}render();}});
app.addEventListener('input',e=>{if(e.target.id==='room-code')roomInput=e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,'');});
app.addEventListener('click',async e=>{
 const b=e.target.closest('button[data-action]');if(!b||b.disabled)return;const a=b.dataset.action;
 if(a==='level'&&host()){level=+b.dataset.id;selected=level*20+1;if(room)room.remoteReady=false;publish();render();}
 if(a==='mission'&&host()){selected=+b.dataset.id;if(room)room.remoteReady=false;publish();render();}
 if(a==='switch-side'){localSide=+b.dataset.side;render();}
 if(a==='mode'&&!room){mode=b.dataset.id;render();}
 if(a==='start')start();
 if(a==='resume'){const saved=storage.get('aegis-run-v1',null);if(validSnapshot(saved)){run={...saved,paused:false};selected=run.id;level=getMission(selected).level;mode=run.mode==='solo'?'solo':'local';timed=run.timed;lastTick=performance.now();render();}}
 if(a==='pick')input(+b.dataset.side,'pick',b.dataset.id);
 if(a==='lock')input(+b.dataset.side,'lock');
 if(a==='link')input(1,'link');
 if(a==='next'&&host()){localSide=0;update(nextTurn(run));lastTick=performance.now();}
 if(a==='retry'&&host())start();
 if(a==='next-mission'&&host()){selected=Math.min(100,run.id+1);level=getMission(selected).level;run=null;if(room)room.remoteReady=false;publish();render();}
 if(a==='pause'&&host()){update({...run,paused:!run.paused,revision:run.revision+1});lastTick=performance.now();}
 if(a==='journal')journal();
 if(a==='intel'){const step=getStep(run);const side=+b.dataset.side;showDialog(`<p class="eyebrow">P${side+1} / INTELLIGENCE</p><h2>${side===0?'観測記録':'現場の情報'}</h2><p>${esc(side===0?step.clue:step.supportClue)}</p><p>${esc(getMission(run.id).evidence)}</p><p class="fine">相棒に伝え、対処と支援を組み合わせよう。</p>`);}
 if(a==='home'){if(run?.phase==='choose'&&host())update({...run,paused:true,revision:run.revision+1});showDialog(`<h2>任務一覧へ戻る</h2><p>${room?'オンラインの部屋を退出します。':'途中の任務はこの端末に保存されています。'}</p>${btn('一覧へ戻る','confirm-home','primary')}`);}
 if(a==='create')await connect(0,roomCode());
 if(a==='join'){if(!/^[A-Z0-9]{6}$/.test(roomInput)){toast('6文字のコードを入力してください。');return;}await connect(1,roomInput);}
 if(a==='ready'&&room?.side===1){room.ready=true;room.send('ready',{ready:true,mission:selected,timed});render();}
 if(a==='leave'){await leave();render();}
 if(a==='offline'&&host()){await leave();mode='local';run={...run,mode:'local'};update({...run});}
 if(a==='invite'&&room){const url=new URL(location.href);url.search='';url.searchParams.set('room',room.code);try{await navigator.clipboard.writeText(url.href);toast('招待リンクをコピーしました');}catch{toast('部屋のコード：'+room.code);}}
});
dialog.addEventListener('click',async e=>{if(e.target.closest('[data-action="confirm-home"]')){helpPaused=false;dialog.close();remember();await leave();run=null;render();}});
document.getElementById('sound').onclick=()=>{sound=!sound;const b=document.getElementById('sound');b.textContent=sound?'音 ON':'音 OFF';b.setAttribute('aria-pressed',String(sound));tone('tap');};
document.getElementById('help').onclick=help;
document.getElementById('fullscreen').onclick=async()=>{try{if(document.fullscreenElement){await document.exitFullscreen();return;}await document.documentElement.requestFullscreen();try{await screen.orientation?.lock?.('landscape');}catch{}}catch{document.documentElement.classList.toggle('expanded');toast('画面内を最大表示しました。端末を横向きにすると大きく遊べます。');}};
document.addEventListener('fullscreenchange',()=>{const b=document.getElementById('fullscreen');b.textContent=document.fullscreenElement?'↙ 全画面を終了':'⛶ 全画面';b.setAttribute('aria-pressed',String(!!document.fullscreenElement));});
document.addEventListener('keydown',e=>{if(e.repeat||e.ctrlKey||e.metaKey||e.altKey||dialog.open||['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName))return;if(!run||run.phase!=='choose')return;const i=['1','2','3'].indexOf(e.key);if(i>=0){e.preventDefault();input(0,'pick',getStep(run).options[i].id);}const j=['j','k','l',';'].indexOf(e.key.toLowerCase());if(j>=0){e.preventDefault();input(1,'pick',SUPPORTS[j].id);}if(e.key.toLowerCase()==='f'){e.preventDefault();input(0,'lock');}if(e.key==='Enter'){e.preventDefault();input(1,'lock');}});
setInterval(()=>{const now=performance.now(),elapsed=(now-lastTick)/1000;lastTick=now;if(!run||!host()||blocked()||run.phase!=='choose'||!run.timed||!LEVELS[getMission(run.id).level].seconds)return;if(!room&&document.hidden)return;run.remaining=Math.max(0,run.remaining-elapsed);const clock=document.getElementById('clock');if(clock){clock.innerHTML=clockText();clock.classList.toggle('urgent',run.remaining<=10);}if(run.remaining<=0)update(resolveTurn(run,true));},250);
setInterval(()=>{if(room?.online){if(host())publish();else if(!run)room.send('ready',{ready:room.ready,mission:selected,timed});}},2000);
document.addEventListener('visibilitychange',()=>{lastTick=performance.now();if(document.hidden)remember();});
window.addEventListener('pagehide',()=>{remember();room?.close();});
const invitation=new URLSearchParams(location.search).get('room');if(invitation&&/^[A-Z0-9]{6}$/i.test(invitation)){mode='online';roomInput=invitation.toUpperCase();roomText='招待されたコードです。「P2：参加」で入れます。';}
render();
