import {GAMES,GAME_BY_ID,createGame,action,tick,view,isRealtime} from './engine.mjs';
import {OnlineRoom} from './network.mjs';
import {Renderer,COLORS} from './render.mjs?v=physical2';
const $=id=>document.getElementById(id),stage=$('stage'),renderer=new Renderer(stage);
let spec=null,net=null,hostState=null,state=null,side=0,preview=true,filter='all',choice=0,selectedCard=-1,selectedCell=-1,lastUI='',sound=false,audio=null,lastInput=0,lastCheckpoint=0,lastFrame=performance.now(),elapsed=0,roomStatus='',busy=false,focused=true;
const inputs={},input={x:0,y:0,aimX:500,aimY:300,primary:false},keys=new Set(),pending=new Map(),accepted=new Map(),sendTimes=new Map(),inputTimes={},rates={};
renderer.graphics.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const notice=t=>$('notice').textContent=t;
function beep(){if(!sound)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),gain=audio.createGain();o.type='sine';o.frequency.setValueAtTime(450,audio.currentTime);o.frequency.exponentialRampToValueAtTime(720,audio.currentTime+.05);gain.gain.setValueAtTime(.045,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.13);o.connect(gain);gain.connect(audio.destination);o.start();o.stop(audio.currentTime+.14);}catch{}}
function listGames(){const search=$('search').value.toLowerCase(),category=$('category').value;const games=GAMES.filter(g=>(filter==='all'||g.mode===filter)&&(!category||g.category===category)&&(!search||(g.title+g.concept).toLowerCase().includes(search)));$('games').innerHTML=games.map(g=>`<button class="game-card" data-game="${g.id}"><div class="card-art"><div class="world-tile" style="background-position:${g.theme%4/3*100}% ${Math.floor(g.theme/4)/3*100}%"></div><span class="card-character" aria-hidden="true" style="background-position:${(g.number%4)/3*100}% ${Math.floor((g.family==='race'?8:g.family==='combat'?4:g.family==='cards'?12:0)/4)/3*100}%"></span><span class="game-number">${String(g.number).padStart(3,'0')}</span><span class="card-mode ${g.mode}">${g.mode==='coop'?'CO-OP / 協力':'VERSUS / 対戦'}</span></div><div class="card-content"><h2>${esc(g.title)}</h2><div class="card-info"><span>${g.minPlayers===g.maxPlayers?g.minPlayers:g.minPlayers+'–'+g.maxPlayers}人</span><span>${Math.ceil(g.duration/60)}分</span><span>${esc(g.category)}</span></div></div></button>`).join('');$('empty').hidden=games.length>0;}
for(const category of [...new Set(GAMES.map(g=>g.category))])$('category').add(new Option(category,category));
$('games').addEventListener('click',e=>{const id=e.target.closest('[data-game]')?.dataset.game;if(id)selectGame(id);});$('search').oninput=listGames;$('category').onchange=listGames;document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));listGames();});
function selectGame(id,fromRoom=false){if(!GAME_BY_ID[id])return;if(net?.room&&!fromRoom){notice('別のゲームへ移るには、現在のルームを退出してください。');$('library').hidden=true;$('play').hidden=false;return;}spec=GAME_BY_ID[id];selectedCell=selectedCard=renderer.selected=-1;document.documentElement.style.setProperty('--scene-x',spec.theme%4/3*100+'%');document.documentElement.style.setProperty('--scene-y',Math.floor(spec.theme/4)/3*100+'%');$('library').hidden=true;$('play').hidden=false;$('gameTitle').textContent=spec.title;$('gameMeta').textContent=String(spec.number).padStart(3,'0')+' / '+(spec.mode==='coop'?'CO-OP':'VERSUS')+' / '+spec.minPlayers+'–'+spec.maxPlayers+' PLAYERS';$('inputHelp').textContent=['arena','combat','race','sports'].includes(spec.family)?'PC：矢印 / WASDで移動、Space / ZでA、XでB。クリックで狙いを指定。スマホ：左スティックとA・B。':'盤面や手札を選び、下のボタンで操作します。自分の手番はプレイヤー名の枠が光ります。';if(!fromRoom){side=0;preview=true;hostState=null;state=view(createGame(id,Array.from({length:spec.minPlayers},(_,i)=>({id:'preview'+i,name:'PLAYER '+(i+1)})),12345),0);$('rules').textContent=state.goal;$('stageOverlay').hidden=false;$('stageOverlay').innerHTML='<div><p class="eyebrow">READY WHEN YOU ARE</p><h2>ルームを作って、友達を呼ぼう。</h2><p>招待コードがあれば、すぐに参加できます。</p></div>';$('actionPanel').innerHTML='';$('hand').innerHTML='';$('market').innerHTML='';$('scoreboard').innerHTML='';$('privateInfo').hidden=true;history.replaceState(null,'','?game='+id);}window.scrollTo({top:0});}
$('libraryButton').onclick=()=>{if(net?.room){$('play').hidden=true;$('library').hidden=false;}else{$('play').hidden=true;$('library').hidden=false;history.replaceState(null,'',location.pathname);}listGames();};
async function withBusy(fn){if(busy)return;busy=true;notice('');$('create').disabled=$('join').disabled=true;try{await fn();}catch(e){notice(e.message);if(!net?.ready){net?.close();net=null;}}finally{busy=false;$('create').disabled=$('join').disabled=false;}}
async function setupNet(){if(net)return net;net=await new OnlineRoom().init();net.addEventListener('room',e=>roomUpdate(e.detail));net.addEventListener('message',e=>receive(e.detail));net.addEventListener('error',e=>notice(e.detail));net.addEventListener('connection',e=>{$('connection').textContent=e.detail.online?'仲間と接続しています':'通信を再接続しています…';});net.addEventListener('latency',e=>{$('connection').textContent=(net.direct(e.detail.id)?'端末間通信':'中継通信')+' · '+Math.round(e.detail.ms)+' ms';});return net;}
$('create').onclick=()=>withBusy(async()=>{if(!spec)return;const n=await setupNet();await n.create(spec.id,$('name').value||'PLAYER');});
$('join').onclick=()=>withBusy(async()=>{const n=await setupNet();await n.join($('roomCode').value,$('name').value||'PLAYER');});
$('resume').onclick=()=>withBusy(async()=>{const n=await setupNet();const r=await n.resume();if(!r)throw new Error('復帰できるルームがありません。');if(r.checkpoint&&r.side===0){hostState=r.checkpoint;preview=false;state=view(hostState,0);}});
$('ready').onclick=()=>withBusy(()=>net.setReady(!net.me.ready));$('start').onclick=()=>withBusy(()=>net.start());$('rematch').onclick=()=>withBusy(()=>net.rematch());
$('leave').onclick=async()=>{const id=spec.id;await net?.leave();net=null;hostState=null;state=null;pending.clear();accepted.clear();roomStatus='';$('lobby').hidden=false;$('roomPanel').hidden=true;$('leave').hidden=true;$('touchControls').hidden=true;selectGame(id);notice('ルームを退出しました。');};
$('copyInvite').onclick=async()=>{const url=new URL(location.href);url.searchParams.set('game',spec.id);url.searchParams.set('room',net.room.room);try{await navigator.clipboard.writeText(url.href);notice('招待リンクをコピーしました。');}catch{notice('招待コード：'+net.room.room);}};
function roomUpdate(r){if(!GAME_BY_ID[r.game])return;if(spec?.id!==r.game)selectGame(r.game,true);side=r.side;$('lobby').hidden=true;$('roomPanel').hidden=false;$('leave').hidden=false;$('codeDisplay').textContent=r.room;$('members').innerHTML=r.members.map((m,i)=>`<li style="color:${COLORS[i]}">${esc(m.name)}<span>${i===0?'HOST':m.ready?'準備OK':'準備中'}</span></li>`).join('');$('start').hidden=side!==0||r.status!=='waiting';$('start').disabled=r.members.length<spec.minPlayers||r.members.some(m=>!m.ready);$('ready').hidden=side===0||r.status!=='waiting';$('ready').textContent=r.members[side]?.ready?'準備を取り消す':'準備OK';$('rematch').hidden=side!==0||r.status!=='finished';
 if(r.status==='waiting'){if(roomStatus!=='waiting'){hostState=null;preview=true;state=view(createGame(spec.id,Array.from({length:spec.minPlayers},(_,i)=>({id:'p'+i,name:r.members[i]?.name||'PLAYER '+(i+1)})),12345),side);pending.clear();}const needed=Math.max(0,spec.minPlayers-r.members.length);$('stageOverlay').hidden=false;$('stageOverlay').innerHTML=`<div><p class="eyebrow">ROOM ${esc(r.room)}</p><h2>${needed?'あと'+needed+'人で遊べます。':'仲間の準備を待っています。'}</h2><p>招待コードを友達へ送り、全員が準備OKになったら開始。</p></div>`;$('touchControls').hidden=true;}
 if(r.status==='playing'){if(side===0&&!hostState){hostState=r.checkpoint||createGame(spec.id,r.members,crypto.getRandomValues(new Uint32Array(1))[0]);lastCheckpoint=0;}preview=false;$('stageOverlay').hidden=true;if(side===0)state=view(hostState,0);$('touchControls').hidden=!state||!isRealtime(state)||!matchMedia('(pointer:coarse)').matches;}
 if(r.status==='closed'){notice('ホストがルームを終了しました。');$('stageOverlay').hidden=false;$('stageOverlay').innerHTML='<div><h2>ルームが終了しました。</h2><p>退出して、新しいルームを作れます。</p></div>';}
 roomStatus=r.status;if(state){$('rules').textContent=state.goal;updateUI(true);}
 }
function receive({side:sender,body,from}){if(body.type==='state'&&sender===0&&side!==0&&body.state?.id===spec?.id){state=body.state;preview=false;lastInput=performance.now();$('stageOverlay').hidden=true;$('touchControls').hidden=!isRealtime(state)||!matchMedia('(pointer:coarse)').matches;updateUI();return;}
 if(body.type==='input'&&side===0){if(sender<1||sender>=net.room.members.length)return;const i=body.input||{};inputs[sender]={x:Math.max(-1,Math.min(1,Number(i.x)||0)),y:Math.max(-1,Math.min(1,Number(i.y)||0)),primary:!!i.primary,aimX:Math.max(0,Math.min(1000,Number(i.aimX)||0)),aimY:Math.max(0,Math.min(600,Number(i.aimY)||0))};inputTimes[sender]=performance.now();return;}
 if(body.type==='ack'&&sender===0){pending.delete(body.request);if(!body.ok)notice('その操作は今はできません。遊び方と手番を確認してください。');return;}
 if(body.type==='action'&&side===0&&hostState&&typeof body.request==='string'){const key=from+body.request;if(accepted.has(key)){net.send(from,{type:'ack',request:body.request,ok:accepted.get(key)});return;}const now=Date.now();rates[sender]??=[];rates[sender]=rates[sender].filter(t=>now-t<1000);if(rates[sender].length>=18)return;rates[sender].push(now);const ok=action(hostState,sender,body.action);accepted.set(key,ok);if(accepted.size>1500)accepted.delete(accepted.keys().next().value);net.send(from,{type:'ack',request:body.request,ok});if(ok){state=view(hostState,0);updateUI();sendStates(true);}return;}
 }
function submit(a){if(!net?.room||preview||!state||state.phase!=='playing')return;notice('');if(side===0){const ok=action(hostState,0,a);if(ok){beep();state=view(hostState,0);updateUI();sendStates(true);}else notice('その操作は今はできません。遊び方と手番を確認してください。');}else{const request=crypto.randomUUID();pending.set(request,{action:a,time:0});retryActions();}}
function retryActions(){if(!net||side===0)return;const now=performance.now(),host=net.room.members[0]?.id;for(const [request,a] of pending){if(now-a.time<600)continue;if(pending.size>30){pending.delete(request);continue;}a.time=now;net.send(host,{type:'action',request,action:a.action});}}
function sendStates(force=false){if(!net?.ready||side!==0||!hostState)return;const now=performance.now();for(const member of net.room.members.slice(1)){const other=net.room.members.indexOf(member),interval=net.direct(member.id)?65:400;if(!force&&now-(sendTimes.get(member.id)||0)<interval)continue;sendTimes.set(member.id,now);net.send(member.id,{type:'state',state:view(hostState,other)});}}
function cardName(c,n){if(typeof c==='number')return 'NUMBER';if(Array.isArray(c))return c.join(' · ');if(n===47)return ['','移動','防御','攻撃','回復'][c.rank];if(c.type)return {coin:'コイン',attack:'攻撃',shield:'盾',heal:'回復'}[c.type]||c.type;return ['♠','♥','♣','♦'][c.suit||0];}
function cardHTML(c,i,n,market=false){const rank=typeof c==='number'?c:Array.isArray(c)?c.join(' | '):[43,45,46,47,50].includes(n)?c.rank:({11:'J',12:'Q',13:'K',14:'A',15:'2'})[c.rank]||c.rank;return `<button class="playing-card ${selectedCard===i&&!market?'chosen':''}" data-${market?'market':'card'}="${i}" style="color:${Array.isArray(c)?'#d8f4ff':COLORS[(c.suit||0)%8]}"><span>${esc(cardName(c,n))}</span><b>${esc(rank)}</b>${c.cost?'<span>'+c.cost+'コイン</span>':''}</button>`;}
let lastUIAt=0;function updateUI(force=false){if(!state||preview)return;if(!force&&performance.now()-lastUIAt<180)return;lastUIAt=performance.now();const s=state;const signature=JSON.stringify([s.version,s.phase,s.turn,s.round,s.players.map(p=>[Math.floor(p.score),p.hp]),s.hand,s.data.market,s.data.committed,s.data.messages,s.private,s.message]);if(!force&&signature===lastUI)return;lastUI=signature;
 $('rules').textContent=s.goal;$('scoreboard').innerHTML=s.players.map(p=>`<div class="player-score ${s.turn===p.side?'active':''}" style="--player:${COLORS[p.side]}"><b>${esc(p.name)}</b><small>${p.side===side?'YOU':''}</small><strong>${Math.round(p.score)}</strong></div>`).join('');$('gameMessage').textContent=s.message||'';
 $('hand').innerHTML=(s.hand||[]).map((c,i)=>cardHTML(c,i,s.n)).join('');$('market').innerHTML=(s.family==='cards'?s.data.market||[]:[]).map((c,i)=>cardHTML(c,i,s.n,true)).join('');
 const privateLines=[];if(s.private?.word)privateLines.push('あなたのお題：'+s.private.word);if(s.private?.role)privateLines.push('役割：'+s.private.role);if(s.private?.forbidden)privateLines.push('禁止：'+s.private.forbidden.join(' / '));if(s.private?.hint!==undefined)privateLines.push('秘密のヒント：'+JSON.stringify(s.private.hint));if(s.private?.value!==undefined)privateLines.push('本当の価値：'+s.private.value);if(s.private?.numbers)privateLines.push('担当の数字：'+s.private.numbers.join(' / '));if(s.private?.clues&&s.n===98)privateLines.push(...s.private.clues.map(c=>c.position+'番目は駅'+c.station));if(s.private?.clues&&s.n===78)privateLines.push('未来の手掛かり：'+s.private.clues.join(' → '));if(s.private?.fleet)privateLines.push('自分の船：'+s.private.fleet.map(i=>(Math.floor(i/6)+1)+'行'+(i%6+1)+'列').join('、'));if(s.private?.chest!==undefined)privateLines.push('本物：宝箱'+(s.private.chest+1));$('privateInfo').hidden=!privateLines.length;$('privateInfo').textContent=privateLines.join('\n');
 if(!document.activeElement?.closest('#actionPanel')||force)renderActions(s);
 if(s.data.messages){$('chatLog').hidden=!s.data.messages.length;$('chatLog').innerHTML=s.data.messages.map(m=>`<p><b>${esc(s.players[m.side]?.name)}：</b> ${esc(m.text)}</p>`).join('');$('chatLog').scrollTop=$('chatLog').scrollHeight;}
 }
function renderActions(s){const n=s.n,buttons=[],b=(label,type,extra={})=>buttons.push(`<button data-action="${type}" data-extra='${esc(JSON.stringify(extra))}'>${esc(label)}</button>`);let fields='';
 if(isRealtime(s)){b('A / 操作','primary');b('B / 能力','secondary');if(n===84)s.choices.forEach((c,i)=>b(c,'choice',{choice:i}));}
 else {
 const choices={32:['石を落とす'],35:['横線路','縦線路','交差線路'],36:['手札を選択'],38:['移動','壁'],40:['採集','建設','交換'],57:['合法 / 通す','密輸 / 検査'],66:['燃料','酸素','修理'],67:['床','支柱'],73:['開く','旗'],76:['移動','出口'],77:['足す','引く','掛ける'],79:['回転','所有'],80:['足す','引く','掛ける'],82:['速射','長射程','減速'],83:['速射','長射程','減速'],90:['採集','射手','戦士'],95:['砂壁','水路']};
 if(choices[n])fields+=`<select id="choiceInput" aria-label="操作の種類">${choices[n].map((label,i)=>`<option value="${i}" ${choice===i?'selected':''}>${label}</option>`).join('')}</select>`;
 if([31,39,41,48,50].includes(n))b('パス / 場を更新','pass');
 if(n===32)b('重力を反転','secondary');
 if([9,34,46,47,51,53,56,60,67,70,97,98].includes(n))b('決定 / 手番終了','confirm');
 if(n===47)b('予約を戻す','undo');if(n===98)b('一駅戻す','secondary');
 if([37,49,60].includes(n))b(n===37?'ソナー':'調査 / 入替','secondary');
 if(n===71)b('盾をためる','secondary');if(n===64)b('担当部品を投入','cell',{i:0});
 if(n===72){b('左','cell',{choice:0});b('右','cell',{choice:1});b('回転','cell',{choice:2});b('落とす','secondary');}
 if(n===58)for(const [i,label] of ['↑','→','↓','←'].entries())b(label,side===0?'hint':'cell',{choice:i});
 if(n===43)b('ヒントを伝える','hint');if([83,90].includes(n))b(n===90?'ユニット生産':'敵を送り込む','send');
 if(n===54){b('修理','primary');b('妨害 / 捕獲','secondary');b('会議を開く','meeting');}
 if(n===91){b('捕獲','primary');b('救助','secondary');}
 if(n===80)for(let i=0;i<3;i++)b('数字 '+(side+1+i),'cell',{i});
 if([42,50,56,57,59].includes(n)){fields+='<input id="valueInput" type="number" min="0" max="99" inputmode="numeric" placeholder="入札額 / 予想 / 相手の席" aria-label="数字を入力">';b(n===59?'回答する':'金額 / 選択を決定','bid');}
 if(n===56)b('鑑定（3コイン）','secondary');
 if(n===59)fields+='<select id="choiceInput" aria-label="回答"><option value="0">前の選択肢</option><option value="1">後の選択肢</option></select>';
 if(s.data.stage==='vote')for(const p of s.players)if(p.hp>0)b(p.name+'に投票','vote',{value:p.side});
 if(s.family==='social'||n===58){fields+='<input id="textInput" maxlength="120" placeholder="メッセージ / 回答" aria-label="メッセージまたは回答">';b('送信','chat');if([51,52].includes(n))b('回答する',n===51?'confirm':'answer');}
 if(n===41)fields+='<select id="groupInput" aria-label="出す枚数"><option value="1">1枚</option><option value="2">2枚</option><option value="3">3枚</option><option value="4">4枚</option></select>';
 }
 const html=fields+buttons.join('');if($('actionPanel').dataset.kind!==s.id+':'+s.data.stage+':'+s.phase||$('actionPanel').innerHTML!==html){const text=$('textInput')?.value,value=$('valueInput')?.value;$('actionPanel').innerHTML=html;if(text&&$('textInput'))$('textInput').value=text;if(value&&$('valueInput'))$('valueInput').value=value;$('actionPanel').dataset.kind=s.id+':'+s.data.stage+':'+s.phase;}
 }
$('actionPanel').addEventListener('change',e=>{if(e.target.id==='choiceInput')choice=Number(e.target.value);});
$('actionPanel').addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;let extra={};try{extra=JSON.parse(b.dataset.extra);}catch{}const a={type:b.dataset.action,i:selectedCell,choice:Number($('choiceInput')?.value??choice),value:$('valueInput')?.value??null,text:$('textInput')?.value||'',x:input.aimX,y:input.aimY,...extra};if(state?.n===49&&a.type==='secondary'){a.i=selectedCell;a.j=(selectedCell+1)%24;}submit(a);if(['chat','answer'].includes(a.type)&&$('textInput'))$('textInput').value='';});
$('hand').addEventListener('click',e=>{const button=e.target.closest('[data-card]');if(!button)return;selectedCard=Number(button.dataset.card);if([36,39].includes(state.n)){updateUI(true);return;}submit({type:'card',i:selectedCard,choice:state.n===41?Number($('groupInput')?.value||1):-1});});
$('market').addEventListener('click',e=>{const b=e.target.closest('[data-market]');if(b)submit({type:state.n===46?'buy':'card',i:Number(b.dataset.market)});});
function point(e){const r=stage.getBoundingClientRect();const camera=renderer.camera||{zoom:1,x:0,y:0};return {x:((e.clientX-r.left)*1000/r.width-camera.x)/camera.zoom,y:((e.clientY-r.top)*renderer.logicalHeight/r.height-camera.y)/camera.zoom};}
let drawing=false,lastPoint=null,lastDraw=0;
stage.addEventListener('pointerdown',e=>{stage.setPointerCapture(e.pointerId);const p=point(e);input.aimX=p.x;input.aimY=p.y;renderer.pointer=p;if(!state||preview)return;if([51,53].includes(state.n)&&state.turn===side){drawing=true;lastPoint=p;return;}const i=renderer.cellAt(p.x,p.y);if(i>=0){selectedCell=i;renderer.selected=i;submit({type:'cell',i,choice:[36,39].includes(state.n)?Math.max(0,selectedCard):choice});}else if(isRealtime(state))submit({type:'primary',x:p.x,y:p.y});});
stage.addEventListener('pointermove',e=>{const p=point(e);input.aimX=p.x;input.aimY=p.y;renderer.pointer=p;if(drawing&&lastPoint&&performance.now()-lastDraw>110){lastDraw=performance.now();if(p.x>83&&p.x<917&&p.y>140&&p.y<517&&lastPoint.x>83&&lastPoint.x<917&&lastPoint.y>140&&lastPoint.y<517)submit({type:'draw',x:p.x,y:p.y,i:Math.round(lastPoint.x),j:Math.round(lastPoint.y)});lastPoint=p;}});
stage.addEventListener('pointerup',()=>{drawing=false;lastPoint=null;});stage.addEventListener('pointercancel',()=>{drawing=false;lastPoint=null;});
function keyboard(){input.x=(keys.has('ArrowRight')||keys.has('d')?1:0)-(keys.has('ArrowLeft')||keys.has('a')?1:0);input.y=(keys.has('ArrowDown')||keys.has('s')?1:0)-(keys.has('ArrowUp')||keys.has('w')?1:0);input.primary=keys.has(' ')||keys.has('z');}
window.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,select')||!state||preview)return;if(['ArrowUp','ArrowRight','ArrowDown','ArrowLeft',' ','z','x'].includes(e.key))e.preventDefault();keys.add(e.key);keyboard();if(e.repeat)return;if(e.key==='x')submit({type:'secondary',x:input.aimX,y:input.aimY});if(!isRealtime(state)&&state.n===72){const opts={ArrowLeft:0,ArrowRight:1,ArrowUp:2,ArrowDown:3,' ':3};if(opts[e.key]!==undefined)submit({type:'cell',choice:opts[e.key]});}if(!isRealtime(state)&&state.n===58){const dirs=['ArrowUp','ArrowRight','ArrowDown','ArrowLeft'];if(dirs.includes(e.key))submit({type:side===0?'hint':'cell',choice:dirs.indexOf(e.key)});}});
window.addEventListener('keyup',e=>{keys.delete(e.key);keyboard();});window.addEventListener('blur',()=>{keys.clear();keyboard();input.primary=false;});
const stick=$('stick');let stickPointer=null;stick.onpointerdown=e=>{stickPointer=e.pointerId;stick.setPointerCapture(e.pointerId);stickMove(e);};function stickMove(e){if(e.pointerId!==stickPointer)return;const r=stick.getBoundingClientRect(),dx=(e.clientX-r.left-r.width/2)/(r.width/2),dy=(e.clientY-r.top-r.height/2)/(r.height/2),len=Math.max(1,Math.hypot(dx,dy));input.x=dx/len;input.y=dy/len;stick.firstElementChild.style.transform=`translate(${input.x*r.width*.25}px,${input.y*r.height*.25}px)`;if(state?.players[side]&&isRealtime(state)){input.aimX=state.players[side].x+input.x*220;input.aimY=state.players[side].y+input.y*220;}}stick.onpointermove=stickMove;stick.onpointerup=stick.onpointercancel=()=>{stickPointer=null;input.x=input.y=0;stick.firstElementChild.style.transform='';};
$('touchA').onpointerdown=e=>{e.preventDefault();e.target.setPointerCapture(e.pointerId);input.primary=true;submit({type:'primary',x:input.aimX,y:input.aimY});};$('touchA').onpointerup=$('touchA').onpointercancel=()=>input.primary=false;$('touchB').onpointerdown=e=>{e.preventDefault();submit({type:'secondary',x:input.aimX,y:input.aimY});};
$('sound').onclick=()=>{sound=!sound;$('sound').textContent='音 '+(sound?'ON':'OFF');$('sound').setAttribute('aria-pressed',String(sound));beep();};$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await stage.parentElement.requestFullscreen();}catch{notice('この端末ではブラウザーの全画面表示を使ってください。');}};
document.addEventListener('visibilitychange',()=>{focused=!document.hidden;keys.clear();keyboard();if(document.hidden&&hostState)net?.checkpoint(hostState);});
let lastGraphicsUi=0;
function frame(now){renderer.budget.sample(now-lastFrame,renderer.renderMs||0,now,focused&&!!state&&!$('play').hidden);const dt=Math.min(.1,(now-lastFrame)/1000);lastFrame=now;if(hostState&&!preview&&net?.room?.status==='playing'){const wasOver=hostState.phase==='over';inputs[0]={...input};for(const p of hostState.players)if(p.side&&now-(inputTimes[p.side]||0)>1000)inputs[p.side]={};elapsed+=dt;let count=0;while(elapsed>=1/30&&count++<4){tick(hostState,inputs,1/30);elapsed-=1/30;}state=view(hostState,0);sendStates(!wasOver&&hostState.phase==='over');if(now-lastCheckpoint>5000||hostState.phase==='over'&&net.room.status!=='finished'){lastCheckpoint=now;net.checkpoint(hostState);}updateUI();}
 if(net?.ready&&!preview&&side>0&&state?.phase==='playing'){const host=net.room.members[0]?.id,interval=net.direct(host)?50:125;if(now-(sendTimes.get('input')||0)>interval){sendTimes.set('input',now);net.send(host,{type:'input',input});}retryActions();if(lastInput&&now-lastInput>6500){$('stageOverlay').hidden=false;$('stageOverlay').innerHTML='<div><h2>ホストとの接続を待っています。</h2><p>同じルームで再接続すると続きから遊べます。</p></div>';}}
 if(state&&!$('play').hidden&&renderer.budget.shouldDraw(now,focused,preview||!isRealtime(state))){stage.parentElement.classList.toggle('square-board',!!state.board&&stage.clientWidth<600);renderer.draw(state,side,now);if(now-lastGraphicsUi>200){lastGraphicsUi=now;const remaining=Math.max(0,state.duration-state.t);$('clock').textContent=String(Math.floor(remaining/60)).padStart(2,'0')+':'+String(Math.floor(remaining%60)).padStart(2,'0');$('progress').textContent=state.mode==='coop'?Math.floor(state.progress)+' / '+state.target:state.n===100?state.data.ruleLabel:'ROUND '+state.round;}}
 requestAnimationFrame(frame);}
try{renderer.setQuality(localStorage.getItem('arcade.graphics')||'auto');}catch{}$('quality').value=renderer.quality;$('quality').onchange=()=>{renderer.setQuality($('quality').value);try{localStorage.setItem('arcade.graphics',renderer.quality);}catch{}};
listGames();try{await renderer.load();}catch(e){notice(e.message);}const query=new URLSearchParams(location.search);if(query.get('game')&&GAME_BY_ID[query.get('game')])selectGame(query.get('game'));if(query.get('room')){if(!spec)selectGame('g011');$('roomCode').value=query.get('room').toUpperCase();notice('名前を入力して「ルームに参加」を押してください。');}try{const saved=JSON.parse(sessionStorage.getItem('aitech-arcade-session-v1')||'null');$('resume').hidden=!saved?.room;}catch{}requestAnimationFrame(frame);

Object.defineProperty(window,'arcadeGraphics',{get:()=>({...renderer.budget.stats,renderMs:renderer.renderMs||0,worlds:renderer.worldImages.size,cachePixels:renderer.cache.pixels,width:stage.width,height:stage.height})});
