import {identity,sharedKey,seal,open} from './crypto.mjs';
const STORE='aitech-arcade-session-v1';
export class OnlineRoom extends EventTarget {
 constructor(config=globalThis.SUPABASE_CONFIG){super();this.config=config;this.peers=new Map();this.keys=new Map();this.seen=new Map();this.lastSent=new Map();this.seq=Date.now()*1000;this.closed=false;this.ready=false;this.sendQueues=new Map();this.receiveQueues=new Map();}
 emit(name,detail){this.dispatchEvent(new CustomEvent(name,{detail}));}
 async init(){let saved;try{saved=JSON.parse(sessionStorage.getItem(STORE)||'null');}catch{}this.identity=await identity(saved?.identity);this.saved=saved;this.save();return this;}
 save(){const {key,...id}=this.identity;try{sessionStorage.setItem(STORE,JSON.stringify({identity:id,room:this.room?.room||this.saved?.room||null}));}catch{}}
 async api(op,extra={}){const r=await fetch(this.config.url+'/functions/v1/arcade-rooms',{method:'POST',headers:{'Content-Type':'application/json',apikey:this.config.publishableKey},body:JSON.stringify({protocol:1,token:this.identity.token,room:this.room?.room,op,...extra}),signal:AbortSignal.timeout(12000)});const d=await r.json();if(!r.ok)throw new Error(d.error||'通信できませんでした。');return d;}
 async create(game,name){const room=await this.api('create',{game,name,publicKey:this.identity.publicKey});await this.connect(room);return room;}
 async join(code,name){const room=await this.api('join',{room:code.trim().toUpperCase(),name,publicKey:this.identity.publicKey});await this.connect(room);return room;}
 async resume(){if(!this.saved?.room)return null;const room=await this.api('resume',{room:this.saved.room});await this.connect(room);return room;}
 async connect(room){this.room=room;this.save();await this.updateRoom(room);const createClient=this.config.createClient||(await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.57.0/+esm')).createClient;this.client=createClient(this.config.url,this.config.publishableKey,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false},realtime:{params:{eventsPerSecond:90}}});
 this.channel=this.client.channel('arcade:'+room.topic,{config:{broadcast:{self:false,ack:false}}}).on('broadcast',{event:'packet'},({payload})=>this.receive(payload));
 await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(new Error('リアルタイム通信に接続できません。')),15000);this.channel.subscribe(status=>{if(status==='SUBSCRIBED'){clearTimeout(timeout);this.ready=true;this.emit('connection',{online:true});resolve();}else if(['CHANNEL_ERROR','TIMED_OUT','CLOSED'].includes(status)){this.ready=false;this.emit('connection',{online:false});}});});
 this.pollTimer=setInterval(()=>this.poll(),4000);this.heartbeat=setInterval(()=>{if(this.room?.side===0){for(const m of this.room.members.slice(1))this.send(m.id,{type:'ping',time:Date.now()});}else this.send(this.room.members[0].id,{type:'ping',time:Date.now()});},2500);
 await this.ensurePeers();this.emit('room',this.room);
 }
 async updateRoom(room){this.room=room;this.me=room.members[room.side];if(!this.me)return;for(const m of room.members)if(m.id!==this.me.id&&!this.keys.has(m.id))this.keys.set(m.id,await sharedKey(this.identity.key,m.publicKey));for(const [id,p] of this.peers)if(!room.members.some(m=>m.id===id)){p.pc.close();this.peers.delete(id);this.keys.delete(id);}this.emit('room',room);}
 async poll(){if(this.closed||this.polling)return;this.polling=true;try{await this.updateRoom(await this.api('get'));await this.ensurePeers();}catch(e){this.emit('error',e.message);}finally{this.polling=false;}}
 async setReady(ready){await this.updateRoom(await this.api('ready',{ready}));}
 async start(){await this.updateRoom(await this.api('start'));}
 async rematch(){await this.updateRoom(await this.api('rematch'));}
 async checkpoint(state){if(this.room?.side!==0||this.saving)return;this.saving=true;try{await this.updateRoom(await this.api('checkpoint',{state}));}catch(e){this.emit('error',e.message);}finally{this.saving=false;}}
 async ensurePeers(){if(!this.ready||!globalThis.RTCPeerConnection||this.room.side!==0)return;for(const m of this.room.members.slice(1))if(!this.peers.has(m.id)){const p=this.makePeer(m.id);this.attachChannel(m.id,p.pc.createDataChannel('game',{ordered:true}));try{await p.pc.setLocalDescription(await p.pc.createOffer());await this.send(m.id,{type:'signal',description:p.pc.localDescription},true);}catch{p.pc.close();this.peers.delete(m.id);}}}
 makePeer(id){const pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.cloudflare.com:3478'},{urls:'stun:stun.l.google.com:19302'}]});const p={pc,channel:null,candidates:[]};this.peers.set(id,p);pc.onicecandidate=e=>{if(e.candidate)this.send(id,{type:'signal',candidate:e.candidate.toJSON()},true);};pc.ondatachannel=e=>this.attachChannel(id,e.channel);pc.onconnectionstatechange=()=>{this.emit('transport',{id,direct:pc.connectionState==='connected'});if(pc.connectionState==='failed'){pc.close();this.peers.delete(id);}};return p;}
 attachChannel(id,channel){const p=this.peers.get(id);p.channel=channel;channel.onopen=()=>{this.emit('transport',{id,direct:true});this.send(id,{type:'hello'});};channel.onmessage=e=>{try{this.receive(JSON.parse(e.data));}catch{}};channel.onclose=()=>this.emit('transport',{id,direct:false});}
 async signal(id,msg){let p=this.peers.get(id);if(!p)p=this.makePeer(id);try{if(msg.description){await p.pc.setRemoteDescription(msg.description);for(const c of p.candidates)await p.pc.addIceCandidate(c);p.candidates=[];if(msg.description.type==='offer'){await p.pc.setLocalDescription(await p.pc.createAnswer());await this.send(id,{type:'signal',description:p.pc.localDescription},true);}}else if(msg.candidate){if(p.pc.remoteDescription)await p.pc.addIceCandidate(msg.candidate);else p.candidates.push(msg.candidate);}}catch{}}
 direct(id){return this.peers.get(id)?.channel?.readyState==='open';}
 send(id,body,relay=false){const task=(this.sendQueues.get(id)||Promise.resolve()).catch(()=>{}).then(()=>this.sendPacket(id,body,relay));this.sendQueues.set(id,task);return task;}
 async sendPacket(id,body,relay=false){if(this.closed||!this.ready||!this.keys.has(id)||!this.me)return false;const key=this.keys.get(id),seq=++this.seq;const context=this.room.topic+':'+this.me.id+':'+id;try{const packet={from:this.me.id,to:id,seq,...await seal(key,{...body,seq},context)};const channel=this.peers.get(id)?.channel;if(!relay&&channel?.readyState==='open'&&channel.bufferedAmount<262144&&JSON.stringify(packet).length<60000){channel.send(JSON.stringify(packet));}else await this.channel.send({type:'broadcast',event:'packet',payload:packet});return true;}catch{return false;}}
 receive(packet){if(!packet?.from||packet.to!==this.me?.id||!this.keys.has(packet.from))return;const task=(this.receiveQueues.get(packet.from)||Promise.resolve()).catch(()=>{}).then(()=>this.receivePacket(packet));this.receiveQueues.set(packet.from,task);return task;}
 async receivePacket(packet){if(!packet||packet.to!==this.me?.id||!this.keys.has(packet.from)||!Number.isSafeInteger(packet.seq)||packet.seq<=(this.seen.get(packet.from)||0))return;try{const body=await open(this.keys.get(packet.from),packet,this.room.topic+':'+packet.from+':'+packet.to);if(body.seq!==packet.seq||packet.seq<=(this.seen.get(packet.from)||0))return;this.seen.set(packet.from,packet.seq);if(body.type==='signal'){await this.signal(packet.from,body);return;}if(body.type==='ping'){await this.send(packet.from,{type:'pong',time:body.time});return;}if(body.type==='pong'){this.emit('latency',{id:packet.from,ms:Date.now()-body.time});return;}const side=this.room.members.findIndex(m=>m.id===packet.from);this.emit('message',{from:packet.from,side,body});}catch{}}
 async leave(){try{await this.api('leave');}catch{}this.close();try{sessionStorage.removeItem(STORE);}catch{}}
 close(){this.closed=true;clearInterval(this.pollTimer);clearInterval(this.heartbeat);for(const p of this.peers.values())p.pc.close();if(this.client&&this.channel)this.client.removeChannel(this.channel);this.ready=false;}
}
