import {SCENARIOS,DIFFICULTIES,GOALS,TECHNIQUES,techURL} from './data.mjs';
import {createMission,scenario,actions,supports,story,clue,vote,execute,advance,canExecute,validState,NODES} from './engine.mjs';
import {StoryRoom,roomCode} from './network.mjs';
const root=document.getElementById('app'),STORE='aitech-ghostline-progress-v1';
let screen='lobby',difficulty=0,search='',selected=1,mode='local',role=0,state=null,room=null,busy=false,codeInput='',noticeTimer=0,processed=new Set(),sound=false,audioContext,onlineText='';
let progress={};try{progress=JSON.parse(localStorage.getItem(STORE)||'{}');if(!progress||typeof progress!=='object'||Array.isArray(progress))progress={};}catch{}
const escape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(text,action,cls='',disabled=false,extra='')=>`<button type="button" data-action="${action}" class="${cls}" ${disabled?'disabled':''} ${extra}>${text}</button>`;
const current=()=>SCENARIOS[selected-1];
const online=()=>mode==='online'&&room?.active;
const myRole=()=>online()?room.side:role;
const host=()=>!online()||room.side===0;
function notice(text){const box=document.getElementById('notice');box.textContent=text;box.classList.add('show');clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>box.classList.remove('show'),4200);}
function beep(end=false){if(!sound)return;try{audioContext??=new(window.AudioContext||window.webkitAudioContext)();audioContext.resume();const o=audioContext.createOscillator(),g=audioContext.createGain();o.connect(g);g.connect(audioContext.destination);o.type='sine';o.frequency.setValueAtTime(end?660:440,audioContext.currentTime);g.gain.setValueAtTime(.035,audioContext.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+.14);o.start();o.stop(audioContext.currentTime+.15);}catch{}}
function top(){return `<header class="topbar"><a class="brand" href="../games-2d.html"><span class="brand-icon">G</span>GHOSTLINE <small>CO-OP STORY</small></a><div class="bar-actions"><a href="../games-2d.html" class="back">2Dゲーム集</a>${online()?`<span class="room-badge">${escape(room.code)} · ${room.online?'2人接続':'相手を待機'}</span>`:''}${button(sound?'音 ON':'音 OFF','sound','small secondary',false,`aria-pressed="${sound}"`)}${button('全画面','fullscreen','small secondary')}${screen!=='lobby'?button('任務一覧','home','small secondary'):button('遊び方','help','small secondary')}</div></header>`;}
function footer(){return `<footer class="game-footer"><span>架空の演習ネットワーク / ATT&CK参考のオリジナルゲーム</span><span class="rotate-note">${innerWidth<600?'スマホを横にして「全画面」で大きく遊べます':'2人の判断をつなぎ、目標へ。'}</span></footer>`;}
function missionCards(){const list=SCENARIOS.filter(m=>m.difficulty===difficulty&&(!search||`${m.title} ${m.org} ${m.asset} ${m.id}`.includes(search)));return list.length?list.map(m=>`<button class="mission" data-action="mission" data-id="${m.id}"><div class="mission-head"><span class="mono">OP. ${String(m.id).padStart(3,'0')}</span><span class="${progress[m.id]?'clear-tag':''}">${progress[m.id]?`CLEAR ${escape(progress[m.id].grade)}`:`CHAPTER ${String(m.chapter).padStart(2,'0')}`}</span></div><h3>${m.title}</h3><p>${m.brief}</p><div class="mission-foot"><span class="goal">${GOALS[m.goal].name}</span><span>${m.org} ↗</span></div></button>`).join(''):'<p class="empty">この難易度には一致する任務がありません。</p>';}
function lobby(){return `<main class="lobby"><aside class="sidebar"><div><p class="eyebrow">MISSION SELECT</p><h1>二人の判断が、<br>突破口になる。</h1><p class="side-copy">侵入担当と解析担当。違う手掛かりを共有し、100の任務を攻略しよう。</p><div class="counter"><strong>${Object.keys(progress).filter(k=>SCENARIOS[Number(k)-1]).length.toString().padStart(2,'0')}</strong><span>/ 100 CLEARED<br>この端末の記録</span></div></div><nav class="difficulty-list" aria-label="難易度">${DIFFICULTIES.map((d,i)=>button(`${d.name}<small>${d.code} / 20</small>`,'difficulty',`difficulty ${difficulty===i?'active':''}`,false,`data-id="${i}" aria-pressed="${difficulty===i}"`)).join('')}</nav><div class="side-footer">${button('ルームコードで参加','join-home','small secondary')}<br>1台で2人 / 別端末でオンライン協力<br>すべての任務を最初から選べます。</div></aside><section class="catalog"><div class="catalog-head"><h2>${DIFFICULTIES[difficulty].name} <span class="muted">/ 20 SCENARIOS</span></h2><input id="mission-search" type="search" placeholder="任務名・舞台を検索" aria-label="この難易度の任務を検索" value="${escape(search)}"></div><div class="mission-list" id="mission-list">${missionCards()}</div></section></main>`;}
function brief(){const m=current(),d=DIFFICULTIES[m.difficulty];return `<main class="brief"><section><p class="eyebrow">OP. ${String(m.id).padStart(3,'0')} / ${d.code} / CHAPTER ${m.chapter}</p><h1>${m.title}</h1><p class="brief-story">${m.brief}</p><div class="facts"><div class="fact"><span>舞台</span><strong>${m.org}</strong></div><div class="fact"><span>今回の目標</span><strong>${GOALS[m.goal].name}</strong></div><div class="fact"><span>対象データ・権限</span><strong>${m.asset}</strong></div><div class="fact"><span>演習の制約</span><strong>${d.turns}手 / 支援 ${d.assist}回</strong></div></div><div class="objective" style="margin-top:24px"><p class="eyebrow">CLEAR CONDITION</p><p>${GOALS[m.goal].description} 完了時に警戒100未満・保全度60以上が必要。</p></div><p class="muted" style="font-size:.875rem;margin-top:18px">${m.environment} ${d.desc}。</p></section><aside class="prep"><h2>チームを編成</h2><div class="mode-picks">${button('同じ端末で2人','mode-local',mode==='local'?'active':'',!!room?.active)}${button('別端末で協力','mode-online',mode==='online'?'active':'',!!room?.active)}</div><div class="roles"><div><div class="role-title">P1 / 侵入担当</div><p>入口と識別子を確認。経路を選び、二人の判断を実行する。</p></div><div><div class="role-title">P2 / 解析担当</div><p>原本と経路の手掛かりを共有。照合・監視解析・保全で支援する。</p></div></div>${mode==='local'?`<p class="online-description">毎ターン、P1の行動とP2の支援を選びます。「二人で実行」で物語が進行。1人で両役を操作して練習もできます。</p>${button('任務を開始','start','primary start')}`:onlinePrep()}</aside></main>`;}
function onlinePrep(){if(!room?.active)return `<p class="online-description">P1が部屋を作り、P2に6文字のコードを伝えてください。</p>${button(busy?'接続中…':'部屋を作成（P1）','create-room','primary start',busy)}<div class="room-inputs"><input id="room-input" maxlength="6" autocomplete="off" autocapitalize="characters" placeholder="6文字のコード" aria-label="ルームコード" value="${escape(codeInput)}">${button('参加','join-room','',busy)}</div><p class="online-description">${escape(onlineText)}</p>`;
 return `<p class="online-description">部屋のコード / あなたは ${room.side===0?'P1 侵入担当':'P2 解析担当'}</p><p class="room-code" id="room-code">${escape(room.code)}</p><p class="online-description">${room.online?(room.side===0?(room.remoteReady?'相棒の準備OK。任務を開始できます。':'相棒の準備を待っています。'):(room.ready?'準備OK。ホストの開始を待っています。':'手掛かりを共有する準備ができたら押してください。')):'相棒の接続を待っています。'}</p><div class="room-inputs">${button('招待リンクをコピー','invite','small')}${button('部屋を退出','leave-room','small')}</div>${room.side===0?button('二人で任務を開始','start','primary start',!room.online||!room.remoteReady):button(room.ready?'準備OK ✓':'準備OKにする','ready','primary start',!room.online||room.ready)}<p class="online-description">${escape(onlineText)}</p>`;}
const coords={recon:[70,75],access:[210,75],sideentry:[330,75],discovery:[100,165],deadend:[40,260],pivot:[230,165],credential:[335,210],privilege:[295,300],vault:[155,300],inspect:[60,345],encrypt:[245,400],exfil:[75,420]};
function mapMarkup(){const lines=[['recon','access'],['access','sideentry'],['access','discovery'],['sideentry','discovery'],['discovery','deadend'],['discovery','pivot'],['pivot','credential'],['credential','privilege'],['pivot','vault'],['privilege','vault'],['vault','inspect'],['vault','encrypt'],['vault','exfil']];return `<div class="network-map"><div class="map-label mono">NETWORK / ${current().fingerprint}</div><svg viewBox="0 0 400 475" role="img" aria-label="現在地 ${NODES[state.node]}。通過した区画を明るく表示。">${lines.map(([a,b])=>`<line class="edge ${state.visited.includes(a)&&state.visited.includes(b)?'visited':''}" x1="${coords[a][0]}" y1="${coords[a][1]}" x2="${coords[b][0]}" y2="${coords[b][1]}"></line>`).join('')}${Object.entries(coords).map(([id,[x,y]])=>`<g class="${state.visited.includes(id)?'visited':''} ${state.node===id?'current':''}"><circle cx="${x}" cy="${y}" r="${state.node===id?11:7}"></circle><text x="${x}" y="${y+25}" text-anchor="middle">${NODES[id]}</text></g>`).join('')}</svg><div class="map-bottom mono"><span>${state.visited.length} NODES VISITED</span><span>INTEL ${state.intel}</span></div></div>`;}
function hud(){return `<div class="hud"><div class="hud-title"><p class="eyebrow">OP. ${String(selected).padStart(3,'0')} / ${DIFFICULTIES[current().difficulty].code}</p><h1>${current().title}</h1></div><div class="meters"><div class="meter ${state.trace>69?'danger':''}"><label>警戒 <strong>${state.trace}%</strong></label><div class="track"><i style="width:${state.trace}%"></i></div></div><div class="meter integrity"><label>保全度 <strong>${state.integrity}%</strong></label><div class="track"><i style="width:${state.integrity}%"></i></div></div><div class="moves">残り手数<strong>${Math.max(0,state.turns)}</strong></div></div></div>`;}
function roleSwitch(){return `<div class="player-switch">${[0,1].map(i=>button(`P${i+1} ${i===0?'侵入担当':'解析担当'}${state.votes[i]?' ✓':''}`,'role',`${myRole()===i?'active':''} ${i===1?'analyst':''}`,online()&&room.side!==i,`data-id="${i}" aria-pressed="${myRole()===i}"`)).join('')}</div>`;}
function playPanel(){const [title,text]=story(state),r=myRole(),choices=r===0?actions(state):supports(state);return `<div class="story-content"><div class="story-step"><span class="eyebrow">PHASE ${String(state.log.length+1).padStart(2,'0')} / ${r===0?'OPERATOR':'ANALYST'}</span><span class="technique">${NODES[state.node]}</span></div><h2>${title}</h2><p>${text}</p>${roleSwitch()}</div><div class="choice-area" aria-label="${r===0?'侵入担当の行動':'解析担当の支援'}">${choices.map((a,i)=>`<button class="choice ${r===1?'analyst':''} ${state.votes[r]===a.id?'selected':''}" data-action="vote" data-id="${a.id}" ${a.disabled||online()&&!room.online?'disabled':''} aria-pressed="${state.votes[r]===a.id}"><span class="choice-index">${i+1}</span><span class="choice-copy"><strong>${a.label}</strong><small>${a.desc}${r===0?` ／ ${a.cost}手`:''}</small></span></button>`).join('')}</div><div class="decision-footer"><span class="decision-status">${online()&&!room.online?'通信が切れています。進行を一時停止。':`P1 ${state.votes[0]?'選択済':'選択待ち'} · P2 ${state.votes[1]?'支援済':'支援待ち'}`}<br>支援残り ${state.assist}回 / 保全度60以上でクリア</span>${online()&&!room.online&&room.side===1?button('再接続','reconnect','small'):button(host()?'二人で実行':'P1の実行を待つ','execute','primary',!host()||!canExecute(state)||online()&&!room.online)}</div>`;}
function techniqueInfo(id){if(!TECHNIQUES[id])return '';const t=TECHNIQUES[id];return `<div class="result-tech"><a href="${techURL(id)}" target="_blank" rel="noopener noreferrer">${id} · ${t[0]} ↗</a><br><span class="muted">${t[2]} / ${t[1]}</span><p>${t[3]}</p><strong>守る側の視点</strong><br>${t[4]}</div>`;}
function feedbackPanel(){const f=state.feedback,end=state.phase==='ended';return `<div class="result-card"><p class="eyebrow">${end?(state.ending.success?'MISSION COMPLETE':'MISSION INCOMPLETE'):'ACTION REPORT'}</p>${end?`<div class="end-grade">${state.ending.grade}</div>`:''}<h2>${end?(state.ending.success?'二人で目標を達成した':'攻略記録を持って、もう一度'):f.action}</h2><p>${f.text}</p><p class="muted">支援：${f.support} ／ 消費 ${f.cost}手 ／ 警戒 ${f.trace>0?'+':''}${f.trace} ／ 保全度 ${f.integrity>0?'+':''}${f.integrity}</p>${techniqueInfo(f.tech)}<div class="result-actions">${end?`${button('攻略記録','journal','secondary')}${button('再挑戦','retry','primary',!host()||online()&&!room.online)}`:button(host()?'次の局面へ':'P1の進行を待っています','advance','primary',!host()||online()&&!room.online)}</div>${end&&state.ending.success&&selected<100?button('次の任務へ','next-mission','secondary start',!host()):''}${online()&&!room.online&&room.side===1?button('相棒に再接続','reconnect','secondary start'):''}</div>`;}
function play(){return `<main class="play">${hud()}<div class="board"><aside class="map-side">${mapMarkup()}<div class="objective"><p class="eyebrow">OBJECTIVE / ${GOALS[current().goal].name}</p><p>${current().asset}</p></div><div class="intel-box"><p class="eyebrow">P${myRole()+1} / PRIVATE INTEL</p><p>${clue(state,myRole())}</p></div>${button(`攻略記録 <span>${state.log.length} ACTIONS ↗</span>`,'journal','journal-button')}</aside><section class="story-panel">${state.phase==='play'?playPanel():feedbackPanel()}</section></div></main>`;}
function render(){root.innerHTML=top()+(screen==='lobby'?lobby():screen==='brief'?brief():play())+footer();}
function broadcast(){if(room?.side!==0||!room.online)return;room.send(state&&screen==='play'?{type:'snapshot',state}:{type:'setup',mission:selected,remoteReady:room.remoteReady});}
function saveProgress(){if(state?.ending?.success){const old=progress[selected];if(!old||state.integrity-state.trace>old.score)progress[selected]={grade:state.ending.grade,score:state.integrity-state.trace};try{localStorage.setItem(STORE,JSON.stringify(progress));}catch{notice('この端末ではクリア記録を保存できませんでした。');}}}
function change(next){if(next===state)return;state=next;saveProgress();broadcast();render();beep(state.phase==='ended');}
function start(){if(online()&&(!host()||!room.online||!room.remoteReady))return;state=createMission(selected);screen='play';role=0;processed.clear();change({...state});}
function addRoomListeners(n){n.addEventListener('status',e=>{onlineText=e.detail?'接続しました。':'相手との接続が切れました。進行は保存されています。';if(e.detail)broadcast();render();});n.addEventListener('hello',()=>{if(n.side===0)broadcast();else n.send({type:'ready',ready:n.ready});});n.addEventListener('error',e=>{onlineText=e.detail;notice(e.detail);render();});n.addEventListener('message',e=>receive(e.detail));}
function receive(m){if(room.side===0){if(m.type==='ready'){room.remoteReady=m.ready===true;broadcast();render();}else if(m.type==='command'&&typeof m.id==='string'&&m.id.length<100){room.acknowledge(m.id);if(processed.has(m.id)){broadcast();return;}processed.add(m.id);if(processed.size>200)processed.delete(processed.values().next().value);if(m.run===state?.run&&m.node===state.node&&state.phase==='play'&&m.kind==='support'&&m.step===state.log.length){change(vote(state,1,m.value));}else broadcast();}}else{
 if(m.type==='setup'&&Number.isInteger(m.mission)&&SCENARIOS[m.mission-1]){if(selected!==m.mission||screen==='play')room.ready=false;selected=m.mission;state=null;screen='brief';render();}
 if(m.type==='snapshot'&&validState(m.state)){if(state&&state.run===m.state.run&&m.state.revision<=state.revision)return;state=m.state;selected=state.mission;screen='play';saveProgress();render();}
 }
}
async function connect(side,code){if(busy)return;busy=true;onlineText='接続中…';render();try{if(room)await room.close();room=new StoryRoom();addRoomListeners(room);await room.connect(side,code);onlineText=side===0?'部屋を作成しました。相棒にコードを伝えてください。':'部屋に参加しました。';}catch(e){onlineText=e.message;await room?.close();notice(e.message);}finally{busy=false;render();}}
async function leave(){await room?.close();room=null;onlineText='';}
async function fullscreen(){try{if(document.fullscreenElement){await document.exitFullscreen();return;}if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();else if(document.documentElement.webkitRequestFullscreen)document.documentElement.webkitRequestFullscreen();else{notice('このブラウザでは全画面にできません。横向きで遊べます。');return;}try{await screenOrientationLock();}catch{}}catch{notice('画面を横にすると大きく遊べます。');}}
function screenOrientationLock(){return globalThis.screen?.orientation?.lock?.('landscape');}
function showDialog(html){document.querySelector('dialog')?.remove();const dialog=document.createElement('dialog');dialog.innerHTML=`${button('閉じる','close-dialog','small close')}${html}`;document.body.append(dialog);dialog.addEventListener('click',e=>{if(e.target.closest('[data-action="close-dialog"]'))dialog.close();});dialog.addEventListener('close',()=>dialog.remove());dialog.showModal();}
function journal(){showDialog(`<h2>攻略記録</h2><p class="muted">${current().title} / ${state?.ending?.success?'クリア':'進行記録'}</p>${state?.log.length?state.log.map(l=>`<div class="log-entry"><span class="eyebrow">${String(l.step).padStart(2,'0')} / ${NODES[l.node]}</span><br><strong>${escape(l.action)}</strong><br>P2：${escape(l.support)} ／ ${l.cost}手 ／ 警戒 ${l.trace>0?'+':''}${l.trace}${l.tech?`<br><a href="${techURL(l.tech)}" target="_blank" rel="noopener noreferrer">${l.tech} ${TECHNIQUES[l.tech]?.[0]||''} ↗</a>`:''}</div>`).join(''):'<p>まだ行動していません。</p>'}`);}
function help(){showDialog(`<h2>GHOSTLINEの遊び方</h2><p>① 任務と遊び方を選択。別端末ならP1が部屋を作り、P2が6文字のコードで参加します。</p><p>② P1は入口・対象識別子、P2は経路・原本の特徴を確認。声やメッセージで伝え合ってください。</p><p>③ P1が行動、P2が支援を選びます。P1の「二人で実行」で物語が進みます。同じ端末では上の役割ボタンで切り替えられます。</p><p>④ 目標を達成すると終了。警戒100で封鎖、手数を使い切ると時間切れ。クリアには保全度60以上が必要です。</p><p>「手掛かりを照合」は支援回数を使いません。監視解析や保全には追加の手数と支援回数を使います。</p><p>選んだ手法の<a href="https://attack.mitre.org/" target="_blank" rel="noopener noreferrer">MITRE ATT&CK®</a>との対応と、防ぐ側の考え方を行動後に確認できます。ATT&CKは固定された攻略順序ではなく、攻撃行動を整理する知識ベースです。順序と難易度はゲーム独自の設計です。</p><p class="muted">すべて架空の演習。選択肢はゲーム状態のみを変更します。MITREによる認定・監修を示すものではありません。ATT&CK確認日：2026-09-14。</p>`);}
root.addEventListener('input',e=>{if(e.target.id==='mission-search'){search=e.target.value;document.getElementById('mission-list').innerHTML=missionCards();}if(e.target.id==='room-input')codeInput=e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,'');});
root.addEventListener('click',async e=>{const b=e.target.closest('button[data-action]');if(!b||b.disabled)return;const action=b.dataset.action;
 switch(action){
 case 'difficulty':difficulty=Number(b.dataset.id);search='';render();break;
 case 'mission':selected=Number(b.dataset.id);screen='brief';state=null;render();break;
 case 'mode-local':mode='local';render();break;
 case 'mode-online':mode='online';render();break;
 case 'join-home':selected=1;screen='brief';mode='online';render();break;
 case 'start':start();break;
 case 'role':role=Number(b.dataset.id);render();break;
 case 'vote':if(online()&&!room.online)return;if(myRole()===1&&online()){room.command({kind:'support',value:b.dataset.id,run:state.run,node:state.node,revision:state.revision,step:state.log.length});notice('支援を送信しました。');}else{const oldRole=myRole();if(!online()&&oldRole===0&&!state.votes[1])role=1;change(vote(state,oldRole,b.dataset.id));}break;
 case 'execute':if(host()&&(!online()||room.online))change(execute(state));break;
 case 'advance':if(host()&&(!online()||room.online)){if(!online())role=0;change(advance(state));}break;
 case 'retry':if(host()){state=null;start();}break;
 case 'next-mission':if(host()){selected=Math.min(100,selected+1);state=null;screen='brief';if(online())room.remoteReady=false;broadcast();render();}break;
 case 'home':if(online()||state&&state.phase!=='ended'){showDialog(`<h2>任務一覧へ戻る</h2><p>進行中の任務${online()?'と協力ルーム':''}を終了します。</p><button class="primary" id="confirm-home">一覧へ戻る</button>`);document.getElementById('confirm-home').onclick=async()=>{document.querySelector('dialog')?.close();await leave();state=null;screen='lobby';render();};}else{state=null;screen='lobby';render();}break;
 case 'create-room':await connect(0,roomCode());break;
 case 'join-room':if(!/^[A-Z0-9]{6}$/.test(codeInput)){notice('6文字のルームコードを入力してください。');return;}await connect(1,codeInput);break;
 case 'ready':room.ready=true;room.send({type:'ready',ready:true});render();break;
 case 'invite':try{const url=new URL(location.href);url.search='';url.searchParams.set('room',room.code);await navigator.clipboard.writeText(url.href);notice('招待リンクをコピーしました。');}catch{notice('部屋のコード：'+room.code);}break;
 case 'leave-room':await leave();state=null;screen='brief';render();break;
 case 'reconnect':{const code=room.code;await connect(1,code);break;}
 case 'sound':sound=!sound;beep();render();break;
 case 'fullscreen':await fullscreen();break;
 case 'journal':journal();break;
 case 'help':help();break;
 }
});
window.addEventListener('keydown',e=>{if(e.repeat||e.altKey||e.ctrlKey||e.metaKey||document.querySelector('dialog')||['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;if(screen==='play'&&state.phase==='play'&&['1','2','3'].includes(e.key)){const buttons=root.querySelectorAll('[data-action="vote"]');buttons[Number(e.key)-1]?.click();}if(e.key==='Enter'){root.querySelector('[data-action="execute"]:not(:disabled),[data-action="advance"]:not(:disabled)')?.click();}});
window.addEventListener('beforeunload',()=>room?.close());
let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{const f=root.querySelector('.game-footer');if(f)f.outerHTML=footer();},150);});
setInterval(()=>{if(room?.online){if(room.side===0)broadcast();else if(screen==='brief'&&room.ready)room.send({type:'ready',ready:true});}},3000);
const invitation=new URLSearchParams(location.search).get('room');if(invitation&&/^[A-Z0-9]{6}$/i.test(invitation)){mode='online';screen='brief';codeInput=invitation.toUpperCase();onlineText='招待された部屋のコードを入力済みです。「参加」を押してください。';}
render();
